Ryujinx/Ryujinx

README.md
Ryujinx/OsHle/Ipc/IpcHandler.cs
Ryujinx/OsHle/Objects/AudIAudioOut.cs
Ryujinx/OsHle/Objects/AudIAudioRenderer.cs
Ryujinx/OsHle/Services/ServiceAud.cs

Implement IAudioOut.
Small corrections on AudIAudioRenderer.
Add glitched audio playback support through OpenAL.

Basic audio support

---

Ryujinx/OsHle/Objects/AudIAudioOut.cs

Logging.Warn instead of Logging.Warning

Copy Paste mistake

---

Ryujinx.csproj
Ryujinx/Config.cs

Include Ryujinx.conf file to the build folder.
Fix the Ryujinx.conf filepath.

Config Class bugfix

---

.travis.yml
Ryujinx.csproj

* Build and run on macOS
* Add macOS Travis CI

macOS build

---

Ryujinx/Cpu/Instruction/AInstEmitAluHelper.cs

AInstEmitAluHelper: Simplify EmitSubsCCheck

---

Program.cs
Ryujinx/OsHle/Horizon.cs
Ryujinx/OsHle/Process.cs
Ryujinx/OsHle/Svc/SvcHandler.cs
Ryujinx/OsHle/Svc/SvcSystem.cs
Ryujinx/Switch.cs

implement http://switchbrew.org/index.php?title=SVC#svcExitProcess as application exit to avoid NotImplemented Exception

Gracefully close the app on exit

---

Ryujinx.Tests/Cpu/CpuTestSimdMove.cs
Ryujinx/Cpu/AOpCodeTable.cs
Ryujinx/Cpu/Instruction/AInstEmitSimdMove.cs

Implement Zip1, Zip2

---

Ryujinx/Ui/GLScreen.cs

Changed the vertex positions to
```
(-1, +1, 0)
(+1, +1, 0)
(-1, -1, 0)
(+1, -1, 0)
```
because that made more sense.

Resize display to window size

---

Ryujinx/Config.cs
Ryujinx/Cpu/Translation/AILOpCodeStore.cs
Ryujinx/Hid/HidController.cs
Ryujinx/Hid/JoyCon.cs
Ryujinx/Logging.cs
Ryujinx/OsHle/Handles/HSharedMem.cs
Ryujinx/OsHle/Horizon.cs
Ryujinx/Switch.cs
Ryujinx/VirtualFs.cs

Removes some nesting and adds a little xml documentation

Misc language simplifications

---

Ryujinx/OsHle/Objects/FspSrv/IDirectory.cs
Ryujinx/OsHle/Objects/FspSrv/IFile.cs
Ryujinx/OsHle/Objects/FspSrv/IFileSystem.cs

Lots of FS HLE fixes and implementation of missing functions/objects.

---

README.md

This change is self-explanatory. Someone who is a native English speaker could fix it even more, but I just fixed the most important lines.

Fix various typos in the Readme

---

Ryujinx.Core/Loaders/Executable.cs
Ryujinx.Core/Loaders/Executables/IExecutable.cs
Ryujinx.Core/Loaders/Executables/Nro.cs
Ryujinx.Core/Loaders/Executables/Nso.cs
Ryujinx.Core/OsHle/Homebrew.cs
Ryujinx.Core/OsHle/Objects/Am/ISelfController.cs
Ryujinx.Core/OsHle/Process.cs
Ryujinx.Core/OsHle/Svc/SvcSystem.cs

Implement missing SetScreenShotPermission object.
Implement missing IsCurrentProcessBeingDebugged in SVC.
Add a Extension variable to Executable.
Add basic support of hbmenu.nro.

Initiale hbmenu.nro support

---

Ryujinx.Core/Hid.cs
Ryujinx.Core/Hid/HidTouchScreen.cs
Ryujinx.Core/Switch.cs
Ryujinx/Ui/GLScreen.cs

This implements single tap touchscreen. Tested with libtransistor hid tests. I also fixed the incorrect Hid_Num_Entries constant.
Previous branch had commit errors

Implement single tap touchscreen

---

Ryujinx.Tests/Cpu/CpuTest.cs
Ryujinx.Tests/Cpu/CpuTestAlu.cs
Ryujinx.Tests/Cpu/CpuTestMisc.cs
Ryujinx.Tests/Cpu/CpuTestScalar.cs
Ryujinx.Tests/Cpu/CpuTestSimdMove.cs

~~Added a test control system~~ also in compliance with the Setup and Teardown methods that are called for each new Test or TestCase.
Added six mixed tests.

Review of cpu tests and creation of a class for mixed cpu tests.

---

Ryujinx.Core/OsHle/Services/Vi/IApplicationDisplayService.cs

This passes libtransistor sdl tests.

stub IApplicationDisplayService:CloseDisplay

---

Ryujinx.Core/Logging.cs
Ryujinx.Core/OsHle/Services/Vi/NvFlinger.cs
Ryujinx.Core/PerformanceStatistics.cs
Ryujinx.Core/Switch.cs
Ryujinx/Ui/GLScreen.cs

This implements basic stats, currently only measuring frametime. Using microsecond precision for getting the frametime, and milliseconds for logging. I am hoping to back it up with a profiler when the gui is implemented.

Implement basic performance statistics

---

Ryujinx.Core/OsHle/Services/Bsd/ServiceBsd.cs
Ryujinx.Core/OsHle/Services/ServiceFactory.cs
Ryujinx.Core/OsHle/Utilities/EndianSwap.cs

- Implementation of bsd:s & bsd:u.
- Adding an EndianSwap class.

Implement BSD Service

---

Ryujinx.Core/OsHle/Services/Hid/ServiceHid.cs

for #55 , allows tetris to boot

stub some hid service functions

---

ChocolArm64/Memory/AMemoryHelper.cs
Ryujinx.Audio/AudioFormat.cs
Ryujinx.Audio/IAalOutput.cs
Ryujinx.Audio/OpenAL/OpenALAudioOut.cs
Ryujinx.Audio/PlaybackState.cs
Ryujinx.Audio/Ryujinx.Audio.csproj
Ryujinx.Core/OsHle/Homebrew.cs
Ryujinx.Core/OsHle/Ipc/IpcPtrBuffDesc.cs
Ryujinx.Core/OsHle/ServiceMgr.cs
Ryujinx.Core/OsHle/Services/Aud/AudioOutData.cs
Ryujinx.Core/OsHle/Services/Aud/IAudioDevice.cs
Ryujinx.Core/OsHle/Services/Aud/IAudioOut.cs
Ryujinx.Core/OsHle/Services/Aud/ServiceAudOut.cs
Ryujinx.Core/OsHle/Services/Bsd/ServiceBsd.cs
Ryujinx.Core/OsHle/Services/FspSrv/IFile.cs
Ryujinx.Core/OsHle/Services/Lm/ILogger.cs
Ryujinx.Core/OsHle/Services/Vi/IHOSBinderDriver.cs
Ryujinx.Core/OsHle/Svc/SvcSystem.cs
Ryujinx.Core/Ryujinx.Core.csproj
Ryujinx.Core/Settings/SystemSettings.cs
Ryujinx.Core/Switch.cs
Ryujinx.Core/VirtualFileSystem.cs
Ryujinx.Graphics/Gpu/NsGpuPGraph.cs
Ryujinx/Ryujinx.csproj
Ryujinx/Ui/Program.cs

This is a rewrite of the audout code. This fixes a few issues like ound not working on RetroArch, kgdoom hanging and poor sound output on libnx homebrew.

Improvements to audout

---

Ryujinx.Core/OsHle/Services/Apm/ISession.cs
Ryujinx.Core/OsHle/Services/Apm/PerformanceConfiguration.cs
Ryujinx.Core/OsHle/Services/Apm/PerformanceMode.cs

Stubs getperformanceconfiguration of issesion. Also added enums for performance mode and configuration.

Stub isession:getperformanceconfiguration

---

ChocolArm64/AOpCodeTable.cs
ChocolArm64/Instruction/AInstEmitAlu.cs
ChocolArm64/Instruction/ASoftFallback.cs

Add Cls Instruction.

---

Ryujinx.Core/Config.cs
Ryujinx.Core/Logging.cs
Ryujinx.Core/OsHle/Services/Acc/IAccountServiceForApplication.cs
Ryujinx.Core/OsHle/Services/Acc/IManagerForApplication.cs
Ryujinx.Core/OsHle/Services/Acc/IProfile.cs
Ryujinx.Core/OsHle/Services/Am/IApplicationFunctions.cs
Ryujinx.Core/OsHle/Services/Am/ISelfController.cs
Ryujinx.Core/OsHle/Services/Am/IWindowController.cs
Ryujinx.Core/OsHle/Services/Apm/ISession.cs
Ryujinx.Core/OsHle/Services/Aud/IAudioDeviceService.cs
Ryujinx.Core/OsHle/Services/Aud/IAudioOut.cs
Ryujinx.Core/OsHle/Services/Aud/IAudioRenderer.cs
Ryujinx.Core/OsHle/Services/Aud/IAudioRendererManager.cs
Ryujinx.Core/OsHle/Services/Hid/IHidServer.cs
Ryujinx.Core/OsHle/Services/Nifm/IGeneralService.cs
Ryujinx.Core/OsHle/Services/Nifm/IRequest.cs
Ryujinx.Core/OsHle/Services/Ns/IAddOnContentManager.cs
Ryujinx.Core/OsHle/Services/Set/ISystemSettingsServer.cs
Ryujinx/Ryujinx.conf

This adds a new stub log level, and logs most of the stubs I am familiar with.

Add special log for stubs

---

ChocolArm64/AOpCodeTable.cs
ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs
Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
Ryujinx.Tests/Cpu/Tester/Instructions.cs
Ryujinx.Tests/Cpu/Tester/Pseudocode.cs
Ryujinx.Tests/Cpu/Tester/Types/Bits.cs

Add ABS (scalar & vector), ADD (scalar), NEG (scalar) Tests.
Update Tester as well.

Add ADDHN{2}, RADDHN{2}, SUBHN{2}, RSUBHN{2} (vector) instructions. Add 8 Tests.

---

Ryujinx.Core/OsHle/Services/Am/IAllSystemAppletProxiesService.cs
Ryujinx.Core/OsHle/Services/Am/IApplicationCreator.cs
Ryujinx.Core/OsHle/Services/Am/IGlobalStateController.cs
Ryujinx.Core/OsHle/Services/Am/IHomeMenuFunctions.cs
Ryujinx.Core/OsHle/Services/Am/ISystemAppletProxy.cs
Ryujinx.Core/OsHle/Services/ServiceFactory.cs

Implement:
- IAllSystemAppletProxiesService
- IApplicationCreator
- IGlobalStateController
- IHomeMenuFunctions
* RequestToGetForeground stub.
* GetPopFromGeneralChannelEvent stub event.
- ISystemAppletProxy
* GetCommonStateGetter
* GetSelfController
* GetWindowController
* GetAudioController
* GetDisplayController
* GetLibraryAppletCreator
* GetHomeMenuFunctions
* GetGlobalStateController
* GetApplicationCreator
* GetDebugFunctions

Update am service

---

Ryujinx.Core/LogClass.cs
Ryujinx.Core/OsHle/Services/Am/ICommonStateGetter.cs
Ryujinx.Core/OsHle/Services/Am/ISelfController.cs
Ryujinx.Core/OsHle/Services/Ns/IServiceGetterInterface.cs
Ryujinx.Core/OsHle/Services/Ns/ISystemUpdateInterface.cs
Ryujinx.Core/OsHle/Services/Ns/IVulnerabilityManagerInterface.cs
Ryujinx.Core/OsHle/Services/Prepo/IPrepoService.cs
Ryujinx.Core/OsHle/Services/ServiceFactory.cs
Ryujinx.Core/OsHle/Services/Set/ISettingsServer.cs
Ryujinx.Core/OsHle/Services/Set/ISystemSettingsServer.cs
Ryujinx.Core/OsHle/Services/Vi/IHOSBinderDriver.cs

- ICommonStateGetter
* GetBootMode
- ISelfController
* SetHandlesRequestToDisplay
- IServiceGetterInterface
- ISystemUpdateInterface
- IVulnerabilityManagerInterface
- IPrepoService
- ISettingsServer
* GetLanguageCode
- ISystemSettingsServer
* GetFirmwareVersion2
- IHOSBinderDriver
* TransactParcelAuto

Some implementations

---

ChocolArm64/AOpCodeTable.cs
ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs
ChocolArm64/Translation/ILGeneratorEx.cs
Ryujinx.Tests/Cpu/CpuTest.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs
Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
Ryujinx.Tests/Cpu/Tester/Instructions.cs
Ryujinx.Tests/Cpu/Tester/Pseudocode.cs

Add Sqxtn_S, Sqxtn_V, Uqxtn_S, Uqxtn_V instructions and Tests (6).

---

Ryujinx.Core/OsHle/Services/Vi/IManagerDisplayService.cs
Ryujinx.Core/OsHle/Services/Vi/ISystemDisplayService.cs

Also add some missing PrintStub calls

Implement ISystemDisplayService::GetDisplayMode & Add IManagerDisplayService::SetLayerVisibility stub

---

Ryujinx.Core/OsHle/Diagnostics/Demangle.cs
Ryujinx.Core/OsHle/Diagnostics/Demangler.cs
Ryujinx.Core/OsHle/Process.cs

This is a simple C++ demangler (only supporting name demangling) that will
probably be enough for any stacktrace cases.

Add a C++ demangler

---

Ryujinx.Core/OsHle/Services/Am/IApplicationFunctions.cs
Ryujinx.Core/OsHle/Services/Nv/INvDrvServices.cs
Ryujinx.Core/OsHle/Services/ServiceFactory.cs

Stubs both GetPseudoDeviceId, FinishInitialize and adds more pctl service names.

[IApplicationFunctions/INvDrvServices] Stub GetPseudoDeviceId, FinishInitialize and add more pctl service names.

---

Ryujinx.Core/Logging/LogClass.cs
Ryujinx.Core/OsHle/Ipc/IpcMessage.cs
Ryujinx.Core/OsHle/Services/Acc/IAccountServiceForApplication.cs
Ryujinx.Core/OsHle/Services/Am/IApplicationFunctions.cs
Ryujinx.Core/OsHle/Services/Am/ILibraryAppletAccessor.cs
Ryujinx.Core/OsHle/Services/Am/ILibraryAppletCreator.cs
Ryujinx.Core/OsHle/Services/Am/ISelfController.cs
Ryujinx.Core/OsHle/Services/Am/IStorageAccessor.cs
Ryujinx.Core/OsHle/Services/Am/StorageHelper.cs
Ryujinx.Core/OsHle/Services/Aud/IAudioDevice.cs
Ryujinx.Core/OsHle/Services/FspSrv/IFileSystemProxy.cs
Ryujinx.Core/OsHle/Services/Nfp/IUser.cs
Ryujinx.Core/OsHle/Services/Nfp/IUserManager.cs
Ryujinx.Core/OsHle/Services/Nifm/IStaticService.cs
Ryujinx.Core/OsHle/Services/Nv/INvDrvServices.cs
Ryujinx.Core/OsHle/Services/Nv/NvGpuAS/NvGpuASIoctl.cs
Ryujinx.Core/OsHle/Services/Nv/NvGpuGpu/NvGpuGpuIoctl.cs
Ryujinx.Core/OsHle/Services/Nv/NvHostChannel/NvHostChannelIoctl.cs
Ryujinx.Core/OsHle/Services/Nv/NvHostCtrl/NvHostCtrlIoctl.cs
Ryujinx.Core/OsHle/Services/Nv/NvMap/NvMapIoctl.cs
Ryujinx.Core/OsHle/Services/ServiceFactory.cs

This gets SMO booting to the main menu (that is if you fuck with texture formats)

SMO stubs and implementations

---

Ryujinx.HLE/Hid/Hid.cs

Unsure if this will break other games though.
Please do test. :)

Fix input in SMO

---

Ryujinx.HLE/OsHle/Services/Set/ISettingsServer.cs

Implement GetAvailableLanguageCodes2 with a method

---

Ryujinx.HLE/OsHle/Services/Aud/IAudioOutManager.cs

Implement ListAudioOutsAuto & OpenAudioOutAuto

---

ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs
Ryujinx.Tests/Cpu/Tester/Instructions.cs

Add Sqxtun_S, Sqxtun_V with 3 tests.

---

Ryujinx.Graphics/Gal/OpenGL/OGLStreamBuffer.cs

Fix GL.CreateBuffers -> GL.GenBuffers

---

Ryujinx.HLE/OsHle/Services/ServiceFactory.cs

someone has forgotten to link the mm:u service in ServiceFactory so it's what this PR add

add the forgotten mm:u link

---

ChocolArm64/AOpCodeTable.cs
ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs
ChocolArm64/Instruction/AInstEmitSimdHelper.cs
Ryujinx.Tests/Cpu/CpuTest.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs
Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
Ryujinx.Tests/Cpu/Tester/Instructions.cs

Remove EmitAbd()
Add EmitVectorTernaryOpSx()
Update Tester.
Nits.

Add Saba_V, Sabal_V, Sabd_V, Sabdl_V, Uaba_V, Uabal_V; Update Uabd_V, Uabdl_V. Add 16 tests.

---

ChocolArm64/ChocolArm64.csproj
Ryujinx.Audio/Ryujinx.Audio.csproj
Ryujinx.Graphics/Ryujinx.Graphics.csproj
Ryujinx.HLE/Ryujinx.HLE.csproj
Ryujinx.LLE/Luea.csproj
Ryujinx.ShaderTools/Ryujinx.ShaderTools.csproj
Ryujinx.Tests/Ryujinx.Tests.csproj
Ryujinx/Ryujinx.csproj

Also explicitly set the RID in all the projects

Add linux-x64 to RID property to make tests works on linux

---

Ryujinx.HLE/OsHle/Services/Time/IStaticService.cs
Ryujinx.HLE/OsHle/Services/Time/ISteadyClock.cs
Ryujinx.HLE/OsHle/Services/Time/ISystemClock.cs
Ryujinx.HLE/OsHle/Services/Time/SystemClockType.cs

- Fully implement ISystemClock
- Implement ISteadyClock 1.0 cmds
- Add cmd 300 to IStaticService
- Add EphemeralNetwork to SystemClockType

Some things for time:*

---

ChocolArm64/AOpCodeTable.cs
ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs
ChocolArm64/Instruction/AInstEmitSimdLogical.cs
ChocolArm64/Instruction/ASoftFallback.cs
ChocolArm64/Instruction/AVectorHelper.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs
Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
Ryujinx.Tests/Cpu/Tester/Instructions.cs

Move CountSetBits8() from AVectorHelper to ASoftFallback class.
Update Tester.
Nits.

Add Rbit_V instruction. Add 8 tests (Rbit_V; Rev16_V, Rev32_V, Rev64_V). Improve CountSetBits8() algorithm.

---

Ryujinx.HLE/OsHle/Services/Aud/AudErr.cs
Ryujinx.HLE/OsHle/Services/Aud/IAudioOutManager.cs

This fixes OpenAudioOut forcing the channels count to 2 which is not correct, and also adds error checking to this method. Also fixed formatting.

Improvements to IAudioOutManager

---

ChocolArm64/Memory/AMemory.cs
ChocolArm64/Memory/AMemoryWin32.cs
Ryujinx.HLE/Gpu/Engines/NvGpuEngine3d.cs
Ryujinx.HLE/Gpu/Memory/NvGpuBufferType.cs
Ryujinx.HLE/Gpu/Memory/NvGpuVmm.cs
Ryujinx.HLE/Gpu/Memory/NvGpuVmmCache.cs

Should be faster than calling it once per page.

Query multiple pages at once with GetWriteWatch

---

ChocolArm64/Instruction/AInstEmitSimdCvt.cs
ChocolArm64/Instruction/ASoftFloat.cs
Ryujinx.Tests/Cpu/CpuTestSimdCvt.cs

Test examples from [Wikipedia](https://en.wikipedia.org/wiki/Half-precision_floating-point_format#Half_precision_examples).

AInstEmitSimdCvt: Half-precision to single-precision conversion

---

Ryujinx.Graphics/AGraphicsConfig.cs
Ryujinx.Graphics/Gal/OpenGL/OGLShader.cs
Ryujinx.Graphics/Gal/ShaderDumper.cs
Ryujinx.Graphics/GraphicsConfig.cs
Ryujinx/Config.cs
Ryujinx/Ryujinx.conf

Shader dumps should be compatible with `nvdisasm`.

Add config key to dump shaders in local directory

---

ChocolArm64/Instruction/AInstEmitMemoryEx.cs

For some reason this is taken care of on the normal LDP instruction but I never did the same on the exclusive/atomic version of this instruction. The fix is storing the address into a temp.

Fix LDXP/LDAXP when Rt == Rn

---

Ryujinx.HLE/OsHle/Services/FspSrv/IFileSystem.cs

This deletes the contents of the directory, but not the directory itself.

Implement IFileSystem:CleanDirectoryRecursively

---

Ryujinx.HLE/OsHle/Services/Nifm/IGeneralService.cs

Code is **extremely** shitty, but it correctly performs its intended function!

 Implement GetCurrentIpAddress()

---

Ryujinx.HLE/OsHle/Handles/KThread.cs
Ryujinx.HLE/OsHle/Kernel/AddressArbiter.cs
Ryujinx.HLE/OsHle/Kernel/KernelErr.cs
Ryujinx.HLE/OsHle/Kernel/SvcHandler.cs
Ryujinx.HLE/OsHle/Kernel/SvcSystem.cs
Ryujinx.HLE/OsHle/Kernel/SvcThreadSync.cs

Currently needed by Sonic Mania Plus

Implement SvcWaitForAddress 0x34

---

appveyor.yml

It also add crosscompile for linux and osx. window rid has been changed to win-x64, because we don't only support win10 but any window OS that supports NetCore.

Added appveyor configuration file

---

Ryujinx.HLE/OsHle/Horizon.cs
Ryujinx.HLE/OsHle/Process.cs
Ryujinx.HLE/VirtualFileSystem.cs

This should fix issues on Windows of #272

Fix SystemPathToSwitchPath platform issues and make sure to delete temporary NRO after sessions dispose

---

Ryujinx.HLE/OsHle/Ipc/IpcHandler.cs
Ryujinx.HLE/OsHle/Ipc/IpcMessageType.cs

This PR adds both RequestWithContext and ControlWithContext, but currently does not support token parsing (which is okay for now because we don't need it ATM).

Add 5.0.0 IPCs

---

Ryujinx.HLE/OsHle/Services/Am/ICommonStateGetter.cs
Ryujinx.HLE/OsHle/SystemStateMgr.cs

fix DockedMode variable which is static bool instead of bool

fix toggleable variable in config to set the docked mode

---

ChocolArm64/AOpCodeTable.cs
ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs
Ryujinx.Tests/Cpu/Tester/Instructions.cs

Add Sadalp_V, Saddlp_V, Uadalp_V, Uaddlp_V instructions; add 8 Tests.

---

Ryujinx.HLE/OsHle/Horizon.cs
Ryujinx.HLE/OsHle/Services/Hid/IHidServer.cs

I don't know where this is set, so I implemented it just like the VSync event. It is probably set at the NPadStyleSet methods, but not much is known.

Implement AcquireNpadStyleSetUpdate event

---

Ryujinx.Graphics/Gal/Shader/ShaderDecodeAlu.cs
Ryujinx.Graphics/Gal/Shader/ShaderDecodeMem.cs

- Negative flag bit was wrong for FMUL (and also it doesn't have an abs flag). I used 2 separate methods for FADD/FMUL since they are pretty different.
- Wrong mask was being used on TEXS instruction when one of the registers was ZR. Plus, it would write the color value to a ZR register (ultimately ignoring it).

Fix FMUL and TEXS shader instructions

---

ChocolArm64/AOpCodeTable.cs
ChocolArm64/Instruction/AInstEmitSimdHash.cs
ChocolArm64/Instruction/ASoftFallback.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs
Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
Ryujinx.Tests/Cpu/Tester/Instructions.cs
Ryujinx.Tests/Cpu/Tester/Pseudocode.cs
Ryujinx.Tests/Cpu/Tester/Types/Bits.cs
Ryujinx.Tests/Cpu/Tester/Types/Integer.cs

Test (open box): [sha256-armv8(emu)-master.zip](https://github.com/Ryujinx/Ryujinx/files/2288842/sha256-armv8.emu.-master.zip)
Update Tester.

Add SHA256H, SHA256H2, SHA256SU0, SHA256SU1 instructions; add 4 Tests (closed box).

---

Ryujinx.Graphics/Gal/OpenGL/OGLPipeline.cs

It also adds GL_{UNSIGNED_}_INT_2_10_10_10_REV.

Use signed and unsigned vertex types

---

Ryujinx.HLE/HOS/Kernel/SvcMemory.cs

This fix games like DK Country

SvcSetHeapSize: match kernel check for invalid size

---

Ryujinx.HLE/HOS/Services/Lm/ILogger.cs
Ryujinx.HLE/HOS/Services/Lm/LmLogField.cs

- Manage end of the log packet correctly.
- Add drop count parsing.
- Use the correct buffer type. (0x21 not 0x9)

Improve LM implementation

---

Ryujinx.Graphics/Gal/IGalShader.cs
Ryujinx.Graphics/Gal/OpenGL/OGLShader.cs
Ryujinx.HLE/Gpu/Engines/NvGpuEngine3d.cs

Might help a little on slow drivers.

Avoid querying and setting texture bindings in hot code

---

ChocolArm64/AOpCodeTable.cs
ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs
Ryujinx.Tests/Cpu/CpuTest.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs
Ryujinx.Tests/Cpu/CpuTestSimdCrypto.cs
Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
Ryujinx.Tests/Cpu/Tester/Instructions.cs

Add SHADD, SHSUB, UHSUB, SRHADD, URHADD, instructions; add 12 Tests.

---

Ryujinx.Graphics/Gal/ImageFormatConverter.cs

This was supposed to return false.

Fixup HasColor for depth/stencil values

---

Ryujinx.Graphics/Gal/Shader/GlslDecl.cs
Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs
Ryujinx.Graphics/Gal/Shader/ShaderDecode.cs
Ryujinx.Graphics/Gal/Shader/ShaderDecodeAlu.cs
Ryujinx.Graphics/Gal/Shader/ShaderDecodeFlow.cs
Ryujinx.Graphics/Gal/Shader/ShaderDecodeMem.cs
Ryujinx.Graphics/Gal/Shader/ShaderDecodeMove.cs
Ryujinx.Graphics/Gal/Shader/ShaderDecodeSpecial.cs
Ryujinx.Graphics/Gal/Shader/ShaderDecoder.cs
Ryujinx.Graphics/Gal/Shader/ShaderIrInst.cs
Ryujinx.Graphics/Gal/Shader/ShaderOpCodeTable.cs

This has performance issues on low-end GPUs regardless of their vendor since it includes #368.

Implement SSY/SYNC shader instructions

---

Ryujinx.HLE/Gpu/Engines/NvGpuEngine3d.cs

Some games checks if the timestamp value is non-zero, we need to write something there. The frequency was taken from a game, I'm not sure it is correct. The meaning of the counter field depends on some bits on the control word, it is used to query various counts on the gpu (generated primitives, emitted primitives, etc), currently it is hardcoded to 1.

Improve handling on QueryGet on the gpu

---

KEYS.md
Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/Ryujinx.HLE.csproj
Ryujinx.HLE/Switch.cs
Ryujinx.HLE/VirtualFileSystem.cs
Ryujinx/Ui/Program.cs

Uses [LibHac](https://github.com/Thealexbarney/LibHac) for content file reading.

Add XCI, NSP and NCA loading support

---

Ryujinx.Graphics/Gal/OpenGL/OGLEnumConverter.cs
Ryujinx.Graphics/Gal/OpenGL/OGLTexture.cs
Ryujinx.Graphics/Texture/ImageUtils.cs

Address some reggresions caused by #402.

Fixup image error message and add G8R8 to size query

---

ChocolArm64/AOpCodeTable.cs
ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs
ChocolArm64/Instruction/AInstEmitSimdHelper.cs
ChocolArm64/Instruction/AInstEmitSimdShift.cs
Ryujinx.Tests/Cpu/CpuTest.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs
Ryujinx.Tests/Cpu/CpuTestSimdIns.cs
Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
Ryujinx.Tests/Cpu/CpuTestSimdShImm.cs

**Instruction fixed:**
Sqrshrn_V
**Instructions added:**
Rshrn_V
Sqrshrn_S
Sqrshrun_S, Sqrshrun_V
Sqshrn_S, Sqshrn_V
Sqshrun_S, Sqshrun_V
Uqrshrn_S, Uqrshrn_V
Uqshrn_S, Uqshrn_V
**Tests added:**
Shrn_V
Rshrn_V
Sqrshrn_S, Sqrshrn_S
Sqrshrun_S, Sqrshrun_V
Sqshrn_S, Sqshrn_V
Sqshrun_S, Sqshrun_V
Uqrshrn_S, Uqrshrn_V
Uqshrn_S, Uqshrn_V

Fix/Add 1+12 [Saturating] [Rounded] Shift Right Narrow (imm.) Instructions; add 14 Tests. Add 6 Tests for PR#405. Add 2 Tests for PR#412.

---

Ryujinx.Audio/OpenAL/OpenALAudioOut.cs

This seems to only affect libnx homebrew, using SDL2 in a very specific way (using `Mix_OpenAudio `). I simplified OpenALAudioOut, made the methods thread safe, and also modified it to ensure that after the event is fired, it will always have buffers available to return through GetReleasedBuffers. This was not happening before because when playback is (re)started, OpenAL will zero all counts, so no buffers were returned.

Ensure that the audout event is fired only when there are buffers available

---

Ryujinx.Graphics/Gal/GalPipelineState.cs
Ryujinx.Graphics/Gal/OpenGL/OGLPipeline.cs
Ryujinx.Graphics/Gal/OpenGL/OGLRasterizer.cs
Ryujinx.Graphics/NvGpuEngine3d.cs
Ryujinx.Graphics/NvGpuEngine3dReg.cs
Ryujinx.Graphics/Texture/ImageUtils.cs

I couldn't use GalPipelineState here because glClear* requires glDepthMask to be true

Implement DepthWriteMask and add R16G16

---

Ryujinx.HLE/HOS/Services/Hid/HidNpad.cs
Ryujinx.HLE/HOS/Services/Hid/HidSixAxis.cs
Ryujinx.HLE/HOS/Services/Hid/HidVibration.cs
Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs

Since we can't support all those Hid calls in the right way, we can stub them with more information as possible in the logs.
I have added all symbols in it to be more revelant as possible.
It's remove some Hid spam in few games too, because we assign some var as the game want.

Full 5.X stubbed IHidServer

---

ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs
ChocolArm64/Instruction/AInstEmitSimdCmp.cs
ChocolArm64/Instruction/AInstEmitSimdCvt.cs
ChocolArm64/Instruction/AInstEmitSimdHelper.cs
ChocolArm64/Instruction/AInstEmitSimdLogical.cs
ChocolArm64/Instruction/AInstEmitSimdMove.cs
ChocolArm64/Instruction/AVectorHelper.cs
ChocolArm64/Memory/AMemory.cs

Didn't notice any performance difference on the few games I tested.
Most of those instructions are not tested because currently there are no tests for them on Ryujinx.Tests.

Optimize BIC, BSL, BIT, BIF, XTN, ZIP, DUP (Gp), FMADD (Scalar) and FCVT (Scalar) using SSE intrinsics

---

Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/Ryujinx.HLE.csproj
Ryujinx/Config.cs
Ryujinx/Ryujinx.conf

Open patched games if opening an XCI with a patch
Update to LibHac 0.1.2
Enable RomFS validation
Allow loading an NCA without a RomFS

Misc content loading improvements

---

Ryujinx.HLE/HOS/Services/Ssl/ISslContext.cs
Ryujinx.HLE/HOS/Services/Ssl/ISslService.cs

This PR implement an empty `ISslContext` and update `CreateContext` and `SetInterfaceVersion` inside `ISslService`

Implement ISslContext

---

Ryujinx.HLE/HOS/Services/Am/ISelfController.cs
Ryujinx.HLE/HOS/Services/Aud/AudioRenderer/IAudioRenderer.cs
Ryujinx.HLE/HOS/Services/Aud/IAudioRendererManager.cs
Ryujinx.HLE/HOS/Services/Irs/IIrSensorServer.cs
Ryujinx.HLE/HOS/Services/Mm/IRequest.cs
Ryujinx.HLE/HOS/Services/ServiceFactory.cs
Ryujinx.HLE/Logging/LogClass.cs

Stubs Again

---

Ryujinx.HLE/HOS/Services/Sfdnsres/GaiError.cs
Ryujinx.HLE/HOS/Services/Sfdnsres/IResolver.cs
Ryujinx.HLE/HOS/Services/Sfdnsres/NetDBError.cs

- GetAddrInfo & GetNameInfo still need to be implemented.

Implement IResolver

---

Ryujinx.HLE/HOS/Services/Acc/IAccountService.cs
Ryujinx.HLE/HOS/Services/Acc/IManagerForApplication.cs

`IAccountService`:
- Add symbols.
- Fix some mistake.
- Add `IsUserRegistrationRequestPermitted` and `TrySelectUserWithoutInteraction`.
`IManagerForApplication`:
- Add symbols.
- Add Uuid args.
- Little improvement of `GetAccountId`

Update IAccountService and IManagerForApplication

---

Ryujinx.HLE/HOS/Services/Acc/IAccountService.cs
Ryujinx.HLE/Utilities/UInt128.cs

Fix WriteUserList function as it writes the values in the wrong order.
Also clean up some unused variables in UInt128 and fix a code style issue.

Fix some issues with UserId

---

Ryujinx.HLE/FileSystem/SaveHelper.cs
Ryujinx.HLE/HOS/Diagnostics/Demangler/Ast/CallExpression.cs
Ryujinx.HLE/HOS/Diagnostics/Demangler/Ast/CasExpression.cs
Ryujinx.HLE/HOS/Diagnostics/Demangler/Ast/CastExpression.cs
Ryujinx.HLE/HOS/Diagnostics/Demangler/Ast/InitListExpression.cs
Ryujinx.HLE/HOS/Diagnostics/Demangler/Ast/NodeArray.cs
Ryujinx.HLE/HOS/Diagnostics/Demangler/Ast/TemplateArguments.cs
Ryujinx.HLE/HOS/Services/Aud/IAudioRendererManager.cs
Ryujinx.HLE/HOS/Services/Irs/IIrSensorServer.cs
Ryujinx.HLE/HOS/Services/Mm/IRequest.cs
Ryujinx.HLE/Utilities/UInt128.cs
Ryujinx.Tests.Unicorn/MemoryPermission.cs
Ryujinx.Tests.Unicorn/Native/ArmRegister.cs
Ryujinx.Tests.Unicorn/Native/Interface.cs
Ryujinx.Tests.Unicorn/Native/UnicornArch.cs
Ryujinx.Tests.Unicorn/Native/UnicornMode.cs
Ryujinx.Tests.Unicorn/UnicornAArch64.cs
Ryujinx.Tests.Unicorn/UnicornError.cs
Ryujinx.Tests/Cpu/CpuTestSimdArithmetic.cs

Could be avoided if people took the time to configure their IDEs.

Remove unnecessary usings

---

Ryujinx.Common/Logging/LogClass.cs
Ryujinx.HLE/HOS/Services/Psm/IPsmServer.cs
Ryujinx.HLE/HOS/Services/Psm/IPsmSession.cs
Ryujinx.HLE/HOS/Services/ServiceFactory.cs

- Add `IPsmServer`
- Stub `GetBatteryChargePercentage` & `GetChargerType`

Implement basic psm service

---

Ryujinx.HLE/Hid/Hid.cs

This fix some issues on some homebrews.

hid: Implement KEY_RSTICK_* & KEY_LSTICK_*

---

Ryujinx.Graphics/Gal/OpenGL/OGLEnumConverter.cs

Add BGRA8 Srgb, need for Unreal Engine 4 games

Add BGRA8 Srgb

---

Ryujinx.Graphics/Gal/OpenGL/OGLEnumConverter.cs
Ryujinx.Graphics/Texture/ImageUtils.cs

Need for https://github.com/Ryujinx/Ryujinx-Games-List/issues/84

Add RGBA16 Unorm

---

Ryujinx.HLE/Input/Hid.cs
Ryujinx.HLE/Input/HidNpadController.cs
Ryujinx.HLE/Input/HidProController.cs
Ryujinx/Ui/GLScreen.cs

I omitted writing to main layout during the refactor. which broke homebrew input. also add the joystick fix that got lost.

Fix homebrew input

---

CONFIG.md
README.md

This PR I feel like is long overdue, this attempts to update the Readme with accurate information!
I will probably also be attempting to update the website as well, a lot of that information is outdated too.
Feedback is appreciated!
EDIT: You can find the Website PR here: https://github.com/Ryujinx/Ryujinx-Website/pull/2

Update the Readme

---

Ryujinx.HLE/Loaders/Executables/NxStaticObject.cs

Avoid trying to decompress something that doesn't exist

Fix issues with compressed NSO without a section

---

Ryujinx.HLE/HOS/Services/FspSrv/IFileSystemProxy.cs

Fix wrong contenttype used

---

Ryujinx.Graphics/Graphics3d/NvGpuEngine3d.cs

Fixes the out of bounds exception during SNK boot mentioned here: https://github.com/Ryujinx/Ryujinx-Games-List/issues/140
~~You will also need this commit as listed in the original issue: https://github.com/Ryujinx/Ryujinx/commit/1fe2b366bad03f8676d7914b63e94c167a836f67~~
To test constant attributes still work you can use the demo application I made here along with SNK: https://github.com/BaronKiko/Ryujinx-OGL-Demos/releases/tag/cont_attrib
Precompiled and source code there.

SNK 40th Anniversary Out of Bounds Fix

---

Ryujinx.HLE/HOS/Horizon.cs
Ryujinx/Program.cs

Add support of PFS0 as ExeFS

---

Ryujinx.Graphics/Gal/OpenGL/OGLPipeline.cs
Ryujinx.Graphics/Gal/OpenGL/OGLRenderTarget.cs
Ryujinx.Graphics/Graphics3d/NvGpuEngine3d.cs

Fixes cave story+ rendering issues as detailed in this bug https://github.com/Ryujinx/Ryujinx/issues/562 for me, please test on AMD.

Scissor test fix

---

Ryujinx.HLE/FileSystem/FileSystemProvider.cs
Ryujinx.HLE/FileSystem/IFileSystemProvider.cs
Ryujinx.HLE/FileSystem/PFsProvider.cs
Ryujinx.HLE/FileSystem/RomFsProvider.cs
Ryujinx.HLE/HOS/HomebrewRomFs.cs
Ryujinx.HLE/HOS/HomebrewRomFsStream.cs
Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcMemory.cs
Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcTable.cs
Ryujinx.HLE/HOS/Services/FspSrv/FileTimestamp.cs
Ryujinx.HLE/HOS/Services/FspSrv/IFileSystem.cs
Ryujinx.HLE/HOS/Services/Ns/IApplicationManagerInterface.cs
Ryujinx.HLE/HOS/Services/Ns/IServiceGetterInterface.cs
Ryujinx.HLE/HOS/Services/Pm/IShellInterface.cs
Ryujinx.HLE/HOS/Services/ServiceFactory.cs
Ryujinx.HLE/HOS/Services/Sm/IUserInterface.cs
Ryujinx.HLE/HOS/Services/Sm/SmErr.cs
Ryujinx.HLE/Loaders/Executables/NxRelocatableObject.cs

This PR makes HBL working inside Ryujinx.
It also add back the RomFS support for NROs and fix other errors related to homebrew loading.

Support HomeBrew Loader

---

Ryujinx.Graphics/Gal/OpenGL/OGLPipeline.cs
Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs
Ryujinx.Graphics/Gal/Shader/ShaderDecodeAlu.cs
Ryujinx.Graphics/Gal/Shader/ShaderDecodeOpCode.cs

Some games needs face culling to render correctly. I know it caused issues with some games (not rendering) on the past, but ignoring it also causes issues, so... I think it's better to just enable it, and try fixing any possible issues arising from it later.

Fix XMAD shader instruction, gl_FrontFacing and enable face culling

---

Ryujinx/Program.cs

Added "ROM not found." message if specified file is invalid.

---

Ryujinx.Tests/Cpu/CpuTestMisc.cs

Add Tests for adds/cmn & subs/cmp with condition check.

---

ChocolArm64/Decoders/OpCodeSimdCvt64.cs
ChocolArm64/Instructions/InstEmitSimdCvt.cs
ChocolArm64/OpCodeTable.cs

fyi @LDj3SNuD.
Needs unit tests.
Closes #594

Implement fixed-point variant of the UCVTF and SCVTF instructions

---

ChocolArm64/Instructions/InstEmitBfm.cs

The ARM manual lists 2 alias insts for BFM, BFXIL and BFI. The first one being Bitfield Extract and Insert into Low Bits, and the second one being Bitfield Insert (from low bits into any position at the destination). So, rather than generating code for the BFM instruction, which is a bit more complex, check which variant of the instruction it is (BFXIL or BFI), and generate simpler code depending on the variant.
Shows some small codegen improvements, BFM tests are still passing.

Optmize BFM instruction

---

Ryujinx.HLE/FileSystem/Content/LocationHelper.cs

Reuse basePath variable in LocationHelper

---

ChocolArm64/Instructions/InstEmitSimdArithmetic.cs
ChocolArm64/Instructions/InstEmitSimdCmp.cs
ChocolArm64/Instructions/InstEmitSimdCvt.cs
ChocolArm64/Instructions/InstEmitSimdHelper.cs
ChocolArm64/Instructions/InstEmitSimdLogical.cs
ChocolArm64/Instructions/InstEmitSimdShift.cs
ChocolArm64/Translation/ILEmitterCtx.cs
Ryujinx.Common/Utilities/BitUtils.cs
Ryujinx.Tests/Cpu/CpuTestSimdArithmetic.cs
Ryujinx.Tests/Cpu/CpuTestSimdExt.cs
Ryujinx.Tests/Cpu/CpuTestSimdIns.cs
Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
Ryujinx.Tests/Cpu/CpuTestSimdShImm.cs
Ryujinx.Tests/Ryujinx.Tests.csproj

Add "Part" & "Shift" opt.
Remove EmitLdvectmp2() & EmitStvectmp2()
Remove .Dup
Remove "Tmp" stuff

Add Rshrn_V & Shrn_V Sse opt.. Add Mla_V, Mls_V & Mul_V Sse opt.; add Tests.

---

Ryujinx.Graphics/Gal/OpenGL/OglTexture.cs

Adds support for cube map arrays, all there is to it.

Cube map array support

---

ChocolArm64/Instructions/InstEmitSimdArithmetic.cs
ChocolArm64/Instructions/InstEmitSimdCmp.cs
ChocolArm64/Instructions/InstEmitSimdHelper.cs
ChocolArm64/Instructions/InstEmitSimdLogical.cs
ChocolArm64/Translation/ILEmitterCtx.cs

Add Cmeq_V, Cmge_V, Cmgt_V, Cmle_V & Cmlt_V (Z & ~Z) Sse opt..

---

Ryujinx.HLE/HOS/Services/Irs/IIrSensorServer.cs

Based on RE here: https://gist.github.com/AcK77/20220f58c445bdfb3f97c9fd438de0ea
Resolves #618

Implement IIrSensorServer GetNpadIrCameraHandle

---

Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Services/Irs/IIrSensorServer.cs
Ryujinx.HLE/HOS/Services/ServiceFactory.cs

Implement IIrSensorServer GetIrsensorSharedMemoryHandle

---

Ryujinx.HLE/Input/HidHotkeyButtons.cs
Ryujinx/Config.jsonc
Ryujinx/Ui/GLScreen.cs
Ryujinx/Ui/NpadKeyboard.cs
Ryujinx/_schema.json

Allows you to enable and disable vsync at runtime with the a specified hotkey, tab by default.

Toggle VSync Hotkey

---

Ryujinx.HLE/HOS/Services/Pctl/IParentalControlService.cs

Implement IParentalControlService CheckFreeCommunicationPermission

---

Ryujinx.HLE/HOS/Services/Friend/IFriendService.cs
Ryujinx.HLE/HOS/Services/Irs/IIrSensorServer.cs
Ryujinx.HLE/HOS/Services/Nv/INvDrvServices.cs

Rework, was make broken old pr: https://github.com/Ryujinx/Ryujinx/pull/653
Add:
Closes #644, closes #619 and closes #634

Add some HOS service

---

Ryujinx.HLE/HOS/Services/Vi/IApplicationDisplayService.cs
Ryujinx.HLE/HOS/Services/Vi/IManagerDisplayService.cs

Add IManagerDisplayService::CreateStrayLayer

---

Ryujinx.HLE/HOS/Services/Nv/INvDrvServices.cs
Ryujinx/Config.jsonc

Extended ignore missing services to INvDrvServices

---

Ryujinx/_schema.json

Added missing bracket in _schema.json

---

ChocolArm64/Instructions/InstEmitSimdArithmetic.cs
ChocolArm64/Instructions/InstEmitSimdHelper.cs
ChocolArm64/OpCodeTable.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs

Tests:
```
Total tests: 11600. Passed: 11600. Failed: 0. Skipped: 0.
Test execution was successful.
Test execution time: 1.6604 Minutes
```
Closes https://github.com/Ryujinx/Ryujinx/issues/690

Add Smaxv_V, Sminv_V, Umaxv_V, Uminv_V Inst.; add Tests.

---

ChocolArm64/Instructions/InstEmitSimdCvt.cs
ChocolArm64/OpCodeTable.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs

Fixes https://github.com/Ryujinx/Ryujinx/pull/691#issuecomment-496109657

Add FCVT <Hd>, <Sn> and FCVT <Sd>, <Hn> Inst.; add Tests.

---

Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Services/FspSrv/IFile.cs
Ryujinx.HLE/HOS/Services/FspSrv/IFileSystem.cs
Ryujinx.HLE/Ryujinx.HLE.csproj

Updates the IFile Read and Write methods to honor any specified ReadOption and WriteOption

Update to LibHac 0.4.1

---

Ryujinx.Tests/Cpu/CpuTestAlu.cs
Ryujinx.Tests/Cpu/CpuTestMov.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs

Add const for random numbers for the test category `Mov`.

Implement a custom value generator for the Tests of the CLS and CLZ instructions (Base: 32, 64 bits. Simd: 8, 16, 32 bits).

---

Ryujinx.HLE/HOS/Services/Acc/AccErr.cs
Ryujinx.HLE/HOS/Services/Acc/Account/AccountState.cs
Ryujinx.HLE/HOS/Services/Acc/Account/AccountUtils.cs
Ryujinx.HLE/HOS/Services/Acc/Account/UserProfile.cs
Ryujinx.HLE/HOS/Services/Acc/IAccountService.cs
Ryujinx.HLE/HOS/Services/Acc/IManagerForApplication.cs
Ryujinx.HLE/HOS/Services/Acc/IProfile.cs
Ryujinx.HLE/HOS/Services/Arp/ApplicationLaunchProperty.cs
Ryujinx.HLE/HOS/Services/Friend/IFriendService.cs
Ryujinx.HLE/HOS/SystemState/SystemStateMgr.cs
Ryujinx.HLE/Utilities/UInt128.cs

- Move all account things to the account service
- More accurate IAccountServiceForApplication
- Add helper to UInt128

Refactoring of acc:u0

---

Ryujinx.HLE/HOS/Services/Set/ISettingsServer.cs
Ryujinx.HLE/HOS/Services/Set/SettingsError.cs

This PR fix GetAvailableLanguageCodes* implementations and add some new commands (MakeLanguageCode, GetAvailableLanguageCodeCount2, and GetQuestFlag).
This fix #631

set: Improve implementation

---

Ryujinx.HLE/HOS/Services/Friend/IDaemonSuspendSessionService.cs
Ryujinx.HLE/HOS/Services/Friend/INotificationService.cs
Ryujinx.HLE/HOS/Services/Friend/IServiceCreator.cs

- Add INotificationService (close #621)
- Add IDaemonSuspendSessionService

friends: Implementation of IServiceCreator

---

Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Services/Time/IStaticService.cs

- Implement Time SharedMemory (because the code is the same, reference to #672)
- Implement GetSharedMemoryNativeHandle (close #616)
- Cleanup IStaticService

time: Implement GetSharedMemoryNativeHandle

---

Ryujinx.HLE/HOS/Services/Hid/HidUtils.cs
Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs
Ryujinx.HLE/HOS/Services/Hid/Irs/IrsError.cs
Ryujinx.HLE/HOS/Services/Hid/NpadIdType.cs
Ryujinx.HLE/HOS/Services/ServiceFactory.cs

Based on:
- #663 and #664 as references.
- Some RE from here: https://gist.github.com/AcK77/20220f58c445bdfb3f97c9fd438de0ea

irs: Little service cleanup

---

Ryujinx.HLE/FileSystem/Content/ContentManager.cs
Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Services/Time/ITimeZoneService.cs
Ryujinx.HLE/HOS/Services/Time/ITimeZoneServiceTypes.cs
Ryujinx.HLE/HOS/Services/Time/TimeError.cs
Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZone.cs
Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZoneManager.cs
Ryujinx.HLE/Ryujinx.HLE.csproj
Ryujinx.HLE/Utilities/StreamUtils.cs
Ryujinx.HLE/Utilities/StringUtils.cs

It was about time, wasn't it?
This PR adds an accurate implementation of the timezone logic found in the PCV sysmodule.

ITimeZoneService rewrite

---

ChocolArm64/Instructions/InstEmitSimdArithmetic.cs
ChocolArm64/Instructions/InstEmitSimdHelper.cs
ChocolArm64/OpCodeTable.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs
Ryujinx.Tests/Cpu/CpuTestSimdCvt.cs
Ryujinx.Tests/Cpu/CpuTestSimdIns.cs
Ryujinx.Tests/Ryujinx.Tests.csproj

Update `Ryujinx.Tests.csproj` Package References.
Nits.

Add Saddlv_V Inst. Improve Cnt_V, Dup_Gp & Ins_Gp Tests. Tuneup Cls_V & Clz_V Tests.

---

Ryujinx.HLE/HOS/Services/Bsd/IClient.cs

Fix a copy pasta from the past 💯

Fix bsd recvfrom implementation

---

Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Services/Bpc/IRtcManager.cs
Ryujinx.HLE/HOS/Services/Time/Clock/ClockTypes.cs
Ryujinx.HLE/HOS/Services/Time/Clock/StandardNetworkSystemClockCore.cs
Ryujinx.HLE/HOS/Services/Time/Clock/SteadyClockCore.cs
Ryujinx.HLE/HOS/Services/Time/IStaticService.cs
Ryujinx.HLE/HOS/Services/Time/ISteadyClock.cs
Ryujinx.HLE/HOS/Services/Time/ISystemClock.cs

Also implement bpc:r as a result of 2.0.0 changes.
Close #682

Implement time:* 2.0.0 & 3.0.0 commands

---

Ryujinx.Graphics/Graphics3d/Texture/ImageUtils.cs

A little adding for missing Rgba16Uint
- Close issue: https://github.com/Ryujinx/Ryujinx/issues/745

Add Rgba16Uint

---

Ryujinx.HLE/HOS/Services/FspSrv/IFileSystemProxy.cs

Implement OpenReadOnlySaveDataFileSystem

---

Ryujinx.HLE/HOS/Services/Acc/IAccountService.cs
Ryujinx.HLE/HOS/Services/Nifm/GeneralServiceDetail.cs
Ryujinx.HLE/HOS/Services/Nifm/GeneralServiceManager.cs
Ryujinx.HLE/HOS/Services/Nifm/IGeneralService.cs
Ryujinx.HLE/HOS/Services/Nifm/IRequest.cs
Ryujinx.HLE/HOS/Services/Nifm/IStaticService.cs
Ryujinx.HLE/HOS/Services/Nifm/ResultCode.cs

- Add nifm:a and nifm:u with a max sessions as comment since sm don't take care of sessions for now.
- Implement IGeneralService GetClientId based on RE (close #623).
- Implement IGeneralService IsAnyInternetRequestAccepted based on RE (close #624).
- Add some informations in IGeneralService CreateRequest.
- Fix a comment in IAccountService.

IGeneralService Implement GetClientId and IsAnyInternetRequestAccepted

---

Ryujinx.HLE/Ryujinx.HLE.csproj

Brings in a bugfix for the `EnsureDirectoryExists` functions

Update to LibHac 0.5.1

---

Ryujinx.Common/Logging/Logger.cs
Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcTable.cs
Ryujinx/Ui/MainWindow.cs

**Fixes:**
- A null reference exception on exit if Discord integration is not enabled
- Not having a logger reference time set to 0 if the execution times of the launcher and the title do not match
- The incorrect build up of debug strings for some services, like `GetCurrentProcessorNumber6`
Nits.

Misc fixes

---

Ryujinx.Common/Utilities/BitUtils.cs
Ryujinx.Common/Utilities/EndianSwap.cs
Ryujinx.HLE/HOS/Font/SharedFontManager.cs
Ryujinx.HLE/HOS/Services/Audio/HardwareOpusDecoderManager/IHardwareOpusDecoder.cs
Ryujinx.HLE/HOS/Services/Audio/Types/OpusPacketHeader.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs

Also implement new variants of this api.
This should fix #763

Fix hwopus DecodeInterleaved implementation

---

Ryujinx.HLE/FileSystem/Content/ContentManager.cs
Ryujinx.HLE/FileSystem/Content/LocationEntry.cs
Ryujinx.HLE/FileSystem/SaveHelper.cs
Ryujinx.HLE/HOS/Font/SharedFontManager.cs
Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/FileSystemProxyHelper.cs
Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IDirectory.cs
Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IFile.cs
Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IFileSystem.cs
Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IStorage.cs
Ryujinx.HLE/HOS/Services/Fs/IDeviceOperator.cs
Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
Ryujinx.HLE/HOS/Services/Ncm/Lr/LocationResolverManager/ILocationResolver.cs
Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs
Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZoneContentManager.cs
Ryujinx.HLE/Ryujinx.HLE.csproj
Ryujinx/Configuration.cs
Ryujinx/Ui/ApplicationLibrary.cs

- Adjust APIs to match Nintendo's more closely
- `Result` is used in more places instead of exceptions
- Adds a basic FS service

Update to LibHac 0.6.0

---

Ryujinx.HLE/HOS/Services/Nifm/StaticService/IGeneralService.cs
Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/InternetConnectionState.cs
Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/InternetConnectionStatus.cs
Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/InternetConnectionType.cs
Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs

This implement GetSettingsItemValueSize (required by hbl) and
GetInternetConnectionStatus (required by hb-menu).

Fix latest version of hbl/hb-menu

---

Ryujinx.HLE/HOS/Services/Loader/ResultCode.cs
Ryujinx.HLE/HOS/Services/Ro/IRoInterface.cs
Ryujinx.HLE/HOS/Services/Ro/ResultCode.cs
Ryujinx.HLE/HOS/Services/Ro/Types/NroInfo.cs
Ryujinx.HLE/HOS/Services/Ro/Types/NrrHeader.cs
Ryujinx.HLE/HOS/Services/Ro/Types/NrrInfo.cs

This commit contains a little rewrite of IRoInterface to fix some issues
that we were facing on some recent games (AC3 Remastered & Final Fantasy
VIII Remastered)
Also move IRoInterface to the RO module.
Related issues:
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/196

Improve IRoInterface logic

---

Ryujinx.HLE/HOS/Applets/AppletManager.cs
Ryujinx.HLE/HOS/Applets/IApplet.cs
Ryujinx.HLE/HOS/Applets/PlayerSelect/PlayerSelectApplet.cs
Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardConfig.cs
Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardState.cs
Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardType.cs
Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/LibraryAppletCreator/ILibraryAppletAccessor.cs
Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ILibraryAppletCreator.cs
Ryujinx.HLE/HOS/Services/Am/AppletAE/AppletFifo.cs
Ryujinx.HLE/HOS/Services/Am/AppletAE/AppletSession.cs
Ryujinx.HLE/HOS/Services/Am/AppletAE/IAppletFifo.cs
Ryujinx.HLE/HOS/Services/Am/AppletAE/IStorageAccessor.cs
Ryujinx.HLE/HOS/Services/Am/ResultCode.cs

Currently only implements the full screen keyboard, inline keyboard will come later. We also assume that the full screen keyboard always accepts UTF-16 text, even though the inline keyboard has a flag to indicate what encoding to write text in.

Initial swkbd implementation

---

Ryujinx.HLE/HOS/Services/Ro/IRoInterface.cs
Ryujinx.HLE/HOS/Services/Ro/ResultCode.cs

This fix some regressions caused by #809 .

Fix issues on ro implementation

---

Ryujinx.HLE/HOS/Services/Time/IStaticServiceForPsc.cs

Little mistakes found by @gdkchan oops

Fix wrong buffer usage in time

---

Ryujinx.HLE/HOS/Services/Prepo/IPrepoService.cs

Due to a guessed parsing implementation of the report, sometime it throw an error, since the data isn't really useful, it's better to silent possible exceptions with a message.

prepo: Silent error while parsing report

---

ARMeilleure/Decoders/Decoder.cs

This was causing OOM in some specific cases.

Add a limit for the number of instructions in a function

---

Ryujinx/Ryujinx.csproj
Ryujinx/Ui/GameTableContextMenu.cs
Ryujinx/Ui/GameTableContextMenu.glade
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/MainWindow.glade

GUI: Implement context menu for the game table

---

Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs

This add some code to handle usage of poll without any fds.
This is required by Dark Souls Remastered main loop logic as it's
calling it without any fds during initialization.
This fix #754 
===

Fix an edge case in bsd IClient::Poll implementation

---

Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IStorage.cs

Fix LibHac.IStorage not being disposed in FileSystem proxy

---

Ryujinx.HLE/HOS/Horizon.cs

Fix GUI freeze wehn closing without any emulation running

---

Ryujinx.Graphics.OpenGL/FormatTable.cs
Ryujinx.HLE/HOS/Services/SurfaceFlinger/NvFlinger.cs

Also fix B5G6R5Unorm wrong definition in Ryujinx.Graphics.OpenGL.

Fix R5G6B5 in SurfaceFlinger

---

README.md

Correct inaccuracy in readme

---

Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/NvHostAsGpuDeviceFile.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/Types/AddressSpaceContext.cs

MapBufferEx: take page size into account

---

Ryujinx/Ui/ApplicationLibrary.cs
Ryujinx/Ui/ApplicationMetadata.cs
Ryujinx/Ui/MainWindow.cs

Just cleaning up some duplicated code, in preparation of simplifying Json saving and loading in the whole application.

Get rid of code duplication

---

Ryujinx/Ui/AboutInfo.cs
Ryujinx/Ui/AboutWindow.cs

Just cleaning up some code, this struct was unused.
Verified with @Xpl0itR 
One step closer to https://github.com/Ryujinx/Ryujinx/issues/879

Get rid of unused class AboutInfo

---

Ryujinx.HLE/FileSystem/Content/ContentManager.cs

This fix a race condition happening since #791 when trying to load a
game via command line.

Fix race condition in ContentManager

---

ARMeilleure/Translation/Translator.cs
Ryujinx.Audio/Renderers/OpenAL/OpenALAudioOut.cs
Ryujinx.Common/Logging/Formatters/DefaultLogFormatter.cs
Ryujinx.Common/Logging/LogEventArgs.cs
Ryujinx.Common/Logging/Logger.cs
Ryujinx.Common/Logging/Targets/AsyncLogTargetWrapper.cs
Ryujinx.HLE/HOS/Kernel/Common/KTimeManager.cs
Ryujinx.HLE/HOS/Kernel/Threading/HleScheduler.cs
Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs
Ryujinx.Profiler/InternalProfile.cs
Ryujinx.Profiler/UI/ProfileWindowManager.cs
Ryujinx/Ui/GLScreen.cs
Ryujinx/Ui/MainWindow.cs

Name all threads

---

Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/IAudioRenderer.cs
Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/Types/UpdateDataHeader.cs
Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/VoiceContext.cs

- Fixes a typo
- Removes an unused variable
- Removes a redundant modulo operation

Various small audren fixes

---

Ryujinx.Graphics.Gpu/GpuContext.cs
Ryujinx.HLE/FileSystem/Content/ContentManager.cs
Ryujinx.HLE/FileSystem/StorageId.cs
Ryujinx.HLE/FileSystem/VirtualFileSystem.cs
Ryujinx.HLE/HOS/Font/SharedFontManager.cs
Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
Ryujinx.HLE/HOS/Services/Sdb/Pl/ISharedFontManager.cs
Ryujinx.HLE/Switch.cs
Ryujinx/Configuration/DiscordIntegrationModule.cs
Ryujinx/Program.cs
Ryujinx/Ui/ApplicationLibrary.cs
Ryujinx/Ui/GLScreen.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/Migration.cs

Still alive! 🍰 
Make HLE.Switch initialize when starting a game and dispose it when closing the GlScreen.
This also make HLE in charge of disposing the audio and gpu backend.
PS: I'm making a note here; "Huge success"

Keep the GUI alive when closing a game

---

Ryujinx.HLE/FileSystem/VirtualFileSystem.cs
Ryujinx/Ui/ApplicationLibrary.cs
Ryujinx/Ui/GameTableContextMenu.cs
Ryujinx/Ui/MainWindow.cs

This fix a regression caused by #888 on temporary saves for SNES Online.
(and probably other games)

Make VirtualFileSystem only instantiable once

---

Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/FileSystemProxyHelper.cs

Fix OpenBisFileSystem wrong buffer type

---

Ryujinx.HLE/HOS/Services/Prepo/IPrepoService.cs
Ryujinx.HLE/Ryujinx.HLE.csproj

I've found they use msgpack for the report, so I've added a nuget package and deserialize the report in the right way.
Close #838

prepo IPrepoService accurate parsing for report

---

Ryujinx.HLE/HOS/Ipc/IpcHandler.cs

Fix a issue with Yu-gi-oh! Legacy of the Duelist.

Discard higher 32-bits of IPC message magic and command number

---

Ryujinx.HLE/HOS/Horizon.cs
Ryujinx/Ui/ApplicationAddedEventArgs.cs
Ryujinx/Ui/ApplicationCountUpdatedEventArgs.cs
Ryujinx/Ui/ApplicationLibrary.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/SwitchSettings.cs

- Convert file extensions to lowercase before comparing
- Fix bad implementation where applications were being read twice
- Caught more exceptions and added an error popup in addition to error logging

Fix application list

---

Ryujinx.Common/Logging/LogClass.cs
Ryujinx.HLE/HOS/Services/Bcat/ServiceCreator/IBcatService.cs
Ryujinx.HLE/HOS/Services/Bcat/ServiceCreator/IDeliveryCacheProgressService.cs
Ryujinx.HLE/HOS/Services/Bcat/ServiceCreator/Types/DeliveryCacheProgressImpl.cs

This stub IDeliveryCacheProgressService interface as we don't plan to support cache delivery.

Implement IDeliveryCacheProgressService in bcat

---

ARMeilleure/Instructions/NativeInterface.cs
Ryujinx.Audio/Renderers/OpenAL/OpenALAudioOut.cs
Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs
Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs
Ryujinx/Program.cs
Ryujinx/Ui/GtkDialog.cs
Ryujinx/Ui/MainWindow.cs

Also make sure to dispose the OpenAL context to not leak memory when
unloading the emulation context.

Fix a crash when closing the main UI

---

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs
Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
Ryujinx.HLE/HOS/Services/Am/ResultCode.cs

As we currently don't support multi layers on vi/nvnflinger, this PR
implement a stub of this API.
Close #778, #779 and #780

Stub the application copyright framebuffer api

---

Ryujinx/Program.cs
Ryujinx/Ryujinx.csproj
Ryujinx/Ui/AboutWindow.cs
Ryujinx/Ui/GLRenderer.cs
appveyor.yml

Add versioning on CI build.
Fix #887

Improve build identification

---

Ryujinx/Program.cs
Ryujinx/Ryujinx.csproj
Ryujinx/Ui/MainWindow.cs

- Generates config.json from default values if config.json is not present
- Load config from either ryufs or ryujinx.exe parent folder with ryujinx.exe parent folder taking priority

Changes to configuration

---

Ryujinx/Program.cs

As the title say.
This was caused by #811.

Fix crash when first starting the emulator

---

Ryujinx/Ui/ApplicationLibrary.cs

Fix application list again

---

Ryujinx.HLE/HOS/Services/Nifm/StaticService/IGeneralService.cs
Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/DnsSetting.cs
Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/IpAddressSetting.cs
Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/IpV4Address.cs

This is needed by Rocket League.
Also fix GetCurrentIpAddress to not return an ipv6 address.

Implement GetCurrentIpConfigInfo

---

Ryujinx/Ui/SwitchSettings.cs
Ryujinx/Ui/SwitchSettings.glade

Add button in settings to open logs folder

---

Ryujinx.HLE/HOS/Services/Account/Acc/IManagerForApplication.cs

Stub GetNintendoAccountUserResourceCacheForApplication

---

Ryujinx/Ryujinx.csproj

Removes the "Running on XY" text.

Update Glwidget Package

---

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
Ryujinx.HLE/HOS/Services/Am/ResultCode.cs

This PR implement some calls of ISelfController:
- EnterFatalSection
- LeaveFatalSection
- GetAccumulatedSuspendedTickValue (close #937)
According to RE of the 8.1.0 am service.

Implement some calls of ISelfController

---

Ryujinx.HLE/PerformanceStatistics.cs
Ryujinx/Ui/GLRenderer.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/MainWindow.glade
Ryujinx/Ui/StatusUpdatedEventArgs.cs

_Ac_K Edit:
This is what's the informations currently looks like_

Move status information from the title bar to the new status bar

---

Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
Ryujinx.Common/Configuration/ConfigurationState.cs
Ryujinx.Common/Configuration/System/Region.cs
Ryujinx.HLE/HOS/Services/Settings/ISettingsServer.cs
Ryujinx.HLE/HOS/SystemState/SystemRegion.cs
Ryujinx.HLE/HOS/SystemState/SystemStateMgr.cs
Ryujinx.HLE/Switch.cs
Ryujinx/Config.json
Ryujinx/Program.cs
Ryujinx/Ui/SwitchSettings.cs
Ryujinx/Ui/SwitchSettings.glade
Ryujinx/_schema.json

This implement `GetRegionCode` accordingly to RE. I've added a setting in the GUI and a field in the Configuration file with a way to update the Configuration file if needed.

Implement GetRegionCode and add the RegionCode to settings

---

ARMeilleure/Decoders/Decoder.cs
ARMeilleure/Decoders/OpCodeTable.cs

In original code, to create an opcode instance,
use the OpCodeTable to search type of opcode, after that, 
use ConcurrentDictionary<Type, MakeOp> to search MakeOp of type for create instance,
this code flow can be optimized.
Before:
OpCodeTable.GetInstA64(opcode) 
-> get type 
-> _opActivators.GetOrAdd(type) 
-> get MakeOp
-> create instance
After:
OpCodeTable.GetInstA64(opcode) 
-> get MakeOp
-> create instance
ConcurrentDictionary is no longer needed.

Use OpCodeTable to get MakeOp to improve performance

---

Ryujinx.Graphics.OpenGL/TextureCopy.cs

Fixes #880 
Thanks to @ReinUsesLisp for reporting the issue.

Keep sRGB enabled for texture blits

---

Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs

This PR stub GetBlockedUserListIds needed by Animal Crossing: New Horizons.

friends: Stub GetBlockedUserListIds

---

Ryujinx.Graphics.OpenGL/Renderer.cs
Ryujinx/Ui/GLRenderer.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/MainWindow.glade
Ryujinx/Ui/StatusUpdatedEventArgs.cs

Here some proof:
Still needed more testing on another Nvidia, AMD or Intel GPU anyway!

Add GPU name in status bar

---

Ryujinx.Graphics.Shader/Decoders/OpCodeTable.cs
Ryujinx.Graphics.Shader/Decoders/OpCodeVideo.cs
Ryujinx.Graphics.Shader/Decoders/VideoPostOp.cs
Ryujinx.Graphics.Shader/Decoders/VideoType.cs
Ryujinx.Graphics.Shader/Instructions/InstEmitVideo.cs

Fixes black sand on AC:NH.
Thanks to @ReinUsesLisp for doing hw tests.

Implement VMNMX shader instruction

---

Ryujinx/Ui/ApplicationData.cs
Ryujinx/Ui/ApplicationLibrary.cs
Ryujinx/Ui/GameTableContextMenu.cs
Ryujinx/Ui/GameTableContextMenu.glade
Ryujinx/Ui/MainWindow.cs

This allows to open the device save directory.
Also use "EnsureApplicationSaveData" and make the logic for opening the save directory more generic.

ui: Make it possible to open the device save directory

---

Ryujinx.Graphics.Shader/Decoders/Decoder.cs
Ryujinx.Graphics.Shader/Decoders/OpCodeTable.cs

This modification similar to [PR996](https://github.com/Ryujinx/Ryujinx/pull/996) and seems to work well
Thanks gdkchan for the proposal.

Move the OpActivator to OpCodeTable class for improve performance

---

Ryujinx/Ui/GLRenderer.cs
Ryujinx/Ui/GtkDialog.cs

Escape key now brings up a dialog to confirm you want to stop emulation

---

Ryujinx.Graphics.Shader/Decoders/OpCodeTable.cs
Ryujinx.Graphics.Shader/Instructions/InstEmitFArith.cs

This is like ICMP, but for floats instead.

Implement FCMP shader instruction

---

Ryujinx/Ui/MainWindow.cs

Add warning with an option to disable for settings that impact performance

---

Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
Ryujinx.Common/Configuration/TitleUpdateMetadata.cs
Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/ProgramLoader.cs
Ryujinx.HLE/Loaders/Npdm/Npdm.cs
Ryujinx/Ryujinx.csproj
Ryujinx/Ui/ApplicationLibrary.cs
Ryujinx/Ui/GLRenderer.cs
Ryujinx/Ui/GameTableContextMenu.cs
Ryujinx/Ui/GameTableContextMenu.glade
Ryujinx/Ui/TitleUpdateWindow.cs
Ryujinx/Ui/TitleUpdateWindow.glade

Implement update loader and log loaded application info

---

Ryujinx.Graphics.Gpu/State/GpuState.cs

Fix oversight in depth range initialization from PR #1093

---

Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/ISystemAppletProxy.cs
Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs
Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/IApplicationProxy.cs
Ryujinx.HLE/Switch.cs

As SurfaceFlinger is now working more accurately, we can now support
dynamic configuration of docking mode :)

Add support for dynamic docking/undocking

---

Ryujinx/Ui/GameTableContextMenu.cs

This adds update support to the section extractor.

ui: Make ExtractSection takes in account updates

---

Ryujinx.Common/Ryujinx.Common.csproj
Ryujinx.Common/SystemInfo.cs
Ryujinx/Program.cs

Log Ryujinx Version, OS Name, CPU Name and RAM size

---

Ryujinx.Graphics.Shader/Instructions/InstEmitAlu.cs

Fix decoding of some fields on the XMAD shader instruction.
Should fix issues on some games, like for example animations not working on SSBU.

Fix mode and Reg08.H1 decoding on XMAD instruction

---

Ryujinx.Common/Logging/LogClass.cs
Ryujinx.HLE/HOS/Services/Ns/IApplicationManagerInterface.cs
Ryujinx.HLE/HOS/Services/Ns/IReadOnlyApplicationControlDataInterface.cs
Ryujinx.HLE/HOS/Services/Ns/IServiceGetterInterface.cs
Ryujinx.HLE/HOS/Services/Ptm/Ts/IMeasurementServer.cs
Ryujinx.HLE/HOS/Services/Ptm/Ts/Types/Location.cs

Some implementations and stubs required by newer releases of hbl and hbmenu.

Fix hbl 2.3.1 and hbmenu 3.3.0

---

Ryujinx.HLE/Ryujinx.HLE.csproj

- Adds EnumerateDeliveryCacheDirectory to BCAT

Update to LibHac 0.11.1

---

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs

am: add IsVrModeEnabled

---

Ryujinx.HLE/HOS/Services/Am/ResultCode.cs

The error codes were taken from Switchbrew (https://switchbrew.org/wiki/Error_codes)

Add various error codes to AM

---

Ryujinx.HLE/HOS/Services/Account/ResultCode.cs
Ryujinx.HLE/HOS/Services/Friend/ResultCode.cs

The error was taken from Switchbrew (switchbrew.org/wiki/Error_codes)
This is the same kind of error from PR #1182

Add error code for denied internet request in Friends

---

Ryujinx/Ui/GLRenderer.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/MainWindow.glade
Ryujinx/Ui/StatusUpdatedEventArgs.cs

Since we have dynamic Docked/Handheld already, so i try to add Docked/Handheld text on status bar. 
The preview is on this gif (it was an old gif, but the function is the same)

Add Docked/Handheld text on status bar

---

Ryujinx/Ui/MainWindow.cs

Since some people have problems in the latest firmware with some timezones, I thought it would be nice to log the firmware version.
It would also be an nice addition to be future proof if any other problems come up with the firmware version used

Logging the current firmware version

---

Ryujinx.HLE/HOS/Kernel/Memory/KMemoryManager.cs

The `MergeEqualStateNeighbors` function is responsible for merging adjacent blocks on the list with the same state (to avoid keeping useless fragmented blocks on the list with the same state). Doing that may require removing blocks from the list. The following scenario was possible:
- Insert blocks store the next block linked list node on a temporary variable.
- `MergeEqualStateNeighbors` is called, and removes the next block, because its state is equal to the state of the block that we just inserted.
- InsertBlocks loop now tries to access the next block that was stored on the temporary variable. However it no longer belongs to the list, as it was removed on the previous step.
I fixed it by simply removing the temporary variable, and accessing the next block node from the current node …

Fix block iteration on kernel MemoryManager InsertBlock function

---

Ryujinx.HLE/HOS/Services/Ncm/Lr/ResultCode.cs

The error codes were taken from Switchbrew (https://switchbrew.org/wiki/Error_codes)

Add various error codes to NCM LR

---

Ryujinx.HLE/HOS/Services/Sdb/Pdm/ResultCode.cs

The error codes were taken from Switchbrew (https://switchbrew.org/wiki/Error_codes)

Add two error codes to SDB PDM

---

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs

This implement GetFriendInvitationStorageChannelEvent and GetNotificationStorageChannelEvent according to RE.
Needed by Streets of Rage 4 and Dr Kawashima's Brain Training

am: Implement GetFriendInvitationStorageChannelEvent

---

Ryujinx.Graphics.Shader/Decoders/OpCodeTable.cs
Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs

This implement TMML and TMML.B shader instructions

Implement TMML and TMML.B

---

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs

Just a bonus I got while exploring.
XC2:

Fix GetDisplayVersion

---

Ryujinx.HLE/HOS/Services/SurfaceFlinger/BufferQueueConsumer.cs
Ryujinx.HLE/HOS/Services/SurfaceFlinger/BufferQueueCore.cs
Ryujinx.HLE/HOS/Services/SurfaceFlinger/BufferQueueProducer.cs
Ryujinx.HLE/HOS/Services/SurfaceFlinger/BufferSlot.cs
Ryujinx.HLE/HOS/Services/SurfaceFlinger/IGraphicBufferProducer.cs
Ryujinx.HLE/HOS/Services/SurfaceFlinger/NativeWindowTransform.cs

This fixes some bugs in the current implementation and make it closer to
the real implementation.
Also implement new findings.

SurfaceFlinger: fix some bugs

---

Ryujinx.HLE/HOS/Services/Ssl/ISslService.cs
Ryujinx.HLE/HOS/Services/Ssl/SslService/ISslContext.cs

Required for minecraft dungeons.

Stubbing ImportServerPki

---

ARMeilleure/Translation/PTC/Ptc.cs

Fix issues caused by https://github.com/Ryujinx/Ryujinx/commit/2421186d974446ef4183420c50bc37e58d9fe213

Increment PTC version

---

Ryujinx.HLE/HOS/Services/Ro/Types/NRRCertification.cs
Ryujinx.HLE/HOS/Services/Ro/Types/NrrHeader.cs

This was based on Switchbrew page: switchbrew.org/wiki/NRR

Update NRR structs

---

Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
Ryujinx.Common/Configuration/ConfigurationState.cs
Ryujinx.Common/Configuration/Hid/KeyboardConfig.cs
Ryujinx.Common/Configuration/Ui/ColumnSort.cs
Ryujinx/Config.json
Ryujinx/Ui/ApplicationData.cs
Ryujinx/Ui/ApplicationLibrary.cs
Ryujinx/Ui/ControllerWindow.cs
Ryujinx/Ui/GLRenderer.cs
Ryujinx/Ui/KeyboardController.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/_schema.json

Remember GUI column sort and separate hotkey settings from emulated input settings

---

Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs

Fix #1341 
(Thanks to @AcK77 to pointing it out!)

sockets: Make sure to write the receivedBuffer

---

Ryujinx/Ui/GameTableContextMenu.cs

Added an option for purging the PPTC cache and for opening the PPTC directory.
With my discussion with @EmulationFanatic , I also decided to categorize the context menu into submenus for a better UX.

GameTableContextMenu: Implemented options for PPTC

---

Ryujinx.Common/Configuration/AudioBackend.cs
Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
Ryujinx.Common/Configuration/ConfigurationState.cs
Ryujinx/Config.json
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/SettingsWindow.cs
Ryujinx/Ui/SettingsWindow.glade
Ryujinx/_schema.json

This PR allows the user to select which audio backend to use. If the selected backend is unavailable, then the dummy backend is selected. OpenAL is selected by default.

Implement audio backend configuration option

---

Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/SettingsWindow.cs

Only reload list when game dirs are changed
closes #1331

Changes to game list reloading

---

Ryujinx.Graphics.Gpu/NvGpuFifo.cs
Ryujinx.HLE/HOS/ApplicationLoader.cs
Ryujinx.HLE/HOS/ProgramLoader.cs
Ryujinx.HLE/HOS/Services/Bluetooth/IBluetoothDriver.cs
Ryujinx.HLE/HOS/Services/Sockets/Nsd/Manager/FqdnResolver.cs
Ryujinx.HLE/Loaders/Executables/KipExecutable.cs
Ryujinx.HLE/Loaders/Executables/NsoExecutable.cs

Fix compilation warnings and use new LibHac APIs for executable loading

---

Ryujinx/Ui/MainWindow.cs

This restore previous behaviour that was lost with #1325.

Readd SoundIO as OpenAL fallback

---

Ryujinx.Graphics.GAL/IPipeline.cs
Ryujinx.Graphics.GAL/LogicalOp.cs
Ryujinx.Graphics.Gpu/Engine/Methods.cs
Ryujinx.Graphics.Gpu/State/LogicalOpState.cs
Ryujinx.Graphics.Gpu/State/MethodOffset.cs
Ryujinx.Graphics.OpenGL/EnumConversion.cs
Ryujinx.Graphics.OpenGL/Pipeline.cs

Used by XC:DE and XC2 - fixes their interior lighting volumes. Probably fixes a few other things.
Before:
https://gyazo.com/6a5e393ceadb3e9d0b7ec484dbdcd2e4
After:
https://gyazo.com/81a81843cd549e38534ee13a4b219635
(funky paths unrelated)

Implement Logical Operation registers and functionality

---

Ryujinx.HLE/HOS/Kernel/Common/KResourceLimit.cs
Ryujinx.HLE/HOS/Kernel/Memory/KMemoryManager.cs

- Fixes a bug on the ResourceLimit reserve function, that caused some games to take too long to do heap allocation (in particular, those that use a decreasing size of the heap until the `SetHeapSize` call eventually succeeds). They would spam the following on console:
```
HLE.HostThread.0 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
```
- Make `SetHeapSize` thread safe.
Fixes #1317

Fix resource limit reserve taking too long

---

ARMeilleure/Decoders/OpCode32SimdRegWide.cs
ARMeilleure/Decoders/OpCodeTable.cs
ARMeilleure/Instructions/InstEmitSimdArithmetic32.cs
ARMeilleure/Instructions/InstEmitSimdHelper32.cs
ARMeilleure/Instructions/InstName.cs
ARMeilleure/Translation/PTC/Ptc.cs
Ryujinx.Tests/Cpu/CpuTestSimdReg32.cs

Nit.
Tests performed successfully in both debug and release mode.
Closes https://github.com/Ryujinx/Ryujinx/issues/1343.

CPU: A32: Add Vadd & Vsub Wide (S/U_8/16/32) Inst.s with Test.

---

Ryujinx/Ui/SettingsWindow.cs
Ryujinx/Ui/SettingsWindow.glade

Detect available audio backends in the gui on a separate thread and hardcode dummy backend in the dropdown and select it by default.

A couple fixes for the audio backend GUI option

---

Ryujinx.HLE/HOS/Services/Vi/ResultCode.cs
Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs

This implement GetIndirectLayerImageRequiredMemoryInfo call from vi service, accordingly to RE.
Thanks to Thog and gdkchan for helping me to understand some GPU things.
Close #942

vi: Implement GetIndirectLayerImageRequiredMemoryInfo

---

Ryujinx.HLE/Ryujinx.HLE.csproj

Removes the timeout when deleting files from the local file system

Update to LibHac 0.11.3

---

Ryujinx.HLE/HOS/Services/Audio/IAudioInManager.cs

This implement some calls of IAudioInManager:
- ListAudioIns
- ListAudioInsAuto
- ListAudioInsAutoFiltered
Accordingly to RE.
Close #1056

audin: Implement IAudioInManager ListAudioIns

---

Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs
Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/Types/PlayHistoryRegistrationKey.cs

This implement IServiceCreator::GetPlayHistoryRegistrationKey call accordingly to RE.
Close #1110

friend: Implement GetPlayHistoryRegistrationKey

---

Ryujinx.Common/Memory/StructArrayHelpers.cs
Ryujinx.Graphics.Gpu/Engine/GPFifo/CompressedMethod.cs
Ryujinx.Graphics.Gpu/Engine/GPFifo/GPEntry.cs
Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoClassState.cs
Ryujinx.Graphics.Host1x/Host1xClassRegisters.cs
Ryujinx.Graphics.Host1x/ThiRegisters.cs
Ryujinx.Graphics.Nvdec.Vp9/Common/MemoryUtil.cs
Ryujinx.Graphics.Nvdec.Vp9/Constants.cs
Ryujinx.Graphics.Nvdec.Vp9/TileWorkerData.cs
Ryujinx.Graphics.Nvdec.Vp9/Types/LoopFilterThresh.cs
Ryujinx.Graphics.Nvdec.Vp9/Types/Vp9Common.cs
Ryujinx.Graphics.Nvdec/NvdecRegisters.cs
Ryujinx.Graphics.Nvdec/Types/H264/PictureInfo.cs
Ryujinx.Graphics.Nvdec/Types/H264/ReferenceFrame.cs
Ryujinx.Graphics.Nvdec/Types/Vp9/EntropyProbs.cs
Ryujinx.Graphics.Nvdec/Types/Vp9/FrameSize.cs
Ryujinx.Graphics.Nvdec/Types/Vp9/FrameStats.cs
Ryujinx.Graphics.Nvdec/Types/Vp9/LoopFilter.cs
Ryujinx.Graphics.Nvdec/Types/Vp9/PictureInfo.cs
Ryujinx.Graphics.Nvdec/Types/Vp9/Segmentation.cs
Ryujinx.Graphics.Vic/Types/ClearRectStruct.cs
Ryujinx.Graphics.Vic/Types/ConfigStruct.cs
Ryujinx.Graphics.Vic/Types/OutputConfig.cs
Ryujinx.Graphics.Vic/Types/OutputSurfaceConfig.cs
Ryujinx.Graphics.Vic/Types/PipeConfig.cs
Ryujinx.Graphics.Vic/VicRegisters.cs

Silences several warnings + minor code cleanup.

Silence several build warnings

---

Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs

Forwards `OpenSaveDataInfoReaderOnlyCacheStorage` to `OpenSaveDataInfoReaderWithFilter`
Fixes #675 
Not tested with any games. Need someone to test with a game that needs this method.

Add OpenSaveDataInfoReaderOnlyCacheStorage 

---

ARMeilleure/Decoders/OpCode32SimdCvtFI.cs
ARMeilleure/Decoders/OpCode32SimdS.cs
ARMeilleure/Decoders/OpCodeTable.cs
ARMeilleure/Instructions/InstEmitSimdArithmetic32.cs
ARMeilleure/Instructions/InstEmitSimdCvt32.cs
ARMeilleure/Instructions/InstEmitSimdHelper32.cs
ARMeilleure/Instructions/InstEmitSimdMove32.cs
ARMeilleure/Instructions/InstName.cs
ARMeilleure/Translation/PTC/Ptc.cs
Ryujinx.Memory.Tests/Ryujinx.Memory.Tests.csproj
Ryujinx.Tests.Unicorn/Ryujinx.Tests.Unicorn.csproj
Ryujinx.Tests/Cpu/CpuTest.cs
Ryujinx.Tests/Cpu/CpuTest32.cs
Ryujinx.Tests/Cpu/CpuTestSimdCvt32.cs
Ryujinx.Tests/Ryujinx.Tests.csproj

**ARMeilleure\Instructions\InstEmitSimdArithmetic32.cs:**
Vfma_S (Added new inst.)
Vfms_S (Added new inst.)
Vmla_S (Fixed slow path)
Vmls_S (Fixed slow path)
**ARMeilleure\Instructions\InstEmitSimdCvt32.cs:**
Vcvt_FI (Fixed via decoder fix)
Vcvt_RM (Fixed via decoder fix)
Vrint_RM (Updated decoder)
Vrint_Z (Updated decoder)
EmitSse41ConvertInt32 (Fixed via decoder fix)
**Ryujinx.Tests\Cpu\CpuTestSimdCvt32.cs:**
Added new test category
Added 4 Tests for Vcvt_FI inst.
**ARMeilleure\Decoders\OpCode32SimdCvtFI.cs:**
Fixed wrong Vd and Vm
**ARMeilleure\Decoders\OpCodeTable.cs:**
Improved Vcvt_FI & Vcvt_RM opcode table entries (FP16 blacklisting)
Updated Testers packages
Nits
---
Closes https://github.com/Ryujinx/Ryujinx/issues/1339 and https://github.com/Ryujinx/Ryujinx/issues/1337
Affected …

Fix Vcvt_FI & Vcvt_RM; Add Vfma_S & Vfms_S. Add Tests.

---

Ryujinx/Ui/GameTableContextMenu.cs

PPTC GUI: Purge all versioned caches on click

---

Ryujinx/Config.json

As the title say, this restore the value to 1.

Fix debug Config using res scaling 2x by default

---

Ryujinx.HLE/HOS/Services/Caps/IAlbumApplicationService.cs
Ryujinx.HLE/HOS/Services/Caps/IScreenShotApplicationService.cs

This stub `caps:su` and `caps:u` SetShimLibraryVersion call.
Puzzle Book goes ingame now:
Closes #1431

caps: Stub SetShimLibraryVersion

---

Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs

This implement/stub:
- IFriendService : GetCompletionEvent
(Closes #1541 and do Worms W.M.D boots a bit further)
- IFriendService : AddPlayHistory
(It's needed by all games who have `ldn` support)
All checked by RE.

friend: Implement GetCompletionEvent and AddPlayHistory

---

Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/MainWindow.glade
Ryujinx/Ui/SettingsWindow.cs
Ryujinx/Ui/SettingsWindow.glade

Move the open logs folder from setting into the File menu in the main window.
Closes #1543

Move the open logs folder from setting into the File menu in the main window

---

Ryujinx.HLE/HOS/ApplicationLoader.cs
Ryujinx.HLE/HOS/Services/Account/Acc/IManagerForApplication.cs
Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/Types/LaunchParameterKind.cs
Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/Types/ProgramSpecifyKind.cs
Ryujinx.HLE/HOS/UserChannelPersistance.cs
Ryujinx.HLE/HOS/UserChannelPersistence.cs
Ryujinx.HLE/IHostUiHandler.cs
Ryujinx.HLE/Switch.cs
Ryujinx/Ui/ApplicationLibrary.cs
Ryujinx/Ui/GameTableContextMenu.cs
Ryujinx/Ui/GtkHostUiHandler.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/TitleUpdateWindow.cs

This PR implement basic multi programs support and related IPC commands.
This make it possible to launch Super Mario 3D All-Stars and allows to switch between included games.
This PR also clean up and unify all NCA and updates logic to improve maintainability.
NOTE: This PR supersede #1557

hle/ui: Basic multi programs support

---

Ryujinx.Common/Utilities/EmbeddedResources.cs

Fix wrong argument usage on GetStream.
Doesn't change anything as it's not used currently but a nice catch from jD ^^.

Fix GetStream implementation

---

README.md

This touches the README to trigger a rebuild of CI.

Touch README

---

Ryujinx/Ui/MainWindow.cs

Show confirmation dialog when attempting to close the emulator while a game is loaded.
Closes #1533

Show confirmation dialog when attempting to close while a game is loaded

---

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs

Should fix regression introduced by #1625.

Add missing null check on image binding

---

Ryujinx.Graphics.Gpu/Image/Texture.cs

Some games (well, I'm aware of only one) have a large performance hit caused by constant ASTC data updates. Upon investigation, I discovered that on this specific game, the data does not really change, so my guess is that the game is writing the same data over and over in memory on every frame.
In order to avoid paying the cost for ASTC decompression for those redundant updates, I added a check that skips the update if the data did not change. It needs to keep a copy of the data in memory for that. In order to avoid increasing the memory usage in the common case, it only does that if:
- The texture is ASTC compressed.
- The host does not support the format.
- Modification was detected at least a bunch of times before (currently it uses a hardcoded value of 4).
This improves the …

Improve the speed of redundant ASTC texture data updates

---

Ryujinx.Graphics.Gpu/Engine/MethodCopyBuffer.cs

The sizes and regions that are used with the GPU copy engine are pre-multiplied by the amount of bytes per pixel (checked on NVN and deko3d). This means that we shouldn't be passing the BPP value as it was already multiplied with the coords and sizes. This change fixes this by always setting the BPP to 1, which should have the same effect as passing the correct BPP and dividing the width/height and the coords by the BPP.
The component size/count fields are now unused. The copy engine has a feature officially called "remap" that can be used to change the component order. I believe this is where the component sizes and counts come into play, as we don't emulate this feature yet, we don't need to use them.
This change fixes memory corruption caused by too much data being copied in some UE4 …

Correct BPP of buffer to texture copies

---

Ryujinx.HLE/Loaders/Executables/NsoExecutable.cs

NSO files can contains useful informations who aren't currently logged.
This PR fix that by logging Module name, Libraries and SDK Version when they are available.
I've additionnally cleaned up the `NsoExecutable` class a bit.

Loaders: Log extra NSO informations

---

README.md

Updated stats and adjusted verbiage.

Update game compatibility list info in README.md

---

Ryujinx/Ui/SettingsWindow.cs
Ryujinx/Ui/SettingsWindow.glade

Adds an apply button that doesnt close the settings window when saving
the changes.

SettingsWindow: Add an Apply button

---

Ryujinx/Ui/MainWindow.cs

This stops the GUI from asking you to disable debug features in debug builds

Don't warn when debug feature is enabled in debug builds

---

Ryujinx/Ui/Diagnostic/UserErrorDialog.cs

I missed to add the error messages for this error code on the initial PR, this fix it.

ui diag: Add missing error message for ApplicationNotFound

---

ARMeilleure/Translation/Translator.cs
Ryujinx.Graphics.Gpu/GpuContext.cs
Ryujinx.HLE/HOS/ApplicationLoader.cs
Ryujinx.Tests/Cpu/CpuTest.cs
Ryujinx.Tests/Cpu/CpuTest32.cs
Ryujinx/Ui/GLRenderer.cs
Ryujinx/Ui/MainWindow.cs

This rollback the init logic back to previous state, and replicate the way PTC handle initialization.

shader cache: Fix Linux boot issues

---

Ryujinx.Graphics.Gpu/Engine/MethodCopyBuffer.cs

Fix bug introduced on #1670 that affects homebrew using nouveau (and maybe OpenGL games) where it wouldn't copy the full texture data. The other games fixed on the aforementioned PR are still working too (tested one of them).

Fix buffer to texture copy with remap enabled

---

Ryujinx.Graphics.OpenGL/Pipeline.cs

The OpenGL spec states:
> If there is no depth buffer, it is as if the depth buffer test always passes.
Currently, there is some code that disables depth test if there's no depth buffer. This is redundant as the host API will already do that. This change will just set depth test directly instead which reduces the number of API calls and simplifies the code a bit.
Should not cause any change on games.

Simplify depth test state updates

---

Ryujinx.Common/XXHash128.cs
Ryujinx.Graphics.Nvdec.Vp9/Common/BitUtils.cs
Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs
Ryujinx.Graphics.Nvdec.Vp9/Dsp/Convolve.cs

This makes some small improvements to the code made possible by .NET 5, either because it fixed bugs that would otherwise prevent some code from being used, or because it introduced new functions that can replace existing code.

Improvements with new .NET 5 functions or bugfixes

---

Ryujinx.Graphics.Gpu/Shader/Cache/CacheCollection.cs

This assert is wrong and useless now, remove it because it's annoying in
Debug.

salieri: remove a wrong debug assert

---

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs

This PR cleans `IApplicationFunctions` a bit. More will be done about the `GetDesiredLanguage` call later.
`TryPopFromFriendInvitationStorageChannel` is stubbed, checked with RE to return the right result code which close #1571.
This should help to progress in related games. I've tested some which are playable now:

am: Cleaning and stub TryPopFromFriendInvitationStorageChannel

---

Ryujinx.Common/Configuration/ConfigurationState.cs
Ryujinx/Ui/SettingsWindow.cs

This fix a parsing issue of MaxAnistropy field on different system locales by using InvariantCulture.
Thanks to Mirage for pointed that out on Discord.

config: Fix MaxAnisotropy value parsing

---

Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
Ryujinx.Common/Configuration/ConfigurationState.cs
Ryujinx/Config.json
Ryujinx/Program.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/MainWindow.glade
Ryujinx/_schema.json

Add option to start games in fullscreen mode.
Closes #1565 and closes #1253

Add option to start games in fullscreen mode

---

Ryujinx/Ui/DlcWindow.cs
Ryujinx/Ui/DlcWindow.glade
Ryujinx/Ui/TitleUpdateWindow.cs
Ryujinx/Ui/TitleUpdateWindow.glade

Add a "Remove All" button to the DLC and Update windows
Closes #1563

Add a "Remove All" button to the DLC and Update windows

---

Ryujinx.HLE/HOS/Services/Audio/AudioOutManager/IAudioOut.cs
Ryujinx.HLE/HOS/Services/Audio/IAudioOutManager.cs
Ryujinx.HLE/HOS/Services/Nv/INvDrvServices.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvDeviceFile.cs

Following last gdkchan's PR this make sure to close copy handles that are passed by guest when it should.

Make sure to not leak copy handles passed in request

---

Ryujinx.Graphics.Gpu/Image/Pool.cs
Ryujinx.Graphics.Gpu/Memory/Buffer.cs

This PR has two simple changes:
- Uses of QueryModified now pass a cached `Action<ulong, ulong>` delegate of a named method for the function that handles modified regions.
- This is because a profile revealed that a lot of time was being spent creating a new delegate for the lambda function on each call.
- Change Buffer tracking to use simple tracking rather than smart, as the case where the smart tracking is faster has not been discovered yet.
- The same as: https://github.com/gdkchan/Ryujinx/commit/c77cc956866a7452c161b529e5c691e214b5cbc2
- It may have also been causing additional issues in games such as Catherine, though this may just be an amplification of an existing problem.
Combined, these changes almost half buffer tracking time in SMO Metro Kingdom's initial view (~11.5% to ~6%). …

Cache delegate for QueryModified, use regular multi handle.

---

Ryujinx.HLE/HOS/Services/Account/Acc/IManagerForApplication.cs

This buffer does not exist, the comment was wrong.
Fix Mario Kart 8 Deluxe regression introduced on #1808.

Remove inexistent buffer from account function

---

Ryujinx.Common/Utilities/BitUtils.cs
Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs
Ryujinx.HLE/HOS/ProgramLoader.cs
Ryujinx.HLE/HOS/Services/Ro/IRoInterface.cs
Ryujinx.HLE/Loaders/Executables/IExecutable.cs
Ryujinx.HLE/Loaders/Executables/KipExecutable.cs
Ryujinx.HLE/Loaders/Executables/NroExecutable.cs
Ryujinx.HLE/Loaders/Executables/NsoExecutable.cs
Ryujinx.Memory/IVirtualMemoryManager.cs

Sizes can't be negative, so change the type to uint. Fixes #1792.
Affected titles:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/237 (only non-JAP version)
https://github.com/Ryujinx/Ryujinx-Games-List/issues/338
https://github.com/Ryujinx/Ryujinx-Games-List/issues/469
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1304
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2540
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2618
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2901

Correct type of executable sizes

---

Ryujinx.Graphics.Gpu/Shader/Cache/CacheCollection.cs
Ryujinx.Graphics.Gpu/Shader/Cache/CacheHelper.cs
Ryujinx.Graphics.Gpu/Shader/Cache/CacheManager.cs
Ryujinx.Graphics.Gpu/Shader/Cache/CacheMigration.cs
Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs

This improves shader cache resilience when people opens another program that touch the cache.zip.

salieri: Support read-only mode if archive is already opened

---

Ryujinx.HLE/HOS/Services/Nim/IShopServiceAccessServerInterface.cs
Ryujinx.HLE/HOS/Services/Nim/ResultCode.cs

This PR implement nim:eca IShopServiceAccessServerInterface IsLargeResourceAvailable accordingly to RE.
Fix #1794

nim: Implement IsLargeResourceAvailable

---

Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/NvHostAsGpuDeviceFile.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/Types/AddressSpaceContext.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/Types/AllocSpaceArguments.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/Types/FreeSpaceArguments.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/Types/MapBufferExArguments.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/Types/UnmapBufferArguments.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostChannel/NvHostChannelDeviceFile.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvMap/NvMapDeviceFile.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvMap/Types/NvMapAlloc.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvMap/Types/NvMapFree.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvMap/Types/NvMapHandle.cs
Ryujinx.HLE/HOS/Services/SurfaceFlinger/SurfaceFlinger.cs

Closes https://github.com/Ryujinx/Ryujinx/issues/1820
It's my first PR on this project and my first time coding in C#.
Let me know if there is something that I could improve, please.

Remove long <-> ulong casts from Nvservices code

---

README.md

Added GPU enhancements, GUI option updates, game compatibility list updates.

Update README.md to reflect new features/changes in the emulator

---

Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/MainWindow.glade

Closes https://github.com/Ryujinx/Ryujinx/issues/1862

ui: disable "Simulate Wake-up" when no game is running

---

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ILibraryAppletCreator.cs

Fix applet regression introduced on #1929.
Closes #1936.

Fix alignment on CreateTransferMemoryStorage

---

.github/workflows/build.yml

See https://github.com/actions/setup-dotnet/issues/155.

Github Actions: Workaround windows-latest restore failures

---

ARMeilleure/Instructions/InstEmitSimdArithmetic.cs
ARMeilleure/Instructions/InstEmitSimdHelper.cs
ARMeilleure/Translation/PTC/Ptc.cs

* Add `VCLZ.8B/16B` SSSE3 fast path
* Add `VCLZ.4H/8H` SSSE3 fast path
* Add `VCLZ.2S/4S` SSE2 fast path
based on [ARM_NEON_2_x86_SSE](https://github.com/intel/ARM_NEON_2_x86_SSE).

Add VCLZ.* fast path

---

ARMeilleure/Decoders/OpCodeTable.cs
ARMeilleure/Instructions/InstEmitMemoryEx.cs
ARMeilleure/Instructions/InstName.cs
ARMeilleure/Translation/PTC/Ptc.cs

Implements PRFM (register) as NOP, similar to other variants. Also, `pfrm -> prfm`
Closes #1744
Closes #1824 (duplicate)
Please test the programs/games linked in the issues as I don't have them.

Implement PRFM (register variant) as NOP

---

Ryujinx.Common/Configuration/ConfigurationState.cs
Ryujinx/Config.json
Ryujinx/_schema.json

Enables Docked Mode by default, There is one game that doesn't render but for most people I feel having it enabled by default isn't an issue :p

Enable Docked Mode by Default

---

Ryujinx/Modules/Updater/UpdateDialog.cs

Fixes the icon of the updater on Linux.
Before:
After:

Fix Updater Icon On Linux

---

Ryujinx.HLE/HOS/Kernel/Memory/KMemoryManager.cs

This fixes a issue that started happening since #1458, where the inter-process IPC copies would assume that the entire virtual region was contiguous, when it might not be. This causes memory corruption if the region is not contiguous, as the data will be copied to the wrong physical region.
Fixes crash on boot on Bravely Default II Demo, Balan Wonderworld Demo, and possibly other games. Note: It will not fix crashes that already existed before IPC part 2.

Fix inter-process data copy on non-contiguous physical regions

---

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs

This PR implement `appletAE ICommonStateGetter SetLcdBacklighOffEnabled` accordingly to RE.
Closes #2021

appletAE: Implement SetLcdBacklighOffEnabled

---

Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs

This PR fixes an inline keyboard soft-lock in God Eater 3 when changing the codename of your character in the creation screen.
The same tests of #1959 were used:
- Dark Souls Remastered - Character creation screen
- Gnosia - Character creation screen
- Fate / Extella Link - Character creation screen
- Monster Hunter Rise Demo - In-game messaging
- Monster Hunter Generations Ultimate - In-game messaging (standard save)
- Monster Hunter Generations Ultimate - Set / Item renaming (standard save)
- Monster Hunter Generations Ultimate - Guild card renaming (standard save)
- Monster Hunter Generations Ultimate - In-game messaging (imported save)
- Monster Hunter Generations Ultimate - Set / Item renaming (imported save)
- Monster Hunter Generations Ultimate - Guild card renaming (imported save) …

Fix software keyboard soft-lock in God Eater 3

---

Ryujinx/Modules/Updater/Updater.cs

This makes the updater use a bit more formal wording. Easier for people to understand in one try. Especially with changing "most updated version" to "latest version".

Some minor formal wording for the updater.

---

Ryujinx.Audio/Renderer/Dsp/Command/MixCommand.cs
Ryujinx.Audio/Renderer/Dsp/Command/VolumeCommand.cs
Ryujinx.Audio/Renderer/Dsp/DataSourceHelper.cs

Add fast paths in the audio renderer for AArch64 in all current fast paths.

Amadeus: Add ARM SIMD fast paths

---

Ryujinx.Memory.Tests/MockVirtualMemoryManager.cs

This PR fixes a GitHub Action warning, nothing more.

Test: Fixes github action warning

---

Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceSession.cs

That one missing patch oops.
Also improve assert message

Fix typo in assert in OpenAL implementation detail

---

Ryujinx.Graphics.OpenGL/Image/TextureView.cs

Fixes the grammar in the AMD/Intel workaround comment.

Fix a comment's grammar.

---

Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/Widgets/GameTableContextMenu.cs
Ryujinx/Ui/Widgets/GtkDialog.cs
Ryujinx/Ui/Windows/ControllerWindow.cs
Ryujinx/Ui/Windows/DlcWindow.cs

Let's make the wording a bit better, sure this is trivial, but I still want to do it.

Minor wording fixes... Except I'm doing it for all of Ryujinx.

---

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs
Ryujinx.Graphics.Shader/Decoders/Decoder.cs
Ryujinx.Graphics.Shader/Translation/Translator.cs

This PR moves the bindless check stopgap from translation to decode phase and disables cache-related processing early.
Fixes MHR v1.1.1 shader cache crash and possibly other bindless texture related shader cache crashes.
Thanks to @gdkchan for suggestions.
Since this affects shader caches, needs some testing to see if there are regressions.

Shader Cache: Catch bindless textures early

---

Ryujinx.HLE/Loaders/Executables/NsoExecutable.cs

Recent applications seem to ship large binaries and I noticed `PrintRoSectionInfo` is slowing down loads.
- Remove unnecessary `Span.ToArray()`
- Skip a search if name is already found (previously always searched)
- Use `CultureInvariant` with `IgnoreCase` for safety
- Use `Regex.Match` when only first matches are needed. Using `Count` bypasses laziness.
- Use `RegexOptions.Compiled`. Helped in tests, probably because this operates on large "strings". 
It's a shame that .net Regex is pretty inflexible and works only on strings. A considerable portion of execution time is still due to `ASCII.GetString()`.
My tests indicate this method is 40-60% faster now.

Optimize PrintRoSectionInfo

---

Ryujinx.Graphics.OpenGL/Sync.cs

May fix sync object timeouts on AMD.

Force command flush after creating a syncpoint

---

README.md

Update README.MD to reflect new OpenGL requirements, latest gamedb statistics, mods/cheats support

---

.github/workflows/nightly_pr_comment.yml

Hide debug artifacts posted by github-actions

---

Ryujinx.HLE/HOS/Services/Friend/IServiceCreator.cs
Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/INotificationService.cs
Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/NotificationService/NotificationEventHandler.cs
Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/Types/FriendServicePermissionLevel.cs

This PR fixes the permission level names, nothing more.

friend: Fixes PermissionLevel names

---

Ryujinx/Modules/Updater/Updater.cs

This should fixes #2125!
This works as the update system has been pacified (#1899).
Suggestions requested!

Enable updates in portable mode. (related to #1885)

---

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs

This PR stubs `am` `IApplicationFunctions` `ExtendSaveData` call since related call aren't supported by LibHac yet, checked by RE.
Fixes #2207 
Now minecraft is playable but the game seems to deadlock when you use DLC (maybe due to something else):

am: Stub IApplicationFunctions ExtendSaveData

---

Ryujinx.Graphics.OpenGL/Framebuffer.cs
Ryujinx.Graphics.OpenGL/HwCapabilities.cs
Ryujinx.Graphics.OpenGL/Image/TextureCopy.cs

as suggested by gdkchan
supersede #2213

HwCapabilities: Divide Intel into IntelWindows and IntelUnix

---

Ryujinx.HLE/HOS/Services/Mm/IRequest.cs
Ryujinx.HLE/HOS/Services/Mm/Types/MultiMediaOperationType.cs

This PR just cleaned up the `mm:u` services a bit with some unknown values which is now known. Nothing more.

mm: Cleaned up the service a bit

---

Ryujinx.Graphics.Nvdec.H264/FFmpegContext.cs
Ryujinx.Graphics.Nvdec.H264/Ryujinx.Graphics.Nvdec.H264.csproj
Ryujinx/Ryujinx.csproj

Update to FFmpeg 4.4.0

---

Ryujinx/Ui/Windows/ControllerWindow.cs

This was a regression introduced by Miria.

Miria: Make default profile loads Pro Controller by default

---

Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs

This pull request stubs nn::hid::IHidServer::IsFirmwareUpdateAvailableForSixAxisSensor and nn::irsensor::IIrSensorServer::CheckFirmwareVersion, to make games which use these commands run without the "Ignore Missing Services" setting enabled.
This is my first pull request/contribution to Ryujinx, so feedback on what I did right/wrong would be much appreciated.

hid/irs: Stub IsFirmwareUpdateAvailableForSixAxisSensor and CheckFirmwareVersion

---

Ryujinx.HLE/HOS/Services/Mii/Helper.cs
Ryujinx.HLE/HOS/Services/Mii/MiiDatabaseManager.cs
Ryujinx.HLE/HOS/Services/Mii/Types/CoreData.cs
Ryujinx.HLE/HOS/Services/Mii/Types/NintendoFigurineDatabase.cs
Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs

I found multiple inconsistencies while diffing with latest sdb, this PR fixes those findings.

mii: Fix multiple inconsistencies

---

Ryujinx.HLE/HOS/Services/Sdb/Pl/ISharedFontManager.cs

This PR implement `GetSharedFontInOrderOfPriorityForSystem` which is the same as `GetSharedFontInOrderOfPriority` with different permission.

pl: Implement GetSharedFontInOrderOfPriorityForSystem

---

Ryujinx.HLE/HOS/Services/Prepo/IPrepoService.cs
Ryujinx.HLE/HOS/Services/Prepo/Types/PrepoServicePermissionLevel.cs

This PR implement `SaveSystemReport` and `SaveSystemReportWithUser` which are the same as `SaveReport` but with different permission.

prepo: Implement SaveSystemReport and SaveSystemReportWithUser

---

ARMeilleure/Decoders/OpCodeTable.cs
ARMeilleure/Instructions/InstEmitSimdLogical32.cs
ARMeilleure/Instructions/InstName.cs
Ryujinx.Tests/Cpu/CpuTestSimdLogical32.cs

Fixes #2395
MushihimeSama can progress further.
Tests included. Both slow and fast paths passing locally.

Implement VORN (register) Arm32 instruction

---

Ryujinx.Graphics.Gpu/Engine/Compute.cs
Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoDevice.cs
Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs
Ryujinx.Graphics.Gpu/Engine/MethodClear.cs
Ryujinx.Graphics.Gpu/Engine/MethodCopyBuffer.cs
Ryujinx.Graphics.Gpu/Engine/MethodCopyTexture.cs
Ryujinx.Graphics.Gpu/Engine/MethodDraw.cs
Ryujinx.Graphics.Gpu/Engine/MethodUniformBufferBind.cs
Ryujinx.Graphics.Gpu/Engine/MethodUniformBufferUpdate.cs
Ryujinx.Graphics.Gpu/Engine/Methods.cs
Ryujinx.Graphics.Gpu/GpuChannel.cs
Ryujinx.Graphics.Gpu/GpuContext.cs
Ryujinx.Graphics.Gpu/Image/Texture.cs
Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs
Ryujinx.Graphics.Gpu/Image/TextureCache.cs
Ryujinx.Graphics.Gpu/Image/TextureManager.cs
Ryujinx.Graphics.Gpu/Image/TexturePool.cs
Ryujinx.Graphics.Gpu/Image/TexturePoolCache.cs
Ryujinx.Graphics.Gpu/Memory/BufferCache.cs
Ryujinx.Graphics.Gpu/Memory/BufferManager.cs
Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs
Ryujinx.Graphics.Gpu/State/GpuState.cs
Ryujinx.Graphics.Gpu/Window.cs
Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostChannel/NvHostChannelDeviceFile.cs

This adds some basic support for GPU channels. Each channel has *separate state*. Due to the fact that everything was using a single channel before, games that made use of multiple Queues (each Queue is a channel) would end with corrupt state. The most common situation that causes this is Queue A setting up its state, then a new queue (Queue B) being created, and then setting up its own state, and corrupting Queues A state in the process.
This fixes the problem by adding a new `GpuChannel` class, and moving almost all of the state that shouldn't be shared there. A few things such as draw state were not moved yet, but those shouldn't cause issues as this state is reset often. GPU address spaces are also still shared, but this is a separate issue, and queues can share an address space …

Initial support for GPU channels

---

Ryujinx.Common/Configuration/Hid/KeyboardHotkeys.cs
Ryujinx.Graphics.GAL/IRenderer.cs
Ryujinx.Graphics.GAL/ScreenCaptureImageInfo.cs
Ryujinx.Graphics.OpenGL/Renderer.cs
Ryujinx.Graphics.OpenGL/Window.cs
Ryujinx/Config.json
Ryujinx/Configuration/ConfigurationFileFormat.cs
Ryujinx/Configuration/ConfigurationState.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/MainWindow.glade
Ryujinx/Ui/RendererWidgetBase.cs
Ryujinx/_schema.json

Adds taking screen captures of games at their internal resolution. So you can now take your 8K screenshots even if you don't have a display that high. 
It can be used from the Actions menu or with the hotkey, F8.
Fixes #2143 .

Add Screenshot Feature

---

Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceDriver.cs
Ryujinx.Audio.Backends.SoundIo/SoundIoHardwareDeviceDriver.cs
Ryujinx.Audio.Backends.SoundIo/SoundIoHardwareDeviceSession.cs
Ryujinx.Audio/Input/AudioInputManager.cs
Ryujinx.Audio/Input/AudioInputSystem.cs
Ryujinx.Audio/Output/AudioOutputManager.cs
Ryujinx.Audio/Output/AudioOutputSystem.cs
Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs
Ryujinx.Audio/Renderer/Server/AudioRendererManager.cs
Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/LibraryAppletCreator/ILibraryAppletAccessor.cs
Ryujinx.HLE/HOS/Services/Audio/AudioIn/AudioInServer.cs
Ryujinx.HLE/HOS/Services/Audio/AudioOut/AudioOutServer.cs
Ryujinx.HLE/HOS/Services/Audio/AudioRenderer/AudioRendererServer.cs
Ryujinx.HLE/HOS/Services/Bcat/ServiceCreator/IDeliveryCacheDirectoryService.cs
Ryujinx.HLE/HOS/Services/Bcat/ServiceCreator/IDeliveryCacheFileService.cs
Ryujinx.HLE/HOS/Services/Bcat/ServiceCreator/IDeliveryCacheStorageService.cs
Ryujinx.HLE/HOS/Services/DisposableIpcService.cs
Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/INotificationService.cs
Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IFile.cs
Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IStorage.cs
Ryujinx.HLE/HOS/Services/Fs/ISaveDataInfoReader.cs
Ryujinx.HLE/HOS/Services/IpcService.cs
Ryujinx.HLE/HOS/Services/Nifm/StaticService/IGeneralService.cs
Ryujinx.HLE/HOS/Services/Ro/IRoInterface.cs
Ryujinx.HLE/HOS/Services/ServerBase.cs
Ryujinx.HLE/HOS/Services/Sm/IUserInterface.cs
Ryujinx.HLE/HOS/Services/Spl/IRandomInterface.cs

This was an oversight since a long time.
This is needed for #2328 for multi-programs.

Fix disposing of IPC sessions server at emulation stop

---

Ryujinx.HLE/HOS/Services/Ns/Aoc/IAddOnContentManager.cs

This PR fixes a wrong check added in #2414 which made Pokémon crash.

aoc: Fix wrong check

---

Ryujinx/Program.cs
Ryujinx/Ui/MainWindow.cs

Start a game with -f argument doesn't tick "Start Games in Fullscreen Mode" anymore

---

.github/workflows/build.yml
Ryujinx.HLE/HLEConfiguration.cs
Ryujinx.Headless.SDL2/OpenGL/OpenGLWindow.cs
Ryujinx.Headless.SDL2/Options.cs
Ryujinx.Headless.SDL2/Program.cs
Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj
Ryujinx.Headless.SDL2/SDL2Mouse.cs
Ryujinx.Headless.SDL2/SDL2MouseDriver.cs
Ryujinx.Headless.SDL2/StatusUpdatedEventArgs.cs
Ryujinx.Headless.SDL2/WindowBase.cs
Ryujinx.SDL2.Common/SDL2Driver.cs
Ryujinx.sln
appveyor.yml

This is an all integrated experience that only depends on SDL2.
Every settings are configurable via commandline.
User can control input mapping via presaved profile from GTK3 or use the default preset.
It still need to be decided if we want to put sidebar information in the title bar.

frontend: Add a SDL2 headless window

---

Ryujinx.Headless.SDL2/Program.cs

Fixes the build after #2328 was merged

Fix the headless build

---

Ryujinx.Graphics.Shader/ShaderProgram.cs
Ryujinx.Graphics.Shader/Translation/TargetLanguage.cs
Ryujinx.Graphics.Shader/Translation/Translator.cs
Ryujinx.ShaderTools/Program.cs
Ryujinx.ShaderTools/Ryujinx.ShaderTools.csproj

This improves shader tools command line by adding support for target language and api.

shadertools: Prepare for new target Languages and APIs

---

Ryujinx.Memory/Tracking/RegionHandle.cs

On the GPU emulator, `TextureGroup` seems to be working with the assumption that if a handle is dirty, then it must be mapped. Afterall, how can a unmapped memory region be dirtied? However, it may still happen if the region is only partially unmapped. This change fixes the issue by simply not dirtying the handle if it is unmapped (either fully or partially).
Fixes crash when loading a save on Dragon Quest XI S. Note that it fixes a crash with the following stack trace:
```
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0x00000000A6C40000, size=0x0000000000400000
at Ryujinx.Cpu.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in C:\Users\gdk\Documents\Ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 134
at …
```

Do not dirty memory tracking region handles if they are partially unmapped

---

ARMeilleure/State/ExecutionContext.cs
Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceDriver.cs
Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceDriver.cs
Ryujinx.Audio.Backends.SoundIo/SoundIoHardwareDeviceDriver.cs
Ryujinx.Audio/AudioManager.cs
Ryujinx.Audio/Backends/CompatLayer/CompatLayerHardwareDeviceDriver.cs
Ryujinx.Audio/Backends/Dummy/DummyHardwareDeviceDriver.cs
Ryujinx.Audio/Integration/IHardwareDeviceDriver.cs
Ryujinx.Audio/Renderer/Dsp/AudioProcessor.cs
Ryujinx.Audio/Renderer/Server/AudioRendererManager.cs
Ryujinx.Common/Configuration/Hid/KeyboardHotkeys.cs
Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs
Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs
Ryujinx/Config.json
Ryujinx/Configuration/ConfigurationFileFormat.cs
Ryujinx/Configuration/ConfigurationState.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/MainWindow.glade
Ryujinx/Ui/RendererWidgetBase.cs
Ryujinx/_schema.json

Add a new menu item to pause/resume emulation :
Add also a new hotkey to toggle pause (default is F5, can be changed in Config.json file)
~~Implementation is not perfect as Audio continues to play a bit after pause.~~
Closes Ryujinx#1604

Implement a "Pause Emulation" option & hotkey

---

Ryujinx.Tests.Unicorn/libs/README.md
Ryujinx.Tests.Unicorn/libs/linux/unicorn_fspcr.patch

As per the Discord conversation, adding some info on compiling Unicorn with the necessary patch on Linux.

Add Linux Unicorn patch + desc.

---

README.md

Just a README change, nothing special.

Quick README update for game compatibility.

---

ARMeilleure/CodeGen/X86/CallingConvention.cs
ARMeilleure/Signal/NativeSignalHandler.cs
ARMeilleure/Translation/Cache/JitCache.cs
ARMeilleure/Translation/PTC/Ptc.cs
Ryujinx.Common/System/DisplaySleep.cs
Ryujinx.Common/System/WindowsMultimediaTimerResolution.cs
Ryujinx.Headless.SDL2/Program.cs
Ryujinx.Memory/MemoryManagement.cs
Ryujinx.Memory/MemoryManagementUnix.cs
Ryujinx.Memory/MemoryManagementWindows.cs
Ryujinx/Modules/Updater/UpdateDialog.cs
Ryujinx/Modules/Updater/Updater.cs
Ryujinx/Program.cs
Ryujinx/Ui/GLRenderer.cs
Ryujinx/Ui/Helper/OpenHelper.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/VKRenderer.cs

Very basic migration across the codebase.

misc: Migrate usage of RuntimeInformation to OperatingSystem

---

Ryujinx.HLE/HOS/Horizon.cs
Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs
Ryujinx.HLE/HOS/Kernel/SupervisorCall/InfoType.cs
Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall32.cs
Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall64.cs

This PR updates ``GetInfo`` to make it more readeable (by using an ``InfoType`` enum) and implement missing types.
This is based on my kernel 13.0.0 researches.

kernel: Improve GetInfo readability and update to 13.0.0

---

ARMeilleure/Decoders/OpCodeTable.cs
ARMeilleure/Instructions/InstEmitAlu32.cs
ARMeilleure/Instructions/InstName.cs
ARMeilleure/Translation/PTC/Ptc.cs
Ryujinx.Tests/Cpu/CpuTestAlu32.cs

Implemented instruction
- UHADD8
Fixes #1644
I originally implemented this instruction in #2242 but to make it easier for the maintainers to review, I've decided to split it into a separate pull request.

Implement UHADD8 instruction

---

Ryujinx/Config.json

misc: Sync Config.json default debug config

---

Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs

Fixes freezes in OpenGL games, primarily GameMaker ones such as Undertale (when killing undyne, and alphys lab?).
Before this, it would just wait forever after the DMA completes for a value that would never change. In this particular game, it was copying a portion of the render output so that it could be read by CPU.
Found this by looking at register writes right before it froze. I'm not particularly sure what's meant to happen with a "four word" semaphore - it may write a timestamp similar to the counter report method. Right now, it is skipped and logs a warning,
https://gyazo.com/1b9d637de43e03887055b024e4c23760

Add support for releasing a semaphore to DmaClass

---

Ryujinx.SDL2.Common/Ryujinx.SDL2.Common.csproj

Update to latest SDL2 commit
Fix #2905, #2837 and #2767.

sdl2: Update to Ryujinx.SDL2-CS 2.0.19

---

Ryujinx/Ryujinx.csproj

Update to a new SPB version targeting .NET 6.

misc: Update SPB to 0.0.4-build17

---

Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs

Follow-up of #2936, this time fixing a similar issue with the `GetHostByNameRequestWithOptions` and `GetHostByAddrRequestWithOptions`. Also includes other minor changes to improve/simplify the code.
Allows the Twitch app to boot further, but still doesn't work as it requires unimplemented SSL functions.

Fix GetHostByNameRequestWithOptions and GetHostByAddrRequestWithOptions

---

Ryujinx.HLE/HOS/Services/Hid/Hid.cs
Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
Ryujinx.HLE/HOS/Services/Hid/Types/Npad/NpadStyleIndex.cs

While looking to the HID code, I've found some syntax issue, and inconsistencies between `ActivateNpad` and `ActivateNpadWithRevision`. Nothing more.

hid: A little cleanup

---

Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Proxy/DnsBlacklist.cs

This blocks more that have been seen in the wild

misc: Improve DNS blacklist for Nintendo servers

---

ARMeilleure/Decoders/OpCodeTable.cs
ARMeilleure/Instructions/InstEmitSimdCvt.cs
ARMeilleure/Instructions/InstEmitSimdHelper.cs
ARMeilleure/Instructions/InstName.cs
ARMeilleure/Translation/PTC/Ptc.cs
Ryujinx.Tests/Cpu/CpuTestSimd.cs

Fixes #2909 
Add missing instruction that prevents some games from booting.

CPU - Implement FCVTMS (Vector)

---

Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/ManagerServer.cs
Ryujinx.HLE/Ryujinx.HLE.csproj

This improve correctness of that call while possibly spoofing possible recognizable patterns.

account: Rework LoadIdTokenCache to auto generate a random JWT token

---

Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfo4.cs
Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfoSerialized.cs
Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfoSerializedHeader.cs
Ryujinx.HLE/Utilities/StringUtils.cs

Fix a crash on Monster Hunter Rise

sfdnsres: Fix serialization issues

---

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs

This fixes an issue where the render scale array would not be updated when technically the scales on the flat array were the same, but the start index for the vertex scales was different.

Fix res scale parameters not being updated in vertex shader

---

ARMeilleure/Decoders/OpCodeTable.cs

ARMeilleure: OpCodeTable: Add CMN (RsReg)

---

ARMeilleure/Decoders/OpCodeTable.cs
ARMeilleure/Instructions/InstEmitAlu32.cs
ARMeilleure/Instructions/InstName.cs
Ryujinx.Tests/Cpu/CpuTestAlu32.cs

Based on [this commit](https://github.com/merryhime/dynarmic/commit/0ff8c375af74a0d20aee1e383e4ed509808a0314).

ARMeilleure: A32: Implement SHSUB8 and UHSUB8

---

ARMeilleure/CodeGen/X86/X86Optimizer.cs

The `UsesCount` field is limited to 16-bits, so it can overflow if there are more than 65535 uses. The optimization that reuses constant was causing this overflow to happen on a guest function with a lot of memory operations on the same basic block. This change adds a limit on the number of uses a constant may have before it adds another fresh mov, thus avoiding the problem.
The issue was observed on Deathsmiles II. The game is working now with this change.

Add a limit on the number of uses a constant may have

---

Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs

The region X/Y registers, like the width and height ones, are only used for block linear textures. For linear textures, they are ignored. Instead, the driver adds an offset to the source or destination address directly based on the X/Y it wants.
This allows River City Girls Zero to get ingame, before it would crash after the manga style cutscene.
Potentially also fixes issues on other games that does linear <-> block linear copies on DMA *and* that does a block linear copy at least once with a non-zero X/Y.

When copying linear textures, DMA should ignore region X/Y

---

Ryujinx.Audio/Renderer/Dsp/ResamplerHelper.cs

Before, it was selecting the nearest sample, which sounded terrible. This changes it to use a rather simple cubic interpolation, which greatly reduces high frequency noise (could be better tho). This is temporary til the upsampling algorithm used by the switch is reversed.
Improves bad audio in Skyward Sword HD.

Use a basic cubic interpolation for the audren upsampler

---

Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvMap/NvMapDeviceFile.cs

Removes quite a bit of unneeded log spam

Change ServiceNv map creation logs to the Debug level

---

Ryujinx.Common/Logging/LogLevel.cs
Ryujinx.Common/Logging/Logger.cs
Ryujinx.Common/Logging/Targets/ConsoleLogTarget.cs
Ryujinx.HLE/HOS/Kernel/SupervisorCall/SyscallTable.cs
Ryujinx.HLE/HOS/Services/IpcService.cs
Ryujinx.Headless.SDL2/Options.cs
Ryujinx.Headless.SDL2/Program.cs
Ryujinx/Configuration/ConfigurationFileFormat.cs
Ryujinx/Configuration/ConfigurationState.cs
Ryujinx/Configuration/LoggerModule.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/Windows/SettingsWindow.cs
Ryujinx/Ui/Windows/SettingsWindow.glade

Added support for trace logs - fixes #1547

Added trace log level

---

Ryujinx.HLE/HOS/Kernel/SupervisorCall/SyscallTable.cs

Move kernel syscall logs to new trace log level

---

ARMeilleure/Instructions/InstEmitSystem.cs
ARMeilleure/Instructions/NativeInterface.cs
ARMeilleure/Translation/Delegates.cs
ARMeilleure/Translation/IntervalTree.cs
ARMeilleure/Translation/PTC/Ptc.cs
ARMeilleure/Translation/PTC/PtcProfiler.cs
ARMeilleure/Translation/Translator.cs
ARMeilleure/Translation/TranslatorCache.cs
Ryujinx.Cpu/CpuContext.cs
Ryujinx.HLE/HOS/ArmProcessContext.cs
Ryujinx.HLE/HOS/Kernel/Process/IProcessContext.cs
Ryujinx.HLE/HOS/Kernel/Process/ProcessContext.cs

This PR extends the existing `InvalidateJitCacheRegion` to actually *remove* functions overlapping a given range from the cache. One important thing to note is that the function is not actually removed from memory, instead it is just removed from the tables making it inaccessible. Not removing it from memory is to prevent crashes if it happens to be still being executed when the invalidate method is called. This is something that should be improved in the future.
Since the invalidation requires getting all functions that overlaps the invalidated range, I had to use a different data structure since the `ConcurrentDictionary` is not suited for this. Now it uses a `IntervalTree` that is based on the implementation used to find texture overlaps, with a few differences:
- The texture overlaps …

Enable CPU JIT cache invalidation

---

ARMeilleure/Translation/PTC/Ptc.cs

PPTC version increment

---

ARMeilleure/Decoders/OpCode32.cs
ARMeilleure/Decoders/OpCodeT32BImm20.cs
ARMeilleure/Decoders/OpCodeT32BImm24.cs
ARMeilleure/Decoders/OpCodeTable.cs
ARMeilleure/Instructions/InstEmitAluHelper.cs
ARMeilleure/Instructions/InstEmitFlow32.cs
ARMeilleure/Instructions/InstEmitHelper.cs
Ryujinx.Tests/Cpu/CpuTestT32Flow.cs

Finish off the thumb branch instructions.
Yes, the order of j1, j2 differs from i1, i2; please triple check the manual.

T32: Implement B, B.cond, BL, BLX

---

ARMeilleure/Decoders/OpCodeT16BImm11.cs
ARMeilleure/Decoders/OpCodeT16BImm8.cs

Decoders: Fix instruction lengths for 16-bit branch instructions

---

Ryujinx/Configuration/ConfigurationFileFormat.cs
Ryujinx/Configuration/ConfigurationState.cs
Ryujinx/Ui/Helper/ConsoleHelper.cs
Ryujinx/Ui/MainWindow.cs
Ryujinx/Ui/MainWindow.glade

Add menu item that allows the console window to be displayed or hidden. Windows-only.
~~Is there a nice way to make a menu item only display on Windows?~~ Fixed.
Closes #1669.

Ui: Add option to show/hide console window (Windows-only)

---

.github/workflows/nightly_pr_comment.yml

infra: Put SDL2 headless release inside a GUI-less block in PR

---

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs
Ryujinx.Graphics.Shader/Instructions/Lop3Expression.cs

Implemented for fun. Feel free to close if not required.
NPN-transforms the truth table to one of the basic 14 classes.
Terminology as per:
Sanity check: https://gist.github.com/merryhime/8684e2f6a4fcb7c9fe32ffcc932c1109

Lop3Expression: Optimize expressions

---

Ryujinx.Common/ReactiveObject.cs

ReactiveObject: Handle case when oldValue is null

---

.github/workflows/build.yml

Since the build is 1.1.0 now but some lines still stuck at 1.0.0. I copied the variable name from the `release.yml` file.
Fixes #3288.

Update the artifact build's version number in the comment

---

Ryujinx/Program.cs

infra: Warn about support drop of old Windows versions

---

Ryujinx.SDL2.Common/Ryujinx.SDL2.Common.csproj

Update to latest SDL2 release
Fix #2905, #2837, #2767 and #3040.

sdl2: Update to Ryujinx.SDL2-CS 2.0.22

---

Ryujinx.Audio.Backends.OpenAL/Ryujinx.Audio.Backends.OpenAL.csproj
Ryujinx.Ava/Input/AvaloniaKeyboardDriver.cs
Ryujinx.Ava/Ryujinx.Ava.csproj
Ryujinx.Ava/Ui/Applet/AvaloniaDynamicTextInputHandler.cs
Ryujinx.Graphics.OpenGL/Pipeline.cs
Ryujinx.Graphics.OpenGL/Ryujinx.Graphics.OpenGL.csproj
Ryujinx/Ryujinx.csproj

This reformat Avalonia csproj file, remove unused deps and reajust
Ryujinx csproj a bit after some other changes
Also updated OpenTK.Graphics

misc: Clean up of CS project after Avalonia merge

---

Ryujinx/Ui/Windows/AmiiboWindow.cs

Fix amiibo image path

---

.github/workflows/build.yml
.github/workflows/nightly_pr_comment.yml
.github/workflows/release.yml
Ryujinx.Audio.Backends.SoundIo/Ryujinx.Audio.Backends.SoundIo.csproj
Ryujinx.Ava/Ryujinx.Ava.csproj
Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj
Ryujinx.ShaderTools/Ryujinx.ShaderTools.csproj
Ryujinx.Tests/Ryujinx.Tests.csproj
Ryujinx/Ryujinx.csproj

infra: Switch to win10-x64 RID and fix PR comment for Avalonia and SDL2 artifact rename

---

Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs

On instanced draws, the inline index buffer was not being taken into account. This causes games using instanced draws and inline index buffer updates to use incorrect index buffer data, incorrect draw type (as it might do a non-indexed draw), and not resetting the inline index buffer offset, which causes data to be written to the wrong offset.
This change fixes it by adding a new field to indicate if the instanced draw is using inline index buffer data. In this case, it properly consumes the inline index buffer data and resets the offset.
This fixes the 3D sections on Genkai Tokki Moero Crystal H.
Before:
After:
This also fixes the weird performance drops, caused by the GPU trying to rasterize "garbage" from memory as the draw type and index buffers were incorrect.
Note that this includes …

Fix instanced indexed inline draws

---

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs

Fixes a regression introduced by the texture bindings PR.
Also renames TextureStatePerStage, as it's no longer per stage.
Please actually test this one (with res scale and without).

Account for res scale changes when updating bindings

---

Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZoneContentManager.cs

ui: Fix timezone abbreviation since #3361

---

Ryujinx.Ava/Assets/Locales/en_US.json
Ryujinx.Ava/Ui/Controls/ProfileImageSelectionDialog.axaml
Ryujinx.Ava/Ui/Controls/ProfileImageSelectionDialog.axaml.cs
Ryujinx.Ava/Ui/Models/Amiibo.cs
Ryujinx.Ava/Ui/Models/CheatModel.cs
Ryujinx.Ava/Ui/Models/CheatsList.cs
Ryujinx.Ava/Ui/Models/DlcModel.cs
Ryujinx.Ava/Ui/Models/ProfileImageModel.cs
Ryujinx.Ava/Ui/Models/TitleUpdateModel.cs
Ryujinx.Ava/Ui/Models/UserProfile.cs
Ryujinx.Ava/Ui/ViewModels/AmiiboWindowViewModel.cs
Ryujinx.Ava/Ui/ViewModels/AvatarProfileViewModel.cs
Ryujinx.Ava/Ui/ViewModels/MainWindowViewModel.cs
Ryujinx.Ava/Ui/ViewModels/UserProfileViewModel.cs
Ryujinx.Ava/Ui/Windows/AmiiboWindow.axaml
Ryujinx.Ava/Ui/Windows/AmiiboWindow.axaml.cs
Ryujinx.Ava/Ui/Windows/AvatarWindow.axaml
Ryujinx.Ava/Ui/Windows/AvatarWindow.axaml.cs
Ryujinx.Ava/Ui/Windows/CheatWindow.axaml
Ryujinx.Ava/Ui/Windows/CheatWindow.axaml.cs
Ryujinx.Ava/Ui/Windows/DlcManagerWindow.axaml
Ryujinx.Ava/Ui/Windows/DlcManagerWindow.axaml.cs
Ryujinx.Ava/Ui/Windows/TitleUpdateWindow.axaml
Ryujinx.Ava/Ui/Windows/TitleUpdateWindow.axaml.cs
Ryujinx.Ava/Ui/Windows/UserProfileWindow.axaml
Ryujinx.Ava/Ui/Windows/UserProfileWindow.axaml.cs

This adds all the remaining windows. Locale has been updated too.

UI - Avalonia Part 3

---

Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/ManagedSocket.cs

This allows using the DontWait flag in Receive, instead of in ReceiveFrom only.

BSD: Allow use of DontWait flag in Receive

---

Ryujinx.Ava/Assets/Locales/de_DE.json
Ryujinx.Ava/Assets/Locales/el_GR.json
Ryujinx.Ava/Assets/Locales/es_ES.json
Ryujinx.Ava/Assets/Locales/fr_FR.json
Ryujinx.Ava/Assets/Locales/it_IT.json
Ryujinx.Ava/Assets/Locales/ko_KR.json
Ryujinx.Ava/Assets/Locales/pt_BR.json
Ryujinx.Ava/Assets/Locales/ru_RU.json
Ryujinx.Ava/Assets/Locales/tr_TR.json
Ryujinx.Ava/Assets/Locales/zh_CN.json
Ryujinx.Ava/Assets/Locales/zh_TW.json

>This PR aims to Complete #3480 by adding it's changes to the rest of the languages Avalonia supports, as said in #3480:
> This PR aims to adjust the Hacks hint/description in Avalonia to appear more consistently with the rest of the hints in their respective UIs.

Minor Avalonia UI verbiage/case fixes Accross languages

---

Ryujinx.Ava/AppHost.cs
Ryujinx.Ava/Program.cs
Ryujinx.Ava/Ui/Backend/Vulkan/ResultExtensions.cs
Ryujinx.Ava/Ui/Backend/Vulkan/Skia/VulkanRenderTarget.cs
Ryujinx.Ava/Ui/Backend/Vulkan/Skia/VulkanSkiaGpu.cs
Ryujinx.Ava/Ui/Backend/Vulkan/Surfaces/VulkanSurfaceRenderTarget.cs
Ryujinx.Ava/Ui/Backend/Vulkan/VulkanCommandBufferPool.cs
Ryujinx.Ava/Ui/Backend/Vulkan/VulkanDevice.cs
Ryujinx.Ava/Ui/Backend/Vulkan/VulkanDisplay.cs
Ryujinx.Ava/Ui/Backend/Vulkan/VulkanImage.cs
Ryujinx.Ava/Ui/Backend/Vulkan/VulkanInstance.cs
Ryujinx.Ava/Ui/Backend/Vulkan/VulkanOptions.cs
Ryujinx.Ava/Ui/Backend/Vulkan/VulkanPlatformInterface.cs
Ryujinx.Ava/Ui/Backend/Vulkan/VulkanSurfaceRenderingSession.cs
Ryujinx.Ava/Ui/Controls/OpenGLRendererControl.cs
Ryujinx.Ava/Ui/Controls/RendererControl.cs
Ryujinx.Ava/Ui/Controls/VulkanRendererControl.cs
Ryujinx.Ava/Ui/ViewModels/MainWindowViewModel.cs
Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
Ryujinx.Ava/Ui/Windows/MainWindow.axaml.cs
Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml
Ryujinx.Graphics.GAL/IWindow.cs
Ryujinx.Graphics.GAL/Multithreading/ThreadedWindow.cs
Ryujinx.Graphics.OpenGL/Window.cs
Ryujinx.Graphics.Vulkan/ImageWindow.cs
Ryujinx.Graphics.Vulkan/MemoryAllocator.cs
Ryujinx.Graphics.Vulkan/Window.cs
Ryujinx.Graphics.Vulkan/WindowBase.cs
Ryujinx/Ui/RendererWidgetBase.cs

1. Fix up crash that occurs when you toggle fullscreen
2. Add fallback to OpenGl if vulkan is not available.
3. Add swapchain present mode control to gtk
4. Fix screenshot on avalonia vulkan 
5. Fix favorite not being saved on avalonia

Avalonia - Couple fixes and improvements to vulkan

---

Ryujinx.HLE/HOS/Services/Pctl/ParentalControlServiceFactory/IParentalControlService.cs

This PR Implement `EndFreeCommunication` (checked by RE). Nothing more.
Closes #2420

pctl: Implement EndFreeCommunication

---

Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs

This is a very old oversight on our Poll implementation.
This worked so far reliably because games and homebrews pass the same buffer as input and output.
Also fix ``IsUnexpectedLinuxError``

bsd: Fix Poll writting in input buffer

---

Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/IManagerForApplication.cs
Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/ManagerServer.cs
Ryujinx.HLE/HOS/Services/Account/Acc/IAsyncContext.cs
Ryujinx.HLE/HOS/Services/Account/Acc/IAsyncNetworkServiceLicenseKindContext.cs
Ryujinx.HLE/HOS/Services/Account/Acc/Types/NetworkServiceLicenseKind.cs
Ryujinx.HLE/HOS/Services/Account/ResultCode.cs

This is needed to run Pokemon Legends Arceus 1.1.1 with guest internet enabled.
The game still get stuck at loading screen.

account: Implement LoadNetworkServiceLicenseKindAsync

---

Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs

This was an oversight of the implementation.

bsd: Fix Poll(0) returning ETIMEDOUT instead of SUCCESS

---

Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/ISocket.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/ManagedSocket.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdMMsgHdr.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdMsgHdr.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/TimeVal.cs

bsd: implement SendMMsg and RecvMMsg

---

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs

Fixes a regression from #3399 in the Mario Party Superstars spotlight minigame where an image would not rebind when its binding format was changed. Some other games may be affected.
Should also obsolete #3442, as this fixes it in a different way. Check the games that were meant to be fixed by that.

Rebind textures if format changes or they're buffer textures

---

README.md

Update some verbiage and compatibility data.

Update README.MD verbiage and compatibility

---

ARMeilleure/Decoders/OpCode32.cs
ARMeilleure/Decoders/OpCode32SimdCvtFI.cs
ARMeilleure/Decoders/OpCode32SimdDupGP.cs
ARMeilleure/Decoders/OpCode32SimdImm44.cs
ARMeilleure/Decoders/OpCode32SimdMemImm.cs
ARMeilleure/Decoders/OpCode32SimdMemMult.cs
ARMeilleure/Decoders/OpCode32SimdMovGp.cs
ARMeilleure/Decoders/OpCode32SimdMovGpDouble.cs
ARMeilleure/Decoders/OpCode32SimdMovGpElem.cs
ARMeilleure/Decoders/OpCode32SimdRegS.cs
ARMeilleure/Decoders/OpCode32SimdS.cs
ARMeilleure/Decoders/OpCode32SimdSel.cs
ARMeilleure/Decoders/OpCode32SimdSpecial.cs
ARMeilleure/Decoders/OpCodeT16.cs
ARMeilleure/Decoders/OpCodeT32.cs
ARMeilleure/Decoders/OpCodeTable.cs
ARMeilleure/Instructions/InstEmitAluHelper.cs
ARMeilleure/Instructions/InstEmitFlow32.cs

T32 has identical encoding to A32 except cond is always 1110.

T32: Add Vfp instructions

---

Ryujinx.Memory/WindowsShared/PlaceholderManager.cs

This fixes a regression from #3648 that caused punctuation to be missing from text on Super Smash Bros Ultimate, among other issues. Because `MapViewInterval` updates the protections on the tree (to RW), and it is called on partial unmap, restoring protections was not working properly and it would always try to reprotect as RW, which causes the write tracking to be lost. In addition to that, I also fixed the protections tree initialization, which was passing size rather than end address, this was likely causing other issues.
Only affects Windows, and since most games don't trigger partial unmap, the number of affected games is likely low.

Fix partial unmap reprotection on Windows

---

README.md

Just saw this while creating another PR.

Readme: Fix broken shell image

---

ARMeilleure/Decoders/OpCode32SimdCvtTB.cs
ARMeilleure/Decoders/OpCodeTable.cs
ARMeilleure/Instructions/InstEmitSimdCvt32.cs
ARMeilleure/Instructions/InstEmitSimdHelper32.cs
Ryujinx.Tests/Cpu/CpuTestSimdCvt32.cs

A32: Implement VCVTT, VCVTB

---

Ryujinx.HLE/HOS/Services/Ssl/SslService/ISslConnection.cs

Hi, just a simple PR to implement `GetSessionCacheMode` in `SSL` service.

Implement the GetSessionCacheMode in SSL service

---

Ryujinx.Ava/Ui/Controls/ContentDialogHelper.cs

Avalonia: Use overlay dialog for controller applet

---

Ryujinx.Tests.Unicorn/UnicornAArch32.cs
Ryujinx.Tests.Unicorn/UnicornAArch64.cs
Ryujinx.Tests/Cpu/CpuTest.cs
Ryujinx.Tests/Cpu/CpuTest32.cs

Dispose unicorn when done. May help with CI issues in #3771.

Ryujinx.Tests.Unicorn: Implement IDisposable

---

Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs

Fixes a crash in Game Builder Garage when exiting a game using the IR Motion Camera Nodon.
Closes #3503
Before:
https://user-images.githubusercontent.com/65521430/197896055-02fe9ea3-9d1e-44c4-88a2-d7a34f037553.mp4
After:
https://user-images.githubusercontent.com/65521430/197896114-d70a8fe9-40a5-4fc5-9229-7d7eb9e74615.mp4

hid/irs: Stub StopImageProcessorAsync

---

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs

Stubs Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ISelfController: 130 (SetRecordVolumeMuted)
Fixes a crash in Bayonetta 3 when starting the first mission.

AppletAE: stub SetRecordVolumeMuted

---

Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs
Ryujinx.HLE/HOS/Services/Nfc/Nfp/VirtualAmiibo.cs
Ryujinx.HLE/HOS/Services/Prepo/IPrepoService.cs
Ryujinx.HLE/HOS/Services/Ro/IRoInterface.cs

[Available since .NET 6](https://learn.microsoft.com/en-us/dotnet/api/system.random.shared?view=net-7.0)

Make use of Random.Shared

---

Ryujinx.Audio/Renderer/Utils/FileHardwareDevice.cs
Ryujinx.HLE/HOS/Services/Nfc/Nfp/VirtualAmiibo.cs
Ryujinx.HLE/HOS/Services/Nifm/StaticService/IGeneralService.cs
Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZone.cs
Ryujinx.HLE/Loaders/Mods/IPSPatcher.cs

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/utf8-string-literals

Use new C# 11 UTF-8 string literals

---

Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs

Stub IFriendService: 1 (Cancel)

---

Ryujinx.Headless.SDL2/Vulkan/VulkanWindow.cs
Ryujinx.SDL2.Common/Ryujinx.SDL2.Common.csproj
Ryujinx.SDL2.Common/SDL2Driver.cs

chore: Update Ryujinx.SDL2-CS to 2.24.2

---

Ryujinx.Ava/Ryujinx.Ava.csproj

chore: Update Avalonia related dependencies

---

Ryujinx.Audio.Backends.OpenAL/Ryujinx.Audio.Backends.OpenAL.csproj
Ryujinx.Ava/Ryujinx.Ava.csproj
Ryujinx.Graphics.OpenGL/Ryujinx.Graphics.OpenGL.csproj
Ryujinx.Graphics.Vulkan/Ryujinx.Graphics.Vulkan.csproj
Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj
Ryujinx/Ryujinx.csproj

As depandabot isn't really smart with it, let's do it ourself here.

chore: Update OpenTK to 4.7.5

---

Ryujinx.Memory/Tracking/ConcurrentBitmap.cs

ConcurrentBitmap: Use Interlocked Or/And

---

Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceDriver.cs
Ryujinx.SDL2.Common/SDL2Driver.cs

Better logging for SDL2 audio init errors to better diagnose the greyed out option issue

Better SDL2 Audio Init Error Logging

---

Ryujinx.Audio/Renderer/Dsp/AudioProcessor.cs
Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs

A very dumb mistake oops.
Might help with audio desync, might cause audio stutters, will see!
Need heavy testing on **every games that use the audio renderer**

amadeus: Fix wrong SendCommands logic

---

Ryujinx.Common/SystemInfo/MacOSSystemInfo.cs

Now that mac is supported officially, this change adds the missing query for logging a good estimate of available RAM.
Thanks to marysaka for testing a prototype.

Support logging available memory on macOS

---

Ryujinx.Ava/Assets/Styles/BaseDark.xaml
Ryujinx.Ava/Assets/Styles/BaseLight.xaml
Ryujinx.Ava/Ui/Applet/ErrorAppletWindow.axaml
Ryujinx.Ava/Ui/Applet/SwkbdAppletDialog.axaml
Ryujinx.Ava/Ui/Controls/GameGridView.axaml
Ryujinx.Ava/Ui/Controls/GameListView.axaml
Ryujinx.Ava/Ui/Controls/InputDialog.axaml
Ryujinx.Ava/Ui/Controls/NavigationDialogHost.axaml
Ryujinx.Ava/Ui/Controls/ProfileImageSelectionDialog.axaml
Ryujinx.Ava/Ui/Controls/RendererHost.axaml
Ryujinx.Ava/Ui/Controls/SaveManager.axaml
Ryujinx.Ava/Ui/Controls/UpdateWaitWindow.axaml
Ryujinx.Ava/Ui/Controls/UserEditor.axaml
Ryujinx.Ava/Ui/Controls/UserRecoverer.axaml
Ryujinx.Ava/Ui/Controls/UserSelector.axaml
Ryujinx.Ava/Ui/ViewModels/MainWindowViewModel.cs
Ryujinx.Ava/Ui/Windows/AboutWindow.axaml
Ryujinx.Ava/Ui/Windows/AmiiboWindow.axaml
Ryujinx.Ava/Ui/Windows/AvatarWindow.axaml
Ryujinx.Ava/Ui/Windows/CheatWindow.axaml
Ryujinx.Ava/Ui/Windows/ContentDialogOverlayWindow.axaml
Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
Ryujinx.Ava/Ui/Windows/DownloadableContentManagerWindow.axaml
Ryujinx.Ava/Ui/Windows/MainWindow.axaml
Ryujinx.Ava/Ui/Windows/MotionSettingsWindow.axaml
Ryujinx.Ava/Ui/Windows/RumbleSettingsWindow.axaml
Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml
Ryujinx.Ava/Ui/Windows/TitleUpdateWindow.axaml
Ryujinx.Ui.Common/App/ApplicationLibrary.cs
crowdin.yml

**Changes:**
- Fix accessibility violations in ListView and GridView
- Hide loading progress bar when complete
- Change how playtime decimals are formatted
- Adjusted the appearance of favourite star to fit theme
- Fixes whitespace not defocusing text boxes #3662

Ava GUI: Several UI Fixes

---

Ryujinx.Ava/Ryujinx.Ava.csproj
Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj
Ryujinx/Ryujinx.csproj

This adds support for Linux x64, macOS x64 and macOS arm64.

misc: Update Ryujinx.Graphics.Nvdec.Dependencies to 5.0.1-build12

---

ARMeilleure/Decoders/OpCodeTable.cs
Ryujinx.Ava/Program.cs
Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs
Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs

Supersedes https://github.com/Ryujinx/Ryujinx/pull/4035
Removes a few warnings.
It should not affect functionality.

Fix Lambda Explicit Type Specification Warnings

---

Ryujinx.HLE/HOS/Services/Sockets/Bsd/BsdContext.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/IFileDescriptor.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/ISocket.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/EventFileDescriptor.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/EventFileDescriptorPollManager.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/ManagedSocket.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/ManagedSocketPollManager.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/WSAError.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/WinSockHelper.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdAddressFamily.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdIoctl.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdMMsgHdr.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdMsgHdr.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdSockAddr.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdSocketCreationFlags.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdSocketFlags.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdSocketOption.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdSocketShutdownFlags.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdSocketType.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/EventFdFlags.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/IPollManager.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/LinuxError.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/PollEvent.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/PollEventData.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/PollEventTypeMask.cs
Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/TimeVal.cs
Ryujinx.HLE/HOS/Services/Ssl/SslService/SslManagedSocketConnection.cs

A while ago @gdkchan already implemented `Select`, but never created a PR for it.
This PR uses this implementation and adapts it to the current Ryujinx version. 
With this implementation @EmulationFanatic was able to start a LAN game in the Saints Row games.
---
Note: The implementation was tested before I cleaned it up. I'm sure I didn't break anything by cleaning it up, but just in case, let's wait for confirmation that everything still works as expected.

Bsd: Implement Select

---

Ryujinx.Audio/Renderer/Common/WorkBufferAllocator.cs
Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs
Ryujinx.Common/Utilities/BitUtils.cs
Ryujinx.Graphics.Gpu/Engine/InlineToMemory/InlineToMemoryClass.cs
Ryujinx.Graphics.Gpu/Memory/BufferManager.cs
Ryujinx.Graphics.Vulkan/MemoryAllocatorBlockList.cs
Ryujinx.HLE/HOS/Kernel/Ipc/KBufferDescriptorTable.cs
Ryujinx.HLE/HOS/Kernel/Ipc/KServerSession.cs
Ryujinx.HLE/HOS/Kernel/Memory/KCodeMemory.cs
Ryujinx.HLE/HOS/Kernel/Memory/KPageBitmap.cs
Ryujinx.HLE/HOS/Kernel/Memory/KPageHeap.cs
Ryujinx.HLE/HOS/Kernel/Memory/KPageTableBase.cs
Ryujinx.HLE/HOS/Kernel/Memory/KSharedMemory.cs
Ryujinx.HLE/HOS/Kernel/Memory/KTransferMemory.cs
Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs
Ryujinx.HLE/HOS/ProgramLoader.cs
Ryujinx.HLE/HOS/Services/Ro/IRoInterface.cs
Ryujinx.HLE/HOS/Services/SurfaceFlinger/Parcel.cs

Based on issue #3858. 
Replaces several BitUtils overloads with 1 generic method that accepts several types.
I will work on more of the .net 6/7 improvements when I have the time.

Added Generic Math to BitUtils

---

ARMeilleure/Common/AddressTable.cs
ARMeilleure/Common/Counter.cs
ARMeilleure/Common/EntryTable.cs
ARMeilleure/IntermediateRepresentation/BasicBlock.cs
ARMeilleure/Translation/DelegateHelper.cs
ARMeilleure/Translation/Delegates.cs
ARMeilleure/Translation/IntervalTree.cs
ARMeilleure/Translation/TranslatorStubs.cs
Ryujinx.Common/Collections/IntervalTree.cs
Ryujinx.Common/Collections/IntrusiveRedBlackTree.cs
Ryujinx.Common/Collections/IntrusiveRedBlackTreeImpl.cs
Ryujinx.Common/Collections/TreeDictionary.cs
Ryujinx.HLE/Switch.cs
Ryujinx.Memory/MemoryBlock.cs
Ryujinx.Memory/Tracking/RegionHandle.cs

Contributes to #3858 
ArgumentNullException.ThrowIfNull has been introduced in .NET 6 and ObjectDisposedException.ThrowIf in .NET 7

Use new ArgumentNullException and ObjectDisposedException throw-helper API

---

Directory.Packages.props
Ryujinx.Common/Memory/PartialUnmaps/PartialUnmapState.cs
Ryujinx.Memory.Tests/Tests.cs
Ryujinx.Memory/MemoryBlock.cs
Ryujinx.Tests/Memory/PartialUnmaps.cs

chore: Update tests dependencies

---

Directory.Packages.props
Ryujinx.Ui.LocaleGenerator/Ryujinx.Ui.LocaleGenerator.csproj

This PR remove 2 duplicated deps entries added in #3999 and reformat `Ryujinx.Ui.LocaleGenerator.csproj` as the other project files for consistencies.

Misc: Remove duplicated entries and clean locale csproj

---

Ryujinx.Audio/Backends/CompatLayer/CompatLayerHardwareDeviceDriver.cs
Ryujinx.Audio/Backends/Dummy/DummyHardwareDeviceDriver.cs
Ryujinx.Audio/Integration/IHardwareDeviceDriver.cs
Ryujinx.Ava/AppHost.cs

This PR cleaned up the AppHost file a bit (adding the infamous extra spaces to improve readability), resorting private vars, removing useless vars, improving the code here and there, like the AudioBackend check.

ava: Cleanup AppHost

---

ARMeilleure/CodeGen/Arm64/HardwareCapabilities.cs
ARMeilleure/Instructions/InstEmitSimdArithmetic.cs
ARMeilleure/Optimizations.cs
ARMeilleure/Translation/PTC/Ptc.cs

Proposal for #4259.
To be tested.

Arm64: Cpu feature detection

---

Ryujinx.Ava/Assets/Styles/Styles.xaml
Ryujinx.Ava/UI/Models/SaveModel.cs
Ryujinx.Ava/UI/ViewModels/UserSaveManagerViewModel.cs
Ryujinx.Ava/UI/Views/Main/MainViewControls.axaml
Ryujinx.Ava/UI/Views/User/UserSaveManagerView.axaml
Ryujinx.Ava/UI/Views/User/UserSaveManagerView.axaml.cs

- Fixed SaveManager bug in #4166 
- Allow save size to be formatted as KB and GB
- Move SearchBox fix in #4223 to `Styles`

Ava UI: Various Fixes

---

Ryujinx.Graphics.Vulkan/BufferManager.cs
Ryujinx.Graphics.Vulkan/FramebufferParams.cs
Ryujinx.Graphics.Vulkan/MemoryAllocator.cs
Ryujinx.Graphics.Vulkan/PipelineBase.cs
Ryujinx.Graphics.Vulkan/Vendor.cs
Ryujinx.Graphics.Vulkan/VulkanInitialization.cs
Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
Ryujinx.Graphics.Vulkan/Window.cs

This reverts commit dca5b14493e730960ed5cd67906278ecea969b3a.

Revert "Relax Vulkan requirements (#4228)"

---

Ryujinx.Graphics.Gpu/Image/TextureGroup.cs
Ryujinx.Graphics.Gpu/Image/TextureGroupHandle.cs

Fixes regression from #4284 that caused games that flushes texture from CPU (not from GPU thread) to crash on OpenGL. Vulkan is unaffected.
Fixes #4288.

Fix texture flush from CPU WaitSync regression on OpenGL

---

Ryujinx.Audio/Renderer/Dsp/Command/UpsampleCommand.cs
Ryujinx.Audio/Renderer/Dsp/ResamplerHelper.cs
Ryujinx.Audio/Renderer/Dsp/UpsamplerHelper.cs
Ryujinx.Audio/Renderer/Server/Upsampler/UpsamplerBufferState.cs
Ryujinx.Audio/Renderer/Server/Upsampler/UpsamplerState.cs

Audren: Implement polyphase upsampler

---

Ryujinx.HLE/FileSystem/ContentManager.cs
Ryujinx.HLE/HOS/ModLoader.cs
Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/ManagerServer.cs
Ryujinx.HLE/HOS/Services/Caps/CaptureManager.cs

Replace BitConverter.ToString(bytes).Replace("-", "") with Convert.ToHexString(bytes)

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/missing_cpu_instruction.yml
.github/ISSUE_TEMPLATE/missing_service_call.yml

This PR improve issues form a bit:
- Remove the annoying unneeded checkbox.
- Add some labels automatically.
- Remove useless textarea for specs and add inputs instead.
- Add title keys for some issues.

Misc: Update issues form

---

Ryujinx.Graphics.Shader/CodeGen/Spirv/Declarations.cs

This fixes a bug that would cause SPIR-V shader generation to crash, if the shader uses input or output indexing, and all accesses are indexed. That's because the `InputsArray` and `OutputsArray` was being declared inside the loop that is supposed to declare all non-indexed inputs/outputs.
Fixes a crash on Metroid Prime Remastered on Vulkan.

Fix SPIR-V when all inputs/outputs are indexed

---

Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs

The most complicated and mission-critical PR ever drafted

Ava UI: Fix Title Update Manager not selecting right update

---

Directory.Packages.props

As depandabot always have issues with that one, let's do it manually.

chore: Update OpenTK to 4.7.7

---

README.md

Adds post processing information to the GPU section in the readme.

Add post processing feature to the readme

---

.github/workflows/flatpak.yml

I know this is not important at all, but since I was supposed to port the full script to GitHub Actions, I'd like to fix these "issues" anyway.

[Flatpak] Beautify multiline strings again & Add full git commit hash

---

Ryujinx.Graphics.OpenGL/Queries/BufferedQuery.cs

OpenGL: Fix inverted conditional for counter flush from #4471

---

Directory.Packages.props

chore: Update Ryujinx.SDL2-CS to 2.26.3

---

Ryujinx.Graphics.Vulkan/VulkanRenderer.cs

Not sure since when it was broken...

vulkan: fix broken "VK_EXT_subgroup_size_control" support check

---

Ryujinx.Graphics.Vulkan/VulkanInitialization.cs

vulkan: Fix access level of extensions fields and make them readonly

---

Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceSession.cs

This PR makes audio device error not fatal.
In case of error, the SDL2 audio backend will behave like the dummy backend.
Close https://github.com/Ryujinx/Ryujinx/issues/4229.

audout: Fix a possible crash with SDL2 when the SDL2 audio backend is dummy

---

Ryujinx.Horizon.Kernel.Generators/Kernel/SyscallGenerator.cs
Ryujinx.Horizon.Kernel.Generators/Kernel/SyscallSyntaxReceiver.cs
Ryujinx.Horizon/Sdk/Sf/CommandHandler.cs
Ryujinx.Horizon/Sdk/Sf/CommandSerialization.cs
Ryujinx.Horizon/Sdk/Sf/HipcCommandProcessor.cs
Ryujinx.Horizon/Sm/Impl/ServiceManager.cs

🙂I've done some refactoring aming at better readability.

Slight Code Refactoring

---

Ryujinx.Graphics.Vulkan/VulkanDebugMessenger.cs
Ryujinx.Graphics.Vulkan/VulkanInitialization.cs
Ryujinx.Graphics.Vulkan/VulkanRenderer.cs

Also checks for "VK_EXT_debug_utils "existence instead of force enabling it and allow possible error logging during messenger init.

vulkan: Separate debug utils logic from VulkanInitialization

---

Ryujinx.Ui.Common/App/ApplicationLibrary.cs

Addresses issue #4525. Checks if the file is a symlink it gets the true full path of the file so it shows the correct size.

Added check for eventual symlink when displaying game files.

---

Directory.Packages.props

chore: Update Silk.NET to 2.17.1

---

Ryujinx/Program.cs

Fixes a regression from #3707 where I accidentally removed that line.
Thank you to `kakasita#0149` for informing me about this issue!

UI: Set the console title for GTK 

---

src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoDevice.cs

Signal interrupt event to improve back-end frame presentation

---

src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml.cs
src/Ryujinx.HLE/HOS/ModLoader.cs
src/Ryujinx.HLE/Loaders/Processes/Extensions/LocalFileSystemExtensions.cs
src/Ryujinx.HLE/Loaders/Processes/Extensions/NcaExtensions.cs
src/Ryujinx/Ui/Widgets/GameTableContextMenu.cs
src/Ryujinx/Ui/Windows/CheatWindow.cs

Reverts Ryujinx/Ryujinx#4720 for now as it breaks cheat.
Will be revisited another time.

Revert "ModLoader: Fix case sensitivy issues"

---

src/Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs

Fix typo in TextureBindingsManager.cs

---

src/Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/ISystemAppletProxy.cs
src/Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs

Some IPC I have stubbed during private testing and I don't want to deal with them anymore. Nothing more.

AM: Stub some service calls

---

src/Ryujinx.HLE/Loaders/Processes/Extensions/FileSystemExtensions.cs
src/Ryujinx.HLE/Loaders/Processes/ProcessLoader.cs
src/Ryujinx.HLE/Loaders/Processes/ProcessLoaderHelper.cs
src/Ryujinx.HLE/Loaders/Processes/ProcessResult.cs

Follow up of https://github.com/Ryujinx/Ryujinx/pull/4846 as I find another big copy.
Should be the last one around here at least.

misc: Avoid copy of ApplicationControlProperty

---

src/Ryujinx.Graphics.Vulkan/VulkanInitialization.cs

Those shouldn't have been hardcoded.

vulkan: Avoid hardcoding features in CreateDevice

---

src/Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceDriver.cs
src/Ryujinx.Audio/Renderer/Device/VirtualDevice.cs
src/Ryujinx.Audio/Renderer/Device/VirtualDeviceSessionRegistry.cs
src/Ryujinx.HLE/HOS/Horizon.cs

Also adjust VirtualDevice configuration reporting accordingly.

audio: sdl2: Do not report 5.1 if the device doesn't support it

---

src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
src/Ryujinx/Ui/Windows/SettingsWindow.cs

Fixes #4984 
Doesn't make Ryujinx work on Win11 on ARM, because after this it crashes in ARMeilleure.

Fix crash in SettingsViewModel when Vulkan isn't available

---

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs
src/Ryujinx.Graphics.Shader/Instructions/InstEmit.cs
src/Ryujinx.Graphics.Shader/Instructions/InstEmitMove.cs
src/Ryujinx.Graphics.Shader/Instructions/InstEmitPredicate.cs

Hi!
This is my attempt at implementing these shaders.
I'm basically new to this (Ryujinx, c#, shaders). So please feel free to dismiss this, if it's totally off the mark.
It does seem to satisfy these [tests](https://github.com/yuzu-emu/yuzu/pull/3799#issuecomment-619467465).
Maybe there are other tests to check the implementation against?
fixes https://github.com/Ryujinx/Ryujinx/issues/5046, fixes https://github.com/Ryujinx/Ryujinx/issues/5047

Implement p2rc, p2ri, p2rr and r2p.cc shaders

---

Directory.Packages.props

chore: Update Avalonia to 0.10.21

---

src/Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceDriver.cs

Easier than I thought :)
Good job on making it easy to develop (code compiles fast, no hard setup, ...)
Closes #5108

Fix #5108: Allow surround sound for SDL2 in more scenarios

---

.github/ISSUE_TEMPLATE/missing_shader_instruction.yml

For issues like:
- <https://github.com/Ryujinx/Ryujinx/issues/2794>
- <https://github.com/Ryujinx/Ryujinx/issues/5046>
- <https://github.com/Ryujinx/Ryujinx/issues/5047>

Add issue template for missing shader instructions

---

src/Ryujinx.Graphics.Vulkan/TextureView.cs

We still care about the DepthStencilMode for identity image views. Creates a separate view for identity and draw if the aspect flags end up being different for draw.
Fixes visual issues on Mesa (#5143, not sure if it solves all the crashes), and also validation errors elsewhere when asking for identity views of depth textures.

Vulkan: Use aspect flags for identity views for bindings

---

src/Ryujinx.Ava/Assets/Locales/en_US.json
src/Ryujinx.Ava/UI/Applet/SwkbdAppletDialog.axaml.cs
src/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/CJKCharacterValidation.cs
src/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/KeyboardMode.cs
src/Ryujinx/Ui/Applet/SwkbdAppletDialog.cs

Swkbd Applet Fixes

---

src/Ryujinx.HLE/HOS/Services/Hid/IHidbusServer.cs
src/Ryujinx.HLE/HOS/Services/Hid/Types/Npad/BusHandle.cs
src/Ryujinx.HLE/HOS/Services/Hid/Types/Npad/BusType.cs

Partially resolves https://github.com/Ryujinx/Ryujinx/issues/1028
Reference: https://switchbrew.org/wiki/HID_services#GetBusHandle
Tested with NES Switch Online, now boots and is playable.

hle: Stub IHidbusServer.GetBusHandle

---

.github/assign/global.yml
.github/labeler.yml
.github/workflows/build.yml
.github/workflows/pr_triage.yml
.github/workflows/release.yml

This PR fixes the glob patterns in `.github/labeler.yml` and adjusts the paths which trigger a new release to ignore these type of changes.

infra: Fix PR triage workflow glob patterns

---

.github/workflows/pr_triage.yml

For some reason this doesn't work with v1 alone, although other actions do.

infra: Fix action version for triage workflow

---

distribution/macos/create_macos_build.sh
distribution/macos/updater.sh

In a way to continue the cleaning of the project, there are some warnings which can be easily fixed.

macOS: Fix warning in some shell scripts

---

src/Ryujinx/Ui/Windows/ControllerWindow.cs

This fixes a regression from #5395

[Hotfix] Fix naming issue in ControllerWindow

---

src/Ryujinx.Common/Memory/StructArrayHelpers.cs
src/Ryujinx.HLE/HOS/Services/Mii/Types/RandomMiiConstants.cs

This PR fixes a regression from #5380, which was found and debugged by @riperiperi.
Steps to reproduce the previous issue:
1. Start Mario Kart 8 Deluxe
2. Enter VS mode
3. Play one race with any character
4. Return to the course selection after the race finished
5. Crash

HLE: Fix corrupted Mii structs

---

.github/workflows/pr_triage.yml

Another hotfix, because of course we aren't allowed to spawn a shell in an action.

Use poetry run instead of spawning a shell

---

src/Ryujinx.Graphics.Texture/SizeCalculator.cs

This fixes a regression caused by #5220 that caused grass/bushes/flowers/tree animations to stop running on Pokémon Scarlet/Violet. Textures with different layer sizes and more than one "slice" are not considered compatible. Because the layer size for render targets is supplied by the driver rather than being calculated by the emulator, the render texture would have an aligned layer size, while the sampled 3D texture would have an unaligned size. This change fixes it by making sure the layer size is always aligned.
I tested Spiritfarer which was one of the games fixed by the original change and it still seems fine, but I didn't test Zelda Tears of  the Kingdom.
Thanks to @Littl3Guy for narrowing down the build that caused this regression.

Fix layer size for 3D textures with NPOT depth

---

src/Ryujinx.Ava/UI/Applet/ErrorAppletWindow.axaml
src/Ryujinx.Ava/UI/Applet/SwkbdAppletDialog.axaml
src/Ryujinx.Ava/UI/Controls/ApplicationGridView.axaml
src/Ryujinx.Ava/UI/Controls/ApplicationListView.axaml
src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml
src/Ryujinx.Ava/UI/Windows/DownloadableContentManagerWindow.axaml

Remove more usages of ReflectionBinding. Only the controller window still uses it.

Remove more usages of reflection binding

---

src/Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs

Allows Super Bomberman R-2 to go ingame.

Signal friends completion event and stub CheckBlockedUserListAvailability

---

src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
src/Ryujinx.Ava/UI/Views/Main/MainStatusBarView.axaml
src/Ryujinx.Ava/UI/Views/Main/MainStatusBarView.axaml.cs

Added button to show aspect ratio popup options in status bar, so we can easily see and select available aspect ratios.

Avalonia: Show aspect ratio popup options in status bar

---

src/Ryujinx.Ava/UI/Controls/SliderScroll.axaml
src/Ryujinx.Ava/UI/Controls/SliderScroll.axaml.cs
src/Ryujinx.Ava/UI/Views/Input/ControllerInputView.axaml
src/Ryujinx.Ava/UI/Views/Input/MotionInputView.axaml
src/Ryujinx.Ava/UI/Views/Input/RumbleInputView.axaml
src/Ryujinx.Ava/UI/Views/Main/MainStatusBarView.axaml
src/Ryujinx.Ava/UI/Views/Main/MainStatusBarView.axaml.cs
src/Ryujinx.Ava/UI/Views/Main/MainViewControls.axaml
src/Ryujinx.Ava/UI/Views/Settings/SettingsAudioView.axaml
src/Ryujinx.Ava/UI/Views/Settings/SettingsGraphicsView.axaml

This will allow changing slider value with mouse pointer wheel, the new value will be based on tick frequency

Avalonia: Make slider scrollable with mouse wheel

---

src/Ryujinx.HLE/FileSystem/VirtualFileSystem.cs

Fix a side effect of becoming more accurate. When reading a file from a `Sha256PartitionFileSystem`, you can't start a read in the middle of the hashed portion of the file and end the read after the end of the hashed portion. This hashed portion is usually the first 0x200 bytes.
Now when reading a ticket file, instead of reading the file byte-by-byte while parsing it, we read the entire file into a buffer and parse it from there.

Fix loading tickets from a Sha256PartitionFileSystem

---

Directory.Packages.props
src/Ryujinx.Audio.Backends.OpenAL/Ryujinx.Audio.Backends.OpenAL.csproj

OpenTK.OpenAL was renamed to OpenTK.Audio.OpenAL.

chore: Update OpenTK to 4.8.1

---

.github/dependabot.yml

Add groups for certain dependencies:
- Avalonia
- Silk.NET
- OpenTK
- SixLabors
- NUnit
Changes PR limit from 5 to 10.

CI: Dependabot Groups

---

Directory.Packages.props

Ava UI: Update Ava & Friends

---

Directory.Packages.props

#6115 if Dependabot wasn't bugged...

Deps: OpenTK Bump

---

src/Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IFileSystem.cs

This fixes and superseed #5418, nothing more.
(See original PR for description)

Fs: Log when Commit fails due to PathAlreadyInUse

---

src/Ryujinx.HLE/HOS/ModLoader.cs
src/Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/ILazyFile.cs
src/Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/LazyFile.cs

This fixes and superseed #5672 due to inactivity, nothing more. (See original PR for description)
Testing are welcome.
Close #5661

Mod: Do LayeredFs loading Parallel to improve speed

---

src/Ryujinx.Ava/Assets/Locales/en_US.json
src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml
src/Ryujinx/Ui/Widgets/GameTableContextMenu.Designer.cs

Addresses concerns raised in #6214.
Happy to drop the Gtk part because I have zero clue how to write that in Glade.

UI: Clarify Create Application Shortcut tooltip text

---

Directory.Packages.props
src/Ryujinx.Ava/UI/Applet/ControllerAppletDialog.axaml.cs
src/Ryujinx.Ava/UI/ViewModels/ControllerInputViewModel.cs

Updates `Avalonia.Svg` from 11.0.0.10 to 11.0.0.13
Updates `Avalonia.Svg.Skia` from 11.0.0.10 to 11.0.0.13
And reflect update changes as dependabot can't do it.
Superseed #6209

deps: Update Avalonia.Svg

---

src/Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostCtrlGpu/NvHostCtrlGpuDeviceFile.cs
src/Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostCtrlGpu/Types/NumVsmsArguments.cs
src/Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostCtrlGpu/Types/VsmsMappingArguments.cs

Needed by Tomb Raider I-III Remastered Starring Lara Croft. Only the first game seems to be playable right now, and only with "ignore missing services" due to other issues.

Stub VSMS related ioctls

---

src/Ryujinx.Cpu/LightningJit/Arm64/Target/Arm64/Decoder.cs

Some games have really long instruction sequences. Attempting to translate everything in one go causes problem, one of them being that the resulting code is too large and branch instructions can't "reach" all the code anymore, since branch instruction on Arm have a somewhat low limit of a few megabytes. To fix this issue, this change adds a upper limit on the number of (guest) instructions that might be translated at once.
This fixes a crash on the game Bluey: The Videogame with LightningJit, other games might be affected too.

LightningJit: Add a limit on the number of instructions per function for Arm64

---

src/Ryujinx.Ava/Program.cs

Avalonia: only enable gamescope workaround under it

---

src/Ryujinx.Common/Utilities/FileSystemUtils.cs
src/Ryujinx.Gtk3/UI/RendererWidgetBase.cs
src/Ryujinx/AppHost.cs

Regarding Issue #5553, I have implemented the title of the running application to the screenshot text.
This change has been applied to the base Ryujinx project and Ryujinx Ava project.

Add title of game to screenshot text

---

src/Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs
src/Ryujinx.Graphics.Gpu/Image/TextureManager.cs

This fixes a longstanding issue with resolution scale that could result in flickering graphics, typically the first frame something is drawn, or on camera cuts in cutscenes.
The root cause of the issue is that texture scale can be changed when binding textures or images. This typically happens because a texture becomes a view of a larger texture, such as a 400x225 texture becoming a view of a 800x450 texture with two levels. If the 400x225 texture is bound as a render target and has state [1x Undesired], but the storage texture is [2x Scaled], the render target texture's scale is changed to [2x Scaled] to match its new storage. This means the scale changed after the render target state was processed...
This can cause a number of issues. When render target state is processed, texture …

GPU: Rebind RTs if scale changes when binding textures

---

src/Ryujinx.HLE/FileSystem/ContentManager.cs
src/Ryujinx.HLE/FileSystem/ContentPath.cs

Only now I noticed those methods were throwing exception non-stop at the startup, so I've transitioned their control flow to a try-pattern. This refactor includes changing the method's return type to a boolean to signify operation success or failure and introducing an out parameter for the output value. This approach reduces the reliance on exceptions for non-exceptional conditions, streamlines error handling.

Enhance Error Handling with Try-Pattern Refactoring

---

src/Ryujinx.Graphics.Gpu/Image/TextureBindingsArrayCache.cs

Scaling textures used in texture arrays is not supported right now as we currently have no place to write the scales into. The shader generation already correctly sets the `ResScaleUnsupported` flag for all texture arrays, but the binding code did nothing with it. This change updates the code to account for the flag and blacklist scale on the texture if set.
Fixes rendering glitches on Penny's Big Breakaway when using resolution scale, however the game will no longer scale.
Before:
After:

Use ResScaleUnsupported flag for texture arrays

---

Directory.Packages.props

Fixes GHSA-5x7m-6737-26cr
Fixes GHSA-g85r-6x2q-45w7

Update "SixLabors.ImageSharp" to fix vulnerabilities

---

Ryujinx.sln.DotSettings

New key rules have been added to this config file in newer versions of ReSharper.

infra: Update ReSharper's DotSettings

---

README.md

Nothing too crazy, just updating compatibility numbers from https://github.com/Ryujinx/Ryujinx-Games-List/labels?q=status

Update README compatibility section

---

Directory.Packages.props
src/Ryujinx/UI/Applet/ControllerAppletDialog.axaml.cs
src/Ryujinx/UI/ViewModels/Input/InputViewModel.cs

Bump Avalonia.Svg

---

src/Ryujinx.UI.Common/App/ApplicationLibrary.cs

This PR fixes a regression from #6515, which caused Ryujinx to crash on startup if an invalid NSP was read.
Since the previous error handling already did catch the right exceptions, I extended the try-block to include the whole foreach loop. If one of the NCAs cannot be decrypted, it won't be able to get any other applications from the NSP anyway, so we can just return an empty list.
---
Fixes #7035

Catch exceptions when loading applications from invalid NSPs

---

src/Ryujinx/UI/ViewModels/DownloadableContentManagerViewModel.cs
src/Ryujinx/UI/ViewModels/TitleUpdateViewModel.cs

Small quality of life improvement, newly added updates will be automatically selected without the user needing to do it manually.
This also fixes this behaviour not working in DLC manager.

Ava UI: Auto select newly added updates & DLC

---

src/Ryujinx.Graphics.Vulkan/TextureView.cs

This barrier has always been missing, but it only became apparent when #7012 merged, as that stopped the emulator spamming pipeline barriers when the guest asked for a "fragment barrier".
I also added some barriers in case the target buffer used here is used by other commands, though right now it isn't.
Fixes a regression where water would turn white on AMD GPUs with the proprietary driver in BOTW. May fix other issues on this driver.

Vulkan: Add missing barriers for texture to buffer copy

---

src/Ryujinx/UI/Models/TitleUpdateModel.cs
src/Ryujinx/UI/ViewModels/TitleUpdateViewModel.cs

Ava UI: Handle updates containing non numeric characters

---

src/Ryujinx.HLE/HOS/Services/Nim/IShopServiceAccessServerInterface.cs

Fixes #7127 
Should make games like THE NEW DENPA MEN bootable without Ignore Missing Services.

nim:eca : Stub CreateServerInterface2

---

src/Ryujinx/UI/Windows/MainWindow.axaml.cs

Revert "Ava: Wait for CheckLaunchState() to complete to handle exceptions properly"
