Ryujinx/Ryujinx

Ryujinx/OsHle/Handles/HDomain.cs, Ryujinx/OsHle/Handles/HSessionObj.cs, Ryujinx/OsHle/Ipc/IpcHandler.cs, Ryujinx/OsHle/Objects/ObjHelper.cs
This fixes homebrew that does fopen() / fclose() / fopen() on the same file - without IDisposable, the file was not being closed when svcCloseHandle() was called.
This also fixes the spelling of 'GenertateObjectId' in HDomain.
=> Make HSessionObj implement IDisposable

Ryujinx/Cpu/Instruction/AInstEmitAluHelper.cs
`(Rd ^ Rn) & ~(Rn ^ Rm) < 0` is sufficient.
Relevant truth table:
```
Rn Rm Rd | V
0  0  0 | 0
1  1  1 | 0
0  1  0 | 0
0  1  1 | 0
1  0  0 | 0
1  0  1 | 0
0  0  1 | 1
1  1  0 | 1
```
=> AInstEmitAluHelper: Simplify EmitAddsVCheck

Ryujinx.Tests/Cpu/CpuTestScalar.cs
`[TestCase(0x80000000u, 0x00000000u, 0x00000000u)]`
and some of the commented out tests currently fail.
Can remove the NaN tests upon request.
=> Tests: Add Fmax_S test

Ryujinx.Core/OsHle/Services/ServiceFactory.cs, Ryujinx.Core/OsHle/Services/Set/ServiceSetSys.cs
This stubs set:sys functions GetColorSetId  and SetColorSetId. it allows the Homebrew Launcher 2.0+ to boot. this defaults to white theme
=> Stub set_sys functions

ChocolArm64/ATranslatedSub.cs, ChocolArm64/ATranslatedSubType.cs, ChocolArm64/ATranslator.cs, ChocolArm64/Decoder/ADecoder.cs, ChocolArm64/Instruction/AInstEmitException.cs, ChocolArm64/Instruction/AInstEmitFlow.cs, ChocolArm64/Translation/AILEmitter.cs, ChocolArm64/Translation/AILEmitterCtx.cs, ChocolArm64/Translation/ALocalAlloc.cs, Ryujinx.Core/OsHle/Services/Set/ServiceSetSys.cs
This enables background translation of subroutines on the CPU.
First, it trasnlates a slow version, only considering basic blocks. This runs slow but is fast to translate.
In the background, it translates a faster version of the same code. When the translation finishes, it swaps the slow version with the fast version.
This should improve startup speed.
A few things still needs to be done, like removing cold methods to avoid memory leaking. It can also be improved by not recompiling a faster version of methods that only runs once, or rarely runs.
=> Improve CPU initial translation speeds

Ryujinx.Core/OsHle/Svc/SvcSystem.cs
This fixes libnx from https://github.com/switchbrew/libnx/commit/6c72bf8273d57549acfb80502476eace4cbe36d0 onwards.
=> SVC: Add GetInfo type 20 (added in 5.0.0) to the list of explicitly unimplemented types.

Ryujinx.Core/OsHle/Services/Nv/ServiceNvDrv.cs, Ryujinx.Core/OsHle/Svc/SvcSystem.cs
Implements 0x4703 (NvGpuIoctlZbcSetTable) for /dev/nvhost-ctrl-gpu into ServiceNvDrv
=> [ServiceNvDrv] Add 0x4703 ([/dev/nvhost-ctrl-gpu] NvGpuIoctlZbcSetTable)

Ryujinx.Core/Logging.cs, Ryujinx.Core/OsHle/Svc/SvcSystem.cs
This add the calling information to the logs, and also moves the actual printing of the log to one method. calling information is show for all log levels. ~~Only the relative path in the source code structure is shown~~ Only the calling method is shown in logs, although the log entries contains full information about the log.
Example log = https://pastebin.com/Aqthk5kM
=> Show calling information in logs

Ryujinx.Core/Config.cs, Ryujinx.Core/Hid/Hid.cs, Ryujinx.Core/LogClass.cs, Ryujinx.Core/Logging.cs, Ryujinx.Core/OsHle/Handles/KProcessScheduler.cs, Ryujinx.Core/OsHle/Horizon.cs, Ryujinx.Core/OsHle/Process.cs, Ryujinx.Core/OsHle/Services/Am/IApplicationFunctions.cs, Ryujinx.Core/OsHle/Services/Aud/IAudioOut.cs, Ryujinx.Core/OsHle/Services/Bsd/IClient.cs, Ryujinx.Core/OsHle/Services/IpcService.cs, Ryujinx.Core/OsHle/Services/Lm/ILogger.cs, Ryujinx.Core/OsHle/Services/Nv/INvDrvServices.cs, Ryujinx.Core/OsHle/Services/Vi/NvFlinger.cs, Ryujinx.Core/OsHle/Svc/SvcHandler.cs, Ryujinx.Core/OsHle/Svc/SvcMemory.cs, Ryujinx.Core/OsHle/Svc/SvcSystem.cs, Ryujinx.Core/OsHle/Svc/SvcThread.cs, Ryujinx/Ryujinx.conf, Ryujinx/Ui/Program.cs
This adds log classes, and the option to filter logs based on them in config.
Filtering by a main log class will show all subclass logs, no matter if they are enabled or not. Like, filtering by `Kernel` will also show all `KernelScheduler`, `KernelIpc` and `KernelSvc` logs
=> Add logclass, made changes to logging calls

ChocolArm64/AOpCodeTable.cs, ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs
Abs is Int64.MinValue compliant.
(All instructions have been successfully tested.)
=> Add ABS (scalar & vector), ADD (scalar), NEG (scalar) instructions.

Ryujinx.Core/OsHle/Services/Aud/IAudioRendererManager.cs
Apparently the audio rendering buffer size has something to do with games booting so we reversed it with help of @gdkchan.
=> A REAL fix for some games.

Ryujinx.Core/OsHle/Kernel/SvcHandler.cs, Ryujinx.Core/OsHle/Kernel/SvcMemory.cs, Ryujinx.Core/OsHle/Kernel/SvcSystem.cs
SvcGetInfo 16 always should be returning 1(?)
After it returns 1, most games usually calls svcMapPhysicalMemory.
=> [SvcSystem/SvcMemory] Implement SvcGetInfo 16, SvcMapPhysicalMemory & SvcUnmapPhysicalMemory

ChocolArm64/Memory/AMemory.cs, ChocolArm64/Memory/AMemoryHelper.cs, Ryujinx.Core/Gpu/NvGpuVmm.cs, Ryujinx.Core/OsHle/Kernel/SvcSystem.cs, Ryujinx.Core/OsHle/Services/Am/IStorageAccessor.cs, Ryujinx.Core/OsHle/Services/Aud/IAudioDevice.cs, Ryujinx.Core/OsHle/Services/Aud/IAudioOut.cs, Ryujinx.Core/OsHle/Services/Bsd/IClient.cs, Ryujinx.Core/OsHle/Services/FspSrv/IFile.cs, Ryujinx.Core/OsHle/Services/Lm/ILogger.cs, Ryujinx.Core/OsHle/Services/Set/ISystemSettingsServer.cs, Ryujinx.Core/OsHle/Services/Vi/IHOSBinderDriver.cs
See #135. Greatly speeds up ReadBytes in MemoryHelper while still doing memory checks.
Memory permissions and access is checked one page at a time. The function checks if it's mapped and the permissions at the same time, and returns the first invalid address it finds (at the base of the page table entry). If you want to check without permission just pass 0 as the permission flag.
=> Add ranged memory reads and checks.

Ryujinx.HLE/Gpu/NvGpu.cs, Ryujinx.HLE/Gpu/NvGpuEngineDma.cs, Ryujinx.HLE/Gpu/NvGpuEngineDmaReg.cs, Ryujinx.HLE/Gpu/NvGpuFifo.cs
This is used to copy data on the GPU mapped memory. It's usually used to copy textures, and converting linear to block linear (swizzled) for example. Some games seems to use it for that purpose, one example of such game is Has Been Heroes. Maybe Pokkén Tournament aswell?
=> Partial GPU DMA support

ChocolArm64/Instruction/ASoftFallback.cs
Was doing a quick profile and noticed this took up quite a bit of time. BigInteger is general purpose for variable size and does a lot of heap allocation, so just using fixed integer math is much faster here.
When multiplying 100000 sets of integers from a prebuilt array, completes about 14x faster on average than using BigInteger, and gets the same result. Also passed `Ryujinx.Tests.Cpu.CpuTestMul`.
=> Faster soft implementation of smulh and umulh

Ryujinx.HLE/Gpu/NvGpuEngine3d.cs
Since this check is preceded by `IndexSize = 1 << IndexSize;` it can't ever be 0. I think a check for IndexCount was intended here.
=> NvGpuEngine3d: Fix uploading vertex arrays without index buffers.

ChocolArm64/Instruction/ASoftFallback.cs
Does the multiplication by casting the inputs to unsigned, then offsetting the result when operands are negative. 
Tested on 10485760 random combinations of numbers, the unit tests and the case that was broken before (long.MinValue * >=0x80000000).
=> Rework smulh to fix an edge case.

Ryujinx.Audio/Ryujinx.Audio.csproj, Ryujinx.Graphics/Gal/OpenGL/OGLBlend.cs, Ryujinx.Graphics/Gal/OpenGL/OGLEnumConverter.cs, Ryujinx.Graphics/Gal/OpenGL/OGLTexture.cs, Ryujinx.Graphics/Ryujinx.Graphics.csproj, Ryujinx.Tests/Ryujinx.Tests.csproj, Ryujinx/Ryujinx.csproj, Ryujinx/Ui/GLScreen.cs
Thanks to emmauss for the OpenTK fork.
Currently it requires on nuget.org (just like current OpenTK.NETCore dependency) to get it. OpenTK fails to build on Linux (or at least I couldn't build it), but using the NuGet works.
Some changes on Ryujinx had to be done because an up-to-date OpenTK had some changes in enumerations and input API.
About input, using OpenTK.Input.Keyboard.GetState() seems to return an empty state (no keys being pressed). Mouse clicks work, but its relative positions return weird values (moving the window and checking for mouse positions returns negative coordinates). That's why commit gets the states from their events since this seem to give the right values.
Touchscreen input was tested printing the coordinates on a console, not on a real game.
Some visible changes …
=> Port from OpenTK.NETCore to OpenTK.NetStandard

ChocolArm64/AThread.cs, ChocolArm64/Instruction/AInstEmitMemoryEx.cs, ChocolArm64/Memory/AMemory.cs, Ryujinx.HLE/OsHle/Handles/KProcessScheduler.cs, Ryujinx.HLE/OsHle/Handles/KThread.cs, Ryujinx.HLE/OsHle/Handles/ThreadQueue.cs, Ryujinx.HLE/OsHle/Kernel/SvcThread.cs, Ryujinx.HLE/OsHle/Kernel/SvcThreadSync.cs
By doing some stress test I was able to find more (yes, again...) thread synchronization issues. The below issues are fixed:
- CondVarWait mutex unlock + add to wait list was not atomic. This caused races in some games.
- CondVarSignal would sometimes write the updated mutex value to an invalid address.
- The ARM synchronization instructions (like LDAXR/STLXR) were mostly broken and races were possible even when using it correctly.
- Ordering of the arm load atomic instruction were wrong aswell (it tried to acquire the address after the load rather than before).
- TryToRun logic was broken, it would allow a thread to run on 2 different cores.
This PR should fix all the above issues.
Additionaly, during my testing, I also found a bug on libnx mutex, and also PRed a fix for that: …
=> Fix some thread sync issues

Ryujinx.Graphics/Gal/OpenGL/OGLShader.cs, Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeAlu.cs, Ryujinx.Graphics/Gal/Shader/ShaderIrInst.cs, Ryujinx.HLE/Gpu/NvGpuEngine3d.cs, Ryujinx.HLE/Gpu/TextureFactory.cs, Ryujinx.HLE/Gpu/TextureHelper.cs, Ryujinx.HLE/OsHle/Services/Nv/NvMap/NvMapHandle.cs, Ryujinx.HLE/OsHle/Services/Nv/NvMap/NvMapIoctl.cs
This fixes 3 issues found while testing puyo puyo tetris (probably affects other games aswell):
- Due to the wrong array length being used on a bidimensional array, only the first 6 constant buffers where actually set on the shader uniforms.
- SubOp 8 on the MUFU shader instruction is valid (it is the square root instruction), but the value was being masked and only 3 bits (0-7) were being used, so it was emiting a cossine operation for the square root aswell.
- NvMap Free should return the old reference count value, before the decrement, however it was returning the new value. This caused cleanup code to not function properly and resulted in wrong texture addresses being used. It expects the value to be != 0 to free the user resources.
This game was also using a 0 value for the texture …
=> Fix 3 graphics related issues

Ryujinx.Graphics/Gal/OpenGL/OGLShader.cs, Ryujinx.Graphics/Gal/OpenGL/OGLStreamBuffer.cs, Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs
Like title says, it uses UBOs instead of constant uniforms. It's implemented for Maxwell's constant buffers, not for other uniforms (flip, samplers).
It uses 16 KiB for every used constant buffers (that's an OpenGL standard limit), that's 4096 floats per buffer, hopefully games use less than that. It also uses vec4s instead of floats.
=> Implementation of UBOs instead of uniform constant arrays

Ryujinx.Graphics/Gal/IGalShader.cs, Ryujinx.Graphics/Gal/OpenGL/OGLShader.cs, Ryujinx.Graphics/Gal/Shader/GlslDecl.cs, Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeAlu.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeFlow.cs, Ryujinx.Graphics/Gal/Shader/ShaderOpCodeTable.cs, Ryujinx.Graphics/Gal/ShaderDeclInfo.cs, Ryujinx.HLE/Gpu/Engines/NvGpuEngine3d.cs
This change:
- Adds partial support for vertex program A shaders.
- Adds the FADD_I32 shader instruction.
- Fixes the FFMA_I encoding (it had a bit that was fixed to 0).
Vertex program A seems to be an extra shader stage on maxwell that is not used often. It seems that the gpu actually supports 2 vertex shaders, games like Farming Simulator Switch Edition needs it.
I added support on the GlslDecompiler (as adding support for it on the decoder would be way more complicated I believe).  It basically has an extra overload now that allows passing 2 shader addresses, in this case it translates the Vertex Program A as "main" and then calls Vertex Program B on the exit points. Its still necessary to handle cases like a value being passed on an attribute in VPA and then being read in VPB, then …
=> Add support for Vertex Program A and other small shader improvements

Ryujinx.Graphics/Gal/Shader/GlslDecl.cs, Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs
A buggy OpenGL driver fails to link with implicit host-required "position" attribute location. This PR forces the attribute to be in location 15.
It may be an argument that if a shader uses 16 attributes they would overlap. The problem is that the driver wouldn't find a position for it either.
I found this issue in Axiom Verge on NVidia (propietary).
=> Explicit GLSL "position" attribute location

ChocolArm64/AOpCodeTable.cs, ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs, ChocolArm64/Instruction/AInstEmitSimdHelper.cs, ChocolArm64/Translation/ILGeneratorEx.cs
Also added an EmitVectorPairwiseOp method used by the *P variants and modified ADDP to use it.
Not tested yet.
=> Add SMAXP, SMINP, UMAX, UMAXP, UMIN and UMINP cpu instructions

ChocolArm64/Instruction/AInstEmitAlu.cs, ChocolArm64/Translation/AILEmitterCtx.cs
It was emiting bogus condition checks when the adds instruction was used with a conditional instruction on the same basic block. Reported by roblabla.
FYI @LDj3SNuD, it may be worth to expand the tests to catch cases like this later, by writing some small programs with simple instruction sequences.
Example repro program:
```
mov x8, #0
mov x9, #0
adds x8, x8, x9
cset w10, CS
tbnz w10, #0, panic
mov x0, #2
ret
panic:
mov x0, #1
ret
```
X0 should contain 2 but it contains 1 when the test finishes.
=> Remove broken adds/cmn with condition check optimization

Ryujinx.Graphics/Gal/OpenGL/OGLFrameBuffer.cs, Ryujinx.HLE/Gpu/Engines/NvGpuEngine3d.cs
There is a regression when face culling is enabled. It may be linked to flipping issues.
Since face culling is something that's very unlikely to cause problems when disabled, this is a solution until flipping issues are solved.
Added a commented section in OGLFramebuffer to disable face culling.
=> Disable front facing and face culling to avoid regression

Ryujinx.Graphics/Gal/IGalRasterizer.cs, Ryujinx.Graphics/Gal/OpenGL/OGLRasterizer.cs, Ryujinx.HLE/Gpu/Engines/NvGpuEngine3d.cs, Ryujinx.HLE/Gpu/Engines/NvGpuEngine3dReg.cs
Implement the most common way to primtive restart indexed vertices.
Reg 0x0de8 (PRIM_RESTART_WITH_DRAW_ARRAYS) is still unimplemented.
=> Implement GPU primitive restart

Ryujinx.Audio/OpenAL/OpenALAudioOut.cs, Ryujinx.HLE/OsHle/Services/Aud/IAudioOutManager.cs
This fixes mono and 5.1 sound output. Additionally, it also fixes a regression when the sample rate is 0.
=> Allow sample rate of 0 on OpenAudioOut, fix 5.1 sound output

Ryujinx.Graphics/Gal/GalTextureFormat.cs, Ryujinx.Graphics/Gal/IGalRasterizer.cs, Ryujinx.Graphics/Gal/IGalTexture.cs, Ryujinx.Graphics/Gal/OpenGL/OGLCachedResource.cs, Ryujinx.Graphics/Gal/OpenGL/OGLEnumConverter.cs, Ryujinx.Graphics/Gal/OpenGL/OGLRasterizer.cs, Ryujinx.Graphics/Gal/OpenGL/OGLTexture.cs, Ryujinx.HLE/Gpu/Engines/NvGpuEngine3d.cs, Ryujinx.HLE/Gpu/Texture/TextureHelper.cs, Ryujinx.HLE/Gpu/Texture/TextureReader.cs
Currently the following scenario is possible:
- Vertex Buffer with Key 0xaaaa is used, handle 1 is generated and added to the dictionary.
- Handle 1 is bound to a VAO.
- Vertex Buffer with Key 0xaaaa (same vertex buffer, but this time used in a different VB entry slot) is used, handle 2 is generated. Since the key already exists on the dictionary, it deletes the old entry (deleting handle 1!) and updates the entry on the dictionary.
When Draw* is done to actually render that, one of the handles was deleted and the data no longer exists. Oops!
This situation is fixed by adding a locking mechanism. When `Lock` is called it won't delete anything. Instead, buffers that needs to be deleted are queued to be deleted later. When `Unlock` is called, all queued buffers are deleted, and also …
=> Add locking methods to the ogl resource cache

Ryujinx.HLE/OsHle/Services/Nv/NvHostCtrl/NvHostCtrlIoctl.cs, Ryujinx.HLE/OsHle/Services/Nv/NvResult.cs
If `nv!rmos_set_production_mode` is set to 0, the default impl with the fixed return is called. However, if we're running in production mode(default mode) then we should return the error code 0x30006
=> NvGetConfig with production/non production swapping

Ryujinx.HLE/Gpu/Engines/NvGpuFifo.cs, Ryujinx.HLE/Switch.cs, Ryujinx/Ui/GLScreen.cs, Ryujinx/Ui/Program.cs
Bypasses OpenTK's "jail".
Using OpenTK's event system we're able to dispatch GPU calls just once per frame, this PR calls it "as much as possible". This is not ideal because CPU cycles are wasted, but it's better than current approach.
It has included an event system to avoid this (locking host FPS to 60 most of the time) but it deadlocks almost every game so it's disabled.
It also forks OpenTK's event handling and GPU rendering in two different threads, this is mainly because OpenTK malfunctions when sleeps are called in its thread.
=> Loop GLScreen with custom method

Ryujinx.HLE/OsHle/Services/Time/ITimeZoneService.cs
The implementation of the TimezoneRule isn't matching hardware but
doesn't need to be accurate (games are only passing the value)
=> TimeZone implements cmd 0, 1, 2, 3, 4 and 100

Ryujinx.Graphics/Gal/IGalShader.cs, Ryujinx.Graphics/Gal/OpenGL/OGLShader.cs, Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs, Ryujinx.HLE/Gpu/Engines/NvGpuEngine3d.cs, Ryujinx.HLE/Gpu/Texture/TextureHelper.cs, Ryujinx.HLE/Gpu/Texture/TextureReader.cs
This fixes the following issues:
- There was no method to unbind shaders. So if a game used for example, a geometry shader once and never anymore, it would be still bound. An unbind method was added to allow unbinding the shader when the enable flag is set to 0 on the register.
- Code like `--2` (double negation) is not valid in glsl it seems. GlslDecompiler is now more strict about adding parenthesis, and will add it to all negative constants. So now instead of `--2` it writes `-(-2)`. This also impacts some unary operations that doesn't need it through.
- Reading/writing the built-in gl_Position is valid on geometry shader, so now this is allowed instead of using the `position` varying. It also now writes it aswell. This caused problems before because the fragment shader would try to …
=> Some small shader related fixes

Ryujinx.HLE/OsHle/Kernel/SvcThread.cs
Newer games uses 0xFFFFFFFFFFFFFFFF instead of 0 as yield. I believe that the new kernel allows that (maybe to be more inline with the other svcs were ulong max usually has a different behavior).
=> Allow using ulong max value as yield

Ryujinx.HLE/OsHle/Services/Nv/INvDrvServices.cs, Ryujinx.HLE/OsHle/Services/Nv/NvHostChannel/NvChannel.cs, Ryujinx.HLE/OsHle/Services/Nv/NvHostChannel/NvChannelName.cs, Ryujinx.HLE/OsHle/Services/Nv/NvHostChannel/NvHostChannelIoctl.cs, Ryujinx.HLE/OsHle/Services/Nv/NvHostChannel/NvHostChannelSubmitGpfifo.cs
This adds support for Ioctl2 and a few ioctls that are used by newer games.
- Ioctl2 seems to be used with a few ioctls. It seems to be used when the buffer being sent contains cpu addresses (not mapped on the gpu). We can just use Ioctl directly in this case.
- KickoffPbWithAttr does basically the same thing that SubmitGpfifo does, but instead of sending inline data on the struct, it reads the data pointed to by the address located at 0x0.
I also went ahead and did the initial work to enable multiple channels to share the same methods on NvHostChannelIoctl (mostly for SetTimeout).
=> Add support for ioctl2, SetTimeout and KickoffPbWithAttr

Ryujinx.HLE/Loaders/Executable.cs, Ryujinx.HLE/Loaders/Executables/IExecutable.cs, Ryujinx.HLE/Loaders/Executables/Nro.cs, Ryujinx.HLE/Loaders/Executables/Nso.cs, Ryujinx.HLE/OsHle/Homebrew.cs, Ryujinx.HLE/OsHle/Horizon.cs, Ryujinx.HLE/OsHle/Process.cs, Ryujinx.HLE/Switch.cs, Ryujinx.HLE/VirtualFileSystem.cs, Ryujinx/Ui/Program.cs
This PR implements the argv config key in Ryujinx to make it possible
to load libnx's "romfs" files.
This PR also propagates the file path to the executable instances.
=> hbabi: Implement argv (Fix #94)

ChocolArm64/AOpCodeTable.cs, ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs, ChocolArm64/Instruction/AInstEmitSimdCmp.cs, ChocolArm64/Instruction/AInstEmitSimdHelper.cs, ChocolArm64/Instruction/AInstEmitSimdMove.cs, Ryujinx.Tests/Cpu/CpuTestSimd.cs, Ryujinx.Tests/Cpu/CpuTestSimdReg.cs, Ryujinx.Tests/Cpu/Tester/Instructions.cs
Add 10 Tests: Extract Narrow (V); S/U Add/Sub Wide (V). 
Fix Xtn_V Tmp issue when Part != 0. 
Optimization of EmitVectorPairwiseOp() algorithm (reduction of the number of operations and their complexity). 
Fix a Lower Bit Reset issue with EmitSaturatingNarrowOp() when Scalar == true, add EmitVectorZeroLowerTmp().
---
Remove unnecessary Tmp stuff from EmitVectorWidenRmBinaryOp() and EmitVectorWidenRnRmOp().
"Remove" HasFlag() from the EmitVectorOp() and EmitVectorOpF() loops.
Update Tester.
Nits.
=> Implement Ssubw_V and Usubw_V instructions.

ChocolArm64/AOpCodeTable.cs
Ref #282.
We do this by generating a lookup table.
`ToFastLookupIndex` masks the bit `00111111110000000011110000000000` and compresses them to an index. This was chosen so that each bucket has a small number of possible instructions to linearly scan.
Arrays were used in the lookup table instead of linked lists because arrays generally have better memory characteristics (linear scanning is more performant).
=> AOpCodeTable: Speed up instruction decoding

Ryujinx.Graphics/Gal/OpenGL/OGLExtension.cs, Ryujinx.Graphics/Gal/OpenGL/OGLShader.cs, Ryujinx.Graphics/Gal/Shader/GlslDecl.cs, Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeAlu.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeHelper.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeMem.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeMove.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeSpecial.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecoder.cs, Ryujinx.Graphics/Gal/Shader/ShaderHeader.cs, Ryujinx.Graphics/Gal/Shader/ShaderIrInst.cs, Ryujinx.Graphics/Gal/Shader/ShaderIrOperAbuf.cs, Ryujinx.Graphics/Gal/Shader/ShaderOpCodeTable.cs, Ryujinx.Graphics/Gal/ShaderDumper.cs
This PR makes various assumptions in how vertex index are handled in geometry shaders by Maxwell. It stubs/half-implements shader instructions to get the expected vertex index, resulting in a weak implementation. I couldn't find a game actively using a geometry shader to see if the result is as expected, but generated code is valid GLSL.
Maxwell shader binaries do not include primitive input type, so these are stubbed to expect triangle input data.
It uses ARB_enhanced_layouts to set attribute locations (an OpenGL 4.4 extension), so geometry shaders are disabled on drivers without that extension. I tried using reference-by-name but drivers seem to have some differences in how they handle them, specially when a vertex shader does not declare that vaying.
It also changes how shaders are …
=> Implement Geometry shaders

.gitignore
VS 2017 creates file Ryujinx\Properties\launchSettings.json while changing debug properties in IDE. This PR ignores this file
thanks to @Cyuubi
=> .gitignore: ignore autogenerated launchSettings.json

ChocolArm64/Memory/AMemory.cs, Ryujinx.Graphics/Gal/IGalRasterizer.cs, Ryujinx.Graphics/Gal/IGalShader.cs, Ryujinx.Graphics/Gal/OpenGL/OGLRasterizer.cs, Ryujinx.Graphics/Gal/OpenGL/OGLShader.cs, Ryujinx.Graphics/Gal/OpenGL/OGLStreamBuffer.cs, Ryujinx.HLE/Gpu/Engines/NvGpuEngine3d.cs, Ryujinx.HLE/Gpu/Memory/NvGpuVmm.cs
Currently there are three copies being made before data is sent to the GPU:
1. Vmm.ReadBytes copies to a temporary byte[]
2. Gal copies from that byte[] into a buffer in OGLStreamBuffer (cbuf-only step)
3. Buffer is then sent to the OpenGL server
4. The OpenGL driver probably copies it to a temporary address and then sends it to the GPU
Instead of that, this PR gets host memory address and sends that to the OpenGL server (skipping 1 and 2).
=> Send data to OpenGL host without client-side copies

Ryujinx.HLE/OsHle/Services/Bcat/IBcatService.cs, Ryujinx.HLE/OsHle/Services/Bcat/IDeliveryCacheStorageService.cs, Ryujinx.HLE/OsHle/Services/Bcat/IServiceCreator.cs, Ryujinx.HLE/OsHle/Services/ServiceFactory.cs
It's required for doom to have BCAT:U linked but it not use any functions of bcat
=> Link BCAT:U & BCAT:A & BCAT:M & BCAT:S

Ryujinx.Graphics/Gal/OpenGL/OGLShader.cs
It should give a small performance boost on some games without breaking Tiny Nightmare.
=> Avoid calling buffer binding when shader didn't change

Ryujinx/Config.cs, Ryujinx/Ui/GLScreen.cs, Ryujinx/Ui/JoyConController.cs, Ryujinx/Ui/JoyConKeyboard.cs
Changes some frontend related stuff:
* Reworks input and disables unmapped controllers (that's unknown DirectInput controllers). Moves input parsing from GLScreen to a class.
* Alt+Enter or F11 maximizes the window. Pressing escape or one of those combinations again unmaximizes it, pressing escape again closes (as always).
And some other window-related stuff:
* Event polling was done without sleeping the thread, wasting CPU cycles in somethings that's not that important. It should give a performance boost for all games.
* Changes how touchscreen mouse input math is done (avoids float-point math when it's not needed).
Input issues with Cave Story+ when having a (DirectInput) controller plugged in were because triggers where signaled down, making a "moonwalk". It would be nice to have …
=> Window related changes

Ryujinx.HLE/OsHle/Ipc/IpcHandleDesc.cs, Ryujinx.HLE/OsHle/Ipc/IpcMessage.cs, Ryujinx.HLE/OsHle/Services/IpcService.cs, Ryujinx.HLE/OsHle/Services/Nifm/IRequest.cs
This fixes the invalid handle 0x00000000 spam on cave story and maybe other games, also adds the `GetObject` method that can be used to read objects send from user to services, needed by functions PushInData and others.
Had to change the `GetRequestState` from 0 to 1, otherwise cave story would just freeze calling it forever. Not sure about what the value means through, but I do believe it was working before because the event was wrong aswell.
=> Some fixes to IRequest on NIFM, support sending objects to services

ChocolArm64/Memory/AMemory.cs, Ryujinx.HLE/Gpu/Engines/NvGpuEngine3d.cs, Ryujinx.HLE/Gpu/Memory/NvGpuVmmCache.cs
Since games seem to ask for synchronization with `QueryControl`, resources updated between this calls are safe to be checked for change just once, avoiding some overhead.
Maybe `Uploaded*` lists should be moved to resource cache instead of being in Engine3d.
=> Cache changes

Ryujinx.Audio/OpenAL/OpenALAudioOut.cs
OpenAL's thread is wasting cycles waiting for data to dispatch.
Sleeping for 10ms didn't generate audio issues and avoided OpenAL's thread short circuit.
=> Sleep OpenAL thread

Ryujinx.HLE/OsHle/Horizon.cs, Ryujinx.HLE/OsHle/SystemStateMgr.cs
This PR adds `.npdm` file parsing into Ryujinx.HLE, though I don't know if this is the best solution.
=> Add Npdm parsing into Ryujinx.HLE

Ryujinx.Graphics/Gal/OpenGL/OGLRasterizer.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeAlu.cs
Fixes two issues:
- glVertexAttribPointer will aways convert the values to float no matter what. Vertex attributes with integer types were being converted to float, but being read on the shader as if they were integers. The fix is to use glVertexAttribIPointer that passes integers without conversion.
- The bit for the bf flag on the Iset instruction was wrong.
FYI @ReinUsesLisp.
=> Fix for integer vertex attributes and iset bf flag

Ryujinx.HLE/OsHle/IdDictionary.cs
It was not thread safe because it was possible that another thread would modify `FreeIdHint` between the time `Objs.TryAdd` adds it to the dictionary using the id as key, and the value is returned on `return FreeIdHint++;`.
=> Fix race condition on IdDictionary

Ryujinx.HLE/OsHle/Services/Am/ISelfController.cs
this function is useful for super mario odyssey after clicking on the resume button of the in-game pause menu.
=> Add SetScreenShotImageOrientation

ChocolArm64/Instruction/AInstEmitMemoryEx.cs
The offset was wrong and it was reading/writing data to the wrong location, potentially corrupting memory.
=> Fix load/store exclusive/atomic pairwise instructions

Ryujinx.HLE/OsHle/Services/Vi/IApplicationDisplayService.cs
Only the default display is listed. This allows Cartoon Network Battle Crashers to proceed.
=> Implemented IApplicationDisplayService:ListDisplays

Ryujinx.Graphics/Gal/Shader/ShaderDecodeHelper.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeMem.cs, Ryujinx.Graphics/Gal/Shader/ShaderIrOperGpr.cs
It should fix some vertex explosions.
Thanks to bunnei (from yuzu) for pointing out this issue.
=> Avoid gpr overwritting on Ld_C instruction

Ryujinx.Graphics/Gal/OpenGL/OGLEnumConverter.cs, Ryujinx.Graphics/Gal/OpenGL/OGLExtension.cs
I don't know if a game uses mirrored wraps, but IMO it's better to use them when available.
=> Use mirrored texture wraps when available

Ryujinx.Graphics/Gal/ImageFormatConverter.cs, Ryujinx.HLE/Gpu/Texture/TextureHelper.cs, Ryujinx.HLE/Gpu/Texture/TextureReader.cs
Calling to string with the `x2` format is not valid for enums, it will throw `System.FormatException: Format string can be only "G", "g",  "X", "x", "F", "f", "D" or "d".`. The fix is casting it to int first.
=> Fix exception throw message for unimpl texture formats

Ryujinx/Ui/ConsoleLog.cs, Ryujinx/Ui/Program.cs
Writing to the Console blocks until the write completes. This has the potential to block any code path that logs to the application logger.
By queuing up log messages in an asynchronous queue and returning without blocking, we can speed up code paths that heavily log to the console (for example stubbed services like ServiceHid).
From testing, this results in a roughly 8% time decrease between Ryujinx startup and the splash screen in Super Mario Odyssey on my system (in Debug) - 00:03:19.591 down to
00:03:04.354. Depending on your system, YMMV.
=> Asynchronously log messages to the Console window

Ryujinx.HLE/HOS/Services/Vi/NvFlinger.cs, Ryujinx.HLE/Switch.cs, Ryujinx/Config.cs, Ryujinx/Ryujinx.conf, Ryujinx/Ui/GLScreen.cs
This change locks nvflinger's queuebuffer till a vsync event is signalled, effectively limiting the game speed to 60 fps. I have not noticed any performance hit if speed is less than 100%, whether the toggle is on or off. `Tab` toggles the emulated vsync.
=> Lock GbpQueueBuffer till Vsync is signalled

Ryujinx.Graphics/Gal/OpenGL/OGLEnumConverter.cs
For some reason, the format was wrong on both `ImageUtils` and `OGLEnumConverter`. It was using Uint even though the original format, and the format being returned on `OGLEnumConverter` are float formats. I fixed the first on #418 but not the later.
=> Fix d32s8 format on OGLEnumConverter

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Process.cs, Ryujinx.HLE/HOS/SystemState/SystemStateMgr.cs, Ryujinx.HLE/HOS/SystemState/TitleLanguage.cs, Ryujinx/Ui/GLScreen.cs
This adds the current game title on the titlebar. if control data is found in the nsp/xci, it uses the real game title that corresponds to the current language of the emulated system, which if not available, uses the title for American English( default is American English by the way). If control data is not found, it shows the title id.
Changing language is not available now.
=> Show Game Title on Titlebar

Ryujinx.Graphics/Gal/IGalRenderTarget.cs, Ryujinx.Graphics/Gal/OpenGL/OGLRenderTarget.cs, Ryujinx.Graphics/GpuResourceManager.cs
Simplifies GpuResourceManager code a bit.
Avoids calling Vmm.IsRegionModified on rendertarget resource bind and uses a PBO instead of CPU memory (which also avoids stalling execution) for reinterpretation.
It gives a nice boost on my end (at least on SMO's menu):
=> General improvements for GpuResourceManager

Ryujinx.Graphics/Gal/IGalRenderTarget.cs, Ryujinx.Graphics/Gal/OpenGL/OGLEnumConverter.cs, Ryujinx.Graphics/Gal/OpenGL/OGLExtension.cs, Ryujinx.Graphics/Gal/OpenGL/OGLRenderTarget.cs, Ryujinx.Graphics/Gal/OpenGL/OGLShader.cs, Ryujinx.Graphics/GpuResourceManager.cs, Ryujinx.Graphics/NvGpuEngine3d.cs, Ryujinx.HLE/HOS/Services/Vi/NvFlinger.cs, Ryujinx/Ryujinx.conf
`RT_SEPARATE_FRAG_DATA` doesn't seem to be set to commercial games. Until we found out why (probably its set by the OS?), this considers it always being on. I also simplified how OpenGL framebuffers are being bound, but it ends up with more superfluous OpenGL calls.
This requires [ARB_viewport_array](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_viewport_array.txt) (or OpenGL 4.1) to set individual viewports per attachment.
=> Fix multiple rendertargets

ChocolArm64/ATranslatorCache.cs
Previous values were too strict and resulted in functions being deleted too often and in stuttering on some games, this improves that.
- Minimum time since last use for deletion was increased from 30 seconds to 2 minutes.
- Max cache size (in ARM code size, not IL or x86 code size unfortunately) was increased from 2 MB to 4 MB.
- Minimum call count for updating cache entries timestamp was decreased from 1000 calls to 250 calls.
=> Tweak cpu cache deletion policy values

Ryujinx.HLE/HOS/Kernel/KMemoryManager.cs, Ryujinx.HLE/HOS/Process.cs, Ryujinx.HLE/HOS/Services/Ldr/IRoInterface.cs, Ryujinx.HLE/HOS/Services/Ldr/LoaderErr.cs, Ryujinx.HLE/HOS/Services/ServiceFactory.cs, Ryujinx.HLE/Loaders/Executable.cs, Ryujinx.HLE/Loaders/Executables/IExecutable.cs, Ryujinx.HLE/Loaders/Executables/Nro.cs, Ryujinx.HLE/Loaders/Executables/Nso.cs, Ryujinx.HLE/Logging/LogClass.cs
This is required by Super Mario Party.
This PR also adds MapProcessCodeMemory and UnmapProcessCodeMemory functions in KMemoryManager. Those two calls might not reflect what the SVC of the same names do.
=> Implement IRoInterface

Ryujinx.Audio/OpenAL/OpenALAudioOut.cs
Without the lock, `TryDequeue` and `Enqueue` could be called at the same time (on `CallReleaseCallbackIfNeeded` and `AppendBuffer`). This causes problems since `Queue` is not thread safe.
=> Fix race condition on OpenALAudioOut

Ryujinx.Graphics/Gal/GalPipelineState.cs, Ryujinx.Graphics/Gal/GalVertexAttrib.cs, Ryujinx.Graphics/Gal/GalVertexBinding.cs, Ryujinx.Graphics/Gal/IGalRasterizer.cs, Ryujinx.Graphics/Gal/OpenGL/OGLEnumConverter.cs, Ryujinx.Graphics/Gal/OpenGL/OGLPipeline.cs, Ryujinx.Graphics/Gal/OpenGL/OGLRasterizer.cs, Ryujinx.Graphics/Gal/OpenGL/OGLRenderTarget.cs, Ryujinx.Graphics/NvGpuEngine3d.cs, Ryujinx.Graphics/QuadHelper.cs, Ryujinx.Graphics/Texture/ImageUtils.cs, Ryujinx.Graphics/Texture/TextureFactory.cs
This PR:
- Fixes Quads and QuadStrip primitive modes on DrawArrays. It was using the respective OpenGL primitive modes, however they were deprecated on OpenGL 3.x, so it doesn't work anymore. I replaced it with multiple calls to DrawArrays with an offset, and a count of 4. It's not optimal, however the only other option I can think of is creating another vertex buffer, or using a index buffer. Draw Elements now doesn't support Quads or QuadStrip, it should throw an exception if those two are used.
- Allow constant attributes to work properly. When the stride is 0, it should read the attribute from the same location every time, effectively being a constant value, however on OpenGL the value 0 being used as stride is special, it assumes that the data is tightly packed.
=> Quads, QuadStrip, const attributes and half-float attributes support

Ryujinx.Graphics/Gal/GalPipelineState.cs, Ryujinx.Graphics/Gal/OpenGL/OGLPipeline.cs, Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeAlu.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeHelper.cs, Ryujinx.Graphics/NvGpuEngine3d.cs, Ryujinx.Graphics/NvGpuEngine3dReg.cs, Ryujinx.Graphics/Texture/ImageUtils.cs
This PR:
- Adds support for saturation on 3 shader instructions: FADD, FMUL and FMLA.
- Fixes ReadTexture alignment so that each row is aligned into a 4 bytes boundary (needed by OpenGL).
- Adds support for glColorMask.
=> Add support for saturation on some shader instructions, fix ReadTexture alignment and add ColorMask support

Ryujinx.HLE/HOS/Services/FspSrv/IFileSystem.cs
A directory can be open more than one time. This fix issues with
homebrews opening the same directory multiple time. (like ftpd)
=> Remove IFileSystem::OpenDirectory extraneous check

Ryujinx.Graphics/Gal/GalPipelineState.cs, Ryujinx.Graphics/Gal/OpenGL/OGLPipeline.cs, Ryujinx.Graphics/NvGpuEngine3d.cs, Ryujinx.Graphics/NvGpuEngine3dReg.cs
There are multiple (16) depth range values, it assumes that only the first one is used for now.
=> Add depth range support on the GPU

Ryujinx.Graphics/Gal/OpenGL/OGLRenderTarget.cs, Ryujinx.Graphics/Gal/OpenGL/OGLTexture.cs, Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeAlu.cs
Fixes two issues:
- It was possible for render targets to use deleted handles due to an "optimization" that would compare the Key (render target address) with the old one, and if it was the same it would skip setting the new texture. This doesn't work if the texture is "reinterpreted" by creating a new texture for example. The address is still the same, but the handle changes. I still kept the "optimization", but comparing handles rather than addresses. Additionally, when the texture is removed the cached handle values are invalidated.
- Fix a compilation issue where the shader translator wouldn't emit a `return` on functions with just a KIL instruction inside (discard). Also some nits to pretify shader code output.
=> Fix for render target and a shader compilation issue

Ryujinx.HLE/HOS/Kernel/KThread.cs
This should be inside the lock, otherwise another thread may modify those values and it may use the old value.
=> Move prio/core locals inside the lock on yield

Ryujinx.Graphics/Gal/GalPipelineState.cs, Ryujinx.Graphics/Gal/OpenGL/OGLPipeline.cs, Ryujinx.Graphics/NvGpuEngine3d.cs, Ryujinx.Graphics/NvGpuEngine3dReg.cs
This fixes the color mask common flag (it's not another depth mask value, its just used to switch between using just the first value or the entire array, at least according to nouveau). Additionally it initializes the first color mask to 1, 1, 1, 1 by default since some games never writes to this register.
=> Fix Color Mask values

ChocolArm64/Instruction/AInstEmitSimdArithmetic.cs, ChocolArm64/Instruction/AInstEmitSimdShift.cs, ChocolArm64/Translation/AILEmitterCtx.cs
_**AInstEmitSimdArithmetic:**_
**Saddl_V, Uaddl_V:**
- Max Sse Req. : Sse41 (ConvertToVector128Int* [16, 32, 64])
- Types Covered: All
**Shadd_V, Uhadd_V:**
- Max Sse Req. : Sse2
- Types Covered: All but one (B)
**Shsub_V, Uhsub_V:**
- Max Sse Req. : Sse2
- Types Covered: All but one (S)
**Smlal_V, Umlal_V:**
- Max Sse Req. : Sse41 (ConvertToVector128Int* [16, 32]; MultiplyLow [32])
- Types Covered: All but one (S)
**Smlsl_V, Umlsl_V:**
- Max Sse Req. : Sse41 (ConvertToVector128Int* [16, 32]; MultiplyLow [32])
- Types Covered: All but one (S)
**Srhadd_V, Urhadd_V:**
- Max Sse Req. : Sse2
- Types Covered: All but one (S)
**Ssubl_V, Usubl_V:**
- Max Sse Req. : Sse41 (ConvertToVector128Int* [16, 32, 64])
- Types Covered: All
_**AInstEmitSimdShift:**_
**Srshr_V:**
- Max Sse Req. : Sse2
- …
=> Add Sse Opt. for S/Uaddl_V, S/Uhadd_V, S/Uhsub_V, S/Umlal_V, S/Umlsl_V, S/Urhadd_V, S/Usubl_V Inst.; and for S/Urshr_V, S/Ursra_V Inst..

Ryujinx.Graphics/NvGpuEngine2d.cs, Ryujinx.Graphics/NvGpuEngine2dReg.cs
So far all games I've seen that does copies of textures with different sizes seems to expect it to be cropped. Maybe there's a bit to control that somewhere, I guess we'll figure out if we find a game that expects the texture to be resized.
Additionally, removed the old trigger method since it was wrong.
=> Crop instead of resizing on 2d engine texture copies

ChocolArm64/ATranslatorCache.cs, Ryujinx.Common/PerformanceCounter.cs, Ryujinx.Graphics/Gal/OpenGL/OGLCachedResource.cs, Ryujinx.Graphics/NvGpuEngine3d.cs, Ryujinx.HLE/HOS/Kernel/KCoreContext.cs, Ryujinx.HLE/Hid/Hid.cs
Currently, we make use of `Environment.TickCount` in a number of places. This has some downsides, mainly being that the `TickCount` is a signed 32-bit integer, and has an effective limit of ~25 days before overflowing and wrapping around. Due to the signed-ness of the value, this also caused issues with negative numbers. This resolves these issues by using a 64-bit tick count obtained from Performance Counters (via the `Stopwatch` class). This has the favorable side effect of being significantly more accurate than the `TickCount`.
The biggest benefit of this change is that it ensures the monotonicity of the value returned (unless you leave your computer on for over 90,000 years).
I've left the member name as `ElapsedTicks`, because we originally used `TickCount`, however a more accurate …
=> Timing: Optimize Timestamp Aquisition

ChocolArm64/ABitUtils.cs
The method was wrong because the value is signed, so it was doing an arithmetic right shift. The fix is changing the type to ulong. Also added an overload that accepts long and calls the unsigned one. Removed some unused methods while I was at it.
=> Fix the rotate right method on ABitUtils

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/Ryujinx.HLE.csproj, Ryujinx/Config.cs
- Load tickets from XCI files when needed
LibHac updates:
- When a required key is missing, the error gives info about which key is missing and why it's needed
- Hash-verified storage is only hashed the first time a block is read, resulting in performance gains
- Partition FS verification is enabled
Fixes #470
=> Misc content loading improvements

ChocolArm64/Instructions/InstEmitFlow.cs
The value was being overwritten with the return address, resulting in a jump to the wrong location. The fix is saving the register value into a temp before seting the return address and then jumping to the address on the temp.
=> Fix BLR when the source reg is X30

Ryujinx.Graphics/Gal/OpenGL/OGLCachedResource.cs, Ryujinx.Graphics/Gal/OpenGL/OGLConstBuffer.cs, Ryujinx.Graphics/Gal/OpenGL/OGLRasterizer.cs, Ryujinx.Graphics/Gal/OpenGL/OGLTexture.cs
Some games may use different addresses for the same data (probably happens when it deletes and re-creates a buffer all the time, which is inefficient but still...). Since resources are cached by resource, this will cause the creation of a growing number of resources on the host, which may eventually cause the system to get out of memory. This PR attempts to solve this by forcing the cached resources to be removed if memory usage exceeds a given threshold.
Now total amount of gpu memory that the emulator can use is 1GB, being currently divided as 768MB for textures, 64MB for const buffers, 128MB for vertex buffers and 64MB for index buffers. The values may need tweaking, it was just what I came up with but I will need to check the impact on perf. Tried to give more mem to textures since …
=> Force cache to remove entries when memory usage exceeds a given threshold

Ryujinx.Audio/Renderers/SoundIo/SoundIoAudioOut.cs
Given some drivers have issues with SoundIO (for the time being), this attempts to detect if SoundIO can open the default audio device, and then return false in IsSupported if it can't.
=> Audio: Properly implements audio fallback for SoundIO

Ryujinx.Graphics/Gal/OpenGL/OGLTexture.cs, Ryujinx.Graphics/NvGpuEngine3d.cs
Games that uses SRGB textures with framebuffers needs that to display correctly.
I don't know if there's any performance impact in keeping it always enabled.
=> Enable SRGB framebuffers by default

Ryujinx.Graphics/Gal/OpenGL/OGLShader.cs, Ryujinx.Graphics/Gal/Shader/GlslDecl.cs, Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs, Ryujinx.ShaderTools/Program.cs
This fix a crash on Ryujinx.ShaderTools caused by the absence of an
OpenGL context.
=> Move MaxUboSize definition

Ryujinx.HLE/HOS/SystemState/SystemStateMgr.cs, Ryujinx/Config.cs, Ryujinx/Ryujinx.conf
This PR supersedes #532, by improving configured Chinese language so that using TraditionalChinese and SimplifiedChinese won't cause exceptions due to parsing [SystemLanguage](https://switchbrew.org/wiki/Settings_services#LanguageCode) enum as [TitleLanguage](https://switchbrew.org/wiki/Control.nacp#Title_Entry).
=> System Language can be configurable

Ryujinx.Graphics/Graphics3d/NvGpuEngine3d.cs, Ryujinx.Graphics/QuadHelper.cs
Optimizes quad rendering by converting to triangles when uploading (reduces gpu load by 2/3rds in Shantae)
Also fixes minor bug regarding IndexFirst not being converted correctly with quad and quad strips
=> Quad to triangle optimization

Ryujinx.HLE/FileSystem/Content/ContentManager.cs, Ryujinx.HLE/FileSystem/PFsProvider.cs, Ryujinx.HLE/FileSystem/RomFsProvider.cs, Ryujinx.HLE/HOS/Font/SharedFontManager.cs, Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/FspSrv/IFileSystemProxy.cs, Ryujinx.HLE/HOS/Services/Set/ISystemSettingsServer.cs, Ryujinx.HLE/Ryujinx.HLE.csproj, Ryujinx/Config.cs
Copy/pasted applicable changes from changelog
- Use a new `IStorage` interface throughout the library instead of `Stream`
- This interface is more similar to the `IStorage` interface used by Horizon.
- Instead of having a Stream that keeps track of the current position, IStorage accepts an offset, buffer, and length when reading or writing.
- Unlike a Stream, an IStorage instance can be shared between multiple consumers without issue
- `Stream.AsStorage()` and `IStorage.AsStream()` methods are provided for switching between `Stream` and `IStorage`
- Improve AES-XTS performance by ~16x
- Improve AES-CTR performance by 2x
- Allow more disposal methods to cascade down to the base storage
=> Update to LibHac 0.2.0

ChocolArm64/Instructions/CryptoHelper.cs, ChocolArm64/Instructions/InstEmitSimdArithmetic.cs, ChocolArm64/Instructions/InstEmitSimdCmp.cs, ChocolArm64/Instructions/InstEmitSimdCvt.cs, ChocolArm64/Instructions/InstEmitSimdHelper.cs, ChocolArm64/Instructions/InstEmitSimdMove.cs, ChocolArm64/Instructions/SoftFallback.cs, ChocolArm64/Instructions/SoftFloat.cs, ChocolArm64/OpCodeTable.cs, Ryujinx.Tests/Cpu/CpuTestSimdRegElem.cs
ChocolArm64\Instructions\CryptoHelper.cs:
`FromVectorToByteArray()` -> Used `Sse2.Store()`
`FromByteArrayToVector()` -> Used `Sse2.LoadVector128()`
ChocolArm64\Instructions\InstEmitSimdArithmetic.cs,
ChocolArm64\Instructions\InstEmitSimdCmp.cs:
Removed some unnecessary `Optimizations.UseSse`
=> Add Smlal_Ve, Smlsl_Ve, Smull_Ve, Umlal_Ve, Umlsl_Ve, Umull_Ve Inst.; add Tests. Add Sse Opt. for Trn1/2_V and Uzp1/2_V Inst. Nits.

Ryujinx.Graphics/Gal/Shader/GlslDecl.cs, Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeAlu.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeMem.cs, Ryujinx.Graphics/Gal/Shader/ShaderDecodeOpCode.cs, Ryujinx.Graphics/Gal/Shader/ShaderIrOperGpr.cs, Ryujinx.Graphics/Gal/Shader/ShaderOpCodeTable.cs, Ryujinx.Graphics/Gal/Shader/ShaderRegisterSize.cs, Ryujinx.Graphics/Gal/ShaderDumper.cs
Only HADD, HMUL (register only variants) and TEXS.FP16 are supported so far. Currently it just uses 32-bits floats to store the values, since older gpus doesn't have any support for packed half float values. In the future we may use halfs for the gpus that supports it.
Currently it uses a different set of variables for half and single precision float values. However, on the real GPU they share the same register (with 2 half-precision floating point values on each register), so this approach will not work correctly  on all cases (for example, a MOV from one register to another is not going to work since it moves the 32-bits register). One thing that would work properly is packing and unpacking the 16-bits values into 32-bits registers, but doing this without support from the gpu …
=> Initial support for shader half float instructions

Ryujinx.HLE/HOS/Services/Aud/AudioRenderer/IAudioRenderer.cs, Ryujinx.HLE/HOS/Services/Aud/AudioRenderer/VoiceContext.cs
On some games, it seems to add an empty buffer (before the game even calls AppendWaveBuffer), and this was causing the played wave buffers count to be incremented. However it caused bugs on the game, because it doesn't expect that and it caused the released buffers count to be decremented to -1 on `nn::audio::GetReleasedWaveBuffer`, which later leads to memory corruption.
I'm not sure if this is the right fix.
May affect the following games, they need to be retested:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/76
https://github.com/Ryujinx/Ryujinx-Games-List/issues/77
https://github.com/Ryujinx/Ryujinx-Games-List/issues/79
https://github.com/Ryujinx/Ryujinx-Games-List/issues/80
https://github.com/Ryujinx/Ryujinx-Games-List/issues/88 …
=> Do not increment played wave buffers count for empty wave buffers

Ryujinx/Configuration.cs, Ryujinx/Program.cs
Fixes configuration file resolution by looking in the currently running applications directory, rather than the working directory (which might be a ROM directory if the user used drag/drop to load a ROM).
This also fixes the directory the file logger logs into.
Resolves #579
=> Config: Resolve config and file log to application directory

Ryujinx.HLE/HOS/Services/Vi/IApplicationDisplayService.cs, Ryujinx.HLE/HOS/Services/Vi/ScalingMode.cs
For now, it seems Nintendo just map 1:1 between the two enums.
=> Vi: Implement ConvertScalingMode

Ryujinx/Configuration.cs
A typo in the MulticoreScheduling configuration property prevented it from being deserialized correctly.
I'll PR some further changes later to better catch these hard to spot issues.
=> Config: Correct MulticoreScheduling configuration casing

ChocolArm64/Instructions/InstEmitAlu.cs, ChocolArm64/Translation/ILEmitterCtx.cs
Apply the same optimzation that is applied to CMP/SUBS. Rather than doing the condition check based on the NZCV flags, just emit a single IL branch + comparision OpCode. This allow the jit to produce a single cmp + jump sequence, rather than all the code to calculate flag values and the check afterwards.
A few restrictions for the CMN/ADDS case:
- Unsigned comparisons are not allowed, as carry has different values on addition vs. subtractions.
- The value should be immediate (because it's not possible to negate the lowest negative value on a signed integer). The immediate value itself should be positive all the time, so that's fine. When the value comes from a register, it is unknown, so the optimization is not valid in this case.
Perf improvement is probably pretty small, as those …
=> Optimize CMN/ADDS to do a single comparison like CMP/SUBS

Ryujinx.HLE/HOS/Services/Vi/IApplicationDisplayService.cs, Ryujinx.HLE/HOS/Services/Vi/ScalingMode.cs
This improves the `ConvertScalingMode` implementation, by correcting some issues, and implementing a missing error check:
- The Src/DstScalingMode enums were swapped.
- One error condition check was missing.
Would be nice to re-test with games that depends on it.
=> Implement ConvertScalingMode properly

Ryujinx.Graphics/Graphics3d/NvGpuEngine3d.cs
This fixes the "invalid front face 0" kind of error (introduced with #583) for games that does not initialize this register.
=> Initialize FrontFace register with a default value

Ryujinx.Tests/Cpu/CpuTestMisc.cs, Ryujinx.Tests/Cpu/CpuTestSimdCvt.cs
```
Fcvtzs_Gp_Fixed & Fcvtzu_Gp_Fixed:
Total test number: 12800. Passed: 12800. Failed: 0. Ignored: 0.
The execution of the tests was successful.
Test run time: 1,7778 minutes
```
```
Scvtf_Gp_Fixed & Ucvtf_Gp_Fixed:
Total test number: 12672. Passed: 12672. Failed: 0. Ignored: 0.
The execution of the tests was successful.
Test run time: 1,6503 minutes
Note: within `±1 ulp` for `UCVTF <Dd>, <Xn>, #<fbits>`.
```
Nits.
=> Add Tests for instructions Fcvtzs_Gp_Fixed & Fcvtzu_Gp_Fixed, Scvtf_Gp_Fixed & Ucvtf_Gp_Fixed.

ChocolArm64/Instructions/InstEmitFlow.cs, ChocolArm64/Instructions/InstEmitFlow32.cs, ChocolArm64/Instructions/InstEmitFlowHelper.cs, ChocolArm64/Optimizations.cs, ChocolArm64/Translation/CallType.cs, ChocolArm64/Translation/ILBlock.cs, ChocolArm64/Translation/ILEmitterCtx.cs, ChocolArm64/Translation/ILLabel.cs, ChocolArm64/Translation/ILMethodBuilder.cs, ChocolArm64/Translation/ILOpCode.cs, ChocolArm64/Translation/ILOpCodeBranch.cs, ChocolArm64/Translation/ILOpCodeCall.cs, ChocolArm64/Translation/ILOpCodeConst.cs, ChocolArm64/Translation/ILOpCodeLoad.cs, ChocolArm64/Translation/ILOpCodeLoadField.cs, ChocolArm64/Translation/ILOpCodeLoadState.cs, ChocolArm64/Translation/ILOpCodeLog.cs, ChocolArm64/Translation/ILOpCodeStore.cs, ChocolArm64/Translation/ILOpCodeStoreState.cs, ChocolArm64/Translation/LocalAlloc.cs, ChocolArm64/Translation/RegisterUsage.cs, ChocolArm64/Translation/TranslatedSub.cs, ChocolArm64/Translation/Translator.cs, ChocolArm64/Translation/TranslatorQueue.cs, ChocolArm64/Translation/TranslatorQueueItem.cs, ChocolArm64/Translation/VarType.cs, Ryujinx/Config.jsonc, Ryujinx/Configuration.cs, Ryujinx/_schema.json
This implements two optimizations:
- Do not save caller saved registers on the thread state, when the function is "complete".  Caller saved register, as the name implies, should be saved by the caller, after calling any function, and the callee is free to modify those registers. If the function needs to preserve the values on those registers after a call, it is supposed to push it to the stack, and pop after the function call. So, we don't need to save those registers on the thread state, since they should only be used locally (within a function).
Of couse, this optimization is only valid if the code is following the arm64 abi (which all the applications should be following), but anyway, I consider this a rather "dangerous" optimization, so I added a new config entry to disable it, called …
=> Misc. CPU optimizations

Ryujinx.Tests/Cpu/CpuTestSimdImm.cs
```
Total test number: 18576. Passed: 18576. Failed: 0. Ignored: 0.
The execution of the tests was successful.
Test run time: 6,1774 minutes
Note: with `Optimizations.UseAllSseIfAvailable = true/false`
```
=> Add Tests for instructions Movi_V & Mvni_V.

Ryujinx.Graphics/Gal/OpenGL/OglTexture.cs
Implements support for compressed cubemaps.
M2MF doesn't currently support copying compressed textures correctly, however this also affects 2D textures and not just cubemaps so I feel this can be resolved in another PR.
This should allow games that previously booted, but now throw a texture type not implemented exception since the merge of #525, to boot again, excluding games that required Texture Buffer support.
This is basically an implementation of @Thog's code.
=> Compressed cubemap support

Ryujinx.Graphics/Graphics3d/NvGpuEngineM2mf.cs
Correctly calculates the number of iterations required to copy all the data from compressed textures
This solves an issue where it was copying quarter of the full texture width when dealing with compressed textures
=> Compressed M2mf texture copy fix

Ryujinx.HLE/Exceptions/ServiceNotImplementedException.cs, Ryujinx.HLE/HOS/Ipc/IpcHandler.cs, Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcIpc.cs, Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs, Ryujinx.HLE/HOS/ServiceCtx.cs
When a ServiceNotImplemented exception is thrown, it's useful to obtain a guest stack trace as this usually includes critically important information in understanding what exactly was called and how. The stack trace also includes the SDK function and call stack that was used to call the IPC function, which is useful for deciphering unknown or undocumented service functions.
This PR prints a stack trace in the IPC info dump that is logged when a service function is not implemented. It also adds a few extra functions, and refactors some of the existing code to better accommodate more use-cases (eg. no printing the stack trace directly to the log, rather returning it).
I've also obsoleted the `PrintGuestStackTrace` in `HleProcessDebugger` function, as in nearly every situation, getting the …
=> Print Guest Stack Trace in ServiceNotImplemented Exception

ChocolArm64/Instructions/InstEmitSimdCmp.cs, ChocolArm64/Instructions/InstEmitSimdCvt.cs, ChocolArm64/Instructions/InstEmitSimdHelper.cs, ChocolArm64/Instructions/InstEmitSimdMove.cs, ChocolArm64/Instructions/VectorHelper.cs, ChocolArm64/OpCodeTable.cs, Ryujinx.Tests/Cpu/CpuTestSimd.cs, Ryujinx.Tests/Cpu/CpuTestSimdCvt.cs, Ryujinx.Tests/Cpu/CpuTestSimdShImm.cs
Fixed a bug about all the fp to integer conversion instructions (signed & unsigned); where all those fp values close to T.MaxValue were mistakenly converted to ~T.MaxValue.
Fixed the instruction table (Fcvtzs_V_Fixed & Fcvtzu_V_Fixed).
Uniformed the use of the zero vector to the float type only.
Nits.
=> Sse optimized all the fp to integer conversion instructions (signed) with Tests (signed & unsigned).

Ryujinx.Graphics/Gal/OpenGL/OglTexture.cs
Add missing `TextureCubeMapArray` texture type alias to other texture creation path.
=> Add missing TextureCubeMapArray texture type entry

ChocolArm64/Instructions/InstEmitSimdCvt.cs, Ryujinx.Tests/Cpu/CpuTestSimd.cs, Ryujinx.Tests/Cpu/CpuTestSimdCvt.cs, Ryujinx.Tests/Cpu/CpuTestSimdShImm.cs
This PR is intended as a complement to #655.
The Sse optimizations related to the General Purpose fp-to-integer conversion instructions have been removed due to the poor performance improvement in relation to the size and complexity of the signed and unsigned (above all) implementations.
=> Sse optimized the Vector & Scalar fp-to-integer conversion instructions (unsigned); improved the related Tests.

Ryujinx.HLE/HOS/Services/DummyService.cs, Ryujinx.HLE/HOS/Services/IpcService.cs, Ryujinx.HLE/HOS/Services/ServiceFactory.cs, Ryujinx/Config.jsonc, Ryujinx/Configuration.cs, Ryujinx/_schema.json
Adds a config option to ignore missing services. This allows some games to boot with warnings for missing services.
This also provides a quick way to see how many, and what, services are needed to boot a specific game without this option.
Test case, bloons td 5 doesn't boot because of network service requirements however with this it manages to get in game. While slow and containing some graphical errors in the main menu it seems playable.
=> Config option to ignore missing services

Ryujinx.HLE/HOS/Services/Aud/IAudioRendererManager.cs
This should be close #669. 
Based on my own RE.
=> Fix GetAudioRendererWorkBufferSize for REV5

Ryujinx.Graphics/Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics/Shader/Translation/AttributeConsts.cs
This implements gl_ClipDistance.
Additionally, for unimplemented attributes, do not produce an invalid assignment for the constant "undef" that is used for unintialized variables. Instead, it now produces a commented out line with the attribute offset, like this:
```glsl
// bad_attr0x2C0 = temp_82;
```
=> Implement gl_ClipDistance on the shader generator

Ryujinx.Profiler/Profile.cs
I found a bug where it couldn't find the profiler config file when opening via drag and drop as relative paths are based on the path of the opened file.
This fixes that.
=> Profiler fix to handle drag and drop opening

Ryujinx.Graphics/Graphics3d/NvGpuFifo.cs
As was shown by fincs there should be a ++ in the bind macro method.
There is still another issue but it's 1 bug fixed
=> Added missing ++ in BindMacro GPU method

Ryujinx.HLE/FileSystem/Content/ContentManager.cs
This fix content paths being wrong on Linux and OSX.
=> fs: Fix ContentManager content paths on Unix systems

Ryujinx.HLE/HOS/Services/Am/ISelfController.cs
- Add all IPC call to the Dictionary.
- Rename _libraryAppletLaunchableEvent.
- Implement GetAccumulatedSuspendedTickChangedEvent according to the RE:
```C
undefined8 GetAccumulatedSuspendedTickChangedEvent (struct this, uint *ouput_event_handle)
{
svcArbitrateLock(&this->tag_location);
if (this->event_created == 0)
{
if (CreateEvent(&this->event_object, 0, 1) != 0)
{
Assert(&DAT_710018f73b, &DAT_710018f73b, &DAT_710018f73b, 0, result, &DAT_710018f73b);
}
this->event_created = 1;
svcSignalEvent(&this->event_object);
}
svcArbitrateUnlock(&this->tag_location);
uint event_handle = GetEventHandle(&this->event_object);
uint uVar1 = *ouput_event_handle;
*ouput_event_handle = event_handle;
char cVar2 = *(char *)(ouput_event_handle + 1);
*(undefined *)(ouput_event_handle + 1) = 0;
if (cVar2 != 0) …
```
=> Implement GetAccumulatedSuspendedTickChangedEvent to ISelfController

Ryujinx.Common/Extensions/BinaryReaderExtensions.cs, Ryujinx.Common/Logging/Formatters/DefaultLogFormatter.cs
This PR adds support for printing arrays in stubs (useful for IPC InBuffer/InPointer).
This also add an util to parse an array of structure from a BinaryReader.
Thanks to @jduncanator for the DefaultLogFormatter.cs changes.
=> PrntStub: Add a way to print arrays

Ryujinx.HLE/HOS/Services/Friend/FriendErr.cs, Ryujinx.HLE/HOS/Services/Friend/INotificationService.cs, Ryujinx.HLE/HOS/Services/Friend/IServiceCreator.cs
According to the RE, the event isn't signaled when handle is returned.
```C
long nn::friends::detail::service::NotificationService::GetEvent(long this, uint *output_handle)
{
long inner_struct_event;
int result;
if (this->event_created)
{
inner_struct_event = &this->event_object;
}
else
{
inner_struct_event = &this->event_object;
result = CreateEvent(&this->event_object, 0, 1);
if ( result )
{
Assert();
}
this->event_created = true;
}
uint event_handle = nn::os::detail::DetachReadableHandleOfInterProcessEvent(inner_struct_event);
*output_handle = event_handle;
int unknown = *((char *)output_handle + 4);
*((char *)output_handle + 4) = 1;
if (unknown)
{
CloseHandle(*output_handle);
}
return 0LL;
}
```
=> friends: INotificationService Implementation of GetEvent

ChocolArm64/Instructions/InstEmitSimdMove.cs, ChocolArm64/OpCodeTable.cs, Ryujinx.Tests/Cpu/CpuTestSimd.cs, Ryujinx.Tests/Cpu/CpuTestSimdFcond.cs, Ryujinx.Tests/Cpu/CpuTestSimdFmov.cs, Ryujinx.Tests/Cpu/CpuTestSimdImm.cs, Ryujinx.Tests/Cpu/CpuTestSimdIns.cs, Ryujinx.Tests/Cpu/CpuTestSimdReg.cs, Ryujinx.Tests/Cpu/CpuTestSimdRegElem.cs, Ryujinx.Tests/Cpu/CpuTestSimdShImm.cs
OpTable Fixes.
Fmov_V -> Fmov_Vi
**SIMD:**
**FP:**
Improve `Smov_S` & `Umov_S` Tests.
Improve `Simd Permute` Tests.
Add new test category `SimdFmov`.
Nits.
=> Implement the remaining tests for Simd and Fp instructions of data processing type. Small opts. for Fmov_Ftoi/1 & Fmov_Itof/1 Insts.

Ryujinx.HLE/HOS/Services/Acc/IAccountService.cs, Ryujinx.HLE/HOS/Services/FspSrv/IDirectory.cs, Ryujinx.HLE/HOS/Services/FspSrv/IFile.cs, Ryujinx.HLE/HOS/Services/FspSrv/IFileSystem.cs, Ryujinx.HLE/HOS/Services/FspSrv/IFileSystemProxy.cs, Ryujinx.HLE/HOS/Services/FspSrv/IStorage.cs, Ryujinx.HLE/HOS/Services/Ns/IApplicationManagerInterface.cs, Ryujinx.HLE/Ryujinx.HLE.csproj
Many LibHac types will now return or throw result codes the same as Horizon code would.
Small IFileSystem behavior details now match their behavior in Horizon.
Removed open-file tracking in IFileSystem.
=> Update to LibHac 0.5.0

Ryujinx.HLE/HOS/Services/Acc/IProfile.cs, Ryujinx.HLE/HOS/Services/Aud/AudioRenderer/IAudioRenderer.cs, Ryujinx.HLE/HOS/Services/Aud/IAudioRendererManager.cs, Ryujinx.HLE/HOS/Services/IpcService.cs, Ryujinx.HLE/HOS/Services/Lr/ILocationResolverManager.cs
Since the reflection code didn't take care about `private`, this cause regression, so I have added the flag just in case and fix calls who are declared with `private` to `public`.
=> Fix private on some call

CONFIG.md, Ryujinx/Config.jsonc, Ryujinx/Configuration.cs, Ryujinx/Ui/GLScreen.cs, Ryujinx/Ui/NpadController.cs, Ryujinx/_schema.json
This PR changes game controller input from using the `OpenTK.Input.Gamepad` class to `OpenTK.Input.Joystick`. This should make every DInput and XInput device recognized as a game controller by the OS to work with Ryujinx, instead of only limiting it to recognized and automapped gamepads like before. Other than it improving compatibility, it has the same limitation as before. Although axes can be used for other buttons, both analog sticks can only use axes.
=> Use the Joystick interface for game controller input.

Ryujinx.Audio/Native/libsoundio/SoundIOOutStream.cs
This fix audio slowdown on Unix based platforms where soundio will try
to switch to mono because of the invalid data written.
=> Fix a memory corruption in SoundIO wrapper

Ryujinx.HLE/HOS/Services/Am/ICommonStateGetter.cs, Ryujinx.HLE/HOS/Services/Am/ResultCode.cs, Ryujinx.HLE/HOS/Services/Apm/CpuBoostMode.cs, Ryujinx.HLE/HOS/Services/Apm/PerformanceConfiguration.cs
- Implement am call `ICommonStateGetter::SetCpuBoostMode` according to the RE:
```c++
signed __int64 __fastcall nn::ICommonStateGetter::SetCpuBoostModeImpl(__int64 this, unsigned int cpu_boost_mode)
{
if ( cpu_boost_mode > 1 )
{
return 0x3F480LL;
}
__int64 v2 = *(_QWORD *)(this + 0x38);
__int64 v3 = *(_QWORD *)(*(_QWORD *)(v2 + 8) + 0x298LL);
nnLock((_DWORD *)(v3 + 0x104));
__int64 v5 = *(_QWORD *)(v2 + 0x18);
bool unk_bool = *(unsigned __int8 *)(v5 + 0x7C);
*(_DWORD *)(v5 + 0x80) = cpu_boost_mode;
if (!unk_bool)
{
*(_BYTE *)(v5 + 0x7C) = 1;
}
wait_condvar(v3 + 0xA8);
nnUnlock((_DWORD *)(v3 + 0x104));
return 0LL;
}
```
- Add enum for apm `CpuBoostMode`
- Add missing values in apm `PerformanceConfiguration` with some comments.
- Close issue #717
=> am: Implement ICommonStateGetter::SetCpuBoostMode

Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZone.cs
This address issues when the user doesn't provide system archives and that an invalid posix timezone rule name is used.
Related to Ryujinx/Ryujinx-Games-List#195
=> timezone: improve sanity checks on TimeZone Rule name

Ryujinx.Graphics/Shader/Instructions/InstEmitFArith.cs
Changes FSETP to match envytools' updated documentation: https://github.com/envytools/envytools/blob/master/envydis/gm107.c#L2014
=> shader: Add missing fsetp negation bit on srcB

Ryujinx/Program.cs, Ryujinx/Ui/MainWindow.cs
GTK context MUST be fully initialized before initializing OpenTK because a possible conflcit between OpenTK's SDL2 backend and GTK.
This PR move the load LoadApplication call outside of MainWindow constructor to fix this issue.
=> ui: Fix segfault on Linux when passing a program via command line

Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/AudioRendererCommon.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/BehaviorInfo.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/CommandGenerator.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/EdgeMatrix.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/IAudioRenderer.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/NodeStates.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/PerformanceManager.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/SplitterContext.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/Types/AudioConsts.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/Types/AudioRendererConsts.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/Types/AudioRendererParameter.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/Types/SupportTags.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/Types/UpdateDataHeader.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/VoiceContext.cs, Ryujinx.HLE/HOS/Services/Audio/IAudioRendererManager.cs
According to RE:
- `GetAudioRendererWorkBufferSize` is updated and improved to support `REV7`
- `RequestUpdateAudioRenderer` is updated to `REV7` too
Should improve results on recent game and close #718 and #707
=> audren: Fix AudioRenderer implementation

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs, Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/IApplicationProxy.cs, Ryujinx.HLE/HOS/Services/Am/AppletOE/IApplicationProxyService.cs
According to RE, just the handle is returned, nothing more.
Added the switchbrew's note in case of further implementations.
close #762
=> am: Implement IApplicationFunctions GetGpuErrorDetectedSystemEvent

Ryujinx.HLE/HOS/Ipc/IpcHandler.cs
When we close a session via IPC, we should return an error code.
This fix an assert in some games that are shipped with debug modules.
=> ipc: Fix error code returned by CloseSession

Ryujinx.Audio/IAalOutput.cs, Ryujinx.Audio/Renderers/DummyAudioOut.cs, Ryujinx.Audio/Renderers/OpenAL/OpenALAudioOut.cs, Ryujinx.Audio/Renderers/OpenAL/OpenALAudioTrack.cs, Ryujinx.Audio/Renderers/SoundIo/SoundIoAudioOut.cs, Ryujinx.HLE/HOS/Services/Audio/AudioOutManager/IAudioOut.cs
- Implementation of `audout:u` SetAudioOutVolume and GetAudioOutVolume (checked with RE). 
- Add Get and Set for Volume into audio backends.
- Cleanup of all audio backends to follow the `IAalOutput` structure and .NET standard.
- Split OpenAL backend into 2 files for consistency.
close #777.
=> audout:u: Implement SetAudioOutVolume and GetAudioOutVolume

Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZoneContentManager.cs
This fix a regression on Pokémon Let's Go Eevee! (and
probably other games) caused by changes from #783.
=> Fix TimeZoneBinary dispose issues

Ryujinx/Ui/NpadController.cs
This PR fixes the behaviour when a button is set to an analog input, such as an analog trigger. 
Before, IsActivated would return true if abs(value) were greater than Deadzone, which matches behaviour for analog stick deadzone. For buttons (the only use of IsActivated), this returns true when the value is Deadzone away from 0.
However, analog _triggers_ on controllers like the Xbox 360 actually have -1 for off, and 1 for on. That means that by default, the buttons were activating whenever the trigger was not half pressed. That, and the "TriggerThreshold" variable in config was not being used at all.
Note that there is still a use case where a button could be assigned to a specific analog _stick_ direction, eg. dpad right to analog horizontal +, but you couldn't do that before as you …
=> Fix behaviour when an analog trigger is assigned to a button.

Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcTable.cs
Allows passing data into and out of the same registers when calling via the Kernel ABI. This allows implementing specific supervisor calls like "CallSecureMonitor", that expect their args and results in the same registers.
For example:
```cs
public void CallSecureMonitor64(ref ulong x0, ref ulong x1, ref ulong x2, ref ulong x3, ref ulong x4, ref ulong x5, ref ulong x6, ref ulong x7)
{
var X = new[] { x0, x1, x2, x3, x4, x5, x6, x7 };
Logger.PrintInfo(LogClass.KernelSvc, "CallSecureMonitor was called.");
Logger.PrintInfo(LogClass.KernelSvc, $"In  X[0] = {X[0]:X16}");
Logger.PrintInfo(LogClass.KernelSvc, $"In  X[1] = {X[1]:X16}");
Logger.PrintInfo(LogClass.KernelSvc, $"In  X[2] = {X[2]:X16}");
Logger.PrintInfo(LogClass.KernelSvc, $"In  X[3] = {X[3]:X16}"); …
```
=> svc: Implement `ref` parameters

Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForApplication.cs
The output buffer for sequential writing of the 8 potential `User Id` (for a total of 128 bytes), for the commands `ListAllUsers` and `ListOpenUsers`, must always be cleaned for a smaller number of `User Id` (generally 1); in order to avoid that the potential random values contained in it may be misinterpreted as true `User Id` by the `GetUserExistence` commands and avoid the Sdk failure of EnsureSaveData.
=> Fix ghost users bug.

Ryujinx.HLE/HOS/Ipc/IpcHandler.cs
This is a hack, but it works for now. We should really determine a way to automatically calculate the required buffer size to avoid situations where specific IPC calls "overflow" this arbitrary size, or determine by means of reverse engineering if there really is a fixed "maximum size" that we could implement here.
=> Increase IPC buffer size

README.md
NXDumptool can dump NSP dumps so using SDTool is no longer needed. This PR also has some minor style changes.
=> Update README.md to reflect new changes in NXDumptool

ARMeilleure/CodeGen/X86/Assembler.cs, ARMeilleure/CodeGen/X86/CodeGenerator.cs, ARMeilleure/CodeGen/X86/HardwareCapabilities.cs, ARMeilleure/CodeGen/X86/IntrinsicTable.cs, ARMeilleure/Instructions/InstEmitSimdCmp.cs, ARMeilleure/Instructions/InstEmitSimdCvt.cs, ARMeilleure/Instructions/InstEmitSimdHelper.cs, ARMeilleure/IntermediateRepresentation/Intrinsic.cs, ARMeilleure/Optimizations.cs, Ryujinx.Tests.Unicorn/Ryujinx.Tests.Unicorn.csproj, Ryujinx.Tests/Ryujinx.Tests.csproj
Fix `Fcmge_S/V` & `Fcmgt_S/V` Inst.s; thanks to jduncanator for narrowing the issue (see Ryujinx/Ryujinx-Games-List#207)
Optimize `Fccmp*_S` & `Fcmp*_S` Inst.s
Fix `Cvtsd2si` Opcode
Follow-up `Fcm**_S/V` & `Fc*mp*_S` Inst.s
Improve `CmpCondition` enum and its uses
Nits
Successful unit testing on Windows
---
Optimize `Fccmp*_S` & `Fcmp*_S` Inst.s:
`FCCMP  S1, S2, #0, EQ`:
```diff
LOC_0x2:
mov             eax, dword ptr [rsp + 0x60]
mov             ecx, dword ptr [rsp + 0x5c]
cmp             eax, ecx
setne           bpl
movzx           ebp, bpl
test            ebp, ebp
jne             LOC_0x3
- mov             ebp, 1
+ mov             eax, 1
- and             ebp, 0
- mov             eax, ebp
mov             dword ptr [rsp + 0x5c], eax
- xor             ebp, ebp
+ mov             eax, 1
- …
```
=> Fix Fcmge_S/V & Fcmgt_S/V Inst.s

KEYS.md, README.md
To be honest the previous guide was ancient. This guide is easy to follow and quick if done correctly.
Furthermore, I've have corrected the formatting of `title.keys` documentation as that was outdated too.
=> Update KEYS.md to use a new dumping guide and correct title.key formatting

ARMeilleure/Instructions/InstEmitSystem.cs, ARMeilleure/Instructions/NativeInterface.cs, Ryujinx.Tests/Cpu/CpuTestSystem.cs
Successful unit testing on Windows (debug and release mode).
Closes https://github.com/Ryujinx/Ryujinx/issues/806.
---
`MRS X0, NZCV`:
```assembly
...
mov             ecx, dword ptr [rsp + 0x5c]
mov             esi, ecx
shl             esi, 0x1c
mov             ecx, dword ptr [rsp + 0x60]
mov             edi, ecx
shl             edi, 0x1d
mov             ecx, dword ptr [rsp + 0x64]
mov             r8d, ecx
shl             r8d, 0x1e
mov             ecx, dword ptr [rsp + 0x68]
mov             r9d, ecx
shl             r9d, 0x1f
or              r9d, r8d
or              edi, esi
mov             esi, r9d
or              esi, edi
mov             esi, esi
mov             rcx, qword ptr [rsp + 0x54]
mov             rdi, rcx
or              rdi, 1
mov             rcx, qword ptr [rsp + 0x4c]
mov …
```
=> Add Mrs & Msr (Nzcv) Inst., with Tests.

Ryujinx.HLE/HOS/Services/Audio/IAudioRendererManager.cs
`revisionInfo` and `appletResourceUserId` were read in the wrong order.
=> Fix GetAudioDeviceServiceWithRevisionInfo logging

Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs, Ryujinx.HLE/HOS/ProgramLoader.cs
Small change is small, but this simply sets AArch32 mode in ARMeilleure when the application is 32-bit.
=> Set AArch32 mode in KThread

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs, Ryujinx.HLE/HOS/Services/Am/ResultCode.cs, Ryujinx.HLE/HOS/Services/Sdb/Pdm/IQueryService.cs, Ryujinx.HLE/HOS/Services/Sdb/Pdm/QueryService/QueryPlayStatisticsManager.cs, Ryujinx.HLE/HOS/Services/Sdb/Pdm/QueryService/Types/ApplicationPlayStatistics.cs, Ryujinx.HLE/HOS/Services/Sdb/Pdm/QueryService/Types/PlayLogQueryCapability.cs, Ryujinx.HLE/HOS/Services/Sdb/Pdm/ResultCode.cs
- Fix some nits in `IApplicationFunctions`
- Implement `QueryApplicationPlayStatistics` and `QueryApplicationPlayStatisticsByUid` checked by RE.
- Implement `QueryApplicationPlayStatisticsForSystem` and `QueryApplicationPlayStatisticsByUserAccountIdForSystem` checked by RE.
- Implement `QueryPlayStatisticsManager` to get/set played games statistics. We currently don't store any statistics because it's handled by qlaunch (or maybe am service?) on Switch.
We can add support later if games use returned statistics for something.
=> Implement IApplicationFunctions & IQueryService commands

Ryujinx.Common/Logging/LogClass.cs, Ryujinx.HLE/HOS/Services/Ldn/IUserServiceCreator.cs, Ryujinx.HLE/HOS/Services/Ldn/NetworkInterface.cs, Ryujinx.HLE/HOS/Services/Ldn/ResultCode.cs, Ryujinx.HLE/HOS/Services/Ldn/Types/NetworkState.cs, Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
- Implement `IUserServiceCreator: CreateUserLocalCommunicationService` according to RE.
- Implement `IUserLocalCommunicationService` calls:
- Every calls in this interface are layered to `NetworkInterface`.
- `GetState` according to RE.
- `InitializeOld`, `Initialize` and `Finalize` stubbed with the appropriate result code and some TODO according to RE.
- `AttachStateChangeEvent` according to RE.
Close #824
=> ldn: Implement calls of UserLocalCommunicationService

Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZone.cs
"Merry Christmas.. or maybe not? ❄️" edition
This PR fix an extraneous incrementation that shouldn't even have existed in the first place.
=> Fix timezone month offset by one

Ryujinx.HLE/HOS/Services/Ldn/ResultCode.cs, Ryujinx.HLE/HOS/Services/Prepo/IPrepoService.cs, Ryujinx.HLE/HOS/Services/Prepo/ResultCode.cs
- Implement `SaveReportOld`, `SaveReportWithUserOld`, `SaveReport`, `SaveReportWithUser` not accurate by RE (except for result codes). It's  here to do something with the data since we will never use the `Play Report` sent by the game. So it's better than just a stub.
- Fix a typo in `ldn` result code.
Close #807
=> prepo: Implement calls of IPrepoService

Ryujinx.HLE/HOS/Services/Lm/LogService/ILogger.cs
The type and size are custom encoded integer, not byte.
This fix crashes on games that send messages longer than 127 characters.
=> Fix ILogger type and size decoding

.github/workflows/build.yml
This configure a simple CI job on every possible configurations that the emulator might be build on.
PS: General system stability improvements to enhance the user's experience.
=> Use Github Actions as a secondary CI

Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/NvHostAsGpuDeviceFile.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/Types/RemapArguments.cs
The struct on switchbrew is wrong, the field at 0x8 is not padding. I confirmed looking at nvservices that it is indeed used as a offset, multiplied by some page size.
=> Fix remap ioctl map offset

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Kernel/Process/KHandleTable.cs, Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcHandler.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcSystem.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcTable.cs, Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs
This fix the oldest issue with the HLE code: the kernel side
disposability.
Changelog:
- Implement KProcess::UnpauseAndTerminateAllThreadsExcept, KThread::Terminate, KThread::TerminateCurrentProcess, KThread::PrepareForTermiation and the svc post handler accurately.
- Implement svcTerminateProcess and svcExitProcess. (both untested)
- Fix KHandleTable::Destroy not decrementing refcount of all objects stored in the table.
- Spawn a custom KProcess with the maximum priority to terminate every guest KProcess. (terminating kernel emulation safely)
- General system stability improvements to enhance the user's experience.
PS: This based on @TuxSH's reversing of kernel 6.0.0
=> Make HLE disposable safely

Ryujinx.HLE/HOS/Services/Time/TimeManager.cs
Found this diff while looking at my reversing of PSC, oops.
===
=> Fix EphemeralNetworkSystemClock using the wrong steady clock

Ryujinx.Common/ReactiveObject.cs
This fix the logger configuration initial state being ignored.
===
=> Fix ReactiveObject initial event not being propagated with boolean types

Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZone.cs
Nintendo actually uses range from 1 to 12 for months (when original timezone code manage 0-11)
=> Fix timezone month being reported incorrectly to games

Ryujinx.HLE/Exceptions/InvalidFirmwarePackageException.cs, Ryujinx.HLE/FileSystem/Content/ContentManager.cs, Ryujinx.HLE/FileSystem/Content/SystemVersion.cs, Ryujinx.HLE/HOS/Font/SharedFontManager.cs, Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/Sdb/Pl/ISharedFontManager.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade
This adds support for installing firmware backups and updates. Supported formats include a non-trimmed game card dump(XCI), a firmware update package in nsp format, or a zip archive of the system content registered directory from a switch. The installer can be access through the "Tools" menu. Do note, you would still need the necessary keys for the firmware you are installing.
This PR is ready for testing and reviews.
=> System firmware installer

Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs, Ryujinx.HLE/Loaders/Elf/ElfSymbol.cs, Ryujinx.HLE/Loaders/Elf/ElfSymbol32.cs, Ryujinx.HLE/Loaders/Elf/ElfSymbol64.cs
This adds stacktrace and symbols parsing for 32 bits binaries.
Stacktrace code based on @riperiperi's work.
===
=> Add 32 bits support to HleProcessDebugger

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/Arp/ApplicationLaunchProperty.cs, Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs, Ryujinx/Ui/GLScreen.cs, Ryujinx/Ui/MainWindow.cs
qlaunch calls EnsureApplicationSaveData when launching an application, so we need to do the same.
Also workaround the lack of a program registry by manually setting the program ID if needed when calling some savedata functions.
=> Call EnsureApplicationSaveData when launching a game

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.GAL/IRenderer.cs, Ryujinx.Graphics.Gpu/NvGpuFifo.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Renderer.cs
The barrier is cheaper than the glFinish call.
Thanks to @ReinUsesLisp for suggesting using a barrier here.
=> Replace glFinish with barrier for WaitForIdle

ARMeilleure/Memory/MemoryManager.cs, Ryujinx.Graphics.GAL/IBuffer.cs, Ryujinx.Graphics.GAL/ITexture.cs, Ryujinx.Graphics.Gpu/Engine/Compute.cs, Ryujinx.Graphics.Gpu/Engine/MethodCopyBuffer.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Image/SamplerPool.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.Gpu/Memory/Buffer.cs, Ryujinx.Graphics.Gpu/Memory/MemoryAccessor.cs, Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Gpu/Shader/ShaderDumper.cs, Ryujinx.Graphics.OpenGL/Buffer.cs, Ryujinx.Graphics.OpenGL/TextureView.cs, Ryujinx.Graphics.Shader/Decoders/Decoder.cs, Ryujinx.Graphics.Shader/Translation/ShaderHeader.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
This adds a new method on the CPU memory manager that returns a span of a memory region directly when the region is contiguous in memory. This avoids doing a allocation and copy, so its faster.
We need to return a read-only span here since the region may not be contiguous, and in this case it does a allocation and returns a copy of the data, modification wouldn't be reflected in memory, so it returns a read-only span to communicate that and prevent writes on the region.
=> Add a GetSpan method to the memory manager and use it on GPU

Ryujinx.HLE/HOS/Kernel/SupervisorCall/RAttribute.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcHandler.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcIpc.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcMemory.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcSystem.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcTable.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcThread.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcThreadSync.cs
This PR rework the svc handling system to prepare for 32 bits support.
Changelog:
- Add RAttribute to handle arguments positioning manually. (needed for 32 bits support)
- Enforce usage of RAttribute.
- Add 32 bits codepath for SVC handling.
- Pre-generate all SVC handler in the static constructor.
=> Rework SVC handling

Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs, Ryujinx.HLE/Ryujinx.HLE.csproj, Ryujinx/Ui/SaveImporter.cs
This brings support for temporary savedata, ignores case in key names when loading from a file, and prints the rights ID correctly when missing a title key.
=> Update to LibHac 0.8.2

Ryujinx.Graphics.Gpu/Image/Sampler.cs, Ryujinx.Graphics.Gpu/Image/SamplerDescriptor.cs
This fixes rendering of shadows in a number of games including Mario Tennis Aces.
=> Add sampler border color support on the GPU

Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/EffectContext.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/IAudioRenderer.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/Types/EffectIn.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/Types/EffectOut.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/Types/EffectState.cs
This is the same as #541, but the structs on that PR were mostly wrong, so I rewrote it based on the client audio code.
This is meant as a temporary fix until the proper audio rewrite by @Thog lands, until then this can unblock a few games that depends on effects.
=> Support audio effect output status

Ryujinx.Graphics.Shader/Translation/EmitterContext.cs
This fix resolves the issue with the skybox on Captain Toad.
=> Fix shader output color buffer index when non-sequential render targets are used

Ryujinx/Ryujinx.csproj
The DiscordRichPresence nuget is finally updated to target .NET core, so upgrading to the latest version gets rid of the build warning that the package was restored using .NET framework.
=> Update DiscordRichPresence package reference to 1.0.147

Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
The size field reported back from the Software Keyboard applet is wrong. I noticed this while debugging an issue with Little Town Hero in yuzu. In Ryujinx, the game does not actually accept the inputted text, but the error is ignored (see code in https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs#L132). With this change, the game accepts the entered text.
=> SoftwareKeyboard: Interactive data size should include size field.

Ryujinx.Graphics.OpenGL/EnumConversion.cs, Ryujinx.Graphics.OpenGL/TextureView.cs
Fix some rendering issues on Xenoblade Chronicles 2 and probably other games.
Fix #866
=> Enable stencil texturing

Ryujinx.HLE/FileSystem/SaveInfo.cs, Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/AccountUtils.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForApplication.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IManagerForApplication.cs, Ryujinx.HLE/HOS/Services/Account/Acc/Types/UserId.cs, Ryujinx.HLE/HOS/Services/Account/Acc/Types/UserProfile.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/Storage/StorageHelper.cs, Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs, Ryujinx.HLE/HOS/Services/Friend/IServiceCreator.cs, Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/FriendService/Types/Friend.cs, Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/FriendService/Types/UserPresence.cs, Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs, Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/INotificationService.cs, Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/NotificationService/NotificationEventHandler.cs, Ryujinx.HLE/HOS/Services/Prepo/IPrepoService.cs, Ryujinx.HLE/HOS/Services/Sdb/Pdm/QueryService/QueryPlayStatisticsManager.cs, Ryujinx.HLE/HOS/SystemState/SystemStateMgr.cs
The account user id isn't an UUID. This PR adds a new UserId type with
the correct value ordering to avoid mismatch with LibHac's Uid. This also fix
an hardcoded value of the UserId.
As the userid has been invalid for quite some time (and to avoid forcing
users to their recreate saves), the userid has been changed to "00000000000000010000000000000000".
Also implement a stub for IApplicationFunctions::GetSaveDataSize. (see
the sources for the reason of the stub)
Fix #626
=> Fix inconsistencies with UserId

Ryujinx.Graphics.Gpu/Memory/MemoryAccessor.cs, Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs
This was causing a bottleneck in a few games. The cost of `UpdateShaderState` is now more in line with the other state changes (though it still wins out). (6% -> 0.7% total cpu in same situation)
`GetSubSize` has been updated with a `maxSize` parameter to prevent it from scanning the whole memory space when the caller expects a small size.
=> Compare shader code using a span instead of individual reads.

Ryujinx.Common/ReferenceEqualityComparer.cs, Ryujinx.Graphics.Gpu/Engine/MethodCopyTexture.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs
Before this change, all items on the `_cache` would be enumerated when flushing. I was getting an absurdly high CPU usage rivalling that of MacroInterpreter in situations with lots of draw calls.
Question: is the locking necessary? I wasn't able to verify if the GPU textures are ever modified from another thread, so I added it in for safety.
=> Only enumerate cached textures that are modified when flushing.

Ryujinx/Ui/GameTableContextMenu.cs, Ryujinx/Ui/GameTableContextMenu.glade, Ryujinx/Ui/MainWindow.cs
Add options to the context menu in the GUI to extract the ExeFs, RomFs and Logo sections from an NCA file or an NSP/PFS0/XCI containing NCA files.
Source:
https://github.com/Thealexbarney/LibHac/blob/master/src/hactoolnet/FsUtils.cs#L26
https://github.com/Thealexbarney/LibHac/blob/master/src/hactoolnet/FsUtils.cs#L68
https://github.com/Thealexbarney/LibHac/blob/master/src/hactoolnet/ProcessNca.cs
=> Implement NCA section extractors in the GUI

Ryujinx.Graphics.Gpu/Constants.cs, Ryujinx.Graphics.Gpu/Engine/Compute.cs, Ryujinx.Graphics.Shader/Translation/GlobalMemory.cs, Ryujinx.Graphics.Shader/Translation/Lowering.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/GlobalToStorage.cs
The hardware only supports 8 constant buffers for compute shader, but the driver seems to expose 14. The driver makes up for the remaining cbufs by "emulating" them using global memory access. This is very similar to what is done for storage buffers.
This adds support for that on the shader, by identifying access to emulated uniform buffers (the same way we do to identify access to storage buffers) and replacing them with the proper uniform buffer access. The GPU side checks and binds the uniform buffers based on the descriptors.
=> Support compute uniform buffers emulated with global memory

Ryujinx.Common/Configuration/LoggerModule.cs, Ryujinx.Common/Logging/Targets/FileLogTarget.cs
I have separated logs into a single file per run. It should keep up to 3 runs before deleting them.
I have also disable stubs by default as they are the majority of the logs and they aren't very helpful.
I chose not to create a setting for max number for simplicity. I also chose not to limit the size of individual files as it would require checks during runtime and rewriting the whole file when it overflows. This shouldn't really be a concern with the other changes.
=> Reducing log sizes

Ryujinx.Graphics.OpenGL/Window.cs, Ryujinx/Ui/GLRenderer.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade
Changelog:
- Fix transparency of the window on some games on Windows.
- Fix escape key not being able to exit emulation.
- Fix inverted logic in fullscreen event handling.
- Fix a race condition when stoping emulation causing a hang.
- Fix a memory leak of the OpenGL context when stoping emulation (saving ~200MB of RAM when stoping emulation).
- Simplify and document behaviours when exiting the emulator while the
emulation is running.
=> Some fixes for the new GLRenderer

Ryujinx.Graphics.Shader/Decoders/OpCodeLdc.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeMemory.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeRed.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitMemory.cs
This was missing sign-extension, which was causing it to use the wrong offset when the offset is negative. Also correct LDC offset that is a byte offset, not a word offset.
=> Sign-extend shader memory instruction offsets

Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessToIndexed.cs
This should fix a regression in LM3 caused by #934. The pattern for LDC changed, but the bindless -> indexed code pattern match was not updated to handle that.
=> Update bindless to indexed conversion code pattern match

Ryujinx/Program.cs, Ryujinx/Ui/MainWindow.cs
This add the AppVeyor build version (added in #927) in the console window title and in the GUI title (when you are on the games list or when an emulated game is closed).
=> Add version in all window titles

Ryujinx/Ui/GLRenderer.cs
As per users request, the gamepad can now interact with the emulator again when unfocused.
=> Accept gamepad inputs when not focused

Ryujinx/Ui/GLRenderer.cs, Ryujinx/Ui/MainWindow.glade
This PR, default the minimal resolution of the GL widget to 480p (16:9) if the screen resolution is lower than 1080p.
Also ensure to use the scaling factor in OnConfigureEvent (this fix 4K display)
=> Improve rendering on resolution lower than 1080p

ARMeilleure/Decoders/InstDescriptor.cs
Fix a bug when a "semi-valid" instruction encoding is used.
=> Set Undefined instruction emitter for Undefined property on InstDescriptor

Ryujinx.Graphics.OpenGL/TextureCopyUnscaled.cs
This specifically affected the case where a texture was being copied into some non-zero target level on the destination texture. In this case, the source texture will already be the correct size to fit into the mip level, but the destination's size will still be that of mip level 0. By scaling the destination's size using the target mip level, we get the real size of where the texture should be copied to. The final copy takes the minimum of both sizes, but ideally they should both be equal.
Before, we would scale the source texture's size, essentially applying the mip scaling twice and causing only a small region of the texture to be copied into the destination. This doesn't cause any fatal errors, but caused Mario Kart's cubemap mipmaps to barely work at all.
Before:
After:
Example of …
=> Reduce copy destination size by target mipmap level, rather than source size.

Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenHelper.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenPacking.cs, Ryujinx.Graphics.Shader/Decoders/DecoderHelper.cs, Ryujinx.Graphics.Shader/Decoders/FPType.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeDArithImm.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeTable.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitAluHelper.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitConversion.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitFArith.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitHelper.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/Instruction.cs, Ryujinx.Graphics.Shader/StructuredIr/InstructionInfo.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, Ryujinx.Graphics.Shader/StructuredIr/VariableType.cs, Ryujinx.Graphics.Shader/Translation/EmitterContextInsts.cs, Ryujinx.Graphics.Shader/Translation/Lowering.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/ConstantFolding.cs
Implements 3 instructions required by Rune Factory 4 Special (DADD, DFMA and DMUL). Other remaining instructions (DSET, DSETP and other conversion instructions) can be added later.
=> Initial support for double precision shader instructions.

ARMeilleure/Decoders/Decoder.cs, ARMeilleure/Instructions/InstEmitSystem32.cs
This PR specifically targets a pattern seen in MK8 v1.7.1, where based on the result of a function, many locations would conditionally jump to data. Of course, the game never takes these branches, but our decoder and translator still follow them, which will cause a crash when they encounter any issues or code that deliberately throws (eg. if a specific variant of an instruction is not implemented)
The specific case this targets is data that is interpreted as a branch immediate instruction. This causes a special problem since we analyze branches when doing highCq code compilation, and try to follow and compile them into one whole function. It's very likely that the immediate branch location will be hilariously out of bounds, which will cause an exception when the decoder attempts to read …
=> Don't decode blocks starting outside mapped memory & undefined instead of throw on invalid sysreg coprocessor

ARMeilleure/CodeGen/X86/IntrinsicTable.cs, ARMeilleure/Decoders/OpCode32SimdRev.cs, ARMeilleure/Instructions/InstEmitSimdArithmetic.cs, ARMeilleure/Instructions/InstEmitSimdArithmetic32.cs, ARMeilleure/Instructions/InstEmitSimdCmp32.cs, ARMeilleure/Instructions/InstEmitSimdCvt.cs, ARMeilleure/Instructions/InstEmitSimdCvt32.cs, ARMeilleure/Instructions/InstEmitSimdHelper.cs, ARMeilleure/Instructions/InstEmitSimdHelper32.cs, ARMeilleure/Instructions/InstEmitSimdLogical32.cs, ARMeilleure/Instructions/InstEmitSimdMove32.cs, ARMeilleure/IntermediateRepresentation/Intrinsic.cs
This PR adds x86 intrinsic paths to most of the A32 SIMD instructions. This should bring performance more in line with A64, and the slow/non SSE paths should not be affected.
Since this adds fast paths for most instructions I'll go over the omissions instead. 
Omissions:
- Memory instructions.
- VABS+VNEG integer, VDUP, integer multiply (and fused variants) *
- Vector by scalar for integer *
- Narrow ops (there are only like 2 right now)
- VRECPE.f64, VRSQRTE.f64 (integer is not implemented at all, 64 has no x86 intrinsic)
- VCVT f32<->f64. *
- VCVT f32/64 to integer when using fpscr for rounding mode.
- VCVT integer to f32/64. *
- Anything with round mode "away from zero"
- Move immediate. *
- Shift instructions.
- Integer compare instructions.
Everything else should be covered.
Starred …
=> Implement Fast Paths for most A32 SIMD instructions

Ryujinx.Graphics.Shader/Decoders/Decoder.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitFlow.cs
This fixes two things:
First, it had a bug for branches using both a predicate and CC condition. When the predicate was inverted, it was inverting the whole expression, not just the predicate. I'm not aware of any specific issue caused by this bug, I just found it while I was looking at the code and decided to fix.
The other one is more complicated. When the shader has BRX instruction (which is basically a indirect branch with address from a register), we currently try to guess the possible targets. It assumes that the BRX is used for switch jump table optimization, and in this case the possible targets can be guessed by finding the common block that all the target branches to (the switch break). This doesn't work very well when PBK/SSY -> BRK/SYNC sequences are used, because the target …
=> Fix branch with CC and predicate, and a case of SSY/PBK propagation

ARMeilleure/CodeGen/Optimizations/Optimizer.cs, ARMeilleure/CodeGen/RegisterAllocators/HybridAllocator.cs, ARMeilleure/CodeGen/RegisterAllocators/LinearScanAllocator.cs, ARMeilleure/CodeGen/X86/Assembler.cs, ARMeilleure/CodeGen/X86/CodeGenCommon.cs, ARMeilleure/CodeGen/X86/CodeGenerator.cs, ARMeilleure/CodeGen/X86/PreAllocator.cs, ARMeilleure/CodeGen/X86/X86Optimizer.cs, ARMeilleure/IntermediateRepresentation/Node.cs, ARMeilleure/Translation/Compiler.cs, ARMeilleure/Translation/Translator.cs
This optimizes memory access on x64 by folding operations into the memory operand.
Right now it's a separate optimization pass specific to x64, done on both low cq and high cq. Had to modify the register allocators to know about the `MemoryOperand` being used as source operand on operations, and also the `Node` to keep track of def and uses used by the memory operand.
Would be nice to test for:
- Possible performance improvements from this change, although I would expect very small perf increase if any.
- Possible regressions caused by this change (shouldn't have any but you never know).
**Sample diffs:**
Before:
```nasm
0x00000013 | 4889cb                    | mov             rbx, rcx
0x00000016 | 4889d8                    | mov             rax, rbx
0x00000019 | 4889c1 …
```
=> Optimize x64 loads and stores using complex addressing modes

Ryujinx.Graphics.Gpu/MacroInterpreter.cs, Ryujinx.Graphics.Gpu/NvGpuFifo.cs, Ryujinx.Graphics.Gpu/NvGpuFifoMeth.cs, Ryujinx.Graphics.Gpu/ShadowRamControl.cs
The MME shadow RAM is used as "backup" storage of the hw register values. It's used by some NVN calls too restore state after a operation that needs to do temporary changes to the states to do some operation.
One example of them is ClearTexture. First it sets the MmeShadowControl  to "Passthrough" to prevent any changes from being written to shadow ram, since they are temporary. It changes render target state to set the texture to be cleared, and then call Clear. After that, it re-runs the macro with MmeShadowControl set to "Replay" to re-load the values from the shadow RAM and write those original values back to the hw register, restoring the previous state.
Other regular macro calls usually have MmeShadowControl set to "TrackWithFilter" that will write the value both to the hw regs and …
=> Implement MME shadow RAM

ARMeilleure/Decoders/OpCodeTable.cs, ARMeilleure/Instructions/InstEmitSimdCrypto32.cs, ARMeilleure/Instructions/InstEmitSimdLogical32.cs, ARMeilleure/Instructions/InstName.cs, Ryujinx.Tests/Cpu/CpuTest32.cs, Ryujinx.Tests/Cpu/CpuTestSimdCrypto32.cs, Ryujinx.Tests/Cpu/CpuTestSimdLogical32.cs
Adds instructions required for games to perform cryptography, and tests for them. Currently, unicorn doesn't seem to be able to do the crypto instructions in A32, so we're just comparing against expected values for now.
Tested in Mario Kart 8 Deluxe, which uses this for multiplayer comms.
Also adds a test for VORR (non-immediate), since it was free.
=> Implement AESMC, AESIMC, AESE, AESD and VEOR AArch32 instructions

Ryujinx/Ui/GLRenderer.cs
Just a quick fix to get linux working again. This shouldn't reintroduce transparency issues, as I don't think the 24 bit surface had any. (we made it 32 bit to combat issues on windows)
=> Fix GTK window crash by using 24 bit surface on unix, 32 bit on windows.

Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs
Some shader instruction (such as TXQ/Texture Query) has incomplete type information, because it is not needed. For example, a texture query operation only needs to know the texture dimensions. It does not need to know for example, if the texture is used for Depth Comparison. Depth comparison sampler type has the `Shadow` suffix, this is required for regular samples with depth comparison.
Basically, the problem is that the shader translator would sometimes use incomplete type information (from a TXQ instruction) to write the sampler type on the output program. This in turn causes a mismatch between the sampler type that texture sample instructions expects, and what was declared, and the shader fails to compile.
The fix I used is simply changing the order that the texture instructions are …
=> Improve shader sampler type selection

ARMeilleure/CodeGen/RegisterAllocators/CopyResolver.cs, ARMeilleure/CodeGen/RegisterAllocators/HybridAllocator.cs, ARMeilleure/CodeGen/RegisterAllocators/LinearScanAllocator.cs, ARMeilleure/CodeGen/RegisterAllocators/LiveInterval.cs, ARMeilleure/CodeGen/X86/CodeGenerator.cs, ARMeilleure/CodeGen/X86/PreAllocator.cs, ARMeilleure/CodeGen/X86/X86Optimizer.cs, ARMeilleure/Common/BitMap.cs, ARMeilleure/Common/BitMapPool.cs, ARMeilleure/Common/BitUtils.cs, ARMeilleure/Common/SortedIntegerList.cs, ARMeilleure/Common/ThreadStaticPool.cs, ARMeilleure/IntermediateRepresentation/MemoryOperand.cs, ARMeilleure/IntermediateRepresentation/Node.cs, ARMeilleure/IntermediateRepresentation/Operand.cs, ARMeilleure/IntermediateRepresentation/OperandHelper.cs, ARMeilleure/IntermediateRepresentation/Operation.cs, ARMeilleure/IntermediateRepresentation/OperationHelper.cs, ARMeilleure/ThreadStaticPool.cs, ARMeilleure/Translation/ControlFlowGraph.cs, ARMeilleure/Translation/EmitterContext.cs, ARMeilleure/Translation/PriorityQueue.cs, ARMeilleure/Translation/RegisterUsage.cs, ARMeilleure/Translation/SsaDeconstruction.cs, ARMeilleure/Translation/Translator.cs
The focus of these optimisations is mainly to reduce the number of allocations done when generating code. These allocations were greatly affecting the performance of other threads in the program, meaning that lowCq code would run much slower while highCq was being compiled, and multiple highCq threads would completely starve each other no matter how many cores you have.
With this change and direct-call, booting games up has more comparable performance to master.
- Use pools for Operands, Operations and Nodes. The allocations for all of these small objects happened pretty much constantly and likely caused a lot of heap contention.
- This uses a `ThreadStaticPool`, a new class which pools objects in a big list. These objects are never deleted, as it is assumed that future workloads will use …
=> CodeGen Optimisations (LSRA and Translator)

ARMeilleure/Translation/TranslatedFunction.cs
Add local var to reduce calling Marshal.GetFunctionPointerForDelegate, Can slightly improve performance.
=> Modify TranslatedFunction.GetPointer () to optimize performance

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs
This changes the way how texture invalidation works a bit to allow partial invalidation of textures. When the texture is modified by the GPU, and modification of the data by guest from the CPU side is detected, instead of re-loading the whole texture and potentially losing modifications made by the host GPU, instead it just copies the specific pages that were detected as modified. This prevents destruction of GPU written data, even if it's not a perfect solution (since it only copies whole pages at once).
In terms of performance I don't expect any noticeable regressions, it will be slower to re-upload textures modified by the host GPU, but re-loading textures from the guest memory is already a somewhat slow operation, so I guess for the part where it stutters due to texture load it could …
=> Support partial invalidation on texture access

Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs
Requires GLSL 4.3.0+ or the respective extension, so I decided to just increase the required version on the shader. Also removed shader storage buffer requirement since it is always available with version 4.3.
=> Implement textureQueryLevels

Ryujinx.Debugger/UI/ProfilerWidget.cs
=> Fix the item name cannot be displayed in profiler view

Ryujinx.HLE/HOS/Services/Prepo/IPrepoService.cs
It seems MsgPack.Cli incorrectly converts some unicode control characters directly to JSON literal Unicode strings (eg. '\1'). As these are invalid, pretty printing the JSON report fails.
This removes pretty printing, pending a proper implementation, and tidies up MsgPack deserialization.
=> prepo: Resolve JSON parsing issues in prepo report handling

Ryujinx/Ui/GLRenderer.cs
This fix an issue who write the wrong GPU vendor in status bar because of the "ati" in "Corporation".
=> Fix gpu vendor name parsing

Ryujinx.HLE/HOS/Services/Prepo/IPrepoService.cs
This implement RequestImmediateTransmission and GetTransmissionStatus of the prepo service accurately to RE.
Since we don't use reports, I've explained what the calls do in the real service.
Close #958
=> prepo: Implement RequestImmediateTransmission and GetTransmissionStatus

Ryujinx.Common/Ryujinx.Common.csproj, Ryujinx.Common/Utilities/MessagePackObjectFormatter.cs, Ryujinx.HLE/HOS/Services/Prepo/IPrepoService.cs
This adds a user readable formatter for MessagePack objects. It's not the prettiest thing itself, but it works.
This will need significant testing on games that make heavy use of prepo, although I suspect the worst case scenario to be objects that just have their types printed in the output (eg. `System.Byte[]`).
=> prepo: Add a MessagePack object formatter

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.Gpu/Engine/MethodClear.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/State/GpuStateTable.cs, Ryujinx.Graphics.Gpu/State/MethodOffset.cs, Ryujinx.Graphics.Gpu/State/ScissorState.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.OpenGL/TextureCopy.cs, Ryujinx.Graphics.OpenGL/Window.cs
This implements ✂️ support on the GPU.
Fixes bugs in a few games, like animal crossing customization screen:
Before (image not mine):
After:
=> Implement GPU scissors

Ryujinx.Graphics.OpenGL/Debugger.cs, Ryujinx.Graphics.OpenGL/Framebuffer.cs, Ryujinx.Graphics.OpenGL/HwCapabilities.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/TextureCopyUnscaled.cs, Ryujinx.Graphics.OpenGL/TextureStorage.cs, Ryujinx.Graphics.OpenGL/TextureView.cs
Intel has a bug where trying to render to a texture view with a format different from it's parent will still use the parent format.
As workaround, this creates a intermmediate texture, copies -> intermmediate, renders and copies intermmediate -> parent.
=> Workaround for AMD and Intel view format bug

Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs
Should help text rendering in most games on AMD gpus. Need testers.
Draft until we decide the best course of action. (detect amd and switch on/off, or use the slow method at all times / another)
Thanks to Rodrigo for suggesting that this might be the issue.
=> Index constant buffer vec4s using ternary expressions.

Ryujinx.HLE/FileSystem/Content/ContentManager.cs, Ryujinx.HLE/HOS/Font/SharedFontManager.cs, Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZoneContentManager.cs
This PR change the following behaviours:
- TimeZoneBinary system archive isn't required until guest code call LoadTimeZoneRule.
- Fonts system archives aren't required until a "pl:u"/"pl:s" IPC call is made.
- Custom font support was dropped.
- TimeZoneBinary missing message is now an error and not a warning.
=> Reduce requirements for running homebrew

Ryujinx.Graphics.GAL/VertexAttribDescriptor.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/State/VertexAttribState.cs, Ryujinx.Graphics.OpenGL/VertexArray.cs
When a attribute is not used, NVN sets bit 6 on the attribute, which indicates that it uses a constant value. The emulator was ignoring that bit and assuming all attributes would always point to data inside the vertex buffer. This is incorrect and some games relies on the constant behavior -- basically they use on the shader attributes that are "disabled".
This fixes bug on some tiles on Animal Crossing.
Before:
After:
Recommend testing in a few games to be sure that nothing regressed.
=> Support constant attributes (with a value of zero)

Ryujinx.Common/Configuration/ConfigurationFileFormat.cs, Ryujinx.Common/Configuration/ConfigurationState.cs, Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.Gpu/GraphicsConfig.cs, Ryujinx.Graphics.Gpu/Image/Sampler.cs, Ryujinx.Graphics.OpenGL/HwCapabilities.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx/Config.json, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/SwitchSettings.cs, Ryujinx/Ui/SwitchSettings.glade
This PR exposes a config option to make the max anisotropy configurable. The value can be 0-16 or -1 to let the game decide the level of anisotropy. The value is set to -1 by default.
=> Make max anisotropy configurable

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/DefineNames.cs, Ryujinx.Graphics.Shader/InterpolationQualifier.cs, Ryujinx.Graphics.Shader/ShaderProgramInfo.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
This remove code used to propagate interpolation qualifier from the fragment shader stages to the previous stages. Older GLSL versions requires that, but since 4.3.0, the spec says that only the fragment shader input qualifiers matters, so since we require this version now, we don't need it anymore.
From the spec:
> When interpolation or auxiliary qualifiers do not match, those provided in the fragment shader supersede those provided in previous stages. If any such qualifiers are completely missing in the fragment shaders, then the default is used, rather than any qualifiers that may have been declared in previous stages. That is, what matters is what is declared in the fragment shaders, not what is declared in shaders in previous stages. …
=> Remove output interpolation qualifier

Ryujinx.HLE/HOS/Applets/IApplet.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
Also, fix IApplet's `ReadStruct` signature to catch bad uses at compile time.
Fixes regression where SoftwareKeyboard is unusable.
=> Revert SwKbd Applet ReadStruct

Ryujinx/Ui/ApplicationLibrary.cs
Nacp was marked as deprecated in LibHac 0.10.0, this PR remove all usage of it
from Ryujinx and use the new struct ApplicationControlProperty.
=> libhac: use ApplicationControlProperty instead of Nacp

ARMeilleure/Instructions/InstEmitFlowHelper.cs
This path is always reached when a function larger than our current length limit (currently 5000 instructions) is compiled. It can add quite a few entries to the jump table, but it is insignificant compared to our maximum capacity.
Essentially, the situation is that the decoder has a hard upper cap on the number of instructions it will decode at once. If this is reached, it will leave a branch with a target block as "null", which causes us to emit a tail continue when emitting that branch, which would find and execute the next code block. Before, this would always go back to GetOrTranslate, and typically return a LowCq function.
Also made the call flag here use CallFlag instead of 1L.
Reduces CPU load on games that generally have large functions.
=> Use the jump table for HighCq tail continues.

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.Gpu/Constants.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/State/GpuState.cs, Ryujinx.Graphics.Gpu/State/GpuStateTable.cs, Ryujinx.Graphics.Gpu/State/MethodOffset.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/TextureCopy.cs, Ryujinx.Graphics.OpenGL/Window.cs
Implements RasterizeEnable register using `GL_RASTERIZER_DISCARD`. Fixes the micro black hole that appears in XC2 menu and opening sequence.
Before (the small dot near the top of the image)-
After-
RasterizeEnable is set to 1 on init as described in nouveau/mesa/deko3d.
`GL_RASTERIZER_DISCARD` causes `glClear`s to be ignored so it is disabled before host clears ~but not at other places. I think this is the right behavior. [Wiki Source](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glEnable.xhtml)~
EDIT: Apparently it affects blits on some vendors (NVIDIA). Thanks to @gdkchan for promptly testing.
Viewport counts were set to 8 previously. Switch hardware supports max of 16.
Blittting only uses Viewport 0 according to [wiki](https://www.khronos.org/opengl/wiki/Framebuffer#Blittin …
=> Simple GPU fixes

ARMeilleure/CodeGen/Optimizations/Simplification.cs
Simplify `BitwiseExclusiveOr %x %x` to 0 which incurs a modest diff.
IR:
```patch
-  i64 %12 = BitwiseExclusiveOr i64 %1, i64 %1
-  i64 %13 = BitwiseAnd i64 %12, i64 %1
-  i32 %14 = CompareLess i64 %13, i64 0x0
-  i32 %15 = CompareNotEqual i64 %1, i64 0x0
-  BranchIfTrue i32 %15
+  i32 %12 = CompareLess i64 0x0, i64 0x0
+  i32 %13 = CompareNotEqual i64 %1, i64 0x0
+  BranchIfTrue i32 %13
```
CodeGen:
```patch
cmp    rbp,0x0
setae  dl
movzx  edx,dl
-mov    rcx,rbp
-xor    rcx,rbp
-and    rcx,rbp
+xor    ecx,ecx
cmp    rcx,0x0
setl   r8b
movzx  r8d,r8b
```
In large translations, it can save a few local variables which affects register usage and the amount of spills.
`CompareLess` and friends are not constant folded currently, so the ` cmp    rcx,0x0` remains.
=> Optimize %x ^ %x = 0

Ryujinx.Graphics.Shader/Instructions/InstEmitFArith.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitHelper.cs
It was not reading the negation bit. The fix should also apply to HSET2 and HSETP2, in addition to HADD2, it seems that the only instruction that doesn't support negation of the constant buffer is HMUL2.
=> Fix negation of HADD2 constant buffer source

Ryujinx.HLE/HOS/Horizon.cs
Also fix a regression from cecbd256 where the dummy control data wouldn't be used
=> Ensure account save data exists when launching an extracted game

ARMeilleure/Instructions/NativeInterface.cs, ARMeilleure/Instructions/SoftFallback.cs, ARMeilleure/Memory/MemoryManager.cs, ARMeilleure/State/NativeContext.cs, ARMeilleure/State/V128.cs, Ryujinx.Tests/Cpu/CpuTest.cs, Ryujinx.Tests/Cpu/CpuTest32.cs, Ryujinx.Tests/Cpu/CpuTestMisc.cs
This new implementation takes advantage of `_e0` and `_e1` being contiguous in memory and turns the accesses into essentially array indexing, through the use of `Unsafe`.
The RyuJIT can now inline most of the methods, unlike before where it would complain.
Inline decisions of RyuJIT before:
```
[0 IL=0000 TR=000000 06000001] [FAILED: ldsfld of value class] V128:get_Zero():V128
[0 IL=0002 TR=000135 06000014] [FAILED: too many basic blocks] V128:GetUInt64(int):long:this
[0 IL=0002 TR=000157 06000013] [FAILED: has switch] V128:GetUInt32(int):int:this
[0 IL=0193 TR=000107 0600000B] [FAILED: too many il bytes] V128:Insert(int,int):this
[0 IL=0209 TR=000117 0600000C] [FAILED: too many basic blocks] V128:Insert(int,long):this
```
Since `GetUInt64` and `GetUInt32` are the leaf methods and they …
=> Improve V128

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/State/MethodOffset.cs, Ryujinx.Graphics.Gpu/State/ViewVolumeClipControl.cs, Ryujinx.Graphics.Gpu/State/YControl.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs
Also adds misc enums
Seems to fix fog issue in BOTW
Before:
After:
Depth clamping is also used for stenciled shadow implementations. So, please check for fixes in shadows as well.
Tested on NVIDIA only.
=> Implement Depth Clamping

ARMeilleure/CodeGen/X86/PreAllocator.cs
IR after PreAllocation pass:
```patch
block5:
-  i64 %9 = Copy i64 %0
-  i64 %10 = Copy i64 0x11
-  Store i64 %9, i64 %10
-  i64 %11 = Copy i64 0x8
-  Store i64 memory, i64 %11
-  i64 %12 = Copy i64 0x4
-  Store i64 memory, i64 %12
-  i64 %13 = Copy i64 0x1
-  Store i64 memory, i64 %13
-  i64 r0 = Copy i64 %2
+  i64 r0 = Copy i64 r3
+  Store i64 r0, i64 0x11
+  Store i64 memory, i64 0x8
+  Store i64 memory, i64 0x4
+  Store i64 memory, i64 0x1
+  i64 r0 = Copy i64 r5
Return
```
CodeGen:
```patch
mov	rax, rbx
-mov	rcx, 0x11
-mov	qword ptr [rax], rcx
-mov	rcx, 8
-mov	qword ptr [rax + 8], rcx
-mov	rcx, 4
-mov	qword ptr [rax + 0x10], rcx
-mov	rcx, 1
-mov	qword ptr [rax + 0x18], rcx
+mov	qword ptr [rax], 0x11
+mov	qword ptr [rax + 8], 8
+mov	qword ptr [rax + 0x10], 4
+mov	qword ptr [rax + …
```
=> Avoid temporaries when pre-allocating Store %x, imm8/16/32

Ryujinx.Graphics.Gpu/Engine/MethodReport.cs
Currently FastGpuTime will simply use a counter that is incremented each time ReportCounter is called. This causes games to behave as if operations were completed pretty much instantly, and this breaks some UE4 games, presumably because they divide the nanoseconds timestamp by some constant, and after the division to change in time is not registered (`currentTimestamp - previousTimestamp` would  always return 0). The fix I decided to use here is just dividing the host timestamp by a fixed amount.
This gives the illusion to the game that operations are completed faster than they really are, which is the purpose of this setting.
There's nothing special about the value 256, I just used it because it is a power of 2 (allowing the division to be optimized to shift), and because it seemed like …
=> Report more realistic GPU timestamps when FastGpuTime is enabled

Ryujinx.Graphics.Gpu/Engine/MethodClear.cs, Ryujinx.Graphics.Gpu/Engine/MethodConditionalRendering.cs, Ryujinx.Graphics.Gpu/Engine/MethodDraw.cs, Ryujinx.Graphics.Gpu/Engine/MethodReport.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Memory/CounterCache.cs, Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs, Ryujinx.Graphics.Gpu/Memory/UnmapEventArgs.cs, Ryujinx.Graphics.Gpu/State/GpuState.cs
This adds some support for conditional rendering. Conditonal rendering can be used to disable clears and draws based on some condition. When it is used, most of the time it is used for occlusion queries.
Currently it is reading the counter values from memory. For that to work, report calls needs to always write the value in memory. This is very inefficient as each time report is called, it is necessary to wait until the previous commands have completed in order to read the counter value from the GPU, and then wait it in memory.
A possible solution for the above problem is host conditional rendering (that is, using OpenGL conditional rendering functions directly, and passing the query). I added a "counter cache" that should help making this possible, but there's still some work required to …
=> Initial conditional rendering support

Ryujinx.HLE/HOS/Services/SurfaceFlinger/BufferQueueProducer.cs
This invalidate the GraphicBuffer on the consumer side when
SetPreallocatedBuffer is called on a buffer slot.
This fix rendering issues on games with a dynamic resolution like Yoshi
Crafted World.
=> SurfaceFlinger: Invalid GraphicBuffer in SetPreallocatedBuffer

Ryujinx/Ui/ApplicationLibrary.cs
Catch JsonParsingException and load defualt metadata in the event that the json gets nulled
=> Fix metadata.json JsonParsingException crash

Ryujinx.Graphics.GAL/BlendDescriptor.cs, Ryujinx.Graphics.GAL/ColorF.cs, Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/State/BlendState.cs, Ryujinx.Graphics.Gpu/State/BlendStateCommon.cs, Ryujinx.Graphics.Gpu/State/GpuState.cs, Ryujinx.Graphics.Gpu/State/GpuStateTable.cs, Ryujinx.Graphics.Gpu/State/MethodOffset.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs
Also initializes blend states to GL default values.
Haven't seen any game use constant color blend modes, but the initialization may help fix any issues.
Added a local state to constant color because some games spam the same value.
Tested on NVIDIA.
**EDIT:** Adds Set methods to GpuState too
=> Implement Constant Color blends

ARMeilleure/CodeGen/X86/PreAllocator.cs
Summary of changes:
- Fix bug where it would try to use a constant for third operand of CompareAndSwap, now it inserts a copy, should fix #1124.
- Changed nodes list iteration to now take the next node from the node returned from each individual copy insertion and transform functions. This avoid processing new nodes that were inserted by those functions, can save a tiny bit of time.
- Renamed a few functions for more clarity.
=> Do temp constant copy for CompareAndSwap, other improvements to PreAllocator

Ryujinx.Graphics.GAL/ITexture.cs, Ryujinx.Graphics.Gpu/Engine/MethodReport.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.OpenGL/TextureBase.cs, Ryujinx.Graphics.OpenGL/TextureBuffer.cs, Ryujinx.Graphics.OpenGL/TextureView.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeTable.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs, Ryujinx.Graphics.Texture/SizeInfo.cs
This implements texture/image buffer support required by some games, and also fixes some bugs here and there, like:
- ISET instruction immediate variant not being decoded in some cases (single line change, found it while testing a game).
- TEXS.1D.LZ missing the LOD level constant argument, could throw `ArgumentOutOfRangeException` during GLSL code generation.
- Bounds check on `SizeInfo` struct `GetMipOffset` method.
=> Implement texture buffers

Ryujinx/Ui/MainWindow.cs
As I was unable to disable the ctrl + f key-binding, this implements
something to make it works with the default GTK code logic.
Also remove unused _treeView static member.
=> UI: Implement interactive search on GameTable

Ryujinx.HLE/HOS/Kernel/Memory/KMemoryRegionBlock.cs
This should fix the block coalescing implementation. The previous implementation was incomplete, missing the `count >= 64`. I probably thought it was some sort of compiler optimization that could be omitted at the time. I rechecked the kernel implementation and implemented the missing parts.
Also thanks to SciresM for mesosphere, an open source implementation of Horizon kernel that helped me double check that the memory allocator implementation was correct.
This should fix `OutOfMemory` error being returned by some games that does allocation frequently using (Un)MapPhysicalMemory syscalls.
=> Fix kernel memory allocator block coalescing

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Texture/LayoutConverter.cs, Ryujinx.Graphics.Texture/SizeCalculator.cs
This fixes the texture sparse tile width alignment, when the texture/level is small enough to have at least one dimension that fits inside a single GOB. This is based on what NVIDIA does.
Fixes texture corruption on Astral Chain.
Before:
After:
=> Fix texture level offset/size calculation when sparse tile width is > 1

Ryujinx.Graphics.Gpu/MacroInterpreter.cs, Ryujinx.Graphics.Gpu/NvGpuFifo.cs, Ryujinx.Graphics.Gpu/State/GpuState.cs
This in an improvement of #987, the shadow ram control affects all writes, not only those coming from MME.
In addition to the linked PR, this fixes more issues with some games, like for example stencil mask being destroyed by a stencil clear.
This fixes for examlpe, stencil logo effect on Kill la Kill.
Before:
After:
Thanks again to @fincs for clarifying that.
=> Fix MME shadow RAM implementation

Ryujinx.Graphics.Gpu/State/GpuState.cs
Fixes a regression introduced by #1051 in conjunct with gpu-syncpoints PR, shadow RAM should not affect MME methods, and it should also not affect the shadow RAM control register itself.
=> Fix shadow RAM affecting MME methods

Ryujinx/Ryujinx.csproj
#1121 made a change to the package include condition, this PR reverts that change which fixes the issue where visual studio builds were missing dependencies.
=> Revert change to package include condition

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/State/ViewVolumeClipControl.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs
Fixes issues introduced by the depth clamp PR (#1120) while preserving all the benefits. (shadows not clipping out of existence) Also halves the polygon offset, as drivers seem to double the input when putting it into the register.
Example of issue caused by using the previous bits:
https://gyazo.com/35de04d5621763181575bda68d21d277
Fixed here, terrible cubemaps unrelated:
https://gyazo.com/e55978c51759214bb43a4c2c5221d26c
The odyssey still has a huge shadow, rather than the one that got cut off pre-depth-clamp.
Verified with deko3d and opengl code. Example:
https://github.com/devkitPro/deko3d/blob/4e47ba0013552e592a86ab7a2510d1e7dadf236a/source/maxwell/gpu_3d_state.cpp#L42
=> Fix depth clamp enable bit, unit scale for polygon offset.

Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/IAudioRenderer.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager/Types/RendererInfoOut.cs, Ryujinx.HLE/Utilities/StructWriter.cs
This implement the rendering information output of
RequestUpdate.
This is needed by some games to keep track of the count of update on the
DSP.
=> audren: implement Renderer Info output informations

ARMeilleure/Translation/Compiler.cs
Dominance information is not used when not in SSA form. So this should slightly improve the throughput of LCQ.
=> Do not compute dominance information when not in SSA

Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvDeviceFile.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostCtrl/NvHostCtrlDeviceFile.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostCtrl/Types/NvHostEvent.cs
This should fix Mario Tennis and LM3 regressions with syncpoints.
NOTE: Mario Tennis seems to have another issue related to the texture
cache that happens randomly sometime when starting a match.
PS: Also add a debug logger for all known ioctl call to facilitate
debugging and add a missing UpdateMin in EventSignal.
=> nvservices: mitigate abort with heavy load on the GPU processing thread

Ryujinx.Graphics.Gpu/Engine/MethodFifo.cs, Ryujinx.Graphics.Gpu/Synchronization/SynchronizationManager.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostCtrl/NvHostCtrlDeviceFile.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostCtrl/Types/NvHostEvent.cs, Ryujinx.HLE/HOS/Services/SurfaceFlinger/SurfaceFlinger.cs
Classic mistake.. this adds a lock inside NvHostEvent and on the events array as those could be manipulated asynchronously.
This should fix some weird race condition happening (example: event id 0 sometime being invalid between 7PM and 8PM on AC:NH when starting, ect)
=> nvservice: add a lock around NvHostEvent and remove release fence on SFv2

Ryujinx/Ryujinx.csproj
Revert this once again. This time it was broken by #1131
=> Revert package include condition

Ryujinx/Ui/ControllerWindow.cs
Fixes a combination of issues that lead to keyboard profiles not loading.
- `System.Text.Json` throws `JsonException` when parsing fails, not `ArgumentException`.
- Stream is closed by `JsonHelper.Deserialize` as it wraps it in a `BinaryReader`, which wraps deserializing in a using block. Closing the `BinaryReader` closes the enclosed `FileStream`.
- The stream does not seek to the beginning again when trying to parse keyboard config.
Changes the exception type, and gives each load attempt its own file stream.
(also sorted usings)
=> Fix issues causing keyboard profiles to throw errors on load.

Ryujinx.Graphics.Gpu/Memory/Buffer.cs
Invalidating the buffer on creation is not necessary, because `SynchronizeMemory` already invalidates all modified ranges. And for a newly created buffer, the entire range should be considered as "modified" since no check was performed before for the new ranges.
=> Remove buffer invalidation

Ryujinx.Graphics.Gpu/Image/TexturePool.cs
NVN uses special swizzle values for depth/stencil textures. Apparently R is Depth, and G is Stencil, while on 24-bit depth format, it is inverted (R is Stencil and G is Depth). This is something specific to the NVIDIA GPU, and we shouldn't pass this swizzle to the host, as setting the component to G breaks sampling the depth value. So, instead of passing the swizzle directly, now it fixes it up and passes the correct values. This does the same thing that NVN does, that is, (value, value, value, 1) for depth, and (value, value, value, value) for stencil.
This should fix issues like shadows not working on non-NVIDIA GPUs, or even on NVIDIA depending on the driver or context created.
=> Use correct swizzle on depth-stencil textures

Ryujinx/Ryujinx.csproj
This release should fix OpenGL context creation on OSX (using Cocoa).
NOTE: As macOS doesn't support OpenGL 4.3, the emulator will probably not work but this fix the hard crash when starting any games/homebrew.
=> Update GLWidget to 1.0.2

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.Gpu/Constants.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/State/MethodOffset.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs
Complements PR #680 
> Note that, despite redeclaring the output, you still have to glEnable the specific clip distances you intend to use. If you enable a clip distance, but do not write to it from the last vertex processing stage, you get undefined behavior. 
[Source](https://www.khronos.org/opengl/wiki/Vertex_Post-Processing#User-defined_clipping)
Games I tested set clip mask to `0xff`. I just hope that all games redeclare `gl_ClipDistance` properly.
Tested on NVIDIA only.
=> Implement user-defined clipping (gl_ClipDistance) on GL state pipeline

ARMeilleure/Common/BitMap.cs, ARMeilleure/Diagnostics/IRDumper.cs, ARMeilleure/Diagnostics/Symbols.cs, ARMeilleure/Translation/EmitterContext.cs, ARMeilleure/Translation/JumpTable.cs
Improves IRDumper to now dump:
MemoryOperand
```wasm
i64 r0 = Load i64 [i64 r1 + i64 r0*8]
```
IntrinsicOperation
```wasm
v128 v1 = Extended.X86Shufps v128 v1, v128 v0, i32 0xF0
```
Jump Table & Dynamic Table
```wasm
i64 %299 = Load i64 0x1DFFBB80018 ;; JMP_TABLE_1+8
...
i64 %289 = Copy i64 0x1DFFCB80010 ;; DYN_TABLE_1
i64 %295 = Copy i64 0x1DFFCB80018 ;; DYN_TABLE_1+8
```
Function names
```wasm
i64 %794 = Copy i64 0x7FFA30A038C4 ;; GetFunctionAddress
```
Multiple destinations
```wasm
i32 r0, i32 r3, i32 r1, i32 r2 = CpuId i32 r0
```
=> Improve IRDumper

.travis.yml
This configuration hasn't been used for years and isn't valid anymore anyway.
=> Remove travis configuration

ARMeilleure/ARMeilleure.csproj, Ryujinx.Audio/Ryujinx.Audio.csproj, Ryujinx.Common/Ryujinx.Common.csproj, Ryujinx.Debugger/Ryujinx.Debugger.csproj, Ryujinx.Graphics.GAL/Ryujinx.Graphics.GAL.csproj, Ryujinx.Graphics.Gpu/Ryujinx.Graphics.Gpu.csproj, Ryujinx.Graphics.Nvdec/Ryujinx.Graphics.Nvdec.csproj, Ryujinx.Graphics.OpenGL/Ryujinx.Graphics.OpenGL.csproj, Ryujinx.Graphics.Shader/Ryujinx.Graphics.Shader.csproj, Ryujinx.Graphics.Texture/Ryujinx.Graphics.Texture.csproj, Ryujinx.HLE/Ryujinx.HLE.csproj, Ryujinx.LLE/Luea.csproj, Ryujinx.ShaderTools/Ryujinx.ShaderTools.csproj, Ryujinx.Tests.Unicorn/Ryujinx.Tests.Unicorn.csproj, Ryujinx.Tests/Ryujinx.Tests.csproj, Ryujinx/Ryujinx.csproj
Some parts of our code needs C# 8 who isn't set as default in Visual Studio. To fix this we have to set the C# version correctly in the csproj files and then we are be able to build the project using Visual Studio.
=> Upgrade projects to C#8

Ryujinx/Program.cs
We currently logs system informations before we load the configuration file.
Since the logger use the configuration file (to sets if it should store the logs in a file, etc...), if we print something before the configuration init, the log file doesn't contains any system informations.
Now it's fixed.
=> Fix SystemInfo logging to file

ARMeilleure/Diagnostics/Logger.cs, Ryujinx.HLE/HOS/Applets/Controller/ControllerSupportArg.cs, Ryujinx.HLE/HOS/Applets/Controller/ControllerSupportArgHeader.cs, Ryujinx.HLE/HOS/Applets/Controller/ControllerSupportArgPrivate.cs, Ryujinx.HLE/HOS/Applets/Controller/ControllerSupportResultInfo.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMem/StructArrayHelpers.cs
Adds warning suppressions missed in #919. 
Also fix a pragma restore typo.
=> Suppress CS0169 CS0649 warns from HID structs

ARMeilleure/Translation/EmitterContext.cs
Previously blocks ending with a tailcall would still be linked to the next block, with this patch it does not.
This has the effect of unreachable blocks getting removed. Which causes quite a substantial diff, most of it is dead code removal. This should still improve both CQ and throughput, because in some cases there are much less variables to handle which helps the register allocators, and less IR to traverse.
I checked the diffs, but I could not see anything which gave me a thonk moment. Here are some sample diffs. IR is after Translation phase.
1. [IR](https://www.diffchecker.com/JmCNDoPl) - [CodeGen](https://www.diffchecker.com/a3NMobna)
2. [IR](https://www.diffchecker.com/9QKBWg26) - [CodeGen](https://www.diffchecker.com/reYdjtdJ)
If you need the full diff I can upload it here. I …
=> Fix tailcall case in EmitterContext

Ryujinx.HLE/HOS/Services/Time/ResultCode.cs
The error code was taken from Switchbrew (https://switchbrew.org/wiki/Error_codes)
Even if TimeServiceNotInitialized's "description" is 0, the result "value" of "(0 << ErrorCodeShift) | ModuleId" is 0x74 so it is not the same as "Success" (0)
=> Add missing error code to Time

ARMeilleure/CodeGen/X86/CodeGenerator.cs, ARMeilleure/CodeGen/X86/PreAllocator.cs, ARMeilleure/IntermediateRepresentation/Instruction.cs, ARMeilleure/Translation/EmitterContext.cs
#856 removed the uses of such instruction, and instead checks `System.Runtime.Intrinsics.X86.*` for availability of the various x86 extensions. This removes the now unused IR instruction. There is still support on the assembler, so if we need to read CPUID again, we can generate code directly using the assembler, which is imo a better solution. Plus there are plans to expose CPUID on .NET (see: https://github.com/dotnet/runtime/issues/785) so hopefully that will not be necessary at all in the future.
=> Remove CpuId IR instruction

ARMeilleure/Instructions/InstEmitFlow.cs
I could not catch any cases where the operand of `RET` was not `X30` though.
=> Fix RET Xn translation

Ryujinx.HLE/Ryujinx.HLE.csproj
Makes `DirectorySaveDataFileSystem` accurate to Nintendo's version, including retries on commit that should reduce any "TargetLocked" errors
=> Update to LibHac 0.11.2

Ryujinx.HLE/HOS/Horizon.cs
This should fix AC:NH events and probably other games.
=> time: Make sure to initialize the network system clock with a valid system clock

ARMeilleure/Instructions/InstEmitSystem.cs, ARMeilleure/Instructions/NativeInterface.cs, ARMeilleure/State/ExecutionContext.cs
This implements MRS load from `CNTVCT_EL0`. Not sure why a game needs to read a virtual timer, but ~~unprivileged access means `CNTVCT_EL0 = CNTPCT_EL0`.~~ since EL2 isn't implemented,  `CNTVCT_EL0 = CNTPCT_EL0`
Should Fix launch crash in https://github.com/Ryujinx/Ryujinx-Games-List/issues/1309
=> Implement CNTVCT_EL0

Ryujinx.Graphics.OpenGL/Pipeline.cs
It seemed that when busy looping for a query result, we'd be stuck waiting forever as the GL command to write the result to the buffer never went through. This forces a glFlush before we manually read off a query result that has not already been flushed, so that it is definitely written.
Should fix a freeze in Yo-Kai Watch 4. (gdk will need to verify)
=> Flush GL commands before inevitably waiting for a query result.

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs, Ryujinx.HLE/HOS/SystemState/SystemStateMgr.cs, Ryujinx.HLE/HOS/SystemState/TitleLanguage.cs
Fixes wrong language selection when application doesn't support set system language.
XC2
Splatoon 2
Before the fix, the above screens would show Japanese.
Please close this PR if it doesn't meet your standards. Just wrote a quick fix as it was annoying me. I've no interest in expanding this for now.
~~I give up. Can't even name the operation right~~ (Reworded 2nd commit to give proper name)
=> Fix GetDesiredLanguage

Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, Ryujinx.Graphics.OpenGL/HwCapabilities.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeImage.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs
When `EXT_shader_image_load_formatted` is supported, we don't need to specify the image format. In the future this will prevent shader recompilations due to image format changes. For now it can fix cases where a wrong/old image format was being used.
Additionally, fix the BA bit of the SULD/SUST instructions that was wrong aswell.
=> Omit image format if possible, and fix BA bit

Ryujinx.Graphics.Gpu/Engine/Compute.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Image/SamplerPool.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.Gpu/Memory/MemoryAccessor.cs, Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/Operation.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/TextureOperation.cs, Ryujinx.Graphics.Shader/StructuredIr/AstTextureOperation.cs, Ryujinx.Graphics.Shader/Translation/Lowering.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/Optimizer.cs
NVN gained support for binding separate textures and samplers. I don't know exactly at which version they started supporting it (and it's not really relevant here), but that means shaders can now have separate texture and sampler handles, and combine them on the shader. Doing so allows any of the bound textures to be sampled using any of the bound samplers. This is implemented using bindless texture instructions.
This change implements a pass on the shader translator that tries to find the handle sources for a given texture access on the shader, doing some sort of basic data flow analysis and code pattern recognition. When successful, it allows the textures to be bound as normal, and eliminates the need for bindless textures.
Currently, the games that uses separate textures and samplers, …
=> Support separate textures and samplers

Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.GAL/Origin.cs, Ryujinx.Graphics.GAL/ViewportSwizzle.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Image/Sampler.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, Ryujinx.Graphics.Gpu/State/GpuState.cs, Ryujinx.Graphics.OpenGL/EnumConversion.cs, Ryujinx.Graphics.OpenGL/HwCapabilities.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, Ryujinx.Graphics.Shader/Translation/TranslationFlags.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
NVN exposes a function that allows the application to set the origin of the window. It can be set to upper left (following Direct3D conventions), or lower left (following OpenGL). This should be directly equivalent to glClipControl on OpenGL.
The way how this is actually implemented on the GPU, however, is not directly equivalent. The GPU has a bit that changes something on the rasterization stage to take the different origin into account (nouveau calls this bit TriangleRastFlip). It does not flip the viewport, however. Flipping the viewport is done by using a negative value for the viewport scale.
So when the UpperLeft mode is used, NVN does 2 things:
- Negates the viewport Y scale value. This effectively flips the viewport, so all the geometry is flipped on the Y direction. This also …
=> Fix wrong face culling once and for all

Ryujinx.Graphics.Gpu/Engine/MethodFifo.cs, Ryujinx.Graphics.Gpu/Engine/MethodReport.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/State/FifoSemaphoreOperation.cs, Ryujinx.Graphics.Gpu/State/MethodOffset.cs, Ryujinx.Graphics.Gpu/State/SemaphoreOperation.cs, Ryujinx.Graphics.Gpu/State/SemaphoreState.cs
Similar to the 3D engine semaphore, but for PFIFO.
Most fields on the control register are not documented (or at least I'm not aware of any docs), and can't be inferred from NVN RE alone, so this is only a partial implementation, but should be enough for everything that can be currently done with NVN.
=> Implement FIFO semaphore

ARMeilleure/CodeGen/X86/Assembler.cs, ARMeilleure/CodeGen/X86/IntrinsicTable.cs, ARMeilleure/CodeGen/X86/X86Instruction.cs, ARMeilleure/Instructions/InstEmitHash.cs, ARMeilleure/IntermediateRepresentation/Intrinsic.cs, ARMeilleure/Optimizations.cs
Implement crc32 in terms of pclmulqdq.
Logic hopefully should be obvious.
---
Edit: It's essentially just a Barrett reduction.
The above image is from the Intel whitepaper. My implementation differs from Intel's because I optimized it a bit more with a few tricks.
=> Faster crc32 implementation

Ryujinx.Common/Logging/Logger.cs
This can reduces cases where the game locks-up/crashes because the console is in Select mode or manually scrolled.
File log seems to work as usual.
=> Change Console Logging to discard on overflow

Ryujinx.Graphics.Gpu/Engine/MethodCopyBuffer.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Texture/BlockLinearLayout.cs, Ryujinx.Graphics.Texture/Bpp12Pixel.cs, Ryujinx.Graphics.Texture/LayoutConverter.cs, Ryujinx.Graphics.Texture/OffsetCalculator.cs
I'd recommend testing this on a few games to make sure nothing terrible happens, as it's pretty easy to make a mistake here. Greatly speeds up texture loading and flushing (though the GPU will still have to stall for this in master).
Most affected games: Nintendo Switch Online: Super Nintendo Entertainment System (and the NES one), any frames that uses nvdec (MK8 menu, SMO menu + tutorials, probably large black screen videos), maybe a bit less GPU related stuttering in games that stream textures.
List of changes:
- LayoutConverter has separate optimizations for LinearStrided and BlockLinear.
- Block linear now copies using a generic unsafe helper method, that is passed a type representative of the pixel format we're manipulating. This allows us to obtain a function compiled specifically …
=> Optimize texture format conversion, and MethodCopyBuffer

ARMeilleure/Decoders/OpCodeTable.cs
This fixes an issue where part of the VABS instruction would be parsed as an input register, triggering an "undefined" instruction specifically when using it with quadword vectors. It registered the phantom input register as invalid, as it was not divisible by two.
=> VABS takes one input register, not two.

ARMeilleure/Decoders/Block.cs, ARMeilleure/Decoders/Decoder.cs, ARMeilleure/Decoders/Optimizations/TailCallRemover.cs, ARMeilleure/Instructions/InstEmitException.cs, ARMeilleure/Instructions/InstEmitException32.cs, ARMeilleure/Instructions/InstEmitFlow.cs, ARMeilleure/Instructions/InstEmitFlow32.cs, ARMeilleure/Instructions/InstEmitFlowHelper.cs, ARMeilleure/Translation/Translator.cs
Introduce "Exit" blocks (essentially pseudo blocks) which represents a continuation.
The `Branch` and `Next` which would be null (before this PR) are now created as "Exit" blocks and are inserted into the ordered decoded block list. The `Translator` then emits tail continues for these "Exit" blocks and branch instructions can be emitted without the null checks as the "Exit" blocks are address labeled.
Reduces redundant tail continues. For example:
```asm
0x8000ac0:      C8 02 40 F9            ldr	x8, [x22]
0x8000ac4:      1F 1D 00 F1            cmp	x8, #7
0x8000ac8:      E8 17 9F 1A            cset	w8, eq
0x8000acc:      68 C2 00 39            strb	w8, [x19, #0x30]
0x8000ad0:      C8 02 40 F9            ldr	x8, [x22]
0x8000ad4:      1F 1D 00 F1            cmp	x8, #7
0x8000ad8:      20 FB …
```
=> Generalize tail continues

Ryujinx.HLE/FileSystem/Content/ContentManager.cs, Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs, Ryujinx.HLE/HOS/Services/Ns/IAddOnContentManager.cs, Ryujinx.HLE/HOS/Services/Ns/IPurchaseEventManager.cs
Implements most of `IAddOnContentManager` based on fw 9.2.0 RE and a little bit from 10.0.0.
~~Also adds support for reading AddOnContent embedded in XCI.~~
This is my first RE work in this project so please be extra critical.
Supersedes #1218 (Sorry @AcK77 !)
Fixes #636
**EDIT:**
Now supports reading embedded AOC from XCI and NSP. Also, automatically loads any AOC NSPs in the game's base directory.
With some GUI work, custom AOC paths can be added and toggled.
~~Depends on #1236~~
=> Implement aoc:u and support loading AddOnContent

Ryujinx.Graphics.Gpu/Engine/Compute.cs
When using certain storage buffers on compute shaders, there is a optimization pass that transform them into uniform buffers, since NVN uses global memory load/store to "emulate" more uniform buffers than the hardware actually supports on compute (hardware only supports 8, NVN exposes 14). It is not possible to use storage buffers for that aswell, because most drivers only supports up to 16 storage buffers.
When reading storage buffer descriptor information (that the shader reads to calculate the LDG/STG address), there was an error that made it calculate the wrong offset, and bind the wrong data on the uniform buffer. The fix is just correcting the calculation.
This fixes a regression caused by #924 on Tokyo Mirage Sessions, reported several months ago by "kakasita". Of course, other …
=> Fix regression caused by wrong SB descriptor offset

Ryujinx/Ui/GLRenderer.cs
Fixes this exception:
```
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
at Ryujinx.Ui.GlRenderer.UpdateFrame() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 367
at Ryujinx.Ui.GlRenderer.MainLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 361
at Ryujinx.Ui.GlRenderer.Start() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 205
at Ryujinx.Ui.MainWindow.CreateGameWindow(Switch device) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 473
at Ryujinx.Ui.MainWindow.<>c__DisplayClass48_0.<LoadApplication>b__1() in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 424
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at …
```
=> Copy the value of InputConfig to a new array before iterating

ARMeilleure/Decoders/OpCodeTable.cs, ARMeilleure/Instructions/InstEmitSimdArithmetic32.cs, ARMeilleure/Instructions/InstEmitSimdMove32.cs, ARMeilleure/Instructions/InstName.cs, ARMeilleure/Translation/PTC/Ptc.cs, Ryujinx.Tests/Cpu/CpuTestSimdMov32.cs, Ryujinx.Tests/Cpu/CpuTestSimdReg32.cs
Just a few more instructions I've seen games using. Should compliment valx's PR pretty well.
VMVN (immediate) has been renamed from `VMVN_I` to `VMVN_II`, to make way for the integer variant, and it has also been fixed to use BitwiseNot rather than xor the input with itself for whatever reason.
I've added new tests for all the instructions listed, and added a better test for VPADD (and its integer variant). The floating point pairwise instruction tests will only pass if FastFP is false, but I have verified that the intrinsic versions do work with regular values that aren't NaNs, Infinities and whatnot.
The non floating point tests also pass with intrinsic paths disabled. (VMVN, pairwise integer)
=> Fix VMVN (immediate), Add VPMIN, VPMAX, VMVN (register)

Ryujinx.Graphics.Gpu/Synchronization/Syncpoint.cs
This should fix a deadlock on the following scenario:
Render thread calls `Syncpoint.Increment` that will lock `_listLock`, and then will call `GpuSignaled` that will attempt to lock `Lock` on the NvHostEvent.
The nvservices thread calls `Cancel` that will lock the `Lock` on NvHostEvent, then it will call `UnregisterCallback` that attempts to lock `_listLock`.
The render thread can't progress because the nvservices thread holds `Lock`.
The nvservices thread can't progress because the render thread holds `_listLock`.
The symptoms are the fps counter freezing as the render thread is blocked. Deadlocks not showing those symptoms are likely caused by something else and won't be fixed by this.
I tried to come up with a better way to handle concurrency without locking everywhere, but couldn't …
=> Call syncpoint expiration callback outside of the lock

Ryujinx.Graphics.Gpu/Engine/Compute.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs
After doing compute work, the GPU emulation has to switch back to the previous shader that was set. Currently it does that by calling the `UpdateState` method passing, that will read parameters from the GPU state passed and read shader address etc, then translate the shader (if needed), and bind the shader on the host side, then set all required textures, uniform buffers and others. The problem is that it was doing all that using the state of the compute engine, instead of the 3D engine state. The fix here is simply deferring the update to when it is actually needed (before draw).
Should fix issues on games using compute that does not immediately change graphics shader before doing compute work.
Improves: https://github.com/Ryujinx/Ryujinx-Games-List/issues/1672 (but does not completely …
=> Fix compute restore of previous shader state

Ryujinx.HLE/HOS/Services/Nifm/ResultCode.cs, Ryujinx.HLE/HOS/Services/Nifm/StaticService/IRequest.cs
Stubs `GetAppletInfo` to be consistent with current `GetResult` implementation.
Fix #671
=> Stub nifm IRequest GetAppletInfo

Ryujinx/Ui/SettingsWindow.cs
The default way Ryujinx does this is one directory at a time. This PR makes it so you can choose to add as many directories as you want at once.
=> SettingsWindow: Add the ability to add multiple game directories at once

Ryujinx.Graphics.Gpu/Engine/MethodCopyBuffer.cs, Ryujinx.Graphics.Texture/BlockLinearLayout.cs, Ryujinx.Graphics.Texture/LayoutConverter.cs, Ryujinx.Graphics.Texture/OffsetCalculator.cs
Fixes copy from a buffer to a 3D texture (when used for linear to block linear conversion). Previously the Depth in GOBs was being ignored.
Improves rendering on games like Persona 5 Scramble:
Before:
After:
Notes: Used the trick to bypass lockup at the start to test.
=> Fix buffer to 3D texture copy

Ryujinx.Graphics.Shader/Decoders/BitfieldExtensions.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeTable.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitAlu.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/Optimizer.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
- Partial implementation of shader LEA (Load Effective Address) instruction, still missing .HI variants (not added to the opcode table, so they will still display as unknown), as handling of CC flags. This is very similar to ISCADD, it scales (left shifts) a value and adds another, useful for indexing offset calculation.
- Extend bindless elimination optimization introduced on #1216 to also match simple patterns used on image load/store, like the following:
```
/*2e68*/         {         MOV R12, c[0x2][0x120] ;
/*2ed0*/                   SUST.P.2D.IGN [R8], R0, R12 ;
/*2f10*/                   SUST.P.2D.IGN [R10], R4, R12 ;
```
We can propagate `c[0x2][0x120]` to the SUST instructions, and bind the image.
This improves rendering on Persona 5 Scramble.
Before:
After:
Note: This was tested …
=> Implement shader LEA instruction and improve bindless image load/store

Ryujinx.HLE/HOS/Services/Prepo/IPrepoService.cs
On 10.x, Nintendo changed yet another time the prepo SaveReport &
SaveReportWithUser command ids.
This PR add support for command 10104 & 10105 and update naming of the
old variants to match switchbrew.
This fix any game using 10.x based sdknso and telemetry. (like AC:NH 1.3.0)
=> prepo: Update implementation for 10.x changes

Ryujinx.Common/Logging/LogClass.cs, Ryujinx.HLE/FileSystem/VirtualFileSystem.cs, Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs, Ryujinx.HLE/HOS/Kernel/Process/ProcessCreationInfo.cs, Ryujinx.HLE/HOS/ModLoader.cs, Ryujinx.HLE/HOS/ProgramLoader.cs, Ryujinx.HLE/HOS/Services/Ro/IRoInterface.cs, Ryujinx.HLE/Loaders/Executables/IExecutable.cs, Ryujinx.HLE/Loaders/Executables/KipExecutable.cs, Ryujinx.HLE/Loaders/Executables/NroExecutable.cs, Ryujinx.HLE/Loaders/Executables/NsoExecutable.cs, Ryujinx.HLE/Loaders/Mods/IPSPatcher.cs, Ryujinx.HLE/Loaders/Mods/IPSwitchPatcher.cs, Ryujinx.HLE/Loaders/Mods/MemPatch.cs, Ryujinx.HLE/Loaders/Npdm/Npdm.cs, Ryujinx/Ui/GameTableContextMenu.cs, Ryujinx/Ui/MainWindow.cs
This PR adds full support for mods. It follows [Atmosphère's](https://github.com/Atmosphere-NX/Atmosphere) structure with some enhancements for host FS and emulators convenience.
```
// named file replacers [RECOMMENDED]
@mods/contents/<program id>/<mod dir>/romfs/*   [loose files]
@mods/contents/<program id>/<mod dir>/exefs/*   [loose files]
// named patches [RECOMMENDED]
@mods/exefs_patches/<mod dir>/<build id>.ips|*.pchtxt
@mods/nro_patches  /<mod dir>/<build id>.ips|*.pchtxt
@mods/kip_patches  /<mod dir>/<KIP SHA256>.ips
// named title-specific patches [ENHANCEMENT]
@mods/contents/<program id>/<mod dir>/exefs/<build id>.ips|*.pchtxt
// global replacers [COMPATIBILITY, with ams]
@mods/contents/<program id>/romfs.bin
@mods/contents/<program id>/exefs.nsp
@mods/contents/<program …
```
=> Implement modding support

ARMeilleure/CodeGen/Optimizations/ConstantFolding.cs, ARMeilleure/Translation/PTC/Ptc.cs
Creates more opportunities for copy propagation. For example:
```patch
block82 (branch block85):
- i32 %179 = ConvertI64ToI32 i64 0x0
- Call i64 0x7FF85FA30444, i64 %177, i32 %179 ;; WriteByte
+ Call i64 0x7FF888910444, i64 %171, i32 0x0 ;; WriteByte
Branch
```
=> Fold ConvertI64ToI32 imm64

ARMeilleure/CodeGen/Optimizations/ConstantFolding.cs, ARMeilleure/Translation/PTC/Ptc.cs
Can improve codegen of code dealing with a lot of 32 bit integers. For example:
```patch
block61 (next block62) (branch block63):
- i64 %124 = ZeroExtend32 i32 0x1
- i64 %125 = ZeroExtend32 i32 0x5
- i64 %126 = ZeroExtend32 i32 0x14
- i64 %127 = ZeroExtend32 i32 0x3
i64 %128 = Add i64 %18, i64 0xE0
i64 %129 = BitwiseAnd i64 %128, i64 0xFFFFFF8000000000
BranchIfFalse i64 %129
```
These gets constant folded and copy propagated into their use.
=> Fold ZeroExtend8/16/32 imm32/64

ARMeilleure/CodeGen/X86/Assembler.cs, ARMeilleure/Translation/PTC/Ptc.cs
#1358 allows some zero extension operations to be constant folded, with this optimization, some now (considered invalid as they are >= 32/64) are now propagated to shift instructions. That was making the x86 backend throw when trying to encode such shift instructions.
Example of problematic code:
```
i32 %2193 = ZeroExtend8 i32 0x17056D0
i32 %2194 = CompareEqual i32 %2193, i32 0x0
i32 %2195 = CompareGreaterOrEqual i32 %2193, i32 0x20
i32 %2196 = ShiftLeft i32 r12, i32 %2193
i32 %2197 = ConditionalSelect i32 %2195, i32 0x0, i32 %2196
```
After optimizations:
```
i32 r0 = Copy i32 0x0
i32 r0 = CompareEqual i32 r0, i32 0xD0
i32 r1 = Copy i32 0xD0
i32 r1 = CompareGreaterOrEqual i32 r1, i32 0x20
i32 r8 = Copy i32 r11
i32 r8 = ShiftLeft i32 r8, i32 0xD0
i32 r9 = Copy i32 0x0
i32 r8 = Copy i32 …
```
=> Mask shift constants on x86 backend

ARMeilleure/CodeGen/Optimizations/ConstantFolding.cs, ARMeilleure/Translation/PTC/Ptc.cs
Fixes an issue with #1359 where by the operand types can get mismatched. For example:
This
```wasm
i32 %52 = ConvertI64ToI32 i64 0x0
```
would become this
```wasm
i32 %52 = Copy i64 0x0
```
Then on the second pass of the optimizer on the block, `ConstantFolding` transforms it to
```wasm
i32 %52 = Copy i32 0x0
```
This can cause asserts in the assembler to be fired (because of src/dst type mismatch) when the optimizer does not do another pass after the folding of `ConvertI64ToI32`. This can happen when a ConvertI64ToI32 got constant folded but no copy propagation or removal of unused nodes has occurred. So `modified` remains false and the pass to retype the copies never happens.
=> Fix folding of ConvertI64ToI32 imm64

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.Gpu/Image/TextureSearchFlags.cs
The 2D engine does not support depth-stencil formats, so equivalent color formats are used for the copy. This modifies the compatibility check to match equivalent color formats when searching for copy textures.
Should fix broken fog on Pokémon Sword/Shield.
I recommend testing on a few games to ensure no regressions. It might be also worth revisiting this in the future, I don't like this approach to be honest.
=> Fix depth stencil formats copy by matching equivalent color formats

Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/ModLoader.cs
Fixes emulator crashes due to a missed code-path for mod loading when loading unpacked games.
Thanks to @Thog for pointing this out!
=> Fix crash when loading via LoadCart (mods)

ARMeilleure/Decoders/Decoder.cs
Fixes an oversight with the condition for the exception introduced in #1298.
The old condition could never be true, because `GetBlock` will return a block no matter what, so the minimum number of blocks is actually 1.
=> Fix Decode exception condition

Ryujinx.Graphics.Gpu/Memory/BufferManager.cs
When a buffer is deleted and replaced by another one, the buffer manager forces all the buffers to be rebound before the next draw, to ensure there's no deleted buffer still being used. The rebind flag was being ignored for TFB buffers, this fixes this issue.
Seems to fix TFB not working on games like Xenoblade Chronicles 2:
=> Force TFB rebind after buffer modifications

Ryujinx.HLE/HOS/Kernel/Common/KernelTransfer.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs, Ryujinx.HLE/HOS/Kernel/Threading/KSynchronization.cs, Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs
This updates the `WaitSynchronization` syscall implementation to match what the kernel does.
This mostly just add more checks/missing errors that the kernel returns. I don't expect it to improve anything in relation to official games (and hopefully also not regress anything). I recommend testing with a few games if possible, just to be sure that it didn't break anything (I did so myself).
=> Improve kernel WaitSynchronization syscall implementation

Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
Some games call svcBreak with the debug flag set (which is normal, probably just used for debugging). In those cases we currently print the guest stack trace. However it is not adding any value as this is not a error, plus the unwinding could slow down a bit some games that calls it constantly, and it causes issues on some games as the unwinding code is sometimes throwing. So this change removes the log.
=> Do not print guest stack trace for svcBreak debug calls

Ryujinx.HLE/HOS/Kernel/Ipc/KClientSession.cs, Ryujinx.HLE/HOS/Kernel/Memory/KMemoryManager.cs, Ryujinx.HLE/HOS/Kernel/Memory/KTransferMemory.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs, Ryujinx.HLE/HOS/Services/Sm/IUserInterface.cs
- Improve implementation of `CreateTransferMemory` and `CloseHandle` syscalls. It now matches N kernel.
- Fix session services not being disposed. They are not disposed on the `Destroy` method of `KClientSession`, called when the reference count reaches 0, instead of being called on `CloseHandle` for `KSession`.
- Decrement references server/client session on SM `GetService` function. This was done to match what is done on the `CreateSession` syscall. Since we can't use the syscall on SM yet, it is necessary to replicate the behavior there.
This should not have any negative effect on games, but could potentially break something as the `CreateTransferMemory` syscall was changed, which games uses.
=> Fix session service disposal and improve transfer memory implementation

Ryujinx.HLE/HOS/Services/IpcService.cs
This fix a missing part of #1397, making all HLE ipc sessions being disposed when needed.
This is needed for some upcoming wip changes.
=> ipc hle: Fix disposing of session created with MakeObject

Ryujinx.HLE/HOS/Services/Bcat/ServiceCreator/IDeliveryCacheProgressService.cs
The function should copy, not move the handle to the client (the comment on top of the function says so aswell). Before it was returning the handle at the wrong place. This fixes a issue that was uncovered after #1362 that improved the WaitSynchronization implementation. Fixes a regression in SSBU.
=> Fix IDeliveryCacheProgressService GetEvent

Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZoneContentManager.cs, Ryujinx/Ui/SettingsWindow.cs, Ryujinx/Ui/SettingsWindow.glade
Improves the display and sort order of timezones in System Settings.
Dynamically gets the current transition timezone offset from zoneinfo.
Locations from `/zoneinfo/Etc/*` are removed.
I have no way of testing this. But, everything should work the same as before as only labels have changed.
**EDIT:** Now uses an auto-completing entry box. Supports typing region names as well as tz offsets. Attached is a small demo video.
[TZ Entry.zip](https://github.com/Ryujinx/Ryujinx/files/4656032/TZ.Entry.zip)
=> Better TimeZone entry in System Settings

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/LibraryAppletCreator/ILibraryAppletAccessor.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs, Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs, Ryujinx.HLE/HOS/Services/Am/ResultCode.cs
This implement/stub some am calls:
- SetAutoSleepDisabled
- IsAutoSleepDisabled
- SetAlbumImageTakenNotificationEnabled
- EnableApplicationCrashReport
- GetPreviousProgramIndex
- NeedsToExitProcess
- RequestForAppletToGetForeground
- GetIndirectLayerConsumerHandle
All checked by RE.
Additionnaly to that, there is some cleanup here and there.
Fix #1387, #1324, #1165, #1163, #1065
=> Add multiple calls to am service

Ryujinx/Ui/MainWindow.cs
Fixes the issue where the fullscreen toggle does not update it's label properly. Also fixes the issue where the menu and footer do not hide when you are starting a game while already in fullscreen.
=> Fix Fullscreen toggling

ARMeilleure/State/NativeContext.cs
Change NativeContext to use a struct cast internally, instead of manually calculating sizes/offset and using Marshal Read and Write methods. This makes extending it on the future easier, and bugs less likely to happen. It also fixes 2 bugs on the previous implementation:
- Calculated NativeContext size was 4 bytes lower than it should, since it was counting `CallAddress` as 4 bytes long, not 8. Probably wasn't an issue since allocations are page aligned (?).
- The offset calculates for `FpFlags` was wrong. It was storing both `Flags` and `FpFlags` at the same offset, which means that their flags could overwrite each other (I think that only affects the Qc flag).
This was part of some older changes that I had here that became stale, figured it was worth to PR this separately.
=> Refactor NativeContext

ARMeilleure/Translation/PTC/Ptc.cs
#1410 changed the layout of the NativeContext. Since the offsets are hardcoded on the generated code, it needs a PPTC version increment. This increments the version, something that was missed on the original PR.
=> PPTC version increment

Ryujinx.Graphics.GAL/Format.cs, Ryujinx.Graphics.OpenGL/FormatTable.cs, Ryujinx.Graphics.OpenGL/Image/TextureBase.cs, Ryujinx.Graphics.OpenGL/Image/TextureCopy.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Program.cs, Ryujinx.Graphics.OpenGL/Window.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/DefaultNames.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/Translation/AttributeConsts.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, Ryujinx.HLE/HOS/Services/SurfaceFlinger/SurfaceFlinger.cs
This adds proper support for BGRA8 textures. OpenGL does not support this format, so before data was just being written as RGBA. This actually emulates BGRA with the following method:
- When the BGRA texture is used as render target, the R and B components are swapped on the pixel shader. New uniforms were added to indicate if the given output N should have their components swapped. Note that this will consume one extra constant buffer, that can't be used for game constant buffers anymore (however this was already the case with resolution scaling enabled).
- When a BGRA texture is bound, the R and B components are swapped on the swizzle parameters.
- When a BGRA texture is copied to another non-BGRA texture (and vice-versa), it first swaps R and B doing a PBO copy to a temporary texture, …
=> Implement BGRA texture support

Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.OpenGL/HwCapabilities.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs
This uses the polygon offset clamp value set by the game if the host supports it. I don't know any game that uses a non-zero value for the clamp, so I'm not aware of any game that would be affected by this change.
=> Use polygon offset clamp if supported

Ryujinx.Common/Logging/LogClass.cs, Ryujinx.HLE/HOS/Services/Nim/IShopServiceAccessServer.cs, Ryujinx.HLE/HOS/Services/Nim/IShopServiceAccessServerInterface.cs, Ryujinx.HLE/HOS/Services/Nim/IShopServiceAccessor.cs, Ryujinx.HLE/HOS/Services/Nim/IShopServiceAsync.cs, Ryujinx.HLE/HOS/Services/Ns/IAddOnContentManager.cs, Ryujinx.HLE/HOS/Services/Ns/IPurchaseEventManager.cs
As we aren't able to process purchase on the eShop throught the emulator, I have:
- Stub IPurchaseEventManager::SetDefaultDeliveryTarget (with RE check).
- Implement IPurchaseEventManager::GetPurchasedEventReadableHandle (with RE check).
As we can't do any eShop async call throught the emulator, I have:
- Stub IShopServiceAccessServerInterface::CreateServerInterface
- Stub IShopServiceAccessServer::CreateAccessorInterface
- Stub IShopServiceAccessor::IShopServiceAsync
Close #1084 and #1322
Pokémon Café Mix is now fully playable:
=> ns/nim: Stub eShop related calls

Ryujinx.Graphics.Vic/Image/SurfaceWriter.cs
Implements the missing BGRA output surface format on VIC, needed for video decoding on some games. The only game I know that uses this format is The Caligula Effect, and videos now render on this title:
Notes:
- Requires #1418 to render without swapped B/R channels.
- Needs swkbd modification to go ingame, otherwise it complains that the name is too long (max is 6 characters, Ryujinx has 7).
=> Implement VIC BGRA output surface format

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/GlslGenerator.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/Translation/TranslationFlags.cs
#1370 introduced some changes to varying layout to allow capture for transform feedback. Those varying caused a regression on Intel iGPUs on windows were the shader was failing to link due to a compiler bug, it shows the following error:
```
SHADER_ID_LINK error has been generated. GLSL link failed for program 3, "": Varying "in_attr1_x" has different type qualifier across different shaders.
```
Since the changes on the layout are only needed to support transform feedback, this reverts the changes when transform feedback is not enabled. This fixes the regression on Intel, while still allowing transform feedback to work. NOTE: Transform feedback is not going to work on Intel + Windows.
=> Fix shader regression on Intel iGPUs by reverting layout changes

ARMeilleure/CodeGen/X86/CodeGenerator.cs, ARMeilleure/Translation/PTC/Ptc.cs
Prefer `movd`/`movq` over `pextrd`/`pextrq` when extracting element 0 of a vector for i32/i64.
```patch
@@ -84,7 +84,7 @@
jz .L7
.L5:
movdqu xmm0,[rsp+0xa0]
-  pextrq rbx,xmm0,0x0
+  movq rbx,xmm0
mov rbp,WriteUInt64
mov rax,[rsp+0xbc]
mov rcx,rax
@@ -1012,7 +1012,7 @@
movdqu xmm0,xmm4
movdqu [rsp+0x124],xmm0
movdqu xmm0,[rsp+0x124]
-  pextrd ebp,xmm0,0x0
+  movd ebp,xmm0
mov ebp,ebp
mov rax,rbp
mov [rsp+0x8c],rax
```
This makes `Instrinsic.X86Cvtsi2si %x` unnecessary since these operations can now be replaced by a `i32/i64 VectorExtract %x, 0x0` instead.
=> Use movd,movq for i32/64 VectorExtract %x, 0x0

Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
The main goal here is reducing the number of out arguments on the `Decode` function (from 3 to 1). The other out args were moved to the `ShaderConfig` struct. Said struct was also changed to a class as there was no advantage in keeping it a struct, plus it was necessary for those changes to work. as otherwise it would have copy semantics and the new methods added wouldn't change what it should.
The intention of those changes is just improving the code without any changes on functionality.
=> Refactor shader translator ShaderConfig and reduce the number of out args

ARMeilleure/Instructions/InstEmitMemoryHelper.cs, Ryujinx.Cpu/InvalidAccessHandler.cs, Ryujinx.Cpu/MemoryManager.cs, Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs, Ryujinx.HLE/HOS/Kernel/Threading/KScheduler.cs, Ryujinx.Memory/InvalidMemoryRegionException.cs, Ryujinx.Memory/MemoryBlock.cs
- Prints the guest stack trace when a invalid memory access occurs on the guest, instead of just throwing "AccessViolationException".
- Prints the guest stack trace on attempts to execute a undefined instruction (useful for invalid instructions, not so much for unimplemented instructions).
- Change `ArgumentOutOfRangeException` to custom `InvalidMemoryRegionException` on `MemoryBlock`. The former is too generic and would be problematic when using try/catch to handle invalid access.
Should have no performance impact, on the codegen, one jump will change (from less to less than or equal), this forces the slow path to be taken, and the costly validity checks are done there.
=>  Print guest stack trace on invalid memory access 

Ryujinx.Common/SystemInfo/WindowsSystemInfo.cs
We currently don't check if WMI service is available when we get the CPU name and the RAM size.
This fix the issue by catching all exceptions and set default values instead.
Close #1353
=> common: Fix WMI exception

Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
This is required by AC:NH for the new online save features of 1.4.0
NOTE: I haven't bothered to add the IPC comment as most of the FS interface is missing that right now. (will surely do something about that in a next PR)
=> fs: stub ReadSaveDataFileSystemExtraDataWithMaskBySaveDataAttribute

Ryujinx.Common/Configuration/ConfigurationFileFormat.cs, Ryujinx.Common/Configuration/ConfigurationState.cs, Ryujinx.Common/Configuration/GraphicsDebugLevel.cs, Ryujinx.Graphics.GAL/IRenderer.cs, Ryujinx.Graphics.OpenGL/Debugger.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx/Ui/GLRenderer.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/SettingsWindow.cs, Ryujinx/Ui/SettingsWindow.glade
Provides a GUI option to toggle logging of OpenGL debug output.
Improves GL Debug output. Prints call stacks on `GL_ERROR`s.
Also, moves developer-centric logging options to their own category.
I've added the different levels based on little experience with debug output. I'm open to suggestions.
Here's the UI layout-
**Note:** This PR is mostly a developer tool. Does not benefit end-users directly.
=> Facilitate OpenGL debug logging via GUI

Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoClass.cs, Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs, Ryujinx.Graphics.Gpu/Engine/MME/AluOperation.cs, Ryujinx.Graphics.Gpu/Engine/MME/AluRegOperation.cs, Ryujinx.Graphics.Gpu/Engine/MME/AssignmentOperation.cs, Ryujinx.Graphics.Gpu/Engine/MME/IMacroEE.cs, Ryujinx.Graphics.Gpu/Engine/MME/Macro.cs, Ryujinx.Graphics.Gpu/Engine/MME/MacroInterpreter.cs, Ryujinx.Graphics.Gpu/Engine/MME/MacroJit.cs, Ryujinx.Graphics.Gpu/Engine/MME/MacroJitCompiler.cs, Ryujinx.Graphics.Gpu/Engine/MME/MacroJitContext.cs, Ryujinx.Graphics.Gpu/GraphicsConfig.cs, Ryujinx.Graphics.Gpu/State/GpuState.cs
This implement a Macro JIT. It improves the speed of GPU Macro execution by recompiling the code to the host architecture on-demand. Macros are small programs that can read/write GPU registers. Macros are usually very small and simple, and for this reason, there's not much benefit in replacing the interpreter by a JIT. When you have < 50 instructions to run, it just doesn't make that much difference.
This could bring a small speed-up for games using instanced draws, since they use a macro with a loop for them.
Sample CodeGen:
Macro:
```
00000000: 00110071     maddrsend 0x44
00000001: 07400451     parm $r4 maddr 0x1d00
00000002: 00000301     parm $r3
00000003: 00000041     send 0x0
00000004: 00002041     send $r4
00000005: 00001841     send $r3
00000006: 02310021     maddr 0x8c4
00000007: …
```
=> Implement a Macro JIT

Ryujinx.Common/Configuration/GraphicsDebugLevel.cs, Ryujinx.Graphics.OpenGL/Debugger.cs, Ryujinx/Ui/SettingsWindow.glade
Users seem to be infatuated with the new OpenGL debug log option even when placed under Developer options.
This PR tries to dissuade them from fake love.
=> Fix OpenGL debug's allure

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/missing_cpu_instruction.md, .github/ISSUE_TEMPLATE/missing_service_call.md
This disable the creation of empty issues and adds some templates when one is opened.
A link to our discord is directly added to the issue templates list.
Thanks EmulationFanatic for the proof reading.
=> Add Issue Templates

Ryujinx/Ui/SettingsWindow.cs, Ryujinx/Ui/SettingsWindow.glade
This PR fixes the issue of the dummy backend being selected by default when OpenAL is unavailable.
All the backends are in the list but OpenAL and SoundIO is unselectable by the user until their IsSupported function return true. If an unavailable backend is selected by the config, it will still be selected in the UI meaning we wont have that same crash from the 1st version.
=> Replace the Audio Backend ComboBoxText to a ComboBox with a custom model

Ryujinx.HLE/HOS/Services/Bluetooth/IBluetoothDriver.cs
This fix the InitializeBluetoothLe call who didn't return a event handle
=> bluetooth: Fix event handle in IBluetoothDriver

Ryujinx.Graphics.Gpu/Engine/MME/MacroJitCompiler.cs
from: `result = (ulong)a + ((ulong)b - -(ulong)_carry);`
to: `result = (ulong)a - ((ulong)b - (ulong)(1 - _carry));`
(using `MacroInterpreter.cs` as a reference and assuming `_carry` as an `int [0|1]`)
Affected titles:
Ryujinx/Ryujinx-Games-List#1852 (the bug caused black screen and memory leak)
and maybe others
=> Fix MacroJit SubtractWithBorrow Alu Reg Operation.

Ryujinx.Graphics.Gpu/Engine/MethodCopyTexture.cs
Texture copies between depth and color formats aren't allowed in OGL.
Bgra Support (https://github.com/Ryujinx/Ryujinx/pull/1418) exposed an existing bug in texture copies with a new OGL error-
```
GL_INVALID_OPERATION error generated. The <type> and <format> pair is not suppported
```
The root cause for the error was https://github.com/Ryujinx/Ryujinx/pull/1198, which relaxed format matching rules.
But this wasn't reflected in `Methods.CopyTexture()`. This PR updates that check.
Resolves the above OGL error SPAM, removes blur flicker and fixes performance regression after Bgra support in ZLA.
**Note:** Does not fix all graphical glitches in ZLA.
=> Add missing depth-color conversions in CopyTexture

Ryujinx.Audio.Renderer/Dsp/AudioProcessor.cs, Ryujinx.Audio/Downmixing.cs, Ryujinx.Audio/DspUtils.cs, Ryujinx.Audio/IAalOutput.cs, Ryujinx.Audio/Native/libsoundio/SoundIODevice.cs, Ryujinx.Audio/Renderers/DummyAudioOut.cs, Ryujinx.Audio/Renderers/OpenAL/OpenALAudioOut.cs, Ryujinx.Audio/Renderers/OpenAL/OpenALAudioTrack.cs, Ryujinx.Audio/Renderers/SoundIo/SoundIoAudioOut.cs, Ryujinx.Audio/Renderers/SoundIo/SoundIoAudioTrack.cs, Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/Audio/AudioOutManager/IAudioOut.cs
Changes:
- Implement software surround downmixing (fix #796).
- Fix a crash when no audio renderer were created when stopping emulation
- ~~The audio renderer now support output to a 5.1 surround compatible device.~~ => need more testing, removed.
NOTE: This PR also disable support of 5.1 surround on the OpenAL backend as we cannot detect if the hardware directly support it. (the downmixing applied by OpenAL on Windows is terribly slow)
=> Misc audio fixes

Ryujinx.HLE/HOS/Services/Account/Acc/AsyncContext/AsyncExecution.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForApplication.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IAsyncContext.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IManagerForApplication.cs, Ryujinx.HLE/HOS/Services/Account/ResultCode.cs, Ryujinx.HLE/HOS/Services/Nifm/StaticService/IGeneralService.cs
This implement:
- IManagerForApplication::EnsureIdTokenCacheAsync (accordingly to RE) but the Async task is stubbed.
- IAsyncContext interface (accordingly to RE).
- IManagerForApplication::LoadIdTokenCache (checked with RE, and stubbed).
I've tried some games but now they needs some `sfdnsres` calls, some other boots and crashes with other issues.
Maybe we should disable the connection somewhere to lets the game think we are offline. I have done many attempts, without success, but since the code is here now, it's better than nothing.
(I've cleaned up `using` of IGeneralService too)
Closes #629 and closes #630
=> account: Implement IManagerForApplication calls and IAsyncContext

Ryujinx.Graphics.Nvdec.H264/Decoder.cs, Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs, Ryujinx.Graphics.Nvdec.Vp9/Decoder.cs, Ryujinx.Graphics.Nvdec.Vp9/Types/Vp9Common.cs
This fixes some build warnings and debug asserts caused by uninitialized fields on the VP9 decoder.
=> Fix asserts on VP9 decoder in debug mode and build warnings

Ryujinx.Audio.Renderer/Dsp/Command/DownMixSurroundToStereoCommand.cs
This fix front center and lfe being inverted in input of the DownMixSurroundToStereo command.
This fix:
- Voices being missing on FE3H videos.
- Mario Tennis Aces missing background.
- Probably all missing sound issues that anyone could have.
=> Amadeus: Fix inverted downmixing of center and lfe

Ryujinx.Graphics.Gpu/Image/Pool.cs
This fixes a regression introduced in #856 where the pages count would not be calculated properly for the GPU pools, leading to a `ArgumentOutOfRangeException` when `SynchronizeMemory` was called because the array was not large enough to hold all the modified pages.
To my knowledge, the bug is only manifested on deko3d homebrew, I'm not aware of any other application that triggers the bug.
=> Fix off-by-one error in pages count calculation on GPU pool

ARMeilleure/Translation/PTC/Ptc.cs, Ryujinx.Common/Configuration/AppDataManager.cs, Ryujinx.Common/Configuration/ConfigurationState.cs, Ryujinx.Common/Logging/Logger.cs, Ryujinx.HLE/FileSystem/VirtualFileSystem.cs, Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/ModLoader.cs, Ryujinx/Program.cs, Ryujinx/Ui/ApplicationLibrary.cs, Ryujinx/Ui/ControllerWindow.cs, Ryujinx/Ui/DlcWindow.cs, Ryujinx/Ui/GameTableContextMenu.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/Migration.cs, Ryujinx/Ui/TitleUpdateWindow.cs
This is a slightly different but a more generic approach to portable mode.
Ryujinx can now be launched with an extra commandline parameter `-r` or `--root-data-dir` like so-
```
Ryujinx.exe -r <my-data-dir-path>
```
This causes the emulator to use this custom path for the root data directory instead of the usual AppData directory.
Create shortcuts to different data directories for testing/using different configs.
~All host paths in use have been decoupled in the backend. With some GUI work, this will allow even more granularity in the future. (Custom NAND, SDCard, Mod directories).~
~`games`, `profiles`, `system` and `Config.json` are still considered part of the base directory.~
~Needs more work for granular custom directories.~
Support for custom NAND, SDCard directories will be added …
=> Allow launching with custom data directories

ARMeilleure/Instructions/InstEmitMemoryHelper.cs, ARMeilleure/Translation/PTC/Ptc.cs
According to the Intel Optimization Reference Manual, forward conditional branches are predicted to be not taken and backward conditional branches are predicated to be taken, when they are not in the branch target buffer (See section 3.4.1.2 Static Branch Prediction). This PR changes the order of the blocks to take advantage of this.
Before
```asm
.L4:
add rbx,byte -0x30
mov rax,0xffffff8000000007
mov rcx,rbx
and rcx,rax
jz .L7
.L5:
mov rax,WriteUInt64
mov rcx,rbx
mov rdx,r13
call rax
jmp short .L9
.L7:
mov rax,rbx
shr rax,byte 0xc
mov rcx,PAGE_TABLE_0
mov rax,[rcx+rax*8]
test rax,rax
jng .L5
.L8:
mov rcx,rbx
and rcx,0xfff
mov [rax+rcx],r13
.L9:
```
After
```asm
.L4:
add rbx,byte -0x30
mov rax,0xffffff8000000007
mov rcx,rbx
and rcx,rax
jnz .L8
.L5:
mov rax,rbx
shr rax,byte 0xc
mov …
```
=> Improve static branch prediction along fast path for memory accesses

Ryujinx.Graphics.Gpu/Engine/MethodCopyTexture.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs
Closes #1475 
This is a first-time pull request to get acclimated with the project.
Downloaded a code-aligner to undo the spacing changes done by visual studio.
=> Fix: Issue #1475 Texture Compatibility Check methods need to be centralized

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs
Fixes a regression introduced on #1482 that caused height maps to break in SMO after a few steps (and probably affected other games too), the wrong `SizeMatches` overload was being used, compared to the previous code.
=> Fix regression on texture compatibility match checks

Ryujinx.Graphics.Shader/Instructions/InstEmitAlu.cs
It was reading the flags from the wrong bits for the constant buffer + register variant of this instruction.
Fixes dithering pattern on SMO.
Before:
After:
Might also fix issues on other games, of course.
=> Fix PSL and MRG flags on XMAD cbuf-reg shader instruction

ARMeilleure/Decoders/OpCodeSimdMemImm.cs, ARMeilleure/Decoders/OpCodeSimdMemReg.cs, ARMeilleure/Decoders/OpCodeTable.cs, ARMeilleure/Translation/PTC/Ptc.cs
Per the manual:
```
if scale > 4 then UNDEFINED; 
```
This was not being enforced, which lead to a exception later on, during emit stage since the size could be invalid. Now it should produce a "undefined" instruction instead for those invalid cases.
~~PPTC increment is not required, since when the invalid encoding is encountered, it throws a exception later on and no code is generated (before this change).~~ Nevermind that, incremented it since I found another case of undefined encoding that was also not being matched:
```
if option<1> == '0' then UNDEFINED;    // sub-word index
```
This one is also fixed now.
=> SIMD&FP load/store with scale > 4 should be undefined

Ryujinx.HLE/FileSystem/Content/ContentManager.cs, Ryujinx.HLE/FileSystem/SaveHelper.cs, Ryujinx.HLE/FileSystem/VirtualFileSystem.cs, Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/Font/SharedFontManager.cs, Ryujinx.HLE/HOS/ModLoader.cs, Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs, Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/FileSystemProxyHelper.cs, Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IDirectory.cs, Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IFile.cs, Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IFileSystem.cs, Ryujinx.HLE/HOS/Services/Fs/IDeviceOperator.cs, Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs, Ryujinx.HLE/HOS/Services/Fs/IMultiCommitManager.cs, Ryujinx.HLE/HOS/Services/Fs/ISaveDataInfoReader.cs, Ryujinx.HLE/HOS/Services/Mii/MiiDatabaseManager.cs, Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs, Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs, Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZoneContentManager.cs, Ryujinx.HLE/Loaders/Executables/KipExecutable.cs, Ryujinx.HLE/Ryujinx.HLE.csproj, Ryujinx/Ui/ApplicationLibrary.cs, Ryujinx/Ui/DlcWindow.cs, Ryujinx/Ui/GameTableContextMenu.cs, Ryujinx/Ui/SaveImporter.cs, Ryujinx/Ui/TitleUpdateWindow.cs
- Support reading NCA0 files and decrypted NCAs.
- Implement `Kvdb.FlatMapKeyValueStore` and update `SaveDataIndexer` classes to use it. This drastically improves the performance of some save data operations when large numbers of save data exist.
- Change `IFileSystem` interfaces to completely match Nintendo's.
- Add `ReferenceCountedDisposable<T>` to help properly dispose shared objects, and use it when returning an `ISaveDataInfoReader` from `IFileSystemProxy`.
- General system stability improvements to enhance the user's experience.
=> Update to LibHac 0.12.0

Ryujinx.Audio.Renderer/Dsp/Command/DataSourceVersion2Command.cs, Ryujinx.Audio.Renderer/Server/CommandGenerator.cs
This adds a missing offset on the output buffer of the DataSourceVersion2Command.
This fix music only playing on the left channel on Fairy Tail, Family Mysteries: Poisonous Promises, SEGA AGES Sonic the Hedgehog 2, Harukanaru Toki no Naka de７, and probably more.
NOTE: this also add an assert in debug mode to check for the channel index being always 0 for ADPCM. (as this source only support mono)
=> Amadeus: Fix multi-channel PCM sources on REV8

ARMeilleure/Instructions/InstEmitAluHelper.cs, ARMeilleure/Instructions/InstEmitHelper.cs, ARMeilleure/Translation/PTC/Ptc.cs
`RegisterUsage` pass considers `Return` as a `StoreToContext`, so we do not need to emit one before a `Return` instruction. Sample [diff](https://www.diffchecker.com/XlZey6rj).
=> Do not emit StoreToContext before Return

Ryujinx.Cpu/MemoryManager.cs, Ryujinx.Graphics.GAL/IRenderer.cs, Ryujinx.Graphics.GAL/ITexture.cs, Ryujinx.Graphics.GAL/TextureCreateInfo.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Image/AutoDeleteCache.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Image/TextureViewCompatibility.cs, Ryujinx.Graphics.Gpu/Memory/Buffer.cs, Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs, Ryujinx.Graphics.OpenGL/Image/TextureBuffer.cs, Ryujinx.Graphics.OpenGL/Image/TextureStorage.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.OpenGL/ResourceCache.cs, Ryujinx.Graphics.OpenGL/ResourcePool.cs, Ryujinx.HLE/Switch.cs
This PR aims to make texture and buffer memory management better in a few areas, so that we can do things like flush textures without worrying about data corruption, and thus fix a few issues with our AutoDeleteCache having a limited size. The course pictured above generally has the ground incredibly dark, as the course shadow map and lighting cube for the floor are both dropped out of the AutoDeleteCache during loading. No such problem in the screenshot. 😌 
All of these changes are related, which is why they're all part of one PR. There is one change that needs to be here to make this more stable, but more on that later.
1. Overlapping textures that are not  are now removed from the AutoDeleteCache. This gives us a guarantee that no unrelated overlapping textures can flush out of order, …
=> Texture/Buffer Memory Management Improvements

ARMeilleure/CodeGen/RegisterAllocators/HybridAllocator.cs, ARMeilleure/CodeGen/RegisterAllocators/LinearScanAllocator.cs, ARMeilleure/CodeGen/X86/CodeGenerator.cs, ARMeilleure/Diagnostics/IRDumper.cs, ARMeilleure/IntermediateRepresentation/BasicBlock.cs, ARMeilleure/IntermediateRepresentation/Instruction.cs, ARMeilleure/Translation/ControlFlowGraph.cs, ARMeilleure/Translation/EmitterContext.cs, ARMeilleure/Translation/PTC/Ptc.cs, ARMeilleure/Translation/RegisterUsage.cs, ARMeilleure/Translation/Translator.cs
Before `block.Next` had to follow `block.ListNext`, now it does not. `block.Next` and `block.Branch` could also be a bit ambiguous when there was a single successor, now they are not.
Instead `CodeGenerator` will now emit the jump instructions when necessary to ensure control flow. This makes control flow and block order modifications easier (see `ControlFlowGraph.SplitEdge(pred, succ)` & `LinearScanAllocator.FirstSuccessor(bb)` for examples). It also eliminates some simple case of redundant unconditional branches.
```patch
@@ -30,8 +30,6 @@
sub ecx,byte +0x1
mov [rax+0x400],ecx
.L4:
-  jmp short .L5
-.L5:
test rbp,rbp
setl cl
movzx ecx,cl
@@ -46,8 +44,8 @@
```
This PR removes the `Branch` instruction. An alternative approach would be to canonicalize flow by using the `Branch` …
=> Relax block ordering constraints

Ryujinx.HLE/HOS/Services/Hid/Hid.cs
This was tested against HW with https://github.com/Xpl0itR/Input-Test/tree/master/Input-Test and a few changes to record the minimum value axis value when the stick buttons were marked as pressed.
=> Correct the threshold for control stick buttons

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs
This does two change, the first one changes the method used to flip viewport, this should fix a bug that causes the screen to be flipped on some games on GPUs without viewport swizzle support (old NVIDIA GPUs, AMD and Intel). It would flip on the shader when the extension was not supported, but due to the lack of proper shader specialization, this didn't work very well.
The new approach uses `glClipControl` again to flip the viewport, this time also flipping front face to negate the effects of the viewport flipping.
---
The second one changes the method used to detect the depth mode that the game is using. Just checking the depth mode register is not very reliable as a issue similar to the one that could happen with the origin could happen here aswell. Basically, the game changing the …
=> Better viewport flipping and depth mode detection method

ARMeilleure/CodeGen/Optimizations/BlockPlacement.cs, ARMeilleure/CodeGen/X86/CodeGenerator.cs, ARMeilleure/Diagnostics/IRDumper.cs, ARMeilleure/Instructions/InstEmitFlowHelper.cs, ARMeilleure/Instructions/InstEmitMemoryHelper.cs, ARMeilleure/IntermediateRepresentation/BasicBlock.cs, ARMeilleure/IntermediateRepresentation/BasicBlockFrequency.cs, ARMeilleure/Translation/ControlFlowGraph.cs, ARMeilleure/Translation/EmitterContext.cs, ARMeilleure/Translation/PTC/Ptc.cs, ARMeilleure/Translation/Translator.cs
Implement a simple pass which re-orders cold blocks at the end of the list of blocks in the CFG. Sample [diff](https://www.diffchecker.com/tPgkKPTd).
This removes some branching along the fast path for memory accesses and moves `CheckSynchronization` away from loops. It is not clear if we should attempt to re-order the decoded stuff, since presumably the guest compiler should already have placed it in an "optimal" order.
=> Implement block placement

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
This stub:
- IApplicationFunctions BeginBlockingHomeButtonShortAndLongPressed
- IApplicationFunctions EndBlockingHomeButtonShortAndLongPressed
- IApplicationFunctions BeginBlockingHomeButton
- IApplicationFunctions EndBlockingHomeButton
All checked by RE.
It's needed by ARMS to goes in game.
=> am: Stub Begin/EndBlockingHomeButton

Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForApplication.cs, Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
This implement/stub:
- IAccountServiceForApplication ListOpenContextStoredUsers
- IAccountServiceForApplication ListQualifiedUsers
- IHidServer SetTouchScreenConfiguration
All checked by RE.
Closes #1306, Closes #1267 
Make some games goes ingame:
=> acc/hid: Implement ListQualifiedUsers and SetTouchScreenConfiguration

Ryujinx.Graphics.Shader/Translation/EmitterContext.cs
This fixes a issue I observed on Turok 2 where the color components were written to the wrong render target components. Aligning the register index to 4 (the number of components/RGBA) fixes the issue.
Tested with #1558:
Before:
After:
=> Align register index between output targets on pixel shaders

Ryujinx.Graphics.Gpu/Image/Texture.cs
There's a problem with some games, including `Hatsune Miku: Project DIVA Mega Mix`, where they use a texture after it has been removed as a view. In this state, `viewStorage` should be the texture itself, but it was being set as null. A method for propagating the modified flag used in `SignalModified` requires that this is not null, so it only became a problem after it was added with the texture management PR.
Obviously I don't have this game, so I'll be waiting for testing from someone else to ensure it's fixed. Game issue: https://github.com/Ryujinx/Ryujinx-Games-List/issues/237
=> Texture: Make viewStorage still valid after view removal.

Ryujinx.HLE/HOS/Services/Audio/AudioRendererManagerServer.cs
```
Amadeus brings his own strings
```
Run `audren` services in a separate thread to remove audio stutter when unrelated services calls are spammed.
This stutter is due to reuse of `CommonServer` for `audren` after IPC refactor part 1 #1447 
I take no credit for this fix.
=> Run audren services in a separate thread

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs, Ryujinx.HLE/HOS/UserChannelPersistence.cs
Now when no data is available, it returns NotAvailable like the other `Pop` functions. Fixes crashing regressions caused by https://github.com/Ryujinx/Ryujinx/pull/1560 .
Examples of games that call this when no data is present: Splatoon, Super Kirby Clash
=> Return "NotAvailable" when no UserChannel data is present.

Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs, Ryujinx.HLE/HOS/Services/Time/IStaticServiceForGlue.cs, Ryujinx.HLE/HOS/Services/Vi/IApplicationRootService.cs, Ryujinx.HLE/HOS/Services/Vi/IManagerRootService.cs, Ryujinx.HLE/HOS/Services/Vi/ISystemRootService.cs, Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
This PR isolates the more active services to their own threads.
The ones added here are Surfaceflinger family, HID and Time Services.
I wouldn't be surprised if these services are on separate threads in the native sysmodules as well.
Expands on #1572
=> Isolate more services to separate threads

Ryujinx.Graphics.Gpu/Image/TextureManager.cs
This should fix a regression in games that used OpenGL on the guest, where texture copies would fail and cause a single strip of the image to be repeated.
A rule was introduced in https://github.com/Ryujinx/Ryujinx/pull/1408 to skip setting a texture's data if it was a render target, and it had some other overlapping, non-cpu-modified texture in its place. This is because the overlap implies that the data present in memory is part of an incompatible texture, and would just be garbage if read in (and will be overwritten by an imminent clear or draw).
However, this logic was triggering for textures found for MethodCopyTexture, for both the source _and_ destination. Obviously we want the source to prefer data from memory, as copying blank data is useless. Additionally, a copy may be to a …
=> Always set new texture data for textures initialized by a copy.

Ryujinx.HLE/HOS/Applets/AppletManager.cs, Ryujinx.HLE/HOS/Applets/Error/ErrorApplet.cs, Ryujinx.HLE/HOS/Applets/Error/ErrorCommonArg.cs, Ryujinx.HLE/HOS/Applets/Error/ErrorCommonHeader.cs, Ryujinx.HLE/HOS/Applets/Error/ErrorType.cs, Ryujinx.HLE/IHostUiHandler.cs, Ryujinx/Ui/ErrorAppletDialog.cs, Ryujinx/Ui/GtkHostUiHandler.cs
This implement a basic Error Applet using the GUI and the firmware archive.
It's needed for `ldn` as we throw some error code and it's probably called by some games if an error occurs.
- Fix REKT (https://github.com/Ryujinx/Ryujinx-Games-List/issues/2038) who call the error applet at the end of a level due to the lack of online impl (to send the highscore on servers).
- Fix Ghost Blade HD (https://github.com/Ryujinx/Ryujinx-Games-List/issues/1625) who is playable now. It calls the applet to say there is no internet connection.
=> applet: Basic implementation of Error Applet

Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs
Some games render to 1D textures. For the GPU, there's no difference between a 1D texture and a 2D texture with a height of 1, when it is being rendered. For this reason we can't determine if the texture is 1D or 2D when it is used as render target or copy texture. That means that if a game renders to a 2D texture, and later tries to sample it as a 1D texture, it will read garbage as 2D and 1D targets are not considered compatible (the host API does not allow that).
To fix this issue I just converted all 1D textures to 2D textures with a height of 1. The generated shader code was also adjusted to expect 2D textures instead of 1D ones. I added a constant that controls whenever it does that for the shader or not, later the constant can be replaced by a flag somewhere to make the behavior …
=> Convert 1D texture targets to 2D

ARMeilleure/Optimizations.cs, ARMeilleure/Translation/RegisterUsage.cs, ARMeilleure/Translation/Translator.cs
This is an optimization from the old CPU that could eliminate context save of several CPU register by assuming that the function follows the ARM64 ABI. Registers that are caller saved does not need to be saved to the context as the expectation is that the  callee will not use them, and instead just overwrite their values. This optimization has been inactive since the new JIT was implemented (`isCompleteFunction` is always false, so it can never kick in).
Other than the fact that it is unused, I also don't think it's worth re-implementing that as it's a rather dangerous optimizations (as it make assumptions about the code) and the benefits are not even that large anyway.
This should not change anything, it's just removing unused code.
=> Remove old, unused CPU optimization

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
Decoding 2D array ASTC texture was not supported, which means that layers other than the base layer would be completely blank. This adds support for decompression for 2D array textures aswell.
Fixes missing textures in Donkey Kong Country Tropical Freeze.
Before:
After:
=> Support 2D array ASTC compressed texture formats decoding

Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, Ryujinx.Graphics.Shader/Decoders/Decoder.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs
Currently we use a heuristic to find indirect branch targets on shader code. This heuristic was failing to find targets if they were located after a "EXIT" instruction. That was happening because "EXIT" was one of the stop conditions that would make it stop looking. This changes the stop condition to instead stop if the memory is unmapped or if the opcode value is 0 (this disassembles as NOP, but I assume that it's a invalid instruction. It's also what seems to be in the memory after the end of the shader, but I'm not sure if that's 100% reliable).
Maybe theres a better way to solve the problem, I'm not a big fan of this solution to be honest...
This fixes a issue with:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2538
And the game now renders:
Might affect other games aswell, of …
=> Improve BRX target detection heuristics

Ryujinx.HLE/HOS/UserChannelPersistence.cs, Ryujinx/Ui/MainWindow.cs
This fix a bug introduced in #1560 that would cause "Stop emulation" to actually restart the game all the time if it was restarted on another program.
=> Fix exiting emulator with multi programs

Ryujinx.HLE/HOS/Services/SurfaceFlinger/BufferQueueCore.cs
This fix a mistake I made during my original reimplementation of Surface Flinger by disabling async buffer.
This fix a memory corruption on Super Mario All-Stars 3D (Super Mario Sunshine & Super
Mario Galaxy now go ingame).
This also could fix some crashes on other games.
Thanks to @gdkchan for tracing the memory corruption.
=> surfaceflinger: Disable async buffer

Ryujinx.Graphics.Nvdec.H264/Decoder.cs, Ryujinx.Graphics.Nvdec.H264/Surface.cs
Currently, NVDEC uses the size of the surface returned by FFMPEG when writing data back to memory. The problem is that this size is not always correct, afterall FFMPEG does not know when a video ends and another begins. Using the wrong frame size will cause memory corruption, as it will overwrite unrelated data in memory.
I fixed that by forcing the re-creation of the FFMPEG context when the frame size changes. After doing that, FFMPEG is returning the correct frame sizes for the subsequent videos (according to my tests).
This fixes a memory corruption that could occur after switching between different H264 videos with different frame sizes. This fixes random crashes on Super Mario 3D All-Stars main menu/launcher.
=> Fix H264 output frame size when decoding videos of different sizes

Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/CodeGenContext.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/GlslGenerator.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/Decoders/CbIndexMode.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeLdc.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitMemory.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgramInfo.cs
The LDC shader instructions has different indexing modes, and one of them allows selecting from which constant buffer the value will be loaded by using a bitfield from a register. This mode was not supported, and it was assuming that the constant buffer slot number was always constant. This change allows it to be indexed.
Indexing of constant buffers is supported by creating a array of uniform buffers on the shader with all the constant buffers, instead of separating them. This is only done when the special LDC indexing modes are actually used on the shader, so the code should remain the same on shaders that do not make use of it.
This fixes skinned meshes not rendering on Super Mario 3D All-Stars.
Before:
After:
Before:
After:
=> Add support for shader constant buffer slot indexing

Ryujinx.Graphics.Shader/Decoders/OpCodeTable.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitAlu.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitAluHelper.cs
Implements the LEA.HI shader instruction.
This fixes Rosalina rendering on Super Mario Galaxy.
Before:
After:
=> Implement LEA.HI shader instruction

Ryujinx.Graphics.OpenGL/Framebuffer.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs
Dual source blend is a feature that allows two color outputs from the pixel shader to be combined using the GPU blending functions. When one of the dual source blending sources is used, it is only valid to have a single draw buffer set, as on this mode you can only output to a single color buffer. So, this change forces a single draw buffer to be set if dual source blending is in use.
This adds a bunch of checks to the set blend mode function which could potentially slow it down, so if someone has a better suggestion on how to do it without all the checks on a potentially how function, let me know.
This fixes black floor among other things on Super Mario Galaxy observatory.
Before:
After:
=> Fix error when dual source blend is used

Ryujinx.Graphics.Shader/Translation/EmitterContext.cs
This fixes an error I noticed on one of Super Mario Galaxy shaders. When the shader does not output to all the components of a color buffer, the register number still corresponds to the component number. So if, for example, only A (alpha) is written to, the output will be still on R3 rather than R0.
I'm not sure about what exactly this fixes on this game, but mario shadow seems better with this fix. I also tested on other games that had similar issues on the past, and they did not regress.
=> Fix output component register on pixel shaders

Ryujinx.Graphics.GAL/BlendOp.cs, Ryujinx.Graphics.OpenGL/EnumConversion.cs
Fixes the broken shadows on Super Mario Galaxy. Thanks for riperiperi for the help diagnosing this issue.
Before:
After:
Note: This only affects games using the OpenGL and Vulkan APIs.
=> Fix incorrect GPU GL blend func values

Ryujinx.HLE/PerformanceStatistics.cs, Ryujinx/Ui/GLRenderer.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade, Ryujinx/Ui/StatusUpdatedEventArgs.cs
Host FPS is rather confusing for users as they can easily confuse it with Game FPS, thinking that it represents how many frames the game is putting out. However, it is a useful metric for determining if it's our GPU emulation causing the framerate bottleneck, as the host has time to generate more duplicate frames while waiting for more commands. It is also useful to see in screenshots, as it can indicate games with GPU related framerate issues.
This PR introduces a replacement "Fifo %" which indicates the percentage of time spent executing processing the FIFO queue over a period of time. This is essentially how _saturated_ the graphics processing thread is. A new mechanism for measuring percentage time has been added to the PerformanceStatistics class.
It's calculated by getting the …
=> Replace Host FPS with GPU command queue load ("Fifo %")

Ryujinx.Graphics.Shader/Decoders/OpCodeTable.cs
Improves rendering on Doom 64.
Before:
After:
=> Fix LOP3 (cbuf) shader instruction encoding

Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/Translation/AttributeConsts.cs
This could cause geometry shaders to fail to compile if those built-ins were used. I'm not aware of any game having a visible improvement with those changes however.
=> Fix gl_in being used with built-in variables that are not per-vertex

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs
This was causing OpenGL errors in UE4 games, and a driver crash on NVIDIA Pascal GPUs (GeForce 1070 etc). With this fixed, you can now get ingame on UE4 games with a Pascal GPU. (does not appear to fix any other issues)
=> Ensure storage is set for Buffer Textures when binding an Image.

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.Gpu/Engine/Compute.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Engine/ShaderTexture.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingInfo.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, Ryujinx.Graphics.OpenGL/FormatTable.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/StructuredIr/AstTextureOperation.cs, Ryujinx.Graphics.Shader/TextureDescriptor.cs
This fixes a number of related things. First, the `EXT_shader_image_load_store` extension states:
```
If the format layout qualifier is present, 
then the format must match the format of the associated image unit, as 
enumerated in table 8.33, otherwise the access is considered to involve a 
format mismatch
```
In fact the format that was specified on the shader was being ignored, and it was using the format of the image binding instead. So I changed it to use the same format declared on the shader for the image binding aswell, this fixes the mismatch and makes the load/store behave as expected.
The second issue is that there are basically two modes on the SULD/SUST (image load/store) shader instructions. One of them is sized, so it just read/writes a 8/16/32/64/128-bits value in memory …
=> Fix image binding format

Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs
The coords were read from the wrong register for array image load/store.
This fixes the "screen too dark" in Yomi wo Saku Hana.
Before:
After:
Fixes #1635.
=> Fix shader image load/store array index register

Ryujinx.Graphics.GAL/BufferRange.cs, Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, Ryujinx.Graphics.OpenGL/Buffer.cs, Ryujinx.Graphics.OpenGL/Constants.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Program.cs
The NVIDIA driver is returning an error if an attempt is made to resume transform feedback after changing the shader program. I couldn't find anything on the spec that forbids that, it just says:
> An INVALID_OPERATION error is generated by UseProgram if the current transform feedback object is active and not paused;
`glBindBufferRange` with the target set to transform feedback was also returning an error, which also seems to be caused by a transform feedback being currently active. So as a solution for both errors, it now ends and restarts the feedback instead of pausing and resuming it.
The last issue is that having transform feedback buffers used for anything else while the transform feedback is active is not valid and will cause the draw to fail. This is what blocked #1607. This is …
=> Fix transform feedback errors caused by host pause/resume and multiple uses

Ryujinx.Graphics.OpenGL/VertexArray.cs
This is supposed to prevent draws with invalid states (which can cause driver crashes). I forgot to update the checks on #1226.
=> Fix vertex buffer handle null check

Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/SamplerType.cs
The shader decompiler currently tries to find the source of the handles for bindless texture accesses. If it's a constant buffer, it turns it into a regular texture access, and instructs the GPU emulator to read the handle from the respective constant buffer, and bind it properly. If said analysis fails however, it will create a sampler for a handle at constant buffer 0 at offset 0 (those values comes from the fact that the values are not changed from their defaults).
Anyway, the problem is that when the analysis fails for multiple texture accesses, it's possible that multiple texture sampling operations with different sampler types will share the sampler/name. This is invalid and causes the shader compilation to fail. This adds the sampler type to the name of the sampler itself to …
=> Avoid sampler conflicts on bindless samplers with the same name

Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs
Texture2DArray can be scaled without issue, so allow TexelFetch to apply for it.
- Scales x and y, does not scale layer.
- Does not allow Texture3D, Texture1D arrays to be scaled.
Fixes Res Scale in HW:AoC demo:
https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=0d23fa36-1952-11eb-83c8-ebb5d6f907df
=> Add scaling for Texture2DArray when using TexelFetch.

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.OpenGL/Image/TextureBase.cs, Ryujinx.Graphics.OpenGL/Image/TextureCopy.cs, Ryujinx.Graphics.OpenGL/Image/TextureCopyUnscaled.cs, Ryujinx.Graphics.OpenGL/Image/TextureStorage.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs
This scales the texture size before sending it to the OpenGL backend. The advantage of doing that is that it's not necessary to scale it on the several places the sizes are used for something on the backend. Right now there was a bug where it would use the unscaled size to calculate the size of the temporary buffer used for BGRA swap PBO copies, which means that resolution scaling wouldn't work on games presenting BGRA textures, like Dragon Marked for Death for example. This PR fixes this issue.
=> Scale texture resolution before sending to backend

Ryujinx/Updater/UpdateDialog.cs
Command line arguments are not preserved by the updater, and this causes an issue when the updater restarts Ryujinx in portable mode as it will create/use/modify its default directory instead.
This simple pull addresses the first part of #1594 
As far as the second part of the issue, where the updater perhaps overzealously deletes everything but log files and leaving a graveyard of empty folders, which causes problems in portable installs with a Ryujinx\user subfolder or something else the user places inside the Ryujinx folder is unexpectedly deleted, the idea of doing what fuller installers do comes to mind.
Perhaps an UpdateList.txt containing a list of files that the updater deletes is included in the ryujinx.zip/tar.gz/etc and placed in the unpacked directory for the updater to use …
=> Preserve command line arguments when updater restarts Ryujinx

Ryujinx.Graphics.Gpu/Image/Pool.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TexturePoolCache.cs
This is now unused (I think it was unused for a long time actually, I remember introducing them at one point, but in the end I did not use it, and after range tracking, I don't think it will be necessary), so we can remove it. Or, we can keep it too if anyone thinks it could be useful in the future...
=> Remove unused texture and sampler pool invalidation code

Ryujinx.Graphics.OpenGL/Image/TextureCopyUnscaled.cs
Current code was a no-op, if the format is not a compressed format, block width and height will be 1, it should multiply by the compressed format block size. I'm not aware of any specific game or graphical glitch that this fixes (probably none as I don't think it even does compressed -> uncompressed copies right now), but I noticed this long ago and figured it was probably worth to get it fixed anyway.
=> Fix compressed to non-compressed texture copy size

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/CodeGenContext.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs, Ryujinx.Graphics.Shader/TextureDescriptor.cs, Ryujinx.Graphics.Shader/TextureUsageFlags.cs
Resolution scaling is now possible for bound images using SULD, and using SUST will force a blacklist. Additionally, scale calculation logic for texture/images has been moved out of the backend into the GPU, as it should be backend agnostic.
When res scaled:
- Fixes normal-map decals in Xenoblade Chronicles: DE.
- Should cause Paper Mario and Dead or Alive to force to 1x resolution instead of just breaking.
- May fix some other weird issues.
Before (2x):
After (2x):
Should have no effect when res scale is disabled. May do less work when res scale is not needed in the shader, as a result of some restructuring.
=> Support res scale on images, correctly blacklist for SUST, move logic out of backend.

Ryujinx.Graphics.GAL/SamplerCreateInfo.cs, Ryujinx.Graphics.Gpu/Image/Sampler.cs, Ryujinx.Graphics.Gpu/Image/SamplerDescriptor.cs, Ryujinx.Graphics.OpenGL/HwCapabilities.cs, Ryujinx.Graphics.OpenGL/Image/Sampler.cs
Adds the seamless cubemap flag for samplers, which allows linear blending over cubemap edges. This removes hard edges from cubemaps, and specifically improves really low res cubemaps (used for glossy surfaces).
As seen on nouveau, and supposedly set on every texture by NVN.
https://github.com/envytools/envytools/blob/master/rnndb/graph/g80_texture.xml#L389
There is also a global setting for this, but since the per-texture one is set by NVN I just used that instead. Other guest apis may expect the global setting, which should be added separately.
Before:
After:
(this does not fix missing cubemaps in mario kart 8)
=> Add seamless cubemap flag in sampler parameters.

ARMeilleure/CodeGen/RegisterAllocators/LiveInterval.cs
Before when splitting intervals, the end of the range would be included in the split check, this can produce empty ranges in the child split.
This in turn can affect spilling decisions since the child split will have a different start position. This empty range will cause the interval get a register earlier than needed and move to the active set for a brief moment.
For example:
```
A = [153, 172[; [1899, 1916[; [1991, 2010[; [2397, 2414[; ...
Split(A, 1916)
A.0 = [153, 172[; [1899, 1916[
A.1 = [1916, 1916[; [1991, 2010[; [2397, 2414[; ...
```
Not sure if this caused spooky stuff to happen.
=> Fix LiveInterval.Split

Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs
This should fix a random crash in Hyrule Warriors, and potentially other games that use buffer textures. This crashed before as we don't support copying buffer textures.
Buffer textures don't need to do any size change tricks (they're 1D), and their data should be inherited simply by using the same buffer storage.
=> Do not match aligned sizes for buffer texture targets.

Ryujinx.Graphics.Shader/CodeGen/Glsl/NumberFormatter.cs
While encoding a float64 on a immediate is not possible on the guest shaders, there are some cases were constants are used with those double precision values, for example, for saturate it uses the constants 0 and 1 with the clamp function. Before trying to use those constants with a float64 type would throw, now it properly inserts the constant on the generated code. The constant is encoded as float32 for the following reasons:
- The IR has no support for 64-bit contants (float or integer).
- Guest shaders do not support 64-bit immediates as mentioned before, for those cases it needs to load from constant buffer.
- A float32 is enough to encode all constants used without any loss of precision.
While the issue did show up on a few UE4 games, they were caused by corrupted/garbage shaders, …
=> Support single precision contants for double precision operations

Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoDevice.cs
When certain games are running slowly (or at all), they submit commands to the queue while we are still executing commands from a previous submission. This can lead to the event for commands being present being set, but there being no commands on the queue. 
This PR adds an additional check to make sure commands are in the queue before continuing.
- Fixes Fifo% reading in a few games. (capped at 50% sometimes)
(this might indicate a larger problem where we are consuming 2 frames at once without presenting both)
=> Only report that GPU commands are available when the queue is not empty.

Ryujinx.Graphics.Gpu/Engine/MethodClear.cs
This fixes shadows sometimes not clearing in Xenoblade 2, as they are usually cleared immediately after a series of commands with Rasterizer Discard enabled.
=> Synchronize Rasterizer State before Clear

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.GAL/IRenderer.cs, Ryujinx.Graphics.Gpu/Engine/Compute.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingInfo.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Memory/BufferBounds.cs, Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Program.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.OpenGL/Shader.cs, Ryujinx.Graphics.Shader/BufferDescriptor.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/TextureDescriptor.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, Ryujinx.Graphics.Shader/Translation/TranslationCounts.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
This change uses explicit binding points on the shader code, rather than calling the OpenGL `glGet*Location` functions with the texture/image/buffer name and assigning a binding point on the backend. The main advantage here is making the backend cleaner and more flexible.
Advantages:
- Code is simpler/smaller.
- Binding should be a little bit faster, as it no longer needs to get the binding point from index/stage, the binding point is passed directly. A few other things were optimized aswell (for example, it passes all buffers to be bound at once instead of one at a time).
Other changes:
- Buffers are properly unbound instead of just keeping the last binding.
I recommend testing on a few games just to be sure nothing regressed.
=> Use explicit buffer and texture bindings on shaders

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/ISystemAppletProxy.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs, Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/IApplicationProxy.cs, Ryujinx.HLE/HOS/Services/Apm/IManager.cs, Ryujinx.HLE/HOS/Services/Apm/ISession.cs, Ryujinx.HLE/HOS/Services/Apm/ISystemManager.cs, Ryujinx.HLE/HOS/Services/Apm/ManagerServer.cs, Ryujinx.HLE/HOS/Services/Apm/PerformanceState.cs, Ryujinx.HLE/HOS/Services/Apm/ResultCode.cs, Ryujinx.HLE/HOS/Services/Apm/SessionServer.cs, Ryujinx.HLE/HOS/Services/Apm/SystemManagerServer.cs, Ryujinx.HLE/HOS/Services/Apm/Types/CpuBoostMode.cs, Ryujinx.HLE/HOS/Services/Apm/Types/PerformanceConfiguration.cs, Ryujinx.HLE/HOS/Services/Apm/Types/PerformanceMode.cs
This PR implement some IPC calls of apm service:
- `nn::apm::IManager` is fully implemented.
- `nn::apm::ISession` is fully implemented (close #1633).
- `nn::apm::ISystemManager` is partially implemented.
`nn::appletAE::ICommonStateGetter` have some calls which are just a layer of apm IPC calls. What we currently do in some calls is wrong, it's fixed now!
Everything is checked with RE.
=> apm/am: Refactoring/Unstub services

Ryujinx.Graphics.Gpu/Engine/Compute.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingInfo.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/CodeGenContext.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/TextureOperation.cs, Ryujinx.Graphics.Shader/StructuredIr/AstTextureOperation.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, Ryujinx.Graphics.Shader/TextureDescriptor.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs, Ryujinx.Graphics.Shader/Translation/Rewriter.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs, Ryujinx.Graphics.Texture/BCnDecoder.cs
Currently the shader decompiler has a pass to turn bindless texture accesses into regular texture accesses. This is necessary because emulating bindless texture access on the host is complicated, and we can't just access an arbitrary texture from a guest handle easily.
Currently the information about bindless textures is stored on the texture descriptor. It includes 3 fields just for bindless related information: `IsBindless` indicating if the texture is used on a bindless access, `CbufSlot` with the slot of the constant buffer where the handle is located, and `CbufOffset` with the offset on the constant buffer. There is also a `Handle` field that has the offset of the handle on the "texture constant buffer" for regular texture accesses.
This change removes 2 of those fields:
- …
=> Simplify logic for bindless texture handling

Ryujinx.Graphics.Shader/Decoders/AtomicOp.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeAtom.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeTable.cs, Ryujinx.Graphics.Shader/Decoders/ReductionType.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitMemory.cs
This implements the ATOM shader instruction, and fixes negative offsets on the ATOMS shader instructions (the offset was not being sign-extended).
The ATOM instruction is similar to ATOMS, but operates on global memory. It can be used to do atomic operations on memory, such as GLSL `atomicAdd` and friends.
I know a bunch of games that uses this (Fire Emblem Three Houses is one of them), but I don't know any specific issue that this change fixes.
Note: The compare and swap variant is still not implemented, but it also doesn't seems to be implemented for the other atomic instructions.
=> Implement ATOM shader instruction

Ryujinx.Graphics.Gpu/Engine/MethodCopyTexture.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs
Data can be lost if the last sampled size for a texture is smaller than the region it wants to render to, due to the texture being changed to the smaller size. This manifests in games with dynamic resolution as garbage at the bottom right edge, cropping, the image shifting every frame etc. It can also cause data to be lost when copying between textures. This PR attempts to solve this issue by passing in usage hints that indicate the minimum size that the requester would _prefer_, and increase the size to meet it when possible.
Size Hints currently come from two places:
- Textures used as color or depth targets use Viewport 0's dimensions.
- Source and destination textures for copies use the copy region.
- Source is included because generally the texture needs to be synchronized before …
=> Size hints for copy regions and viewport dimensions to avoid data loss

Ryujinx.Cpu/MemoryManager.cs, Ryujinx.Memory.Tests/MockVirtualMemoryManager.cs, Ryujinx.Memory/Tracking/IVirtualMemoryManager.cs, Ryujinx.Memory/Tracking/MemoryTracking.cs, Ryujinx.Memory/Tracking/RegionHandle.cs
Some games uses ranges that are partially unmapped for buffers (I don't know if this is normal or a bug to be honest). This change makes it not report unmapped regions as dirty, as attempting to read from those regions will throw. This fixes a regression in Higurashi no Naku Koro ni Hou after range tracking.
=> Do not report unmapped pages as dirty

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/Switch.cs
Performance mode was stuck on "default", which caused SMO to always run as if it were in handheld mode. This fixes the system init and docked mode switch to also update the performance mode.
=> Fix: Update performance mode when docked mode changes.

Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/State/MethodOffset.cs, Ryujinx.Graphics.Gpu/State/ScreenScissorState.cs
"Screen scissor" is the minimum size of all render targets, and is set when any render target is bound on NVN or OpenGL. Since it works on all render texture's _real_ sizes, it is therefore more reliable than viewport 0's width, and is actually set before clear.
This fixes a regression with Hyrule Warriors: Age Of Calamity's cubemaps, which did not set viewport dimensions before clear, so the hint was inaccurate. This resulted in attempting to create a cubemap with rectangular sides (16x8), which is logically and physically impossible. (also it just fails)
A better solution for size rules regarding cubemap views will likely be done later.
=> Use "Screen Scissor" as size hint for render targets

Ryujinx.HLE/Loaders/Mods/IPSwitchPatcher.cs
Just a quick change to `@enabled` functionality in pchtxt. Previous behavior considered `@enabled` and `@disabled` as state flags, but apparently that's not the case.
```
| Before   | Now
@enabled              |          |
00ABCD0 1F2003D5      | enabled  | enabled
// comment            |          |
00ABCD4 1F2003D5      | enabled  | enabled
|          | 
00ABCD8 1F2003D5      | enabled  | disabled
|          | 
@disabled             |          | 
00ABCDC 1F2003D5      | disabled | disabled
```
Simply put, you now have to add `@enabled` to every block of patches explicitly.
For extensive changes, it's probably best to rewrite to the new spec. I can't right now, if anyone wants to, feel free.
=> IPSwitch: Quick fix to patch sets toggling

Ryujinx/Ui/SettingsWindow.glade
Updates the "Check for updates on launch" to read instead "Check for Updates on Launch" to be consistent with camel-case options elsewhere in the UI. This time done with manual editing instead of with the Glade app.
=> Standardize to camel-case: option to check for updates on launch

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs, Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs, Ryujinx.HLE/HOS/Services/Lbl/ILblController.cs, Ryujinx.HLE/HOS/Services/Lbl/LblControllerServer.cs, Ryujinx.HLE/HOS/Services/Pctl/ParentalControlServiceFactory/IParentalControlService.cs, Ryujinx.HLE/HOS/Services/Pctl/ResultCode.cs
This PR enable VR rendering on games which support it through the Toy-Con VR Goggles.
Please remember Ryujinx currently don't support console SixAxis sensor and for now, in some games, the view can't be moved.
Some games can enable VR only in Handled mode, BotW can enable it in Docked too.
Everything is implemented accordingly to RE:
- am: ICommonStateGetter: SetVrModeEnabled, BeginVrModeEx, EndVrModeEx (Closes #1605).
- lbl: ILblController: SetBrightnessReflectionDelayLevel, GetBrightnessReflectionDelayLevel, SetCurrentAmbientLightSensorMapping, GetCurrentAmbientLightSensorMapping, SetCurrentBrightnessSettingForVrMode, GetCurrentBrightnessSettingForVrMode, EnableVrMode, DisableVrMode, IsVrModeEnabled.
- pctl: IParentalControlService: ConfirmStereoVisionPermission, …
=> am/lbl/hid/pctl: Enabled VR Rendering

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs
This PR fix an issue I've made in #1688 which is enabled VR as default.
It could cause rendering issues in games when VR mode isn't used, as users have reported in Smash (where VR rendering don't seems to works fine anyway).
Before
After
=> am: Fix VR enabled by default

Ryujinx.Graphics.Gpu/Engine/MethodCopyTexture.cs
Fix a regression introduced on #1647 where the wrong format would be propagated to the destination texture. Should fix performance regression on Zelda Links Awakening.
=> Propagate zeta format properly

Ryujinx.Graphics.Gpu/Image/ITextureDescriptor.cs, Ryujinx.Graphics.Gpu/Image/TextureDescriptor.cs, Ryujinx.Graphics.Gpu/Image/TextureTarget.cs, Ryujinx.Graphics.Gpu/Shader/Cache/CacheManager.cs, Ryujinx.Graphics.Gpu/Shader/Cache/Definition/GuestTextureDescriptor.cs, Ryujinx.Graphics.Gpu/Shader/CachedGpuAccessor.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Gpu/Shader/TextureDescriptorCapableGpuAccessor.cs
This fix an issue causing the virtual address of texture descriptors to
not be cleaned up when caching and instead cleaning texture format and swizzle.
This should fix duplicate high duplication in the cache for certain
games and possible texture corruption issues.
**THIS WILL INVALIDATE ALL SHADER CACHE LEVELS CONSIDERING THE NATURE OF THE ISSUE**
=> shader cache: Fix invalid virtual address clean up

Ryujinx.Graphics.Gpu/Shader/Cache/CacheCollection.cs, Ryujinx.Graphics.Gpu/Shader/Cache/CacheManager.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs
This fix a misplace function call ending up causing possibly two write
on the cache.info at the same time.
=> shader cache: Fix possible race causing crashes on manifest at startup

README.md
Updates the readme.md file for clarity on which version of .NET 5 to download, and changes the build command to be a working one with .NET 5.
=> Specify the X64 version of .NET 5, and change the build command

Ryujinx.HLE/Loaders/Executables/NsoExecutable.cs
This fix possible parsing errors of informations on some NSO where the "zero" field value isn't 0, introduced by #1661 leading to crashes at start.
References:
https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/creport/source/creport_modules.cpp#L202
https://github.com/Thog/oss-rtld/blob/master/source/main.cpp#L14
=> loaders: Fix possible parsing errors of informations on some NSO

Ryujinx.Graphics.Gpu/Image/Texture.cs
Layout conversion shouldn't be performed on buffer textures because they are effectively just buffers that are accessed as a texture. Attempting to do those conversions could cause memory corruption as the parameters passed to the conversion functions are most invalid (GOB block sizes etc are all supposed to be ignored on buffer textures).
I'm not aware of any specific issue that this fixes, but this might fix memory corruption on UE4 games (that tends to use buffer textures quite frequently).
=> Do not perform layout conversion on buffer texture flushes

Ryujinx/Ui/GLRenderer.cs
Made it so you can change between handheld and docked mode with a keybinding, which is set to F9 for now
=> GLRenderer: Change between docked and handheld mode using a keybinding

Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade
This PR just add a way to toggle the docked and the handheld mode by clicking the label in the status bar.
Nothing more.
EDIT: Due to some recommandations, I've added the same behavior for the VSync setting, even if we don't recommand to change it when everything works fine.
=> gui: Toggle Docked/Handheld mode and VSync by clicking status bar

Ryujinx.Common/Logging/LogClass.cs, Ryujinx.HLE/HOS/Services/Olsc/IOlscServiceForApplication.cs, Ryujinx.HLE/HOS/Services/Olsc/ResultCode.cs
This PR fix an issue of missing service `olsc:u` added in firmware 10.0.
ACNH 1.6.0 update needs it and some other service calls:
- Initialize
- SetSaveDataBackupSettingEnabled
Both are stubbed since we will not support online savedata backup. 
Checked with RE to return the right result.
ACNH can still be playable now:
=> olsc: Add service olsc:u and stub some calls

ARMeilleure/Translation/PTC/Ptc.cs, ARMeilleure/Translation/PTC/PtcProfiler.cs
We have some nice checks for PTC to make sure the data is valid before we load and use it, and a backup to try in case it isn't.
Unfortunately, none of that is used right now because most of the time it throws attempting to decompress an incomplete stream.
This PR catches decompression errors and treats it as a loading failure, which lets it fall back to the backup instead of crashing. The change has been made for both the cache and the info.
=> Use backup when PTC compression is corrupt

Ryujinx.Graphics.GAL/Extents2D.cs, Ryujinx.Graphics.Gpu/Engine/MethodCopyTexture.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.OpenGL/Image/TextureCopy.cs
Will result in more scaled copy destinations, but allows scaling in some games that copy textures to the output framebuffer.
Also, textures with more than one level are no longer blacklisted. This has been changed to more than 3 levels. (indicates a game texture)
- Res scaling now works in Link’s Awakening (causes shadow acne tho)
- Res scaling no longer blacklists in some cutscenes in Super Mario Odyssey.
Needs further testing, so Draft for now.
=> Allow copy destination to have a different scale from source

Ryujinx.HLE/HOS/Services/Audio/IAudioInManager.cs
This PR fix a wrong id for call `ListAudioInsAuto` in `IAudioInManager`.
=> audin: fix wrong id ListAudioInsAuto call

Ryujinx.Audio.Renderer/Dsp/Effect/DelayLine.cs
This fix an underflow in the setup of delay time in the delay effect.
This fix a regression caused by Amadeus on Shovel Knight: Treasure Trove.
=> amadeus: Fix possible underflow in delay time parameter in delay effect

Ryujinx.Audio.Renderer/Dsp/Command/Reverb3dCommand.cs
This fix reverb 3d mono rendering that was using -1 instead of 1 for delay line
offset.
I also did some clean up as this value is now used by all channels
variants.
Now Resident Evil 6 goes in-gane.
=> amadeus: Fix reverb 3d mono wrong delay line offset

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
This PR fix the `IApplicationFunctions::GetSaveDataSize` call of `am` service.
Checked by RE, we previously didn't return the right values.
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2815 goes in game now (and probably some other games) :
=> am: Fix GetSaveDataSize stub

Ryujinx.HLE/HOS/Services/Pctl/ParentalControlServiceFactory/IParentalControlService.cs
This PR implement `IsRestrictionEnabled` call of `pctl` service.
It uses the same value as `CheckFreeCommunicationPermission`, checked with RE.
Fix https://github.com/Ryujinx/Ryujinx/issues/1743 where game thrown `System.NotImplementedException: ErrorApplet type ErrorPctlArg is not implemented.` because of the wrong logic in `CheckFreeCommunicationPermission`.
=> pctl: Implement IsRestrictionEnabled and fix CheckFreeCommunicationPermission

Ryujinx.Common/SystemInfo/LinuxSystemInfo.cs, Ryujinx.Common/SystemInfo/MacOSSysteminfo.cs, Ryujinx.Common/SystemInfo/WindowsSystemInfo.cs, Ryujinx.Graphics.Nvdec.Vp9/DecodeMv.cs, Ryujinx/Motion/Client.cs, Ryujinx/Program.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Updater/UpdateDialog.cs, Ryujinx/Updater/Updater.cs
This PR fix some warnings:
- SystemInfo which are platform specific, since .NET 5 we have to use `SupportedOSPlatform` attribute.
- `stackalloc` used in a loop could cause a potential stack overflow.
- All not used exceptions have their var removed in Motion client.
- Updater async tasks are currently run synchronously, so I've discarded the await warning by an empty assign.
- `TarInputStream` in the Updater is obsolete now and needs the filename Encoding.
Additionnally to that, I've cleaned up a bit Motion Client code.
BinaryFormatter warnings are still here, I'll let LDj3SNuD handle that.
=> Remove some warnings and cleaning code

Ryujinx/Ui/ApplicationLibrary.cs
This is an issue happening when you change your datetime format on your system and try to sort via last played datetime.
DateTime.Parse use the current thread culture and will not parse date correctly, effectively causing a crash.
As such, I added a check when loading the game list that ensure that the datetime is valid in current culture.
Fix #1727.
=> ui: Check last played datetime validity against current culture

Ryujinx.Graphics.Gpu/Image/TextureManager.cs
This PR disables resolution scaling on textures smaller than 8px on either width or height. It's very unlikely that textures this small (or thin) contain data that the end user really wants to scale.
The existing rules assumed that small textures would be covered by the square texture rule (which works on aligned sizes), this just solidifies it.
A very specific case that this fixes is when a game uses 1-dimensional-like textures, such as the HDR in:
- Splatoon 2
- Pikmin 3 Deluxe
- Captain Toad: Treasure Tracker
These games no longer dramatically increase ingame exposure when res scaling is enabled.
Before:
https://gyazo.com/e857b305b03b93105b4289dfa239658e
After:
This may also fix the blue colour ramp for strong attacks in Hyrule Warriors sometimes becoming trashed, though this game also …
=> Blacklist textures with a very small width or height from scaling

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Image/TextureMatchQuality.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs
When attempting to find "perfectly matching" textures, we actually have a few gives that allow matches that are not exactly perfect. However, this means that multiple textures that are "perfect" can exist, and some might be more preferable to others.
This PR adds a preference system to selection of matching textures, where it will pick the "most perfect" match available in the texture cache. If a match is deemed truly perfect, then it is returned immediately as before. However, if some matches are not perfect, it will return the one with the highest "quality" defined in an enum.
Currently, only format aliasing for sampler/copy is considered an imperfect match. This could be expanded in future to choose better texture matches for texture sizes that match by alignment vs perfectly. I didn't …
=> Prefer truly perfect texture matches over format aliased ones

Ryujinx.Graphics.Gpu/Shader/Cache/CacheCollection.cs, Ryujinx.Graphics.Gpu/Shader/Cache/CacheHelper.cs, Ryujinx.Graphics.Gpu/Shader/Cache/CacheManager.cs, Ryujinx.Graphics.Gpu/Shader/Cache/CacheMigration.cs, Ryujinx.Graphics.Gpu/Shader/Cache/Definition/CacheManifestHeader.cs, Ryujinx.Graphics.Gpu/Shader/Cache/Definition/GuestShaderCacheEntry.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs
This adds the guest GPU accessor to hashes computation.
As this change all the hashes from the cache, I added some migration
logic.
This is required for #1755.
=> salieri: Fix missing guest GPU accessor missing on hashes

Ryujinx.Graphics.Gpu/Shader/Cache/CacheHelper.cs, Ryujinx.Graphics.Gpu/Shader/Cache/Definition/GuestGpuAccessorHeader.cs, Ryujinx.Graphics.Gpu/Shader/Cache/Definition/GuestGpuStateFlags.cs, Ryujinx.Graphics.Gpu/Shader/CachedGpuAccessor.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, Ryujinx.Graphics.Gpu/State/MethodOffset.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs
In normal circumstances, the Z test is performed before the fragment test to avoid running it when possible. However, as this is an optimization, cases where it would change the functionality instead perform the _fragment test_ first, as it can do things like set the output depth, or perform incoherent writes.
This register exists to allow shaders to _force_ the Z test to happen early regardless of whether it will cause different behaviour. In the case of Image Load/Store, performing the Z test first can very much be _desired_ behaviour.
Register can be found here:
https://github.com/envytools/envytools/blob/master/rnndb/graph/gf100_3d.xml#L68
This fixes the interior volumes on Xenoblade for good. The issue was actually found by @ReinUsesLisp [over at …
=> Implement Force Early Z Test Register

Ryujinx.Audio.Renderer/Server/Performance/PerformanceManagerGeneric.cs
This fix a crash at boot in Pang Adventures.
=> amadeus: Fix a typo in TapFrame logic

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManagerServer.cs, Ryujinx.HLE/HOS/Services/Audio/IAudioOutManager.cs, Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs, Ryujinx.HLE/HOS/Services/Nv/INvDrvServices.cs, Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs, Ryujinx.HLE/HOS/Services/Time/IStaticServiceForGlue.cs, Ryujinx.HLE/HOS/Services/Vi/IApplicationRootService.cs, Ryujinx.HLE/HOS/Services/Vi/IManagerRootService.cs, Ryujinx.HLE/HOS/Services/Vi/ISystemRootService.cs
Should fix a regression introduced on #1458 that caused some games like Pokémon to crash due to a OutOfMemory error being returned from SendSyncRequest. It was getting out of memory because multiple guest processes were being creased for the Bsd service, and the memory used by them was never freed. This change creates just a single process for Bsd and fixes the issue. It's worth noting that #1504 does something similar, so it should fix the issue aswell in theory, but I didn't test yet.
=> Create a single guest process per IPC message processor

Ryujinx.HLE/HOS/Services/Audio/AudioRendererManagerServer.cs
Fix regression introduced on #1458 causing a error on Rune Factory 4 Special, the transfer memory handle was not being closed on the audio renderer service, this prevented the memory region from being reused as the transfer memory was still in use by the service. Didn't matter before because we didn't have separate guest process per service, so the kernel was not copying the handle and so the service had no ownership of the memory.
=> Close audio WorkBuffer transfer memory handle

Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Queries/BufferedQuery.cs, Ryujinx.Graphics.OpenGL/Queries/CounterQueue.cs, Ryujinx.Graphics.OpenGL/Queries/CounterQueueEvent.cs, Ryujinx.Graphics.OpenGL/Queries/Counters.cs, Ryujinx.Graphics.OpenGL/Renderer.cs
A glFlush was placed before query end to mitigate some potential issues when ending a query after 0 draw calls were made. However, glFlush has a substantial cost that can greatly slow down OpenGL if you're not careful.
This PR adds a draw count, which can be snapshotted when a query begins and compared when it ends. If 0 draws have occurred since we began, simply return the result immediately (0) and don't add it to the queue.
Affected games:
- Super Mario Odyssey (primarily metro kingdom, or when res scaling is active)
- Specifically, the nvoglv64.dll thread's load is now ~65% of the FIFO processing thread's load in the metro kingdom initial view, rather than being neck and neck with it. This means that perf improvements elsewhere are now visible.
- Splatoon 2
- Mario Kart 8 (many …
=> Dummy out occlusion queries with 0 draws, remove glFlush call

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs
Another quick one. `Target` is accessed from a ton of hot functions, and getting it through `Info` is causing a costly memcpy. This reduces costs when committing texture bindings.
=> Extract texture Target from Info for quick access

Ryujinx.Common/Logging/Targets/FileLogTarget.cs, Ryujinx/Ui/AboutWindow.cs
This change add the build version to the log file names, as example: `Ryujinx_1.0.0-dirty_yyyy-MM-dd_HH-mm-ss.log`
Fixes https://github.com/Ryujinx/Ryujinx/issues/1527 but log file names can't contains the game names since they aren't game specific.
I've cleaned up the class and the About window a bit.
=> logger: Add build version to the log file names

Ryujinx.HLE/HOS/Kernel/Memory/KMemoryManager.cs, Ryujinx.Memory.Tests/MockVirtualMemoryManager.cs, Ryujinx.Memory/AddressSpaceManager.cs, Ryujinx.Memory/IVirtualMemoryManager.cs
Fixes a regression from #1458 , where data written by a service would not mark regions as dirty, and reads from the service would not trigger flushes from textures.
This fixes vertex explosions after one race in Mario Kart 8 Deluxe, and may fix some other games with graphical errors introduced in #1458 . The game appears to write buffer data directly from a service.
Easy repro:
VS Race: Hyrule Circuit -> Sunshine Airport -> Yoshi Circuit
Broken example:
https://gyazo.com/a6ce0d7219ebe086dbb48c0324c43e16
You don't need a fixed example, you've all seen Mario Kart 8 before.
=> Signal memory tracking before/after mapping into another process

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
This implement `IApplicationFunctions GetHealthWarningDisappearedSystemEvent` call which is needed by Mario Kart 8 in chinese version. Call was checked by RE.
We still have to determine where signals some AM events.
Thanks to Kakasita on our Discord for reported this and confirm this works fine!
=> am: Implement GetHealthWarningDisappearedSystemEvent

Ryujinx/Ryujinx.csproj, Ryujinx/Ui/GLRenderer.cs
When NVIDIA Threaded Optimization is on, the driver will snapshot all threads in the system whenever the application creates or exits any threads. I’m guessing it does this so it knows what all your program’s threads are, but the method it uses to do this snapshots and iterates threads in _the entire system_.
https://docs.microsoft.com/en-us/windows/win32/api/tlhelp32/nf-tlhelp32-createtoolhelp32snapshot
The ThreadPool has something called a "GateThread" which terminates itself after some inactivity. However, it immediately starts up again, since the rules regarding when to terminate and when to start differ. This creates a new thread every second or so.
https://github.com/dotnet/runtime/blob/v5.0.0-rtm.20519.4/src/coreclr/src/vm/win32threadpool.cpp#L1424
The main problem with this is …
=> NVIDIA Thread create/delete stutter workarounds

Ryujinx.Common/Logging/LogClass.cs, Ryujinx.HLE/HOS/Services/Ngct/IService.cs, Ryujinx.HLE/HOS/Services/Ngct/IServiceWithManagementApi.cs, Ryujinx.HLE/HOS/Services/Ngct/IUnknown1.cs, Ryujinx.HLE/HOS/Services/Ngct/NgctServer.cs
This fixes the ngct services placeholder which was wrong.
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2887 needs calls of ngct service to goes further.
- IService Match and Filter calls are stubbed. Checked by RE.
- IServiceWithManagementApi Match and Filter calls are stubbed. Checked by RE.
Now Horace is playable :
=> ngct: Fix services and stub calls

Ryujinx.Graphics.OpenGL/Queries/BufferedQuery.cs, Ryujinx.Graphics.OpenGL/Queries/CounterQueue.cs, Ryujinx.Graphics.OpenGL/Queries/CounterQueueEvent.cs
Fixes an issue where GL queries could end up never returning a value after a previous 0-draw query (Luigi's Mansion 3). Ending the empty query before returning it to the pool seems to fix the issue.
=> End empty gl queries before returning them to the pool.

Ryujinx.Cpu/MemoryHelper.cs, Ryujinx.HLE/HOS/Ipc/IpcPtrBuffDesc.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IManagerForApplication.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IProfile.cs, Ryujinx.HLE/HOS/Services/Bcat/ServiceCreator/IDeliveryCacheProgressService.cs, Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs, Ryujinx.HLE/HOS/Services/Time/IStaticServiceForPsc.cs
#1458 added more accurate IPC handling. After the changes, services no longer have access to the size of fixed size buffers (thats how its done on hardware, they don't need to know the size since the size is fixed). Services were not prepared to handle that, and we were reading them from the client buffer descriptor. So, after the IPC changes the functions using fixed-size output buffers could return data that is too large (that would result in a error being returned by the kernel as copy would fail), or too small (which would cause data to be missing).
This updates the affected function to write the correct sizes on the pointer buffer descriptors.
=> Rewrite size for fixed size buffers

ARMeilleure/Instructions/InstEmitMemoryExHelper.cs, ARMeilleure/Translation/PTC/Ptc.cs
This fixes a regression introduced on #1413 where the STREX instruction implementation could write the wrong value or write to the wrong address if the register used for Rs (result) was the same register used for either the address or the value. Additionally, this also zeros the upper bits of the exclusive value stored on context, just to be on the safe side, in case there is some application out there mixing LDREX/STREX of different sizes.
This fixes a regression on Sonic Forces, where the game would no longer boot.
=> Fix register read after write on STREX implementation

ARMeilleure/CodeGen/X86/Assembler.cs, ARMeilleure/CodeGen/X86/PreAllocator.cs
For shift instructions, the pre-allocator needs to insert a copy to ensure the shift value is on the CL register (and you can only use CL for the shift on x86), and additionally, it needs to insert copies to ensure that the first source operand and the destination are on the same register. Right now there are 2 separate functions that handles this, but the problem is that each one of those functions returns a new node that is the node of the last operation is inserted on the list, and due to this behavior, the shift instruction would be skipped on the next call.
To sum it up, the following was possible:
- `HandleDestructiveRegCopy` inserts a copy before and a copy after the operation to ensure dest == src1, then it returns the node of the last copy.
- `HandleConstrainedRegCopy` is then …
=> Fix pre-allocator shift instruction copy on a specific case

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/Types/MessageInfo.cs, Ryujinx.HLE/HOS/SystemState/AppletStateMgr.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade
This implement the ability to send a Wake-up (Resume) message to the guest.
Some games needs to sleep and wake-up the switch to unlock some ingame features, we now supports that.
I've cleaned up the `AppletState` class and `ICommonStateGetter::ReceiveMessage` call is implemented accordingly to RE.
(Thanks to Ryushu on Discord for helping me to reproduce the issue)
=> am/gui: Implement Wake-up message

Ryujinx.Common/Configuration/AspectRatioExtensions.cs, Ryujinx.Common/Configuration/ConfigurationFileFormat.cs, Ryujinx.Common/Configuration/ConfigurationState.cs, Ryujinx.Graphics.GAL/ImageCrop.cs, Ryujinx.Graphics.OpenGL/Window.cs, Ryujinx.HLE/HOS/Services/SurfaceFlinger/SurfaceFlinger.cs, Ryujinx/Config.json, Ryujinx/Ui/GLRenderer.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade, Ryujinx/Ui/SettingsWindow.cs, Ryujinx/Ui/SettingsWindow.glade, Ryujinx/Ui/StatusUpdatedEventArgs.cs, Ryujinx/_schema.json
This implement a setting for the aspect ratio to values: 4:3, 16:9 (default value), 21:9, 32:9 and stretched.
You can sets it at runtime using the settings window or using the toggle in the status bar.
It fixes #1597.
MK8 using an ExeFs patch for 21:9 (1080p screen):
ACNH using an ExeFs patch for 21:9 (1080p screen):
Some SMO example (without patch):
4:3
16:9
21:9
32:9
Stretched
=> gui/gpu: Implement setting and toggle for Aspect Ratio

Ryujinx.HLE/HOS/Horizon.cs
This changes the process termination order to terminate the application before services, this way the application doesn't receive errors due to services exiting. This fixes some crashes on exit caused by games asserting or faulting due to service errors.
=> Terminate application before services

Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoDevice.cs, Ryujinx.Graphics.Gpu/Window.cs, Ryujinx.HLE/HOS/Services/SurfaceFlinger/BufferQueueCore.cs, Ryujinx.HLE/HOS/Services/SurfaceFlinger/BufferQueueProducer.cs, Ryujinx.HLE/HOS/Services/SurfaceFlinger/SurfaceFlinger.cs, Ryujinx.HLE/HOS/Services/SurfaceFlinger/Types/AndroidFence.cs, Ryujinx.HLE/PerformanceStatistics.cs, Ryujinx.HLE/Switch.cs, Ryujinx/Ui/GLRenderer.cs
Experimental (needs testing and approach review). This PR removes the frame timer in GLRenderer and replaces it with a "frame ready" signal that's sent whenever a frame's AndroidFence is completed. When this happens, GPU command processing is interrupted and we present a frame immediately.
- "interrupts" the GPFifo processing, allowing it to check for frames to present
- Window keeps track of # frames with their fences reached. Present only occurs when at least one frame is ready.
This is an alternative to processing and presenting on separate threads. In future this should be rethought since we will have multiple SurfaceFlinger layers to consider, though it might still be useful if we decide to single thread GPU processing between these layers for whatever reason (easier debug?) …
=> Interrupt GPU command processing when a frame's fence is reached.

Ryujinx.Memory/InvalidMemoryRegionException.cs
Changes "a" to "an" since the next word begins with a vowel.
=> Update InvalidMemoryRegionException.cs to abide by English rules.

Ryujinx/Updater/UpdateDialog.cs
A small code change to fix the issue that was forcing the user to press the "Yes" button twice to restart Ryujinx after it had been updated, instead of only once.
Fixes recently opened issue #1800
=> Fix button press issue

README.md, Ryujinx/Ryujinx.csproj, Ryujinx/THIRDPARTY.md
This remove dependency on OpenAL EA on Windows and allows to operate with both backend without any user interventions.
Based on #1842 and supersede it.
=> Distribute with OpenAL Soft on Windows

Ryujinx.Common/Configuration/ConfigurationState.cs, Ryujinx/Config.json, Ryujinx/_schema.json
Enables PPTC by default. Enough time has passed and enough games tested that it should be the preferred setting for 99.9% of games. In case we are worried about PPTC files being put on the user's disk, shader cache already does this by default and generates about the same size files on average, so this should no longer be a concern.
=> Enable Profiled Persistent Translation Cache (PPTC) by default

Ryujinx.HLE/HOS/Kernel/Threading/KAddressArbiter.cs
This PR contains the following changes:
- Update Wait/SignalProcessWideKey implementation to match changes made on official 11.0 kernel.
- They now store a bool at the key address indicating if the number of threads waiting the condition variable is > 0. Games targeting firmware 11.0 or newer needs this to work properly (no games are know to target it so far).
- Update SignalAndModifyIfEqual implementation to match changes made on official 7.0 kernel.
- The way how the value is modified changed. Games targeting firmware 7.0 or newer might need this to work properly.
- Fix a bug where SignalToAddress would use the old priority even if the thread priority was updated after it started waiting (I'm not sure if this was a bug that was present on 6.x kernel or just an oversight).
- Simplified …
=> Update KAddressArbiter implementation to 11.x kernel

Ryujinx.HLE/HOS/Services/Apm/IManagerPrivileged.cs
Closes https://github.com/Ryujinx/Ryujinx/issues/1846
With this PR, there is no more error about missing `apm:p`, but the games that did this error (such as [2048](https://github.com/FlagBrew/2048)) now there is this following error:
```
Exception has occurred: CLR/System.ArgumentOutOfRangeException
An exception of type 'System.ArgumentOutOfRangeException' occurred in Ryujinx.Graphics.Gpu.dll but was not handled in user code: 'Specified argument was out of the range of valid values.'
at Ryujinx.Graphics.Gpu.Synchronization.SynchronizationManager.RegisterCallbackOnSyncpoint(UInt32 id, UInt32 threshold, Action callback) in C:\Users\macabeus\ApenasMeu\Ryujinx\Ryujinx.Graphics.Gpu\Synchronization\SynchronizationManager.cs:line 80
at Ryujinx.HLE.HOS.Services.SurfaceFlinger.AndroidFence.Register …
```
=> services: add "apm:p"

Ryujinx.HLE/HOS/Services/SurfaceFlinger/SurfaceFlinger.cs
This PR fixes a regression introduced in #1741. The actual implementation do the assumption of fences always exists and then it register the callback.
Homebrews may not use fences, so the code crashes when it try to register the callback.
=> surfaceflinger: Fix fences callback registering issue

Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/IManagerForApplication.cs, Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/IManagerForSystemService.cs, Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/IProfile.cs, Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/IProfileEditor.cs, Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/ManagerServer.cs, Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/ProfileServer.cs, Ryujinx.HLE/HOS/Services/Account/Acc/ApplicationServiceServer.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForAdministrator.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForApplication.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForSystemService.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IBaasAccessTokenAccessor.cs, Ryujinx.HLE/HOS/Services/Account/Acc/Types/AccountServiceFlag.cs, Ryujinx.HLE/HOS/Services/Account/Acc/Types/UserId.cs, Ryujinx.HLE/HOS/Services/Arp/IReader.cs, Ryujinx.HLE/HOS/Services/Arp/LibHacIReader.cs, Ryujinx.HLE/HOS/Services/Friend/IServiceCreator.cs
This PR cleanup our account services implementation.
Since the service use the same "basic" functions in different interfaces, I've made some "Server" class which contains generic calls implementation. That lets us implement more calls without writing more duplicate code.
- IManagerForApplication and IManagerForSystemService are based on the same calls.
- IProfile and IProfileEditor are based on the same calls.
- IAccountServiceForAdministrator, IAccountServiceForApplication and IAccountServiceForSystemService are based on the same calls.
I've cleaned arp:r service and IServiceCreator a bit.
Everything is checked by a quick RE.
=> account: Services Refactoring

Ryujinx.HLE/HOS/Services/Hid/HidDevices/DebugPadDevice.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMem/DebugPad/DebugPadEntry.cs
Fixes #1872 
Some games seem to be really insistent on a proper DebugPad.
In any case, updating the second sample timestamp (bringing this in line with other devices) fixes the softlock.
=> Update missing sample timestamp in DebugPad

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeBranch.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeBranchPop.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeConditional.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeExit.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitFlow.cs
Like the BRAnch instruction, BRK and SYNC also support a conditonal, in addition to the predicate, which allows compound predication of the jump. The CC register is set by previous instruction based on the result, setting the NZCV flags. Example:
```
@P0 BRK CC.NEU
```
In this case, the branch is taken if P0 is true *and* the Z flag is clear, as the zero flag should be set if the result is zero, and cleared otherwise. This is usually used with ISET/FSET with `RZ.CC` as destination that will set the zero and negative flags based on the result, which can be -1 (if comparison is true) or 0 (if its false).
This improves rendering on Monster Hunter Rise, but there are still other bugs preventing most objects from being draw.
=> Support conditional on BRK and SYNC shader instructions

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/LibraryAppletCreator/ILibraryAppletAccessor.cs
This PR stub appletAE PresetLibraryAppletGpuTimeSliceZero which is needed by the demo of Monster Hunter Rise.
The call is used when Software Keyboard is used, since we doesn't support applets, it's fine to stub it.
I've check things by RE a bit.
Closes #1875
=> am: stub PresetLibraryAppletGpuTimeSliceZero

Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeConditional.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/NvHostAsGpuDeviceFile.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/Types/AddressSpaceContext.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvMap/NvMapDeviceFile.cs
This is an attempt to fix the remap ioctl when the handle value is 0.
Fixes the invalid address crash on Monster Hunter Ride.
Also includes some cleanup, and I removed some checks that can never be true (checking if unsigned integers is less than 0 etc).
Supersedes #1816
=> Fix remap when handle is 0

Ryujinx.Graphics.Gpu/Engine/Inline2Memory.cs
NVN uses `LoadInlineData` to load the compute QMD structure *and* the reserved driver constant buffer data (thats the only thing it ever seems to use `LoadInlineData` for). Due to the sequence number optimization on buffer updates, that prevents potentially costly modification checks, the compute reserved constant buffers were not being updated, since `LoadInlineData` currently does not update the sequence number. This PR fixes that.
This fixes a bug on Monster Hunter Rise demo where the screen would randomly turn black with white elements due to compute reading values from the wrong SSBO.
The only cases affected by this should be compute reading reserved constant buffers, mainly those using LDG/STG where the shader translator can't figure out which SSBO it is accessing. So, to sum it up, …
=> Fix compute reserved constant buffer updates

Ryujinx.HLE/HOS/Services/Pctl/ParentalControlServiceFactory/IParentalControlService.cs
This PR stub call `IsFreeCommunicationAvailable` since it's the same as call `CheckFreeCommunicationPermission` without a sets of an internal field.
I've fixed a wrong logic found while I'm checked the call by RE.
This fix #1883.
=> pctl: Stub IsFreeCommunicationAvailable

Ryujinx.HLE/FileSystem/VirtualFileSystem.cs
Loading NSPs with personalized tickets results in the following error, and the game does not load:
```
00:00:00.332 |E| Loader LoadNsp: Unable to load NSP: System.Security.Cryptography.CryptographicException: The specified RSA parameters are not valid. Exponent and Modulus are required. If D is present, it must have the same leng
th as Modulus. If D is present, P, Q, DP, DQ, and InverseQ are required and must have half the length of Modulus, rounded up, otherwise they must be omitted.
at System.Security.Cryptography.RSAImplementation.RSACng.ImportParameters(RSAParameters parameters)
at LibHac.Ticket.GetTitleKey(Keyset keyset)
at Ryujinx.HLE.FileSystem.VirtualFileSystem.ImportTickets(IFileSystem fs) in ...\Ryujinx\Ryujinx.HLE\FileSystem\VirtualFileSystem.cs:line 265
at …
```
=> Only attempt to import common tickets.

Ryujinx.Common/Logging/LogClass.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineKeyboardRequest.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineKeyboardResponse.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineKeyboardState.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardAppear.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardCalc.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardDictSet.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardInitialize.cs, Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
This PR implements the inline protocol used by the `SoftwareKeyboardApplet` to talk to games like Gnosia (Ryujinx/Ryujinx-Games-List#2563) and Monster Hunter Gen U (#1640). The lack of this protocol results in bad initialization of the software keyboard applet and, very likely, a hard lock inside the game.
This implementation of the Inline keyboard has support for Ok and Cancel operations and relies on the input GUI to acquire user input while the game runs in the background:
Therefore it does not draw a virtual keyboard on top of the game ~~, which (for now) can lead to minor graphical glitches~~
**OLD version:**
~~These glitches do not break the game and may only appear when the input is requested. They may be fixed by implementing the …
=> Add support for inline software keyboard

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.Gpu/Engine/MethodCopyBuffer.cs, Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, Ryujinx.Graphics.Gpu/State/BufferSwizzleComponent.cs, Ryujinx.Graphics.Gpu/State/CopyBufferSwizzle.cs, Ryujinx.Graphics.Gpu/State/MethodOffset.cs, Ryujinx.Graphics.OpenGL/Buffer.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs
NVN uses the DMA engine remap functionality to do buffer clears. Basically you can specify a constant as the copy source, and it willl fill the buffer with the constant value. This is similar to OpenGL `glClearBufferSubData` function. This implements a fast path using this function. The full functionality still needs to be implemented (and it can't be done with the host API alone, since its possible to intermix sources from another buffers and constants, swizzle etc). However all functionality used by NVN should be implemented.
This also fixes a glitch on vector normals on Monster Hunter Rise (which could contain garbage values as the buffer was not being cleared before), this improving the rendering, but there are also other issues that needs to be fixed (texture related).
=> Implement clear buffer (fast path)

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitAlu.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitMemory.cs, Ryujinx.Graphics.Shader/Translation/EmitterContextInsts.cs
This implements the CC mode on the ISCADD shader instruction (which is supposed to set the NZCV flags based on the post-shift addition result, as far I can tell), and the X (extended) mode on the ISET and ISETP instruction (used for 64-bit and longer comparisons).
This also fixes a bug on the STL, STS and STG shader instruction where using RZ as input with a length greater than 32-bit would only write the value once. Now it writes 0 up to the size of the write (1, 2 or 4 words).
This fixes normal vectors on animated characters in Monster Hunter Rise DEMO improving the rendering a little bit, but there are still other things to be fixed (coming soon).
NOTE: This was a shader bug, so it will invalidate the shader cache.
=> Implement shader CC mode for ISCADD, X mode for ISETP and fix STL/STS/STG with RZ

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeLop.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitAlu.cs
The condition was being read from the wrong bits on the LOP3 instruction.
Note: The shader cache version was updated, shaders will be invalidated (again, sorry about that).
=> Fix shader LOP3 predicate write condition

Ryujinx.Common/Configuration/ConfigurationFileFormat.cs, Ryujinx.Common/Configuration/ConfigurationState.cs, Ryujinx/Config.json, Ryujinx/Ui/GLRenderer.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.glade, Ryujinx/_schema.json
Closes https://github.com/Ryujinx/Ryujinx/issues/1853
=> settings: add Show Confirm Exit toggle

Ryujinx.Graphics.Gpu/Image/TextureInfo.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.Texture/SizeCalculator.cs
The base level was being ignored, which meant that it would bind level 0 only, ignoring the level that was specified. This change allows the correct mipmap level to be accessed from the shader.
Summary of the changes:
- Use base level and max level values from the texture descriptor on the texture pool. They were previously ignored, which means it would always bind all the levels of the texture regardless of what the game actually wants.
- Use layer size provided by the game for render targets. Before the layer size was calculated from the texture dimensions. However, for textures were not all levels are used, we can't calculate the layer size as we don't know the real amount of levels, and we don't know the current base level. So instead of calculating it, it uses the value provided by …
=> Fix mipmap base level being ignored for sampled textures and images

Ryujinx.Cpu/MemoryManager.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TextureInfo.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.Gpu/Memory/GpuRegionHandle.cs, Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs, Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs, Ryujinx.Graphics.Gpu/Window.cs, Ryujinx.Graphics.Texture/SizeInfo.cs, Ryujinx.Memory/AddressSpaceManager.cs, Ryujinx.Memory/IWritableBlock.cs, Ryujinx.Memory/Range/IMultiRangeItem.cs, Ryujinx.Memory/Range/MemoryRange.cs, Ryujinx.Memory/Range/MultiRange.cs, Ryujinx.Memory/Range/MultiRangeList.cs, Ryujinx.Memory/WritableRegion.cs
This aims to support GPU textures mapped at non-contiguous CPU regions, as some games requires it (such as the Monster Hunter Rise Demo and possibly some UE4 games).
**Problem:**
Games can map GPU virtual memory regions to non-contiguous physical regions using the remap ioctl. For example, we may have a GPU region, from 0 to 0x2000, where the range from 0..0x1000 is mapped to physical address 0x8000, and the range 0x1000..0x2000 is mapped to physical address 0x15000 (the values are made up and are supposed to be just an example). Right now the texture data would be read from the physical range 0x8000..0x10000, which is wrong because only half of the data is mapped there. The correct behavior would be reading the first half of the data from 0x8000..0x9000, and the second half from …
=> Support for resources on non-contiguous GPU memory regions

Ryujinx.Cpu/MemoryManager.cs, Ryujinx.Cpu/Tracking/CpuMultiRegionHandle.cs, Ryujinx.Cpu/Tracking/CpuSmartMultiRegionHandle.cs, Ryujinx.Graphics.GAL/IRenderer.cs, Ryujinx.Graphics.Gpu/Engine/Compute.cs, Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoClass.cs, Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoDevice.cs, Ryujinx.Graphics.Gpu/Engine/MethodIncrementSyncpoint.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/GpuContext.cs, Ryujinx.Graphics.Gpu/Memory/Buffer.cs, Ryujinx.Graphics.Gpu/Memory/BufferBounds.cs, Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, Ryujinx.Graphics.Gpu/Memory/BufferModifiedRangeList.cs, Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.OpenGL/Sync.cs, Ryujinx.Graphics.Shader/BufferDescriptor.cs, Ryujinx.Graphics.Shader/BufferUsageFlags.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Memory.Tests/MockVirtualMemoryManager.cs, Ryujinx.Memory.Tests/TrackingTests.cs, Ryujinx.Memory/Range/RangeList.cs, Ryujinx.Memory/Tracking/MultiRegionHandle.cs, Ryujinx.Memory/Tracking/RegionHandle.cs, Ryujinx.Memory/Tracking/SmartMultiRegionHandle.cs, Ryujinx.Memory/Tracking/VirtualRegion.cs
This PR makes it possible for SSBO writes to be read from CPU, and ensures they are not accidentally overwritten. The performance impact should be minimal due to the approach, but more extreme cases could have an impact.
The primary goal is fixing restarting particles that appear in many Nintendo games, caused by CPU writes to the same page that an SSBO write happens to (which causes the whole page to be read in, and replace the SSBO written data with its initial value). I was also hoping it might fix some vertex explosions. Flushing data to be read by CPU is hilariously just a second goal, but it works now too.
Simply adding read/write protection to a region of a buffer every time there is a modification would be a recipe for disaster - a tracked write could happen to the same page of …
=> Implement lazy flush-on-read for Buffers (SSBO/Copy)

Ryujinx/Ui/Applet/ErrorAppletDialog.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/Widgets/GameTableContextMenu.cs, Ryujinx/Ui/Widgets/GtkDialog.cs, Ryujinx/Ui/Widgets/ProfileDialog.cs, Ryujinx/Ui/Windows/AboutWindow.cs, Ryujinx/Ui/Windows/ControllerWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.cs
The icon on the Linux build has been broken since #1859 since every mention of Icon was removed.
Current master:
Generic icon on window and bar
After fix:
The icon is back on the window and the bar
=> Fix Linux Icon

Ryujinx/Ui/KeyboardController.cs
I saw a few user complaints on discord that diagonal inputs are not working with a keyboard controller in certain games. Some games get confused as the current code emulates a square zone whereas they expect a circular one (which is natural). Thought of using a lookup table too but ultimately this seemed cleaner. 
Also previously, the keyboard analog sticks always preferred down-right. So, if say, up & down were pressed together it'd be registered as down. I changed this behavior to be additive so opposite directions cancel out. There's probably other things that could be improved in the area but I'd like to keep this fix simple.
=> Emulate a circular zone for keyboard analog sticks

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ILibraryAppletCreator.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/IStorage.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/IStorageAccessor.cs
This PR implement ILibraryAppletCreator::CreateHandleStorage call (Close #1896), fixes CreateStorage/CreateTransferMemoryStorage results and fixes the am IStorage Write ReadOnly check.
This fix the boot regression of MHGU introduced in #1868.
=> am: Implement CreateHandleStorage and fixes

Ryujinx.Memory/IVirtualMemoryManager.cs, Ryujinx.Memory/MemoryBlock.cs
This reduces the size of the temporary buffer used for copy and fill operations. This should fix a possible out of memory exception, if the user is already low on ram during game load/startup. Does not have any significant impact other than that.
The size was reduced from 1GB to 16MB.
=> Reduce temporary copy/fill buffer size

Ryujinx/Ui/MainWindow.cs
fixes the crashes on linux when you stop emulation, and when you try to
exit the emulator while a game is running
tested on windows too, and didn't come up to any problems on my side
Fixes #1810
=> Fix some GLXBadDrawable crashes on linux

Ryujinx.Graphics.Gpu/Image/TexturePool.cs
Fix a regression introduced by #1911 on Kirby Star Allies, where the game would crash on startup. The game was trying to use a invalid min lod value, where min and max lod where set to 15, and levels was 8, leading to a out of range exception. Now it does not take the base level into account if its value is invalid.
It might be worth doing something similar for min lod and max lod, just in case min lod > max lod (which is also invalid and would result in a negative levels count).
=> Fix out of range exception when a invalid base lod is used

Ryujinx.Graphics.Gpu/Image/Texture.cs
This improves the speed of ASTC decoding greatly by using multiple CPU cores for the task. I believe it was not enabled by default due to the concern that it would take away CPU that would be otherwise used by the game and background JIT. This is not as much of a issue now that we have PPTC (enabled by default) that eliminates the JIT cost after a few runs.
=> Enable parallel ASTC decoding by default

Ryujinx/Ui/KeyboardController.cs
Fixes #1828. Didn't see the issue until now; should've been part of #1906.
=> Fix SL/SR typo in keyboard controller mapping

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ILibraryAppletCreator.cs
From https://switchbrew.org/wiki/Applet_Manager_services#CreateTransferMemoryStorage :
```
The input bool controls whether writing to the storage is allowed: #Write will throw an error if this flag is not set.
```
So the state of `isReadOnly` must be inverted.
=> Fix inverted read only flag in transfer memory creation

Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZone.cs
An unfortunate optimization resulted in `ParsePosixTime` returning false early, making the TZIF footer info go unused for all timezones.
Closes #1949
=> Fix TZName parsing in TZIF footer

Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs
#1905 changed the behavior of exact texture matches a little bit. Instead of comparing the physical address (CPU VA) and assuming it is contiguous, it was changed to compare the GPU VA instead (as physical regions might not be contiguous). This change makes it closer to the previous behavior, it now compares the physical regions if the virtual address is not the same (see the new `CompareRange` method), and allows a match if the virtual addresses are different, but mapped to the same physical region.
This seems to fix (or at least greatly improve) a regression on Rune Factory 4 Special caused by the aforementioned PR.
NOTE: This has the potential to slow things down if the slow path that calls `CompareRange` is hit frequently, which is the reason I was only compared the GPU virtual …
=> Match texture if the physical range is the same

Ryujinx.Graphics.Gpu/Memory/Buffer.cs, Ryujinx.Graphics.Gpu/Memory/BufferManager.cs
Some games such as Yo-kai watch performs a out of bounds storage buffer access. It says that the size is 4 bytes, but accesses (reads and writes) 256 bytes on a compute shader. In fact the game allocates enough memory for that (the buffers are 256 bytes apart), its just the size that is wrong on this particular call. The shader does not use this size for anything, so this is not a problem on the Switch, but on OpenGL, looks like theres some bounds checking going on preventing values after the first 4 bytes from being read/written.
This fixes this particular issue by binding the entire buffer rather than just the range that the game says its using. Unfortunately there is no way to guess the real size of the buffer, so this will just effectively page align the size, which works in this case …
=> Allow out of bounds storage buffer access by aligning their sizes

Ryujinx.Common/System/DisplaySleep.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.glade
This PR prevents Windows from turning off the display while a game is running. 
I also looked into implementing this for Linux but determined it to be too complex, as it requires D-Bus communication, and it would have been hard for me to test since I don't currently have any Linux test environment setup.
The placement and use of the class is based on the WindowsMultimediaTimerResolution class, as that is also a Windows exclusive feature that calls native code. Windows itself keeps tracks of threads that are preventing the display from sleeping and resumes normal behavior when they exit, so it was not necessary to create a method to manually enable the display sleep.
I happened to noticed some minor errors in the GTK Glade file while I was looking at it (One wrong and one missing tooltip) …
=> Prevent Windows Display Sleep

Ryujinx/Ui/Windows/ControllerWindow.glade
Currently, when configuring controller input with an "Xinput Controller" or "Unmapped Controller", the window does not fit the image for Pro Controller (width limited), the image/settings for Joycon Pair (width and height limited), and the settings for single Joycon options (height limited). This PR proportionally enlarges the window so that no scrolling is ever necessary to fully see the controller image or settings fields.
Before:
After:
=> GUI Update: Enlarge controller input window to fit all images/settings without scrolling

Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/AtomicMinMaxS32Shared.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/AtomicMinMaxS32Storage.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/HelperFunctionNames.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/TexelFetchScale_cp.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/TexelFetchScale_fp.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenHelper.cs, Ryujinx.Graphics.Shader/Ryujinx.Graphics.Shader.csproj, Ryujinx.Graphics.Shader/StructuredIr/HelperFunctionsMask.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs
This adds support for atomic minimum and maximum with a signed integer type. The problem of supporting the signed operation is that the storage (both buffer and shared memory) is uint, and the overload of the atomic operation used is decided from the type, so we can only use the uint `atomicMin` and `atomicMax` functions. This adds new functions that can do signed atomic min/max using a CAS loop.
Other changes: Changed some of the helper functions to have `{` on a new line for conssitency with the other ones.
I believe theres no need for shader cache invalidation here as the affected shaders would fail to compile before this change.
Fixes missing graphics on Disgaea 6 Demo.
=> Add support for shader atomic min/max (S32)

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs
Fix a regression when dumping compute shader code since #1701, where it would pretend that the shader has a 0x50 bytes header when it doesn't, so the "code" dump was missing the first 0x50 bytes of code.
=> Fix compute shader code dumping

Ryujinx.HLE/FileSystem/Content/ContentManager.cs, Ryujinx/Ui/App/ApplicationLibrary.cs, Ryujinx/Ui/MainWindow.cs
This PR attempts to improve the initial setup UX. After placing keys, the user no longer needs to restart Ryujinx before installing firmware. Also, if they disregard the `NoKeys` dialog, it'll be shown again when a firmware is selected.
Closes #1843
Slightly unrelated, I noticed the generic exception log in `LoadApplications()` is cryptic unless debug logs are enabled but a dialog pops up asking to check logs. So, moved the exception to the warning itself.
=> Initial Setup: Reload keys before verifying firmware

Ryujinx.Graphics.Gpu/Engine/MethodConditionalRendering.cs
This changes the implementation of conditional rendering to actually compare the values on memory even if they don't come from queries, instead of just returning false.
I beleive it was done this way because Super Mario Maker 2 and Animal Crossing New Horizons had some issues otherwise, but I tested both games and they seem fine now with this change.
This is required to make Marvel Ultimate Alliance 3 render. The game now shows vertex explosions with this change, but it was probably already broken, but not visible as it was not rendering most models.
Games that should be tested with the change (they use conditional rendering without queries):
- Animal Crossing New Horizons
- Super Mario Maker 2
Doesn't hurt to also test other games using conditional rendering (from queries), such as SMO …
=> Fix conditional rendering without queries

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.GAL/VertexAttribDescriptor.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.OpenGL/Framebuffer.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/VertexArray.cs
This makes some simple changes on the OpenGL backend to reduce the number of redudant calls (that does not change any state). This make navigating debugging captures a little bit easier. It might also have a very small performance improvement since it does less native calls.
As an example, I have attached 2 NSight captures, the top one is master and the bottom one is with this PR. Both taken in Xenoblade Chronicles Definitive Edition, on the very first part of the game (last screenshot shows which part it was captured at).
master:
PR:
As you can see, the event count dropped from 96418 to 35501, thus the number of calls is approximately 37% compare to master, so roughly 1/3 of calls. The improvement depends on the game and on the area, but in general those changes at least halves the …
=> Avoid some redundant GL calls

Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs
Fix a regression introduced on #1948 that would generate invalid code for atomic SSBO operations.
Fixes regression on Persona 5 Scramble where it would crash before the title screen.
=> Fix regression on shader atomic SSBO operations

Ryujinx.Graphics.Shader/CodeGen/Glsl/TypeConversion.cs
Fixes crashes with the exception:
```
System.ArgumentException: Invalid reinterpret cast from "F32" to "Bool".
```
This happens on shaders with the `PSET` instruction when the shader translator decides to use a F32 type for the variable that will hold the value. It does that because `PSET` allows moving a predicate to a register, and it may decide to use the float type to avoid casts (obviously, its not the most appropriate type for that, but it should still work regardless).
=> Support shader F32 to Bool reinterpretation

ARMeilleure/Instructions/InstEmitSimdArithmetic.cs, ARMeilleure/Translation/PTC/Ptc.cs
Both estimate instruction (RECPE and RSQRTE) only produces 8 bits of fraction, the remaining 15 bits are filled with zeros. The equivalent x86 instructions also returns an approximation, but they have a bit more precision so the result is different from Arm. This PR round the result to nearest and limits the number of bits of the exponent to 8, to match Arm. The results are still not the same for all inputs, and making them match would require implementing the soft float implementation inline, which would hurt performance considerably, so thats a tradeoff.
This fixes a logic bug on Catherine Full Body where the player was not able to grab the edge of the blocks after pulling a block. Would like to have someone confirm that its indeed fixed.
Closes #1940.
=> Lower precision of estimate instruction results to match Arm behavior

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/Shuffle.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/ShuffleDown.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/ShuffleUp.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/ShuffleXor.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenHelper.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitMove.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/INode.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/Operation.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/PhiNode.cs, Ryujinx.Graphics.Shader/StructuredIr/InstructionInfo.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, Ryujinx.Graphics.Shader/Translation/EmitterContextInsts.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/Optimizer.cs, Ryujinx.Graphics.Shader/Translation/Ssa.cs
This support multiple destination operands on the IR rather than just one.
This is required for supporting the predicate writes for the shuffle instruction. Without this change it would either need to calculate the value inline, or add a separate function just to return the bool result. With the change, now the same function can return both values.
As a follow-up I plan to change the call instruciton implementation and 64-bit multiply to also use it, which will simplify some code.
=> Support multiple destination operands on shader IR and shuffle predicates

Ryujinx.Graphics.Gpu/Image/Pool.cs, Ryujinx.Graphics.Gpu/Image/SamplerDescriptor.cs, Ryujinx.Graphics.Gpu/Image/SamplerPool.cs, Ryujinx.Graphics.Gpu/Image/TextureDescriptor.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs
Rather than evaluating info for cached textures and checking for a match to the existing pool texture, saves the descriptor used to create that texture and only invalidates textures if it no longer equals the guest memory descriptor. Also does this comparison for samplers, to avoid recreating them (before, all samplers on a page would be invalidated).
This may improve performance in games that have stutters caused by texture pool invalidation. Not sure what games that will be, but at least this is a lot faster now.
This PR also fixes an issue with Mario Kart 8 Deluxe introduced by #1905 where the course's cubemap array and shadow map could be evicted from the pool while playing, which would cause the course to become rainbow soup... and generally really hard to look at:
A way to reproduce …
=> Use a descriptor cache for faster pool invalidation.

Ryujinx/Ui/Windows/SettingsWindow.glade
We all call it PPTC. The cache management section calls it PPTC. Now the settings page will call it PPTC (but preserve the full term in parentheses). This way, when asking or directing users about their PPTC settings they won't be left wondering what PPTC is and where to find it.
Before:
After:
=> Add PPTC acronym to settings page for ease of reference

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/GlslGenerator.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, Ryujinx.Graphics.Shader/Translation/ShaderHeader.cs
This implements the geometry shader passthrough functionality, which allows passing the geometry inputs directly to the output without any modification. This feature is exclusive to NVIDIA, but should be possible to support on other vendors eventually by generating the code to copy all inputs to the output on the geometry shader.
This improves rendering on Marvel Ultimate Alliance 3 a little bit.
Before (screenshot not mine):
After:
=> Implement geometry shader passthrough

Ryujinx.Graphics.Shader/IntermediateRepresentation/Instruction.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/Operation.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/Optimizer.cs, Ryujinx.Graphics.Shader/Translation/RegisterUsage.cs, Ryujinx.Graphics.Shader/Translation/Ssa.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
Simplifies handling of shader call instructions, now that multiple operands are supported, the `CallOutArgument` IR instruction is no longer needed, and has been removed. It now stores the out arguments as operands on the call operation itself.
This should not cause any change to the generated code and should also not have any effect, its just refactoring.
=> Use multiple dest operands for shader call instructions

Ryujinx.Graphics.Gpu/Image/Texture.cs
On the guest, multisample textures have their width/height multiplied by the amount of samples in each axis. When the texture is passed to the host, the actual size of the texture is calculated by dividing the width and height by the amount of samples in X and Y. And then the total amount of samples (samples in X * samples in Y) is also passed to the host. This creates a mismatch during flush where the texture that it gets back from the host is smaller than what is is trying to write in memory, this causes an access violation on Linear -> Block Linear conversion as it attempts to do a out of bounds access. Another problem is that the host simple does not support getting data from a multisample texture.
For the reasons listed above, this simply disables flushing for those multisample …
=> Do not flush multisample textures

ARMeilleure/Translation/TranslatedFunction.cs, ARMeilleure/Translation/Translator.cs
One of the changes on #1518 caused a large performance regression (mainly during load) on games that unmap memory frequently. This happens because it checks if the JIT cache has a function overlapping the unmapped range on each unmap, which right now is very slow as the data structure used is not really suitable for quick match of overlapping ranges.
This changes fixes the performance regression by completely removing the invalidation on unmap. The reason for this is because it was already largely incomplete anyway, as it does not actually remove the host code from the cache (possibly causing it to use all the memory reserved for the JIT cache, if the game is generating or loading code at runtime), and because the functions being removed from the cache does not become complete unreachable …
=> Disable partial JIT invalidation on unmap

Ryujinx.Graphics.Gpu/Shader/Cache/CacheHelper.cs, Ryujinx.Graphics.Gpu/Shader/Cache/CacheMigration.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/ShaderProgram.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs, Ryujinx.Graphics.Shader/Translation/TranslatorContext.cs
This is just some refactoring that simplifies how the "Vertex A" shaders (that needs to be combined with "Vertex B" shaders) are handled. The shader translator no longer has an additional overload to create a translator context for "Vertex A". Instead, the caller will call `CreateContext` twice, once for "Vertex B" and then for "Vertex A", and pass "Vertex A" as argument to the `Translate` method, allowing the two to be combined.
Also renamed some instances of "transformation feedback" to "transform feedback", since thats how it is called everywhere else.
Should not change behavior.
=> Simplify handling of shader vertex A

ARMeilleure/CodeGen/X86/CodeGenerator.cs, ARMeilleure/CodeGen/X86/PreAllocator.cs, ARMeilleure/Translation/PTC/Ptc.cs
Currently, the integer add instruction requires 4 registers to take place. By using LEA, we can effectively perform the same working using 3 registers, reducing memory spills and improving translation efficiency.
=> Optimization | Modify Add (Integer) Instruction to use LEA instead.

Ryujinx.Common/Configuration/ConfigurationFileFormat.cs, Ryujinx/Program.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade
I've also changed the code that write the config to disk to use the `FileOptions.WriteThrough` flag to write to disk immediately to decrease the chances of corruption
=> Load default config when an invalid config is found

global.json
This life changing feature allows the use of dotnet sdk 5.0.XXX rather than locking it to 5.0.100
=> Edit the global.json to allow the use of dotnet sdk 5.0.XXX

Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineKeyboardRequest.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineKeyboardResponse.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineKeyboardState.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardAppear.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardCalc.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardCustomizeDic.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardDictSet.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardInitialize.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardUserWord.cs
This PR, together with #1945, fixes keyboard soft-locking issues that some players are having in MHGU. It also fixes a bug when creating a character in Dark Souls Remastered, where a second attempt to input the name, if it is smaller than the first one, will crash the game. Finally it implements a new keyboard request used by MHR that otherwise appears as an error in the log.
The particular reason some users have problems in MHGU seems to be related with a save game migrated from Switch or a different version of Monster Hunter, changing the messages exchanged with the applet with some weird ones. A save file kindly provided by a user on Discord happens to manifest the issue, if it ever need to be reproduced again.
A special thanks for Discord user plaisi for the testing and feedback. …
=> Improve inline keyboard compatibility

Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs, Ryujinx.Graphics.Nvdec.Vp9/Decoder.cs, Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs, Ryujinx.Graphics.Nvdec.Vp9/TileBuffer.cs, Ryujinx.Graphics.Nvdec.Vp9/TileWorkerData.cs, Ryujinx.Graphics.Nvdec.Vp9/Types/Vp9Common.cs
This adds some optimisations to the VP9 decoder:
- Support multithreaded tile decoding. Improves speed by decoding multiple tiles in parallel, on separate CPU cores.
- Add `SkipLocalsInit` attribute to several inverse transform functions with stackallocs. Gives a minor performance improvement by avoiding zeroing the stack.
Most of the benefit comes from the multithreaded decoding. I had an speedup of about 2.5x decoding 1080p videos here (measured with standalone decoding, it is likely lower on the emulator). I would expect similar improvements on other CPUs with more than 6 cores.
**Some technical notes:**
Due to the way how the work is distributed, uneven thread counts does not yield much improvement. For example, a thread count of 2 and a thread count of 3 will give pretty much the …
=> Enable multithreaded VP9 decoding

Ryujinx.HLE/HOS/Services/Prepo/IPrepoService.cs, Ryujinx.HLE/HOS/Services/Prepo/ResultCode.cs, Ryujinx.HLE/HOS/Services/Prepo/Types/PrepoServicePermissionLevel.cs
This PR implement `GetSystemSessionId` of prepo service accordingly to RE.
During my research I've pointed out what the result code `90` is and where it's used in our actual implementation. So I've added it with some missing services too.
This should let "Super Mario 3D World + Bowser's Fury" run without `Ignore Missing Services` enabled. 
Thanks to Ga1act1c from our Discord for let us know the issue.
=> prepo: Implement GetSystemSessionId and add perms

Ryujinx.Common/Configuration/ConfigurationFileFormat.cs, Ryujinx.Common/Configuration/ConfigurationState.cs, Ryujinx/Config.json, Ryujinx/Ui/GLRenderer.cs, Ryujinx/Ui/Windows/SettingsWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.glade, Ryujinx/_schema.json
Closes #1508 
This adds an option on General Settings,  on by default, that when enabled the mouse cursor will automatically hide if it's idle on the game space (windowed or full screen) for more than 8 seconds and recover it once it's moved again.
Before:
After:
Note: Show "Confirm Exit" Dialog is moved on the second screenshot because it should have had position 2 on the SettingsWindow.glade file but it had 1 instead (which belongs to Check for Updates on Launch)
The way this works is pretty simple:
- A timer runs for 8 seconds (8000 msec)
- When it ticks an event fires and the cursor is changed to Gdk's BlankCursor
- Every time the mouse is moved the event that checks that fires, the timer is reset and the cursor gets unset
P.S. The first iteration of the code set the cursor used …
=> Hide Cursor On Idle

ARMeilleure/Instructions/InstEmitMemoryHelper.cs, ARMeilleure/Translation/PTC/Ptc.cs, Ryujinx.Cpu/MemoryManager.cs
Fix a regression introduced on #1987 due to the read/write flags being inverted.
It is not possible to track memory writes without also tracking reads, but tracking reads without tracking writes is possible. The previous code assumed the opposite, which lead to it taking the slow path for memory access when it shouldn't.
=> Fix memory tracking performance regression

Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs
This PR fix an issue introduced on last IPC rewrite PRs where some returned buffer size have to be explicit now.
GetFirmwareVersion/GetFirmwareVersion2 missed this and could crashes some homebrew because libnx have to check the firmware version to allow some call usage (with `hosversionBefore()`).
=> settings: Fix returned buffer size of GetFirmwareVersion

Ryujinx.HLE/HOS/Services/Nifm/StaticService/IGeneralService.cs
This PR fix an issue introduced on last IPC rewrite PRs where some returned buffer size have to be explicit now.
`GetClientId` without an explicit buffer size returns some garbage data to the guest and then `nifm` service crashes because of a wrong ClientId.
Horizon Chase Turbo and Doom regression are fixed.  (Probably some other games too)
=> nifm: Fix returned buffer size of GetClientId

Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/ModLoader.cs, Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
This approach should work fine assuming games behave properly and don't spam `OpenDataStorageByDataId`.
Slow path is only hit when mods are detected.
=> Allow modding AddOnContent RomFS

ARMeilleure/Decoders/OpCodeTable.cs, ARMeilleure/Instructions/InstEmitSimdArithmetic.cs, ARMeilleure/Instructions/InstEmitSimdArithmetic32.cs, ARMeilleure/Instructions/InstEmitSimdHelper.cs, ARMeilleure/Instructions/InstName.cs, ARMeilleure/Instructions/SoftFallback.cs, ARMeilleure/Translation/Delegates.cs, ARMeilleure/Translation/PTC/Ptc.cs, Ryujinx.Tests/Cpu/CpuTestSimd32.cs
Implement `VCNT.8` from the existing `CNT` impl (`Cnt_V` in code).
Tests were also adapted from `Cnt_V`. Both intrinsic and soft-fallback paths succeeded locally.
Closes #1825 
~Will increment PTC version once github tests are successful.~
=> Implement VCNT instruction

Ryujinx/Modules/Updater/UpdateDialog.cs, Ryujinx/Modules/Updater/Updater.cs
Use multiple threads to download different chunks of an update simultaneously. This may reduce download times significantly (depending on your connection / bandwidth limitations).
For example: on my 50mbps connection, download times (windows build) have been reduced from 20s to 10s. Your results will vary.
=> UI: Multithreaded Updater

Ryujinx/Modules/Updater/Updater.cs, Ryujinx/Program.cs, Ryujinx/Ui/MainWindow.cs
The current updater marks everything except `.log` files for deletion.
With this PR, it now deletes only select directories (Windows only, Linux and MacOS don't have these) and all top-level files in the base directory. So, if there's other directories (like portable or custom), their contents will be spared.
Also used this opportunity to log errors from the updater (to easily identify future issues).
This PR does not claim to solve #1594 100%. Only to unblock #1885. So, I have not added an auto-close. 
I do think this is enough for most people, but feel free to close this if it isn't the way to go.
=> Pacify updater

Ryujinx/Modules/Updater/UpdateDialog.cs, Ryujinx/Modules/Updater/Updater.cs
The updater currently sets the binary's (the _"Ryujinx"_ file on Unix) permissions to executable (for the current user) only when the Yes button is clicked on the restart dialog, since the part of the code that performs this task is inside the _YesButton_Clicked_ void in _UpdateDialog.cs_, which means that if you click No, close the updater, kill Ryujinx, etc. you will get a permission denied error the next time you attempt to run it.
This pr moves the part responsible for setting this permission to _Updater.cs_ so it is run after the updater finishes and before the restart dialog.
While when you build Ryujinx the executable has -rwxr-xr-r (any user can execute it), the updater sets the permissions to -rwxr--r-- (only the current user can execute it), this wasn't changed.
_P.S. A white …
=> Fix updater breaking user execute permissions on Unix

Ryujinx.Cpu/MemoryManager.cs, Ryujinx.Memory/AddressSpaceManager.cs
Some address arithmetic used in `MemoryManager` are prone to overflow when the virtual address resides in the last page possible of a 64bit address. This causes, for instance, `IsRangeMapped` to return true even though the address is not mapped, which can lead to a bad logic and a crash.
This PR creates an overflow-safe way of counting pages for the affected functions and replaces the address-based loop in `IsRangeMapped` with page-based loop.
=> Fix virtual address overflow near ulong limit

.github/workflows/build.yml, .github/workflows/nightly_pr_comment.yml, Ryujinx/Modules/Updater/Updater.cs, Ryujinx/Ryujinx.csproj
This PR extends the build job by uploading artifacts for all PRs.
The version of those builds is set to ``1.0.0-<git_short_hash>`` and those builds have the updater explicitly disabled.
With this in place, we will be able to disable AppVeyor on PRs.
=> ci: Use Github artifacts for PRs

Ryujinx.Audio.Backends.SoundIo/SoundIoAudioBuffer.cs, Ryujinx.Audio.Backends.SoundIo/SoundIoHardwareDeviceSession.cs
This should fix weird crashes happening for some people with SoundIO.
It also is expected to improve performances a bit.
Fix #2062
=> Haydn: Make SoundIO session implementation lock-free

Ryujinx.Common/SystemInfo/LinuxSystemInfo.cs, Ryujinx.Common/SystemInfo/MacOSSystemInfo.cs, Ryujinx.Common/SystemInfo/SystemInfo.cs, Ryujinx.Common/SystemInfo/WindowsSystemInfo.cs, Ryujinx/Program.cs
A bit more care for the inconspicuous.
Added extra info to the current logs as they were basically free. (logical-core-count and available-mem-at-launch wherever possible)
- Extract CPU name from CPUID when supported.
- Linux: Robust parsing of procfs files
- Windows: Prefer native calls to WMI 
- Remove unnecessary virtual specifiers
For eg. on Windows, CPU WMI call took 1100ms vs CPUID 1.1ms (on my machine). So, Ryu starts up faster.
Untested on macOS (should work as usual). Others were tested but I'd appreciate more tests on different hardware.
=> Revise SystemInfo

Ryujinx.Cpu/MemoryManager.cs
This PR solves the regression introduced by #2044. As mentioned in the PR, altering the value of `va` breaks the `Tracking.VirtualMemoryEvent` call.
This PR was tested with Monster Hunter Rise DEMO as it is known to manifest the regression.
I also looked for similar regressions in `MemoryTracking` and `AddressSpaceManager`.
=> Fix regression in SignalMemoryTracking

Ryujinx.Cpu/Tracking/CpuRegionHandle.cs, Ryujinx.Graphics.GAL/ITexture.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, Ryujinx.Graphics.Gpu/Image/TextureDependency.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Graphics.Gpu/Image/TextureGroupHandle.cs, Ryujinx.Graphics.Gpu/Image/TextureInfo.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Memory/GpuRegionHandle.cs, Ryujinx.Graphics.OpenGL/Image/TextureBuffer.cs, Ryujinx.Graphics.OpenGL/Image/TextureCopy.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs, Ryujinx.Graphics.Texture/SizeCalculator.cs, Ryujinx.Graphics.Texture/SizeInfo.cs, Ryujinx.Memory/Tracking/IRegionHandle.cs, Ryujinx.Memory/Tracking/RegionHandle.cs
[![Download](https://img.shields.io/badge/Download-%232001-black?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAARCAMAAADjcdz2AAAAe1BMVEVHcEyai5T/XFEAyOr/XlQBxeUBxeX9X1YDxOT/X1UBxeX7XlQAyev7X1QCxeX4YVj+X1UBxeRtmqhnnKv+X1UBxOQCxeUBxOT/X1UAzvELwd8Lwd//VUj+X1U2r8fYbmoAx+j/V0r/X1UCxeb/YlcCzO3/Z1wC1vkC0fPqHM+tAAAAInRSTlMACoFJz879AwP89FBlFeA7o5IZLN+tvZPdFRw0WrZsaX1CnD5B2QAAAI1JREFUGNNNz1cOwyAQBNABO2DAVek9ARvn/icMxSD282k0mkUzyWXXwB93B0wrSxAQ0mSgIx0AwxLwi7WzAssJXmsxHxIQQng9C6FhIlT7LxzoBNXnTTsPYoN7+xhITISOW/uiihfgKhQ2CDtwJV0Egd7IvCNA+1vWPoPbgep4OpeJJn/qwY5ACfrZ/QHYMQ4WY6nIhQAAAABJRU5ErkJggg==&style=flat&labelColor=252a2f&color=f2f5f8)](https://w.ryujinx.org/dl/2001)
Our texture cache tries to make sense of a low level collection of textures iteratively as draws and copies come in and …
=> Texture Cache: "Texture Groups" and "Texture Dependencies"

Ryujinx/Ui/GLRenderer.cs
Both `DateTime.Now` and `ReactiveObject.get` (due to RW lock) are pretty heavy calls and are called from a sensitive location `UpdateFrame()` (runs every ~1ms and is responsible for handling input) which is already in a bad enough state.
There's loads of ways to combat that. With this PR, I have simplified the logic and moved the checks to `HandleScreenState()` which runs in the GUI thread.
=> Fix "Hide Cursor on Idle" inefficiency
