ARMeilleure/Translation/PTC/Ptc.cs, Ryujinx.Graphics.Gpu/GpuContext.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade
Both of them expose two events, one for state change and the other for progress which are consumed by `MainWindow`.
Both PTC and Shader Cache report progress events on a timer (currently 100ms).
This is because PTC/ShaderCache has (or eventually will have) parallel processing. So, it's not easy to serialize it per-change.
GUI changes and initial concept courtesy of @Joshi234 (credited changes) from #1946 which this supersedes.
=> Add progress reporting to PTC and Shader Cache

Ryujinx.HLE/HOS/Services/Time/IStaticServiceForGlue.cs
I happened to notice this when checking Ryu's IPC structures. After double checking with RE it seems the current check is incorrect so use the correct member to fix that.
=> Fix SetStandardSteadyClockInternalOffset permission check

Ryujinx.Cpu/MemoryManager.cs, Ryujinx.Cpu/Tracking/CpuRegionHandle.cs, Ryujinx.Graphics.Gpu/Image/Pool.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Memory/Range/MultiRange.cs, Ryujinx.Memory/Tracking/MemoryTracking.cs, Ryujinx.Memory/Tracking/RegionHandle.cs, Ryujinx.Memory/Tracking/VirtualRegion.cs
- Fixed a memory tracking bug that would set protection on empty PTEs. (causes some buffer tracking crashes)
- When a texture's memory is (partially) unmapped, all pool references are forcibly removed and the texture must be rediscovered to draw with it. This will also force the texture discovery to always compare the texture's range for a match.
- RegionHandles now know if they are unmapped, and automatically unset their dirty flag when unmapped.
- Partial texture sync now loads only the region of texture that has been modified. Unmapped memory tracking handles cause dirty flags for a texture group handle to be ignored.
Buffers can try to sync memory that's unmapped if the size is too large, which it usually is for UE4 games, as it seems to pass in a large uniform buffer size no matter …
=> Improve handling for unmapped GPU resources

Ryujinx.Graphics.OpenGL/Pipeline.cs
For OpenGL, we use RGBA textures as BGRA and swap the components on draw, write, copy etc. However, we forgot to swap the component mask, so when a texture meant to draw to only "blue", it ended up drawing to only "red" and vice versa.
On its own, this doesn't do much as far as I know. Combined with better bindless texture handling, it will lead to fixing shadows in BD2's battles.
=> Flip component mask if target is BGRA.

Ryujinx.Graphics.Gpu/Engine/Compute.cs, Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TextureDescriptor.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, Ryujinx.Graphics.Gpu/Memory/BufferTextureBinding.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.OpenGL/Image/TextureBuffer.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/TextureUsageFlags.cs
Fixes a number of issues with buffer textures:
- Reworked Buffer Textures to create their buffers in the TextureManager, then bind them with the BufferManager later.
- Fixes an issue where a buffer texture's buffer could be invalidated after it is bound, but before use.
- Fixed width unpacking for large buffer textures. The width is now 32-bit rather than 16.
- Force buffer textures to be rebound whenever any buffer is created, as using the handle id wasn't reliable, and the cost of binding isn't too high.
Fixes vertex explosions and flickering animations in UE4 games. May affect games that use ImageStore, as now those textures are flushed on read/write.
Before:
(maybe one day I'll open the game on master to get a better comparison shot for this, but you get the gist)
After:
=> Improve Buffer Textures and flush Image Stores 

Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs
This allows bindless handles to be found for image/texture instructions with predicates, when the assignment of the texture handle is within the same predicate. This is a little rough, since it's made to target a specific pattern.
If the handle source is a PhiNode rather than an Operation, we try to find which phi source is relevant to the instruction. This source is the latest source block that has a branching condition matching the texture access block.
This seems to cover the remaining bindless handles that compilers seem to be creating as an optimization. Note that this is more likely to make a shader create too many samplers, and fail to link.
The only way to solve the issue with creating too many samplers, is either to play bindless textures straight and support bindless on them, or …
=> Traverse PhiNodes for Bindless Elimination

Ryujinx.Graphics.Texture/LayoutConverter.cs
Fixes a possible crash when width is greater than stride, which can happen due to alignment when copying textures with the copy buffer method.
Fixes `System.ArgumentOutOfRangeException` in `ConvertLinearStridedToLinear` called from `CopyBuffer`. May fix another issue when outStride < stride.
=> Fix lineSize for LinearStrided -> Linear conversion

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/LibraryAppletCreator/ILibraryAppletAccessor.cs
Fix the exception saying "Out of handles" being throw for games that tries to create an applet multiple times, a problem likely introduced with #1458.
=> Close ILibraryAppletAccessor handles on disposal

Ryujinx/Ryujinx.csproj, Ryujinx/alsoft.ini
This enforce speaker mode to avoid weird audio quality reduction with
output considered as headphones by Windows (It applies a HRTF or crossfeed filter supposed to improve audio quality, might be a bug on their end)
=> Override openal-soft configuration

Ryujinx.Audio/Renderer/Device/VirtualDeviceSessionRegistry.cs
Some games read the active device name, and decide to ruin the audio if it's the internal speakers. This PR changes it to always report the TV output device. This may also get 5.1 out of a few more games.
Should be tested across a variety of engines in handheld mode, in case they don't appreciate reporting a TV output when in handheld mode.
Fixes awful tinny audio in Pokemon Sword.
=> Report active audio device as TV, rather than internal speakers.

Ryujinx.Common/Configuration/AppDataManager.cs, Ryujinx.HLE/FileSystem/VirtualFileSystem.cs, Ryujinx/Modules/Updater/Updater.cs, Ryujinx/Program.cs
Users seem to have trouble using the "custom data directory" feature for portability. This implements an extra (arguably redundant) way to achieve it. Creating a `portable` dir in the exe base directory now activates portable mode.
This code prioritizes Custom Data argument -> Portable dir -> User Profile.
**EDIT:** Removed first run dialog.
**NOTE1:** I was unable to figure out a way to stop GTK from creating a 'recently-used.xbel' file in user profiles used for Recent items in file dialogs. Besides that, the application should be fully portable.
**NOTE2:** It's still a bit jarring to find the portable directory among the plethora of files and folders. This would have to be resolved in the future.
Closes #1879
Tested on Windows. Should work on others but please do test.
~__I highly …
=> Implement friendlier portable mode

Ryujinx.HLE/HOS/Applets/Error/ApplicationErrorArg.cs, Ryujinx.HLE/HOS/Applets/Error/ErrorApplet.cs
This PR implement `ApplicationErrorArg` to the Error Applet. It's used by the guest to throw some specific error messages.
The code was done for (and merged) LDN2 build since long time ago and have been tested a bunch of times because of that! In a way to reduce the differences between LDN and master build it's fine to add it to master.
=> ErrorApplet: Implement ApplicationErrorArg

Ryujinx.Graphics.Gpu/Constants.cs, Ryujinx.Graphics.Gpu/Engine/MethodCopyBuffer.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs
Fixes an issue where small or width-aligned (rather than byte aligned) textures would fail to create a view of existing data. Creates a copy dependency as size change may be risky.
- View layout compatibility is now determined by the stride shifted by the level, rather than a stride caculated from the level's width.
- Linear textures are considered copy compatible when they have matching stride.
Caused missing lens flare in Mario Kart 8 Deluxe and Splatoon 2.
Fixes an issue where Cross Code would display a black screen.
=> Improve linear texture compatibility rules

ARMeilleure/Translation/PTC/Ptc.cs, ARMeilleure/Translation/PTC/PtcLoadingState.cs, Ryujinx.Graphics.Gpu/GpuContext.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCacheState.cs, Ryujinx/Ui/MainWindow.cs
There were quite a few issues (non-critical or mostly invisible) in my previous code which this PR fixes. My apologies for having to redesign this.
- Reduced the scope of `AutoResetEvent`s used for progress logging threads. It was wasteful to maintain an active `WaitHandle` throughout the emulation session.
- Removed uses of `ThreadPool.QueueUserWorkItem()`. While their placement is calculated, loading is long sometimes and `ThreadPool` might be used internally in other places. So, opted for an explicit low priority `Thread` with a descriptive name. With this and other fixes (below), updates are now twice as frequent with no impact.
- Changed progress reporting to a single event. This removes the awkward boilerplate code on handler side.
- Inconsistencies fixed- NaN/infs, off-by-1 …
=> Fix progress reporting

Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs, Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Proxy/DnsBlacklist.cs, Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfo4.cs, Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfoSerializedHeader.cs, Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/SfdnsresContants.cs
This PR is a big cleanup to our current implementation of `sfdnsres` service.
Additionnaly to that, some calls and fixes have been done by @Thog (PRd with approval, thanks to her).
- Implementation of `GetAddrInfoRequest` (Fixes #637).
- Partial implementation of `GetHostByNameRequestWithOptions`, `GetHostByAddrRequestWithOptions` and `GetAddrInfoRequestWithOptions` (Fixes #642, Fixes #1233).
A DNS Blacklist have been added by @riperiperi (PRd with approval, thanks to him) which is currently used in LDN build, in a way to reduces code differences between the LDN build and master.
Now a lot of games are playable or are blocked to the menu because it needs online service:
Supersedes #1909
Co-Authored-By: Mary <1760003+Thog@users.noreply.github.com>
Co-Authored-By: riperiperi …
=> sfdnsres: Cleanup service and implements some calls

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs, Ryujinx.HLE/HOS/Services/Ectx/IReaderForSystem.cs, Ryujinx.HLE/HOS/Services/Ectx/IWriterForApplication.cs, Ryujinx.HLE/HOS/Services/Ectx/IWriterForSystem.cs
This PR implements `am` service call `SetRequestExitToLibraryAppletAtExecuteNextProgramEnabled` (closes #2028) accordingly to RE and adds placeholder for the `ectx` services. All were added in 11.0.0+ firmware and are needed to boots games (or updated games) which needs this version.
Some games are now playable/bootable:
=> am/ectx: Implement SetRequestExitToLibraryAppletAtExecuteNextProgramEnabled and add service placeholder

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/Caps/CaptureManager.cs, Ryujinx.HLE/HOS/Services/Caps/IAlbumApplicationService.cs, Ryujinx.HLE/HOS/Services/Caps/IAlbumControlService.cs, Ryujinx.HLE/HOS/Services/Caps/IScreenShotApplicationService.cs, Ryujinx.HLE/HOS/Services/Caps/ResultCode.cs, Ryujinx.HLE/HOS/Services/Caps/Types/AlbumFileDateTime.cs, Ryujinx.HLE/HOS/Services/Caps/Types/AlbumImageOrientation.cs, Ryujinx.HLE/HOS/Services/Caps/Types/AlbumStorage.cs, Ryujinx.HLE/HOS/Services/Caps/Types/ApplicationAlbumEntry.cs, Ryujinx.HLE/HOS/Services/Caps/Types/ContentType.cs, Ryujinx.HLE/HOS/Services/Caps/Types/ScreenShotAttribute.cs, Ryujinx.HLE/Ryujinx.HLE.csproj
This PR implement (accordingly to RE):
- `caps:u IAlbumApplicationService (32) SetShimLibraryVersion`
- `caps:c IAlbumControlService (33) SetShimLibraryVersion`
- `caps:su IScreenShotApplicationService (32) SetShimLibraryVersion`
- `caps:su IScreenShotApplicationService (203/205/210) SaveScreenShotEx0/SaveScreenShotEx1/SaveScreenShotEx2`
ImageSharp is used to save the raw screenshot data to a JPG file following what the service does.
All screenshots are saved in: `%AppData%\Ryujinx\sdcard\Nintendo\Album` folder. (as example a screenshot filepath could be `%AppData%\Ryujinx\sdcard\Nintendo\Album\2021\03\26\2021032601020300-0123456789ABCDEF0123456789ABCDEF.jpg`
This is needed by Animal Crossing: New Horizon using the game camera where screenshots looks like this:
And this is needed in …
=> caps: Implement SaveScreenShot calls and cleanup

README.md, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs, Ryujinx/Ui/Windows/AboutWindow.Designer.cs, Ryujinx/Ui/Windows/AboutWindow.cs
This PR adds a properly credit to AmiiboAPI which is used in our Amiibo emulation in the Readme and in the about window.
I've changed a wrong warning code added in a recent PR too (there is no more warning now).
=> misc: Add credit to AmiiboAPI properly and fix a wrong warning code

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitAlu.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs
This fixes a bug where the Z/N flags would be set to a incorrect value if the destination register of some shader instructions are RZ. This was happening because it was comparing the RZ register value, rather than the actual operation result.
While I was at it, I also fixed a bug on pixel shaders with calls where it would set the output pixel values before every return, rather than just on the main function.
I found the first bug while looking at one of the Monster Hunter Rise compute shaders, but I did not notice any improvement after fixing this.
=> Fix ZN flags set for shader instructions using RZ.CC dest

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/LibraryAppletCreator/ILibraryAppletAccessor.cs
This PR stub `ILibraryAppletAccessor (20) RequestExit` call which is needed by Monster Hunter Rise when you press "Private Policy" at the beginning.
The game try to run the `WebApplet` which is already partially stubbed, then call `RequestExit` to know when the applet exits. If the call does nothing, the game just hang forever. If you signals the event, you can interracts with the menu again.
Closes #2016
=> am: Stub ILibraryAppletAccessor RequestExit

Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Proxy/DnsBlacklist.cs
Very simple change. Hostname resolution IPC calls don't seem to have any filtering on the input name so, this PR makes the DNS blacklist case-insensitive to catch them properly. Also added a few extra perf-oriented options to them- `ExplicitCapture` as we only use `IsMatch`, `Compiled` as applications can spam it.
A quick test using a single regex with alternation, something like-
```csharp
Regex blockedHosts = new Regex(string.Join('|', patternsArray), options);
```
yielded no clear winner with a small sample of tests I tried (complex state machine or more backtracking?)
As that's more error-prone and confusing anyway, decided not to use it. If you still prefer a single regex, let me know.
=> Patch up DNS Blacklist

Ryujinx.HLE/HOS/ModLoader.cs, Ryujinx.HLE/HOS/TamperMachine.cs
Discord user mageven reported two issues with the Tamper Machine that are addressed in this PR:
- The first one is a crash when using unpacked games, caused by a missing `return` statement.
- The second one was an inconsistency between the sleep duration in Tamper Machine (1ms) versus Atmosphere (~83.33ms). Time sensitive cheats (if any) may behave differently.
The first issue was reproduced and tested unpacking a game and running it.
For the second issue, I measured the average time between sleeps in the Tamper Machine and it's around 83.7~83.9ms on Windows/Release, even with multiple cheats running, so the timing is now between spec and no significant drift from the `Sleep` function itself was observed.
I re-tested the cheats from my previous PR #1928, those being:
- 60fps mod in MHGU
- …
=> Fix Tamper Machine crash and timings

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs
`SetRenderTargets` might be called on the backend with a texture that was already "released". This happens because the active render targets are stored on the `TextureManager`, but this never increments/decrements the reference count, so those textures might be deleted if they fall out of the auto delete cache. This changes increments and decrements the reference count to prevent that from happening.
Found this while working on Vulkan (using a freed texture would cause a crash), not sure if its causing anything spooky on the OpenGL backend (I guess its less likely to crash there since textures are reused).
Also moved `SetRenderTargetDepthStencil` close to the color one, as the 2 are related and puting them together makes the code easier to read imo.
=> Hold reference for render targets in use

ARMeilleure/IntermediateRepresentation/Operand.cs, ARMeilleure/Translation/SsaConstruction.cs
SSA construction was allocating an array for each basic block twice, it re-uses a single array instead now. This also removes `DefMap`'s dependency on `Register` which makes extending SSA construction to handle `LocalVariable` easier.
Also mark `Operand.GetRegister()` as aggressive inlining, because it wasn't getting inlined.
=> Reduce allocation during SSA construction

ARMeilleure/Instructions/InstEmitFlowHelper.cs, ARMeilleure/Translation/PTC/Ptc.cs
Hoist `StoreToContext` in dynamic branch fast & slow paths out into their predecessor. Reduces register pressure, code size and compile time a little bit because we're throwing less stuff down the pipeline. Sample [diff](https://www.diffchecker.com/17Or5Uog).
Some thing similar can be done with `LoadFromContext` emitted for dynamic calls, by sinking them into the successor. We need to store the return address of the calls (fast & slow paths) into a single variable and apply the call guard check on it. This is essentially tail merging and could be applied to tail continues as well. However we get limited by the `EmitterContext` and `SsaConstruction` because local variables are assumed to be in SSA early on, so they cannot participate in phi nodes.
=> Improve `StoreToContext` emission

Ryujinx.Graphics.OpenGL/HwCapabilities.cs, Ryujinx.Graphics.OpenGL/Sync.cs
One particular game seemed to slow down due to flushing commands on sync creation, so this PR disables it on the platforms that don't seem to need it, such as NVIDIA's proprietary drivers and Mesa. My guess is that the NVIDIA driver is always flushing commands anyways, and telling it to do so manually slows it down.
=> Only flush commands when creating sync on Intel/AMD (windows)

ARMeilleure/CodeGen/X86/PreAllocator.cs
There is a bug with the CRC32 intrinsic were the JIT does not force a copy when a constant value is used as input for this instruction. On debug, this will cause an assert as this specific instruction does not support immediate operands on x86, and in release, it will just generate invalid code. This fixes the issue by forcing the value to be copied to a register, and then replacing the operation input with the register.
Fixes #1457
A user ("yunny") reported the assert firing while rebuilding PPTC cache for Monster Hunter Rise, I have reproduced the issue and verified that the assert no longer fires with the fix, however, I also did not notice any visible improvement on the game.
I also ran all CRC32 tests locally in both LCQ and HCQ modes, and they all pass.
=> (CPU) Fix CRC32 instruction when constant values are used as input

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs, Ryujinx.HLE/HOS/Services/SurfaceFlinger/SurfaceFlinger.cs, Ryujinx.HLE/HOS/Services/Vi/RootService/ApplicationDisplayService/IManagerDisplayService.cs, Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
As the title say.
I also took the liberty of changing the logic on how we select the current layer being rendered to make it more explicit when opening and creating layers.
NOTE: Found by @AcK77
=> Surface Flinger: Fix an oversight when closing a layer

Ryujinx.HLE/HOS/Services/Nifm/StaticService/IGeneralService.cs, Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/DnsSetting.cs, Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/IpSettingData.cs, Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/NetworkProfileData.cs, Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/ProxySetting.cs, Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/WirelessSettingData.cs, Ryujinx.HLE/HOS/Services/Sockets/Nsd/IManager.cs, Ryujinx.HLE/HOS/Services/Sockets/Nsd/Manager/FqdnResolver.cs, Ryujinx.HLE/HOS/Services/Ssl/ISslService.cs, Ryujinx.HLE/HOS/Services/Ssl/SslService/ISslConnection.cs, Ryujinx.HLE/HOS/Services/Ssl/SslService/ISslContext.cs, Ryujinx.HLE/HOS/Services/Ssl/Types/CertificateFormat.cs, Ryujinx.HLE/HOS/Services/Ssl/Types/InterfaceVersion.cs, Ryujinx.HLE/HOS/Services/Ssl/Types/IoMode.cs, Ryujinx.HLE/HOS/Services/Ssl/Types/OptionType.cs, Ryujinx.HLE/HOS/Services/Ssl/Types/SessionCacheMode.cs, Ryujinx.HLE/HOS/Services/Ssl/Types/SslVersion.cs, Ryujinx.HLE/HOS/Services/Ssl/Types/VerifyOption.cs
This PR implement the `nifm` call GetCurrentNetworkProfile (REd by @Thog, thanks to her) and stubs some `ssl` services calls, some details:
- `nifm` `IGeneralService` `GetCurrentNetworkProfile` is implemented (fixes #643) and now blocked games boot further.
- `nifm` `GetLocalInterface()` helper and `DnsSetting` struct have been fixed to return the right values.
- `ssl` `ISslService` have been cleaned up.
- `ssl` `ISslContext` have been cleaned up, `CreateConnection` and `ImportClientPki` have been stubbed (fixes #1289).
- `ssl` `ISslConnection` is partially stubbed, which make some games playable, see the attached screenshots.
- `nsd` `IManager` `Resolve` and `ResolveEx` have been fixed using the right buffer type.
All those changes makes some games boot further and some others playable:
=> nifm/ssl: Implement GetCurrentNetworkProfile and stub Ssl Service

Ryujinx.Graphics.OpenGL/Image/ITextureInfo.cs, Ryujinx.Graphics.OpenGL/Image/TextureBase.cs, Ryujinx.Graphics.OpenGL/Image/TextureCopy.cs, Ryujinx.Graphics.OpenGL/Image/TextureStorage.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs
When doing sub-image copies with `glCopyImageSubData` on Intel, the driver seems to ignore the specified `dstLayer` for some reason (and also `dstLevel` I'm guessing), and always copies the data to the base layer. This problem doesn't happens when passing the storage handle rather than the view handle, so to fix this, the change adds a special path for intel, that passes storage handles rather than view handles, and adds the view base layer and level to the source and destination layer and level. In theory, this should work on all vendors without any performance penalty, but I decided to play safe here and only do this for Intel, to avoid the risk of breaking it for other vendors.
Some comparison screenshots:
Before:
After:
**Note:** This only affects Intel iGPUs, other vendors are not …
=> Fix sub-image copies on intel GPUs

Ryujinx.Common/Configuration/ConfigurationState.cs, Ryujinx.Common/Logging/LogClass.cs, Ryujinx.Common/ReactiveObject.cs, Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/Switch.cs, Ryujinx/Ui/GLRenderer.cs, Ryujinx/Ui/Windows/SettingsWindow.cs
This PR aims to expose more user changeable information in the logs, mainly so that the upcoming Discord bot (https://github.com/Ryujinx/ryuko-ng/pull/3) can use this information for analysis.
This also simplifies the hotkey states logging from #1942 (which I have now removed), as it uses the already recorded configuration states and leverages the already existing `ReactiveObject.cs` change state.
Both UI menu item changes and hotkey changes are logged in real time once settings are saved.
New information includes:
- File Logging Enabled
- File Integrity Checks Enabled
- File Global Access Log Mode
- Resolution scale
- Resolution scale custom
- Aspect Ratio
- Anisotrophic Filtering
- Docked/Undocked
- PPTC enabled/disabled
- Shader Cache enabled/disabled
- V-Sync enabled/disabled
- Audio …
=> Improves logging to console.

Ryujinx.HLE/HOS/Services/Sockets/Nsd/IManager.cs, Ryujinx.HLE/HOS/Services/Sockets/Nsd/Manager/FqdnResolver.cs, Ryujinx.HLE/HOS/Services/Ssl/SslService/ISslConnection.cs, Ryujinx.HLE/HOS/Services/Ssl/SslService/ISslContext.cs
This PR fixes a little regression introduced in #2186 at the `IManage` `Resolve`/`ResolveEx` calls, there was an overflow caused by added an empty char at the end of a not trimmed input buffer and then write the result in a too small output buffer. (https://github.com/Ryujinx/Ryujinx-Games-List/issues?q=is%3Aissue+is%3Aopen+nsd)
Additionnally to that, I've stubbed `ISslContext` `GetConnectionCount` which fixes #2206 and I've fixed a spamming of `ISslConnection` `Write` by returning a transferred size.
Some game are now playable:
=> nsd/ssl: Fix Resolve/ResolveEx and stub GetConnectionCount

Ryujinx.Input.SDL2/SDL2Driver.cs
We actually don't need to init sensors or haptic to get motion or rumble working on game controllers.
This fix a group policy issue on some Windows 10 Pro when trying to init the SDL2 sensors APIs.
=> Miria: Fix Group Policy related crashes

Ryujinx.HLE/HOS/Applets/Controller/ControllerApplet.cs, Ryujinx.HLE/HOS/Applets/PlayerSelect/PlayerSelectApplet.cs, Ryujinx.HLE/HOS/Horizon.cs
This fixes controller applet related in Mario Kart 8 Deluxe, in 2-4 player mode or when opening the applet in character select.
Not sure if this should be added to other foreground applets. If anyone knows of any other games with applet related softlocks, speak now or forever hold your peace.
=> Return focus from controller applet after completion

Ryujinx.Graphics.OpenGL/Image/ITextureInfo.cs, Ryujinx.Graphics.OpenGL/Image/TextureCopy.cs, Ryujinx.Graphics.OpenGL/Image/TextureStorage.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs
The texture target must be taken from the storage rather than the view, when using the storage handle for the copy.
Screenshots with workaround artificially enabled on NVIDIA.
Before:
After:
Related to https://github.com/Ryujinx/Ryujinx/pull/2213 , but mesa should probably be explicitly detected to disable other workarounds anyways (specifically the view format one).
=> Fix intel view copy workaround.

Ryujinx.Audio/Renderer/Dsp/Effect/DelayLine.cs
This allows to handle an OOB with delay lines when DelayTimeMax = 0.
On real hardware, it will end up reading garbage at the given user work buffer address.
As we do not use those buffers and allocate them ourself for simplicy, this could possibly cause a crash.
Proposed solution here is to only increase the size of _workBuffer by one like what is done in DelayLineReverb3d already.
This fixes FEZ. (Ryujinx/Ryujinx-Games-List#3526)
=> Amadeus: Allow out of bound read on empty delay lines

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/GlobalToStorage.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/Optimizer.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/Utils.cs
The emulator currently has a optimisation pass that tries to pattern match global memory access patterns with a base address from a constant buffer. This has the same problem that bindless elimination had before #2089. Since the pass couldn't see beyond phi nodes. anything with control flow divergence would make it stop looking and give up, which would in turn result in the slow fallback path being used for the global memory access. This change uses the same trick used on bindless elimination to enable the pass to see through phi nodes and catch more cases. This allows the elimination to match, for example, cases where the global memory access and the base address are on different `if` blocks.
**Potential improvements:**
- Reduced code size.
- May improve compile times as a result.
- …
=> Improve shader global memory to storage pass

Ryujinx.Audio/Renderer/Dsp/Command/DelayCommand.cs
This adds missing parenthesis around low pass z computation.
This fixes FEZ audio gain issues inside rooms. (Ryujinx/Ryujinx-Games-List#3526)
=> Amadeus: Fix low pass base gain related issues on delay effect in mono

ARMeilleure/Common/Counter.cs, ARMeilleure/Common/EntryTable.cs, ARMeilleure/Decoders/Block.cs, ARMeilleure/Decoders/Optimizations/TailCallRemover.cs, ARMeilleure/Instructions/InstEmitFlowHelper.cs, ARMeilleure/Instructions/NativeInterface.cs, ARMeilleure/IntermediateRepresentation/OperandHelper.cs, ARMeilleure/Translation/ArmEmitterContext.cs, ARMeilleure/Translation/Delegates.cs, ARMeilleure/Translation/PTC/Ptc.cs, ARMeilleure/Translation/TranslatedFunction.cs, ARMeilleure/Translation/Translator.cs
Contributes to #2158.
* Add re-usable structures to do on translation counting ~(might want to make `Counter` a generic though)~.
* Add on translation call counting.
* Change call counting behavior to be associated with nodes (i.e head of translations) instead of edges (i.e out of translation branches). Before if all incoming branches to a translation was not hinted for rejit, it would never tier up even though it could be hot.
* **Pros**: Improves hot code discovery.
* **Cons**: Increase in code size. -- Because we may discover more code to rejit, and the decoder may produce a far larger output for HCQ than for LCQ.
PPTC integration is done this way for the sake of simplicity and because it allows `EntryTable` to be dynamic/expandable. ~although it currently is not.~
Call counting is not …
=> Add inlined on translation call counting

Ryujinx.Graphics.Gpu/Engine/Methods.cs, Ryujinx.Graphics.Gpu/Shader/Cache/Definition/HostShaderCacheEntry.cs, Ryujinx.Graphics.Gpu/Shader/Cache/Definition/HostShaderCacheEntryHeader.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitMemory.cs, Ryujinx.Graphics.Shader/ShaderProgramInfo.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgramContext.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgramInfo.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, Ryujinx.Graphics.Shader/Translation/FeatureFlags.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
This changes clip distances to only be enabled if they are actually written to on the vertex shader, since otherwise the results are undefined according to the spec.
No changes were observed on NVIDIA, but on Intel, this fixes flashing triangles on games that uses custom clip distances (most first party games).
Before:
After:
Should be tested on all games that were fixed by the original implementation: https://github.com/Ryujinx/Ryujinx/pull/1118
(I was not able to reproduce the bug on Super Mario Odyssey even without clip distances).
I also changed the way how InstanceId use is reported slightly, it now uses `FeatureFlags` to be consistent with how the other built-in uses are reported.
=> Only enable clip distance if written to on shader

Ryujinx.Input/HLE/NpadManager.cs
This fix a possible crash with raw keyboard input since Miria.
I took the liberty to move the the keyboard update to avoid possible duplicate update if we end up having two keyboards in use.
=> Miria: Do not try to query keyboard input when controller isn't set

Ryujinx.HLE/HOS/Services/Account/Acc/AccountManager.cs, Ryujinx.HLE/HOS/Services/Account/Acc/AccountSaveDataManager.cs, Ryujinx.HLE/HOS/Services/Account/Acc/Types/UserProfile.cs, Ryujinx.HLE/HOS/Services/Caps/CaptureManager.cs, Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs, Ryujinx/Program.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade, Ryujinx/Ui/Widgets/GameTableContextMenu.cs, Ryujinx/Ui/Widgets/GtkDialog.cs, Ryujinx/Ui/Widgets/GtkInputDialog.cs, Ryujinx/Ui/Windows/AvatarWindow.cs, Ryujinx/Ui/Windows/UserProfilesManagerWindow.Designer.cs, Ryujinx/Ui/Windows/UserProfilesManagerWindow.cs
This PR adds the support of Custom User Profiles (Patreon goal) which can be selected through a new menu entry `Options > Manage User Profiles`.
- `RyuPlayer` is the default user, which can't be deleted, because users are linked with save game files, if we remove it, all users using previous version of Ryujinx will loose save files. In this way you could be able to move your old save files to a new profile if you want to, or you can just rename and change the image profile of the default one.
- Select a user is done by double click on it or with keyboard arrows and enter key, the selected one is always on top (multiple profiles selection is still unsupported for now).
- `Manage User Profiles` is disabled while a game is running because of this previous point. (You have to stop the running …
=> account: add Custom User Profiles support

Ryujinx.HLE/HOS/Services/Nv/NvMemoryAllocator.cs
This fixes the region in use check. Previous it was failing if the checked range would end at the start of an already mapped range. For example:
- A check at address 0xFFFFFF0000 with size 0x10000 is done.
- Free region starts at 0x1000 and ends at 0x10000000000
- `(gpuVa + size) < _tree.Get(floorAddress)` returns false because `0xFFFFFF0000 + 0x1000` is not less than 0x10000000000.
This is incorrect because the range being requested *is* free, it just happens to end at the same address as the end of the free range (and of the address space). So the fix here is changing the `<` to `<=` to allow the cases where the end address is exactly equal to match aswell.
This fixes a failure calling the `AllocSpace` ioctl on a few games. However no effect was observed with this fix, because the …
=> Fix IsRegionInUse check on NV memory allocator

Ryujinx.HLE/HOS/Services/Hid/Types/Npad/NpadIdType.cs
As discussed with @Thog , this value should be `int`, not `uint`.
Fixes [a crash](https://github.com/Ryujinx/Ryujinx/issues/2244) on launch on Bayonetta 2 (and potentially other games that call this similarly).
=> Fix uint -> int typo in NpadIdType

Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
This PR addresses ghost typing and movement issues in Black Legend caused by leaving the hid shared memory completely zeroed.
I added code to `HidServer` to fill the entries of the hid devices when their respective `Activate` function is called.
=> Initialize hid inputs on activation to avoid spurious inputs

Ryujinx.HLE/HOS/Services/Time/IStaticServiceForPsc.cs
The timepoint was not being written, which caused Shantae (https://github.com/Ryujinx/Ryujinx-Games-List/issues/3555) to softlock on the Limited Runs logo as time did not advance. This fixes the issue. Might also affect other games of course, but this is the only one known to be affected so far.
=> Fix GetClockSnapshot not writing steady clock timepoint

Ryujinx.HLE/HOS/Services/Nfc/Nfp/UserManager/IUser.cs
This PR increase the Amiibo scanning delay which simulate the scanning. Previously we used 50ms which seems to work in all of games. But sadly games like FE3H or Hyrule Warriors AoC seems to need more delay to validate a scan. It's fixed with 125ms. (should partially fixes issue https://github.com/Ryujinx/Ryujinx/issues/2122)
=> nfp: Increase Amiibo scanning delay

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs
Fix a bug that caused buffer memory modified by atomic instructions only on shaders to not be flushed.
This fixes Pokémon not being identified on photos in New Pokémon Snap.
Fixes #2254
=> Fix shader buffer write flag on atomic instructions

Ryujinx/Modules/DiscordIntegrationModule.cs, Ryujinx/Ryujinx.csproj
This PR cleanup Discord Presence class:
- We currently store some hardcoded TitleId to show corresponding game icons on discord, which is pretty bad designed since discord limits the number of icons. Instead of that I have added a generic gamecard icon.
- The main menu time include the games time too now.
- There are null-check for game TitleId and Game Name, where are string and never null. I've removed it and check the TitleId is 0 then we can know it's an homebrew.
- I've added a button to visit the website.
- DiscordRichPresence is updated to lastest version.
=> misc: Cleanup Discord Presence

Ryujinx.HLE/HOS/Services/Sockets/Nsd/IManager.cs, Ryujinx.HLE/HOS/Services/Sockets/Nsd/Manager/FqdnResolver.cs, Ryujinx.HLE/HOS/Services/Sockets/Nsd/ResultCode.cs, Ryujinx.HLE/HOS/Services/Sockets/Nsd/Types/ApplicationServerEnvironmentType.cs, Ryujinx.HLE/HOS/Services/Sockets/Nsd/Types/NsdSettings.cs
This PR cleanup the `nsd` service a bit and implement / stub some calls (checked with RE):
- Added placeholders for lastest firmware calls,
- `GetSettingName` is removed because of a bad previous implementation (doesn't seems to be used by any games so there is no regression).
- `SetChangeEnvironmentIdentifierDisabled`, `WriteSaveDataToFsForTest`,`DeleteSaveDataOfFsForTest`, and `IsChangeEnvironmentIdentifierDisabled` are stubbed.
- `GetApplicationServerEnvironmentType` is implemented (closes #2247).
Now PGA TOUR 2K21 goes in-game (then deadlock):
=> nsd: Cleanup the service and implement some calls

Ryujinx.Common/Logging/LogClass.cs, Ryujinx.Graphics.Nvdec.H264/FFmpegContext.cs
This PR redirect the FFmpeg logging to our own log manager. It fixes #2263 and makes the log output cleaner.
=> ffmpeg: Redirect log output

Ryujinx.Audio.Backends.SDL2/Ryujinx.Audio.Backends.SDL2.csproj, Ryujinx.Audio.Backends.SDL2/SDL2AudioBuffer.cs, Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceDriver.cs, Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceSession.cs, Ryujinx.Audio/Backends/Common/HardwareDeviceSessionOutputBase.cs, Ryujinx.Common/Configuration/AudioBackend.cs, Ryujinx.Common/Configuration/ConfigurationFileFormat.cs, Ryujinx.Common/Configuration/ConfigurationState.cs, Ryujinx.Input.SDL2/SDL2GamepadDriver.cs, Ryujinx.SDL2.Common/Ryujinx.SDL2.Common.csproj, Ryujinx.SDL2.Common/SDL2Driver.cs, Ryujinx.sln, Ryujinx/Ryujinx.csproj, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.cs
This adds support to SDL2 as an audio backend.
It has the same compatibility level as OpenAL without its issues.
I also took the liberty of restructuring the SDL2 code to have one shared project between audio and input.
The configuration version was also incremented.
=> audio: Implement a SDL2 backend

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Ipc/IpcMessage.cs, Ryujinx.HLE/HOS/Services/ServerBase.cs, Ryujinx.HLE/HOS/Services/Sm/IUserInterface.cs
This PR addresses the following issues:
- SM was previously instancied once and reused on all sessions. This
could cause inconsistency on the service initialization.
- TIPC replies were not matching what is generated on hardware.
=> SM instance & TIPC fixes

Ryujinx/Ui/RendererWidgetBase.cs
This fix an issue when after a relaunch of a game containing other games (embedded games), the renderer window size would be 1x1.
This bug was introduced by #2260.
=> Fix embedded game rendering

Ryujinx/Input/GTK3/GTK3MappingHelper.cs
I found some mistake I made back when I first wrote the mapping for
Miria.
This fix:
- an offset by one after the tilde key in the mapping.
- F30 being mapped to F29.
=> Miria: Fix GTK3 keyboard mapping

ARMeilleure/CodeGen/X86/X86Optimizer.cs, ARMeilleure/Instructions/InstEmitMemory.cs, ARMeilleure/Translation/PTC/Ptc.cs
This makes a few minor improvements to the x86 backend, reducing the generated code size a little bit, and potentially improving performance (nothing really noticeable though).
Changes:
- Allow `add rax, 0x123`followed by `add rax, rbx` to be fully contained into the memory operand. Previously it was only able to contain the `add rax, rbx` leaving the constant addition. Now it can be fully contained as `mov rax, [rax+rbx*1+0x123]`.
- On blocks where the same constant value is used more than once, if the constant can't fit on a 32-bit immediate, instead of inserting a `mov` before each use, it now inserts a single move per block, and keeps the constant in a register.
- Improved codegen for pre-indexed pair Arm loads and stores a little bit. Instead of adding the offset to the base …
=> Fold constant offsets and group constant addresses

Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.OpenGL/Framebuffer.cs, Ryujinx.Graphics.OpenGL/HwCapabilities.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Renderer.cs
Currently, on Intel/AMD (windows, not mesa) we must perform a copy whenever rendering to a view with a different format from its storage. This is rather slow because it happens after every draw. This change moves this behaviour out of the backend, so that it can be covered by Copy Dependencies, which are much faster as they only copy on read, rather than after every write.
Upsides:
- Greatly speeds up drawing to views with a different format for AMD/Intel, as the copy is only performed when the texture with the other format is read, rather than after every draw.
- Removes the SignalModified calls and checks from GAL, which may speed up drawing a little on NVIDIA where it did not matter.
- Removing this makes the code in the gl backend a little nicer too.
- This may avoid other weird …
=> Use copy dependencies for the Intel/AMD view format workaround

ARMeilleure/CodeGen/RegisterAllocators/HybridAllocator.cs, ARMeilleure/CodeGen/RegisterAllocators/LinearScanAllocator.cs, ARMeilleure/IntermediateRepresentation/Operand.cs, ARMeilleure/Translation/ControlFlowGraph.cs, ARMeilleure/Translation/EmitterContext.cs, ARMeilleure/Translation/SsaConstruction.cs
This allows us to write flow controls like loops and if-elses with `LocalVariables` participating in phi nodes.
=> Allow `LocalVariable` to be assigned more than once

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Shader/Cache/CacheHelper.cs, Ryujinx.Graphics.Gpu/Shader/CachedGpuAccessor.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, Ryujinx.Graphics.Gpu/Shader/TextureDescriptorCapableGpuAccessor.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs, Ryujinx.Graphics.Shader/Translation/Rewriter.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
Fixes some issues with bindless textures, when CbufSlot is not equal to the current TextureBufferIndex. Before, this could get information from an invalid texture descriptor, which could break the shader depending on the data.
Specifically fixes a random chance of full screen colour flickering in Super Mario Party. May fix issues in other games that use bindless textures, such as newer UE4 ones. Does not fix bright cubemaps in UE4 games, or weird blocky lighting.
=> Pass CbufSlot when getting info from the texture descriptor

Ryujinx.Graphics.OpenGL/BackgroundContextWorker.cs
Fixes a random crash when starting an embedded game.
=> Assign _backgroundContext before starting its worker thread.

Ryujinx.Graphics.Nvdec.H264/FFmpegContext.cs, Ryujinx/Program.cs
This should fixes #2284 where the lib folder set in RootPath isn't the same between some linux distributions.
Since I don't use linux I can't really test it so feedbacks are really appreciate.
=> ffmpeg: Attempt to fix RootPath on some linux distributions

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
Fixes a potential regression introduced on #2290 where the constant buffer array size would be incorrect on games that uses non-constant constant buffer slots. Note that the only game that is know to do that is Super Mario 3D All-Stars, and from what I was able to test, it is fine even without that fix, probably because all the constant buffers that it accesses on the shader using the non-constant indexing are also used elsewhere.
While testing, I also found a shader cache related issue. The `QueryConstantBufferUse` value is not saved on the cache, which causes it to use the default one of `0xffff`, which equals to 16 constant buffers used. This is too high, higher than the amount of uniform buffers allowed on the host, so it may cause a compilation error. It seems to be a existing issue …
=> Fix constant buffer array size when indexing is used and other buffer descriptor and resolution scale regressions

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, Ryujinx.Graphics.Shader/Translation/TranslatorContext.cs
Fix a bug introduced by #2290 (hopefully the last one this time) where buffer and texture information from one vertex shader was not propagated to the other after they were merged. This was not a problem before because the use information was only collected later, after the shaders were already merged. Now they are collected very early, before they are merged, so the information needs to be propagated after the merge.
Fixes regressions on Catherine Full Body and other games using 2 vertex shaders.
=> Fix buffer and texture uses not being propagated for vertex A/B shaders

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
Fix a regression with res scale where the old logic from the glsl emitter for detecting 2d array textures, but our new dimension count did not include a dimension for array index anyways.
Fixes res scale in the warriors games. 1D or 3D sampled textures should remain blacklisted.
=> Fix dimensions check for scale eligibility

Ryujinx.Input.SDL2/SDL2Keyboard.cs, Ryujinx.Input.SDL2/SDLKeyboardDriver.cs
Add a new keyboard backend to the Ryujinx.Input.SDL2 project.
This is currently unused.
=> input: Implement a SDL2 keyboard backend

Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs, Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs, Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs
HleProcessDebugger was changed quite a bit to facilitate code reuse between the stack trace and register print code.
=> Extend info printed when guest crashes/breaks execution

Ryujinx.Graphics.Gpu/State/GpuStateTable.cs
The entries for non-independent blend state were missing from the state table, which means it wouldn't detect modification for most of those blend registers, and this not update the blend state. This only affects OpenGL games as NVN and Vulkan always have independent blend enabled (which is working properly).
This fixes broken blend on some OpenGL games, like Code of Princess EX.
With PR:
=> Fix non-independent blend state not being updated

Ryujinx.Graphics.Gpu/Image/FormatTable.cs
This is used by Yokai Watch 1.
Together with #2302 and #2303, it improves rendering on this game.
With PR:
I actually implemented it quite some time ago, but the game was still very broken so I didn't submit it for this reason. Now it seems much better with the other fixes I linked.
Theres still a issue similar to what was recently fixed on Super Mario Party where the screen is overlayed by a solid colour.
=> Add another Depth32F texture format variant

Ryujinx.Graphics.Gpu/Engine/MethodCopyTexture.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs
The guest OpenGL driver does out of bounds copies when copying textures for layout conversion. The way how this is supposed to work is that the copy should wrap to the next line of the texture and continue copying from there. Before this was being emulated on the host with two blits, which did work but had the issue that the second copy required the source texture to have one extra line. This extra line could sometimes have pixels fall into unmapped memory regions, which would cause a crash with a invalid memory region exception.
This uses a new approach that only requires a single bit. It simply adds an offset to the texture address, that way the copy is "in bounds" and no wrap to the next line is necessary. It also doesn't need to read any extra pixel.
This fixes the crash due to …
=> Use a different method for out of bounds blit

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs
When selecting a texture that's a view for a sampler resize, we should take care that resizing it doesn't change the aligned size of any larger mip levels.
This PR covers two cases:
- When creating a view of the texture, we check that the aligned size of the view shifted up to level 0 still matches the aligned size of the container. If it does not, a copy dependency is created rather than resizing.
- When searching for a texture for sampler, textures that do _not_ match our aligned size when both are shifted up by its base level are not considered an exact match, as resizing the found texture will cause the mip 0 aligned size to change. It will create a copy dependency view instead.
Fixes graphical errors and crashes (on flush) in various Unity games that use render-to-texture. This …
=> Compare aligned size for largest mip level when considering sampler resize

Ryujinx.Graphics.OpenGL/VertexArray.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
This fixes the value of the constant vertex attribute, which was being set to `1, 1, 1, 1` for some reason. According to the spec
> When values for a vertex shader attribute variable are sourced from a current generic attribute value, the attribute must be specified by a command compatible with the data type of the variable. The values loaded into a shader attribute variable bound to generic attribute index are undefined if the current value for attribute index was not specified by [...]
So this explicitly sets the value now, which fixes one of the issues reported on https://github.com/Ryujinx/Ryujinx-Games-List/issues/3599
Before:
After:
The other issue (missing clouds in the background) is fixed by #2005.
While I was at it, I also fixed an issue introduced on #2145 that broke shader …
=> Fix value of constant vertex attributes

ARMeilleure/Instructions/InstEmitSimdArithmetic.cs, ARMeilleure/Translation/PTC/Ptc.cs
Improves the accuracy of the FRECPS and FRSQRTS Arm instructions, by also handling the cases where one of the inputs is infinity and other is 0, as per the manual.
This fixes a bug on Rune Factory 5 where the characters skirt and other parts of the characters clothing would be lifted or stretched.
Before:
After:
Other changes:
- Fixed a oversight on the implementation of FRECPE and FRSQRTE rounding function, where it was using the CMPEQW SSE instruction instead of CMPEQD. It should use the dword variant since it is comparing 32-bit values. This didn't actually cause any major problems because it is just used to select between the rounded or non-rounded values, so it just causes the result to have more precision than it should in some rare cases. No changes noticed on the games tested.
- …
=> Improve accuracy of reciprocal step instructions

Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall32.cs
The values were inverted, causing games to get a invalid mask value.
Only affects 32-bit games.
Allows https://github.com/Ryujinx/Ryujinx-Games-List/issues/1350 to progress further.
=> Fix inverted low/high mask value on GetThreadCoreMask32 syscall

Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
Fixes a regression introduced on #1845 where a incorrect function name would be included on the trace if the function had its name stripped. Now it is just empty, like it was before the change.
Before:
```
0x000000003cac6114	sdk:0x58114	nn::diag::detail::VAbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, std::__va_list):0x00b8
0x000000003cac61a0	sdk:0x581a0	nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, char const*, ...)
0x000000003cb4b894	sdk:0xdd894	nn::os::detail::ThreadManagerImplByHorizon::SetThreadCoreMask(nn::os::ThreadType*, int, unsigned long long) const:0x0058
0x000000003cb45dcc	sdk:0xd7dcc	nn::os::SetThreadCoreMask(nn::os::ThreadType*, int, unsigned long long):0x002c …
```
=> Fix guest stack trace inexistent function names

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Translation/Rewriter.cs
This would fix a bug in the shader translator where it would try to normalize image load/store colours. Normalizing for `imageLoad` "works", but would provide incorrect results as it already uses a snorm format for the image when it is bound. For `imageStore`, it causes a NRE as the current code tries to get the "destination" operands from the operation, but fails as theres none on `imageStore`. It would also try to normalize the value of other texture operations such as `TextureSize` which is obviously wrong as normalizing the sizes of a texture because the format is SNORM makes no sense.
Fix a crash on https://github.com/Ryujinx/Ryujinx-Games-List/issues/3611 but the game does not render properly (seems to be a problem elsewhere, maybe the lack of atomic image instructions since the …
=> Do not attempt to normalize SNORM image buffers on shaders

Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Window.cs
Previous code was binding then blitting while the framebuffer was bound
and then clearing the alpha channel by its handle.
This ended up triggering a bug since AMD driver 21.4.1 ending up
clearing the whole framebuffer as a result.
New code fix this weird logic by applying the clear on the bound
framebuffer.
Close #2236.
=> Avoid clearing alpha channel by handle when presenting

Ryujinx.Graphics.OpenGL/HwCapabilities.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs
Improves OpenGL performance on FAST RMX and Xenoblade DE/2. Will probably only work on NVIDIA GPUs, but the emulated quads path will still be valid for other GPUs. Note: SLOW RMX gets a bit faster in handheld mode.
I'd recommend checking on platforms without supported host quads (AMD? Intel? Mesa?) to make sure a GL error is actually thrown when attempting GL.Begin(PrimitiveType.Quads).
=> Use Quads on OpenGL host when supported.

Ryujinx.Graphics.Gpu/Engine/MethodCopyTexture.cs, Ryujinx.Graphics.Gpu/State/CopyTextureControl.cs
NVN adds an offset to the source X/Y coordinates of the blit, in order to ensure that the blit will be "centered" (sampling from the center of the pixel rather than the corner). This is done by adding `RatioX / 2.0` and `RatioY / 2.0` to the X/Y coordinates, where `RatioX` and `RatioY` are calculated as `SourceRegionX / DestinationRegionX` and `SourceRegionY / DestinationRegionY` respectively. This changes removes said offset by subtracting the offset value from the coordinates.
This fixes some off-by-one errors that caused the destination textures to have a black border. When used to blit mipmap levels, this could propagate and cause the whole texture to be black in the end, as it would usually use the previous level as source.
This only affects copies between regions of different sizes, …
=> Fix texture blit off-by-one errors

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Decoders/Decoder.cs, Ryujinx.Graphics.Shader/Decoders/MergeType.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/Optimizer.cs
PBK and SSY shader instruction pushes an address to a stack, which is poped by BRK and SYNC instructions respectively. When the addresses on stack are mixed, only the address for the matching instruction should be used.
Consider the following example:
- PBK pushes address 0xA00.
- SSY pushes address 0xB00.
- BRK is executed.
The current behaviour is that the shader translator assumes that BRK would jump to 0xB00, which is incorrect as the address was pushed by a SSY instruction, not PBK. This changes makes it discard the 0xB00 address, then use the 0xA00 since the type of this instruction matches.
Fixes pink sky on Dead or Alive Xtreme 3.
PR:
Things to look for while testing:
- Any regression caused by this change.
- Shader compilation being slower, since it needs to …
=> Fix shaders with mixed PBK and SSY addresses on the stack

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs
Some games stores the handles on different constant buffers, which was not supported.
This extends the shader bindless elimination to support this case, and also extends the GPU emulation to support reading the handles from different buffers.
Fixes black screen on Final Fantasy XII. Other games with black textures might be affected as well.
I believe updating the shader cache version is not needed, as shaders with bindless access are not cached right now anyway.
Should be tested on other games that uses bindless textures to ensure they didn't regress.
=> Support bindless textures with separate constant buffers for texture and sampler

Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs, Ryujinx.Graphics.Gpu/State/GpuState.cs
This fixes a regression caused by #980, that was causing a crash on New Super Lucky's Tale.
As always, this need feedback on possible regression on any games.
Fix #2343.
=> Do not clear gpu subchannel state on BindChannel

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs
Before this, all samplers instance were leaking on exit because the
dispose method was never getting called.
This fix this issue by making TextureBindingsManager disposable and
calling the dispose method in the TextureManager.
This was found thanks to the Vulkan spec layer.
=> GAL: Fix sampler leaks on exit

Ryujinx/Ui/Windows/SettingsWindow.glade
This PR increases the height of the settings window, making it so that there is no need to scroll down to see options on the General & System tabs.
Before:
After:
=> Increase height of Settings Window

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Decoders/Decoder.cs
The NV shader compiler puts these at the end of shaders. This is needed when a shader includes a BRX instruction, as we continue decoding past all exits in order to catch potential branch targets. Before, this would terminate when it encountered a 0, but some shaders did not have a 0 at the end and ended up decoding forever, possibly because the shader data _did_ end at the infinite loop, and the "instruction" afterwards was just leftover data from earlier rather than 0.
Note that a better solution would probably be identifying the BRX targets rather than continuing to decode like this, but this workaround is functional for now.
A few games with complex shaders should be tested, maybe Fire Emblem to make sure it still works. Fixes Dark Devotion.
=> End shader decoding when reaching a block that starts with an infinite loop (after BRX)

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs
When the (separate) sampler bindless handle comes from the offset 0 of the constant buffer, it was being ignored which caused the wrong sampler to be used. This correct the bug by adding 1 to the offset on the shader translator, and then subtracting 1 on the GPU emulator to ensure that it is never 0 if a separate bindless sampler is used.
Fix incorrect sampling on Final Fantasy XII.
Before:
After:
=> Fix separate bindless sampler at offset 0

Ryujinx.HLE/HOS/Services/Account/Acc/ApplicationServiceServer.cs
Since the implementation of User Profiles, we can get more than one profile stored. This PR fixes a wrong condition in `TrySelectUserWithoutInteraction`.
Closes #2320
=> account: Fix wrong condition in TrySelectUserWithoutInteraction

Ryujinx.HLE/HOS/Ipc/IpcMessage.cs
Since original IPC implementation doesn't check the buffers size, there is no reason to check them so I've removed it. Checking the buffers addresses could prevent to unexpected behaviors.
That fixes a bsd service issue with some homebrews and some games included Knockout City (https://github.com/Ryujinx/Ryujinx-Games-List/issues/3622) which is now bootable (but not playable since online is required):
=> ipc: Remove size checks for buffer type 0x21/0x22

Ryujinx/Ui/Windows/ControllerWindow.cs
This PR allows to "unbind" inputs in the `ControllerWindow` by middle-clicking while an input is selected.
This is my first code contribution to Ryujinx, so I apologize if the code is not compliant with some internal standard, or even if it's just outright bad for some reason that I don't understand.
=> Unbind input on middle click

Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/HidUtils.cs, Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs, Ryujinx.HLE/HOS/Services/Hid/IHidSystemServer.cs, Ryujinx.HLE/HOS/Services/Hid/ResultCode.cs, Ryujinx.HLE/HOS/Services/Hid/Types/AppletFooterUiType.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Npad/NpadInternalState.cs
This PR implements IHidServer `GetPlayerLedPattern`, `SetNpadJoyHoldType`, `IsVibrationDeviceMounted` (Closes #2041) and `GetNpadJoyHoldType` accordingly to RE.
Additonnally it stubs IHidSystemServer `ApplyNpadSystemCommonPolicy` and implements `GetLastActiveNpad`, `GetNpadSystemExtStyle` and `GetAppletFooterUiType` accordingly to RE too.
There are some little cleanup here and there.
=> hid: Cleanup and implement some calls

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs
Not passing those inputs was generating a link error on the shaders, as the fragment shader was consuming inputs that were not explicitly passed from the geometry shader. This change makes it pass all possible inputs when the passthrough is enabled.
Fixes some missing graphics on Game Builder Garage.
Before:
After:
Note: Doesn't fix apple not showing on the first tutorial, this looks more like a logic bug rather than just something not being rendered (but existing).
=> Pass all inputs when geometry shader passthrough is enabled

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs, Ryujinx.Graphics.Shader/Translation/Rewriter.cs
The component order of the instruction is the inverse of the vector returned by `textureQueryLod`.
Fixes blurry graphics on Mario + Rabbids Kingdom Battle, caused by the shader sampling from the wrong texture level (due to the incorrect LOD value).
Before:
After:
=> Fix shader texture LOD query

Ryujinx.HLE/HOS/Services/Hid/HidDevices/TouchDevice.cs, Ryujinx.HLE/HOS/Services/Hid/HidDevices/Types/TouchPoint.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/TouchScreen/TouchAttribute.cs, Ryujinx.Input/HLE/TouchScreenManager.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/RendererWidgetBase.cs
Even if Touch works in some games, we didn't set the `End` attribute and then the wrong value is written in the shared memory. That could lead to some touch issues in some specific games.
While testing, a bug was found about MainWindow focus, it's fixed now.
It could be nice to get some feedbacks, if anyone knows games with touch issues feel free to test if that fixes it.
Fixes #2351
Now Mini Metro, Umineko no Naku Koro ni Saku and probably more games:
=> input: Fixes TouchPoint wrong attribute

.github/workflows/build.yml, Ryujinx/Ryujinx.csproj, appveyor.yml
This enables the single file publish feature at the project level to embed the managed dependencies on the executable, and remove some unused dependencies/files.
Here is what the publish folder looks like with this change:
Needs feedback, currently I still need to decide what to do about the PDBs:
- Embeding them requires adding `<DebugType>embedded</DebugType>` to each project which is not exactly ideal.
- Also, embeding is not working properly, stack traces are not showing the file and line numbers.
Easiest solution is simply including the PDBs on the output if we decide this information is desirable to have on release aswell, but it will be one extra file per project.
=> Reduce number of dlls on distribution with single file publish

Ryujinx.Common/Logging/LogClass.cs, Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/Nfc/ISystemManager.cs, Ryujinx.HLE/HOS/Services/Nfc/IUserManager.cs, Ryujinx.HLE/HOS/Services/Nfc/NfcManager/INfc.cs, Ryujinx.HLE/HOS/Services/Nfc/NfcManager/Types/NfcPermissionLevel.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/IDebugManager.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/ISystemManager.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/IUserManager.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/INfp.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/Types/AmiiboConstants.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/Types/CommonInfo.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/Types/DeviceType.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/Types/ModelInfo.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/Types/MountTarget.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/Types/NfpDevice.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/Types/NfpDeviceState.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/Types/NfpPermissionLevel.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/Types/RegisterInfo.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/Types/State.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/Types/TagInfo.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/Types/VirtualAmiiboFile.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/UserManager/Types/DeviceType.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/VirtualAmiibo.cs
This PR add permission levels for `nfc` and `nfp` services:
- `nfc`: `CreateUserInterface` and `CreateSystemInterface` are implemented.
- `INfc`: `Initialize` and `IsNfcEnabled` calls are stubbed.
- `nfp`: `CreateDebugInterface` and `CreateSystemInterface` are implemented.
- `INfp`: `GetRegisterInfo2` for `IDebug` and `ISystem` are implemented.
Additionnally to that, a wrong size in `RegisterInfo` struct is now fixed.
=> nfc/nfp: Implement ISystemManager and ISystem

Ryujinx.HLE/HOS/Services/Settings/ISettingsServer.cs, Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs, Ryujinx.HLE/HOS/SystemState/SystemStateMgr.cs
This PR implement `set` and `sys:set` calls : `GetDeviceNickName` and `SetDeviceNickName` accordingly to RE.
I've cleaned up both services a bit and `SystemStateMgr` class too.
Closes #2110
=> settings: Implement GetDeviceNickName and SetDeviceNickName

Ryujinx.Cpu/IVirtualMemoryManagerTracked.cs, Ryujinx.Cpu/MemoryManager.cs, Ryujinx.Cpu/MemoryManagerHostMapped.cs, Ryujinx.Cpu/Tracking/CpuMultiRegionHandle.cs, Ryujinx.Cpu/Tracking/CpuRegionHandle.cs, Ryujinx.Graphics.Gpu/Memory/Buffer.cs, Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs, Ryujinx.Memory.Tests/MultiRegionTrackingTests.cs, Ryujinx.Memory/Tracking/MemoryTracking.cs, Ryujinx.Memory/Tracking/MultiRegionHandle.cs
This greatly speeds up games that constantly resize buffers, and removes stuttering on games that resize large buffers occasionally:
- Large improvement on Super Mario 3D All-Stars. Slowdown now is just due to the creation of the OGL buffer resources. (#1663 needed for best performance)
- Improvement to Hyrule Warriors: AoC, and UE4 games. These games still stutter in general due to texture creation/loading.
- Small improvement to other games, potential 1-frame stutters avoided.
`ForceSynchronizeMemory`, which was added with POWER, is no longer needed. Some tests have been added for the MultiRegionHandle.
=> Inherit buffer tracking handles rather than recreating on resize.

Ryujinx.HLE/HOS/Services/Hid/HidDevices/MouseDevice.cs, Ryujinx.Input/HLE/InputManager.cs, Ryujinx.Input/HLE/NpadManager.cs, Ryujinx.Input/HLE/TouchScreenManager.cs, Ryujinx.Input/IMouse.cs, Ryujinx.Input/MouseStateSnapshot.cs, Ryujinx/Config.json, Ryujinx/Configuration/ConfigurationFileFormat.cs, Ryujinx/Configuration/ConfigurationState.cs, Ryujinx/Input/GTK3/GTK3Mouse.cs, Ryujinx/Input/GTK3/GTK3MouseDriver.cs, Ryujinx/Ui/RendererWidgetBase.cs, Ryujinx/Ui/Windows/ControllerWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.glade, Ryujinx/_schema.json
Add direct mouse support, similar to the direct keyboard support. This enables games and homebrew that support usb mouse to have that option enabled.
Touchscreen is disabled when direct mouse is enabled. Also, the real cursor is hidden while inside the client area, but gtk seems to reset the mouse cursor state often, so you will see the mouse pop in once in a short while.
=> Add Direct Mouse Support

Ryujinx/Ui/MainWindow.cs
This adds two improvements to the `_gameTable` search that pops up when you start typing something while browsing the game list.
First, it allows searching by TitleID instead of name. This was brought up on Discord as a useful way to figure out what game you have mods for, and allows to more easily find games with weird titles that cannot be easily typed out (*stares at Pokémon*).
Second, instead of using the default `StartsWith` search behaviour for names, it instead uses `Contains`. This, for example, allows to type "odyssey" and find Super Mario Odyssey. The current behaviour would not return any result when such a search was made.
Note that the `SearchEqualFunc` here returns `false` if there *is* a match. This is intentional, though incredibly counter-intuitive. It's just how these …
=> Improve gameTable search

Ryujinx.HLE/HOS/Services/Caps/IAlbumApplicationService.cs, Ryujinx.HLE/HOS/Services/Caps/ResultCode.cs, Ryujinx.HLE/HOS/Services/Caps/Types/ContentType.cs
This PR stubs caps service call `GetAlbumFileList0AafeAruidDeprecated` and `GetAlbumFileList3AaeAruid` (Closes #2035, Closes #2401), both are checked by RE.
This avoid using "ignore missing services" when you want to play World of Light in Super Smash Bros Ultimate.
=> caps: Stubs GetAlbumFileList0AafeAruidDeprecated and GetAlbumFileList3AaeAruid

Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.OpenGL/HwCapabilities.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs
Some overloads of the texture sample functions (in special, those that take a 2D or Cube shadow sampler, with a LOD level or LOD bias parameter) requires an extension, namely the [texture shadow LOD](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_shadow_lod.txt) extension. This PR enables the extension on shaders, fixing a compilation failure that would otherwise occur on those shaders. Additionally, since the extension is not widely supported, this removes the LOD parameters if the GPU doesn't support the extension. Note that it was already removing the parameter in one case (any array shadow sampler that had explicit LOD levels). Now this case is handled properly if the extension is supported, which is more accurate.
Fixes lighting on Mario Golf Super Rush, and …
=> Fix texture sampling with depth compare and LOD level or bias

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/GlslGenerator.cs
Fixes default output values for shader outputs, which was `vec4(0, 0, 0, 0)` before but should be `vec4(0, 0, 0, 1)`.
Fixes missing geometry on Monster Hunter Stories 2: WIngs of Ruin (Trial Version).
Before:
After:
=> Fix default value for unwritten shader outputs

Ryujinx.Common/Logging/LogClass.cs, Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/ILibraryAppletProxy.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/ISystemAppletProxy.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/LibraryAppletProxy/AppletStandalone.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/LibraryAppletProxy/ILibraryAppletSelfAccessor.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/LibraryAppletProxy/IProcessWindingController.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/IAppletCommonFunctions.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/IDisplayController.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/IAllSystemAppletProxiesService.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/Types/AppletIdentityInfo.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/Types/AppletProcessLaunchReason.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/Types/LibraryAppletInfo.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/Types/LibraryAppletMode.cs, Ryujinx.HLE/HOS/Services/Am/ResultCode.cs, Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs, Ryujinx.HLE/HOS/Services/Mii/Helper.cs, Ryujinx.HLE/HOS/Services/Mii/IImageDatabaseService.cs, Ryujinx.HLE/HOS/Services/Mii/MiiDatabaseManager.cs, Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs, Ryujinx.HLE/HOS/Services/Settings/Types/PlatformRegion.cs, Ryujinx.HLE/HOS/SystemState/SystemStateMgr.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade
Why "no name"? Because it's the Miis default name in the Switch service so yeah, let's introduce a standalone mode for official Mii Editor applet.
Since Ryujinx requires a Switch firmware to be installed, we can run applets directly from the firmware's files. In that way we can run the Mii Editor applet in a standalone mode.
That allows you to create, edit, rename, save, move and delete Miis in the `mii` service system save data, which is required by some games such as Mario Kart 8 Deluxe, Miitopia or more recently Mario Golf (in adventure mode). Now save files aren't needed.
Launching applets from games is not supported. For this reason, if you play a game that requires having Miis created, you need to first launch the Mii applet (from the File > Launch Mii Applet menu), create a Mii of …
=> no name: Mii Editor applet support

Ryujinx.Graphics.Gpu/Image/TextureManager.cs
When switching from one render target to another, when both have a copy dependency to each other, a copy can be deferred on the second target when unbinding the first.
Before, this would not be honoured before binding the new texture, so the copy would stay deferred until the render targets change again, at which point it would copy in old data and essentially clear all the draws done during that time.
This change runs synchronize memory to make sure that copies are honoured. This can cause a redundant copy, but this is a rare situation and it's better than it breaking for now.
This should fix miiedit on AMD/Intel GPUs on windows. May fix other games, or perhaps rare copy dependency bugs on NVIDIA too.
=> Honour copy dependencies when switching render target

Ryujinx.HLE/HOS/Services/Audio/IHardwareOpusDecoderManager.cs, Ryujinx.HLE/HOS/Services/Audio/Types/OpusDecoderFlags.cs, Ryujinx.HLE/HOS/Services/Audio/Types/OpusParametersEx.cs
This is based off of my RE of 12.0.2 audio services, the newly added parameter can be safely ignored due to ryujinx not using fixed-size I/O buffers. I also included a minor fixup to avoid returning incorrect error codes to callers as HOS always aborts (aside from one special case however nothing actually returns that 😖)
This is completely untested as I don't own any games using the new 12.0.0+ SDK so it should probably be tested on one of them before merging.
=> Implement 12.0.0 hwopus functions

Ryujinx.HLE/HOS/Services/Ns/Aoc/IAddOnContentManager.cs, Ryujinx.HLE/HOS/SystemState/SystemStateMgr.cs
This PR fixes an wrong returned value (introduced in #2414) which cause some DLC not recognized in some games like Super Robot War T.
In #2414 I've removed the EventHandle check too, because it could cause some issues, but sadly it doesn't do the job so I reverted changes. It should fix Diablo III: Eternal Collection.
Revert a change made to desired title language in Traditional Chinese in #2419.
=> aoc: Fixes some inconsistencies

Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/DnsSetting.cs
For a strange reason `IPInterfaceProperties.IsDynamicDnsEnabled` throws a `PlatformNotSupported` exception in Linux.
This PR fixes this issue with a `try/catch` and set the value to false. Closes #2415.
Now games can be playable back. Thanks to @SeraUQ and @pineappleEA for the tests.
=> nifm: Fixes IsDynamicDnsEnabled not supported

Ryujinx/Ui/Windows/ControllerWindow.cs
There is a wrong condition in `GetShrinkedGamepadName` which throw an oob if the controller name is equal to the checked value. It's now fixed and shoud closes #2442 .
=> ui: Fixes GetShrinkedGamepadName

Ryujinx/Ui/RendererWidgetBase.cs
Add a portable screenshot folder to save images when portable mode is active. Also adds a few error checks
=> Add portable screenshot folder

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/GlslGenerator.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/StructuredIr/AstOptimizer.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, Ryujinx.Graphics.Shader/Translation/TargetApi.cs, Ryujinx.Graphics.Shader/Translation/TargetLanguage.cs, Ryujinx.Graphics.Shader/Translation/TranslationOptions.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs, Ryujinx.ShaderTools/Program.cs
Allows the target language and API to be passed to the translator. Will be used by the Vulkan and SPIR-V backend in the future.
=> Allow shader language and target API to be specified on the shader translator

Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs
This fixes a regression introduced on #2286. This PR made buffer updates are batched, but sometimes the updates are delayed way too much, and when it gets to actually write the data, the buffer was already unmapped, leading to a NRE as the address is invalid and the buffer no longer exists. This attempts to solve this by making those updates happen more frequently (at the end of every command buffer).
Note: This has the potential to reduce performance, so it has to be tested to make sure that performance was not regressed. If it was, then it will need to be fixed using a different method.
Affected games:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/876 (probably?)
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1096
Maybe more...
=> Flush UBO updates more frequently

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/TexelFetchScale_cp.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/TexelFetchScale_fp.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
Monster Hunter Rise has a shader that divides `gl_FragCoord` by screen size, then multiplies it by the texture size and uses the result on `texelFetch`. This doesn't work because while `gl_FragCoord` is unscaled, the `textureSize` isn't. This change also unscales the size which fixes the issue.
Before:
After:
Might also fix a similar issue on Monster Hunter Stories 2 (#2436). Needs testing.
=> Unscale textureSize when resolution scaling is used

Ryujinx.Memory/IVirtualMemoryManager.cs, Ryujinx.Memory/MemoryBlock.cs
Fixes issues pointed out by FICTURE7:
- `MemoryBlock` returned `WritableRegion` dispose method never needs to perform a write-back, as `MemoryBlock` regions are always contiguous.
- Added missing `using` on the IVirtualMemoryManager.Fill` method, before there was the possibility that the value was never written back to memory if the region was not contiguous.
Closes #2445
=> Fix GetWritableRegion write-back

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
This PR implement `CreateApplicationAndRequestToStart` call, result code is checked by RE.
Now we can restart a guest program by itself. This is needed by SSBU when you changes the game language.
NOTE: This currently don't works using OpenAL backend due to another issue.
Closes #2108
=> am: Implement CreateApplicationAndRequestToStart

Ryujinx.HLE/HOS/Kernel/Memory/KPageTableBase.cs
This fixes a bug where virtual memory allocation could be out of range, as it was using the memory block address without enforcing it to be inside the requested range.
This fixes memory corruption that leads to crashes in some games that makes assumptions about the virtual memory, without first checking if it is in use. As far I can tell, only games using `MapPhysicalMemory`/`UnmapPhysicalMemory` are affected, but it could affect more too.
Fixes crash on boot on Disaster Report 4, now ingame (however suffers from typical UE4 texture corruption, so not playable).
Likely also affects other games, it's worth trying games that crashes very early on boot due to invalid memory region exceptions or aborts, especially if they are UE4 games.
=> Fix virtual memory allocation being out of range

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/TextureOperation.cs, Ryujinx.Graphics.Shader/Translation/Rewriter.cs
Fixes a regression introduced on #2441 where shaders using rectangle textures wouldn't have their `textureSize` used for the coordinates normalization operation flagged and wouldn't be able to get the texture scale. While I was at it, I also fixed a issue that I noticed where the constant buffer slot wouldn't be added to the new texture operations inserted on the rewrite pass, which could cause them to fail with bindless textures.
Fixes regression on The Touryst. One thing to note is that I found high memory usage when testing this title. I'm not sure if it's a leak, but as I have a low amount of RAM, this leads to graphical glitches and crashes. However I believe this is not a new issue, someone else reported high memory usage on this game too a while ago.
Closes #2469
=> Fix shader compilation on shaders that uses rectangle textures

Ryujinx.Graphics.Gpu/Engine/Compute/ComputeClass.cs, Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs, Ryujinx.Graphics.Gpu/Engine/InlineToMemory/InlineToMemoryClass.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClass.cs
This improves the performance of Inline-to-Memory engine data transfers by pusing all the data at once, instead of word by word. This is similar to the optimization that is done for constant buffer updates.
Mostly expected to affect Switch games using the OpenGL API as those use Inline-to-Memory a lot more. NVN only uses it to write the compute QMD structure afaik (which is small). Might reduce the loading times or stutters on said OpenGL games a little bit. I noticed that they have an issue where they simply pause for a few seconds sometimes though, and it doesn't seems to be a GPU related issue.
=> Implement a fast path for I2M transfers

Ryujinx.HLE/HOS/Services/Nv/INvDrvServices.cs
Fixes an oversight where it was getting the transfer memory handle from the wrong location, leading to only the process handle being closed.
Fixes crash with some homebrew that initializes nvservices more than once, I'm not sure if games can do this, and I'm not aware of any game being affected by this change.
=> Close transfer memory properly on nvservices

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs
If the shader does not use textures or images at all, then theres no need to initialize those pools. This fixes a `InvalidMemoryRegionException` that would happen on the emulator if there was a draw/compute dispatch without setting the pools address. This is handled by simply setting them to null if the GPU VA is 0. Additionally, if the shader does access textures and they are null, its prints an error to the log.
Fixes regression on https://github.com/Ryujinx/Ryujinx-Games-List/issues/1020 (unsure on which version it started).
Btw, no errors are logged on this game, so the shader where this used to happen is not accessing textures.
=> Do not require texture and sampler pools being initialized

Ryujinx.Graphics.Gpu/Image/TextureCache.cs
There is a bug where textures that are modified on the fast path of DMA copies might suffer from data loss, if the texture is deleted, because the data is never flushed. The fix here is adding the texture to the "auto delete cache", so that the data is eventually flushed when it falls out of the cache, and the texture is kept alive for longer, so even if it is removed from the texture pool, chances are that it will still exist on the next use (thus not even needing to flush and reload the data).
This fixes black portraits on Legend of Mana, might also fix the other graphical glitch that was reported.
Before:
After:
Needs more testing to confirm that all instances of the bug where fixed.
It is worth nothing that images might have a similar issue. If a image is modified by a shader, but not …
=> Ensure that DMA copy target textures are kept alive or flushed

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs, Ryujinx.Graphics.OpenGL/PersistentBuffers.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.Texture/LayoutConverter.cs
This change gets data for buffers and textures by first copying it to a mapped persistent buffer, waiting on a fence, and copying the data out of it. This seems to be magnitudes faster than downloading the data directly with the gl methods, so it should improve games and situations where data is being flushed back from the GPU a lot.
There is one buffer used per opengl context for flushing data. For one instance of the Renderer, there is a `_main` and a `_background` buffer, so that the main rendering thread and the background context can both flush at the same time without stepping on each other's toes. Each buffer sizes up to match the biggest thing it has flushed so far, similar to the PBO copy buffer for textures. One benefit of doing it this way is that 4 instances of the same 1080p …
=> Flush buffers and texture data through a persistent mapped buffer.

Ryujinx.Audio/Renderer/Dsp/AudioProcessor.cs, Ryujinx.Audio/Renderer/Dsp/Command/AdpcmDataSourceCommandVersion1.cs, Ryujinx.Audio/Renderer/Dsp/Command/AuxiliaryBufferCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/BiquadFilterCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/CircularBufferSinkCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/ClearMixBufferCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/CommandList.cs, Ryujinx.Audio/Renderer/Dsp/Command/CopyMixBufferCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/DataSourceVersion2Command.cs, Ryujinx.Audio/Renderer/Dsp/Command/DelayCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/DepopForMixBuffersCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/DepopPrepareCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/DownMixSurroundToStereoCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/LimiterCommandVersion1.cs, Ryujinx.Audio/Renderer/Dsp/Command/LimiterCommandVersion2.cs, Ryujinx.Audio/Renderer/Dsp/Command/MixCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/MixRampCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/MixRampGroupedCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/PcmFloatDataSourceCommandVersion1.cs, Ryujinx.Audio/Renderer/Dsp/Command/PcmInt16DataSourceCommandVersion1.cs, Ryujinx.Audio/Renderer/Dsp/Command/Reverb3dCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/ReverbCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/UpsampleCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/VolumeCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/VolumeRampCommand.cs, Ryujinx.Audio/Renderer/Dsp/DataSourceHelper.cs, Ryujinx.Audio/Renderer/Dsp/Effect/IDelayLine.cs, Ryujinx.Audio/Renderer/Dsp/State/ReverbState.cs, Ryujinx.Audio/Renderer/Server/CommandBuffer.cs
This improve RyuJIT codegen drastically on the DSP side.
This may reduce CPU usage of the DSP thread quite a lot.
There is still room to improvements on that side and this might be addressed by follow up PRs.
As always, regression testing needed.
=> Amadeus: DSP code generation improvements

Ryujinx.Graphics.OpenGL/HwCapabilities.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs, Ryujinx.Graphics.OpenGL/PersistentBuffers.cs, Ryujinx.Graphics.OpenGL/Renderer.cs
It seems like this method of flushing data is much slower on Mesa drivers, and slightly slower on Intel Windows. Have not tested Intel Mesa, but I'm assuming it is the same as AMD. The game in question is Skyward Sword HD, as it had the greatest effect from the last PR.
This also adds vendor detection for AMD on Unix, which counted as "Unknown" before.
=> Only use persistent buffers to flush on NVIDIA and Windows+AMD

Ryujinx.Cpu/MemoryManager.cs, Ryujinx.Cpu/MemoryManagerHostMapped.cs, Ryujinx.Graphics.GAL/IRenderer.cs, Ryujinx.Graphics.GAL/ITexture.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Memory/Buffer.cs, Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs, Ryujinx.Graphics.OpenGL/Buffer.cs, Ryujinx.Graphics.OpenGL/Image/TextureBuffer.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs, Ryujinx.Graphics.OpenGL/PersistentBuffers.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.Texture/LayoutConverter.cs, Ryujinx.Memory.Tests/MockVirtualMemoryManager.cs, Ryujinx.Memory/AddressSpaceManager.cs, Ryujinx.Memory/IVirtualMemoryManager.cs, Ryujinx.Memory/IWritableBlock.cs, Ryujinx.Memory/WritableRegion.cs
A few changes here to generally improve performance, even for platforms not using the persistent buffer flush.
- Texture and buffer flush now return a ReadOnlySpan<byte>. It's guaranteed that this span is pinned in memory, but it will be overwritten on the next flush from that thread, so it is expected that the data is used before calling again.
- As a result, persistent mappings no longer copy to a new array - rather the persistent map is returned directly as a Span<>. A similar host array is used for the glGet flushes instead of allocating new arrays each time.
- Texture flushes now do their layout conversion into a WriteableRegion when the texture is not MultiRange, which allows the flush to happen directly into guest memory rather than into a temporary span, then copied over. This …
=> Return mapped buffer pointer directly for flush, WriteableRegion for textures

Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs, Ryujinx.Input/HLE/NpadController.cs, Ryujinx.Input/HLE/NpadManager.cs
There's a bug where the right joycon is not retrieved from cemuhook, and that the right joycon motion shared mem is cleared after update. This aims to fix that issue. 
This should allow right joycon to work in Skyward Sword.
=> Ensure right joycon motion data is set

Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceDriver.cs, Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceSession.cs, Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceDriver.cs, Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceSession.cs, Ryujinx.Audio.Backends.SoundIo/SoundIoHardwareDeviceDriver.cs, Ryujinx.Audio.Backends.SoundIo/SoundIoHardwareDeviceSession.cs, Ryujinx/Ui/RendererWidgetBase.cs
This fixes a bunch of issues, mostly related to the audio backends.
First, `SDLHardwareDeviceSession` can't be disposed twice. Attempting to do so will cause a crash due to a double free. This was happening most of the time here when I use the SDL2 backend. What was causing the double dispose was the session being disposed from the audio out server thread, and from some other thread disposed the `Switch` instance (which disposes the audio device driver, which in turn disposes all the existing sessions). There is a race when the driver and session dispose methods are called the same time, which in turn can cause the session dispose to be called twice, and then free it twice, causing the crash.
OpenAL sessions would deadlock most of the time when disposed. This caused the emulator to hang …
=> Make audio disposal thread safe on all 3 backends

Ryujinx.HLE/Exceptions/CodeRegionTamperedException.cs, Ryujinx.HLE/HOS/Kernel/Process/ProcessTamperInfo.cs, Ryujinx.HLE/HOS/ModLoader.cs, Ryujinx.HLE/HOS/ProgramLoader.cs, Ryujinx.HLE/HOS/Tamper/AtmosphereCompiler.cs, Ryujinx.HLE/HOS/Tamper/AtmosphereProgram.cs, Ryujinx.HLE/HOS/Tamper/CodeEmitters/EndConditionalBlock.cs, Ryujinx.HLE/HOS/Tamper/CompilationContext.cs, Ryujinx.HLE/HOS/Tamper/ITamperProgram.cs, Ryujinx.HLE/HOS/Tamper/ITamperedProcess.cs, Ryujinx.HLE/HOS/Tamper/MemoryHelper.cs, Ryujinx.HLE/HOS/Tamper/MemoryRegion.cs, Ryujinx.HLE/HOS/Tamper/Operations/IfBlock.cs, Ryujinx.HLE/HOS/Tamper/TamperedKProcess.cs, Ryujinx.HLE/HOS/TamperMachine.cs
This PR focuses on improving reporting for cheats and updating the cheat instructions to match [Atmosphere's implementation](https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/features/cheats.md). Those are:
- A warning is now issued when the cheat tries to write to code region instead of requiring log analysis in debug mode;
- The cheat names are now printed in the log for better error detection and support;
- Implemented new addressing modes `Alias` and `Aslr`;
- Implemented `else` instruction for conditionals.
Also, with #1865 merged, it is now safe to enable cheats to write to code regions (with the aforementioned warning). This is a preparation for the upcoming full support, but does not mean that all cheats will work (some of them may start working).
=> Update TamperMachine and disable write-to-code prevention

Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs, Ryujinx.Graphics.Gpu/Engine/InlineToMemory/InlineToMemoryClass.cs
Makes more copies respect non-contiguous GPU virtual memory regions, instead of assuming it is contiguous. After this, the main thing missing will be support for non-contiguous buffers, which will be more complicated, and will be done on a separate PR.
This also fixes a bug that I noticed on I2M, where the copy would be incorrect for block linear textures, if destination X was not a multiple of 16. This was fixed by aligning the start of the vector copy, which should start and end of a multiple of 16. I'm not aware of any games that uses it with a X value that is not a multiple of 16 though (it is usually 0), so maybe nothing was affected by this bug.
=> Support non-contiguous copies on I2M and DMA engines

Ryujinx.Input/HLE/NpadController.cs
Xinput devices provides axis data with square ranges, ie +-32767. Moving the sticks to diagonal ends means that it will have the max range values for both axes. This causes fast motion of player characters in games that do not clamp their input. 
This fixes it by clamping the input to a circle. Fixes Link sprinting without using up stamina when the controller sticks are at diagonals
=> Clamp controller sticks to circle, instead of square

Ryujinx.Common/Configuration/Hid/KeyboardHotkeys.cs, Ryujinx/Config.json, Ryujinx/Configuration/ConfigurationFileFormat.cs, Ryujinx/Configuration/ConfigurationState.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade, Ryujinx/Ui/RendererWidgetBase.cs
This fixes #2502, which was a regression caused by #2411 (I'm sorry! 😅)
For one, Alt no longer focuses the menu bar (this is the part of my implementation that caused the issue). That functionality wasn't really relevant to the original intent of #2411, and the main purpose of the PR remains usable. Focus on Alt is something I might fix later, as I can't seem to figure out what broke it in the first place.
Secondly, this reworks the entire flow of how the "Show UI" hotkey works. Note that it is specifically a "Show UI" hotkey, and hiding the UI still has to be done via the Actions menu, as we don't want users to trigger it by accident (there was some relevant discussion in #2411).
1. It is now a legitimate entry in the `KeyboardHotkeys` struct, rather than being hacked on via …
=> Hide UI rework/arrow key fix

Ryujinx.HLE/Exceptions/ServiceNotImplementedException.cs, Ryujinx.HLE/HOS/Services/IpcService.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/INfp.cs, Ryujinx.HLE/HOS/Services/Nv/INvDrvServices.cs, Ryujinx.HLE/HOS/Services/Sockets/Nsd/IManager.cs, Ryujinx.HLE/HOS/Services/Time/ITimeServiceManager.cs
Noticed this whilst debugging another issue. Doesn't add much, but removes the need to pass in whether the command is a Tipc command or a Hipc command to the exception constructor.
=> hle: Tidy-up ServiceNotImplementedException

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Program.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/DefaultNames.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/TexelFetchScale_cp.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/TexelFetchScale_fp.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/SupportBuffer.cs, Ryujinx.Graphics.Shader/Translation/TranslationCounts.cs
Currently we have some "loose" uniforms on shaders that are being used for the texture scales, and the value that indicates if a texture is BGRA or not. They require a `glGetUniformLocation` to get the location the compiler assigned to them, and also requires setting the new uniform data every time the shader change. The motivator for this change though, was the fact those uniform variables are not support on SPIR-V, and I believe its better to handle things in a similar way between the backends. Plus, if we want to produce SPIR-V from GLSL, this change is necessary (otherwise it will fail to compile).
With the new approach, a single buffer that can fit everything (the render scales, IsBGRA, and a new alpha test field) is created. Data is written to the buffer using the current …
=> Replace BGRA and scale uniforms with a uniform block

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Gpu/Shader/ShaderDumpPaths.cs, Ryujinx.Graphics.Gpu/Shader/ShaderDumper.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/GlslGenerator.cs, Ryujinx.Graphics.Shader/Decoders/Decoder.cs, Ryujinx.Graphics.Shader/Decoders/IOpCodeAttribute.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeAttribute.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeIpa.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgramContext.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgramInfo.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs, Ryujinx.Graphics.Shader/Translation/TranslatorContext.cs
Sometimes, an shader attribute is consumed on a later stage, but the previous stage does not write it. On NVIDIA, all attributes that are not written to are initialized with a default value of (0, 0, 0, 1). This is not the case for other vendors however, and according to the spec, the values on them are "undefined". This causes problems for AMD and Intel as the attributes have different values.
The current approach taken is assuming all the first 16 attributes are used, so initializes the first 16.  That's because on desktop, usually only 16 attributes are supported (at least on OpenGL, Vulkan might allow more?). This causes shaders to fail to compile if the previous stage does not write the attribute at all. For example, one shader in Yo-kai Watch 4 fails to compile due to this, I'm not …
=> Make sure attributes used on subsequent shader stages are initialized

Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Image/TextureScaleMode.cs
There are a number of textures where it is definitely _possible_ to scale them, but we don't scale them due to the potential for wasted work (depth of field need not be high res) and undesired effects (blur shaders do not behave correctly when scaled, scaling texture atlases results in ugly linear blending blur).
This PR gives these types of texture a new scale mode, rather than blacklisting them entirely. This mode is "Undesired", as we don't _want_ to scale the texture, but if it's bound alongside another texture that is scaled, we'd rather scale them _both_ than blacklist and potentially lose res scale entirely.
- Games that reuse depth stencil between a lot of unrelated draws to textures of different sizes will no longer blacklist from scaling forever. (Bayonetta 2)
- Textures that …
=> Use "Undesired" scale mode for certain textures rather than blacklisting

Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.Gpu/Shader/CachedGpuAccessor.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessorBase.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Gpu/Shader/TextureDescriptorCapableGpuAccessor.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/GlobalToStorage.cs, Ryujinx.Graphics.Shader/Translation/Rewriter.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
This is a workaround for yet another bug on Intel where `gl_FrontFacing` returns incorrect values (it seems to be flipped?), the solution here is casting the bool to float and then bitcasting to integer and checking if its non-zero. The solution was found by trial and error, if someone knows a better way, please let me know.
Fixes rendering of mario mustache on Super Mario Odyssey on Intel (affects both Vulkan and OpenGL):
Before:
(Note that the screenshot is a bit old, the shadow glitch on cappy was already fixed).
After:
This also fixes the "dead" palette on Zelda Link's Awakening, however the game is not rendering correctly on OpenGL, so the fix is only visible on Vulkan.
Other changes here includes:
- Added 2 new functions to the IGpuAccessor interface, used to check if the host has …
=> Workaround for Intel FrontFacing built-in variable bug

Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.Shader/SupportBuffer.cs
Fixes a regression caused by #2496 when combined with #2537, that broke rendering on some cases due to the scale not being initialized.
=> Ensure render scale is initialized to 1 on the backend

Ryujinx/Ui/MainWindow.cs
We have a constant of `UserError.FirmwareParsingFailed`, which when used produces the following message:
> Ryujinx was unable to parse the provided firmware. This is usually caused by outdated keys.
This is a better description of the firmware installation problems that a lot of users face than the currently used `UserError.NoKeys`, that simply states:
> Ryujinx was unable to find your 'prod.keys' file
This PR changes the generated error message to the more relevant one.
=> Improve firmware install error due to outdated keys

Ryujinx.Graphics.Gpu/Memory/BufferManager.cs
Transform feedback buffers can be modified by the GPU, so they must have the `write` flag set to true to indicate they might have been modified.
Seems to fix vertex explosion in SNK Heroines Tag Team Frenzy.
Before:
After:
Worth noting that it seems somewhat random, but I was getting the same corruption with this character selection. There's still some vertex explosions on some special effects, but I suspect this is a different problem since those seems more consistent.
=> Enable transform feedback buffer flush

Ryujinx.HLE/FileSystem/EncryptedFileSystemCreator.cs, Ryujinx.HLE/FileSystem/VirtualFileSystem.cs
This prevents key errors from users changing their keys or sd seed. Adds a wrapper file system that deletes any files that were created with another key and uses a blank key for all AES-XTS file systems.
Fixes #2558
=> Always use an all-zeros key for AES-XTS file systems

ARMeilleure/CodeGen/Optimizations/Simplification.cs, ARMeilleure/Translation/PTC/Ptc.cs
`TryEliminateBitwiseAnd` would turn the `BitwiseAnd` operation into a copy of the wrong type. E.g:
Before `Simplification`:
```llvm
i64 %0 = BitwiseAnd i64 0x0, i64 %1
```
After `Simplication`:
```llvm
i64 %0 = Copy i32 0x0
```
Since the with the changes in #2515, we iterate in reverse order and `Simplication`, `ConstantFolding` does not indicate if it modified the CFG, the second pass to "retype" the copy into the proper destination type does not happen.
This also blocked copy propagation since its destination type did not match with its source type. But in the cases I've seen, the
`PreAllocator` would insert a copy for the propagated constant, which results in no diffs.
Since the copy remained as is, asserts are fired when generating it.
=> Fix type mismatch in `BitwiseAnd` simplification

Ryujinx.HLE/FileSystem/EncryptedFileSystemCreator.cs, Ryujinx.HLE/HOS/LibHacHorizonManager.cs
Cleaning the directories ended up being the best solution because none of these three other options when encountering a file with a different key worked with every program's file system handling logic. Fixes Ryujinx/Ryujinx-Games-List#3678
- Deleting the file
- Deleting the file and creating an empty one
- Deleting the file and creating one of the same size
=> Clean the SD card save directory when opening the emulator

Ryujinx.Graphics.GAL/Format.cs, Ryujinx.Graphics.OpenGL/FormatTable.cs, Ryujinx.Graphics.OpenGL/Image/TextureCopy.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Window.cs
This is similar to #1418, but handles packed 16-bit texture formats instead of 32-bit ones. Namely this one does the R<->B swap trick with the B5G6R5 and B5G5R5A1 formats. I forgot that you can actually render to those too back then.
This fixes the blue and red swapped issue on Pokkén Tournament DX.
Before:
After:
The A1B5G5R5 format seems wrong aswell, but this one is not as simple to fix as all components needs to be swapped rather than just R and B.
Also fixes a similar issue on Pokémon Stadium on Super Smash Bros Ultimate:
Fixes #2093.
Side note: All the different component ordering between the APIs and documentation is an eternal source of confusion to me.
=> Swap BGR components for 16-bit BGR texture formats

Ryujinx.Memory/Tracking/RegionHandle.cs
This fixes a regression that occurred when allowing tracking actions to release the tracking lock. If multiple threads were to trigger a read action in the same handle at the same time, then it was possible for one of the threads to continue almost immediately without flushing, as the action would have been consumed on the other. This would result in the thread that skipped the action either reading/writing old data, then the action would complete and overwrite it, causing weird issues.
The fix is just to replace the _preAction consumption with a handle level lock. The action is not set as null until it completes, and the lock prevents multiple threads from triggering the action.
This was causing crashes in catherine full body.
=> Ensure that all threads wait for a read tracking action to complete.

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.Texture/Region.cs, Ryujinx.Graphics.Texture/SizeInfo.cs
It's possible that while two textures start and end addresses indicate an overlap, that the actual data contained within them is sparse due to a layer stride. One such possibility is array slices of a cubemap at different mip levels - they overlap on a whole, but the actual texture data fills the gaps between each other's layers rather than actually overlapping.
This fixes issues with UE4 games having incorrect lighting (solid white screen or really dark shadows). There are still remaining issues with games that use the 3D texture prebaked lighting, such as THPS1+2, and games that use SUATOM/SURED like BD2 and Triangle Strategy.
This PR also fixes a bug with TexturePool's resized texture handling where the base level in the descriptor was not considered. This was causing data loss in some …
=> Avoid deleting textures when their data does not overlap.

Ryujinx.Cpu/IVirtualMemoryManagerTracked.cs, Ryujinx.Cpu/MemoryManager.cs, Ryujinx.Graphics.Gpu/Engine/MME/MacroHLE.cs, Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs, Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs
This addresses one of the TODOs from #2557. If the first draw is non-zero, we need to calculate a correct maximum draw count in order to only do the missing draws, or just do nothing if all draws were already done.
In addition, this includes a few other improvements:
- The `Read<T>` method on the memory manager now takes an optional `tracked` argument to flush on read. This is required to flush the draw count.
- The `Read<T>` method now calls `Read<T>` on the "physical memory" instead of `GetSpan`, to avoid casting the span etc. Should have better codegen.
- Software `MemoryManager` `Read<T>` is no longer tracked (as it was never supposed to be, only `ReadTracked<T>` should be tracked). Should be a low risk change as we use the host mapped memory manager by default (which should already …
=> Handle indirect draw counts with non-zero draw starts properly

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/Shuffle.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/ShuffleDown.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/ShuffleUp.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/ShuffleXor.glsl
Fixes some issues with thread shuffles, mainly shuffle up that was not taking negative threads IDs into account. If the source thread ID is negative after the subtraction by the index, it is *not* valid (but it was returning valid before because the comparison was unsigned, and 0xFFFFFFFF (-1) for example, is >= 0. I also made it *always* read the value from the source thread, rather than doing it conditionally, as the latter also caused graphical glitches.
Fixes vertex explosion on Marvel Ultimate Alliance 3.
Now:
When combined with #2090, also fixes block flickering on shadows. See screenshots below.
master:
(Lighting is broken, water is dark etc).
riperiperi's PR without this fix:
(Lighting works but flickers, see the lamp pole only being half lit, the water with …
=> Fix out-of-bounds shader thread shuffle

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenHelper.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeSuatom.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeSured.cs, Ryujinx.Graphics.Shader/Decoders/OpCodeTable.cs, Ryujinx.Graphics.Shader/Decoders/ReductionType.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/Instruction.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/TextureFlags.cs, Ryujinx.Graphics.Shader/StructuredIr/InstructionInfo.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/Optimizer.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
Fixes morph target animation (used for facial animations, eyes) and anything else using atomic image store (probably on buffer textures) in UE4 games. Should affect BD2 and I think Trials of Mana. Yoshi's Crafted World uses these, but I'm not sure what for. May affect other games.
envytools and nvdisasm were used to determine the opcode formats. 
BD2 example:
https://user-images.githubusercontent.com/6294155/110537362-81b22280-811a-11eb-845b-bd67aba491f3.mp4
https://user-images.githubusercontent.com/6294155/110537430-91316b80-811a-11eb-91cf-aa62db561999.mp4
Note: Currently does not support FP or 64-bit types (which may not even exist for textures). Not sure if we should, but that's why the PR is currently draft.
=> Implement Shader Instructions SUATOM and SURED

Ryujinx.Graphics.Gpu/Image/TextureTarget.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Gpu/Shader/TextureDescriptorCapableGpuAccessor.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/TextureOperation.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
Assumes the texture is 3D if the component mask contains Z.
This fixes a bug in UE4 games where parts of the map had garbage pointers to lighting voxels, as the lookup 3D texture was not being initialized. Most notable game is THPS1+2.
May need another PR to keep image store data alive and properly flush it in order using the AutoDeleteCache.
=> Fix TXQ for 3D textures.

Ryujinx/Ui/MainWindow.cs
Game metadata (specifically, time played staying at 0s was the obvious symptom) was not being updated when clicking Actions->Stop Emulation. This works as expected when exiting the emulator because UpdateGameMetadata is called from MainWindow.End, which is called from both Exit_Pressed  and Window_Close.
This PR updates the game metadata in this case
=> Update game metadata when stopping emulation

Ryujinx/Input/GTK3/GTK3MappingHelper.cs
The single quote key (') was incorrectly mapped to the gtk key quotedbl. This fixes #2514
=> Fix GTK3 mapping for single quote key

Ryujinx.Graphics.Gpu/Engine/Twod/TwodClass.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs
Before, this would only apply to render targets and texture blit. Now it applies to image stores, the fast dma copy path and any other type of modification.
Image store textures always have at least one reference in the texture pool, so the function of the AutoDeleteCache keeping textures _alive_ is not useful, but a very important function for a while has been its use to _flush textures in order of modification_ when they are dereferenced, so that their data is not lost.
Before, textures populated using image stores were being dereferenced and reloaded as garbage. Now, when these textures are dereferenced, their data will be put back into memory, and everything stays intact.
Fixes lighting breaking when switching levels in THPS1+2, and potentially some more UE4 games. I've tested a bunch …
=> Lift textures in the AutoDeleteCache for all modifications.

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ICommonStateGetter.cs
The `GetDefaultDisplayResolution` function was returning a 720p resolution even when docked. While I believe this is technically not incorrect, most of the benefit of enabling docked mode on the emulator is getting a higher resolution, so I believe increasing the resolution in this case is desirable.
Note that there are a bunch of other functions where a 720p resolution is hardcoded, namely: `GetDisplayMode`, `GetDisplayResolution` and `ListDisplays`. I can also switch up to 1080p in all those functions when docked, but I'm not sure if that's the correct behaviour, so at this time I have left it as is, but can change if anyone think it's better or can confirm that doing so is the correct behaviour.
Allows Tsukihime -A piece of blue glass moon- to render at higher resolution when docked. …
=> Report 1080p resolution when in docked mode

Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/NvHostAsGpuDeviceFile.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/Types/GetVaRegionsArguments.cs
This implements the `GetVaRegions` ioctl, which is used to get the ranges of the address space that the application can actually use. It returns two ranges, one for small pages and one for big pages. The Vulkan driver uses this to calculate the usable address space size (calculated as the maximum end address of all VA regions returned). Since it was not writing anything before, I believe it could just return stack garbage.
This fixes a crash on Quake due to `VK_ERROR_OUT_OF_DEVICE_MEMORY` being returned by the guest driver, caused by the fact that it assumed that the usable address space size was 0, which would fail the check for any buffer size that is greater than 0.
The game can progress further now, but crashes due to Sockets issues.
I recommend testing this on a few games as Im not …
=> Implement GetVaRegions on nvservices

Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs, Ryujinx.Graphics.Gpu/Engine/InlineToMemory/InlineToMemoryClass.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Texture/OffsetCalculator.cs
Some OpenGL games (such as https://github.com/Ryujinx/Ryujinx-Games-List/issues/3704) are using negative stride values. This would cause the copy to advance backwards, which I imagine might be useful if the copy is also supposed to flip the image vertically. This should actually "just work" with our simple offset calculation, but does not due to the fact that the current code uses spans, and the code to get the span is not aware of the fact the stride (and consequently the size) might be negative.
To account for that, the following changes were made.
- `Math.Abs` is used on the stride to calculate the size, to ensure it is positive.
- If stride is negative, the base offset is adjusted to the real start offset of the copy.
Nothing else needs to be changed, as the base pointers and the …
=> Account for negative strides on DMA copy

Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/Widgets/GameTableContextMenu.cs, Ryujinx/Ui/Windows/DlcWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.cs, Ryujinx/Ui/Windows/TitleUpdateWindow.cs, Ryujinx/Ui/Windows/UserProfilesManagerWindow.cs
We currently use the FileChooser from GTK, which is a bit mess. Instead of it we could use the native FileChooser from all specifics OS. This is what this PR attempt to fix.
It could be nice to get a test under linux since I've only tested it under Windows without any issues.
Fixes #2584 and fixes #2530
=> gui: Replace FileChooserDialog with FileChooserNative

Ryujinx/Ui/Widgets/GameTableContextMenu.cs
Fix a regression introduced in #2633, FileChooserNative parent can't be set to null because it's running in modal.
=> gui: Hotfix for FileChooserNative during section extraction

Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs, Ryujinx.Audio/Renderer/Server/AudioRendererManager.cs, Ryujinx.HLE/HOS/Horizon.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade
This PR fixes two problems :
- Hiding Pause/Resume entry in Action menu doesn't work properly after switching fullscreen mode. With this PR, the entries are always shown but contextually disabled
- Since #2428, Ryujinx can't be properly closed because of a remaining audio thread. This should be fixed now.
=> Fix problems added by Pause

Ryujinx.Graphics.Gpu/Engine/Compute/ComputeClass.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs
This was allocating multiple arrays per draw or compute invocation. Noticed it on a profile, its cost was significant but not mind blowing. Figured like the other change, removing these allocations might have some small effects on performance outside this method. Good to remove costs like this either way.
I've changed the SetTextures and SetImages method to instead rent the bindings array for modification, now called RentTextureBindings, which is in charge of ensuring the arrays are the correct size, and clearing the state arrays. This is done to set the data directly, rather than allocate or copy into the bindings manager. 
They now use arrays that are pre-allocated with a default size, but can be increased in size to fit shaders that bind way more textures, such as bindless accesses.
=> Set texture/image bindings in place rather than allocating and passing an array

Ryujinx.Graphics.Gpu/Memory/BufferModifiedRangeList.cs, Ryujinx.Memory/Range/RangeList.cs, Ryujinx.Memory/WindowsShared/EmulatedSharedMemoryWindows.cs, Ryujinx.Memory/WindowsShared/PlaceholderList.cs
This PR changes the RangeList to cache the Address and EndAddress within the list itself rather than accessing them from the object's properties. It also changes the RangeList to be backed by an array containing structs with the above information, back to back. This improves memory locality when binary searching through the array list, so I reckon it'll avoid slow cache misses from jumping to a bunch of resources miles apart to check their address and end address. It might cost more to add or remove items to large lists, but our use case is mostly searching.
This array list is used in a few places: Memory tracking, windows emulated view + placeholder tracking, buffer modified list and buffer lookup. It's this last use that is most important - we were losing quite a bit of time looking up …
=> Array based RangeList that caches Address/EndAddress

Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Gpu/Shader/TextureDescriptorCapableGpuAccessor.cs, Ryujinx.Graphics.OpenGL/HwCapabilities.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/Shuffle.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/ShuffleDown.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/ShuffleUp.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/ShuffleXor.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/SwizzleAdd.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenBallot.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenHelper.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs
Uses new subgroup extension (that AFAIK were introduced for SPIR-V) if the old `ARB_shader_ballot` extension is not supported. This is required for Vulkan. Additionally, this benefits Intel on OpenGL as they don't support the `ARB_shader_ballot` extension on the proprietary driver for some reason, but does support the new extensions.
Games that makes use of shuffles and lane ID access and masks should work better on Intel Windows OpenGL now.
For example, Astral Chain works on Intel OpenGL now.
Before:
After:
Other vendors should not be affected as they support the shader ballot extension (which is still preferred).
=> Use shader subgroup extensions if shader ballot is not supported

Ryujinx.Common/Collections/IntervalTree.cs, Ryujinx.Common/Collections/TreeDictionary.cs, Ryujinx.Memory/Range/MultiRangeList.cs
This PR implements an augmented interval tree based off of the existing TreeDictionary and uses it for the MultiRangeList. This greatly speeds up texture overlap checks, as they can't use the non-overlapping fast path that buffers and tracking handles can use. Like the tree dictionary, it is based on a red-black tree and is self balancing.
This supports multi-ranges by inserting the resource into the interval tree multiple times; one for each sub-range. When searching for a range with multiple subranges, multiple queries are made and the results are merged.
Fixes a potential performance regression with #2624, as checking if a texture is in a range becomes much cheaper (5% -> 0.02%). This will also speed up texture/view creation, and notifying textures that they have been unmapped, which …
=> Implement and use an Interval Tree for the MultiRangeList

Ryujinx.Graphics.Gpu/Engine/InlineToMemory/InlineToMemoryClass.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs
This PR adds a method to PhysicalMemory that attempts to write all cached resources directly, so that memory tracking can be avoided. The goal of this is both to avoid flushing buffer data, and to avoid raising the sequence number when data is written, which causes buffer and texture handles to be re-checked.
It just uses the existing ForceDirty method that is used for updating buffer data with the ConstantBufferUpdater. This avoids going through the tracking structure, reprotection and triggering read actions. The last part is the most important - as we know the exact range being written to, we don't need to flush the entire pages that we're writing to - just punch a hole in the "modified" ranges and write the data directly.
This currently only targets buffers, with a side check on …
=> Fast path for Inline2Memory buffer write that skips write tracking

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs
Fixes an issue where scales might not be properly updated on games that uses compute. The issue happens because the backend is using a single array to store both fragment and compute scales, while the GPU emulation is using 2 (and is working with the assumption that the backend also uses 2). This change simply shares the same array for both compute and graphics, which solves the problem and the scale changing on one will also force the other to be updated later.
This fixes resolution scale issues on NI no Kuni 2:
Before:
After:
This might potentially also fix the resolution scale regression that was reported on Discord on Mario Rabbids Kingdom Battle, but I did not test it myself.
This is potentially a regression caused by #2595, but I did not confirm.
=> Share scales array for graphics and compute

Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs, Ryujinx.HLE/HOS/Services/Hid/Irs/ResultCode.cs, Ryujinx.HLE/HOS/Services/Hid/Irs/Types/ImageTransferProcessorState.cs, Ryujinx.HLE/HOS/Services/Hid/Irs/Types/IrCameraHandle.cs, Ryujinx.HLE/HOS/Services/Hid/Irs/Types/PackedClusteringProcessorConfig.cs, Ryujinx.HLE/HOS/Services/Hid/Irs/Types/PackedImageTransferProcessorConfig.cs, Ryujinx.HLE/HOS/Services/Hid/Irs/Types/PackedMomentProcessorConfig.cs, Ryujinx.HLE/HOS/Services/Hid/Irs/Types/PackedTeraPluginProcessorConfig.cs
This PR stubs some irs service calls which are needed to get some games playable or at least bootable since we don't support IR data throught real JoyCon for now.
- Stubs `IIrSensorServer` `StopImageProcessor`, `RunMomentProcessor`, `RunClusteringProcessor`, `RunImageTransferProcessor`, `GetImageTransferProcessorState`, `RunTeraPluginProcessor`. All calls are a bit checked by RE.
Closes #2267, Closes #2248, Closes #2126
Night Vision and Spy Alarm are now bootable (but still unplayable due to the lack of the IR data):
Doukoku Soshite... is now playable:
And probably some other games...
=> irs: Stub some service calls

ARMeilleure/Translation/PTC/Ptc.cs
Fix an issue introduced in #2190 where by 2 different count table entry addresses were used for LCQ functions. E.g:
```asm
.L1:
mov rbp,COUNT_TABLE_0   ;; This gets an address.
mov ebp,[rbp]
lea esi,[rbp+1]
mov rdi,COUNT_TABLE_1   ;; This gets another address.
mov [rdi],esi
cmp ebp,64h
je near .L34
```
This caused LCQ functions to not tier up when they're loaded from the PTC cache. This does not happen when they're freshly compiled.
This PR fixes the issue by ensuring only a single counter is created per translation when they're loaded from the cache.
=> Fix PTC count table relocation patching

ARMeilleure/Instructions/InstEmitSystem.cs, ARMeilleure/Translation/PTC/Ptc.cs
Seems like this is used as an optimized way to clear memory in homebrew applications. Unfortunately, calling the software fallback method every 8 bytes was not very optimal.
The existing EmitStore is used by passing in ZR as the register to get a 0 write.
=> Use normal memory store path for DC ZVA

ARMeilleure/CodeGen/RegisterAllocators/HybridAllocator.cs, ARMeilleure/CodeGen/X86/CodeGenerator.cs, ARMeilleure/IntermediateRepresentation/Operand.cs, ARMeilleure/IntermediateRepresentation/Operation.cs
This brings a set of optimizations to the `HybridAllocator` which increases the throughput of LCQ, and usually shaves a couple of seconds from boot time. I also disabled `BlockPlacement` in LCQ to get some extra throughput since with the host mapped memory manager, there is a lot less cold code to split from hot code.
=> Optimize `HybridAllocator`

Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClass.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Shader/Cache/Definition/HostShaderCacheEntry.cs, Ryujinx.Graphics.Gpu/Shader/Cache/Definition/HostShaderCacheEntryHeader.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/ShaderProgramInfo.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, Ryujinx.Graphics.Shader/Translation/FeatureFlags.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
There are some cases where games have bogus values written as the render target texture depth. This can cause very large 2D array textures to be created, which not only is bad for performance, but can also cause OOM and other issues.
Usually the non-base layers of the texture doesn't are not accessed at all, as it will only render to a single layer. It only matters when the shader writes to `gl_Layer` with a non-zero value. Doing so will modify the target layer. Knowing this, I have modified the code to only ever use 2D array when one of the VTG (vertex, tessellation or geometry) shaders writes to `gl_Layer`.
This fixes #2628 which was caused by an 1080p array texture with 257 layers (which would take several GBs of memory and cause all sorts of issues). …
=> Only make render target 2D textures layered if needed

Ryujinx.Graphics.Gpu/Image/AutoDeleteCache.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Graphics.Gpu/Image/TextureGroupHandle.cs
When a texture is deleted by falling to the bottom of the AutoDeleteCache, its data is flushed to preserve any GPU writes that occurred. This ensures that the data appears in any textures recreated in the future, but didn't account for a texture that already existed with a copy dependency.
This change forces copy dependencies to complete if a texture falls out from from the AutoDeleteCache. (not removed via overlap, as that would be wasted effort) This is done via a full sync of the storage texture right now, as that's the best way to ensure all the rules are followed.
Fixes broken lighting caused by pausing in SMO's Metro Kingdom. May fix some other infrequent issues. 
I'd recommend testing games that do a lot of render to texture / copies, like 1st party games and UE4 games.
(too …
=> Force copy when auto-deleting a texture with dependencies

Ryujinx.Graphics.Nvdec.H264/FFmpegContext.cs
Fix memory leaks that started happening while playing some videos after #2671.
=> Unref frames before decoding with FFMPEG

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs
Right now, the emulator will print an error and exit early if an attempt is made to use textures without having a sampler pool currenntly bound. That is because accessing a texture without a sampler is usually not valid. But there are one case where the sampler is not needed, which is when textures are accessed with `texelFetch`, as those are not filtered in any way.
This is usually not a problem, because it's not common for a game to only ever use `texelFetch`, but it turns out Cotton Guardian Force does this. This change allows the texture to be bound without a sampler, which improves rendering on this title.
Before:
With this PR:
I also investigated the weird lines above, as it looked like an issue that could be caused by incorrect sampling, but it wasn't. Instead, it was caused by the …
=> Relax sampler pool requirement

Ryujinx.Graphics.Gpu/Memory/Buffer.cs, Ryujinx.Graphics.Gpu/Memory/BufferModifiedRangeList.cs, Ryujinx.Memory/Range/RangeList.cs
This fixes a potential regression with the new range list changes, where the cost for creating new ones would be rather large due to creating a 1024 size array. Also reduces cost for range list inheritance by using the first existing range list as a base, rather than creating a new one then adding both lists to it.
The growth size for the RangeList is now identical to its initial size. Every 32 elements was probably a little too common - now it is 1024 for most things and 8 for the buffer modified range list.
The Unmapped and SyncMethod methods have been changed to ensure that they behave properly if the range list is set null. Cleaned up a few calls to use the null-conditional operator.
=> Smaller initial size for BufferModifiedRangeList & directly inherit backing array

Ryujinx.HLE/HOS/Services/Vi/RootService/ApplicationDisplayService/Types/DisplayInfo.cs, Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
Fixes a regression caused by #2640. The `DisplayInfo` struct was incorrect, the `Array40` struct was used for the name fixed buffer, that has a size of 0x40 bytes. However, the size on the `Array` struct name is decimal, not hexadecimal, so the correct type here is `Array64`.
Fixes regression that would cause Dragon Ball Xenoverse 2 to no longer boot, as it would pass a invalid size of 0 to surface flinger initialization, which would later cause other failures.
I also removed the `Fill` call as it was useless, the `Write` already writes all the 0x60 bytes. Also fixed the write address, that was not taking the current `i` value into account, although it was not an issue right now as only one entry is ever written on `ListDisplays` currently.
=> Fix DisplayInfo struct

Ryujinx.Graphics.Gpu/Synchronization/SyncpointWaiterHandle.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostCtrl/Types/NvHostEvent.cs
It seems that #2739 introduced timeouts where they didn't exist before. This might be because before this change, it could return without waiting in some cases (which is not correct). After the change that allows it to actually wait properly, things like shader compilation started causing timeouts which makes some game assert. Now the CPU waits are supposed to prevent this, and I assumed they could never timeout since it passes a infinite timespan, but...
```cs
// TODO: Remove this when GPU channel scheduling will be implemented.
if (timeout == Timeout.InfiniteTimeSpan)
{
timeout = TimeSpan.FromSeconds(1);
}
```
This codes forces the timeout to 1s when it is infinite, so it *might* timeout. So to fix this, I changed it to return "false" even when there is a timeout, to avoid guest …
=> When waiting on CPU, do not return a time out error from EventWait

Ryujinx.Graphics.GAL/TextureCreateInfo.cs, Ryujinx.Graphics.OpenGL/Image/TextureStorage.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs
This clamps the amount of levels to avoid OpenGL errors on textures with an invalid number of mipmap levels. I'm not aware of any commercial game which such error, but there are some mods that do use an invalid mipmap level count for some reason, and that causes the textures to be solid black as the texture initialization will fail. The PR fixes this issue.
While technically the mod is incorrect, I think it's fine to do this on our side as the actual GPU will not attempt to validate the levels count, so the texture would work there.
=> Clamp number of mipmap levels to avoid API errors due to invalid textures

Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostChannel/NvHostChannelDeviceFile.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostChannel/NvHostGpuDeviceFile.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostCtrl/NvHostCtrlDeviceFile.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostCtrl/Types/NvHostEvent.cs
First, fixes syncpoints not being released when the channel is closed. This fixes this error:
```
Cannot allocate a new syncpoint!
```
that would be printed on the log on games that creates lots of channels. I'm not sure what the effect of this syncpoint allocation failing was, but it did not cause games to crash as far I can tell.
The second issue this fixes is event handles not being closed. In special those returned by `QueryEvent`. This was causing Legend of Mana and maybe other games to crash with the "Out of handles!" exception. This should be also fixed now, as events are closed when the channel is closed, or when the event is unregistered.
I recommend testing a few games to be sure nothing regressed.
Closes #2809.
=> Ensure syncpoints are released and event handles closed on channel close

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitMove.cs
This fixes a regression introduced on #2534 where shaders would be generated trying to access `gl_PatchPrimitivesIn` on geometry shaders, because the invocation info system register is accessed on those shaders, however this built-in can only be accessed on tessellation evaluation shaders according to the spec.
Also contains a fix for another issue I found while testing this, bindless images with unknown handle source uses a 0 constant right now. However, it was using a float constant for images with integer formats, which is incorrect. Change it to use the proper integer type, this fixes some shader compilation errors.
The first issue apparently doesn't affect NVIDIA, as apparently their compiler doesn't complain on OpenGL and it "just works".
On AMD and Intel, this fixes a regression …
=> Fix InvocationInfo on geometry shader and bindless default integer const

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/Utils.cs
This fixes bindless texture elimination with inverted predicates (like `@!P0`). Before, it was working with the assumption that the branch would always enter the predicated block if the condition is true, but this is not exactly the case. What the branch does is skip the predicated instruction if the condition is false. So for non-inverted predicates, it will skip it if the condition is *false*, and for inverted ones, it will skip it if the condition is *true* (as if it is false, then the instruction is supposed to execute). In both cases, the branch not taken case is where it enters the block, so in both cases, the `Next` block is the one that should match the Phi incoming block.
This fixes lighting issues on Disaster Report 4, and maybe other games. Should also allow global memory SSBO …
=> Fix bindless/global memory elimination with inverted predicates

Ryujinx/Ui/Windows/SettingsWindow.glade
The "help hint" of Settings > Input > Direct mouse access has the wrong text, referring to the keyboard instead of the mouse, and this 1-line quick PR addresses that
=> Fix direct mouse access checkbox label

Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, Ryujinx.Graphics.Gpu/Image/Sampler.cs, Ryujinx.Graphics.Gpu/Image/SamplerPool.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs
There's a major flaw with the anisotropic filtering setting that causes @GamerzHell9137 to report graphical bugs that otherwise wouldn't be there, because he just won't set it to Auto. This should fix those issues, hopefully.
These bugs are generally because anisotropic filtering is enabled on something that it shouldn't be, such as a post process filter or some data texture. This PR maintains two host samplers when custom AF is enabled, and only uses the forced AF one when the texture is 2d and fully mipmapped (goes down to 1x1). This is because game textures are the ideal target for this filtering, and they are typically fully mipmapped, unlike things like screen render targets which usually have 1 or just a few levels.
This also only enables AF on mipmapped samplers where the filtering …
=> Limit Custom Anisotropic Filtering to mipmapped textures with many levels

Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/INfp.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/VirtualAmiibo.cs
*Totally not a joke to an earlier implementation*
Instead of the user being a blank "No Name", I decided to attempt to change a Todo to be actually functional now that we have UserProfiles. Now when amiibos request to have their owner's name, instead of "No Name" being used, it uses the name of the current profile!
=> Nickname! - Init Amiibos with Profile's name!

Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs
This contains some of the changes on #2458, where it reads the depth range from the register when it determines it can't guess it from the depth near/far + translate values. On top of that, it adds another case where it uses the register, which is when both near and far values are 0, as in this case too the assumption that `TranslateZ = (Near + Far) / 2` for -1 to 1 and `TranslateZ = Near` for 0 to 1 no longer holds, as 0 divided by 2 is still 0, so there's no way to tell the depth range in this case using this method.
This improves rendering of Bastion on OpenGL:
Fixes #1628.
=> Better depth range detection

Ryujinx.HLE/HOS/Kernel/Common/KSystemControl.cs, Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs
Add basic support for the CFI value being passed in X18 since 11.0.0 by the official kernel.
We do not implement any random generator atm in the kernel and as such the KSystemControl.GenerateRandom function is stubbed.
=> kernel: Add support for CFI

Ryujinx.HLE/HOS/Kernel/Common/KTimeManager.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
This PR corrects some mistake while comparing my reversing of kernel 13.x with our own.
``WaitAndCheckScheduledObjects`` timing accuracy was also improved.
=> kernel: Fix sleep timing accuracy

Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx/Ui/Windows/DlcWindow.cs
If a DLC file goes missing, the user can't even open the DLC dialog to fix it, which leads to bad user experience. This PR adds File.Exists() checks to both the DLC dialog window and the content loader to ignore missing files rather than crashing the program.
=> Don't blow up everything if a DLC file is moved or renamed.

Ryujinx.HLE/HOS/Services/Nfc/Nfp/VirtualAmiibo.cs
The .NET 6 changes ended up causing a difference in the way we deserialise and would end up deserializing wrongly.
This PR fixes it by restoring the previous behaviour while still fixing the illink warning that caused that change in the first place.
=> Fix Amiibo hanging since .NET 6 changes

Ryujinx/Ryujinx.csproj
https://github.com/Ryujinx/Ryujinx/commit/39f171ece5df6ba07f1d4a5aaf6f3026ce15833e added ``alsoft.ini`` to fix issues on headphones on WIndows for OpenAL Soft.
However, ``alsoft.ini`` was supposed to only be deployed on Windows releases, and is in fact [not supported by OpenAL Soft on Linux](https://github.com/kcat/openal-soft/blob/f963a2c543a35edf4810c5a1c106d6162e51b274/alc/alconfig.cpp#L365-L361).
This PR add a condition check to avoid adding it to Linux releases.
=> misc: Fix alsoft.ini being present on Linux releases

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/NumberFormatter.cs, Ryujinx.Graphics.Shader/Instructions/InstEmit.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitConversion.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitFloatArithmetic.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitFloatComparison.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitFloatMinMax.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitHelper.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitMultifunction.cs, Ryujinx.Graphics.Shader/StructuredIr/InstructionInfo.cs, Ryujinx.Graphics.Shader/Translation/EmitterContextInsts.cs
Changes:
- Implements remaining double instructions: DMNMX, DSET and DSETP.
- Implements remaining double-precision operations on MUFU instruction: RCP64H and RSQ64H.
- Fix immediate operands on all double-precision instruction. Before it was being interpreted as a the higher 20-bits of a float value converted to double, when it should be the higher 20-bits of a double value.
I know that World War Z uses the DSET/DSETP instruction, but I don't know which impact those changes would have on this title, and I don't know many other games using them, as double-precision is rarely used on shaders for performance reasons.
=> Implement remaining shader double-precision instructions

ARMeilleure/ARMeilleure.csproj, ARMeilleure/Signal/UnixSignalHandlerRegistration.cs, Ryujinx.Memory/MemoryManagementUnix.cs, Ryujinx.Memory/MemoryManagerUnixHelper.cs, Ryujinx.Memory/Ryujinx.Memory.csproj, Ryujinx/Modules/Updater/UpdateDialog.cs, Ryujinx/Modules/Updater/Updater.cs, Ryujinx/Program.cs, Ryujinx/Ryujinx.csproj
This remove the usage of the ``Mono.Posix.NETStandard`` package, saving ~1.5MB on releases and removing an external C library.
Need testing on Linux.
=> Remove usage of Mono.Posix.NETStandard accross all projects

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitSurface.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs
When the register is RZ, it should set the destination operand to null, because setting it to a constant of zero would cause it to generate `0 = ...;` which is obviously not valid GLSL code. I found the issue only on SUATOM, but other texture instructions also had a similar issue, but unlike SUATOM, I don't think it would be ever RZ on  regular shader code, as doing a texture sample but discarding the results makes no sense.
I'm not sure which games this affects as this bug was found using a fuzzer. Testing is welcome.
=> Fix SUATOM and other texture shader instructions with RZ dest

ARMeilleure/Decoders/OpCodeTable.cs, ARMeilleure/Instructions/InstEmitMemoryEx32.cs, ARMeilleure/Instructions/InstEmitSimdMemory32.cs, ARMeilleure/Instructions/InstName.cs
> Consumption of Speculative Data Barrier is a memory barrier that controls speculative execution and data value
prediction.
Implemented as no-op since that's how it should behave on the Switch CPU. This instruction has been added in new-ish Arm processors to mitigate side-channel attacks that takes advantage of the processors speculative execution. The Switch CPU does not actually support, on an older version of the Arm architecture reference manual, this encoding is documented to be a reserved hint instruction that should execute as NOP.
This is required by Monster Rancher 1 & 2 DX, which now works.
Fixes #2918.
=> Implement CSDB instruction

Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClass.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClassState.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.OpenGL/Image/TextureBuffer.cs
This PR fixes the following issues:
- Outdated descriptors were used in some cases, because the `SequenceNumber` optimization, intended to avoid checking for memory modifications when not necessary made it miss some updates. To fix this, the GPU methods `InvalidateTextureHeaderCacheNoWfi` and `InvalidateSamplerCacheNoWfi` were added, and now increments the `SequenceNumber`. Said methods *should* be called to invalidate the GPU caches for those pools on the Switch, so we can take advantage of that and note that they were probably modified.
- `CommitTextureBindings` and `CommitImageBindings` would try to bind *buffer textures* before setting the buffer storage. This causes an OpenGL error the first time the texture is used, because it has not been initialized at this point (with a call to …
=> Fix for texture pool not being updated when it should + buffer texture fixes

Ryujinx.HLE/HOS/Kernel/SupervisorCall/SyscallTable.cs
We get people asking how to fix the "PortRemoteClosed" error all the time. This removes the warning as the result is not really an error, it is a normal result that is returned under normal operation, when a service session is closed. Now the result is only printed as "Debug" level, like the other non-Success results that happens under normal operation.
=> Remove PortRemoteClosed warning

Ryujinx.Audio/Common/AudioDeviceSession.cs
Fixes what I assume to be an oversight that caused buffers to be enqueued (and played) more than once, if the game appended them fast enough.
Fixes audio in the Youtube app. Might potentially fix games with broken audio too.
=> Fix bug causing an audio buffer to be enqueued more than once

Ryujinx.HLE/HLEConfiguration.cs, Ryujinx.HLE/HOS/Services/Nifm/StaticService/IRequest.cs, Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs, Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdSocketFlags.cs, Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs, Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfo4.cs, Ryujinx.HLE/Switch.cs, Ryujinx.Headless.SDL2/Options.cs, Ryujinx.Headless.SDL2/Program.cs, Ryujinx/Configuration/ConfigurationFileFormat.cs, Ryujinx/Configuration/ConfigurationState.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.glade
This fixes several issues related to the sockets implementation:
- `GetAddrInfoWIthOptions` was incorrect, as the output layout is different from `GetAddrInfo`. On the former, the `serializedSize` is actually the *first* field on the output, and not the last. Before any games trying to use this function would just not receive anything from SDK side, as it would think the serialized size is 0 and thus theres no data to be read. This has been fixed which allows DNS lookup to actually work.
- `Socket.Connect` would return the error `EAGAIN` if an attempt was made to connect with a non-blocking socket. That is because those will make an async connection, and Winsocks/the .NET wrapper returns `WSAEWOULDBLOCK` in this case, which is translated to the Linux error `EAGAIN`. But that is incorrect …
=> Fix GetAddrInfoWithOptions and some sockets issues

Ryujinx.Graphics.Gpu/Engine/InlineToMemory/InlineToMemoryClass.cs
Data can only be pushed 4 bytes at a time, so for this reason, the data for each line must be aligned to 4 bytes on submission, even if the line length is not a multiple of 4 (as is the case for < 4 bpp formats for example). This was not being taken into account, which caused the padding bytes to be copied into the next lines.
This fixes some texture corruption on OpenGL games (only OpenGL games will be affected, NVN does not use this at all).
Fixes subtitle text in Cat Girl Without Salad:
Before:
After:
Also fixes a similar issue on the Youtube app.
=> Fix I2M texture copies when line length is not a multiple of 4

Ryujinx/Configuration/ConfigurationState.cs
The default configuration was missing the audio volume setting, causing updated config files to have their volume level set to 0. This PR sets the default volume level to 1 (100%) as it should have been when volume PR was created.
=> Fix missing default value of audio volume.

Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Texture/LayoutConverter.cs
The copy could be out of bounds before if `xCount` was less than stride, as the span size is calculated based on the stride and `xCount` (so it could be missing a few bytes at the end). This change makes it not copy any more than `xCount`. I'm not sure if the fast path should be used in this case though, as technically the data of the few missing pixels would be just 0.
This fixes some random crashes in the Youtube app and maybe some other games that does DMA copy with linear source textures.
Testing to ensure that it did not regress any game is welcome.
=> Fix DMA copy fast path line size when xCount < stride

Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceSession.cs
Instead of recreating the stream every time the buffer sample count is not a multiple of the current sample count, just use the minimum sample count of all buffers ever submited to the audio stream.  This shoulld fix the "New audio stream setup with a sample count of ..." log spam followed by massive slowdown in some games, such as Final Fantasy VII, when using the SDL2 audio backend.
=> Use minimum stream sample count on SDL2 audio backend

Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs
It should be flipped when this bit is set, required by OpenGL games.
Fixes menus being cut off in the Youtube app.
Before:
After:
Testing to ensure there's no regressions on games is welcome.
=> Flip scissor box when the YNegate bit is set

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
This PR stub `SetMediaPlaybackStateForApplication` of the am service. Accordingly to gdkchan it's needed by the Youtube app. This is checked by RE aswell.
=> am: Stub SetMediaPlaybackStateForApplication

Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs
This PR stubs `IsFriendListCacheAvailable` and `EnsureFriendListAvailable` call of `friend` service, checked by RE, which close #2896.
Sadly, Super Bomberman R Online is still stuck on the loading screen and keep calling `TryPopFromFriendInvitationStorageChannel`, probably because another issue somewhere.
=> friend: Stub IsFriendListCacheAvailable and EnsureFriendListAvailable

Ryujinx.Graphics.OpenGL/FormatTable.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs
The format had the wrong order before, resulting in graphical glitches in at least one title (NSO Nintendo 64 emulator).
This emulator does not work on master due to other components that are not implemented yet, so I have tested it on a private branch, and I'm providing those screenshots only to illustrate what was fixed.
Before:
After:
=> Fix A1B5G5R5 texture format

Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.GAL/Format.cs, Ryujinx.Graphics.Gpu/Image/FormatTable.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.Texture/PixelConverter.cs
This format is used by the NSO N64 emulator. It is supported by Vulkan, but not OpenGL, so I added a compatibility flag to report when its not supported, in which case we do conversion to the R4G4B4A4 on the CPU. The reason I choose this format, is because conversion can be done by simply zero-extending the value from 8-bits to 16-bits.
The N64 emulator does not work on master due to other components that are not implemented yet, so I have tested it on a private branch, and I'm providing those screenshots only to illustrate what was fixed.
Before:
(Actually, it would look slightly different on master, as it defaults for RGBA8 format when a format is not implemented, on the above screenshot it simply failed to create the texture).
After:
=> Add support for the R4G4 texture format

Ryujinx.Graphics.GAL/ImageCrop.cs, Ryujinx.Graphics.Gpu/Window.cs
Right now, the presentation texture size is used to find a matching texture on the cache, but after that is not used anymore, instead it uses the cached texture size. The problem is that due to size alignment, the cached texture might be actually larger than the texture size, leading to gaps when the texture is presented.
This has been fixed here by forcing the extra size to be cropped before presentation, using the crop rectangle that was already being passed from surface flinger.
Before:
After:
Should fix a similar issue on Hades aswell, but I did not test this one.
=> Force crop when presentation cached texture size mismatches

Ryujinx.HLE/HOS/ModLoader.cs, Ryujinx.HLE/HOS/Tamper/AtmosphereProgram.cs, Ryujinx.HLE/HOS/Tamper/ITamperProgram.cs, Ryujinx.HLE/HOS/TamperMachine.cs, Ryujinx.HLE/Switch.cs, Ryujinx/Ryujinx.csproj, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/MainWindow.glade, Ryujinx/Ui/Widgets/GameTableContextMenu.Designer.cs, Ryujinx/Ui/Widgets/GameTableContextMenu.cs, Ryujinx/Ui/Windows/CheatWindow.cs, Ryujinx/Ui/Windows/CheatWindow.glade
Adds a cheat manager which makes it possible to disable and enable installed cheat at runtime. This can be accessed by the context menu on the game list, or Actions -> Manage Cheats during gameplay. By default, all cheats are disabled.
Do note that this does not allow you to edit or add cheats. . Also, because the tampermachine only load cheats at launch, new cheats added to the cheat files and enabled will not be applied.
Related to #2651 .
=> Add Cheat Manager

Ryujinx.Graphics.Nvdec.FFmpeg/FFmpegContext.cs
This PR adds some checks and logging error messages related to the ffmpeg context creation, that will prevent users to open issues because they don't have the correct packages installed.
Close #2762
=> ffmpeg: Add extra checks and error messages

Ryujinx/Ui/Windows/CheatWindow.cs
Hot fix for issue with enabled cheats when cheat file is not in upper case.
=> Fix build id case issue for enabled cheats

Ryujinx.HLE/HOS/Services/Sockets/Nsd/IManager.cs, Ryujinx.HLE/HOS/Services/Sockets/Nsd/Manager/FqdnResolver.cs, Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
This fix a missing implementation usage of NSD on IResolver when requested on ``GetAddrInfoRequest*`` and ``GetHostByNameRequest*``.
=> sfdnsres: Implement NSD resolution

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.GAL/Multithreading/Commands/UpdateRenderScaleCommand.cs, Ryujinx.Graphics.GAL/Multithreading/ThreadedPipeline.cs, Ryujinx.Graphics.GAL/SupportBufferUpdater.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/DefaultNames.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/TexelFetchScale_fp.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/TexelFetchScale_vp.glsl, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/Ryujinx.Graphics.Shader.csproj, Ryujinx.Graphics.Shader/ShaderStage.cs, Ryujinx.Graphics.Shader/SupportBuffer.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
Occasionally games read off textureSize on the vertex stage to inform the fragment shader what size a texture is without querying in there. Scales were not present in the vertex shader to correct the sizes, so games were providing the raw upscaled texture size to the fragment shader, which was incorrect.
One downside is that the fragment and vertex support buffer description must be identical, so the full size scales array must be defined when used. I don't think this will have an impact though. Another is that the fragment texture count must be updated when vertex shader textures are used. I'd like to correct this so that the update is folded into the update for the scales.
Also cleans up a bunch of things, like it making no sense to call CommitRenderScale for each stage.
Fixes render …
=> Add support for render scale to vertex stage.

Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
The title says it all, if guest internet access is disabled, no DNS lookup is performed and it returns an error immediately. If the guest internet access is disabled, it doesn't make sense that we allow the servers to be reached.
This fixes a regression introduced by #2936 that made Crash Bandicoot 4 crash early on boot after trying to connect to some server. Note that the game will still crash with guest internet access enabled, that should be fixed separately.
The regression likely comes from the fact that before the fix on the linked PR, it was returning a serialized size of 0 which made the applications assume nothing was actually returned. This change should make it behave in a similar way to the old behaviour, except we return an actual error code now.
Thanks to Muffin for finding …
=> Return error on DNS resolution when guest internet access is disabled

Ryujinx.Graphics.GAL/ITexture.cs, Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs, Ryujinx.Graphics.GAL/Multithreading/CommandType.cs, Ryujinx.Graphics.GAL/Multithreading/Commands/Texture/TextureGetDataSliceCommand.cs, Ryujinx.Graphics.GAL/Multithreading/Resources/ThreadedTexture.cs, Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs, Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoClass.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClass.cs, Ryujinx.Graphics.Gpu/GpuContext.cs, Ryujinx.Graphics.Gpu/Image/AutoDeleteCache.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Graphics.Gpu/Image/TextureGroupHandle.cs, Ryujinx.Graphics.Gpu/Image/TextureViewCompatibility.cs, Ryujinx.Graphics.Gpu/Memory/MultiRangeWritableBlock.cs, Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs, Ryujinx.Graphics.OpenGL/Image/TextureBuffer.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs, Ryujinx.Graphics.OpenGL/PersistentBuffers.cs, Ryujinx.Graphics.Texture/LayoutConverter.cs, Ryujinx.Graphics.Texture/SizeCalculator.cs, Ryujinx.Graphics.Texture/SizeInfo.cs, Ryujinx.Memory/Range/MultiRange.cs, Ryujinx/Ui/RendererWidgetBase.cs
This PR aims to solve a bunch of issues caused by texture modification and data flushing, by primarily handling data flush on a per-handle instead of per-view basis, and synchronizing flushes with syncpoint increments.
This introduces a new backend method, so it's not currently compatible with Vulkan (though the benefits are more important there)
This one has been a while coming. When texture flush via memory tracking was first added, our CPU and various other components were considerably slower. The GPU was so tight with the CPU as a result of both this and the lack of backend multithreading, so when the game tried to access the data it was almost certain that the draw would have completed and the data would be there, just by chance.
This did not last. Over time people started …
=> Texture Sync, incompatible overlap handling, data flush improvements.

Ryujinx.Graphics.Gpu/Image/TexturePool.cs
The width/height of render target and copy textures is already pre-multiplied by the driver for multisample textures. For shader sampled textures that are on the pool, they are not pre-multiplied. This changes multiply their size by the multisample size, in order to allow them to match existing textures on the cache, in addition to allowing the texture to have the correct size (as the `TextureCreateInfo` that is passed to the backend has the width and height divided by the amount of samples).
Fixes rendering on Okami HD.
PR:
Might also fix broken fight effects on Rune Factory 5.
Testing on games using multisampling is appreciated.
=> Fix sampled multisample texture size

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Decoders/Decoder.cs, Ryujinx.Graphics.Shader/Decoders/InstDecoders.cs, Ryujinx.Graphics.Shader/Decoders/InstTable.cs, Ryujinx.Graphics.Shader/Instructions/InstEmit.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitFloatArithmetic.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitFlowControl.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitIntegerArithmetic.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
A bunch of shader fixes here:
- Implement the IMUL (integer multiply) shader instruction. Used by MelonDS Switch port and possible other homebrew. Not sure if commercial games uses this shader instruction.
- Implement PCNT and CONT shader instructions. Those are similar to existing PBK/BRK and SSY/SYNC pairs. Also used by MelonDS Switch port and possibly other homebrew, AFAIK the NVIDIA compiler never uses this instruction.
- Fix FMUL32I instruction implementation. Third operand should use the destination register, not "SrcC" as it does not exist for this instruction. (Regression from https://github.com/Ryujinx/Ryujinx/pull/2698).
- Fix a issue similar to the above one for HFMA32I aswell, but this one was also missing from the instruciton table so I have added it too. (Technically not a …
=> Implement IMUL, PCNT and CONT shader instructions, fix FFMA32I and HFMA32I

Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Proxy/DnsBlacklist.cs
=> sfdnsres: Block communication attempt with NPLN servers

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs
This fixes some regressions caused by #2971 which caused rendered 3D texture data to be lost for most slices. Fixes issues with Xenoblade 2's colour grading, probably a ton of other games.
This also removes the check from TextureCache, making it the tiniest bit smaller (any win is a win here).
=> Fix adjacent 3d texture slices being detected as Incompatible Overlaps

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.GAL/RectangleF.cs, Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClass.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClassState.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs
On OpenGL (and Vulkan too iirc), when the bound render targets have different sizes, then it only render on the intersection of all their sizes. On the GPU, this clipping is controlled by the `ScreenScissorState` pair of registers. This register was being mostly ignored before, but for clears, that may cause issues if there are render targets of different sizes bound, and the game is trying to clear one of them, with a screen scissor size that matches the target being cleared. OpenGL would clip it to the smallest size and not clear the entire region.
This issue has been fixed by forcing all other render targets to be unbound, to avoid the host clipping, and then using a custom scissor region, calculated from the screen scissor and user scissor (0). Additionally, I also implemented the …
=> Fix render target clear when sizes mismatch

ARMeilleure/Instructions/InstEmitFlowHelper.cs, ARMeilleure/Instructions/InstEmitMemory.cs
Fixes an assert that was caused by the return type not matching the actual return type of the functoin, due to the address bein 32-bits. Usually this does not cause asserts, but when combined with the tail merge optimization, it could store 32-bit to 64-bit copies due to the mismatch of the different return types, which would later cause an assert on the copy.
I think this is otherwise harmless, since on x86, 32-bit operations will zero the upper 32-bits of the register, so the zero extension is technically not needed in this case.
=> Fix return type mismatch on 32-bit titles

Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs
This fix a misplace critical section leave.
This fix a deadlock on DoDonPachi Resurrection when starting a new game and possibly other games.
=> kernel: Fix deadlock when pinning in interrupt handler

Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs
Fixes a regression introduced on #2994 that would cause the screen to "flicker" in some games with resolution scale other than native. Affected games includes Luigi's Mansion 3.
Also changes `Math.Ceiling` to `MathF.Ceiling` to avoid an implicit cast to double (plus, float operations are generally faster than double ones).
=> Scale scissor used for clears

Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.Gpu/Shader/TextureDescriptorCapableGpuAccessor.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs
This adds a new capability, `SupportsBgraFormat`. On OpenGL, it is always false as this API has no support for BGRA texture formats. However, it will be set to true on Vulkan, which allows us to use those formats there, without needing to swap the components ourselves on the fragment shader output.
Main benefit here is reducing the diff with the Vulkan branch and making review easier. Should not cause any changes on games.
=> Add capability for BGRA formats

ARMeilleure/CodeGen/X86/Assembler.cs, ARMeilleure/CodeGen/X86/CodeGenerator.cs, ARMeilleure/Instructions/InstEmitMemoryEx.cs, ARMeilleure/IntermediateRepresentation/Instruction.cs, ARMeilleure/Translation/EmitterContext.cs, ARMeilleure/Translation/PTC/Ptc.cs
This just adds a memory barrier for the guest barrier instructions on the CPU. Before we had "host mapped memory" (the POWER PR), this was not *as* important because software memory emulation had to do address translation and validation, which would generate a large number of instructions per memory access, which makes memory reordering across separate guest memory accesses less likely. With the change it becomes a bigger problem because guest memory access can compile to a single host instruction.
Should fix softlocks on those games:
- Pokémon Mystery Dungeon DX (would sometimes get stuck on a black screen right before the title screen).
- Pokémon Brilliant Diamond/Shining Pearl (usually entering or exiting buildings, or changing areas in general).
Potentially also affected:
- Pokémon …
=> Add host CPU memory barriers for DMB/DSB and ordered load/store

Ryujinx.Graphics.OpenGL/Queries/BufferedQuery.cs, Ryujinx.Graphics.OpenGL/Queries/CounterQueue.cs
This fixes a rare bug where reporting a counter for a region containing 0 draws could deadlock the GPU. If this write overlaps with a tracking action, then the GPU could end up waiting on something that it's meant to do in the future, so it would just get stuck.
Before, this reported immediately and wrote the result to guest memory (tracked) from the backend thread. The backend thread cannot be allowed to trigger read actions that wait on the GPU when backend threading is enabled, as it can end up waiting on itself, and never advancing. This is the only case that does this...
In the case of backend multithreading's `SyncMap`, it would try to wait for a backend sync object that does not yet fully exist, as the sync object would exist according to the GPU and tracking, but it has not yet …
=> Fix deadlock for GPU counter report when 0 draws are done

Ryujinx.Audio/Renderer/Dsp/Command/DeviceSinkCommand.cs
This fix an out of bound when indexing inputs for games that uses unsupported input count. (8 here)
Death Coming now goes to menu but crash trying to contact online servers (even with guest internet disabled)
Close #2724.
=> amadeus: Fix possible device sink input out of bound

ARMeilleure/CodeGen/X86/PreAllocator.cs, ARMeilleure/Translation/PTC/Ptc.cs
This fixes a regression introduced on #2515 where in some cases, during the pre-allocation stage, the new register operations would not be added to the call operation node. This would cause the register allocator to not keep track of the fixed registers (possibly overwriting the register values), and also to do register allocation for the operands passed on the call (which it should not, calls are supposed to be entirely handled by the pre-allocator, as the ABI requires each argument to be passed on a specific register or stack offset).
This only affects Linux, and mostly calls that passes V128 values (those are passed on a pair of 2 general purpose registers on Linux).
Fixes #2805, fixes #2864, fixes #3024 and fixes #3028.
Yes, that fixes the save file corrupted error on Pokémon …
=> Fix calls passing V128 values on Linux

Ryujinx/Modules/Updater/Updater.cs
After downloading the latest release from GitHub actions which doesn't have executable rights we call chmod from the binding to libc that we have created. While the chmod command accepts permissions in Symbolic Mode (for example +x for executable rights) or Octal Mode (for example 755), the libc api accepts permissions in Decimal Mode. The 0 preceding 777 in the code suggests that its an octal number in a language like C however such thing does not exist in C# therefore we need to convert it to Decimal. The reason 755 is chosen instead of 777 this time is because these are the default permissions dotnet gives the binary and when converted in decimal the equivalent is 493.
Closes #2497
=> Fix: Autoupdater doesn't set the correct permissions on Linux/Unix

Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs, Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoClass.cs, Ryujinx.Graphics.Gpu/Engine/Threed/SemaphoreUpdater.cs, Ryujinx.Graphics.Gpu/GpuContext.cs
BOTW was reading a ulong 8 bytes after a semaphore release. Turns out this is the timestamp it was trying to do performance calculation with, so I've made it write when necessary. This fixes BOTW being capped at 20fps all the time. (now it only does this when the game runs too slowly)
This mode was also added to the DMA semaphore I added recently, as it is required by a few games. (i think quake?)
The timestamp code has been moved to GPU context. Check other games with an unusually low framerate cap or dynamic resolution to see if they have improved.
=> Add timestamp to 16-byte/4-word semaphore releases.

Ryujinx.HLE/HOS/Kernel/Common/KernelTransfer.cs, Ryujinx.HLE/HOS/Kernel/Memory/KPageTableBase.cs, Ryujinx.HLE/HOS/Kernel/Memory/MemoryPermission.cs, Ryujinx.HLE/HOS/Kernel/Memory/MemoryState.cs, Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs, Ryujinx.HLE/HOS/Kernel/Process/KProcessCapabilities.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/InvalidSvcException.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/MemoryInfo.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall32.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall64.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/ThreadContext.cs, Ryujinx.HLE/HOS/Kernel/Threading/KAddressArbiter.cs, Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs, Ryujinx.HLE/HOS/Services/IpcService.cs, Ryujinx.HLE/HOS/Services/Nv/INvDrvServices.cs, Ryujinx.HLE/HOS/Services/ServerBase.cs
This PR cherrypick some misc parts of #1504 and give small clean up here and there.
Changes:
- All syscalls output are now before input arguments.
- All syscalls now doesn't use raw memory write to output data structure to userspace.
- All references to ``position`` were renamed to ``address``.
- ``GetThreadContext3`` have been rewritten to be accurate (fixing AArch32 support for it in the process).
- ``KernelTransfer`` now uses ``IsRangeMapped`` and uses generic functions.
- Some fields were switched to unsigned to improve correctness and avoid useless casts.
=> kernel: A bit of refactoring and fix GetThreadContext3 correctness

ARMeilleure/Instructions/InstEmitSimdArithmetic.cs, ARMeilleure/Translation/PTC/Ptc.cs
This just fixes a small oversight that I was already aware of for a while. The operation there is supposed to reduce the precision of the reciprocal instruction result, this is not necessary because *Intel* CPUs have more preicision than Arm CPUs for the reciprocal estimate instruction. The operation is supposed to round the value by adding a constant and then masking. However the instruction used was PADDW, which adds *words* (16-bits), when it should be using PADDD, which adds *double-words* (32-bits). This small bug could cause the lower bits of the float value to overflow, in some cases causing a small precision error in the mantissa field of the float value.
This should fix the "twitching" on some animations in Pokémon Legends Arceus.
Before (pay attention to the left arm): …
=> Fix small precision error on CPU reciprocal estimate instructions

Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs
Fixes a regression introduced on #2994 that could cause the depth buffer to not be bound after a clear. The issue would happen if the game clears the color buffer after depth, and `clipSizeMismatch` is true. Additionally, make the clip region size take multisampled textures into account. Before, the size was incorrect for multisample textures, which would cause it to detect false mismatches.
Fixes regression where models would not be draw on Sonic Colors Ultimate. Thanks to Muffin for finding the regression.
=> Fix bug that could cause depth buffer to be missing after clear

Ryujinx.HLE/FileSystem/VirtualFileSystem.cs, Ryujinx.HLE/HOS/ApplicationLoader.cs
- Run the extra data fix in FixExtraData on non-system saves that have no owner ID.
- Set the owner ID in the dummy application control property if an application doesn't have a proper one available.
This fixes programs giving PermissionDenied in most, if not all situations when mounting their save data
=> Try to ensure save data always has a valid owner ID

ARMeilleure/Decoders/OpCodeTable.cs, ARMeilleure/Instructions/InstEmitAlu32.cs, ARMeilleure/Instructions/InstName.cs, Ryujinx.Tests/Cpu/CpuTestAlu32.cs
Complete the other half of the 8-bit halving add.
Implementation [ported from here](https://github.com/merryhime/dynarmic/commit/cb17f9a3edfa774dea555778a659a9b705c7ca88), as well as the associated comment.
=> ARMeilleure: A32: Implement SHADD8

Ryujinx.Common/GraphicsDriver/DriverUtilities.cs
Ryujinx tries to enable threaded optimizations when threaded gal (Graphics Backend Multithreading) is Off, on Linux this is done by settings environmental variables. Since threaded gal conflicts with them Ryujinx also tries to force them off when it's on On or Auto (ATM Auto == On). The function ToggleOGLThreading takes a bool as input and the environmental variable that toggles this on MESA is mesa_glthread which takes true or false as arguments, so we convert the bool to a string using dotnet's ToString. The problem with ToString is that it converts to True or False which MESA doesn't accept and results in `illegal environment value for mesa_glthread: "False".  Ignoring.` So we have to convert it to lowercase using ToLower after it resulting in `ATTENTION: default value of option …
=> Make sure mesa_glthread gets a lowercase string

Ryujinx.Audio.Backends.SoundIo/Ryujinx.Audio.Backends.SoundIo.csproj
On the project file for the project ```Ryujinx.Audio.Backends.SoundIo``` we specify which SoundIO library will be published depending on the RuntimeIdentifier property; if it isn't linux-x64 or osx-64 it is Windows therefore it gets a .dll, if it isn't linux-x64 or win-x64 then it's OS X so it gets a .dylib and if it isn't win-x64 or osx-64 it has to be Linux so it gets a .so file. And these checks work fine when building the project as an individual project. So if you do for example ```dotnet build Ryujinx.Audio.Backends.SoundIo/Ryujinx.Audio.Backends.SoundIo.csproj -o soundio -r osx-x64``` the generated soundio folder will contain a .dylib but not a .dll or .so file as it should. However, when building Ryujinx as a whole and ```Ryujinx.Audio.Backends.SoundIo``` is built as a subproject …
=> Ship SoundIO library only for the specified runtime

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs
When using geometry shader passthrough, ensure that the inputs consumed by the next stage are passed on the geometry shader stage.
This fixes a regression on Game Builder Garage, but I'm not sure which specific PR caused the regression.
master (solid black characters):
PR:
=> Fix missing geometry shader passthrough inputs

ARMeilleure/Instructions/InstEmitHelper.cs, ARMeilleure/Instructions/InstEmitMemory32.cs
There are a few times when reading from R15 is very slightly different from normal and returns a word-aligned PC instead:
1. During a literal load.
2. During a two-word thumb BLX instruction.
3. During an ADR instruction.
4. During a literal store (the only one which isn't UNPREDICTABLE is a VFP store, afaik.)
Thus for the above special cases we need to have a different register read function.
The reason this is an issue is because the value of PC which is exposed to the memory addressing circuitry is always word aligned.
The effect of this change will only be noticeable once thumb support is implemented.
=> InstEmitMemory32: Literal loads always have word-aligned PC

.gitignore, Ryujinx.Input/HLE/NpadController.cs
Previously, the way that deadzones were calculated was that if the x axis is smaller than the set value of the deadzone, then X would be 0. same goes for Y. This works for a select few games, but say for example, in some game you're moving forward with the stick pressed all the way forward. if you wanted to turn say 5 degrees to the right, then it wouldn't be possible, as the deadzone would entirely prevent small adjustments on the edge of another axis. With this new implementation, it creates what is essentially a dead circle in the centre, and then smooths the edges from there. This both allows for small adjustments at the extreme ends of a specific axis, but also prevents the problem of a sudden burst of movement once you're past the deadzone, because of there being no "sharp" edges. …
=> Adjusting how deadzones are calculated

Ryujinx.Audio/Renderer/Dsp/Command/LimiterCommandVersion1.cs, Ryujinx.Audio/Renderer/Dsp/Command/LimiterCommandVersion2.cs, Ryujinx.Audio/Renderer/Dsp/State/LimiterState.cs, Ryujinx.Audio/Renderer/Server/CommandGenerator.cs
There was multiple inconsistencies on the implementation as it was left untested back then.
The following fixes were made:
- Statistics are now not reported when explicitly disabled by a game.
- The buffer for delayed samples is now explicitly initialized. (for correctness)
- Fix input gain not being applied for delayed samples.
- Fix missing input and output conversion. (Nintendo map to PcmFloat where we map to PcmInt16 with float)
This fixes missing audio on Nintendo Switch Sports Online Play Test.
Closes #3125.
=> amadeus: Fix limiter correctness

Ryujinx.Graphics.GAL/IRenderer.cs, Ryujinx.Graphics.GAL/Multithreading/Resources/Programs/BinaryProgramRequest.cs, Ryujinx.Graphics.GAL/Multithreading/Resources/Programs/SourceProgramRequest.cs, Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs, Ryujinx.Graphics.GAL/ShaderInfo.cs, Ryujinx.Graphics.Gpu/Shader/Cache/Definition/HostShaderCacheEntry.cs, Ryujinx.Graphics.Gpu/Shader/Cache/Definition/HostShaderCacheEntryHeader.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Program.cs, Ryujinx.Graphics.OpenGL/Renderer.cs, Ryujinx.Graphics.OpenGL/Shader.cs, Ryujinx.Graphics.Shader/ShaderProgramInfo.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, Ryujinx.Graphics.Shader/Translation/ShaderHeader.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
On OpenGL, if you have multiple render targets, but the fragment shader only writes one output, it still writes that output to all bound render targets. This does not match hardware behaviour, which is not writing those render targets. I fixed by forcing the color mask to be disabled for the components that the fragment shader does not write. For this, a new `ShaderInfo` struct is passed to the shader compilation functions on the backend. The struct was added because we will likely need to pass more information in the future (it already does on the Vulkan branch).
The output map handling was simplified on the shader translator. Instead of extracting each bit into a struct with 4 bools, it just stores and use the bitmask directly. This is also more efficient.
Fixes cave in Pokémon Legends …
=> Do not allow render targets not explicitly written by the fragment shader to be modified

Ryujinx.Audio/Renderer/Dsp/Command/PcmFloatDataSourceCommandVersion1.cs
Really simple copy pasta error here.
Shouldn't affect anything as float support was added at the same REV as datasource command v2.
=> amadeus: Fix PCMFloat datasource command v1

Ryujinx/Ryujinx.csproj
Update GtkSharp.Dependencies to fix between menu flickering (Thanks to @merryhime [PR](https://github.com/Ryujinx/GtkSharp.Dependencies/pull/2)) and enable the SkipInstallGtk in csproj to avoid downloading unused GTK3 install locally.
=> misc: Update GtkSharp.Dependencies and speed up initial Windows build

ARMeilleure/Decoders/IOpCode32Alu.cs, ARMeilleure/Decoders/IOpCode32HasSetFlags.cs, ARMeilleure/Decoders/OpCode32AluUmull.cs, ARMeilleure/Instructions/InstEmitAluHelper.cs
Bugfix.
`OpCode32AluUmull` does not derive from `IOpCode32Alu`, so introduce a new interface.
=> Decoders: Add IOpCode32HasSetFlags

Ryujinx.Common/Logging/LogClass.cs, Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/IWindowController.cs, Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs, Ryujinx.HLE/HOS/Services/Mnpp/IServiceForApplication.cs, Ryujinx.HLE/HOS/Services/Mnpp/ResultCode.cs
This PR implement/stub the `mnpp:app` service (closes #3107) accordingly to RE, which seems to do some telemetry for China region only, so everything is stubbed.
This PR fixes some inconsistencies in the hid service too and stub EnableSixAxisSensorUnalteredPassthrough, IsSixAxisSensorUnalteredPassthroughEnabled, LoadSixAxisSensorCalibrationParameter, GetSixAxisSensorIcInformation calls (closes #3123 and closes #3124).
=> Implement/Stub mnpp:app service and some hid calls

Ryujinx.Common/Utilities/BitUtils.cs, Ryujinx.Graphics.Texture/BlockLinearLayout.cs, Ryujinx.HLE/HOS/Kernel/Common/MersenneTwister.cs, Ryujinx.HLE/HOS/Kernel/Memory/KMemoryRegionManager.cs, Ryujinx.HLE/HOS/Kernel/Process/KContextIdManager.cs, Ryujinx.HLE/HOS/Kernel/Process/KProcessCapabilities.cs
Replaces BitUtils.CountTrailingZeros/CountLeadingZeros/IsPowerOfTwo with BitOperations methods
=> Use BitOperations methods and delete now unused BitUtils methods

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
Fix one case of shader failing to compile. `textureSize` sampler type is sourced from the texture pool since the GPU instruction does not specify the type. However, the type may still not be ideal in a few cases:
- Texture is sampled with depth compare later on. In this case the type should be `sampler*Shadow` and not just `sampler*`.
- Texture pool type does not match sampled type. For example, texture pool could have Texture2D while it samples as Texture2DArray.
To handle those cases, if there is more than one use of the texture, one by `textureSize` and another by regular `texture` sample operations, it prefers the type from the `texture` sample operation, as this instruction actually specifies the type and it is accurate.
I did find shaders failing to compile on games due to this, but …
=> Prefer texture over textureSize for sampler type

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/DisposableIpcService.cs, Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
This should prevent filesystem services from blocking other services that don't have their own ServerBase. May improve filesystem related stutters in certain titles, generally indicated by getting better on a second run (not shader related) or being worse on network/HDD vs SSD.
Improves button advanced cutscenes such as Miqol's Request in Xenoblade: DE when the game is on a network share (used to stutter when voice lines played).
Should probably be tested to make sure no mysterious bugs have been unearthed, and to see if any other filesystem related perf issues are improved.
=> Add dedicated ServerBase for FileSystem services

ARMeilleure/Translation/SsaConstruction.cs, Ryujinx.Audio/Renderer/Dsp/State/ReverbState.cs, Ryujinx.Audio/Renderer/Server/Voice/VoiceState.cs, Ryujinx.Graphics.Gpu/Shader/Cache/CacheHelper.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.OpenGL/Program.cs, Ryujinx.HLE/HOS/Services/ServerBase.cs, Ryujinx.HLE/Loaders/Executables/KipExecutable.cs, Ryujinx.HLE/Loaders/Executables/NroExecutable.cs, Ryujinx.HLE/Loaders/Executables/NsoExecutable.cs, Ryujinx.HLE/Loaders/Mods/MemPatch.cs
And collapse one Array.Clear(array, 0, array.Length) to just Array.Clear(array)
Less code and a bit faster.
=> Collapse AsSpan().Slice(..) calls into AsSpan(..)

ARMeilleure/Instructions/InstEmitFlow32.cs, ARMeilleure/Instructions/InstEmitHelper.cs
Ensure PC is appropriately masked in BXWritePC and BLX (reg) uses BXWritePC.
=> A32: Fix BLX and BXWritePC

Ryujinx/Ui/App/ApplicationLibrary.cs
Currently we just load the version of the update, instead of the whole NACP file. This PR fixes that. A little cleanup is made into the code to avoid duplicate things.
(Closes #3039)
Before:
After:
=> gui: Fixes the games icon when there is an update 

ARMeilleure/Decoders/Decoder.cs, ARMeilleure/Decoders/DecoderMode.cs, ARMeilleure/Translation/Translator.cs
Allow for single stepping of instructions.
This is forked off #3101 for ease of review. Note however, this PR was implemented [slightly differently](https://github.com/Ryujinx/Ryujinx/pull/3101/files#diff-82cd0b0f0bc66b6bc9dddb35b31c72707554587253f7a5de9f4602766383c6baR99) to allow for the existence of IT blocks introduced by the thumb PR. (i.e. We step over an IT block as a monolithic unit.)
Resolving the above IT block situation is not really considered a priority given it's unlikely to crop up much in the real world use case, thus the additional complexity is unlikely to be worth it. Will revisit if this turns out to be an issue.
=> ARMeilleure: Implement single stepping

Ryujinx.Graphics.Gpu/Engine/Twod/TwodClass.cs, Ryujinx.Graphics.Gpu/GraphicsConfig.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Image/TextureSearchFlags.cs, Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs
Unreal Engine games tend to move texture data directly into levels of a texture via DMA. This is all well and good, but if the game is using _texture streaming_, then it will move this data between a pool of storage textures by **blitting** individual levels. This causes a number of problems for us, as People Who Want to Emulate Video Games:
- To copy a single level of a mipmapped texture to another, we need to create a view for the source and destination, which takes time and clutters up the texture cache.
- Blitting compressed texture data is done by aliasing the src/dst textures as another format... which is not supported in OpenGL, so we need to perform additional copies between the "data" representation and the "compressed" one, which is used for rendering.
- Copy dependencies aren't …
=> Perform unscaled 2d engine copy on CPU if source texture isn't in cache.

Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs, Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs, Ryujinx.Memory/Range/MemoryRange.cs, Ryujinx.Memory/Range/MultiRangeList.cs
We are currently hiting a case in some games where the texture data is only partially mapped, so for example, some mipmap levels are not mapped, which causes an exception to be throw on the call to `GetPhysicalRegions`, as it expects the full texture region to be mapped.
This change allows the textures to be created even if their data is not fully mapped. For the ranges that are not mapped, the data is read as 0, and writes goes nowhere. Mapped regions are read/written as normal. This should match hardware behaviour, which needs to work this way most likely to support sparse textures, as unmapped regions being accessed shouldn't cause a crash.
A few methods were adjusted to take this into account:
- `GetPhysicalRegions` now returns `ulong.MaxValue` and the size for unmapped ranges, …
=> Allow textures to have their data partially mapped

Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/LibHacHorizonManager.cs, Ryujinx.HLE/HOS/ModLoader.cs, Ryujinx.HLE/HOS/ProgramLoader.cs, Ryujinx.HLE/HOS/Services/Account/Acc/AccountManager.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForApplication.cs, Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs, Ryujinx.HLE/HOS/Services/Arp/LibHacIReader.cs, Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/FileSystemProxyHelper.cs, Ryujinx.HLE/HOS/Services/Fs/IDeviceOperator.cs, Ryujinx.HLE/HOS/Services/Pctl/ParentalControlServiceFactory/IParentalControlService.cs, Ryujinx.HLE/HOS/Services/Sdb/Pdm/QueryService/QueryPlayStatisticsManager.cs, Ryujinx.HLE/Loaders/Executables/NsoExecutable.cs, Ryujinx.HLE/Ryujinx.HLE.csproj, Ryujinx/Ui/App/ApplicationLibrary.cs, Ryujinx/Ui/Widgets/GameTableContextMenu.cs, Ryujinx/Ui/Windows/TitleUpdateWindow.cs
Main updates include:
- Support for reading NCAs with compressed sections. Fixes the following games:
- Ryujinx/Ryujinx-Games-List#3815
- Ryujinx/Ryujinx-Games-List#3786
- Maybe others
- Be more resilient to invalid `DirectorySaveDataFileSystem` extra data states.
Helps recover from situations where external things mess with the extra data files instead of just erroring
- Fix checking the FS access control content owner info size. 
No actual games hit this issue
=> Update LibHac to v0.16.0

ARMeilleure/Decoders/Decoder.cs, ARMeilleure/Instructions/InstEmitException.cs, ARMeilleure/Instructions/InstEmitException32.cs
Exiting when encountering a trapping instruction is important for ensuring correct behavior, because further code beyond the trapping instruction should not execute. This allows for the opportunity for a debugger (e.g. gdbstub) that has taken over the dispatch loop to redirect the program counter appropriately.
If an instruction is a trap, we expect execution to normally resume at the trapping instruction itself. The common usecase for this is when a BRK instruction is inserted as a software breakpoint, and execution is expected to resume at that location once the original instruction has been replaced.
=> Decoder: Exit on trapping instructions, and resume execution at trapping instruction

ARMeilleure/Instructions/InstEmitAluHelper.cs, ARMeilleure/Translation/PTC/Ptc.cs, Ryujinx.Tests/Cpu/CpuTestAluImm32.cs
Add a test for some of these arm32 instructions. This reveals an existing bug. Fix this bug.
Bug occurs because carry flag is overwritten before it can be used in the calculation which is incorrect behaviour.
=> A32: Fix ALU immediate instructions

Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/Decoders/Decoder.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs, Ryujinx.Graphics.Shader/Translation/UInt128.cs
If one shader stage reads an input that is not written by the previous stage, as per the spec, the contents are undefined. This is not a problem on NVIDIA as the contents are actually consistent for those uninitialized values, but it does cause issues for Intel and AMD. So to fix that, the shader translator adds code to explicitly initialize outputs that are used by the next stage, but might not be written on the current one.
Right now it initialize some outputs that don't need to be initialized, for one of those two reasons:
- The specific component is not accessed on the next stage. Right now it only keeps track of the entire vec4 input that is consumed on the next stage. It does not keep track of the individual XYZW float components.
- The output might not be used on the next stage at …
=> Only initialize shader outputs that are actually used on the next stage

Ryujinx.Common/Configuration/AppDataManager.cs, Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/ModLoader.cs, Ryujinx/Ui/Widgets/GameTableContextMenu.Designer.cs, Ryujinx/Ui/Widgets/GameTableContextMenu.cs
Implements addition of SD paths into the ModLoader so that standard atmosphere/hardware directory set up mods can be used semi-seamlessly. GUI context menu addition to open the directory is also added.
Closes #3174
=> Mod loading from atmosphere SD directories

Ryujinx.Audio/Renderer/Server/Performance/PerformanceManagerGeneric.cs
Fix a copypasta from the original Amadeus PR causing invalid CopyHistories output.
Also added a missing size check.
This fix a crash in [Mononoke Slashdown](https://github.com/Ryujinx/Ryujinx-Games-List/issues/3844) (now goes in-game)
=> amadeus: Fix wrong Span usage in CopyHistories

ARMeilleure/State/ExecutionContext.cs, ARMeilleure/State/NativeContext.cs, Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs, Ryujinx.Tests/Cpu/CpuTest32.cs
Very minor PR for ease of review. Forked off from #3101.
Provide helper functions for getting a uint value instead of having to construct from flags.
Also fix GetPsr in KThread while we're here. See [Atmosphere reference](https://github.com/Atmosphere-NX/Atmosphere/blob/96f95b9f95988bd30c3dcac6c2bbabf573a23bb5/libraries/libmesosphere/source/arch/arm64/kern_k_thread_context.cpp#L43).
=> KThread: Fix GetPsr mask

Ryujinx.HLE/HOS/Services/Vi/IApplicationRootService.cs, Ryujinx.HLE/HOS/Services/Vi/IManagerRootService.cs, Ryujinx.HLE/HOS/Services/Vi/ISystemRootService.cs, Ryujinx.HLE/HOS/Services/Vi/ResultCode.cs, Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
It is only possible to get an event once per display with `GetDisplayVSyncEvent`, but the emulator implementation had no such limit. This updates the implementation to return an error if an event was already returned. Based on RE.
Fixes `WaitSyncrhonization` `InvalidHandle` error spam on .hack//G.U. Last Recode, also making the game playable with logs enabled.
Testing is appreciated to ensure there's no regressions.
=> Limit number of events that can be retrieved from GetDisplayVSyncEvent

Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs
This fixes a `NullReferenceException` that could happen when closing the emulator or stopping emulation. The problem is that `GetUserDisableCount` reads guest memory, however the memory manager is disposed as soon as all guest threads exit (well, what is really disposed is the ArmProcessContext, but that will decrement the memory manager reference count and set the instance to null). "Exiting" here happens when `KThread.Exit` is called, and at this point `StopRunning` is called, which will set the `Running` property to false and force a interrupt. The interrupt will happen *after* `StopRunning` is called, which might trigger the exception if the memory manager was already disposed. This doesn't always happen because the memory manager is disposed only after all threads exit, and it is …
=> Fix GetUserDisableCount NRE

Ryujinx.Common/Configuration/Hid/Controller/JoyconConfigControllerStick.cs, Ryujinx.Headless.SDL2/Program.cs, Ryujinx.Input.SDL2/SDL2Gamepad.cs, Ryujinx/Ui/Windows/ControllerWindow.cs, Ryujinx/Ui/Windows/ControllerWindow.glade
One solution to feature request #2287
Instead of mapping axes independently I added simple option to swap X/Y sticks.
NOTE: I encountered an issue that probably needs fixing. Inverting axes options work properly if we select Pro Controller or Joycon Pair for controller type, but if we select Joycon Right, invert options for left sticks are actually used for right stick.
=> Implement rotate stick 90 degrees clockwise

Ryujinx.HLE/HOS/Services/Olsc/IOlscServiceForApplication.cs
This PR implement `GetSaveDataBackupSetting` of OLSC service which is now needed by ACNH 2.0.5.
The game is playable as usual if you use the same user profile as the original save file (I don't know if it was the case before), everything is checked by RE. (Closes #3140)
=> olsc: Implement GetSaveDataBackupSetting

Ryujinx.Graphics.Shader/Translation/Translator.cs
Fix regression on Game Builder Garage introduced on https://github.com/Ryujinx/Ryujinx/pull/3054, passthrough attributes should not be initialized because they are already passed from the previous stage to the next.
Diff is the same as https://github.com/Ryujinx/Ryujinx/pull/3106.
=> Do not initialize geometry shader passthrough attributes

Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, Ryujinx.Graphics.Shader/Translation/UInt128.cs
Fixes another regression from https://github.com/Ryujinx/Ryujinx/pull/3054, this time making sure that *indexed* inputs are intialized. Since it can't guess which output the next stage might access when they are indexed, it just initializes all of them.
Fixes a regression that would cause shaders to fail to compile on WarioWare: Get It Together! and probably other games using indexed attributes.
(GIft was not showing before here).
=> Initialize indexed inputs used on next shader stage

Ryujinx.Graphics.Gpu/Memory/BufferCache.cs
Some games have a buffer usage pattern where it uses small adjacent buffers with increasing addresses. Right now this causes a new buffer to be created each time, merging the existing overlapping buffers. So that is effectively resizing the existing buffer all the time, page by page which is very inefficient.
This change attempts to address that by dynamically increasing the size based on the current buffer size. Currently it uses a growth rate of 1.5x. So if the existing buffer has 64KB and it attempts to extend it by one page to 68KB, then the new size will be 64KB * 1.5 = 96KB. Further attempts to extend it again by 4KB to 72KB, 76KB, 80KB etc, will be effectively a no-op since the 96KB buffer can already fit all the data.
The downsize of this approach is that it can use a bit more …
=> Dynamically increase buffer size when resizing

Ryujinx.Graphics.GAL/Format.cs, Ryujinx.Graphics.Gpu/Engine/Types/ZetaFormat.cs, Ryujinx.Graphics.Gpu/Image/FormatTable.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.OpenGL/FormatTable.cs, Ryujinx.Graphics.OpenGL/Framebuffer.cs, Ryujinx.Graphics.OpenGL/Image/FormatConverter.cs, Ryujinx.Graphics.OpenGL/Image/TextureCopy.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs
The main change here is a implementation of the S8D24 format, which has 24-bits of depth and 8-bits of stencil, similar to the D24S8 format but with the inverse ordering. As OpenGL does not support the format, a function has been added to swap the ordering, and then it just uses the regular D24S8 format. I replaced the old D24X8 format with S8D24 because D24X8 was not actually used anywhere (the backend and GPU emulation did take it into account, but nothing actually produced this format, as it was not in any of the format tables).
This changes fixes starbits interaction on Super Mario Galaxy, now allowing the game to be progressed through.
Thanks to @riperiperi for finding the problem.
Note: It's recommended to test with https://github.com/Ryujinx/Ryujinx/pull/2861 to improve the initial …
=> Implement S8D24 texture format

Ryujinx.HLE/HOS/Services/Nifm/StaticService/IGeneralService.cs
Hello, this is my first PR to this project so hopefully I did what's needed to maintain a level of coding quality. I will spend a majority of this post explaining why I did what I did and why it resolves #2533 (At least partially)
**First let's talk about FPS improvements:**
Mainline: ~15-16 FPS
W/ this PR:  (Hits 30 FPS easily)
**Now lets talk changes:**
There is only one function change, it is a rewrite of the GetCurrentIpAddress(ServiceCtx context) this is done to mitigate the time that the GetLocalInterface() takes because it has a nested loop and in the current mainline, the first return is immediately discarded so I figured a faster, more targeted method would help mitigate the issues presented in #2533 which it did. I use a method which involves using System.Net and the …
=> Caching local network info and using an event handler to invalidate as needed (improves menu slow down issue in FE3H)

ARMeilleure/Instructions/InstEmitMemoryEx.cs, ARMeilleure/Instructions/InstEmitMemoryEx32.cs, ARMeilleure/Translation/PTC/Ptc.cs
In theory, mfence should be after a write.
Games that would likely be affected by this and would require testing:
* Pokémon Mystery Dungeon (boot) 
* Pokémon Brilliant Diamond/Shining Pearl (entering/exiting buildings)
* Pokémon Legends Arceus (anywhere)
Please note an alternative to this is to just implement an ordered write as a single instruction (`lock xchg`) which has a built-in memory fence.
=> InstEmitMemoryEx: Barrier after write on ordered store

Ryujinx.HLE/HOS/Services/Olsc/IOlscServiceForApplication.cs
This PR fixes a condition previously implemented in #3190 where ACNH can't be booted without an existing savedata.
Closes #3206
=> oslc: Fix condition in GetSaveDataBackupSetting

Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Window.cs
OpenGL game overlays and hooks tend to make a lot of assumptions about how games present frames to the screen, since presentation in OpenGL kind of sucks and they would like to have info such as the size of the screen, or if the contents are SRGB rather than linear.
There are two ways of getting this. OBS hooks swap buffers to get a frame for video capture, but it actually checks the bound framebuffer at the time. I made sure that this matches the output framebuffer (the window) so that the output matches the size. RTSS checks the viewport size by default, but this was actually set to the last used viewport by the game, causing the OSD to fly all across the screen depending on how it was used (or res scale). The viewport is now manually set to match the output framebuffer size.
In the …
=> Fix OpenGL issues with RTSS overlays and OBS Game Capture

Ryujinx.Graphics.OpenGL/Pipeline.cs
Fixes a driver crash when starting some games caused by #3217
Also fixes the possibility of this happening with DrawTexture, which existed before.
=> Don't restore Viewport 0 if it hasn't been set yet.

Ryujinx.Memory.Tests/TrackingTests.cs
The below intermittent test failure is a recurrent problem on CI.
e.g. https://github.com/Ryujinx/Ryujinx/runs/5619181112?check_suite_focus=true
```   Failed Multithreading [846 ms]
Error Message:
Expected: greater than 10
But was:  0
Stack Trace:
at Ryujinx.Memory.Tests.TrackingTests.Multithreading() in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory.Tests\TrackingTests.cs:line 287
Failed!  - Failed:     1, Passed:    81, Skipped:     0, Total:    82, Duration: 2 s - Ryujinx.Memory.Tests.dll (net6.0)```
=> Memory.Tests: Make Multithreading test explicit

Ryujinx.Graphics.Shader/CodeGen/Glsl/CodeGenContext.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs
The multisample and buffer overloads does not take a lod parameter, because multisample and buffer textures can't have mipmaps. This removes the inexistent parameter from the GLSL code generation.
Fixes #3238.
=> Fix shader textureSize with multisample and buffer textures

Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs
We should not force a scissor on clears if the respective scissor is disabled.
This fixes some glitckes on Kirby and the Forgotten Land and maybe other titles caused by textures not being fully cleared, and "garbage" data from previous textures being carried over.
Before:
After:
=> Do not force scissor on clear if scissor is disabled

Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClassState.cs
Primitive restart is a feature that allows "spliting" the vertex stream when a special index value (called primitive restart index) is read from the index buffer. However, on OpenGL it also applies to non-indexed draws. In that case, it will split the stream after "primitive restart index" vertices. Vulkan does not have this behaviour, and the spec explicitly calls out that it only applies to indexed draws:
> primitiveRestartEnable controls whether a special vertex index value is treated as restarting the assembly of primitives. This enable only applies to indexed draws ([vkCmdDrawIndexed](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCmdDrawIndexed.html), [vkCmdDrawMultiIndexedEXT](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCmdDrawMul …
=> Implement primitive restart draw arrays properly on OpenGL

Ryujinx.Graphics.OpenGL/Renderer.cs
When using OpenGL compatibility profiles, fragment clamping behaviour is set to "FIXED_ONLY", which as per the spec:
> The default state for fragment clamping is "FIXED_ONLY", which
has the behavior of clamping colors for fixed-point color buffers
and not clamping colors for floating-pont color buffers.
and:
>   If fragment
clamping is enabled, the final fragment color values or the final
fragment data values written by a fragment shader are clamped to
the range [0, 1] and then may be converted to fixed-point as
described in section 2.14.9.  If fragment clamping is disabled,
the final fragment color values or the final fragment data values
are not modified.
This means that UNorm outputs are clamped to the [0, 1] range (which is fine, UNorm can't store values outside that range), but also …
=> Do not clamp SNorm outputs to the [0, 1] range on OpenGL

Ryujinx.Audio/Renderer/Dsp/Command/DelayCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/Reverb3dCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/ReverbCommand.cs, Ryujinx.Audio/Renderer/Dsp/DataSourceHelper.cs, Ryujinx.Audio/Renderer/Dsp/State/Reverb3dState.cs, Ryujinx.Audio/Renderer/Dsp/State/ReverbState.cs, Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs, Ryujinx.Audio/Renderer/Server/BehaviourContext.cs, Ryujinx.Audio/Renderer/Server/CommandBuffer.cs, Ryujinx.Audio/Renderer/Server/CommandGenerator.cs, Ryujinx.Audio/Renderer/Server/CommandProcessingTimeEstimatorVersion3.cs, Ryujinx.Audio/Renderer/Server/CommandProcessingTimeEstimatorVersion5.cs
This should implement all ABI changes from REV11 on 14.0.0
As Nintendo changed the channel disposition for "legacy" effects (Delay, Reverb and Reverb 3D) to match the standard channel mapping, I took the liberty to just remap to the old disposition for now.
The proper changes will be handled at a later date with a complete rewriting of those 3 effects to be more readable (see https://github.com/Ryujinx/Ryujinx/pull/3205 for the first iteration of it).
=> amadeus: Update to REV11

Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
HW signals this event after `AcquireNpadStyleSetUpdateEventHandle` is called regardless of the controller status. Fixes random controller disconnects on Flip Wars
=> service: hid: Signal event on AcquireNpadStyleSetUpdateEventHandle

Ryujinx.Audio/Renderer/Dsp/Command/DelayCommand.cs, Ryujinx.Audio/Renderer/Dsp/State/DelayState.cs, Ryujinx.Audio/Renderer/Utils/Math/Matrix2x2.cs, Ryujinx.Audio/Renderer/Utils/Math/Matrix6x6.cs, Ryujinx.Audio/Renderer/Utils/Math/MatrixHelper.cs, Ryujinx.Audio/Renderer/Utils/Math/Vector6.cs
This rework the delay effect processing by representing calculation with the appropriate matrix and by unrolling some loops in the code.
This allows better optimization by the JIT while making it more readable.
Also fix a bug in the Surround code path found while looking back at my notes.
=> amadeus: Improve and fix delay effect processing

Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs
This change aims to make the size of vertex buffers that are too large smaller.
First, I will describe an approach that I have tried on the past. Since on indexed draws, the vertex index comes from the index buffer, we can find an upper bound, that is, the maximum vertex index that can possibly be accessed by examining all entries on the index buffer. From that, we can calculate a maximum size by multiplying the value by the vertex buffer stride.
This has a few problems:
- We don't know if the index buffer was written from CPU or GPU. If it was written by the GPU, then it is most likely in GPU memory and we need to flush the data to examine it (which is expensive).
- Checking the entire index buffer to get the maximum index might not be exactly cheap depending on the index buffer size. So …
=> Calculate vertex buffer size from index buffer type

Ryujinx.HLE/HOS/ModLoader.cs, Ryujinx/Ui/Widgets/GameTableContextMenu.cs
This prompt was fairly redundant and was just another box to click. 
Creation of mod directories do not require this extra step and it seems weird to keep this one. If there is a particular reason to keep this around then I'm all ears but I currently can't see a scenario where a user wishes to open a directory... then says "No" when asked to create one.
The logger now simply reads when a directory has been created instead.
=> Remove save data creation prompt

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs
We have no way to know if textures are multisampled on the 2D engine for copies. Currently, this is handled by allowing the matched texture to be multisampled, even if we are looking for a non-multisample 2D texture for copies. The problem is that right now, this is only allowed for *exact* matches, which means that if the copy texture is slightly different from the one in the cache (for example, the format is different, such as render target texture being Unorm and copy one being Srgb), exact match will fail and it will try to create a view instead, or new texture if that fails too.
This case is happening on Pinball FX3 with the update. Render target is Unorm, copy is Srgb, exact match fails, view match fails because the target is different (render target is 2DMultisample, copy is just …
=> Allow copy texture views to have mismatching multisample state

ARMeilleure/CodeGen/Optimizations/TailMerge.cs, ARMeilleure/Signal/NativeSignalHandler.cs, ARMeilleure/Translation/PTC/Ptc.cs
This fixes two issues.
First, it fixes a regression from the tail merge optimization (#2721). This optimization can make multiple blocks that end with a return instruction instead jump to a single return block. This has the advantage of reducing code size as we only need to emit the epilogue for one block instead of several blocks. Additionally, this optimization also tries to remove blocks if, for example, the only instruction on a block is a return. However, there was one case where this was producing incorrect code. Consider the following IR:
```
block0 (block1, block2):
i64 %0 = LoadArgument i32 0x0
i64 %1 = Load i64 %0
i32 %2 = Load i64 %1
BranchIf i32 %2, i32 0xC0000005, Equal
block1:
Return i32 0x0
block2 (block3, block4):
i32 %3 = Load i64 0x22D7B2D5BE0
i32 %4 = Load i64 …
```
=> Fix tail merge from block with conditional jump to multiple returns

Ryujinx.Common/System/ForceDpiAware.cs
Detect dpi based on screen dimensions provided by X server. As is standard expected behavior of a Linux application, this can be overridden by the user's Xft.dpi setting.
=> ForceDpiAware: X11 implementation

Ryujinx.HLE/HOS/Services/Audio/HardwareOpusDecoderManager/Decoder.cs, Ryujinx.HLE/HOS/Services/Audio/HardwareOpusDecoderManager/DecoderCommon.cs, Ryujinx.HLE/HOS/Services/Audio/HardwareOpusDecoderManager/IDecoder.cs, Ryujinx.HLE/HOS/Services/Audio/HardwareOpusDecoderManager/IHardwareOpusDecoder.cs, Ryujinx.HLE/HOS/Services/Audio/HardwareOpusDecoderManager/MultiSampleDecoder.cs, Ryujinx.HLE/HOS/Services/Audio/IHardwareOpusDecoderManager.cs, Ryujinx.HLE/HOS/Services/Audio/Types/OpusMultiStreamParameters.cs, Ryujinx.HLE/HOS/Services/Audio/Types/OpusMultiStreamParametersEx.cs, Ryujinx.HLE/HOS/Services/Audio/Types/OpusPacketHeader.cs, Ryujinx.HLE/HOS/Services/Audio/Types/OpusParametersEx.cs
This PR mainly implements the multistream related Opus decoding functions, that are required by MLB The Show 22 and maybe other games. In addition to that, it does some small refactoring to avoid code duplication:
- Implementation of decoding moved to a single method to avoid code duplication.
- Decoding now uses spans rather than streams when possible. Unfortunately Concentus doesn't have overloads of the decoding functions that takes spans, so we still need to do some copies.
- GetWorkBufferSize functions were updated, before it was only taking the ADSP side into account and only calculating the size of the Opus decoder state. But the service also adds an extra size, so the code was updated to reflect that. This shouldn't have any consequence though as we don't really use the transfer …
=> Implement HwOpus multistream functions

Ryujinx.Input/HLE/NpadController.cs
Right now on Master, when using motion controls with SDL2 (the default option), multiple games suffer from completely broken motion controls making them unplayable when the option is used.
Some games such as Kirby and the Forgotten Land require motion controls to complete them at 100%.
This was due to a missing `-` in front of `gyroscope.Z` in the controller config file.
This PR fixes that.
I tested Mario Kart 8 Deluxe and The Legend of Zelda: Breath of the Wild and in both cases it fixed the issues reported by users and myself, this PR should also fix most of the other issues reported as they were all the same issue.
Needs testing on multiple games to make sure nothing broke and needs testing on different controllers such as DS4 and DS5 just to be sure. I tested on the Pro Controller and …
=> Fix broken motion controls when using SDL2.

Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Graphics.Gpu/Image/TextureGroupHandle.cs, Ryujinx.Memory/Tracking/RegionHandle.cs
A variable called _actionRegistered is used to keep track of whether a tracking action has been registered for a given texture group handle. This variable is set when the action is registered, and should be unset when it is consumed. This is used to skip registering the tracking action if it's already registered, saving some time for render targets that are modified very often.
There were two issues with this. The worst issue was that the tracking action handler exits early if the handle's modified flag is false... which means that it never reset _actionRegistered, as that was done within the Sync() method called later. The second issue was that this variable was set true after the sync action was registered, so it was technically possible for the action to run immediately, set the flag …
=> Fix various issues with texture sync

Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs
This fixes some regression introduced by #3253, like some glitches on Xenoblade Chronicles 2 blade awakening cutscenes. First, we can't guess the vertex buffer size from the index buffer type when the draw is not indexed, as in those cases the index buffer type is completely meaningless. This also does not allow it for instanced vertex buffers as I believe it might be possible to access vertices outside of the range in those cases (due to vertex being incremented per instance, might be wrong though). I have verified that it still works for Perky Little Things and Super Mario 64, which is what the previous PR fixed.
=> Restrict cases where vertex buffer size from index buffer type is used

Ryujinx.Memory/Tracking/RegionHandle.cs
If two or more threads encounter a region of memory where a read action has been registered, then they must _both_ wait on the data.
Clearing the action before it completed was causing the null check above to fail, so the action would only be run on the first thread, and the second would end up continuing without waiting. Depending on what the game does, this could be disasterous.
This fixes a regression introduced by #3302 with Pokemon Legends Arceus, and possibly Catherine. There are likely other affected games. What is fixed in that PR should still be fixed.
=> Fix flush action from multiple threads regression

Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/Kernel/KernelStatic.cs, Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs, Ryujinx.HLE/HOS/ProgramLoader.cs, Ryujinx.HLE/HOS/Services/Pm/IDebugMonitorInterface.cs
This basically implements the few missing pieces to make the Skyline + ARCcropolis mods work.
Two changes here:
- Implement the `GetProcessInfo` atmosphere extension that this mod uses just to get a handle to the game process, to use the code memory syscalls. I'm not a fan of implementing extensions, and considered puting this behind an option, but it's probably better to just always expose it since it would be just more work for people using the mod otherwise (unless its enabled by default). There are also other ways to get a handle to the process without using any extensions (although they are a bit convoluted).
PPTC is automatically disabled when the mod is used because it detects "incompatible" exefs modifications.
**NOTE:** This has only been tested on version 3.0.0-beta.2.6 of …
=> Implement PM GetProcessInfo atmosphere extension (partially)

Ryujinx.Memory/WindowsShared/PlaceholderManager.cs
Removes the `count > 0` assert as it doesn't make sense, since count will be 0 if the protection didn't already exist before. Likely a leftover from one of my previous implementations before I arrived at the final version.
No impact on release builds, only impacts debug builds.
=> Remove AddProtection count > 0 assert

Ryujinx.HLE/HOS/Services/Ro/IRoInterface.cs, Ryujinx.Memory/MemoryBlock.cs, Ryujinx.Memory/MemoryManagement.cs, Ryujinx.Memory/MemoryManagementWindows.cs, Ryujinx.Memory/WindowsShared/PlaceholderManager.cs, Ryujinx.Memory/WindowsShared/PlaceholderManager4KB.cs
Fixes the following issues:
- Windows requires all view mappings to be unmapped to release the memory. Just closing the file mapping handle is not enough. This was not being done which caused several GBs of memory to leak after the emulation was stopped (or on multi-title games, after switching from one title to the other).
- When using forced 4KB view mapping, if the mapping was done on memory that was already mapped, it would fail. Now it unmaps the memory before mapping in this case. This matches the other implementation that does not work page-by-pagee.
- When using forced 4KB view mappings, if there was a region in memory adjacent with the regular mapping, it would try to coalesce the two which might be invalid as the placeholder manager does not keep track of those 4KB mappings. …
=> Fix shared memory leak on Windows

Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs, Ryujinx.HLE/HOS/Services/Ro/IRoInterface.cs, Ryujinx.HLE/HOS/Services/ServerBase.cs, Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs, Ryujinx.HLE/HOS/Services/Sm/IUserInterface.cs, Ryujinx.HLE/HOS/Services/Sm/SmRegistry.cs
This change allows the JIT service, required by the NSO N64 emulator and Super Mario 3D All Stars (for Super Mario 64), to run. It is not an actual service implementation, rather it runs the service on the firmware, so this is an "LLE" approach as opposed to the usual HLE approach where we re-implement the service on the emulator. There are a few reason for using this approach here:
- The JIT service needs to call an (Arm) user supplied function, which would be very complicated to do from a HLE service.
- Unlike other services, this one is initialized on-demand (when PrepareForJit is called), which means we don't need to initialize it for games that does not require it, minimizing the impact of those changes.
- The service has few dependencies, so it's easy to get it running.
Notes:
- …
=> Enable JIT service LLE

Ryujinx.Graphics.GAL/StencilOp.cs, Ryujinx.Graphics.OpenGL/EnumConversion.cs
This PR adds the alternative enum values for StencilOp. Similar to the other enums, I added these with the same names but with Gl added to the end. These are used by homebrew using Nouveau, though they might be used by games with the official Vulkan driver.
Reference for the values from envytools:
https://github.com/envytools/envytools/blob/39d90be897f41434d67277ebdf244d6bd419ecd9/rnndb/graph/nv_3ddefs.xml#L77
Fixes some broken graphics in the Citra RetroArch core, such as missing shadows in Mario Kart 7. Likely fixes other homebrew.
Before:
After:
=> Add alternative "GL" enum values for StencilOp

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs, Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/HidUtils.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/Types/Npad/HidNpadJoyAssignmentMode.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/Types/Npad/NpadHandheldActivationMode.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/Types/Npad/NpadJoyDeviceType.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/Types/SixAxis/AccelerometerParameters.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/Types/SixAxis/GyroscopeZeroDriftMode.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/Types/SixAxis/SensorFusionParameters.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/Types/Vibration/HidVibrationDeviceValue.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/Types/Vibration/VibrationDeviceHandle.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/Types/Vibration/VibrationDevicePosition.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/Types/Vibration/VibrationDeviceType.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/Types/Vibration/VibrationDeviceValue.cs, Ryujinx.HLE/HOS/Services/Hid/HidServer/Types/Vibration/VibrationValue.cs, Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs, Ryujinx.Input/HLE/NpadController.cs
This PR implement `am IsGamePlayRecordingSupported` needed by RetroArch. (and fixes `SetGamePlayRecordingState` which uses the same field).
Additionnally to that, RetroArch have an issue related to the number of max players, which is set to 16 as default (fixed here: https://github.com/libretro/RetroArch/commit/aefc0de8d7c2bf30b78002c75eae12f21fb6176f). Since the number of max players on Switch is 8, it throw an exception in our `hid` code because we don't check anything. This is now fixed accordingly to RE.
Now `SetNpadJoyAssignmentModeSingleByDefault`, `SetNpadJoyAssignmentModeSingle`, `SetNpadJoyAssignmentModeDual`  and `SetNpadJoyAssignmentModeSingleWithDestination` are implemented (partially for some)
I've removed the `Hid` suffix on some type because it make no sense and it's not …
=> hid: Various fixes and cleanup

Ryujinx.Graphics.Gpu/GpuContext.cs, Ryujinx.Graphics.Gpu/Shader/DiskCache/ParallelDiskCacheLoader.cs, Ryujinx.Headless.SDL2/WindowBase.cs
The Backend Multithreading only expects one thread to submit commands at a time. When compiling shaders, the translator may request the host GPU capabilities from the backend. It's possible for a bunch of translators to do this at the same time.
There's a caching mechanism in place so that the capabilities are only fetched once. By triggering this before spawning the thread, the async translation threads no longer try to queue onto the backend queue all at the same time.
The Capabilities do need to be checked from the GPU thread, due to OpenGL needing a context to check them, so it's not possible to call the underlying backend directly.
=> Prefetch capabilities before spawning translation threads.

Ryujinx.Ava/AppHost.cs, Ryujinx.Ava/Ui/Controls/RendererControl.cs, Ryujinx.Ava/Ui/Windows/MainWindow.axaml.cs, Ryujinx/Ui/GLRenderer.cs, Ryujinx/Ui/RendererWidgetBase.cs
Scales the blit to the window's framebuffer. Should fix rendering when desktop scaling is over 150%
=> UI - Scale end framebuffer blit

Ryujinx.HLE/HOS/Services/Audio/AudioRenderer/AudioRendererServer.cs
The error message has a `0x` prefix which leads one to believe that the number of hexadecimal, but since there's no specifier for the number base it will just print as decimal, or in some cases it will just display 0x followed by the result name, if it's on the result code enum. Fix this by casting the result to integer and using the `:X` specifier to print as hex.
This just changes how the error is printed on the log/console, should have no other effect.
=> Fix audio renderer error message result code base

Ryujinx.Ava/Program.cs
Fixes an issue where per-monitor DPI was not working - it would just select the lowest DPI and scale the window surface up when moving to other monitors instead of switching application DPI. I guess avalonia already has this under control, so no need to tell windows any different. Makes things a little sharper on my 2nd screen.
It's worth noting that GTK doesn't support this at all.
Before:
After:
=> Don't force DPI aware on Avalonia

Ryujinx.HLE/HOS/ApplicationLoader.cs
Some homebrews are packed as a NSP, but without NCAs inside, instead the ExeFS contents are stored directly on the NSP. It looks like the code was already supposed to support this, but someone added a check that makes it fail when no main NCA is found. I removed the check to allow NSP homebrews to be loaded.
=> Allow loading NSPs without a NCA inside

Ryujinx.Graphics.Gpu/Engine/Threed/SemaphoreUpdater.cs
Counter type 0 actually releases the semaphore payload rather than a constant zero as was previously thought. This is required by Skyrim.
=> Fix 3D semaphore counter type 0 handling

Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostChannel/NvHostChannelDeviceFile.cs
The syncpoint maximum value represents the maximum possible syncpt value at a given time, however due to PBs being submitted before max was incremented, for a brief moment of time this is not the case which could lead to invalid behaviour if a game waits on the fence at that specific time.
=> Fix a potential GPFIFO submission race

Ryujinx.Graphics.GAL/Target.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, Ryujinx.Graphics.OpenGL/Image/IntermmediatePool.cs, Ryujinx.Graphics.OpenGL/Image/TextureCopy.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs
On the GPU, there are cases where we know that a texture is multisampled, and there are some cases that we don't know, the cases where we don't know, we have an overlap at the same address of a multisample texture, with a width and height that is equal to the multisample width and height multiplied by the amount of samples in X and Y respectively. Since multisample and non-multisample textures are not considered "compatible" in any API, most of those cases are not handled. Currently, there are a few tricks used to make some cases work. 2D engine blit source textures wil get multisample textures from the cache if it can find one at the requested address. Notably, the cases where a texture on the pool accessed from a shader does not have a multisample type on the texture descriptor is not …
=> Copy dependency for multisample and non-multisample textures

ARMeilleure/IntermediateRepresentation/Operand.cs
Currently, the operand uses count (and capacity) is limited to a `ushort`, mostly to save memory. The maximum number of uses a variable may have is then 65535, since this is the maximum value you can store on a `ushort`. For 99% of the games that is enough, however there are a few games with very large blocks using mostly the same register over and over again. This pattern can easily reach the limit.
The fix here is simply changing the type used to store the uses count and capacity from `ushort` to `uint`, which now increases the limit to 2147483647 which is the signed 32-bit integer maximum value. The actual amount of memory used didn't actually increase since that, due to alignment, the structure size in memory was 48 bytes. It had 5 unused bytes, so now 4 of them are being occupied by …
=> Extend uses count from ushort to uint on Operand Data structure

Ryujinx.Memory/MemoryBlock.cs, Ryujinx.Memory/MemoryManagement.cs, Ryujinx.Memory/MemoryManagementWindows.cs, Ryujinx.Memory/WindowsShared/PlaceholderManager.cs
The freed memory range was not being removed from the tree, which could cause it to try coalescing the (now inexistent) placeholder with the placeholder of the new region that was allocated. This would usually happen when a new mapping was created on an adjacent memory region, for example when the emulation was stopped for one game and another was launched, there was the change that it would throw the following exception:
```
Ryujinx.Memory.WindowsShared.WindowsApiException: VirtualFree returned error code 0x1E7.
```
This PR should fix the issue making sure the freed range is fully removed from the tree when the memory block is disposed. Additionally, this is limiting the range of memory that it tries to coalesce to just inside of a memory block, so that it won't try to coalesce different …
=> Remove freed memory range from tree on memory block disposal

Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, Ryujinx.Graphics.Gpu/Engine/Threed/IbStreamer.cs
#3383 fixed the issue where the index buffer, count and potentially draw type would be incorrect. However, it still had one issue. The index count used on the draw would be the total index count for all instances, which causes it to overdraw. This fixes the issue now passing the count for a single instance.
For example, below you can see the counts before and after on RenderDoc:
Before:
After:
On the games the original fix was targeting, this did not cause visual issues (which is why I didn't notice it was wrong), only performance issues from it drawing the same thing over and over. So now the game is a bit faster on those 3D sections.
=> Fix instanced indexed inline draw index count

Ryujinx.Graphics.OpenGL/Pipeline.cs
When using the draw textures fallback (used when the NV_draw_texture extension is not supported), we should ignore current ClipControl settings, otherwise it can cause the viewport to be flipped. That was causing some games to be upside down on AMD and Intel, like Moero Chronicles and friends (fox example, see https://github.com/Ryujinx/Ryujinx-Games-List/issues/182#issuecomment-1147521009). NVIDIA is not affected because it supports the NV_draw_texture extension and ClipControl does not seem to affect DrawTexture.
=> Ignore ClipControl on draw texture fallback

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs, Ryujinx.HLE/HOS/Services/ServerBase.cs, Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/EventFileDescriptor.cs
The `Read` and `Write` methods are supposed to be called from different threads, but there are two issues that prevents it from working in some cases:
- Currently only one thread is processing BSD IPC requests. So if any of the methods blocks, it will be unable to process requests submitted from other guest threads. This means that if one thread calls blocking `Read` and another calls `Write` after, the `Write` request will never be processed because it will be blocked on `Read`.
- Both `Read` and `Write` methods are taking the same lock. So even if the issue above didn't exist, calling both methods would result in a deadlock.
To fix the first issue I have changed `ServerBase` and added a new optional argument that allows one to specify a thread count, which defaults to 1. This thread …
=> Allow concurrent BSD EventFd read/write

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Services/ServerBase.cs, Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/EventFileDescriptor.cs
https://github.com/Ryujinx/Ryujinx/pull/3385 fixed a issue where blocking Read/Write operations would prevent all sockets requests from being processed, because only one thread was processing them. However, it introduced another issue. Since right now the IPC processing is not thread safe, it was breaking in some games that uses sockets. like Pokémon Sword/Shield, where the game would crash after a few seconds with the following exception:
```
Unhandled exception. System.NotImplementedException: HipcResponse
```
It seems to indicate one thread is trying to process TLS where a response was just written by another thread.
In order to fix this, I made it only use one thread for sockets again, and to avoid regressing Diablo 2 again I forced the non-blocking flag to prevent the thread from …
=> Less invasive fix for EventFd blocking operations

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.GAL/Multithreading/Commands/ClearRenderTargetColorCommand.cs, Ryujinx.Graphics.GAL/Multithreading/Commands/ClearRenderTargetDepthStencilCommand.cs, Ryujinx.Graphics.GAL/Multithreading/ThreadedPipeline.cs, Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClass.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.OpenGL/Framebuffer.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs
This fixes two issues.
First, it adds support for array and 3D textures to depth-stencil render targets. Before, only the color render targets had support for this, and in cases where an Array render target was used with a depth buffer for example, it would cause a framebuffer completness error on OpenGL and not draw anything.
The second and more problematic issue is that render target clears takes a layer parameter, but it was being ignored. What is worse is that it decides if the render target is layered or not based on shader state, and since the shader state is not updated for clears, it might not consider the texture layered at all. This means that often only the first layer would be cleared. To fix this, first I made it force the texture to be considered layered if the clear layer …
=> Support Array/3D depth-stencil render target, and single layer clears

Ryujinx.Graphics.Gpu/Image/Pool.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TextureDescriptor.cs, Ryujinx.Graphics.Gpu/Shader/ShaderSpecializationState.cs
The texture ID might not be valid at the time the shader is compiled or specialization check (perhaps because the game did not bind the texture yet, either due to a bug or because the shader accesses it conditionally and the path were it is accessed is not supposed to be taken), so be must not try to read the descriptor in those cases as it could access unmapped memory and crash.
This adds an additional check before doing the access. If not valid, it will use a texture descriptor with the most common state. Doing so might avoid future shader recompilation due to state changes (in the case the texture is actually bound later).
This was causing a crash on A Hat in Time before reaching the title screen after progressing at a certain point in the game.
Fixes #3390.
=> Ensure texture ID is valid before getting texture descriptor

Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs, Ryujinx.Memory/Tracking/MemoryTracking.cs
This fixes two issues. The first issue is that `VirtualMemoryEvent` will call `_invalidAccessHandler` on invalid access, but it does so holding the `ThreadingLock`. Because the current invalid access handler prints the guest stack trace, it calls the HLE kernel `QueryMemory` function that will take memory manager locks. Since the memory manager calls CPU map/unmap methods which calls Tracking map/unmap methods, and those methods will also try to acquire the `TrackingLock`, this can cause deadlock if the invalid access happens when a guest memory mapping operation is in progress. This was fixed by calling it after releasing the lock.
The second issue was in kernel, when `TerminateProcess` is called, it will attempt to terminate all running threads, but it also requests the termination of …
=> Fix ThreadingLock deadlock on invalid access and ExitProcess

Ryujinx.Common/Memory/Box.cs, Ryujinx.HLE/HOS/Services/Time/StaticService/ITimeZoneServiceForGlue.cs, Ryujinx.HLE/HOS/Services/Time/StaticService/ITimeZoneServiceForPsc.cs, Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZone.cs, Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZoneContentManager.cs, Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZoneManager.cs, Ryujinx.HLE/HOS/Services/Time/TimeZone/Types/CalendarAdditionalInfo.cs, Ryujinx.HLE/HOS/Services/Time/TimeZone/Types/TimeTypeInfo.cs, Ryujinx.HLE/HOS/Services/Time/TimeZone/Types/TimeZoneRule.cs, Ryujinx.HLE/Utilities/StringUtils.cs
This drastically reduce overhead of using TimeZoneRule around the codebase by avoiding to copy TimeZoneRule 16384 bytes all around.
Effect on games is unknown but could improve perf a bit depending on JIT output.
=> time: Make TimeZoneRule blittable and avoid copies

Ryujinx.HLE/HOS/Services/Time/TimeZone/Types/TimeTypeInfo.cs, Ryujinx.HLE/HOS/Services/Time/TimeZone/Types/TimeZoneRule.cs, Ryujinx.Tests/Ryujinx.Tests.csproj, Ryujinx.Tests/Time/TimeZoneRuleTests.cs
Because of that PR, TimeZoneRule was bigger than 0x4000 thanks to a
misuse of a constant.
This PR address this issue and add a new unit test to ensure the size of
TimeZoneRule is 0x4000 bytes.
Also address suggestions that were lost on the original PR.
Close https://github.com/Ryujinx/Ryujinx/issues/3417
=> timezone: Fix regression caused by #3361

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs
#3399 tries to avoid texture binding updates if the state does not change, however it has one flaw, it checks if the texture and sampler IDs changed, and checks if the pool contents changed, but it does not check if the pool itself changed. This causes issues for games that changes the pools but keeps the same bindings. This seems pretty rare so I believe the number of games affected by the regression is low.
Fixes regression on Super Zangyura.
Before:
After:
Closes #3419.
=> Account for pool change on texture bindings cache

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/TextureHandle.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs
This is extending the shader bindless texture access elimination to also work on cases where the texture handle is being combined with a constant handle value using bitwise OR operation.
Doing so allows Monster Hunter Rise Sunbreak to render (it was just showing black screen before):
Still does not reach the title screen due to other issues.
Testing is welcome. Probably a good idea to test The Witcher 3 and Hades since those two uses the other "odd" handle combinations.
=> Bindless elimination for constant sampler handle

Ryujinx.HLE/HOS/Services/Ptm/Ts/IMeasurementServer.cs
This stub GetTemperature of ptm service, needed by the latest version of Homebrew Menu. (Fixes #3422)
=> ptm: Stub GetTemperature

ARMeilleure/Instructions/InstEmitSimdCvt.cs, ARMeilleure/Instructions/SoftFloat.cs, ARMeilleure/Translation/Delegates.cs, ARMeilleure/Translation/PTC/Ptc.cs, Ryujinx.Tests/Cpu/CpuTestSimd.cs
This implements the half to double and double to half conversion variants of the FCVT instruction. Fast paths does Half -> Single -> Double and Double -> Single -> Half since x86 has no instruction to convert directly between them (except with one of the AVX-512 extensions).
This is required by Portal, when combined with #3438 the game seems to be playable:
=> Implement CPU FCVT Half <-> Double conversion variants

Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs, Ryujinx.HLE/HOS/Services/SurfaceFlinger/LayerState.cs, Ryujinx.HLE/HOS/Services/SurfaceFlinger/SurfaceFlinger.cs, Ryujinx.HLE/HOS/Services/Vi/RootService/ApplicationDisplayService/IManagerDisplayService.cs, Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
This fixes the Vi implementation of the layer management related functions to match what the service does:
- `CreateStrayLayer` sets the layer state to `Stray`, `CreateManagedLayer` and friends sets the state to `ManagedClosed`.
- `OpenLayer` returns an error if the layer ID does not exist. The previous implementation would create a new layer in this case.
- `OpenLayer` returns an error if the layer state is not `ManagedClosed`. This is the case for layers created by `CreateStrayLayer`, or layers that were already opened. The previous implementation would not return an error and open it again.
- `OpenLayer` sets the state to `ManagedOpened`.
- `CloseLayer` sets the state to `ManagedClosed` if it is `ManagedOpened`. The previous implementation would fully remove the layer, which causes …
=> Fix Vi managed and stray layers open/close/destroy

Ryujinx.Ava/Input/AvaloniaMouseDriver.cs
Fixes a deadlock that occurs if you open any window while direct mouse input is enabled.
=> Fix deadlock in mouse input on Avalonia

Ryujinx.Ava/AppHost.cs, Ryujinx.Ava/Ui/Windows/MainWindow.axaml.cs
Fixes a bug in the hide cursor feature.
The mouse cursor isn't restored  when it's hidden by an option and moves outside the game, but not the window, or if the game exits to menu.
=> Avalonia - Ensure mouse cursor is only hidden when mouse is in renderer

Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml.cs
Should fix the crash that occurs when mapping controller input and a config hasn't been saved for that controller
=> Avalonia - Use loaded config when assigning controller input

Ryujinx.Ava/Common/ApplicationHelper.cs, Ryujinx.Ava/Modules/Updater/Updater.cs, Ryujinx.Ava/Ryujinx.Ava.csproj, Ryujinx.Ava/Ui/Applet/AvaHostUiHandler.cs, Ryujinx.Ava/Ui/Controls/ContentDialogHelper.cs, Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs, Ryujinx.Ava/Ui/ViewModels/MainWindowViewModel.cs, Ryujinx.Ava/Ui/ViewModels/UserProfileViewModel.cs, Ryujinx.Ava/Ui/Windows/CheatWindow.axaml, Ryujinx.Ava/Ui/Windows/DlcManagerWindow.axaml.cs, Ryujinx.Ava/Ui/Windows/MainWindow.axaml.cs, Ryujinx.Ava/Ui/Windows/TitleUpdateWindow.axaml.cs, Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj, Ryujinx/Ryujinx.csproj
Includes;
1.Fix crash with the updater on launch.
2.Reduce size of cheat window
3.Enable Tiered Compilation
4.Remove warnings from the avalonia project
=> Avalonia - Couple fixes and improvements

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/Optimizer.cs
In order to ensure that all variables only have a single assignment to keep optimizations simple, we keep the IR in [SSA form](https://en.wikipedia.org/wiki/Static_single-assignment_form). It is possible for a variable to be set to the same value in multiple blocks, and currently the shader translator will insert a copy on each one of them. Since it does not know that the values are actually the same, it will insert a Phi on blocks with multiple predecessors where the value is used. But the Phi is not actually needed in this case, if the value is actually the same on all of them, it doesn't matter from where it comes from.
This change extends the optimizer to also propagate the Phi source values if the value is always the same, regardless of the incoming block. This makes the generated …
=> Propagate Shader phi nodes with the same source value from all blocks

Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/ManagedSocket.cs
Some games and the Super Mario Odyssey Multiplayer Mod do this.
The SMO multiplayer mod also needs you to revert #3394 as it uses a blocking socket to receive (which hangs), and it doesn't seem to like being forced as non-blocking.
May fix some of the other games listed in #3236.
=> Handle the case where byte size option values are sent to BSD

Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs, Ryujinx.HLE/HOS/Kernel/Threading/KSynchronization.cs
Reduce cases where unnecessary copies of data are made in DMA handler, and also add a fast path for pure linear transfers where we can bypass the stride offset calculator on each element and thus use a faster copy method. Should reduce load times slightly and give better performance / less GC stutter during FMVs
=> Reduce some unnecessary allocations in DMA handler

Ryujinx.Graphics.Gpu/Image/TextureCache.cs
This PR adds another “safe mode” toggle for scaling that disables it for 2d textures that might be used as 3D. These textures essentially have a line of “slices” stacked in the x direction, rather than using a real 3d texture, as it is easier to render into. Games that dynamically update a 3D look-up-table to do tone mapping might do this. If that texture were scaled, the slices would blend into each other, causing black to appear as red, and bright red to darken too.
Some notes about the rules:
- It is assumed that the slices are stacked in the x-direction.
- It is assumed that the “slice” count is the same as the height, so the width is the height squared.
- Due to other rules, minimum affected texture size is 64x8
Hopefully this should fix issue #3456 , but all those games are on …
=> Avoid scaling 2d textures that could be used as “3d“

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitHelper.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgramContext.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/GlobalToStorage.cs, Ryujinx.Graphics.Shader/Translation/Rewriter.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
Currently it sets all the constant buffer used on the shader as "used". However some later passes may make them unused (for example, texture handles are read from constant buffer 2, but bindless elimination might be able to find that out and remove the constant buffer access and replace it with a non-bindless texture access). With this change, constant buffer use is set much later, after all optimizations and eliminations. This prevents the emulator from creating and sending data for buffers that are not actually used by the shader. This can have a very minor performance benefit, I would expect Vulkan to benefit more from this since we usually need to end the current render pass to perform inline buffer updates.
=> Avoid adding shader buffer descriptors for constant buffers that are not used

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Decoders/Block.cs, Ryujinx.Graphics.Shader/Decoders/Decoder.cs, Ryujinx.Graphics.Shader/Translation/Rewriter.cs
Because the decoder did not consider branch instructions that uses the CC register as conditional, it would skip blocks right after the branch instruction and only visit the branch target address. This causes some code to be missing from the shader.
Fixes "green lights" on JUMP FORCE Deluxe.
Before:
After:
Closes #2760.
Note that the shader is still not entirely correct on this game. It has a bindless texture instruction using a handle that is the output from a shuffle instruction. The bindless elimination pass can't handle this. This is likely some compiler generated pattern that we will need to recognize and transform into the proper texture operation.
This also fixes a minor issue introduced by #3194, bindless textures were considered to have non-normalized coordinates, which caused it …
=> Fix decoding of block after shader BRA.CC instructions without predicate

Ryujinx.Ava/Assets/Locales/en_US.json, Ryujinx/Ui/Windows/SettingsWindow.glade
This PR aims to standardize title case practices in the GTK settings window, as well as adjust the Hacks hint/description in both GTK and Avalonia to appear more consistently with the rest of the hints in their respective UIs.
GTK Before:
GTK After:
Avalonia Before:
Avalonia After:
=> Minor GTK & Avalonia UI verbiage/case fixes

Ryujinx.Graphics.Nvdec.FFmpeg/Native/FFmpegApi.cs
Fix a possible crash related to older version of ffmpeg being loaded
instead of the one shipped with the emulator.
=> fix: Ensure to load latest version of ffmpeg libraries first

Ryujinx.Ava/Ui/Windows/MainWindow.axaml
Makes menuitem checkboxes behave in the same way as the settings menu checkboxes in that they are embedded textblocks within checkbox parents versus the current implementation where the menuitem is given the text and a checkbox is embedded inside.
Given them a static width of 250 as this is the current size of the drop-down so that anywhere clicked along the row (even outside the text itself) is clickable.
=> Avalonia - Make menuitems toggleable on textclick

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitFlowControl.cs
This adds support for shader conditional exit, using the CC (Condition Code) register.
Fixes bloom in Tokyo Mirage Session (closes #3261).
Before:
After:
Note that the CC register is written by previous instructions. Since it is not implemented in *all* shader instructions yet, there is a chance that this cause different, incorrect behavior if an EXIT.CC instruction that uses CC written by an instruction were the emulator does not support CC condition write yet. Of course, before that change, it would be also incorrect since EXIT.CC was not supported at all, but it's something to keep in mind since it can cause still incorrect but different behavior. This game uses ISET RZ.CC followed by EXIT.CC, so it is correct with this change.
=> Add support for conditional (with CC) shader Exit instructions

Ryujinx/Ui/MainWindow.glade, Ryujinx/Ui/Windows/SettingsWindow.glade
This PR aims to standardize & improve tooltips in GTK by copying them from the forthcoming Avalonia UI.
All applicable tooltips in the Settings window were standardized.
In the main Ryujinx window, the following tooltips were standardized:
File > Load Application from File
File > Load Unpacked Game
=> Backport Avalonia menu/settings tooltips to GTK where possible

Ryujinx.Graphics.Gpu/GpuChannel.cs, Ryujinx.Graphics.Gpu/Image/PoolCache.cs, Ryujinx.Graphics.Gpu/Image/SamplerPool.cs, Ryujinx.Graphics.Gpu/Image/SamplerPoolCache.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.Gpu/Image/TexturePoolCache.cs
Currently, the texture pool cache has a hard limit of 4 pools. If a game is actively using more than that, then the least recently used one is removed. This is not good for performance as we will need to re-create the pool (and possibly the textures) again later. In addition to that, there is no sampler pool cache, so the emulator needs to re-create the pool and all samplers every time the sampler pool changes (which may or may not happen frequently, most games only uses one pool, so there's no problem there).
To address those issues, this change takes a new factor into account before deleting pools. It only deletes pools that have not been used for some time. In order to avoid introducing non-deterministic behavior, it does not actually use time, rather it uses a "timestamp" that is …
=> Add a sampler pool cache and improve texture pool cache

Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs
`FindTexture` tries to find an existing texture that matches the copy parameters, if found we try to write the data into the texture directly which is more efficient. However, `FindTexture` was also matching textures that have a height higher than the copy height. This causes problems because linear strided -> linear conversion expects data to be at least as large as the texture itself, and in this case it won't be causing an exception.
The fix here is making `FindTexture` only match linear textures with *exactly* the copy height. In addition to that, I removed the `RegionY` parameter because it is not used for linear copies, only block linear ones (that's an incorrect assumption that was made in the past and corrected, but I missed that code). Since after this only two fields from …
=> Fix DMA linear texture copy fast path

Ryujinx.Ava/Assets/Locales/en_US.json, Ryujinx.Ava/Ui/Controls/UserEditor.axaml, Ryujinx.Ava/Ui/Controls/UserEditor.axaml.cs, Ryujinx.Ava/Ui/Controls/UserSelector.axaml, Ryujinx.Ava/Ui/Controls/UserSelector.axaml.cs, Ryujinx.Ava/Ui/ViewModels/UserProfileViewModel.cs
This PR cleanup the UserEditor code a bit, 2 texts are added for "Name" and "User Id", because when you create a new profile, the textbox is empty without any hints. `axaml` files are autoformated too.
=> Avalonia: Cleanup UserEditor a bit

Ryujinx.Ava/Ryujinx.Ava.csproj, Ryujinx/Ryujinx.csproj
Update SPB to 0.0.4-build24 which fix the issue by checking libX11-xcb presence.
Fix https://github.com/flathub/org.ryujinx.Ryujinx/issues/4.
=> vk: Workaround XCB not availaible on FlatHub build

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/CodeGenContext.cs
Changes undefined values on spir-v shaders (caused by phi nodes) to be initialized instead of truly undefined.
Fixes an issue with NVIDIA gpus seemingly not liking when a variable is _potentially_ undefined. Not sure about the details at the moment.
Fixes:
- Tilt shift blur effect in Link's Awakening (bottom of the screen)
- Potentially block flickering on newer NVIDIA gpus in Splatoon 2? Needs testing.
=> SPIR-V: Initialize undefined variables with 0

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs
#2518 introduced a regression on GPUs that supports geometry shader passthrough. The fallback was being used even if the feature is supported, that is invalid because you can't assign to passthrough inputs and causes compilation error on OpenGL. Might be causing issues on Vulkan too, but likely not as bad as OpenGL.
Fixes regression on Marvel Ultimate Alliance 3 on Maxwell and newer NVIDIA GPUs.
=> Fix geometry shader passthrough fallback being used when feature is supported

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs
#3399 introduced some regressions on resolution scaling that #3403 attempted to fix, however even with this fix some issues remained. I attempted to fix some of the remaining issues on #2518 because it was reported that resolution scaling was broken on Atelier Ryza and other games from the series. However, this introduced yet another issue on Xenoblade Chronicles Definitive Edition.
The problem seems to be caused by the interaction between textures and images. The scales for both is stored on  the same buffer and same array, yet on the texture bindings manager their state is separate. Right now, the only things that forces an update is the scale index, usage flags or the texture itself changing. One simple scenario where this could break is a game using a image that is scaled on a single …
=> Fix resolution scale values not being updated

Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
This PR stub ResolverSetOptionRequest (checked by RE), but the options parsing is still missing since we don't support it in our current code.
(Close #3479)
=> Sfdnsres: Stub ResolverSetOptionRequest

Ryujinx.Graphics.Gpu/Shader/DiskCache/ParallelDiskCacheLoader.cs
This was broken by the Vulkan changes - OpenGL was building host caches at boot on one thread, which is very notably slower than when it is multithreaded.
This was caused by trying to get the program binary immediately after compilation started, which blocks. Now it does it after compilation has completed.
=> Fix Multithreaded Compilation of Shader Cache on OpenGL

Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.GAL/Multithreading/Commands/ClearRenderTargetColorCommand.cs, Ryujinx.Graphics.GAL/Multithreading/Commands/ClearRenderTargetDepthStencilCommand.cs, Ryujinx.Graphics.GAL/Multithreading/ThreadedPipeline.cs, Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs, Ryujinx.Graphics.Gpu/Engine/MME/MacroHLE.cs, Ryujinx.Graphics.Gpu/Engine/MME/MacroHLEFunctionName.cs, Ryujinx.Graphics.Gpu/Engine/MME/MacroHLETable.cs, Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClass.cs, Ryujinx.Graphics.OpenGL/Framebuffer.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.Vulkan/FramebufferParams.cs, Ryujinx.Graphics.Vulkan/HelperShader.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/PipelineFull.cs
This adds a HLE macro for render target clears (color and depth-stencil). The main advantage here is clearing textures with more than one layer (array or 3D). Before it would clear one layer at a time, with this change it can clear all of them at once, which might result in a minor performance improvement on games that render to array or 3D textures (most games won't).
Testing is welcome to ensure there's no regressions.
=> Implement HLE macros for render target clears

ARMeilleure/Decoders/OpCode32Mrs.cs, ARMeilleure/Decoders/OpCodeTable.cs, ARMeilleure/Instructions/InstEmitSimdHash32.cs, ARMeilleure/Instructions/InstEmitSystem32.cs, Ryujinx.Tests/Cpu/CpuTestSimd32.cs, Ryujinx.Tests/Cpu/CpuTestSimdReg32.cs
Ported those instructions from the Arm64 implementation, those are required by Mario Kart 8 Deluxe with update 2.1.0.
I added tests for SHA256, but unfortunately Unicorn does not support those instructions on Arm32, so I had to run the Arm64 tests, and copy the inputs and outputs and use those to validate the Arm32 test results. It would be better if Unicorn supported the instructions.
Fixes #3546.
=> Implement Arm32 Sha256 and MRS Rd, CPSR instructions

Ryujinx.Graphics.OpenGL/Framebuffer.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs
There was a regression (likely from #3400) causing New Super Mario Bros U Deluxe (or any game that tries to clear unbound color targets) to crash with NullReferenceException. This change fixes the issue by making sure that the framebuffer exists and that we don't try to get the layer count from inexistent textures.
=> OpenGL: Fix clear of unbound color targets

Ryujinx.Graphics.GAL/Format.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Engine/Types/ColorFormat.cs, Ryujinx.Graphics.OpenGL/FormatTable.cs, Ryujinx.Graphics.Vulkan/FormatTable.cs
Since RGBX formats have no alpha component, any blend operation that uses "DstAlpha" or "1 - DstAlpha" factors should use 1 and 0 respectively. However, since those formats are implemented using RGBA formats on the backend, this is not the case right now.
To fix this issue, I made it force a blend factor that would make it behave as if alpha was always 1.
This fixes the broken blending on LA MULANA.
Before:
After:
Additionally, I have removed all RGBX format from the GAL Format enum (since they were unused, with the exception of one, `B5G5R5X1Unorm`, but that was implemented using the same format as `B5G5R5A1Unorm` on Vulkan, so I just removed it too and made it use `B5G5R5A1Unorm` directly instead).
Testing is welcome. The likelihood of another game hitting this issue is very low though.
=> Fix blend with RGBX color formats

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs
This was an oversight during Vulkan rebase. Since #3487 added a sampler pool cache, it should use the sampler pool passed as argument rather than the one on `_samplerPool` field.
Thanks to Leischii for finding this issue.
Closes #3561
=> Fix texture bindings using wrong sampler pool in some cases

ARMeilleure/CodeGen/X86/AssemblerTable.cs, ARMeilleure/CodeGen/X86/PreAllocator.cs
Don't assume all vector instructions have a vex encoding.
Not checking this causes invalid allocations on vector instructions that don't have a vex prefixed variant.
=> PreAllocator: Check if instruction supports a Vex prefix in IsVexSameOperandDestSrc1

Ryujinx.HLE/HOS/Applets/Controller/ControllerApplet.cs
This strictly bandaid fix (as in it'll work until HID is properly reversed) stops ControllerApplet spam seen in Splatoon 2, Xenoblade Chronicles 3 and other single-player games which don't play well with multiple inputs configured/enabled. Instead the usual "Controller Applet" message dialog pops up requesting "exactly 1 player". 
The spam eventually caused crashes like `InvalidOperationException: Out of handles` or `InvalidMemoryAccess` in Splatoon 2 or very weird behavior such as bad/no audio, erratic character movement and eventual crashes(?) in Xenoblade 3. 
This oversight was originally fixed in the now abandoned #1523. Relevant excerpt-
> Also, I noticed there was some talk about a crash in Splatoon 2 related to multiple configured controllers while playing with the new local …
=> ControllerApplet: Override player counts when SingleMode is set

Ryujinx.Common/SystemInfo/MacOSSystemInfo.cs, Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs, Ryujinx.Graphics.Shader/TextureFormat.cs, Ryujinx.Graphics.Vulkan/Shader.cs, Ryujinx.Graphics.Vulkan/TextureBuffer.cs, Ryujinx.HLE/FileSystem/ContentManager.cs
There were a handful of cases of either duplicate or unnecessary semicolons. Those have been removed.
=> Removed extra semicolons.

Ryujinx.Graphics.Shader/CodeGen/Spirv/CodeGenContext.cs, Ryujinx.sln.DotSettings, Spv.Generator/Instruction.cs, Spv.Generator/InstructionOperands.cs, Spv.Generator/LiteralInteger.cs, Spv.Generator/LiteralString.cs
When running the Mii Editor, I was getting the following error:
```
00:00:03.926 |E| .NET ThreadPool Worker Gpu DebugReport: SPIR-V offset 10180: SPIR-V parsing FAILED:
Unsupported SpvOpConstant bit size: 1
10180 bytes into the SPIR-V binary
00:00:03.926 |E| .NET ThreadPool Worker Gpu : Background Compilation failed: Unexpected API error "ErrorUnknown".
```
This prevented me from seeing the colored squares when picking my favorite color.
With this change, the issue is fixed:
The issue was that we were making invalid constants. The type was "bool" which is one bit, but we assigned it an int32. Instead, I changed it to just a constant false. We were doing something similar with floating points (assigning int32 to a float32).
~This _MAY_ also have been the cause of the crash for #3566, and …
=> Fix SpirV parse failure

Ryujinx/Input/GTK3/GTK3MappingHelper.cs
Skipped over the last "Count" key explicitly, instead of relying on an exception.
Previously, the code included all values, and just blindly swallowed exceptions.
Now, we just skip the last (Count) key.
=> Skipped over the last "Count" key explicitly

Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClassState.cs, Ryujinx.Graphics.Gpu/GpuContext.cs, Ryujinx.Graphics.Gpu/Shader/DiskCache/ParallelDiskCacheLoader.cs, Ryujinx.Graphics.Shader/AttributeType.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/Translation/AttributeInfo.cs, Ryujinx.Graphics.Vulkan/FormatCapabilities.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/PipelineConverter.cs, Ryujinx.Graphics.Vulkan/TextureView.cs, Ryujinx.Graphics.Vulkan/VulkanConfiguration.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
This is an alternative to #3529. It solves the same problem, but using a different approach. Rather than using a format that has the same size but different type, this uses a format that has the same type but different size. The fact that it has the same type means that no conversion on the shader is required, but it brings other potential issues which is why I didn't want to use this approach before:
- The fact that this format is larger means that its size may be greater than offset + stride, which is invalid according to the spec.
- If the shader attempts to access the last component which should not exist, it will read garbage (the whatever is next in the vertex buffer) rather than 0.
- This can cause out of bounds access of the vertex buffer (by 2 bytes).
Puting this here for testing …
=> Use RGBA16 vertex format if RGB16 is not supported on Vulkan

Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs, Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml.cs, Ryujinx/Ui/Windows/SettingsWindow.cs
Previously no matter what setting was changed the GUI directory page would refresh and reload the entire game list. For larger libraries this can take an extremely long time and can make changing any settings quite painful for those users. 
This change adds a new variable that tracks if the game directories have been modified and will only force a refresh on save/apply if there have actually been valid changes made within the functions.
=> Check if game directories have been updated before refreshing GUI

Ryujinx.HLE/Loaders/Mods/IPSwitchPatcher.cs
As title say.
Thanks @shadowninja108 for the issue report 👍
=> misc: Fix missing null terminator for strings with pchtxt

Ryujinx.Graphics.GAL/ITexture.cs, Ryujinx.Graphics.GAL/Multithreading/CommandHelper.cs, Ryujinx.Graphics.GAL/Multithreading/CommandType.cs, Ryujinx.Graphics.GAL/Multithreading/Commands/Texture/TextureSetDataSliceRegionCommand.cs, Ryujinx.Graphics.GAL/Multithreading/Resources/ThreadedTexture.cs, Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs, Ryujinx.Graphics.Gpu/Engine/InlineToMemory/InlineToMemoryClass.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.OpenGL/Image/TextureBuffer.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs, Ryujinx.Graphics.Vulkan/TextureBuffer.cs, Ryujinx.Graphics.Vulkan/TextureView.cs
This adds a fast path for Inline-to-memory texture data transfers, similar to what's done on DMA engine. This one has the difference that it can transfer to the sub-region of a texture. Normally, since OpenGL games transfer part of the texture using 2D engine and the remaining using Inline-to-memory, we do a GPU side blit, and then immediately after flush the texture to write the remaining data on CPU. This is not only very inefficient, but also a source of bugs. Due to the flush issue that I attempted to fix in #3481, it can actually break those textures.
This approach simply submits the remaining data to GPU directly if the texture is already in the cache, which does not require flush and is much more efficient, and also fixes some texture corruption on OpenGL games.
For example, on …
=> Fast path for Inline-to-Memory texture data transfers

Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/ManagedSocket.cs
This PR adds a length check for `optionValue` before trying to read bytes that could possibly be out of range for this array.
Adding this check allows Minecraft to boot and play properly when "Enable guest internet access" is left unchecked.
Enabling that option will still cause the game to hang on boot and even disabled it will still hang when trying to stop emulation.
Although I have no idea why that happens, my blind guess would be that this is related to blocking sockets somehow?
Related issue: #3236
---
Also I want to add that I'm a bit confused about why these changes fix this issue.
When logging the values I noticed that nothing should have fulfilled [this if-condition](https://github.com/Ryujinx/Ryujinx/blob/6922862db8677fb8067a3e35d2433b1f12f8329c/Ryujinx.HLE/HOS/Services/Sockets/ …
=> Bsd: Fix ArgumentOutOfRangeException in SetSocketOption

Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfo4.cs
The port should be in network endianess when replying.
=> sfdsnres: fix endianess issue for port serialisation

Ryujinx.HLE/HOS/Services/SurfaceFlinger/SurfaceFlinger.cs
The vsync signal was signalling out at the swap interval, rather than every 16.667ms. Most games don't care about this, but there are a select few that do read the signal. This PR changes it to signal at 60hz regardless, and now swap interval is handled by setting a delay to the next frame when a present happens.
Fixes cutscene issues in [Tokyo Mirage Sessions #FE](https://github.com/Ryujinx/Ryujinx/issues/2914). The events within the cutscene relied on the vsync timer being at 60hz, whereas the animations relied on the actual presentation rate being 30hz. Having both run at the same speed caused interesting issues, but mostly just the voice lines playing at increasingly long delays.
This might also fix some weird game speed issues in The Legend of Zelda: Link's Awakening, and Breath of …
=> Change vsync signal to happen at 60hz, regardless of swap interval

Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
This PR adds another check to prevent games from crashing with guest internet access enabled.
@EmulationFanatic sent me a log of "Victor Vran Overkill Edition" crashing on boot because a `System.NullReferenceException` was thrown inside of `BsdSockAddr.FromIPEndPoint()`. 
Following the stack trace I found a missing check for `socket.RemoteEndPoint` to ensure it's not null.
With this change "Victor Vran Overkill Edition" boots with guest internet access enabled, although it will still deadlock shortly after, but that's a different issue.
Thanks to @EmulationFanatic for confirming my fix works so quickly!
=> Bsd: Fix NullReferenceException in BsdSockAddr.FromIPEndPoint()

Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/ManagedSocketPollManager.cs
We should report errors even when not requested.
This also ensure we only clear the bits that were requested on the output.
Finally, this should fix when input events is 0.
=> bsd: improve socket poll

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/ConstantFolding.cs
The `LoadConstant` IR operation is used for constant buffer loads with non-constant offset or constant buffer index. If both are constant, we can just use the regular "Cbuf" operand. Doing so allow bindless elimination to kick in on more cases (since it does not expect a `LoadConstant` operation, as those are usually used when the offset is not constant).
Improves rendering on Ys VIII: Lacrimosa of DANA:
Before:
After:
=> Transform shader LDC into constant buffer access if offset is constant

Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs, Ryujinx.Audio/Renderer/Server/AudioRendererManager.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManager.cs, Ryujinx.HLE/HOS/Services/Audio/AudioRendererManagerServer.cs
Right now we use the memory supplied by the guest when possible (when it is contiguous etc, which should be always the case with host memory manager modes) to store audio renderer state. While this is correct, there are some cases where the game unmaps the memory before the audio renderer is fully disposed. This can cause the audio renderer to try accessing the memory and cause an access violation because it was already unmapped.
This change fixes it by allocating our own memory to be used to store audio renderer state. Fixes an access violation crash on Urban Trial Tricky that started happening after #3267 (since before that change, access violation would cause the thread to just retry forever, which was probably masking the error).
Personally I'm not a fan of this change and I'm open to …
=> Allocate work buffer for audio renderer instead of using guest supplied memory

Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessorBase.cs, Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/Translation/AttributeInfo.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
This change remove SPIR-V `ViewportIndex` outputs if the GPU does not support it, in an attempt to support older GPUs. Nothing should change for OpenGL as it does not currently output `gl_ViewportIndex` in GLSL.
Testing is welcome, it should not affect newer GPUs (for NVIDIA, it should not affect Maxwell 2nd gen and newer).
=> Do not output ViewportIndex on SPIR-V if GPU does not support it

Ryujinx.Graphics.Gpu/Engine/Threed/SemaphoreUpdater.cs
Adds a scale factor for samples passed counter report based on the render target scale at the time. This ensures that when a game reads this counter, it appears similar to the result at 1x.
This doesn't cover cases where the the render target scale changes during the queried draws, though that might be better to handle along with other scope related issues in a future rework of counters. Games generally don't count for occlusion queries over render target changes anyways.
Fixes an issue in Splatoon 2 and the splatfest demo where the special charge would scale too quickly at high res, points at the end of the game would be broken (but still provide a correct winner), and playing at a low res would make it impossible to swim in ink.
Before (0.25x):
After (0.25x):
Not that I'd recommend …
=> Scale SamplesPassed counter by RT scale on report

Ryujinx.Graphics.Vulkan/FormatCapabilities.cs, Ryujinx.Graphics.Vulkan/FormatTable.cs, Ryujinx.Graphics.Vulkan/TextureView.cs
The component order was wrong.
Since the correct format was introduced on a extension and not all GPUs supports it, it will continue using the RGBA4 format with a different swizzle. The new swizzle also works correctly on the games below, but will not work correctly if the texture is rendered from GPU. If the GPU does support the ABGR4 format, then all cases should work correctly.
Fixes text on a few games.
Ni no Kuni.
Before:
After:
Ys VIII: Lacrimosa of Dana.
Before:
After:
Vroom in the night sky.
Before:
After:
Might also fix #3545 but I don't have the game to test.
OpenGL is not affected.
=> Fix R4G4B4A4 format on Vulkan

ARMeilleure/Decoders/OpCode32SimdMemPair.cs, ARMeilleure/Decoders/OpCodeTable.cs, ARMeilleure/Instructions/InstEmitSimdMemory32.cs, ARMeilleure/Translation/PTC/Ptc.cs, Ryujinx.Tests/Cpu/CpuTestSimdMemory32.cs
Due to what appears to be an oversight, not all "modes" were being tested on the VLDn/VSTn (pair) tests. Only VLD1 and VST1 was being tested. Fixing that revealed several failures caused by an incorrect register increment value, which caused some of those instructions to get or put the value on the wrong register.
This change fixes the above issues, and additionally updates the `OpCodeTable` to account for several "Undefined" encoding, which were considered valid before.
Fixes black screen on No More Heroes 2.
Before:
After:
Fixes several missing effects on Pikmin 3 Deluxe.
Before (pay attention to the antenna above the main character head):
After:
Fixes the main character falling below the ground on Sphinx the Cursed Mummy.
Before: …
=> Fix increment on Arm32 NEON VLDn/VSTn instructions with regs > 1

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/Operation.cs, Ryujinx.Graphics.Shader/IntermediateRepresentation/TextureOperation.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs
Because 1D and Buffer textures uses the same type on most texture instructions on the shader, it must get the actual texture type from GPU state. However, it was not doing that for bindless textures and assuming a buffer type, even if bindless elimination was successful. This change allows it to fix the type if bindless elimination is successful.
Fixes black screen on Prinny 2.
Master:
This PR:
This PR + #3695:
=> Fix bindless 1D textures having a buffer type on the shader

ARMeilleure/Decoders/OpCode32Simd.cs, ARMeilleure/Decoders/OpCode32SimdBase.cs, ARMeilleure/Decoders/OpCode32SimdBinary.cs, ARMeilleure/Decoders/OpCode32SimdCmpZ.cs, ARMeilleure/Decoders/OpCode32SimdDupElem.cs, ARMeilleure/Decoders/OpCode32SimdExt.cs, ARMeilleure/Decoders/OpCode32SimdImm.cs, ARMeilleure/Decoders/OpCode32SimdLong.cs, ARMeilleure/Decoders/OpCode32SimdMemPair.cs, ARMeilleure/Decoders/OpCode32SimdMemSingle.cs, ARMeilleure/Decoders/OpCode32SimdMovn.cs, ARMeilleure/Decoders/OpCode32SimdReg.cs, ARMeilleure/Decoders/OpCode32SimdRegElem.cs, ARMeilleure/Decoders/OpCode32SimdRegElemLong.cs, ARMeilleure/Decoders/OpCode32SimdRegLong.cs, ARMeilleure/Decoders/OpCode32SimdRegWide.cs, ARMeilleure/Decoders/OpCode32SimdRev.cs, ARMeilleure/Decoders/OpCode32SimdShImm.cs, ARMeilleure/Decoders/OpCode32SimdShImmLong.cs, ARMeilleure/Decoders/OpCode32SimdShImmNarrow.cs, ARMeilleure/Decoders/OpCode32SimdSqrte.cs, ARMeilleure/Decoders/OpCode32SimdTbl.cs, ARMeilleure/Decoders/OpCodeTable.cs
Hopefully self explanatory; makes use of T32 encoding being very similar to the A32 encoding for these instructions.
Really there are only two transforms here:
```
11110100 -> 11111001
1111001x -> 111x1111
```
Instruction classes affected by bit 24->28 shift:
* `OpCode32SimdImm`
* `OpCode32SimdLong`
* `OpCode32SimdReg`
* `OpCode32SimdRegElem`
* `OpCode32SimdRegElemLong`
* `OpCode32SimdRegLong`
* `OpCode32SimdRegWide`
* `OpCode32SimdShImm`
* `OpCode32SimdShImmLong`
* `OpCode32SimdShImmNarrow`
Note that this is usually handled in a base class; because this is usually the common `U` bit.
=> T32: Implement Asimd instructions

Ryujinx.Graphics.Vulkan/AutoFlushCounter.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/PipelineFull.cs
NVIDIA's OpenGL driver has a built-in mechanism to automatically flush commands to GPU when a lot have been queued. It's also pretty inconsistent, but we'll ignore that for now.
Our Vulkan implementation only submits a command buffer (flush equivalent) when it needs to. This is typically when another command buffer needs to be sequenced after it, presenting a frame, or an edge case where we flush around GPU queries to get results sooner.
This difference in flush behaviour causes a notable difference between Vulkan and OpenGL when we have to wait for commands. In the worst case, we will wait for a sync point that has just been created. In Vulkan, this sync point is created by flushing the command buffer, and storing a waitable fence that signals its completion. Our command buffer contains …
=> Periodically Flush Commands for Vulkan

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Shader/TextureHandle.cs
Currently, trying to read a handle that is used for bindless texture access from a constant buffer that is not bound will crash the emulator, because it tries to read from a unmapped address. This change has it assume that the handle value is 0 if the constant buffer is not bound. This is in-line with the sparse buffer behavior where out of bounds access read as 0 and does not write anywhere (although this is not really a sparse buffer, so not sure if it would apply here?).
This fixes a crash at launch on Sniper Elite 3 Ultimate Edition.
=> Allow bindless textures with handles from unbound constant buffer

Ryujinx.Ava/AppHost.cs, Ryujinx.Ava/Assets/Locales/en_US.json, Ryujinx.Ava/Assets/Styles/Styles.xaml, Ryujinx.Ava/Ui/Models/StatusUpdatedEventArgs.cs, Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs, Ryujinx.Ava/Ui/ViewModels/MainWindowViewModel.cs, Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml, Ryujinx.Ava/Ui/Windows/MainWindow.axaml, Ryujinx.Ava/Ui/Windows/MainWindow.axaml.cs, Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml
A few changes bundled together here as they all somewhat overlapped.
- Settings navbar is now not compact which, at least to me, seems far nicer to use and falls more in-line with new WinUI tools. Some borders have been added to make it less floaty too.
- All text now wraps with an overflow globally as this removes the need to do this for individual blocks when changing locales etc. Some are quite long and overall this prioritises the information always being displayed which is (again in my opinion) usually more important than forcing a static UI. (see navbar again)
- Right stick control border is now aligned properly, profile buttons now match refresh size (see above image).
- Controller ID has been removed in favour of a numbering system for "same" controller types. ID is a fairly …
=> Avalonia - Misc changes to UX

Ryujinx.Graphics.Vulkan/BufferHolder.cs, Ryujinx.Graphics.Vulkan/BufferManager.cs, Ryujinx.Graphics.Vulkan/BufferState.cs, Ryujinx.Graphics.Vulkan/CacheByRange.cs, Ryujinx.Graphics.Vulkan/EnumConversion.cs, Ryujinx.Graphics.Vulkan/HelperShader.cs, Ryujinx.Graphics.Vulkan/IndexBufferPattern.cs, Ryujinx.Graphics.Vulkan/IndexBufferState.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/PipelineConverter.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
This PR adds a mechanism for topology conversion, and uses it to convert quads to triangles before drawing. This is an alternative to our previous approach of queuing one draw per quad, and converts quads to Triangles instead of Triangle Fan.
This is done using an `IndexBufferPattern`, which is a simple way to define a repeating pattern of indices that can be used for topology conversion.
- Non-Indexed draws become indexed, using a shared index buffer that indexes the quad vertices so that they can be drawn as a triangle list. This buffer is stored in the IndexBufferPattern and expanded when needed.
- Indexed draws have their index buffers converted using the `IndexBufferPattern` into one that can be drawn as a triangle list. The rules are quite similar to the vertex buffer restride - the …
=> Convert Quads to Triangles in Vulkan

Ryujinx.HLE/HOS/Services/Account/Acc/AccountManager.cs, Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/ManagerServer.cs, Ryujinx.HLE/HOS/Services/Account/Acc/ApplicationServiceServer.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForApplication.cs
`StoreOpenContext` can be used to save the current list of open users, while `ListOpenContextStoredUsers` can be used to retrieve the list that was saved. This is useful in multi-program applications because the previous program can save the open users and then the next one can retrieve the list, however on master this was stubbed and would always return an empty list. This change makes it save the open profiles and return them on the next program.
Additionally stub `LoadOpenContext`. This started being called after I made `ListOpenContextStoredUsers` behave correctly.
Fixes crash when launching the games in Prinny Presents NIS Classics Volume 3: La Pucelle: Ragnarok / Rhapsody: A Musical Adventure. This is a collection with 2 games, and the crash was caused because it was trying to mount …
=> Fix ListOpenContextStoredUsers and stub LoadOpenContext

Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/PipelineConverter.cs
Any difference in the blend state when blend is disabled is meaningless, but Ryujinx would compare different disabled blends and compile them as separate pipelines. This change ensures that all pipelines where blend state is meaningless record it as zero, which avoids compiling a bunch of pipelines that are essentially identical.
The NVIDIA driver is pretty forgiving when it comes to silly pipeline misses like this, but other drivers don't offer the same level of kindness.
This should reduce stuttering on those drivers, and might improve overall performance very slightly due to less pipeline variants being in the hash table.
Just needs tests to ensure nothing totally broke. Performance difference will probably be impossible to measure on NVIDIA.
=> Vulkan: Zero blend state when disabled or write mask is 0

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/CodeGenContext.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/Instructions.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/SpirvGenerator.cs, Ryujinx.Graphics.Shader/Decoders/Decoder.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitAttribute.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, Ryujinx.Graphics.Shader/Translation/AttributeConsts.cs, Ryujinx.Graphics.Shader/Translation/AttributeInfo.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs, Ryujinx.Graphics.Shader/Translation/TranslatorContext.cs
This is mainly fixing a wrong assumption that I made about tessellation per-patch input/output buffer. I assumed that it was the same as the regular attribute buffer, but it isn't really. The only offsets from the per-patch buffer that have a special meaning are the ones < 0x18. Those map to the TessOuterLevel and TessInnerLevel built-ins. The remaining space can be used for anything, so it's just generic storage. So this PR is changing the code including the GLSL and SPIR-V backends to account for this.
In addition to that, it fixes some existing issues that affects SPIR-V/Vulkan:
- On SPIR-V, the `LoadOutputMask` flag was being ignored for `LoadAttribute`, which could cause it to read from a input rather than output variable.
- `gl_TessCoord` was being declared with a vec2 type on …
=> Fix incorrect tessellation inputs/outputs

Ryujinx.Common/Logging/LogClass.cs, Ryujinx.HLE/HOS/Services/Fatal/IService.cs, Ryujinx.HLE/HOS/Services/Fatal/Types/CpuContext32.cs, Ryujinx.HLE/HOS/Services/Fatal/Types/CpuContext64.cs, Ryujinx.HLE/HOS/Services/Fatal/Types/FatalPolicy.cs
This PR adds a basic implementation of fatal service, guest processes call it when there is something wrong. But since we can already have all informations by debugging it's not really useful.
In any case, that's avoid an unimplemented service exception. Structs/Enum are based on Atmosphère source code.
After logs the error report, I call SvcBreak. Feedbacks are welcome on this, since some guests calls it right after fatal service so I can remove it if needed.
(Closes #83 ~finally~)
=> fatal: Implement Service

Ryujinx.Graphics.Vulkan/Shader.cs
Implemented in a fun way for zero allocations (like C string literals). If this is too hacky, I'll replace it with a static `AllocHGlobal`, it should clean up properly without a free. 
Not sure why there's a condition for disposing but I kept it (afaik it's not even referenced outside of `ShaderCollection`). Let me know if it can be removed too. 
Also added missing `IDisposable` for clarity.
=> Avoid allocating unmanaged string per shader

Ryujinx.Graphics.Gpu/Window.cs, Ryujinx.HLE/HOS/Services/SurfaceFlinger/SurfaceFlinger.cs
Because surface flinger is disposed *after* the guest processes, it is possible it will try to enqueue a pending frame when the process has already exited. This will cause an exception to be thrown on tne `EnqueueFrameThreadSafe` method. This change makes it not throw and instead return a bool indicatiing if the frame was added to the queue or not. Surface Flinger can then deal with this and release the frame immediately.
This fixes an exception that could be thrown in some rare cases while ending emulation.
=> Allow Surface Flinger frame enqueue after process has exited

Ryujinx.Ava/Ui/Windows/AboutWindow.axaml
It seems at some point someone had done the work to make it so that the about window titlebar would show translated names but never removed the hardcoded english "Ryujinx - About" from the main .axaml.
Removing it seems to make it work as expected without issues.
=> Avalonia: Fix About window not displaying translated window titles

Ryujinx.Graphics.Vulkan/BufferManager.cs, Ryujinx.Graphics.Vulkan/TextureBuffer.cs
Because buffer handles can be re-used (when the old buffer is deleted and a new one created), it is possible that the same handle will actually refer to different buffers. So skipping the update if the handle is the same as the old one is not correct. To fix this, it also forces an update if new buffers were created since the last update. We're currently doing the same thing on OpenGL. This was not always a problem on Vulkan, as buffer handles were not reused, but at some point I added the `IdList` which allows reuse of handles.
This is a tentative fix for the weird issue were models constantly swap back to a very old animation frame on UE4 games. It's hard to confirm if this change actually fixes the issue due to its random nature though. Testing is welcome.
=> Vulkan: Fix buffer texture storage not being updated on buffer handle reuse

Ryujinx.Graphics.Vulkan/BufferUsageBitmap.cs
`BufferUsageBitmap` calculates a inclusive end address as `offset + size - 1`, however, if size is 0, it will result in a invalid offset that is less than the start. `BitMap.SetRange` is not prepared to handle this and will throw `IndexOutOfRangeException` if such ranges are passed. This started happening after #3715 because some games draws quads with a vertex count of 0. The fix here explicitly returns in `BufferUsageBitmap` when the size is 0 since there's nothing to be done in this case.
Fixes #3734.
=> Support use of buffer ranges with size 0

Ryujinx.HLE/HOS/Services/Bcat/ServiceCreator/IDeliveryCacheDirectoryService.cs, Ryujinx.HLE/HOS/Services/Bcat/ServiceCreator/IDeliveryCacheFileService.cs, Ryujinx.HLE/HOS/Services/Bcat/ServiceCreator/IDeliveryCacheStorageService.cs, Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IDirectory.cs, Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IFile.cs, Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IFileSystem.cs, Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IStorage.cs, Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs, Ryujinx.HLE/HOS/Services/Fs/ISaveDataInfoReader.cs, Ryujinx.HLE/HOS/Services/Ssl/SslService/ISslConnection.cs
Right now, the FS Read methods allocates an array without any regard for existing memory contents, reads the data from the file (or directory entries for `IDirectory.Read`) and then writes the buffer in memory. In most cases this does not cause issues because the application  usually doesn't care about the existing memory contents, but in some cases, applications might pass a buffer that is large and exposes other data to the service. In those cases, since it allocates a new array for the buffer and does not read existing memory contents, such values would be zeroed.
This was causing a crash on the title screen of SWORD ART ONLINE: Alicization Lycoris, because part of the buffer used on `IDirectory.Read` contained data for a `FiberType` struct, and since the method would zero out the …
=> Fix memory corruption in BCAT and FS Read methods when buffer is larger than needed

Ryujinx.Graphics.Vulkan/BufferHolder.cs, Ryujinx.Graphics.Vulkan/BufferManager.cs, Ryujinx.Graphics.Vulkan/CacheByRange.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/PipelineFull.cs, Ryujinx.Graphics.Vulkan/StagingBuffer.cs
- Cache now clears under more circumstances, the most important being the fast path write.
- Cache supports partial clear which should help when more buffers join.
- Fixed an issue with I8->I16 conversion where it wouldn't register the buffer for use on dispose.
Should hopefully fix issues with https://github.com/Ryujinx/Ryujinx-Games-List/issues/4010 and maybe others.
=> Vulkan: Fix some issues with CacheByRange

Ryujinx.Common/Memory/SpanOrArray.cs, Ryujinx.Graphics.GAL/ITexture.cs, Ryujinx.Graphics.GAL/Multithreading/Resources/ThreadedTexture.cs, Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Graphics.OpenGL/Image/TextureBuffer.cs, Ryujinx.Graphics.OpenGL/Image/TextureView.cs, Ryujinx.Graphics.Texture/LayoutConverter.cs, Ryujinx.Graphics.Vulkan/TextureBuffer.cs, Ryujinx.Graphics.Vulkan/TextureView.cs
Texture data is often converted before upload, meaning that an array was allocated to perform the conversion into. However, the backend SetData methods were being passed a Span of that data, and the Multithreaded layer does `ToArray()` on it so that it can be stored for later! This method can't extract the original array, so it creates a copy.
This PR changes the type passed for textures to a new ref struct called SpanOrArray, which is backed by either a ReadOnlySpan or an array. The benefit here is that we can have a ToArray method that doesn't copy if it is originally backed by an array.
This will also avoid a copy when running the ASTC decoder.
On NieR this was taking 38% of texture upload time, which it does a _lot_ of when you move between areas, so there should be a 1.6x performance …
=> GPU: Pass SpanOrArray for Texture SetData to avoid copy

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs
It was checking if the sampler was disposed, but not the texture. This could cause an attempt to update the data of a texture that was already disposed, which causes access violation on Vulkan.
This fixes the following crash on Crash Team Racing when using Vulkan:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at Ryujinx.Graphics.Vulkan.TextureView.CopyFromOrToBuffer(Silk.NET.Vulkan.CommandBuffer, Silk.NET.Vulkan.Buffer, Silk.NET.Vulkan.Image, Int32, Boolean, Int32, Int32, Int32, Int32, Boolean)
at Ryujinx.Graphics.Vulkan.TextureView.SetData(System.ReadOnlySpan`1<Byte>, Int32, Int32, Int32, Int32, Boolean, System.Nullable`1<Ryujinx.Graphics.GAL.Rectangle`1<Int32>>)
at …
```
=> Fix disposed textures being updated on TextureBindingsManager

Ryujinx.Graphics.Vulkan/SamplerHolder.cs
We were passing the custom border color struct, but the border color was not being set to "custom" which means that the driver would just ignore it.
Fixes shadows in Xenoblade Chronicles 2 cutscenes.
Before:
After:
Obviously, it will continue being broken on drivers that does not support the `VK_EXT_custom_border_color` extension.
=> Vulkan: Fix sampler custom border color

Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/ManagedSocket.cs
This small PR fixes the `InvalidOperationException` that would be thrown if `RecvFrom()` gets called without calling `Bind()` first.
I'm not really sure about the return value, but couldn't find a better fit. Since I don't have bsdsockets RE'd enough to look this up, I decided to leave it like that and hope someone knows the correct return value to use here.
---
This fixes the crash Overpass experienced when selecting the career mode.
Thanks to @EmulationFanatic for sending me the crash log and testing my patch.
=> bsd: Check if socket is bound before calling RecvFrom()

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Decoders/Decoder.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitFlowControl.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
This change improves the code generated for BRX instructions. This should help compilers produce slightly better code for those shaders, and make the output a bit easier to read aswell.
What this change does it basically chaining the blocks, where at the start, each block checks if the BRX target address matches the block address, and if not, it jumps to the next block which will do the same check, until it reaches the last possible BRX target block. Before, it would generate all the jumps sequentially at the point of the BRX instruction. The new approach is only used if all targets of the BRX instruction only have a single predecessor (which should be the block where the BRX is located), because otherwise the change wouldn't be valid. Failing to use the new approach, it will still use …
=> Improve shader BRX instruction code generation

Ryujinx.Input/HLE/NpadManager.cs
`ReloadConfiguration` and `RefreshInputConfigForHLE` pass the unfiltered InputConfig down the chain even when the mapped host controller is invalid (missing, etc..). Bug probably introduced with #2194 and #2269. 
Admittedly I don't understand Miria much, so I've opted for a shallow fix. Let me know if there's a better way or I missed something.
=> Fix phantom configured controllers

Ryujinx.Graphics.Vulkan/IndexBufferPattern.cs
Luigi's Mansion 3 performs a few non-index quads draws with 6 vertices for the mini map. It's meant to ignore the last two, but the index pattern's primitive count calculation was rounding up and drawing two quads instead of one.
https://user-images.githubusercontent.com/6294155/196014080-7f74a3be-265a-4f1e-a2e7-45ea30ee72f9.mp4
No idea why the game does this but this should fix random triangles in the map.
This is a recent regression from #3715. Feel free to make sure other stuff hasn't broken.
=> Fix primitive count calculation for topology conversion

Ryujinx.Graphics.Vulkan/BufferHolder.cs, Ryujinx.Graphics.Vulkan/IndexBufferState.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/VertexBufferState.cs
- The arguments for the 0th dummy vertex buffer were incorrect - it was given an offset of 16 rather than a size of 16. This was causing a lot of validation errors and out of bounds access.
- The wrong size was used when doing `autoBuffer.Get` on a converted vertex buffer.
- The possibility of a vertex buffer being disposed and then rebound can rebindings to find a different buffer where the current range is out of bounds. Avoid binding when out of range to prevent validation errors.
- The above also affects generation of converted buffers, which was a bit more fatal. Conversion functions now attempt to bound input offset/size.
Fixes some issues introduced in #3679 ,  #3715.
=> Fix various issues caused by Vertex/Index buffer conversions

Ryujinx.HLE/HOS/Tamper/Conditions/InputMask.cs
I noticed a report that cheats with conditional inputs don't work and scanning through just code, found this logic error. Please test if this fixes the problem as I pretty much never use cheats.
I would've preferred `(_input.Value ^ _mask) == 0` but original implementation uses this check-
https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/dmnt/source/cheat/impl/dmnt_cheat_vm.cpp#L976
=> TamperMachine: Fix input mask check

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs, Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
This implements `OpenDataStorageWithProgramIndex`. This implementation only supports accessing the storage if the program index is the same as the current program index. It doesn't look like the emulator has any infrastructure right now to access data from other NCAs from the game. The current content manager only "installs" firmware NCAs, so only those are accessible.
If an attempt is made to access the storage of another program, it will throw `NotImplementedException`.
This is enough for all games that I have that requires this functionality.
RollerCoaster Tycoon 3:
MLB The Show 22:
This one has quite a few issues. It runs very slow and crashes on Vulkan due the local size being above the limit of 1024 on my graphics card (although it seems that Pascal and older have a higher limit of …
=> Implement OpenDataStorageWithProgramIndex partially

Ryujinx.HLE/HOS/Kernel/Memory/KPageTableBase.cs
The current kernel implementation first tries to allocate at a random location on the address space, and if that fails, it tries a linear allocation. But due to an oversight, it was using the `address` variable as temporary storage for the random region it was checking inside the loop. Since it expects the `address` to be 0 if the random allocation failed, and it is used a temporary, it will never actually be 0 when allocation fails, which might cause it to incorrectly return an address of memory already in use.
This is fixed here by introducing a new, separate `aslrAddress` variable to store the temporary value for the random allocation attempts.
In practice, it's very unlikely for the random allocation to fail, so I believe not many games are affected by this issue. It is much more …
=> Fix kernel VA allocation when random allocation fails

Ryujinx.Common/Utilities/EmbeddedResources.cs, Ryujinx.HLE/HOS/Diagnostics/Demangler/Demangler.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/INfp.cs, Ryujinx.HLE/HOS/Tamper/InstructionHelper.cs, Ryujinx.HLE/Loaders/Mods/IPSwitchPatcher.cs, Ryujinx.HLE/Utilities/StringUtils.cs
Use the Span overloads of the Parse methods when possible to avoid string allocations and remove one unnecessarry array allocation
=> Avoid allocations in .Parse methods

Ryujinx.Ava/Modules/Updater/Updater.cs, Ryujinx/Modules/Updater/UpdateDialog.cs
Edit: The method is slightly changed now. But the outcome is still the same. (https://github.com/Ryujinx/Ryujinx/pull/3744#issuecomment-1271276850)
Original Post:
Ryujinx updates fail to load any arguments that have spaces in them.
Example, loading Ryujinx with command line arguments:
````
-r "D:/Custom Ryujinx Folder"
arg[0] = "-r"
arg[1] = "D:/Custom Ryujinx Folder"
````
Will restart after updates with:
````
-r D:/Custom Ryujinx Folder
arg[0] = "-r"
arg[1] = "D:/Custom"
arg[2] = "Ryujinx"
arg[3] = "Folder"
````
This now wraps all arguments in quotes, resulting in:
````
"-r" "D:/Custom Ryujinx Folder"
arg[0] = "-r"
arg[1] = "D:/Custom Ryujinx Folder"
````
The quotes around each of the args gets ignored when run (eg. "-r" still works fine).
edit:
I should note that this was tested in …
=> Fix: Arguments Break when Updating

Ryujinx.Graphics.Vulkan/TextureStorage.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
Due to the `using` statement being scoped to the `CreateTextureView` method, `TextureStorage` would be disposed as soon as the view was returned.
This was largely fine as the `TextureStorage` resources were being kept alive by the views holding their own references to them, but it also meant that dispose is only called as soon as the texture is created.
Aliased Storages are `TextureStorages` created with the same allocation as another `TextureStorage`, if they have to be aliased as another format. We keep track of a TextureStorage's `_aliasedStorages` as they are created, and dispose them when the `TextureStorage` is disposed...
...except it is disposed immediately, before any aliased storages are even created. The aliased storages added after this will never be disposed, and the …
=> Vulkan: Dispose TextureStorage when views hit 0 instead of immediately

Ryujinx.Ava/Assets/Locales/pl_PL.json, Ryujinx.Ava/Ui/Windows/MainWindow.axaml
Adding the new shortened "volume" string from the recent updates to Avalonia.
You need the period there otherwise it could be read as "Głoś" -> "Preach".
=>  Avalonia: Update Polish Translation

Ryujinx.Memory.Tests/Tests.cs, Ryujinx.Memory/MemoryManagementUnix.cs
This fixes an issue where UnmapView was failing on Linux because the flags combination being passed was invalid.
Needs to be tested on Linux, would be nice to know if it fixes #3372.
=> Fix mapping leaks caused by UnmapView not working on Linux

Ryujinx.HLE/HOS/Services/Nfc/NfcManager/INfc.cs, Ryujinx.HLE/HOS/Services/Nfc/NfcManager/Types/State.cs
Very basic state management but works with Hyrule Warriors Definitive Edition. Partially fixes #2122.
An evolution since that issue, on master, that game now asked for `Ryujinx.HLE.HOS.Services.Nfc.NfcManager.INfc: 2` to be implemented. By implementing this basic state management, the game accepts Amiibo scans through the emulator and does not crash anymore.
Should I remove the Stub prints from `Initialize` and `Finalize`? I feel like I didn't really implement anything nor did any kind of reverse engineering to figure out what is supposed to happen here, except blindly setting the state.
=> Manage state of NfcManager

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
Right now we do the Z value conversion for the -1 to 1 depth mode in the last vertex pipeline stage shader that is used. But because shaders using geometry shader passthrough don't (and can't) modify `gl_Position`, when those shaders are used, it wouldn't do the conversion at all. This fixes the issue by not considering geometry shader with passthrough as `LastInVertexPipeline`, so it will do the conversion in the previous stage instead, which can be vertex or tessellation control.
Fixes black screen in Game Builder Garage on Vulkan.
Before:
After:
=> Vulkan: Fix vertex position Z conversion with geometry shader passthrough

.github/dependabot.yml
This PR adds `dependabot.yml` to automatically create PRs when a new version of an action gets released.
It's currently configured to only run weekly and adds the label `infra` for each PR that it creates.
I doubt that it will create more than 3 PRs at a time, but we could still limit the amount of open PRs from it, if you want.
---
Originally this was part of #3774 and is now it's own PR.
=> CI: Add dependabot for github actions

.github/workflows/build.yml, .github/workflows/nightly_pr_comment.yml, .github/workflows/release.yml
As I spent a lot of time staring at the workflows, I noticed that most actions used within them aren't on their latest version.
Aside from that I also updated the workflows to replace the deprecated `set-output` workflow command with the new one and added `--no-build` to the test action, as Ryujinx was built right before.
=> CI: Update workflows

.github/dependabot.yml
@marysaka was looking to add this to dependabot too, so I quickly added it here.
For nuget packages dependabot will check for updates every day, add the label `infra` to PRs and prefix them with `nuget`.
I was looking at other PRs updating nuget packages before and wasn't sure which prefix to pick. The most common ones are `misc` and `infra`, so please tell me if you want the prefix changed.
(Sorry for creating so many small PRs, my next PR won't be something CI related and probably not as small.)
=> Add updates for nuget packages to dependabot

Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/PipelineConverter.cs, Ryujinx.Graphics.Vulkan/PipelineDynamicState.cs, Ryujinx.Graphics.Vulkan/PipelineState.cs
Prevents Mario Kart 8 Deluxe from creating an unbounded number of graphics pipelines when using blend constants (it seems to blend between colours depending on progress through certain course sections). Of course, it's possible for other games to do this.
Should generally use less memory and speed up drivers where compiling pipeline variants is slower.
=> Vulkan: Use dynamic state for blend constants

Ryujinx.Graphics.Vulkan/BufferHolder.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs
This is basically extracting a fix from #3748 since I don't know when that PR is going to be merged. Right now, we are missing the `IndirectCommandRead` bit on buffer barriers, which might potentially cause parameters to be fetched before write to the buffer is complete and cause the draw to use incorrect parameters. This was causing some DeviceLost crashes on Monster Hunter Rise with latest NVIDIA drivers, and maybe the older ones aswell.
=> Vulkan: Fix indirect buffer barrier

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/CodeGenContext.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/Declarations.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgramContext.cs
GLSL requires that tessellation control shaders are indexed with `gl_InvocationID` built-in input. You can't actually use anything else as index, so this is effectively useless. On SPIR-V, this was not being done. This was not causing any validation errors, and most compilers did not complain about it, except AMD on Windows, where it would cause the compiler to crash. So to fix this, I have changed it to index outputs using `gl_InvocationID` on tessellation control shaders, which matches the GLSL compiler, and fixes the AMD crash.
Fixes crash on the following games on AMD Vulkan (Windows):
- Bayonetta 3 (chapter 1, after the cutscene).
- Luigi's Mansion 3 (right before the title screen).
- And likely any other game using tessellation (see list below, I did not test all of them).
Testing …
=> SPIR-V: Fix tessellation control shader output types

Ryujinx.Graphics.Vulkan/VulkanInitialization.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
[VK_EXT_debug_report](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_debug_report.html) has been deprecated for quite some time now in favor of the much more featureful
[VK_EXT_debug_utils](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_debug_utils.html) extension.
This PR converts our debug-report-callback into the newer debug-messenger pattern.
`VK_EXT_debug_utils` adds some additional diagnostic tooling for marking debug-label scopes for queue-operations, command-buffers, and assigning name-labels to vulkan objects to aid in debugging(for a later PR).
=> Vulkan: Replace `VK_EXT_debug_report` usage with `VK_EXT_debug_utils`

.github/workflows/build.yml
Quick fix for the [issue](https://discordapp.com/channels/410208534861447168/410432399500115968/1035943546982768761) mentioned by mageven on discord.
Windows builds should now properly include the SourceRevisionId.
You can verify that this works in the following workflow run: https://github.com/TSRBerry/Ryujinx/actions/runs/3352123839/jobs/5554048680
=> CI: Fix windows builds missing SourceRevisionId

Ryujinx.Graphics.Nvdec.FFmpeg/FFmpegContext.cs, Ryujinx.Graphics.Nvdec.FFmpeg/Native/AVCodec.cs, Ryujinx.Graphics.Nvdec.FFmpeg/Native/AVCodec501.cs, Ryujinx.Graphics.Nvdec.FFmpeg/Native/AVCodecContext.cs, Ryujinx.Graphics.Nvdec.FFmpeg/Native/FFCodec.cs
For some reason FFmpeg 5.1.x reverted part of the changes made in 5.0.x on AVCodec.
This fix decoding issues with it.
Close #3645
=> fix: Support FFmpeg 5.1.x for decoding

Ryujinx.Graphics.Gpu/Engine/Compute/ComputeClass.cs
Since instanced draws does one call per instance, we currently use an approach were the draw is deferred until we get the total instance count. In some rare circumstances, it was possible for a compute dispatch to be done while the draw was still pending, but then later it would do the pending draw, but at this point the state is already wrong, and since a compute shader is bound for the compute dispatch, it would try to draw with a compute shader which is invalid. This was causing crashes on Vulkan on the game Nights of Azure 2: Bride of the New Moon.
This change is basically just making sure all pending draws are done before the compute dispatch operation.
With this change, the aforementioned game now works on Vulkan.
=> Ensure all pending draws are done before compute dispatch

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.OpenGL/Image/TextureBase.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, Ryujinx.Graphics.Vulkan/PipelineState.cs, Ryujinx.Graphics.Vulkan/PipelineUid.cs
This improves the management of pipeline state and bindings management on the Vulkan backend:
- #3793 started using dynamic state for blend constants, which reduces  the amount of pipelines that we need to create, however the state was still there, and was still being compared/hashed which is a bit wasteful. This PR removes the blend constant from the pipeline state since it is not used anymore. Should make pipeline state lookup a little bit faster.
- Changed the descriptor set updater to stop ignoring null textures and clean up the bindings, instead of keeping stale bindings. This is to avoid bugs where we keep potentially already freed resources bounds, and also the potential for "garbage" to be sampled on the shader. The new behaviour should be closer to the hardware behaviour, and …
=> Minor improvement to Vulkan pipeline state and bindings management

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/Declarations.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitAttribute.cs, Ryujinx.Graphics.Shader/Translation/AttributeConsts.cs, Ryujinx.Graphics.Shader/Translation/AttributeInfo.cs
`gl_VertexId`  and `gl_InstanceID` are only valid on OpenGL. On Vulkan, `gl_InstanceIndex` should be used instead. However, there's a difference between the two. `gl_InstanceIndex` includes the `gl_BaseInstance` while `gl_InstanceID` doesn't. So this code replaces `gl_InstanceID` with `gl_InstanceID - gl_BaseInstance`, and `gl_VertexID` with `gl_VertexIndex` (the two should be equivalent).
The old approach was already working fine on NVIDIA, but not Intel.
Fixes incorrect rendering on games using `gl_InstanceID` on the shader and instanced draw with non-zero base instance on Intel.
Before:
After:
Other games that are likely affected are Sniper Elite 3, Metro 2033 Redux, and others, but I didn't test those.
I don't know if the issue affects AMD.
=> Fix VertexId and InstanceId on Vulkan

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/CodeGenContext.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/GlslGenerator.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/CodeGenContext.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/SpirvGenerator.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgramInfo.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
Currently, shaders with transform feedback use individual, per-component outputs. That's because each component might potentially have a different, non-sequential offset, and in those cases we might need to specify different offsets per component. This works fine on NVIDIA, but causes an issue where some outputs are not written, or written at the wrong offset on Intel. To work around this issue, this change now attempts to use vector outputs in some cases. This is done when the offsets are sequential, and there's no fragment shader stage (because in this case, we don't need to worry about the VTG output not matching the fragment shader inputs).
Fixes grass on Xenoblade Chronicles Definitive Edition on Intel.
Before:
After:
This might improve things for AMD aswell, so it would be nice to …
=> Use vector transform feedback outputs if possible

Ryujinx/Ui/Windows/AboutWindow.Designer.cs
Avalonia's _About_ section and the main website already list the phonetically recommended pronunciation of Ryujinx to be REE-YOU-JINX. GTK still has the old and busted REE-YOU-JI-NX (whose pronunciation is anyone's guess).
This PR aligns GTK with reality.
Before:
After:
=> GTK: It's REE-YOU-JINX

Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/Translation/Translator.cs
Replace usage of OrderBy(x => x) with Order()
[Introduced in .NET 7](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.order?view=net-7.0#system-linq-enumerable-order-1(system-collections-generic-ienumerable((-0))))
A bit faster and less allocations.
=> Use new LINQ Order() methods

Ryujinx.Ava/Ryujinx.Ava.csproj, Ryujinx/Program.cs, Ryujinx/Ryujinx.csproj
For some reasons, my fresh installation of Fedora 36 (KDE) doesn't have a symlink for libX11.so.
This PR fixes this by trying to import the library with its major version or fallback to the normal way.
SPB was updated in consequence.
=> Fix Fedora support

Ryujinx/Ui/MainWindow.cs
Allows to start Ryujinx in wayland environment, ignoring code to retrieve monitor dimensions
relates #2714
=> Allow to start Ryujinx in wayland environment

Ryujinx.Cpu/IExecutionContext.cs
Thread ID Register, Floating-point Control Register, and Floating-point Status Register all had Register capitalized, so the Register in Processor State register should be capitalized.
=> Capitalization to be consistent

.github/workflows/build.yml, .github/workflows/release.yml
As title say.
Fix Avalonia build versions for PRs.
Also ensure that the --self-contained doesn't warn at build.
=> ci: Clean up Actions leftovers

Ryujinx.Graphics.Gpu/Constants.cs, Ryujinx.Graphics.Gpu/Engine/Compute/ComputeClass.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, Ryujinx.Graphics.Gpu/Shader/ComputeShaderCacheHashTable.cs, Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheGpuAccessor.cs, Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, Ryujinx.Graphics.Gpu/Shader/GpuChannelComputeState.cs, Ryujinx.Graphics.Gpu/Shader/GpuChannelGraphicsState.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Gpu/Shader/ShaderSpecializationList.cs, Ryujinx.Graphics.Gpu/Shader/ShaderSpecializationState.cs, Ryujinx.Graphics.Shader/Constants.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/GlobalToStorage.cs
The zeroth constant is typically used by official drivers as a kind of "driver support buffer". Command buffers/macros load draw parameters in this buffer for the shader to use with the Constant Buffer Update methods, such as base vertex, base instance, and shader storage buffer addresses. The last one is used to "emulate" storage buffers, as it simply adds the address of the storage buffer to the offset provided.
The problem here is that when storage buffer bindings are in use, the macro attempts to update this for every draw. Most of the time it is the same value, sometimes it is different. But in the majority of cases, we _shouldn't_ care, we already located where the global access wanted to go, so we don't even need to read it.
This PR identifies these cases and removes the base …
=> GPU: Eliminate CB0 accesses when storage buffer accesses are resolved

Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
This PR fixes #3856.
Currently I think it makes sense to just return the default values, since we are already doing that for the other commands. 
~~Note: This is currently just a guess based on `GetSaveDataSize`. I'll mark this PR as ready for review as soon as I am able to confirm this is correct.~~
=> am: Stub GetSaveDataSizeMax

Ryujinx.Graphics.Gpu/GpuChannel.cs, Ryujinx.Graphics.Gpu/Memory/BufferCache.cs
Since we're now using this for modified checks on the HLE indirect draw method, I'm worried that leaving these to forever gather cache entries isn't the best idea for performance in the long term, and it could keep old buffer objects alive for longer than they should be.
This PR adds the ability to prune invalid entries before checking these caches, and queues it whenever gpu memory is unmapped. It also aligns modified checks to the page size, as I figured it would be possible for a huge number of overlapping over a game's runtime. Ideally this should reduce time spent doing buffer modified lookups after a while of playing a game.
This prevents Super Mario Odyssey from having 10s of thousands of entries in the modified cache in Metro Kingdom, and them duplicating when entering and leaving …
=> Prune ForceDirty and CheckModified caches on unmap

Ryujinx.Graphics.Vulkan/BufferHolder.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/ShaderCollection.cs
The preload command buffer is used to avoid render pass splits and barriers when updating buffer data. However, when a render pass is not active (for example, at the start of a command buffer, or during compute invocations) buffer uploads can be performed at any time, so the optimization isn't as useful.
This PR makes it so that the preload command buffer is only used for buffer updates outside of a render pass. It's still used for textures as I don't want to shake things up right now regarding how the preload buffer is obtained before some other changes, and texture updates are a lot rarer anyways.
This also immediately ends the render pass when switching to a compute shader.
Improves performance slightly in Pokemon Scarlet/Violet (43 -> 48), as it was switching to compute, writing a …
=> Vulkan: Don't create preload command buffer outside a render pass

Ryujinx.Graphics.Gpu/Memory/BufferModifiedRangeList.cs
A quick fix to prevent reading the wrong value of Count when reregistering ranges for a new target buffer. Buffer flushes from another thread can modify the range list when the lock isn't active, which can change the count.
This prevents some crashes in Pokemon Scarlet/Violet and some other games. It's probably likely that buffer migration during flush is causing some other issues in this game, but this at least prevents the crashing.
=> Gpu: Fix thread safety of ReregisterRanges

Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs
This might fix an issue with AMD gpus on linux where the data could contain random garbage. On the switch, it always samples as 0.
Or so I think. Needs testing.
=> Vulkan: Clear dummy texture to (0,0,0,0) on creation

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Gpu/Shader/DiskCache/ShaderBinarySerializer.cs
This is a continuation of #3866, which added a workaround for `gl_Layer` on Vulkan for older GPUs, but it has one issue when loading the shader cache, because right now the shader cache assumes that there will be one SPIR-V shader for each guest shader stage, however this is not the case with the workaround since we need to insert a geometry shader  that didn't originally exist. This PR modifies the host shader save/load to take that into account. It now saves the shader stage type and stages count aswell, instead of assuming its the same as the guest code.
Fixes a crash when loading the shader cache on Vulkan on the affected GPUs on Pokémon Scarlet/Violet.
This is a general change on the shader cache so testing on any GPU is appreciated to ensure there's no regressions on Vulkan. OpenGL …
=> Fix shader cache on Vulkan when geometry shaders are inserted

Ryujinx.Graphics.Gpu/GpuChannel.cs
Event was not being unsubscribed which was causing NRE if any map or unmap operation was done after the GPU channel is destroyed since #3862. Only affects games that uses multiple GPU channels. Should fix #3871 but I did not test this particular game, so would be nice to get tests on this game.
=> Unsubscribe MemoryUnmappedHandler even when GPU channel is destroyed

Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs
`DrawTextures` is a bit weird because it behaves like a draw, but it's actually more like a blit. It does not use any shader, so we don't need to update the shader state for this operation. Updating shader state was causing problems because it could be in a invalid state, which would cause exceptions on the shader translator when processing the shader (as it would be working with a completely invalid shader).
This fixes a crash in A Hat in Time depending on where you are in the game. I'm not sure if the crash happens on OpenGL since it's possible that the translator would just generate a broken GLSL shader without throwing. But I can confirm the issue on Vulkan (`System.ArgumentException: Invalid shader stage "15".`), which is fixed by this PR.
=> Do not update shader state for DrawTextures

Ryujinx.HLE/FileSystem/VirtualFileSystem.cs, Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/LibHacHorizonManager.cs, Ryujinx.HLE/HOS/Services/Fs/IDeviceOperator.cs, Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs, Ryujinx.HLE/Ryujinx.HLE.csproj
- Remove some leftover debug code for `CompressedStorage`
- Add key sources for system version 15.0.0
- Update save data service functionality for changes in 14.0.0
- Implement the `CreateSaveDataFileSystemWithCreationInfo2` method in `IFileSystemProxy` introduced in 14.0.0
- Remove workaround that cleared the saves on the SD card when starting the emulator. Fixes #3800
- General system stability improvements to enhance the user's experience
=> Update to LibHac 0.17.0

Ryujinx.Ava/Common/Locale/LocaleManager.cs, Ryujinx.Ava/Ui/ViewModels/AmiiboWindowViewModel.cs
Since we move to .NET7, JsonSerializer now needs to have explicit options as arguments, which leads to some warnings in Avalonia project. This is fixed by using our `JsonHelper` class.
=> ava: Fix JsonSerializer warnings

Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoDevice.cs
Saves allocating/copying new arrays for them constantly - they can be quite small so it can be very wasteful. About 0.4% of GPU thread in SMO, but was 2.24% in Pokemon S/V when I checked. I guess this will typically happen more when indirect draw macros are used. I didn't see it at all on SMO's title screen, for example.
Avoiding allocations on prefetch and the special pushes will be a bit harder due to pooling+copying having a cost of its own, and it might not be as effective since it's not done on that critical GPU thread, but an OS one. I left it out of this PR, though not without trying some things and being disappointed.
Assumes that non-prefetch command buffers won't be randomly clobbered before they finish executing, though that's probably a safe bet.
=> GPU: Access non-prefetch command buffers directly

Ryujinx.Graphics.GAL/BufferAssignment.cs, Ryujinx.Graphics.GAL/IPipeline.cs, Ryujinx.Graphics.GAL/Multithreading/BufferMap.cs, Ryujinx.Graphics.GAL/Multithreading/Commands/SetStorageBuffersCommand.cs, Ryujinx.Graphics.GAL/Multithreading/Commands/SetUniformBuffersCommand.cs, Ryujinx.Graphics.GAL/Multithreading/ThreadedPipeline.cs, Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, Ryujinx.Graphics.Vulkan/HelperShader.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs
The GAL Multithreading layer is good at reducing the cost of calls that would take longer on the backend, but the downside is an extra cost for loading commands into the command queue, and resource references/spans into circular queues.
The `(int first, BufferRange[] ranges)` method call has very significant performance implications when the bindings are spread out, which they generally always are in Vulkan, as the method ends up being called a lot of times every buffer update. This change makes it so that these methods are only called a maximum of one time per draw.
Significantly improves GPU thread performance in SMO, Pokemon Scarlet/Violet, and any other games that tend to bind many constant buffers at once. Probably not as much in OpenGL.
This change is already in LDN 3.0.
=> GAL: Send all buffer assignments at once rather than individually

Ryujinx.Ava/Ui/Applet/AvaHostUiHandler.cs
When the error message is unknown (not found on the firmware), the emulator currently passes a generic message and null as the buttons array. Some code on the Avalonia UI doesn't expect that to be null so it throws a `NullReferenceException`. This PR adds a explicit null check to handle that case.
Before this change, it would show this dialog after the generic error dialog:
With this change, it only shows the generic error dialog as expected.
=> Fix NRE on Avalonia for error applets with unknown error message

Ryujinx.Ava/App.axaml.cs
Before this, Ryujinx would possibly report as "Avalonia Application".
=> Ryujinx.Ava: Add missing redefinition of app name

Ryujinx.Ava/AppHost.cs, Ryujinx.Ava/Ui/Controls/OpenGLEmbeddedWindow.cs, Ryujinx.Ava/Ui/Windows/MainWindow.axaml.cs, Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs, Ryujinx.Graphics.OpenGL/Queries/Counters.cs, Ryujinx.Graphics.OpenGL/Window.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs, Ryujinx.HLE/HOS/Horizon.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/RendererWidgetBase.cs, Ryujinx/Ui/VKRenderer.cs
This fixes a dispose issue under Horizon/GTK/Avalonia, we don't check if the ApplicationClient is null so it throw NRE. We don't check if the main loop is active and waiting an event which is set in the main loop... So that could lead to a freeze.
Avalonia code is running on a main thread and waiting for the popup result, popup are running on a UI thread for the main thread never get the result and freeze.
Everything works fine in GTK/Avalonia (Thanks to @TSRBerry and @emmauss for their help) now.
Fixes https://github.com/Ryujinx/Ryujinx/issues/3873
=> ui: Fixes disposing on GTK/Avalonia and Firmware Messages on Avalonia

Ryujinx.Common/Extensions/BinaryReaderExtensions.cs, Ryujinx.Cpu/MemoryHelper.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardCustomizeDic.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardDictSet.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardUserWord.cs, Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/FriendService/Types/UserPresence.cs, Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs, Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/NotificationService/Types/NotificationInfo.cs, Ryujinx.HLE/HOS/Services/Sdb/Pdm/QueryService/QueryPlayStatisticsManager.cs, Ryujinx.HLE/HOS/Services/Time/Clock/Types/ClockSnapshot.cs, Ryujinx.HLE/HOS/Services/Time/IStaticServiceForPsc.cs, Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZone.cs, Ryujinx.Input/Motion/CemuHook/Protocol/ControllerData.cs, Ryujinx.Input/Motion/CemuHook/Protocol/ControllerInfo.cs, Ryujinx.Input/Motion/CemuHook/Protocol/SharedResponse.cs
This changes most codepaths of the emulator to not rely on ``Marshal.PtrToStructure`` and ``Marshal.StructureToPtr``.
Some structures were changed to make them unmanaged as a result.
I kept ``ReadStruct`` in ``SoftwareKeyboardApplet`` as it would probably be more of a burden to manipulate data safely there (and the overhead is acceptable)
Heavy testing is advised but structure size matched so it should technically be fine.
=> Reduce usage of Marshal.PtrToStructure and Marshal.StructureToPtr

Ryujinx.Cpu/Jit/MemoryManager.cs, Ryujinx.Cpu/Jit/MemoryManagerHostMapped.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ConstantBufferUpdater.cs, Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs, Ryujinx.Memory.Tests/MockVirtualMemoryManager.cs, Ryujinx.Memory/AddressSpaceManager.cs, Ryujinx.Memory/IVirtualMemoryManager.cs
Benefits:
- Reduces number of buffer uploads greatly in certain games (4096 byte cost each time)
- Avoids splitting render pass on Vulkan (cost depends on GPU driver)
- Batches adjacent ConstantBufferUpdater (CBU) writes into one access, reduces number of memory manager calls.
Downsides:
- Check/triggers read tracking for upload regions (slightly slower)
- Can be slow in software memory if range is non-contigous (forces redundant update anyways)
- The redundancy check method says that it can return true if checking would be too slow, and that's what it does in this case. Allocating and filling an array with the non-contiguous regions would be a lot slower than just saying the write happened.
- Upload must be flushed by potential users (could be buggy if a case is missed)
This has a lot of …
=> GPU: Don't trigger uploads for redundant buffer updates

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Translation/Optimizations/GlobalToStorage.cs
This replacement is meant to be done with the original identified byteOffset, not the one assigned later on by the below conditionals (that already has the constant offset added, for instance).
This fixes videos being pixelated in Xenoblade 3, and other regressions that might have happened since #3847.
Also I accidentally made this branch on the main repo. 🥴
=> Fix CB0 alignment with addresses used for 8/16-bit LDG/STG

Ryujinx.Ava/Ui/Controls/EmbeddedWindow.cs, Ryujinx.Ava/Ui/Controls/VulkanEmbeddedWindow.cs
Small PR to fix the invisible window issue on Linux when using Avalonia and the Vulkan backend.
Thanks to @emmauss who basically already fixed this in a discord chat.
=> Avalonia: Fix invisible Vulkan window on Linux

Ryujinx.Ava/Ui/Controls/EmbeddedWindow.cs, Ryujinx.Ava/Ui/Controls/VulkanEmbeddedWindow.cs
Fixes a regression from #3901
Thanks to @piplup55 for notifying me about the issue!
(This time Avalonia works on Linux works for both OpenGL and Vulkan. We only need to fix invisible dialogs after that, before it's usable again!)
=> Avalonia: Fix OpenGL crashing on Linux

Ryujinx.HLE/HOS/Services/Ptm/Psm/IPsmSession.cs
there's a *very small* logic error in the Psm service [here](https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.HLE/HOS/Services/Ptm/Psm/IPsmSession.cs#L21-L38) : 
`stateChangeEventHandle` is never used to update `_stateChangeEventHandle`. This PR takes care of that
=> HLE: fix small issue in IPsmSession

.github/ISSUE_TEMPLATE/bug_report.md
It would appear that GitHub does not allow the "about" section of an issue template to exceed 200 characters.
Because of this, the template is missing from the issue type selector when opening a new issue, meaning that there is a bug that stops me from reporting bugs 😆
I have shortened the extra information (originally added in 51bb8707efbbb1af9ca959e68c8ab7d6bd26dc07) so that it fits under this limit, which should make the template usable again.
=> Unbreak bug_report.md

Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs, Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfo4.cs, Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfoSerialized.cs
We currently doesn't check the `AddressLength` of the `AddrInfoSerializedHeader` and this could lead to an oob since we still trying to parse addresses for the (unused) passed `hints` in `GetAddrInfoRequestImpl`.
I've cleaned up a bit the code too, and added a missing padding which could help to understand the size of `AddrInfo4`.
Fixes https://github.com/Ryujinx/Ryujinx/issues/3918
HB App Store seems to works (at least run, I haven't tried it more):
=> sfdnsres: Fix deserializer of AddrInfoSerialized when addresses are empty

Ryujinx.Graphics.OpenGL/EnumConversion.cs, Ryujinx.Graphics.Vulkan/EnumConversion.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs
Polygon topology wasn't really supported and would only work on OpenGL on drivers that haven't removed it. As an alternative, this PR makes all cases of polygon topology use triangle fan. The topology type and transform feedback type have not been changed, as I don't think geo shader/tfb should be used with polygons.
The OpenGL spec states:
> Only convex polygons are guaranteed to be drawn correctly by the GL.
For convex polygons, triangle fan is equivalent to polygon. I imagine this is probably how it works on device, as this get-out-of-jail-free card is too enticing to pass up.
This fixes the stat display in Pokemon S/V in Vulkan, or on OpenGL on drivers that don't support GL_POLYGON in compatibility mode.
=> GPU: Always draw polygon topology as triangle fan

Ryujinx.Ava/Ryujinx.Ava.csproj, Ryujinx.Ava/Ui/Controls/ContentDialogHelper.cs
Thanks to @amwx we are *finally* able to fix invisible dialogs on Linux! 
This PR updates FluentAvalonia to [1.4.5](https://github.com/amwx/FluentAvalonia/pull/248#issuecomment-1329844847) and adapts `ContentDialogHelper` to use the new function signature when using an overlay window.
As soon as this is merged, Avalonia will be completely usable on Linux again!
=> Avalonia: Update FluientAvalonia & Make dialogs work on Linux

Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.OpenGL/VertexArray.cs
Some games will have vertex attributes with a invalid buffer index (the vertex buffer doesn't exist). This is invalid and may cause crashes on both on OpenGL and Vulkan depending on the driver. The OpenGL backend was already validating this and disabling the attribute if the buffer index was invalid. However, Vulkan wasn't. This changes does the validation on the GPU project, and removes the validation from the OpenGL backend. So now both backends should be covered.
Fixes some crashes on specific games on Vulkan with some drivers. I don't think this issue affects NVIDIA.
=> Ensure that vertex attribute buffer index is valid on GPU

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/Instructions.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/SpirvGenerator.cs, Ryujinx.Graphics.Vulkan/VulkanInitialization.cs
This replaces the use of those two extensions with equivalent functionality that is supported on "base" SPIR-V and does not require any extension. This is more widely supported and required on MoltenVK as it does not support those extensions.
=> Remove shader dependency on SPV_KHR_shader_ballot and SPV_KHR_subgroup_vote extensions

Ryujinx.Graphics.GAL/IRenderer.cs, Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs, Ryujinx.Graphics.Gpu/GpuContext.cs, Ryujinx.Graphics.Gpu/Memory/Buffer.cs, Ryujinx.Graphics.Gpu/Memory/BufferCache.cs, Ryujinx.Graphics.Gpu/Memory/BufferMigration.cs, Ryujinx.Graphics.Gpu/Memory/BufferModifiedRangeList.cs, Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs, Ryujinx.Graphics.OpenGL/Sync.cs, Ryujinx.Graphics.Vulkan/SyncManager.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
Makes sure that the modified range list is always from the latest iteration of the buffer, and flushes earlier iterations of a buffer if the data has not been migrated yet.
Before, flushes on migrated buffers could flush uninitialized data, as it would assume that a sync number for a previous write had been reached, but the copy to migrate the buffer data had not yet been reached. The flush's change to the modified range could also be lost when switching, as the change would be applied to the dead buffer.
Buffers now have a reference count to keep their data alive. When a migration is performed (with modified ranges), then it takes a reference to the source buffer and gets added to a list on `_context`. When any sync is created, we check the current reached sync number and pending …
=> GPU: Track buffer migrations and flush source on incomplete copy

Ryujinx.Ava/Assets/Locales/de_DE.json, Ryujinx.Ava/Assets/Locales/el_GR.json, Ryujinx.Ava/Assets/Locales/en_US.json, Ryujinx.Ava/Assets/Locales/es_ES.json, Ryujinx.Ava/Assets/Locales/fr_FR.json, Ryujinx.Ava/Assets/Locales/it_IT.json, Ryujinx.Ava/Assets/Locales/ja_JP.json, Ryujinx.Ava/Assets/Locales/ko_KR.json, Ryujinx.Ava/Assets/Locales/pl_PL.json, Ryujinx.Ava/Assets/Locales/pt_BR.json, Ryujinx.Ava/Assets/Locales/ru_RU.json, Ryujinx.Ava/Assets/Locales/tr_TR.json, Ryujinx.Ava/Assets/Locales/zh_CN.json, Ryujinx.Ava/Assets/Locales/zh_TW.json
Add back `SettingsButtonSave` & `SettingsButtonClose` removed in #3955 
Fixes #3982
=> Ava GUI: Add back locales removed in #3955

Ryujinx.Ava/Program.cs, Ryujinx.Headless.SDL2/Program.cs, Ryujinx.Headless.SDL2/WindowBase.cs, Ryujinx.SDL2.Common/SDL2Driver.cs, Ryujinx/Program.cs
Executes `SDL_PumpEvents` on main thread.
I note the SDL2 frontend already manually calls `SDL_PumpEvents` in its main loop.
macOS enforces the need for events pumped on the main thread.
=> SDL2Driver: Invoke dispatcher on main thread

README.md
Since we now using Crowdin to handle locale translation, it could be nice to informs people somewhere.
=> Add crowdin badge and information in readme

Ryujinx.Graphics.Vulkan/Vendor.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs, Ryujinx.HLE/HOS/Applets/Error/ErrorApplet.cs, Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Proxy/DnsBlacklist.cs, Ryujinx.HLE/Loaders/Executables/NsoExecutable.cs
This PR replaces all regular expressions with [source generated ones](https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators). Small change, but it (at least in theory) should enable better application trimming and NativeAOT friendliness. The only downside is that classes need to be made partial.
=> Use source generated regular expressions

Ryujinx.Graphics.Gpu/Engine/Compute/ComputeClass.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, Ryujinx.Graphics.Gpu/Shader/CachedShaderBindings.cs, Ryujinx.Graphics.Gpu/Shader/CachedShaderProgram.cs
Reduces work on UpdateShaderState. Now the cost is a few reference moves for arrays (for stages with bindings), rather than copying data. Cached bindings arrays are created when shaders are loaded.
1-2 fps here on the usual spot in SMO.
Upside: Removes a bunch of redundant code from ComputeClass, cheaper UpdateShaderState.
Downside: bindings arrays are no longer readonly (though it was only the top level array that was readonly, not the contained ones).
=> GPU: Swap bindings array instead of copying

Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, Ryujinx.Graphics.Gpu/Engine/Threed/SpecializationStateUpdater.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClass.cs, Ryujinx.Graphics.Gpu/Shader/GpuChannelGraphicsState.cs, Ryujinx.Graphics.Gpu/Shader/GpuChannelPoolState.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCacheHashTable.cs, Ryujinx.Graphics.Gpu/Shader/ShaderSpecializationList.cs, Ryujinx.Graphics.Gpu/Shader/ShaderSpecializationState.cs
This PR adds a new class, the SpecializationStateUpdater, that allows elements of specialization state to be updated individually, and signal the state is checked when it changes between draws, instead of building and checking it on every draw. This also avoids building spec state switching shaders.
Most state updates have been moved behind the shader state update, so that their specialization state updates make it in before shaders are fetched.
Downside: Fields in GpuChannelGraphicsState are no longer readonly. To counteract copies that might be caused this I pass it as `ref` when possible, though maybe `in` would be better? Not really sure about the quirks of `in` and the difference probably won't show on a benchmark.
The result is around 2 extra FPS on SMO here in the usual spot. Not …
=> GPU: Use lazy checks for specialization state

Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessorBase.cs, Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Shader/Translation/Rewriter.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
For some reason, OpenGL does not allow SNorm formats to be used with buffer textures (at least on NVIDIA), so this workaround was added where it uses a signed integer format and does the normalization on the shader. This was also being done on Vulkan where this limitation doesn't exist. This change stops doing that on Vulkan, which makes the shaders more efficient.
Since no shader specialization was done for this, it would also be incorrect if the same shader was used for SNorm and non-SNorm textures, and this change also "fixes" this on Vulkan since no special conversion needs to be done on the shader anymore (thus there's no longer a need for specialization here). But I don't know if any game actually triggers that case.
Most UE4 games uses this format. Ultimately I don't expect any …
=> Allow SNorm buffer texture formats on Vulkan

Ryujinx.HLE/HOS/Kernel/SupervisorCall/InfoType.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
Add's InfoType.MesosphereCurrentProcess to enum InfoType. 
It allows exefs replacements and homebrew to easily get their own process handle for use with certain SVCs, such as MapProcessMemory.
This isn't vanilla HOS behaviour but rather an extension added by Atmosphere, so I am not sure if this is fitting for Ryujinx. It is possible to get the process handle with a hacky method involving an IPC trick, but this is not exactly desirable.
=> Add InfoType.MesosphereCurrentProcess

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Translation/Rewriter.cs
Fixes a regression from #4011 where shaders with global memory access from unknown location would do the global -> storage replacement, but since there are no storage buffers declared, it would fail to generate the SPIR-V, resulting in crashes. Affected game is Mario Golf Super Rush, and maybe a few more (but generally those games are not working properly anyway, with the exception of Mario Golf, since the global memory access will be wrong in those cases).
=> Fix shaders with global memory access from unknown locations

Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
People are constantly inadvertently uncapping their framerates with the hotkey being set to Tab due to Alt Tabbing. Furthermore, Avalonia uses Tab for UI navigation, so it doesn't even work there. As more people switch to Avalonia, it becomes more apparent that the default needs to change.
Chose F1 specifically because it's the closest to Tab. Was considering F9 instead as that has less chances of misclicking F2 (mute audio) or Esc (quit emulation), though I leave that up for debate. Regardless, it can be customized on Avalonia, so not too big of a deal.
=> Change default Vsync toggle hotkey to F1 instead of Tab

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Translation/Rewriter.cs
Fixes a regression from #4029 that caused storage buffer access in the shader to be ignored when the match fails.
Closes #4036.
=> Fix storage buffer access when match fails

Ryujinx.Audio/Renderer/Common/EffectType.cs, Ryujinx.Audio/Renderer/Common/PerformanceDetailType.cs, Ryujinx.Audio/Renderer/Dsp/Command/CommandType.cs, Ryujinx.Audio/Renderer/Dsp/Command/CompressorCommand.cs, Ryujinx.Audio/Renderer/Dsp/Command/LimiterCommandVersion1.cs, Ryujinx.Audio/Renderer/Dsp/Command/LimiterCommandVersion2.cs, Ryujinx.Audio/Renderer/Dsp/Effect/ExponentialMovingAverage.cs, Ryujinx.Audio/Renderer/Dsp/FixedPointHelper.cs, Ryujinx.Audio/Renderer/Dsp/FloatingPointHelper.cs, Ryujinx.Audio/Renderer/Dsp/State/CompressorState.cs, Ryujinx.Audio/Renderer/Dsp/State/LimiterState.cs, Ryujinx.Audio/Renderer/Parameter/Effect/CompressorParameter.cs, Ryujinx.Audio/Renderer/Server/BehaviourContext.cs, Ryujinx.Audio/Renderer/Server/CommandBuffer.cs, Ryujinx.Audio/Renderer/Server/CommandGenerator.cs, Ryujinx.Audio/Renderer/Server/CommandProcessingTimeEstimatorVersion1.cs, Ryujinx.Audio/Renderer/Server/CommandProcessingTimeEstimatorVersion2.cs, Ryujinx.Audio/Renderer/Server/CommandProcessingTimeEstimatorVersion3.cs, Ryujinx.Audio/Renderer/Server/CommandProcessingTimeEstimatorVersion5.cs, Ryujinx.Audio/Renderer/Server/Effect/BaseEffect.cs, Ryujinx.Audio/Renderer/Server/Effect/CompressorEffect.cs, Ryujinx.Audio/Renderer/Server/ICommandProcessingTimeEstimator.cs, Ryujinx.Audio/Renderer/Server/StateUpdater.cs, Ryujinx.Tests/Audio/Renderer/Parameter/Effect/CompressorParameterTests.cs
This was in my reversing notes but seems I completely forgot to implement it in #3230.
Also took the opportunity to simplify the Limiter effect a bit.
No games seems to use that effect so far
=> amadeus: Add missing compressor effect from REV11

Ryujinx/Ui/Windows/AvatarWindow.cs, Ryujinx/Ui/Windows/UserProfilesManagerWindow.Designer.cs
In #3980 the GtkSharp package were updated [here](https://github.com/Ryujinx/Ryujinx/commit/e211c3f00a847f50b286349918e5c51967862e93#diff-570835bf5164a409a35109d99b66fe54d190f34e8ecf3c93692eae26b5e7a04fR22), now `VBox`, `HBox` and `Alignment` are deprecated and adds some warnings. This PR fixes that.
=> gtk: Fixes warnings about obsolete components

Ryujinx.HLE/FileSystem/ContentManager.cs, Ryujinx.HLE/HOS/ApplicationLoader.cs
We currently add all AoC items to a list in `ContentManager` and the enable check is only done when FS service ask for the data. Which is wrong. It causes an issue in MK8D which doesn't boot even if you have disabled a not updated DLC.
I've fixed it by not adding the disabled AoC item to the list, I've removed some duplicate code too. There is still an edge case because we currently don't check the AoC Item version, but that should be fixed later since now MK8D throw an error if the DLC isn't updated.
=> hle: Do not add disabled AoC item to the list

Ryujinx.Ava/Ryujinx.Ava.csproj, Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj, Ryujinx/Ryujinx.csproj
This PR closes #2400.
I think I prefer keeping `THIRDPARTY.md` as is and not split it into multiple files. But I'll let @AcK77 decide if that's sufficient to close the referenced issue.
=> Add Ryujinx license to builds

Ryujinx.HLE/HOS/Services/Account/Acc/ApplicationServiceServer.cs, Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForApplication.cs
Closes #4021
Check a bit by RE.
Now Hulu can boot and then throw an error 94 probably due to a wrong socket implementation.
=> acc: Stub CheckNetworkServiceAvailabilityAsync

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/HelperFunctions/SwizzleAdd.glsl, Ryujinx.Graphics.Shader/CodeGen/Spirv/Instructions.cs
Fixes a mistake on the helper function for this shader instruciton that was causing the LUT index to be out of bounds.
Fixes text rendering on The Stanley Parable: Ultra Deluxe, and maybe other games.
Before:
After:
=> Fix shader FSWZADD instruction

Ryujinx.Ava/Assets/Styles/Styles.xaml, Ryujinx.Ava/Ui/Controls/GameListView.axaml, Ryujinx.Ava/Ui/Windows/MainWindow.axaml
This PR change 3 things:
- The Menu font size is reduced to follow what any other application do (We could do it as a settings later).
- Status Bar margin/size is reduced to get something not too large for nothing and well aligned:
Before:
After:
- The selector height when you click on a game in the game list view is increased:
Before:
After:
=> ava: Restyle the Status Bar

Ryujinx.Common/Ryujinx.Common.csproj, Ryujinx.Common/System/ForceDpiAware.cs, Ryujinx.Common/System/GdiPlusHelper.cs
We only used it in one spot for DPI scaling factor.
This implements the same behaviour using gdiplus.
This remove 700KB of dependency to download and around 170KB unpacked.
=> misc: Remove dependency on System.Drawing.Common

Ryujinx.Ava/Input/AvaloniaKeyboardMappingHelper.cs, Ryujinx.Common/GraphicsDriver/NVThreadedOptimization.cs, Ryujinx.Common/SystemInfo/WindowsSystemInfo.cs, Ryujinx.Graphics.Device/DeviceState.cs, Ryujinx.Graphics.Gpu/Engine/DeviceStateWithShadow.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdateTracker.cs, Ryujinx.HLE/HOS/Applets/Error/ErrorApplet.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs, Ryujinx.HLE/HOS/Services/Nfc/Nfp/NfpManager/INfp.cs, Ryujinx.Tests.Unicorn/Native/Interface.cs
This PR fixes some easy trimming warnings by using trimming friendly overloads. Some types were attributed too (it looks ugly though, but this is the only way to fix).
Other trimming warnings such as using dynamic code during JSON serialization/deserialization and reflection usages will be fixed in subsequent PRs.
=> Use method overloads that support trimming. Mark some types to be trimming friendly

Directory.Packages.props, Ryujinx.Audio.Backends.OpenAL/Ryujinx.Audio.Backends.OpenAL.csproj, Ryujinx.Ava/Ryujinx.Ava.csproj, Ryujinx.Common/Ryujinx.Common.csproj, Ryujinx.Graphics.OpenGL/Ryujinx.Graphics.OpenGL.csproj, Ryujinx.Graphics.Vulkan/Ryujinx.Graphics.Vulkan.csproj, Ryujinx.HLE/Ryujinx.HLE.csproj, Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj, Ryujinx.Horizon.Generators/Ryujinx.Horizon.Generators.csproj, Ryujinx.Input/Ryujinx.Input.csproj, Ryujinx.Memory.Tests/Ryujinx.Memory.Tests.csproj, Ryujinx.SDL2.Common/Ryujinx.SDL2.Common.csproj, Ryujinx.ShaderTools/Ryujinx.ShaderTools.csproj, Ryujinx.Tests/Ryujinx.Tests.csproj, Ryujinx.Ui.Common/Ryujinx.Ui.Common.csproj, Ryujinx.sln, Ryujinx/Ryujinx.csproj
This PR enables easy solution-wise package versions management using new NuGet feature - [NuGet Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management). This will forbid usage of different package versions in different projects by default (you can override version if you need it).
This feature is already supported in Rider 2022.3 and Visual Studio 2022 17.4.
Dependabot already supports this format. As a benefit all his PRs will be made in the single file with these changes.
=> Use NuGet Central Package Management to manage package versions solution-wise

Directory.Packages.props
Fix packaging issues on macOS related to an unsatisfied dependency on libX11
=> misc: Update to Ryujinx.Graphics.Nvdec.Dependencies 5.0.1-build13

Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs, Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Proxy/DnsMitmResolver.cs
This PR adds support for Atmosphère's [dns_mitm](https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/features/dns_mitm.md).
This also includes support for the IPC extension command 6500 ("AtmosphereReloadHostsFile").
Since we don't need to differentiate between sysmmc and emummc, we will only be reading `/atmosphere/hosts/default.txt`.
This allows for simple DNS redirection which is used by some mods.
---
Relevant AMS source files:
- [dnsmitm_resolver_impl.cpp](https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/ams_mitm/source/dns_mitm/dnsmitm_resolver_impl.cpp)
- [dnsmitm_host_redirection.cpp](https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/ams_mitm/source/dns_mitm/dnsmitm_host_redirection.cpp)
=> Bsd: Add support for dns_mitm

Ryujinx.Graphics.Vulkan/VulkanInitialization.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
radv only create the border color bo if this feature is enabled, so it crashed when creating samplers with custom border colors 
Fixes #4072
Fixes #3993
=>  Vulkan: enable VK_EXT_custom_border_color features

Ryujinx.Graphics.Gpu/Shader/DiskCache/ShaderBinarySerializer.cs
Fixes a silly mistake that was causing NRE when loading shader caches for games that uses Vertex A. `Info` is expected to be null in this case, because Vertex A shaders are merged with Vertex B, and Vertex B is the one that has the actual `Info`. The Vertex A entry is only there to hold the guest code which is used for modification checks.
One of the affected games is Catherine. The issue only manifests if the user has a shader cache, so it won't happen on the first time playing or after purging the shader cache.
This is likely a regression from #3868.
=> Fix NRE when loading Vulkan shader cache with Vertex A shaders

Ryujinx.Ava/Ui/Applet/SwkbdAppletDialog.axaml.cs
This should have been done in #3938, but was overlooked.
This PR makes the swkbd applet visible again on Linux.
=> Avalonia: Fix invisible swkbd applet on Linux

Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs
Fixes a regression caused by #4003 where the code that writes `_vtgWritesRtLayer` was removed, breaking the crowd in mario strikers.
=> GPU: Fix layered attachment write

Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/FriendService/Types/UserPresence.cs
This fixes an error from #3805 that caused a wrong conversion of ``AppKeyValueStorage`` to string.
As that information isn't really relevant without appropriate parsing, it was removed from ``ToString``.
This should get ride of "bell warning" in Mario Kart 8 when entering Time Trials.
=> hle: Fix wrong conversion in UserPresence.ToString

ARMeilleure/ARMeilleure.csproj, ARMeilleure/CodeGen/X86/Assembler.cs, ARMeilleure/CodeGen/X86/AssemblerTable.cs, ARMeilleure/CodeGen/X86/HardwareCapabilities.cs, ARMeilleure/CodeGen/X86/IntrinsicTable.cs, ARMeilleure/CodeGen/X86/X86Instruction.cs, ARMeilleure/Instructions/InstEmitSimdLogical.cs, ARMeilleure/IntermediateRepresentation/Intrinsic.cs, ARMeilleure/Optimizations.cs, ARMeilleure/Translation/PTC/Ptc.cs
The first sample use-case being a single-instruction alternative to the vector-`NOT` instruction by utilizing the [vpternlogd instruction](https://www.felixcloutier.com/x86/vpternlogd:vpternlogq).
Implements enough of the EVEX encoding features to utilize AVX512 instructions for a 128-bit register use-case.
Does not include:
* Embedded rounding controls
* Embedded exception controls
`Not_V_*` unit tests all pass on my `i9-11900k` and on my `i9-7900x`. Would be good to get some additional verifications on additional hardware or possibly utilizing the [Intel Software Development Emulator](https://www.intel.com/content/www/us/en/developer/articles/tool/software-development-emulator.html).
=> ARMeilleure: Add initial support for AVX512(EVEX encoding)

ARMeilleure/ARMeilleure.csproj, ARMeilleure/CodeGen/X86/Assembler.cs, ARMeilleure/CodeGen/X86/AssemblerTable.cs, ARMeilleure/CodeGen/X86/HardwareCapabilities.cs, ARMeilleure/CodeGen/X86/IntrinsicTable.cs, ARMeilleure/CodeGen/X86/X86Instruction.cs, ARMeilleure/Instructions/InstEmitSimdLogical.cs, ARMeilleure/IntermediateRepresentation/Intrinsic.cs, ARMeilleure/Optimizations.cs, ARMeilleure/Translation/PTC/Ptc.cs
Reverts Ryujinx/Ryujinx#3663
This is causing regressions on a few games on CPUs supporting AVX-512.
=> Revert "ARMeilleure: Add initial support for AVX512(EVEX encoding)"

ARMeilleure/CodeGen/X86/CodeGenerator.cs, ARMeilleure/CodeGen/X86/X86Optimizer.cs, ARMeilleure/Translation/PTC/Ptc.cs
This allows some zero-extension `mov`s to be removed, when the source and destination registers are the same, and the source is 32-bit. In this case, we know that the upper bits are already zero so the zero extension is redundant.
Sample diff.
Before:
```nasm
63: 41 89 34 10             mov    DWORD PTR [r8+rdx*1],esi
67: 41 8d 57 e8             lea    edx,[r15-0x18]
6b: 8d 71 04                lea    esi,[rcx+0x4]
6e: 89 f6                   mov    esi,esi
70: 41 89 3c 30             mov    DWORD PTR [r8+rsi*1],edi
74: 8d 71 08                lea    esi,[rcx+0x8]
77: 89 f6                   mov    esi,esi
79: 45 89 24 30             mov    DWORD PTR [r8+rsi*1],r12d
7d: 8d 71 0c                lea    esi,[rcx+0xc]
80: 89 f6                   mov    esi,esi
82: 45 89 2c 30             mov …
```
=> Eliminate zero-extension moves in more cases on 32-bit games

ARMeilleure/IntermediateRepresentation/Operand.cs
I noticed a weirdly high cost for dictionary accesses from MarkLabel etc. Turns out that the hash code was always the same for labels, so the whole point of having a dictionary was missed and it was putting everything in the same bucket. I made it always hash the _data pointer as that's a good source of identifiable and "random" data.
Will likely affect lowCq (first boot time) more than highCq (pptc, generally).
=> ARMeilleure: Hash _data pointer instead of value for Operand

Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, Ryujinx.Graphics.Gpu/Engine/Threed/DrawState.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs
This is just adding some things I missed on #4123. The vertex buffer size was incorrect in some cases because it was still using the first vertex and count value from the GPU state to calculate it, rather than the parameters that are passed on those methods. This updates the code to use the correct values and calculate the correct vertex buffer size.
Fixes vertex explosions in Sphinx and the Cursed Mummy on OpenGL.
Before:
After:
Technically also fixes it on Vulkan, but the game is not rendering on Vulkan + NVIDIA right now due to a different issue (it does render on Intel).
=> Fix DrawArrays vertex buffer size

Ryujinx.HLE/HOS/Services/Nv/INvDrvServices.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostDbgGpu/NvHostDbgGpuDeviceFile.cs, Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostProfGpu/NvHostProfGpuDeviceFile.cs, Ryujinx.HLE/Ryujinx.HLE.csproj
When debug mode isn't enabled, opening ``/dev/nvhost-dbg-gpu`` or ``/dev/nvhost-prof-gpu`` should fail with a not implemented error code.
This implement this behaviour and also define stubbed interfaces for completeness.
This fixes warning logs on [慟哭そして…](https://github.com/Ryujinx/Ryujinx-Games-List/issues/2901) related to that.
=> hle: Handle GPU profiler and debugger device path correctly

Ryujinx.HLE/HOS/SystemState/SystemStateMgr.cs, Ryujinx.HLE/HOS/SystemState/TitleLanguage.cs
Due to enum.Parse can't transform SystemLanguage to TitleLanguage correctly, it makes 
```
private void GetGameInformation(ref ApplicationControlProperty controlData, out string titleName, out string titleId, out string publisher, out string version)
{
_ = Enum.TryParse(_desiredTitleLanguage.ToString(), out TitleLanguage desiredTitleLanguage);
...
}
```
below transform always get AmericanEnglish in desiredTitleLanguage which is not right, and UI will always show English Title in game table even if you chose SimplifiedChinese as Title Language .
Here are some compartions.
Before (SimplifiedChinese, TraditionalChinese)
After (SimplifiedChinese, TraditionalChinese)
Fixes #2510.
=> make UI display correct content in Chinese

Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs
There was an issue after the optimization that tries to avoid updating textures and samplers when the state didn't change. The issue was that the checks weren't enough if the texture or sampler pool changed, but the handles remained the same. I fixed that by forcing it to update if the current texture pool or sampler pool changed, but that only fixed the issue partially. The scenario below is still possible for example:
- Draw is done with sampler pool A, uses samplers 1 and 2 from pool A.
- Current sampler pool is changed to sampler pool B.
- Draw is done with sampler pool B, uses sampler 1 from pool B (correct).
- Draw is done with sampler pool B, uses sampler 1 from pool B (correct), and sampler 2 from pool A (wrong).
To fix this issue, I changed it to just clear all cached state when …
=> GPU: Force rebind when pool changes

ARMeilleure/Instructions/InstEmitSimdCvt.cs, ARMeilleure/Translation/PTC/Ptc.cs, Ryujinx.Tests/Cpu/CpuTestSimd.cs
The implementation of the slow path for this instruction was incorrect because it would always extract the first element (0) of the input vector, and it was not getting caught by the tests because the input vectors used had the same value in all elements. This change fixes the issue and updates the test to be able to catch this kind of error by using different element values.
Note that by default we use a fast path here that use equivalent x86 instructions directly to emulate this, and the fast path does not suffer from this bug, so the only users affected are those using CPUs that does not support the F16C extension, on games that uses half-float. Intel supports this extension since Ivy Bridge, so only 2nd gen Intel Core CPUs and older should be affected. AMD supports it from even …
=> Fix CPU FCVTN instruction implementation (slow path)

Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.GAL/Format.cs, Ryujinx.Graphics.Gpu/Image/FormatTable.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs, Ryujinx.Graphics.Texture/ETC2Decoder.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
Desktop GPUs don't support the ETC2 format on Vulkan, which was causing graphical issues and crashes in a few games that uses those formats. This change implements a software decoder that will decompress those textures on CPU when the format is not supported on the GPU.
Fixes crashes on Vegas Party, Paradigm Paradox and any other game with the Etc2 format error. Mainly affects NVIDIA and AMD since Intel supports those formats, and Apple Silicon also supports it.
I also added the 1-bit alpha ETC2 format (ETC2 punchthrough alpha) which was missing from the format table, but I'm not aware of any game that uses it.
It's worth noting that NVN does not expose the ETC2 format on the Switch, and Vulkan probably doesn't either, so games using that are those using OpenGL and GLES APIs.
Now the only …
=> Implement a software ETC2 texture decoder

ARMeilleure/Translation/SsaConstruction.cs, Ryujinx.HLE/HOS/Services/Account/Acc/Types/UserProfile.cs, Ryujinx.HLE/HOS/Services/Caps/CaptureManager.cs, Ryujinx.HLE/HOS/Services/Pcv/Bpc/IRtcManager.cs, Ryujinx.HLE/HOS/Services/Ro/IRoInterface.cs, Ryujinx.HLE/HOS/Services/Time/Clock/Types/TimeSpanType.cs
1st commit: Replace a Array.Clear(x, 0, x.Length) call with Array.Clear(x) (more performant)
2nd commit: Use DateTime.UnixEpoch field instead of manually initializing a static field in some places.
3rd commit: Replace SHA256.ComputeHash calls with new static SHA256.HashData method (More performant and avoids the need to initialize a SHA256 instance)
=> Some minor cleanups and optimizations

Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs, Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdSockAddr.cs
bsd::RecvFrom: verify output buffer size (sockAddrOutSize) is non zero before writing socket address
fix for #3458
=> bsd::RecvFrom: verify output buffer size before writing socket address

.gitignore, Ryujinx.Headless.SDL2/Program.cs, nuget.config
While trying to debug #3874 I noticed Ryujinx.Headless.SDL2 was not receiving any SDL events.
This PR fixes this issue and also adds a `nuget.config` I originally planned to add with #4128.
=> [Headless] Fix for not receiving any SDL events on Linux
