Ryujinx.Graphics.GAL/IRenderer.cs, Ryujinx.Graphics.GAL/Multithreading/Commands/Renderer/CreateSyncCommand.cs, Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs, Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoClass.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClass.cs, Ryujinx.Graphics.Gpu/GpuContext.cs, Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs, Ryujinx.Graphics.Vulkan/CommandBufferPool.cs, Ryujinx.Graphics.Vulkan/PipelineFull.cs, Ryujinx.Graphics.Vulkan/SyncManager.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
When the WaitForIdle method is called, we create sync as some internal GPU method may read back written buffer data. Some games randomly intersperse compute dispatch into their render passes, which result in this happening an unbounded number of times depending on how many times they run compute or insert memory barriers.
Creating sync in Vulkan is expensive, as we need to flush the current command buffer so that it can be waited on. We have a limited number of active command buffers due to how we track resource usage, so submitting too many command buffers will force us to wait for them to return to the pool.
This PR allows less "important" sync (things which are less likely to be waited on) to wait on a command buffer's result without submitting it, instead relying on AutoFlush or …
=> Vulkan: Don't flush commands when creating most sync

Ryujinx.Ui.Common/App/ApplicationLibrary.cs
`._` files are automatically generated by macOS to store certain metadata about files when you transfer them to an SD card. These files are hidden in finder (even if you enable “show hidden files”) and can only be deleted through terminal. Some users have reported that these files appeared in the game list, so this is a PR that filters them out of the game list.
=> Filter hidden game files from the Game List

ARMeilleure/Translation/ArmEmitterContext.cs, ARMeilleure/Translation/PTC/IPtcLoadState.cs, ARMeilleure/Translation/PTC/Ptc.cs, ARMeilleure/Translation/PTC/PtcProfiler.cs, ARMeilleure/Translation/Translator.cs, Ryujinx.Ava/AppHost.cs, Ryujinx.Ava/Program.cs, Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs, Ryujinx.Cpu/ICpuContext.cs, Ryujinx.Cpu/IDiskCacheState.cs, Ryujinx.Cpu/Jit/JitCpuContext.cs, Ryujinx.Cpu/Jit/JitDiskCacheLoadState.cs, Ryujinx.Cpu/LoadState.cs, Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/ArmProcessContext.cs, Ryujinx.HLE/HOS/ArmProcessContextFactory.cs, Ryujinx.HLE/HOS/ProgramLoader.cs, Ryujinx.Headless.SDL2/Program.cs, Ryujinx/Program.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/RendererWidgetBase.cs
Right now PPTC has some global state, which means that when there are multiple guest processes running it can't work properly, so it won't be able to manage the caches for the separate processes. This changes it to have one PPTC cache instance per guest process (tied to the `Translator`). This is cleaner and allows the multi-process scenario to work. This allows the workaround where PPTC is disabled when the JIT service is loaded to be removed too (it will now also be cached).
Testing is welcome. Just to make sure PPTC is still working as it should.
=> Make PPTC state non-static

Directory.Packages.props
As title say.
This doesn't include the motion changes of #3894.
=> chore: Update Ryujinx.SDL2-CS to 2.26.1

Ryujinx.Horizon.Common/Result.cs, Ryujinx.Horizon/Sdk/Sf/Hipc/Api.cs
I recently noticed a crash I was getting when minimizing Ryujinx.Headless.SDL2 while it was loading a game.
This PR fixes this crash by adding a new method `AbortOnFailureUnless` and replacing the call to `AbortUnless` with it inside the `Api.Reply` method.
This results in `AbortUnless` being unused currently, should it be removed?
=> [hipc] Fix 'Unexpected result code Success returned' in Reply()

.github/workflows/build.yml, .github/workflows/release.yml, Ryujinx.Ava/Ryujinx.Ava.csproj
Avalonia seems to not like when the artifact doesns't match the root namespace...
Address that by moving the binary to "Ryujinx" like we do on macOS build.
=> ava: Fix regression caused by #4013

Ryujinx.Ava/UI/Windows/MainWindow.axaml
Minor annoyance.
Before:
After:
=> MainWindow: Vertically center SearchBox TextPresenter

Ryujinx.Horizon.Common/Result.cs, Ryujinx.Horizon/Sdk/Sf/Hipc/Api.cs
Because `Reply` was passing the session handle to `ReplyAndReceive`, it would in some cases also receive one request (if a request has been made by the client since the last call to `WaitSynchronization`. This would cause the request to never be actually processed. This fixes the issue by not passing any handle which is the correct behaviour. Result check was also changed, this function is not expected to ever return success. Since it does not pass any handle to wait on, it should always return time out (since nothing was signalled) or port remote closed if the client clossed the session before the service had time to reply.
This is an issue from #4188.
=> HIPC: Fix reply possibly also receiving one request

Ryujinx.Ava/Helper/LoggerAdapter.cs, Ryujinx.Ava/Program.cs, Ryujinx.Common/Logging/LogClass.cs
Instead of outputting to `System.Diagnostics.Trace`, capture Avalonia logging events and adapt to our logging system.
=> Ava: Make Avalonia use our logging system

.github/workflows/build.yml, .github/workflows/release.yml, Ryujinx.Ava/Ryujinx.Ava.csproj, distribution/linux/Ryujinx.sh
Instead of changing CI to rename the file (which also breaks Avalonia...) we could just add a small check to Ryujinx.sh to figure out if Ryujinx or Ryujinx.Ava needs to be executed.
This way we don't need to rename (read: break) the Avalonia binary and can still use the same script.
=> Linux: Add Avalonia detection to Ryujinx.sh

.github/workflows/release.yml, Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj, distribution/linux/Ryujinx.sh
Minor *emergency* PR, since I broke CI with #4224 and didn't include the headless build in #4013.
This PR fixes the packaging step in our release workflow and also adds `Ryujinx.sh` to the headless build.
=> Fix linux packaging step for CI & Add headless build support to Ryujinx.sh

Ryujinx.Ava/Program.cs, Ryujinx.Ui.Common/Helper/CommandLineState.cs, Ryujinx/Program.cs
This small PR adds two command line arguments for both GUIs to override the state of `EnableDockedMode`:
- `--docked-mode`
- `--handheld-mode`
A user on discord has a usecase where this makes sense and I like the idea, so I quickly added it.
=> Add command line arguments to override docked mode

Ryujinx.Ava/UI/Helpers/ContentDialogHelper.cs
Another small PR to fix a regression introduced with #4237.
This PR adds a missing null check to `ContentDialogHelper.ShowAsync()`. This is needed since `GetMainWindow()` can also return null, which is the case on first startup.
Example log from someone on Discord: 
[Ryujinx_1.1.526_2023-01-09_23-10-17.log](https://github.com/Ryujinx/Ryujinx/files/10377344/Ryujinx_1.1.526_2023-01-09_23-10-17.log)
=> Ava: Add missing null check to ContentDialogHelper.ShowAsync()

distribution/macos/Info.plist
https://developer.apple.com/documentation/bundleresources/information_property_list/lsapplicationcategorytype Makes it auto-add to the macOS Launchpad games folder
=> Set LSApplicationCategoryType to games

Ryujinx.Graphics.Gpu/Image/AutoDeleteCache.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs
Currently we have a `AutoDeleteCache` that keeps the mostly frequently used textures on the cache, while deleting the least used ones. It has a hard limit of 2048 entries right now, so if the count gets past that limit, it will start deleting textures. In addition to that we remove data when the storage for different textures overlaps, and that works well for most games. However there is a rare scenario where this does not work well, which is the game frequently remapping textures at different memory regions. The fixed limit on the number of entries does not work well when each texture is very large. We can use a very high amount of VRAM with a low amount of textures. And the overlap removal doesn't help because the textures are located in different memory regions.
To fix this issue, this …
=> Remove textures from cache on unmap if not mapped and modified

Ryujinx.Ava/UI/Windows/TitleUpdateWindow.axaml.cs
=> Ava: Fixes Update count in heading

Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> When you set a "Graphics shader dump path", Avalonia shows a prompt asking if you want to disable it when the game is started. However, clicking on "Yes" does nothing. The path is still set and it asks it every time you launch the game, even if you click on "Yes".
This is now fixed.
(Closes item of https://github.com/Ryujinx/Ryujinx/issues/3662)
=> Ava UI: Fixes PerformanceCheck condition

Ryujinx.Horizon/LogManager/Ipc/LmLogger.cs, Ryujinx.Horizon/LogManager/Types/LogPacket.cs
When guest use `lm` service to print some logging, sent packets have a flag field. We currently doesn't take care of the flags, that could lead to strange logging like that:
This is now fixed:
It's not useful at all, but... Why not 😄 !
=> lm: Handle Tail flag in LogPacket

ARMeilleure/Translation/PTC/Ptc.cs
Add an `Architecture` field to PTC `OuterHeader`.
=> Ptc: Check process architecture

Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs, Ryujinx.Ava/UI/Views/Settings/SettingsGraphicsView.axaml
This PR re-order the settings of the Resolution Scaler in Ava UI to follow what we currently have in GTK.
Before:
After:
I've sorted the configurations fields by their categories in `LoadCurrentConfiguration` and `SaveSettings` too. Some cleanup have to be done in a near future as those names suggest.
(Closes some items of https://github.com/Ryujinx/Ryujinx/issues/3662)
=> Ava UI: Reorder settings of Resolution Scaler

Ryujinx.Horizon.Generators/Hipc/HipcGenerator.cs, Ryujinx.Horizon/Prepo/Ipc/PrepoService.cs, Ryujinx.Horizon/Sdk/Account/Uid.cs, Ryujinx.Horizon/Sdk/Ncm/ApplicationId.cs, Ryujinx.Horizon/Sdk/Prepo/IPrepoService.cs, Ryujinx.Horizon/Sdk/Sm/ServiceName.cs
This PR fixes a little regression I've made in #4220, `SaveSystemReport*` IPCs should use an ApplicationId instead of a pid.
I've added an `ApplicationId` struct to do that more cleaner as just use an `ulong`. 
During testing, an issue of wrong indexes args in HipcGenerator was found and fixed (thanks to @gdkchan )
=> Prepo: Fix SaveSystemReport* IPC definitions

Ryujinx.Graphics.Vulkan/BufferManager.cs, Ryujinx.Graphics.Vulkan/FramebufferParams.cs, Ryujinx.Graphics.Vulkan/MemoryAllocator.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/Vendor.cs, Ryujinx.Graphics.Vulkan/VulkanInitialization.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs, Ryujinx.Graphics.Vulkan/Window.cs
This is relaxing the Vulkan requirements, basically optionally requesting more features, to allow it to run on more GPUs.
This mainly targets the Raspberry Pi 4, but it can benefit other mobile GPUs too.
Changes:
- More features are now only requested if the drivers supports it, instead of being always requested.
- Transform feedback is only enabled if the extension is supported and the feature is supported.
- Choose composite alpha flags based on what the driver supports. Not all drivers supports the "Opaque" mode.
- The number of color attachment on a sub pass was always 8 due to the way how `MaxAttachmentIndex` was set. However the Raspberry Pi GPU only supports up to 4. `MaxAttachmentIndex` was changed to actually reflect the maximum index used. This allows games that uses 4 …
=> Relax Vulkan requirements

Ryujinx.Graphics.Gpu/Image/TextureGroup.cs
Because the `Modified` flag was not being cleared for those textures, the data written from CPU (on GPU thread) was never uploaded to GPU on the modified texture. The texture would keep stale, incorrect data. The fix here is clearing the modified flag if the data is modified from the CPU on the GPU thread.
This fixes missing textures on EVE ghost enemies, and possibly other games.
Before:
After:
Note that on Vulkan, the issue only happens with backend multithreading set to On or Auto. On OpenGL it should happen regardless of this setting. That's because the flag was already being cleared if the `Sync` call happens from the GPU thread (which was always the case on Vulkan with backend threading disabled).
=> Fix texture modified on CPU from GPU thread after being modified on GPU not being updated

Ryujinx.Graphics.Gpu/GpuChannel.cs
While testing EVE ghost enemies I got some random NRE crashes here. It is hard to debug since they are random and don't happen at the same place (but generally happen after playing a video, which is when channels are destroyed). My theory is that MemoryUnmappedHandler is being called after the memory manager is set to null, but before the event is unregistered. So this adds a explicit null check to avoid that.
This is likely a regression from #3862.
=> Fix NRE when MemoryUnmappedHandler is called for a destroyed channel

Ryujinx.Memory/MemoryBlock.cs
Change GetPageSize to use Environment.SystemPageSize #4258
Tested Environment.SystemPageSize on M1 mac and Windows 11 x64, the results are 16384 and 4096
Not sure how it will behave on SteamOS 
Closes #4258
=> Change GetPageSize to use Environment.SystemPageSize

Ryujinx.Ava/AppHost.cs, Ryujinx.Ava/Input/AvaloniaMouseDriver.cs, Ryujinx.Ava/UI/Helpers/EmbeddedWindow.cs, Ryujinx.Ava/UI/Helpers/Win32NativeInterop.cs, Ryujinx.Headless.SDL2/SDL2MouseDriver.cs, Ryujinx/Ui/RendererWidgetBase.cs
There is currently a known issue where `Hide Cursor on Idle` setting doesn't works on Windows.
It's due to the way we handle the renderer embedded window on Avalonia: https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Ava/UI/Helpers/EmbeddedWindow.cs#L136
We create our own W32 window, so even if we want to hide/show the cursor in an Avalonia control, it doesn't work. It seems to work on Linux/macOS because we handle that probably differently.
I fixed it by reworking things a bit and using some `LibraryImport`.
During my test I've discovered another issue, when `Direct Mouse Access` is enabled, it should hide the cursor, it currently doesn't work at all because of the condition used, this compare the wrong object... and so the wrong bounds. I've fixed it, but for an unknown reason the …
=> Ava UI: Fixes "Hide Cursor on Idle" for Windows

Ryujinx.HLE/HOS/Kernel/KernelStatic.cs, Ryujinx.HLE/HOS/Services/Pm/IDebugMonitorInterface.cs, Ryujinx.HLE/HOS/Services/Pm/IInformationInterface.cs, Ryujinx.HLE/HOS/Services/Pm/ResultCode.cs
Implement following missing service calls in `pm`
**`pm:info`:**
- `GetProgramId`
**`pm:dmnt`:**
- `GetApplicationProcessId`
Fixes #2516
=> Implement missing service calls in `pm`

Ryujinx.Graphics.Vulkan/TextureStorage.cs, Ryujinx.Graphics.Vulkan/TextureView.cs
Image stores doesn't work on NVIDIA if you don't specify the `StorageBit` in the usage flags. Because this was only being specified for the base `VkImage`, if the image had a format which is not storage compatible, and the view did, the store would not actually work because the storage bit was never specified. This change fixes the issue by also specifying the image usage flags for the image view.
Fixes black screen on games using multisample sRGB textures, such as Pinball FX3 and Sphinx and the Cursed Mummy.
Before:
After:
May also fix issues on games doing image store on sRGB textures on Vulkan (Kirby?). Intel is not affected, it never had this issue. Dunno about AMD.
Fixes #4280.
=> Specify image view usage flags on Vulkan

Ryujinx.Ui.Common/App/ApplicationLibrary.cs
This PR improve a bit the way applications times are displayed.
Before:
After:
Since GTK and Ava both uses the same code. I can't use locale for now. In any case things will have to be refactored when GTK will be dropped.
I have cleaned the file a bit too.
=> UI: Fix applications times

Ryujinx.Ava/UI/Renderer/EmbeddedWindow.cs, Ryujinx.Ava/UI/Renderer/RendererHost.axaml.cs
Regression from #4297, which removes the `X11Window.Hide()` call when creating an embedded Vulkan window.
This PR adds this call again and also performs some cleanup in related `Renderer` classes.
=> Ava: Fix Linux Vulkan renderer regression

Ryujinx.Graphics.Gpu/Image/AutoDeleteCache.cs, Ryujinx.Graphics.Gpu/Image/Pool.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Image/TextureDescriptor.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.Gpu/Window.cs
Time for obscure edge case performance improvements.
This texture cache takes textures that lose their last pool reference and keeps them alive until the next frame, or until an incompatible overlap removes it. This is done since under certain circumstances, a texture's reference can be wiped from a pool despite it still being in use - though typically the reference will return when rendering the next frame.
This texture cache maintains a dictionary of TextureDescriptor to texture so that textures can be easily rediscovered if they are added to the pool shortly after.
While this may slightly increase texture memory usage when quickly going through a bunch of temporary textures, it's still bounded due to the overlap removal rule. This is an alternative to replacing the pool method of …
=> Add short duration texture cache

Ryujinx.Ava/UI/Controls/GameListView.axaml
When Ava UI was done some games informations have been removed, this PR readd them (TitleId and File extension). I would add more but it's not possible for now since GTK and Ava share the same code here.
=> Ava UI: Readd some infos to the GameList

Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
Starting on macOS and having it immediately crash when loading something in is not a great first-experience.
Set graphics backend to Vulkan on macOS in default settings.
(Let me know if you want something more substantial than this, or if this is something you're alreadly planning, and I'll close this.)
=> ConfigurationState: Default to Vulkan on macOS

Ryujinx.Cpu/AddressSpace.cs
This PR fixes a small issue from #4252 that results in a NRE when disposing an AddressSpace with 4KB pages support.
Now `_privateMemoryAllocator` only executes `Dispose()` if it was in use
=> CPU: Fix NRE when disposing AddressSpace with 4KB pages support

Ryujinx.HLE/FileSystem/VirtualFileSystem.cs, Ryujinx.HLE/HOS/ApplicationLoader.cs, Ryujinx.HLE/HOS/ProgramLoader.cs, Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
We currently loading only one RomFs at a time, which could be wrong if one day we want to load more than one guest at time. This PR fixes that by loading romfs by pid.
=> HOS: Load RomFs by pid

ARMeilleure/Decoders/OpCodeTable.cs, ARMeilleure/Translation/PTC/Ptc.cs, ARMeilleure/Translation/PTC/PtcProfiler.cs, Ryujinx.Ava/UI/ViewModels/ControllerSettingsViewModel.cs, Ryujinx.Common/Utilities/UInt128Utils.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenPacking.cs, Ryujinx.Graphics.Shader/Decoders/InstTable.cs, Ryujinx.HLE/FileSystem/VirtualFileSystem.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs, Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRendererBase.cs, Ryujinx.HLE/HOS/Diagnostics/Demangler/Ast/IntegerLiteral.cs, Ryujinx.HLE/HOS/Diagnostics/Demangler/Demangler.cs, Ryujinx.HLE/HOS/Services/Account/Acc/Types/UserId.cs, Ryujinx.HLE/HOS/Services/Sockets/Nsd/IManager.cs, Ryujinx.Horizon.Generators/CodeGenerator.cs, Ryujinx.Horizon.Kernel.Generators/Kernel/SyscallGenerator.cs, Ryujinx/Ui/Windows/AmiiboWindow.cs, Ryujinx/Ui/Windows/ControllerWindow.cs
Just a bunch of low-hanging fruits.
This PR replaces substring usages with span slices where possible so it will not allocate in this places. It also introduces StringBuilder in a shader code generator which for some reason uses dumb string concatenations instead. But I think maybe it needs to be benchmarked anyway.
=> Optimize string memory usage. Use Spans and StringBuilders where possible

ARMeilleure/Signal/NativeSignalHandler.cs
AArch64 linux requires testing.
Offsets reference: https://gist.github.com/merryhime/bb1b41f0c8c55e413e36b7ec55e389a8
Refer to the following documentation regarding AArch64 Linux to lookup ESR: https://github.com/torvalds/linux/blob/6e50979a9c87371fdb85d16058f9b5cb40751501/arch/arm64/include/uapi/asm/sigcontext.h#L39
=> NativeSignalHandler: Fix write flag

Ryujinx.Graphics.Vulkan/HardwareCapabilities.cs, Ryujinx.Graphics.Vulkan/PipelineFull.cs, Ryujinx.Graphics.Vulkan/VulkanInitialization.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
The only guarantee of the occlusion query type in Vulkan is that it will be zero when no samples pass, and non-zero when any samples pass. Of course, most GPUs implement this by just placing the # of samples in the result and calling it a day. However, this lax restriction means that GPUs could just report a boolean (1/0) or report a value after one is recorded, but before all samples have been counted.
MoltenVK falls in the first category - by default it only reports 1/0 for occlusion queries. Thankfully, there is a feature and flag that you can use to force compatible drivers to provide a "precise" query result, that being the real # of samples passed.
Should fix ink collision in Splatoon 2/3 on MoltenVK. Mentioned on (#4062).
=> Vulkan: Explicitly enable precise occlusion queries

Ryujinx.Ava/Modules/Updater/Updater.cs, Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs, Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs, Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
Since https://github.com/Ryujinx/Ryujinx/pull/4178 is merged, users reported the Updater behavior is a bit strange:
- If you deny the update on startup, then the MenuItem is disabled.
- Running a game and stop it makes the MenuItem enabled back, but if you click, nothing appear.
(Preview of them can be shown at https://github.com/Ryujinx/Ryujinx/issues/3662#issuecomment-1375512394)
This PR should fixes that, the logic using a bool was broken. I've cleaned up some parts of the updater too but not too much since it's not the point here.
(Closes some items of https://github.com/Ryujinx/Ryujinx/issues/3662)
=> Ava UI: Fixes and cleanup Updater

Ryujinx.Audio/Backends/CompatLayer/CompatLayerHardwareDeviceDriver.cs, Ryujinx.Audio/Backends/CompatLayer/CompatLayerHardwareDeviceSession.cs, Ryujinx.Audio/Renderer/Dsp/PcmHelper.cs
* Implement PCM24 conversion.
* Fix PCM8 conversion (was clipping badly).
This PR allows audio devices that do not support PCM16, PCM32 or float output to have PCM24 and PCM8 as possible output options.
=> Audio: Implement PCM24 output

Ryujinx.Ava/UI/Windows/MainWindow.axaml, Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
Most Apps on Mac OS use ^+⌘+F (Control+Cmd+F) to toggle fullscreen mode
Added additional HotKey to toggle full screen by ^+⌘+F. 
Tested on Mac OS Ventura
Closes #3981
=> Ava UI: Add Control+Cmd+F HotKey for Mac OS

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.OpenGL/Program.cs, Ryujinx.Graphics.Shader/Decoders/InstDecoders.cs, Ryujinx.Graphics.Shader/Instructions/InstEmit.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitConditionCode.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitFlowControl.cs, Ryujinx.Graphics.Shader/Instructions/InstEmitIntegerComparison.cs
Implements 2 shader instructions, CSET and CSETP. CSETP was already implemented, but it was a very incomplete and partial implementation, which was good enough for most games but not all of them. This change implements a more complete and more correct implementation.
Fixes textures on Persona 4 Golden.
Before:
After:
=> Implement CSET and CSETP shader instructions

Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs
Some variables in the GAL threading layer are used between threads, such as the command count and consumer pointer, and they assumed that memory accesses were totally ordered. ARM CPUs can reorder reads and writes in a way that could cause these accesses to provide incorrect results, which was causing a few weird issues with the command queue on A64 MacOS. (generally resulting in a random crash)
This change marks reads that need correct ordering as explicitly volatile. This is already in the `macos1` build.
=> Use volatile read/writes for GAL threading

Ryujinx.Ava/AppHost.cs, Ryujinx.Ava/UI/Renderer/EmbeddedWindow.cs, Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs, Ryujinx.Ava/UI/Windows/TitleUpdateWindow.axaml.cs
This PR fixes :
- A screenshot path issue introduced in a recent PR (#4240), which currently doesn't allow users to take screenshots because of a malformed path.
- After the refactoring of `TitleUpdateManager` (#4276), if the JSON is malformed, it reset the internal field but not the file itself. If an update file doesn't exist anymore, it doesn't appear in the UI but still exist in the JSON file. This is now fixed.
- After the refactoring of `Renderer` (#4297), in `_wndProcDelegate` some fields are tested without taking care of the message send to the window, this is now fixed.
=> Ava UI: Various Fixes

Ryujinx.Graphics.Gpu/Engine/Twod/TwodClass.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs
Expected targets:
- Deltarune Chapter 1+2
- Crash Team Racing
- Those new pokemon games idk (reset scale after battle/menu?)
This won’t help all games- for example SMTV issues. This might also be an aggressive solution, so it would be good to test if this has negative effects in other games.
I won’t be able to complete this for a bit so testing would help me make a decision when I can.
=> Allow setting texture data from 1x to fix some textures resetting randomly

Ryujinx.Ava/Input/AvaloniaKeyboardDriver.cs
On macOS, one often has the bell noise when using a keyboard as a controller.
Here we propose a fix to this by swallowing the TextInputEvent when it bubbles back up to MainWindow if Handled wasn't set during tunnelling.
We don't do this on KeyDownEvent because we want TextInputEvent to occur.
Comments very welcome.
=> AvaloniaKeyboardDriver: Swallow TextInput events to avoid bell on macOS

ARMeilleure/ARMeilleure.csproj, ARMeilleure/CodeGen/Arm64/CodeGenCommon.cs, ARMeilleure/CodeGen/Arm64/CodeGenerator.cs, ARMeilleure/Translation/PTC/Ptc.cs, Ryujinx.Tests/Cpu/Arm64CodeGenCommonTests.cs
* O(1) algorithm for determining bit immediates.
* Detect when bit immediates are usable for materalizing constants.
* Very minor improvement in performance on arm64.
=> Arm64: Simplify TryEncodeBitMask and use for constants

Ryujinx.Ava/Program.cs, Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs
For some reason if Config.json is corrupted and contains only { }
JsonSerializer.Deserialize is not validating json against a schema.
ConfigurationFileFormat.TryLoad will return true but ConfigurationState.Instance.Load will throw an exception
It will prevent crash on launch of Ryujinx and improve the user experience
=> Handle parsing of corrupt Config.json and prevent crash on launch

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/Instructions.cs
According to the spec, the operands of bitfield operations can have any integer types, but because MoltenVK uses SPIRV-Cross to translate the shader to MSL, and it does not take into account the integer type, if the types does not matter the MSL built-in function types, the Metal shader will be invalid and won't compile. This change the integer types to what the Metal compiler expects.
Contributes to #4062 even though this one is not listed there.
=> SPIR-V: Change BitfieldExtract and BitfieldInsert for SPIRV-Cross

ARMeilleure/CodeGen/CompiledFunction.cs, ARMeilleure/Instructions/NativeInterface.cs, ARMeilleure/Translation/PTC/Ptc.cs, ARMeilleure/Translation/TranslatedFunction.cs, ARMeilleure/Translation/Translator.cs
This allows us to get rid of a call to `Marshal.GetFunctionPointerForDelegate`. Should make translating new functions a little bit faster on the JIT, but it's unlikely to give any noticeable improvements in practice.
=> Remove use of GetFunctionPointerForDelegate to get JIT cache function pointer

Ryujinx.Graphics.Vulkan/AutoFlushCounter.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/PipelineFull.cs, Ryujinx.Graphics.Vulkan/Queries/BufferedQuery.cs, Ryujinx.Graphics.Vulkan/Queries/CounterQueue.cs, Ryujinx.Graphics.Vulkan/Queries/CounterQueueEvent.cs, Ryujinx.Graphics.Vulkan/Queries/Counters.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs, Ryujinx.Graphics.Vulkan/Window.cs
Vulkan seems to complain when the queries are reset on another command buffer. No idea why, the spec really could be written better in this regard. This fixes complaints logged by the validation layers, and hopefully any implementations that care extensively about them.
This change _guesses_ how many queries need to be reset and resets as many as possible at the same time to avoid splitting render passes. If it resets too many queries, we didn't waste too much time - if it runs out of resets it will batch reset 10 more.
The number of queries reset is the maximum number of queries in the last 3 frames. This has been worked into the AutoFlushCounter so that it only resets up to 32 if it is yet to force a command buffer submission in this attachment.
This is only done for samples passed …
=> Vulkan: Reset queries on same command buffer

Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForApplication.cs
This implements `LoadOpenContext` which is supposed to return a `IManagerForApplication`. Not sure why I assumed it doesn't return anything before.
This fixes a crash on multi-game collections that uses `LoadOpenContext`. It would crash after launching one of the games if it called a function that uses `IManagerForApplication` because it would be null.
Fixes Prinny Presents NIS Classics Volume 1: Phantom Brave: The Hermuda Triangle Remastered / Soul Nomad & the World Eaters and other games with a similar issue.
This also fixes a crash on Prinny Presents NIS Classics Volume 3: La Pucelle: Ragnarok / Rhapsody: A Musical Adventure when trying to exit from the games back to the title selection.
=> Implement Account LoadOpenContext

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs
Fixes a regression caused by #4202 which caused GLSL shaders to fail to compile because with this change, fragment outputs might now have integer types, however when assigning from a float variable, it would not insert the variable because internally the code generator assumed it had a float type. This change updates the code to use the correct fragment output type.
Fixes games rendering to integer textures on OpenGL.
Before:
After:
=> Insert bitcast for assignment of fragment integer outputs on GLSL

Ryujinx.Graphics.Vic/Blender.cs, Ryujinx.Graphics.Vic/Image/SurfaceReader.cs, Ryujinx.Graphics.Vic/Image/SurfaceWriter.cs
As the title says. Additionally improves `ReadNv12` on x86 a bit (4 OR instructions instead of 8).
Contributes to #4062 even though this one is not listed there.
=> Accelerate NVDEC VIC surface read/write and colorspace conversion with Arm64 HW intrinsics

Ryujinx.Ava/AppHost.cs
This change makes the render loop behave the same as the one in GTK.
=> Ava: Add ChangeVSyncMode() call to render loop

Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, Ryujinx.Graphics.Gpu/Engine/Threed/RenderTargetUpdateFlags.cs, Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClass.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, Ryujinx.Graphics.Gpu/Image/TextureInfo.cs, Ryujinx.Graphics.Gpu/Image/TextureManager.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.Gpu/Image/TextureSearchFlags.cs, Ryujinx.Graphics.Gpu/Window.cs
Because NVN aligns the width of the textures for copy and render, matching textures by size exactly on the texture cache does not always work. The texture entry on the texture pool always have the correct size, but render and copy textures do not, so cases where a texture was rendered or copied, and then later accessed on a shader would not work if we simply checked if the width of the texture matches with the one on the cache.
To make this case work we currently change the texture size when it is accessed on the shader. This is done with a `ChangeSize` method that under the hood creates a new texture, copies the old texture data to the new one, then handles re-creating all child views as needed. This not only adds unneeded complexity, but it's also a source of bugs. The main goal of this …
=> Handle mismatching texture size with copy dependencies

Ryujinx.Graphics.Gpu/Image/AutoDeleteCache.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs
#4211 fixed memory leaks on a few games that have a specific texture/render target usage pattern. However this approach caused regressions on a few OpenGL games, that's what River City Girls Zero looks like on master right now for example:
This changes reverts the changes on the linked PR and instead solves the problem using a different approach. It introduces a hard limit on the size (in bytes) of the `AutoDeleteCache`. Before it would start deleting textures if the amount of textures in the cache was above a given limit (currently 2048 textures). Now in addition to this limit, it also deletes if the total size is above 512 MB. To make sure it will keep at least the currently used textures in the cache, there's also a lower bound, it won't delete if there are less than 32 textures in the …
=> Limit texture cache based on total texture size

Ryujinx.Graphics.Vulkan/PipelineConverter.cs, Ryujinx.Graphics.Vulkan/PipelineFull.cs, Ryujinx.Graphics.Vulkan/Queries/BufferedQuery.cs, Ryujinx.Graphics.Vulkan/TextureView.cs
Fixes the following validation errors:
- Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06042 ] Object 0: handle = 0x2eff7599310, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x5c3a371 | vkCreateGraphicsPipelines() pCreateInfo[0]: VkRenderPass 0xbf26f100000002f5[] subpass 0 has colorAttachmentCount of 8 which doesn't match the pColorBlendState->attachmentCount of 1. The Vulkan spec states: If renderPass is not VK_NULL_HANDLE, and the pipeline is being created with fragment output interface state, and the subpass uses color attachments, the attachmentCount member of pColorBlendState must be equal to the colorAttachmentCount used to create subpass (https://vulkan.lunarg.com/doc/view/1.3.231.1/windows/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-060 …
=> Fix some Vulkan validation errors

Ryujinx.Graphics.Vulkan/AutoFlushCounter.cs, Ryujinx.Graphics.Vulkan/PipelineFull.cs
The AutoFlushCounter would flush command buffers on any attachment change (write mask or bindings change) if there was a pending query. This is to get query results as soon as possible for draw skips, but it's assuming that a full occlusion query _pass_ happened, that we want to flush it's data before getting onto draws, rather than the queries being randomly interspersed throughout a pass that also draws.
Xenoblade 2 repeatedly switches between performing a samples passed query and outputting to a render target on each draw, and flips the write mask to do so. Flushing the command buffer every 2 draws isn't ideal, so it's best that we only do this if the pattern matches the large block style of occlusion query. Since #4329 this got a lot more expensive.
This change makes this flush only …
=> Vulkan: Flush command buffers for queries less aggressively

Ryujinx.Graphics.OpenGL/Program.cs
These are infrequent enough that I think it's worth dumping any errors into the log. They also keep causing graphical glitches, and the only indication that anything went wrong is a debug log that is never enabled.
=> Log shader compile errors with Warning level

Ryujinx.HLE/HOS/Services/Hid/HidServer/HidUtils.cs, Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
While testing the game Kingdom Rush [0100A280121F6000], I noticed Ryujinx would crash in HidUtils.GetIndexFromNpadIdType() because the game was requesting an unknown NPad ID. The data the game actually sends is:
[0] 0x1d635b53
[1] 0x00000000 (Player1)
This PR adds extra `IsValidNpadIdType()` checks to ignore these unknown values. It also improves the logic of `IsValidNpadIdType()` a bit and makes it more centralized to other functions within IHidServer (for example, where the check used to be just `nPadId >= 0`
With this change the game now boots fine
I assume the game is not expecting HID service to return `ResultCode.InvalidNpadIdType` because if I do then it breaks execution
=> Better filtering of invalid NPadIds when games request unknown supported players

Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Graphics.Vulkan/TextureView.cs
I was forcing some types of texture to partially update when investigating performance with games that stream in data, and noticed that partially loading texture data was really broken on both backends.
Fixes Vulkan partial texture upload by getting the correct expected size for the texture. Fixes partial texture upload on both backends for both Texture 2D Array and Cubemap using the wrong offset and always uploading to the first layer/level for a handle. 3D might also be affected.
This might fix textures randomly having incorrect data in games that render to it - jumbled in the case of OpenGL, and outdated/black in the case of Vulkan. This case typically happens in UE4 games.
=> Fix partial updates for textures.

Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/PipelineDynamicState.cs
This fix validation error [VUID-vkCmdSetViewport-viewportCount-arraylength](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdSetViewport-viewportCount-arraylength).
Testing is advised to check for any regressions.
=> vulkan: Do not call vkCmdSetViewport when viewportCount is 0

Ryujinx.Graphics.Vulkan/BufferManager.cs, Ryujinx.Graphics.Vulkan/MemoryAllocator.cs, Ryujinx.Graphics.Vulkan/TextureStorage.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
This started as an attempt to remove `vkGetPhysicalDeviceMemoryProperties` in `FindSuitableMemoryTypeIndex` (As this could have some overhead and shouldn't change at runtime) and turned in a little bigger cleanup.
=> vulkan: Clean up MemoryAllocator

Ryujinx.Graphics.Vulkan/HardwareCapabilities.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/PipelineConverter.cs, Ryujinx.Graphics.Vulkan/VulkanInitialization.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
We were hardcoding alignment to 4, but by specs it can be any values that is a power of 2.
This also enable VK_KHR_portability_subset if present as per specs requirements. ([VUID-VkDeviceCreateInfo-pProperties-04451](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkDeviceCreateInfo-pProperties-04451))
=> vulkan: Respect VK_KHR_portability_subset vertex stride alignment

Ryujinx.Ava/Modules/Updater/Updater.cs, Ryujinx/Modules/Updater/Updater.cs
As I was checking for Linux exclusive Updater issues in Avalonia, I noticed a lot of suggestions in the files.
Even after this small refactor they still have a lot of remaining suggestions/warnings, but since we plan on replacing the Updater anyway, I didn't want to bother fixing everything.
I mostly cared about setting the correct permissions on the extracted files on Linux and it turns out we never used the file permissions present in the archive.
Aside from that I also made small typo corrections.
(The diff of this PR looks horrible, sorry about that!)
---
Thanks to @piplup55 for telling me about this issue!
=> GUI: Small Updater refactor & Set correct permissions on Linux when extracting files

Ryujinx.Graphics.Gpu/Image/TextureCache.cs
There are some cases where texture pool entries are completely invalid and would contain garbage. Those cases would usually have a invalid GPU virtual address too which would prevent the texture from being created. But since #4394, an attempt is made to create the texture even if the start address is unmapped ("invalid"), to allow sparse textures to work. This change is adds additional validation to prevent an attempt of calculating the texture size with invalid dimensions, which causes exception.
This fixes a regression caused by the linked PR on SSBU while using ARCropolis mods.
=> Validate dimensions before creating texture

ARMeilleure/Memory/IMemoryManager.cs, ARMeilleure/Signal/NativeSignalHandler.cs, Ryujinx.Cpu/AppleHv/HvMemoryManager.cs, Ryujinx.Cpu/IVirtualMemoryManagerTracked.cs, Ryujinx.Cpu/Jit/MemoryManager.cs, Ryujinx.Cpu/Jit/MemoryManagerHostMapped.cs, Ryujinx.Cpu/MemoryEhMeilleure.cs, Ryujinx.Graphics.Gpu/Image/Pool.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Graphics.Gpu/Memory/Buffer.cs, Ryujinx.Graphics.Gpu/Memory/BufferCache.cs, Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs, Ryujinx.Graphics.Gpu/Memory/ResourceKind.cs, Ryujinx.Memory.Tests/MockVirtualMemoryManager.cs, Ryujinx.Memory.Tests/MultiRegionTrackingTests.cs, Ryujinx.Memory.Tests/TrackingTests.cs, Ryujinx.Memory/AddressSpaceManager.cs, Ryujinx.Memory/IVirtualMemoryManager.cs, Ryujinx.Memory/Tracking/AbstractRegion.cs, Ryujinx.Memory/Tracking/MemoryTracking.cs, Ryujinx.Memory/Tracking/MultiRegionHandle.cs, Ryujinx.Memory/Tracking/RegionHandle.cs, Ryujinx.Memory/Tracking/SmartMultiRegionHandle.cs, Ryujinx.Memory/Tracking/VirtualRegion.cs, Ryujinx.Tests/Memory/MockMemoryManager.cs
Some games (namely Mario + Rabbids Sparks of Hope) uses buffer clears to clear texture data. This PR change buffer clears to clear the data on both guest and host GPU memory. That way, when the texture data is loaded from guest memory, it loads the correct data rather than memory garbage. In addition to that, memory tracking is signalled to indicate to the textures that the data has been modified. The memory tracking region handles was modified to store a "ID", which represents resource kinds. This is used to enable us to signal all resources *except* buffers, since in this case we clear the data on both GPU and guest memory, there's no need to reload buffer data.
Fixes black screen on Mario + Rabbids Sparks of Hope.
Before:
After:
=> Clear CPU side data on GPU buffer clears

Ryujinx.Graphics.Gpu/Engine/InlineToMemory/InlineToMemoryClass.cs
This change makes sure that the texture data has the latest CPU modifications before setting the new data, and marks the texture as modified for Inline-To-Memory copies, similar to what it does on DMA copies. I'm not sure why I didn't do that originally, but it is required to ensure correctness in case the texture was modified from CPU prior to the operation, or is accessed from CPU after (and was not modified from GPU before).
This fixes some graphical issues on Tanuki Justice that were apparently introduced on #3610.
Before:
After:
This only affects games using OpenGL on the Switch. Testing on those games is welcome.
Fixes #4448.
=> Mark texture as modified and sync on I2M fast path

Ryujinx.Memory/Range/NonOverlappingRangeList.cs, Ryujinx.Memory/Range/RangeList.cs
I noticed that in Xenoblade 2, the game can end up spending a lot of time adding and removing tracking handles. One of the main causes of this is actually splitting existing VirtualRegions, which does the following:
- Remove existing VirtualRegion from list
- Update existing VirtualRegion to end at split address, create new VirtualRegion starting at split address
- Add updated VirtualRegion (left) to list
- Add new VirtualRegion (right) to list
This costs 1 deletion and 2 insertions. When there are more VirtualRegions, this gets a lot more expensive, as insertions are done by copying all values to the right, and deletions by copying values to the left.
This PR simply allows it to look up the VirtualRegion being split, and replace its entry with the new end address without insertion or …
=> Memory: Faster Split for NonOverlappingRangeList

Ryujinx.Common/Configuration/AppDataManager.cs
This change makes Ryujinx more consistent with other apps on macOS. This PR also implements automatic migration of Ryujinx data from the old path to the new one, whenever Ryujinx detects the old data directory exists, but the new one does not.
=> Move Ryujinx Folder from ~/.config to ~/Library/Application Support on macOS

Ryujinx.Common/ReleaseInformation.cs
This allows changing base application directory behavior at build time via FORCE_EXTERNAL_BASE_DIR.
This is intended to be used by nixpkgs and flathub builds.
I also added the missing patch for macOS that we have on macos1 to avoid invalidating code signature.
=> misc: changes base application directory behaviour

Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs
This is fixing a regression caused by #4364 that caused some data loss because it would render to a texture with a slightly incorrect size, causing some pixels on the right side to be missing. The problem is caused because the render target texture size is in samples, not "pixels", while the scissor size is in pixels. This is fixed by multiplying the scissor size used as hint by the amount of samples in each direction. Technically this issue already existed before, but apparently with the previous way of handling size mismatches, it was not a problem (or at least, not in this specific case).
Before:
After:
Fixes #4396.
=> Account for multisample when calculating render target size hint

Ryujinx.Ava/Modules/Updater/Updater.cs, distribution/macos/create_app_bundle.sh, distribution/macos/create_macos_release.sh, distribution/macos/updater.sh
This is a very basic updater but should be enough for now.
As we cannot replace ourself while running (otherwise we could get killed because our codesigning get invalidated), the update flow is a bit different. We use a bash script to replace the application and relaunch it.
I also did a bit of refactoring around to make InstallUpdate more readable.
=> macos: Add updater support

Directory.Packages.props, Ryujinx.Common/Logging/Logger.cs, Ryujinx.Common/Ryujinx.Common.csproj, Ryujinx.Common/SystemInterop/StdErrAdapter.cs, Ryujinx.Common/SystemInterop/UnixStream.cs
Redirect stderr output into logging system.
This allows for easier mvk/mesa debugging since stderr will now show up in log files.
Extracted from #4227.
=> Logging: Redirect StdErr into logging system

Ryujinx.Graphics.Vulkan/HardwareCapabilities.cs, Ryujinx.Graphics.Vulkan/PipelineState.cs, Ryujinx.Graphics.Vulkan/VulkanInitialization.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
Normally, primitive restart is only allowed on *strip and *fan topology types on Vulkan. However, the `VK_EXT_primitive_topology_list_restart` allows it to be used on the remaining topology types, which matches what OpenGL supports. This PR allows primitive restart to be enabled in those cases, but only if the GPU/driver supports the extension.
Fixes  sand in Zelda Skyward Sword (on GPUs that supports the extension, which is most of them, but unfortunately MoltenVK doesn't).
Before:
After:
Fixes #4477.
=> Vulkan: Support list topology primitive restart

Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/IpAddressSetting.cs, Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/WinSockHelper.cs
The error codes for MacOS are very different to how they are on windows or linux. An alternate mapping is used when the host operating system is MacOS.
This PR also defaults IsDhcpEnabled to true when interfaceProperties.DhcpServerAddresses is not available.
This change was already in `macos1`.
=> Sockets: Properly convert error codes on MacOS

ARMeilleure/CodeGen/Arm64/PreAllocator.cs, ARMeilleure/CodeGen/PreAllocatorCommon.cs, ARMeilleure/CodeGen/X86/PreAllocator.cs, ARMeilleure/CodeGen/X86/PreAllocatorSystemV.cs, ARMeilleure/CodeGen/X86/PreAllocatorWindows.cs, ARMeilleure/Translation/PTC/Ptc.cs
This has two changes. The first commit is just minor refactoring renaming some functions with names that better match what they do. It also moves OS-specific functions to separate files on x86. For Arm64, moving them is not necessary as all operating systems follows the same ABI there.
The second commit is an optimization. It avoids the insertion of copies to copy the function argument values into a separate register. Instead it just propagates the argument value into each use site to avoid copies. This was already being done for Arm64, so this change is just doing the same for x86.
Sample diff on Windows.
Before:
```nasm
0:  53                      push   rbx
1:  48 83 ec 40             sub    rsp,0x40
5:  48 89 cb                mov    rbx,rcx
8:  48 89 d9                mov    rcx,rbx …
```
=> CPU: Avoid argument value copies on the JIT

.github/workflows/flatpak.yml, .github/workflows/release.yml, global.json
This PR ports the python scripts @marysaka previously used to automatically update the Ryujinx flatpak to GitHub Actions.
This should help to keep dependencies better in sync and will hopefully help to break flatpak builds a bit less.
@marysaka's scripts did most of the work here and I only needed to do the little work to port this.
=> [Flatpak] Add release github workflow

ARMeilleure/CodeGen/Arm64/CodeGenContext.cs, ARMeilleure/CodeGen/RegisterAllocators/LinearScanAllocator.cs, ARMeilleure/Decoders/DecoderHelper.cs, ARMeilleure/Decoders/OpCodeTable.cs, Ryujinx.Audio/Common/AudioDeviceSession.cs, Ryujinx.Ava/UI/Windows/IconColorPicker.cs, Ryujinx.Graphics.Vulkan/Queries/Counters.cs, Ryujinx.Graphics.Vulkan/SpecInfo.cs, Ryujinx.Graphics.Vulkan/Window.cs, Ryujinx.HLE/HOS/Ipc/IpcHandleDesc.cs, Ryujinx.HLE/HOS/Ipc/IpcMessage.cs, Ryujinx.HLE/HOS/Kernel/Common/KTimeManager.cs, Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZoneContentManager.cs, Ryujinx.Input.SDL2/SDL2GamepadDriver.cs, Ryujinx.Memory.Tests/MockVirtualMemoryManager.cs
Miscellaneous performance tweaks:
- remove the use of LINQ in a hot path
- use `Array.Empty<T>()` to avoid allocating 0-byte arrays
- adjust some for loops so that the JIT will elide bounds checking
=> Misc performance tweaks

Directory.Packages.props, Ryujinx.Graphics.Vulkan/Ryujinx.Graphics.Vulkan.csproj, Ryujinx.Input/Motion/CemuHook/Client.cs, Ryujinx.Input/Motion/CemuHook/Protocol/Header.cs, Ryujinx.Input/Ryujinx.Input.csproj
We had some leftovers from Vulkan support release that were around.
I also took that opportunity to use System.IO.Hashing instead of Crc32.NET in Ryujinx.Input.
=> misc: Some dependencies cleanup

Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
Fixes a regression from https://github.com/Ryujinx/Ryujinx/pull/4177 where the window couldn't access the timezone list in the ViewModel.
=> Increase access permissions for AvaloniaList<Timezone>

Ryujinx.Ava/Ryujinx.Ava.csproj, distribution/macos/create_app_bundle.sh, distribution/macos/create_macos_release.sh
This should add support for space in any path causing build errors mentioned in #4434
```
git clean -fdx; sh -x ./distribution/macos/create_macos_release.sh /Users/timezlicer/test\ build/Ryujinx /Users/timezlicer/test\ build/Ryujinx/temp /Users/timezlicer/test\ build/Ryujinx/output /Users/timezlicer/test\ build/Ryujinx/distribution/macos/entitlements.xml 1.1.0-macos `git log | head -1 | cut -c8-14` 2>&1 | tee output.txt
```
Tested with the above
[output.txt](https://github.com/Ryujinx/Ryujinx/files/10798097/output.txt)
---
Fixed merge conflict from #4464
=> Misc: Support space in path on macOS distribution

Ryujinx.Graphics.Gpu/Engine/Threed/SemaphoreUpdater.cs, Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs, Ryujinx.Graphics.OpenGL/Pipeline.cs, Ryujinx.Graphics.OpenGL/Queries/BufferedQuery.cs, Ryujinx.Graphics.OpenGL/Queries/CounterQueue.cs, Ryujinx.Graphics.OpenGL/Queries/CounterQueueEvent.cs, Ryujinx.Graphics.OpenGL/Queries/Counters.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/Queries/BufferedQuery.cs, Ryujinx.Graphics.Vulkan/Queries/CounterQueue.cs, Ryujinx.Graphics.Vulkan/Queries/CounterQueueEvent.cs
Counter results were being scaled on ReportCounter, which meant that the _total_ value of the counter was being scaled. Not only could this result in very large numbers and weird overflows if the game doesn't clear the counter, but it also caused the result to change drastically.
This PR changes scaling to be done when the value is added to the counter on the backend. This should evaluate the scale at the same time as before, on report counter, but avoiding the issue with scaling the total.
I've also included a fix for the 64-bit result partially being written. Drivers tend to write the low half first, then the high half. Now, we retry if the high half is 0xFFFFFFFF. This fixes counter results reading as 0 randomly (game was interpreting 0xFFFFFFFF00000000 as 32-bit uint), which turned …
=> GPU: Scale counter results before addition

Ryujinx.Cpu/Tracking/CpuRegionHandle.cs, Ryujinx.Graphics.GAL/Target.cs, Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureCache.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Graphics.Gpu/Image/TexturePool.cs, Ryujinx.Graphics.Texture/LayoutConverter.cs, Ryujinx.Memory/Range/MultiRange.cs
Sparsely mapped textures are useful when a game wants texture data to cover a large area (say, an entire level), but loading the whole thing would take up too much memory. You can load and unload parts of the texture by mapping physical pages into the texture's virtual memory allocation in GPU address space, and unmapping them when you're finished. This way, you only pay for the pages you use.
Ryujinx's way of handling sparsely mapped textures was to delete their pool references entirely when _any_ mapping change happened, as the texture cache would simply recreate it the next time it was used. This works, but is slow, especially if your game has mapped several 48MB textures in this way, and changes mappings mid-game.
This PR adds the ability to migrate a texture to a new set of physical …
=> Update range for remapped sparse textures instead of recreating them

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Graphics.Gpu/Image/TextureGroupHandle.cs
Texture group handles must store a list of their overlapping views, so they can be properly notified when a write is detected, and a few other things relating to texture readback. This is generally created when the group is established, with each handle looping over all views to find its overlaps. This whole process was also done when only a single view was added (and no handles were changed), however...
Sonic Frontiers had a huge cubemap array with 7350 faces (175 cubemaps * 6 faces * 7 levels), so iterating over both handles and existing views when adding a new one added up very fast (potentially 50 million iterations to add the final views). Since we are only adding a single view, we only need to _add_ that view to the existing overlaps, rather than recalculate them all.
This greatly …
=> GPU: Fast path for adding one texture view to a group

Ryujinx.HLE/HOS/Horizon.cs, Ryujinx.HLE/HOS/Kernel/KernelConstants.cs, Ryujinx.HLE/HOS/Kernel/KernelStatic.cs, Ryujinx.HLE/HOS/Kernel/Process/CapabilityExtensions.cs, Ryujinx.HLE/HOS/Kernel/Process/CapabilityType.cs, Ryujinx.HLE/HOS/Kernel/Process/KHandleTable.cs, Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs, Ryujinx.HLE/HOS/Kernel/Process/KProcessCapabilities.cs, Ryujinx.HLE/HOS/Kernel/Process/ProcessCreationFlags.cs, Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs, Ryujinx.HLE/HOS/ProgramLoader.cs, Ryujinx.HLE/HOS/Services/ServerBase.cs, Ryujinx.HLE/Loaders/Executables/KipExecutable.cs
This PR introduces a new KernelConstant `SupervisorCallCount` which gets used to make sure we are not setting SVCs that are out of range.
Since the amount of SVCs increased with firmware version 15.0.0, I also increased the size of `SvcAccessMask` to make room for them.
Additionally an enum (`CapabilityType`) was introduced along with some common operations in `CapabilityExtensions` to make the code a little bit more readable.
As a result of this PR the homebrew menu (using `hbl.nsp`) can now be launched again!
---
~~I'm planning on adding the logic for `MapRegion` capabilities, which is why this PR is currently marked as a draft.~~
Nvm, it seems `MapRegion` is mostly unused and is probably not worth the effort required to support it for now.
If you still want me to add it before …
=> Update syscall capabilites to include SVCs from FW 15.0.0

Ryujinx.HLE/HOS/Services/ServerBase.cs
This small PR is supposed to fix a regression introduced by #4537.
@riperiperi noticed this:
> _sessionHandles can be modified from other threads, before it would be converted to array then copied, but now it will create an array with the current size, then error out if it copies and it changed to be larger.
At first I used two locks for `_sessionHandles` and `_portHandles`, but thought it might be better to just ensure we are only copying the handles we reserved space for even if the size of the lists change.
I'm not quite sure which approach is better, so feel free to tell me to change it to locks (or something else I'm not thinking of).
=> Avoid copying more handles than we have space for

Ryujinx.Graphics.Gpu/Image/Texture.cs, Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, Ryujinx.Memory/Range/MultiRange.cs
This removes the `MinAddress` and `MaxAddress` properties, that were unused, so it was just wasting memory and time calculating those, and renames `GetSlice` to `Slice` to be consistent with other APIs.
=> Remove MultiRange Min/MaxAddress and rename GetSlice to Slice

ARMeilleure/ARMeilleure.csproj, ARMeilleure/CodeGen/X86/Assembler.cs, ARMeilleure/CodeGen/X86/AssemblerTable.cs, ARMeilleure/CodeGen/X86/HardwareCapabilities.cs, ARMeilleure/CodeGen/X86/IntrinsicTable.cs, ARMeilleure/CodeGen/X86/X86Instruction.cs, ARMeilleure/Instructions/InstEmitSimdLogical.cs, ARMeilleure/Instructions/InstEmitSimdLogical32.cs, ARMeilleure/Instructions/InstEmitSimdMove32.cs, ARMeilleure/IntermediateRepresentation/Intrinsic.cs, ARMeilleure/Optimizations.cs, ARMeilleure/Translation/PTC/Ptc.cs
Continuation of https://github.com/Ryujinx/Ryujinx/pull/3663
This PR addresses an issue in register-indexing, register-designations, and other issues the original PR was found to have.
`vpternlogd` is now utilized for `mvn`, `orn`, and `not`
=> ARMeilleure: Add initial support for AVX512 (EVEX encoding) (cont)

.github/workflows/release.yml
Adds a step to the release GitHub action to tag the commit with the release's version number
This will make it easier for people to correlate their release versions with commits on GitHub.
=> CI: add a version tag to correlate release versions with commits

ARMeilleure/CodeGen/X86/HardwareCapabilities.cs
Protection for the `xgetbv` instruction for systems that do not support `xcr0` such as nehalem processors.
The `XSAVE` cpuid indicates support for `XSAVE`, `XRESTOR`, `XSETBV`, `XGETBV` while `OSXSAVE` indicates if the operating system itself has `XSAVE` turned on. Both must be checked at the same time.
Addresses issues like #4583
=> ARMeilleure: Check for `XSAVE` cpuid flag for AVX{2,512}

Ryujinx.HLE/HOS/Services/Nim/IShopServiceAccessServerInterface.cs
The game passes a transfer memory to the service, since the handle was never closed, it would cause the transfer memory to be mapped forever. If the game tried to call this more than once, the second transfer memory map would fail causing the game to crash.
Fixes crash on SD Shin Kamen Rider Ranbu.
=> Fix handle leak on IShopServiceAccessServerInterface.CreateServerInterface

Ryujinx.Graphics.Gpu/Image/TexturePool.cs
This is fixing a regression from #3754 where textures would not be updated if they are from the short cache. I don't know if not calling `SynchronizeMemory` was intentional or not (I'm assuming that it wasn't).
Fixes #4339.
=> Update short cache textures if modified

Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, Ryujinx.Graphics.Gpu/Engine/Threed/IbStreamer.cs
Before, inline index buffer updates were done one index at a time. This means that, on the most common case, where 2 16-bit indices are uploaded, it would be doing many small 8 byte buffer uploads (since it expands the index size to 32-bits regardless of the original size). This is extremely inefficient, and although the OpenGL NVIDIA driver can cope with it, on Vulkan it was extremely slow.
With this change, the uploads are batched, and it can now submit up to 256 indices (1024 bytes, 1KB) at a time (before it was up to 4, 2 on the common case of 16-bit indices).
Before:
https://user-images.githubusercontent.com/5624669/227070650-cd33c309-c089-48ea-985c-66f2fe9357e8.mp4
https://user-images.githubusercontent.com/5624669/227070451-5d085082-4bc4-4278-bb56-2c0520b86d36.mp4
After: …
=> Batch inline index buffer update

Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, Ryujinx.Graphics.Vulkan/EnumConversion.cs, Ryujinx.Graphics.Vulkan/FramebufferParams.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/TextureStorage.cs
Newer NVIDIA GPUs seem to be able to start clearing render targets before the last rasterization task is completed, which can cause it to clear a texture while it is being sampled.
This change adds a barrier from read to write when doing a clear, assuming it has been sampled in the past. It could be possible for this to be needed for sample into draw by some GPU, but it's not right now afaik.
This should fix visual artifacts on newer NVIDIA GPUs and driver combos. Contrary to popular belief, Tetris® Effect: Connected is not affected. Testing welcome, hopefully should fix most cases of this and not cost too much performance.
=> Vulkan: Insert barriers before clears

Ryujinx.Graphics.Vulkan/VulkanInitialization.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
It was only called in one place, that can be simplified.
=> vulkan: Remove CreateCommandBufferPool from VulkanInitialization

Directory.Packages.props
nuget: bump XamlNameReferenceGenerator from 1.5.1 to 1.6.1
---
This PR combines dependency updates from:
- #4455 
- #4593 
- #4594 
---
Tested on Linux without issues.
=> nuget: bump Avalonia dependencies from 0.10.18 to 0.10.19

Ryujinx.Common/Configuration/Hid/Controller/GamepadInputId.cs, Ryujinx.Common/Configuration/Hid/Controller/StickInputId.cs, Ryujinx.Common/Configuration/Hid/KeyboardHotkeys.cs
This PR allows previous config versions to be parsed correctly again.
=> Fix missing string enum converters for the config

Ryujinx.HLE/Loaders/Processes/ProcessLoaderHelper.cs, Ryujinx.HLE/Loaders/Processes/ProcessResult.cs
This PR reads the `Name` for ProcessResult from the NACP, so `Name` contains the title name which is more a lot more useful to know when we receive logs from users.
The title name will be logged in the language chosen by the user.
=> hle: Set ProcessResult name from NACP

Ryujinx.Graphics.Vulkan/MemoryAllocator.cs, Ryujinx.Graphics.Vulkan/VulkanInitialization.cs, Ryujinx.Graphics.Vulkan/VulkanInstance.cs, Ryujinx.Graphics.Vulkan/VulkanPhysicalDevice.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
That clean up a bit of duplicate logic and avoid querying for stuffs everywhere.
Also move to use an HashSet to store extensions string and use Span instead of unsafe pointers when possible.
=> vulkan: Cleanup PhysicalDevice and Instance querying

Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Common/AtomicStorage.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Common/ISampledData.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Common/ISampledDataStruct.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Common/RingLifo.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/DebugPad/DebugPadState.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Keyboard/KeyboardModifier.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Keyboard/KeyboardState.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Mouse/MouseState.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Npad/NpadCommonState.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Npad/NpadGcTriggerState.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Npad/SixAxisSensorState.cs, Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/TouchScreen/TouchScreenState.cs
There are 7 structs used to hold input device data. These structs implemented interface `ISampledData` so that `AtomicStorage<T>` could access a `ulong SamplingNumber` field. C# implicitly boxes value types any time they are accessed through an interface, resulting in an allocation. These input device structs are so heavily used that on this developer's machine it results in between 30,000-40,000 boxing memory allocations _per second_ while a game is running.
This PR eliminates all of these allocations by:
- replacing the `ISampledData` interface with `ISampledDataStruct`
- `ISampledDataStruct` contains no instance members - it is a "marker interface" only.
- `ISampledDataStruct` is used to constrain static method `ISampledDataStruct.GetSamplingNumber(ref T sampledDataStruct)`, which …
=> Eliminate boxing allocations caused by ISampledData structs

ARMeilleure/Decoders/OpCodeTable.cs
This implements the remaining HINT instructions. Those are reserved encodings that can be used by future CPUs, and executes as NOP on older CPUs that do not support the instructions. This is used by some Pointer Authentication instructions on newer CPUs that some homebrew uses.
Fixes #4656.
=> Implement remaining Arm64 HINT instructions as NOP

Ryujinx/Ui/GLRenderer.cs
This is the smallest PR I ever created, but I can't find another one where it would fit as well.
This fixes an issue where people would sometimes experience crashes if the switch instance wasn't set up yet or an invalid file was loaded which didn't initialize it at all.
=> [GUI] Fix a NRE in Gtk when disposing GLRenderer

Ryujinx.Ava/UI/Applet/AvaHostUiHandler.cs
Fixes an issue in https://github.com/Ryujinx/Ryujinx/issues/3662 where content dialogs would not be spawned if the window was minimized or otherwise lost focus by the user.
=> Avalonia - Force activate parent window before dialog is shown

ARMeilleure/Instructions/InstEmitSystem.cs, ARMeilleure/Instructions/InstEmitSystem32.cs, ARMeilleure/Instructions/NativeInterface.cs, ARMeilleure/State/ExecutionContext.cs, ARMeilleure/State/NativeContext.cs, ARMeilleure/Translation/Delegates.cs, ARMeilleure/Translation/PTC/Ptc.cs
Some games access these system registers several tens of thousands of times in a second from many different threads. While this isn't really crippling, it is a lot of wasted time spent in a reverse pinvoke transition.
Example games are Pokemon Scarlet/Violet and BOTW. These games have a lot of different potential bottlenecks so it's unlikely you will see a consistent improvement, but it definitely disappears from the cpu profile.
=> ARMeilleure: Move TPIDR_EL0 and TPIDRRO_EL0 to NativeContext

Ryujinx.Graphics.Vulkan/AutoFlushCounter.cs, Ryujinx.Graphics.Vulkan/PipelineBase.cs, Ryujinx.Graphics.Vulkan/SyncManager.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
The AutoFlushCounter class was added to periodically flush Vulkan command buffers throughout a frame, which reduces latency to the GPU as commands are submitted and processed much sooner. This was done by allowing command buffers to flush when framebuffer attachments changed.
However, some games have incredibly long render passes with a large number of draws, and really aggressive data access that forces GPU sync.
The Vulkan backend could potentially end up building a single command buffer for 4-5ms if a pass has enough draws, such as in BOTW. In the scenario where sync is waited on immediately after submission, this would have to wait for the completion of a much longer command buffer than usual.
The solution is to force command buffer submission periodically in a "fast flush" mode. This …
=> Vulkan: add situational "Fast Flush" mode

Ryujinx.Ava/AppHost.cs, Ryujinx.HLE/Loaders/Processes/ProcessResult.cs, Ryujinx/Ui/RendererWidgetBase.cs
This restores the behavior we had before #4480 to read title names in case the name of the desired language is empty.
=> HLE: Deal with empty title names properly

Ryujinx.Ava/UI/Applet/SwkbdAppletDialog.axaml.cs
Fixes an issue in https://github.com/Ryujinx/Ryujinx/issues/3662 where the software keyboard in Avalonia does not populate any example text the game provides such as default character names etc.
Before:
After:
=> Avalonia - Move swkbd message null check into constructor

Ryujinx.Headless.SDL2/Program.cs
Caused by the recent application loader changes.
Should also make the PTC progress being logged now.
=> Fix a crash in Ryujinx.Headless.SDL2 when loading an app

Ryujinx.Ava/AppHost.cs, Ryujinx.Ava/Assets/Locales/en_US.json, Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs, Ryujinx.Ava/UI/Views/Settings/SettingsNetworkView.axaml, Ryujinx.Common/Utilities/NetworkHelpers.cs, Ryujinx.HLE/HLEConfiguration.cs, Ryujinx.HLE/HOS/Services/Nifm/StaticService/IGeneralService.cs, Ryujinx.HLE/HOS/Services/Nifm/StaticService/Types/IpAddressSetting.cs, Ryujinx.Headless.SDL2/Options.cs, Ryujinx.Headless.SDL2/Program.cs, Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs, Ryujinx.Ui.Common/Configuration/ConfigurationState.cs, Ryujinx/Ui/MainWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.cs, Ryujinx/Ui/Windows/SettingsWindow.glade
I thought this was added to master ages ago and didn't realize it was still missing.
Thank you to @shadowninja108 for making me aware of this.
This is almost 1:1 taken from the LDN build with some minor adjustments and the addition of the lan-interface-id parameter for `Ryujinx.Headless.SDL2`.
=> [GUI] Add network interface dropdown

Ryujinx.Graphics.Vulkan/Effects/FsrScalingFilter.cs, Ryujinx.Graphics.Vulkan/Effects/FxaaPostProcessingEffect.cs, Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
This changes the method used for clear for the SMAA filter textures. Instead of using the helper shader, it calls the clear method on `PipelineBase` directly, which uses `vkCmdClearAttachments`. This fixes a crash on Intel GPUs when using the SMAA filter. I still need to investigate why `HelperSHadeer.Clear` crashes on Intel, since some games will use that.
I also cleaned up the code a bit and removed some things that doesn't make sense (like setting viewport and scissor before a compute dispatch ???).
Testing is welcome to ensure the SMAA filter is still working as before.
=> Change SMAA filter texture clear method

Ryujinx.Graphics.Vulkan/HashTableSlim.cs
Really small optimization: since we've already calculated the hash for the input pipeline state, we can use it to eliminate mismatching pipelines within the same hashtable bucket a lot faster.
This mostly helps when there are a lot of pipeline variants for a shader collection.
=> Vulkan: HashTableSlim lookup optimization

Directory.Packages.props
Reverts Ryujinx/Ryujinx#4686
The newer version of Silk.NET is not working on macOS, it can't find MoltenVK, so reverting until the problem is investigated and fixed (either own our or Silk.NET side).
Fixes #4689.
=> Revert "chore: Update Silk.NET to 2.17.1"

Ryujinx.Common/Memory/SpanReader.cs, Ryujinx.Horizon/LogManager/Ipc/LmLogger.cs
This PR introduces a new method on `SpanReader` that ensures the length of the span is valid, so it does not try to get a span that is larger than the buffer size. This fixes a crash on Rune Factory 4 Special on newlywed mode when talking with your spouse (at least, that's the only instance where it was reported). While I was testing this change, I made it log the invalid size. The size specified is 1024 bytes, but the remaining buffer size is just 956 bytes. The `LogDataChunkKey` is `Message`. The message appears correct, but the end is truncated, which *might* indicate that the size *was* supposed to be 1024 bytes?
In any case, LM is stubbed in production firmware, so that would not cause issues on a retail Switch, I think this safer behaviour to avoid crash with invalid lengths is …
=> Avoid LM service crashes by not reading more than the buffer size

Ryujinx.Input/Motion/MotionInput.cs
Don't know why this is here.
It just seems to set the filter to an identity. Which then quickly returns to where it's supposed to be anyways.
Fixes #4366
=> Removed MotionInput Calibration

Ryujinx.Graphics.GAL/Capabilities.cs, Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Gpu/Shader/GpuAccessorBase.cs, Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/Instructions.cs, Ryujinx.Graphics.Shader/IGpuAccessor.cs, Ryujinx.Graphics.Vulkan/HardwareCapabilities.cs, Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
There seems to be a bit of a disagreement on how textureGather should select texels when it is exactly half way between them. On BOTW, this tie breaks incorrectly for AMD and Intel on windows on both Vulkan and OpenGL, but correctly on NVIDIA, Apple and mesa drivers.
This is most noticeable in BOTW, where the difference in texel choice breaks the shadows in the game with a weird looking misalignment. A small positive bias causes the instruction to return the correct texels, so I decided to make it determine and add the smallest bias it possibly could.
This PR adds a capability that reveals both the sub texel precision and whether it should be used to bias textureGather. In OpenGL this is assumed, because I don't think it's reported.
This needs to apply after scaling (and with unscaled …
=> Shader: Bias textureGather instructions on AMD/Intel

Ryujinx.Ava/UI/ViewModels/AmiiboWindowViewModel.cs, Ryujinx/Ui/Windows/AmiiboWindow.cs
This PR addresses an issue where some people were unable to use the amiibo window, as it would fail to download the json in time before the timeout cancels the task.
In addition to that all the catch-blocks and other error paths are now logging the error, so when people upload their logs, we can at least figure out what's going wrong.
Thank you to `imDemon#8151` who greatly assisted me while I was trying to figure this out!
---
Fixes #4614
=> UI: Fix amiibo issues & log errors and exceptions

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/CodeGenContext.cs, Ryujinx.Graphics.Shader/CodeGen/Spirv/Declarations.cs, Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, Ryujinx.Graphics.Shader/Translation/TranslatorContext.cs
Transform feedback is a feature that writes the VTG stages output into a buffer. It is possible to write different output components to different offsets into that buffer. To make that work, instead of declaring a `vec4` as output, the emulator breaks that down into 4 individual `float` outputs. The problem is that drivers (other than NVIDIA) usually have problems with this for some reason, resulting in weird bugs, so I made #3832 to address this.
When there are consecutive outputs that are supposed to be written into consecutive buffer offsets, it just "joins" them and makes a vector. The problem is that right now, this is only done when the draw has no fragment shader, because for the cases where it does have a fragment shader, the VTG outputs would not match the fragment shader inputs. …
=> Use vector transform feedback outputs with fragment shaders

Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs
This implements the remap functionality that the DMA engine has. It is more or less like a shuffle, and can be used to re-order components on the pixels of a texture for example. The OpenGL driver uses it to perform BGRA -> RGBA texture data conversion in a few cases.
Fixes inverted red and blue on 20XX and Dragon Quest Builders, maybe other OpenGL games too.
**Dragon Quest Builders:**
Before:
After:
**20XX (title screen):**
Before:
After:
**20XX (in-game):**
Before:
After:
NVN uses remap in a few cases too, but not as a shuffle, it only enables it to increase the copy size. In any case, it might be worth to test NVN games just to ensure there's no regression.
=> Implement DMA texture copy component shuffle

Ryujinx.HLE/HOS/Kernel/Ipc/KServerSession.cs, Ryujinx.HLE/HOS/Kernel/Threading/KAddressArbiter.cs, Ryujinx.HLE/HOS/Kernel/Threading/KConditionVariable.cs, Ryujinx.HLE/HOS/Kernel/Threading/KSynchronization.cs, Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs
Because `ArbitrateLock` was not checking `TerminationRequested` for the current thread, it would wait for the lock even if the thread was already terminated, which would cause the thread to never exit (since the thread that owns the lock is most likely already terminated as well and has exited).
This should fix one of the instances of the emulator freezing when you stop emulation or close, it will not fix *all* of them since they are caused by different issues. Also it's hard to test this since this specific only happens if you close exactly when a guest thread call `ArbitrateLock`, but before the function gets a chance to run.
I also replaced all usages of the pattern `ShallBeTerminated || SchedFlags == ThreadSchedState.TerminationPending` with the `TerminationRequested ` property, and …
=> Add missing check for thread termination on ArbitrateLock

Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, Ryujinx.Graphics.Shader/Translation/TranslatorContext.cs
This fixes a regression from #4565 that caused the geometry shader generated to pass the `gl_Layer` value to pass the wrong values. The problem was caused by the rather confusing `Load` method that I added that takes a "primitive vertex", "vector index" and "element index". For user inputs/outputs, the first value should be the *location*, the second one should be the primitive vertex on geometry shaders, and the third one should be the element index. For arrays, the order changes, and first becomes the "primitive vertex", then the "array index" and lastly the "element index" (if the array entry type is a vector). The parameters where named after the array case, so it is rather confusing for the more common case where we have separate vectors with different location.
Fixes green-ish tint …
=> Fix geometry shader layer passthrough regression

distribution/macos/create_app_bundle.sh, distribution/macos/create_macos_release.sh
This was missed in #4725.
---
Fixes #4737
=> Fix paths and typos for macOS scripts

src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs, src/Ryujinx.Ava/UI/Windows/MainWindow.axaml, src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs, src/Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs, src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs, src/Ryujinx.Ui.Common/Configuration/Ui/WindowStartup.cs, src/Ryujinx/Ui/MainWindow.cs
Based on #4439 with support for Avalonia. 
As the two frameworks fight over data types and the like, GTK is given priority for now. It will be a quick job to edit and expand upon once deprecated e.g. WindowState could start in fullscreen instead of just maximised etc.
CC @HaizenTrist
=> Allow window to remember its size, position and state (GTK + Avalonia)

src/Ryujinx.Graphics.Gpu/Image/Texture.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCache.cs, src/Ryujinx.Graphics.Gpu/Image/TexturePool.cs, src/Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs, src/Ryujinx.Graphics.Gpu/Memory/UnmapEventArgs.cs, src/Ryujinx.Memory/Range/MemoryRange.cs, src/Ryujinx.Memory/Range/MultiRange.cs
This PR fixes a few issues introduced by the sparse texture PR #4442, and also some others that might not have been caught previously.
- Fixes an error where a pool entry and memory mapping changing at the same time could cause a texture to rebind its data from the wrong GPU VA (data swaps).
- This should fix most issues cause by that PR.
- Introduces "remap actions" which can be performed after a gpu mapping has completed. These can be added to when handling the event before the mapping occurs.
- Fixes an error where the texture pool could act on a mapping change before the mapping has actually been changed. ("Unmapped" event happens before change, we need to signal it changed _after_ it completes)
- "Unmapped" event adds to the partial mapping list, "remap action" signals pool mapping …
=> GPU: Fix errors handling texture remapping

src/Ryujinx.Graphics.Gpu/Image/AutoDeleteCache.cs, src/Ryujinx.Graphics.Gpu/Image/Texture.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCache.cs
Occasionally games are very wasteful and clear/write to a texture without ever sampling it. As rendered textures in NVN games seem to mostly have overlapping memory ranges (they are temporary), the texture will eventually get overwritten.
Normally, this would trigger a removal from the auto delete cache, but a pool entry would keep the texture alive. This is important so that games don't recreate all of their render targets every frame. However, with these textures that are never used, they will get deleted immediately and recreated on the next frame. This might also happen with textures that are rendered then copied somewhere else, as that also won't use a pool entry.
Because of the incompatible overlap, there won't be a data upload, but both OpenGL and Vulkan have costs when creating …
=> GPU: Keep rendered textures without any pool references alive

src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs, src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml.cs, src/Ryujinx.HLE/HOS/ModLoader.cs, src/Ryujinx.HLE/Loaders/Processes/Extensions/LocalFileSystemExtensions.cs, src/Ryujinx.HLE/Loaders/Processes/Extensions/NcaExtensions.cs, src/Ryujinx/Ui/Widgets/GameTableContextMenu.cs, src/Ryujinx/Ui/Windows/CheatWindow.cs
This PR fixes an issue where the mod subdirectories had to be lowercase to be recognized by Ryujinx.
Before, this wouldn't be loaded without renaming `exeFS` to `exefs`.
(Screenshot by @piplup55)
These changes also allow for more nesting of the mod directories, but that's just a side-effect of the way it works now.
Aside from that some refactoring for the `ModLoader` class was done.
=> ModLoader: Fix case sensitivy issues

src/Ryujinx.Graphics.Vulkan/PipelineBase.cs
Our Vulkan backend inserts image barriers when a texture is sampled after it is rendered. This is done via a "modification flag" which is set when a render target is unbound (presuming that a texture has finished drawing to it).
Imagine the following scenario:
- Game sets render target to texture A
- Game renders to texture A
- (render pass ends)
- Game binds texture A to a sampler
- Game sets render target to texture B
- Renders to texture B using texture A (barrier required)
Because of the previous behaviour, the check to add a barrier for sampling a texture actually happens _before_ it is registered as modified, meaning no barrier was added at all. This isn't always the case, but it was definitely causing issues in Xenoblade 2.
This change adds the modification flag as soon as the …
=> Vulkan: Record modifications for barriers after changing the framebuffer

src/Ryujinx.Graphics.Gpu/Engine/Twod/TwodClass.cs, src/Ryujinx.Graphics.Gpu/Image/Texture.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCache.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, src/Ryujinx.Graphics.Gpu/Image/TextureSearchFlags.cs
This is a change to prevent some cases of invalid blits involving depth-stencil textures. Both OpenGL and Vulkan only allows blits with depth textures with the *exact same* format. And of course, they don't allow blits between depth and color textures.
From the Vulkan spec:
>  If either of srcImage or dstImage was created with a depth/stencil format, the other must have exactly the same format
From the OpenGL spec:
> GL_INVALID_OPERATION is generated if mask contains GL_DEPTH_BUFFER_BIT or GL_STENCIL_BUFFER_BIT and the source and destination depth and stencil formats do not match. 
So first, this disables the additional depth aliasing rules when searching for the destination texture in the cache. If the source texture is a depth texture, destination *must* also be depth. If it's color, it …
=> Fix some invalid blits involving depth textures

distribution/linux/Ryujinx.sh
=> fix: linux launcher breaks when there are spaces in the directory path

src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs, src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml.cs, src/Ryujinx.HLE/HOS/ModLoader.cs, src/Ryujinx.HLE/Loaders/Processes/Extensions/LocalFileSystemExtensions.cs, src/Ryujinx.HLE/Loaders/Processes/Extensions/NcaExtensions.cs, src/Ryujinx/Ui/Widgets/GameTableContextMenu.cs, src/Ryujinx/Ui/Windows/CheatWindow.cs
This PR contains a new commit that fixes #4780 by creating new instruction lists for every new cheat instead of clearing and share the same list.
---
Original PR: #4720
This PR fixes an issue where the mod subdirectories had to be lowercase to be recognized by Ryujinx.
Before, this wouldn't be loaded without renaming exeFS to exefs.
image
(Screenshot by @piplup55)
These changes also allow for more nesting of the mod directories, but that's just a side-effect of the way it works now.
Aside from that some refactoring for the ModLoader class was done.
=> ModLoader: Fix case sensitivy issues without breaking cheats

src/Ryujinx.Graphics.Gpu/Memory/Buffer.cs, src/Ryujinx.Graphics.Gpu/Memory/BufferCache.cs
Sometimes, constant buffer updates can't be avoided, either due to a cb0 access that cannot be eliminated, or the game updating a buffer between draws to the detriment of everyone.
To avoid uploading the full 4096 bytes each time, this PR remembers the offset and size containing all constant buffer updates since the last sync. It will then upload that range after sync. If a newly dirty range is too far from the existing range, it will trigger the old mechanism for forcing a buffer dirty.
This greatly reduces buffer upload bytes per frame in various games:
- BOTW korok forest: ~3.0MB -> ~1.6MB
- Splatoon 2 1st level: ~1.1MB -> ~0.55MB
- These two games update a 65536 byte constant buffer between draws (100s of them) for their own purposes. The actual updates are around 16 bytes in size, …
=> GPU: Allow granular buffer updates from the constant buffer updater

src/Ryujinx.Graphics.OpenGL/HwCapabilities.cs
Fixes GPU vendor detection on Turkish systems where "NVIDIA Corporation" for example would become "nvıdıa corporation" and fail the check.
=> Use ToLowerInvariant when detecting GPU vendor.

src/Ryujinx/Ui/Windows/DlcWindow.glade, src/Ryujinx/Ui/Windows/TitleUpdateWindow.glade
When hovering over add , remove and removeall buttons in the dlc menu, it says the adds updates , removes updates. Changed to dlc.
=> Correct tooltips for add,remove,removeall buttons

src/Ryujinx.Ava/Common/ApplicationHelper.cs, src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml, src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs, src/Ryujinx/Ui/Widgets/GameTableContextMenu.cs
There is currently a crash if the updated NCA doesn't contain the section we want to extract, this is fixed by adding an extra check.
I have fixed the inverted handler of ExeFs/Logo introduced in #4755 too.
Fixes #4521
=> UI: Fix sections extraction

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/GlobalToStorage.cs
This fixes a regression from #2237 where constant buffer access elimination would not work if the newly mapped storage slot didn't match up with the storage slot on hardware.
I've also changed it to work no matter what constant buffer the address is on.
=> Shader: Use correct offset for storage constant buffer elimination

src/Ryujinx.HLE/Loaders/Processes/ProcessResult.cs
This avoid giant copies being performed when being returned or passed.
=> misc: Switch ProcessResult to a class

src/Ryujinx.HLE/HOS/Horizon.cs, src/Ryujinx.HLE/HOS/Services/Time/Clock/Types/ContinuousAdjustmentTimePoint.cs, src/Ryujinx.HLE/HOS/Services/Time/TimeSharedMemory.cs
Last time we did an upgrade on the time service was during 9.x era, it was about time to take back that reverse again!
15.0.0 added a new structure on the shared memory to get steady clock raw timepoints with a granularity in nanoseconds.
This PR implements this new part.
I plan to write a follow up with a bit of refactoring of this ancient part of the emulator.
As always, reverse and work done by your truly.
This should also fix local and network clock returning 0 under usage with shared memory.
FIx https://github.com/Ryujinx/Ryujinx/issues/2430.
PS: As a reminder, if this change is reused anywhere else, work should be credited as Ryujinx and not my person.
=> time: Update for 15.0.0 changes and fixes long standing issues

src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs, src/Ryujinx.Ava/UI/Views/Settings/SettingsSystemView.axaml
During testing of #4822, Mary pointed out the way we calculate time offset is wrong in our Avalonia UI. This PR fixed that. The axaml file is autoformatted too.
=> Ava: Fix SystemTimeOffset calculation

src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/VertexBufferState.cs, src/Ryujinx.Graphics.Vulkan/VertexBufferUpdater.cs
This PR batches together vertex buffer updates to reduce the number of individual calls to update vertex buffers. It also avoids rebinding vertex buffers that have not changed, which is common when games are doing instanced rendering.
Improves performance slightly on BOTW on my system. Some areas bind more vertex buffers per draw than others.
Note that any improvement greatly depends on the game and the driver.
=> Vulkan: Batch vertex buffer updates

src/Ryujinx.Graphics.Vulkan/Auto.cs, src/Ryujinx.Graphics.Vulkan/BufferHolder.cs, src/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs, src/Ryujinx.Graphics.Vulkan/FenceHolder.cs, src/Ryujinx.Graphics.Vulkan/MultiFenceHolder.cs, src/Ryujinx.Graphics.Vulkan/PersistentFlushBuffer.cs
MultiFenceHolder is currently absolutely reliant on all users submitting to the _same command buffer pool_, which means they must all come from the same thread. This is because waitiers register the command buffer index, which is only valid for entries of the same pool. The locking and dictionary structures greatly slow down the process of binding and ref counting for _all types of buffer_, while also being unnecessary when these rules are followed.
This PR simplifies MultiFenceHolder in a few ways:
- `ReservedCommandBuffer.Waitables` is now a List for less overhead. Enforcing uniqueness is done by `MultiFenceHolder.AddFence` returning true only when the command buffer index is not yet registered on the waitable. Similarly, the call to Contains has been replaced with asking the waitable …
=> Vulkan: Simplify MultiFenceHolder and managing them

src/Ryujinx.Ava/AppHost.cs, src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs, src/Ryujinx.Headless.SDL2/Program.cs, src/Ryujinx/Ui/MainWindow.cs, src/Ryujinx/Ui/Windows/SettingsWindow.cs
This will allow in the future possible multiple driver selection without any need of LD preload. (useful when testing custom version of mesa for example)
=> vulkan: Pass Vk instance to VulkanRenderer

src/Ryujinx.Graphics.Vulkan/MoltenVK/MVKInitialization.cs
Command buffer errors currently trigger an exception "DeviceLost" crashing the process.
Looking at [MKV's code](https://github.com/KhronosGroup/MoltenVK/blob/53a4eb26f2fbd7322eb087eb4af263fe466543b0/MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm#L392-L408) we observe that:
- It hard fails if error is:
```
MTLCommandBufferErrorBlacklisted || MTLCommandBufferErrorNotPermitted || MTLCommandBufferErrorDeviceRemoved
```
- Otherwise fails conditionally if `config.resumeLostDevice == false` (current default)
For Ryujinx's use-case it's more graceful to resume on those errors rather than crashing the app, the error isn't totally silenced since `mvk` still logs it
Fixes #4704, #4575
- Users can currently workaround this by setting this env `MVK_CONFIG_RESUME_LOST_DEVICE=1`, but IMO this should be the …
=> fix(mvk): resumeLostDevice

src/Ryujinx.Horizon/Sdk/Sf/Cmif/ServerDomainManager.cs
Fixes a regression caused by #4803 that caused Animal Crossing New Horizons to hang when loading a save, because one of the BCAT service objects was not being disposed, and so future access would return `TargetLocked` errors forever.
Fixes #4877.
=> Fix missing domain service object dispose

src/ARMeilleure/Translation/Translator.cs
This fixes a potential issue that could happen if all guest threads exit, but there is still a background translation in flight on one of the background translation threads. In this situation, it would crash because some collections have already been disposed. This seems extremely rare since I never got it myself, but got a report of it happening from @AcK77.
=> Ensure background translation threads exited before disposing JIT

.github/workflows/build.yml, .github/workflows/release.yml, distribution/macos/create_macos_build.sh
This PR resolves #4836. This allows macOS users to get a release (or PR build) based on the current master.
Releases will also be able to use the updater, since @marysaka previously added support for that as well.
Additionally some changes to the release workflow have been made to take advantage of matrix strategies, which should help to shorten the time until people are able to update to the next version after a new push to master.
**Note**: We haven't upstreamed all macOS changes yet (see: #4062), so these releases won't work as well as the 1.1.0-macos1 build.
=> Update release workflow & Add jobs for macOS

src/Ryujinx.SDL2.Common/SDL2Driver.cs
This fixes #4828.
The problem was that SDL was inhibiting the display from sleeping even when a game was not running.  I added a hint to disable that SDL feature.  The normal behavior in `DisplaySleep.cs` will still apply and prevent sleep while a game is currently running.
=> Stop SDL from inhibiting sleep (#4828).

src/Ryujinx.Audio/Renderer/Dsp/Command/DelayCommand.cs, src/Ryujinx.Audio/Renderer/Dsp/Command/Reverb3dCommand.cs, src/Ryujinx.Audio/Renderer/Dsp/Command/ReverbCommand.cs, src/Ryujinx.Audio/Renderer/Dsp/DataSourceHelper.cs
This was always going to happens, as a result quadratic would break and move index after the channel count point, effectively breaking input/output indices.
Fixes TOTK audio but also possible newer game using quadratic.
I also fixed an index issue on reverb 3d early delay.
PS: As a reminder, if this change is reused anywhere else, work should be credited as Ryujinx and not my person.
=> amadeus: Fix wrong channel mapping check and an old typo

src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
This fixes a bug on the ASTC decoder that caused some ASTC texture to be corrupt and have white pixels where they shouldn't. Only affects GPUs that don't support ASTC natively (which is pretty much everything other than Apple Silicon and old Intel integrated GPUs).
Reference form the official decoder: https://github.com/ARM-software/astc-encoder/blob/0a3269f9de2b457dbeb7c5c6265e96c45b64647c/Source/astcenc_color_unquantize.cpp#L229
This fixes some texture corruption in The Legend of Zelda: Tears of the Kingdom.
Before:
After:
=> Fix incorrect ASTC endpoint color when using LuminanceDelta mode

src/Ryujinx.Audio/Renderer/Dsp/AudioProcessor.cs, src/Ryujinx.Audio/Renderer/Dsp/Command/DeviceSinkCommand.cs
Also add a simple Stereo to 5.1 change for device sink.
Tested against NES - Nintendo Switch Online that output stereo on the audio renderer.
Close https://github.com/Ryujinx/Ryujinx/issues/4422.
=> amadeus: Allow 5.1 sink output

src/Ryujinx.Ava/AppHost.cs, src/Ryujinx.Ava/UI/Controls/ApplicationListView.axaml, src/Ryujinx.Ava/UI/Helpers/NullableDateTimeConverter.cs, src/Ryujinx.Ava/UI/Models/Generic/LastPlayedSortComparer.cs, src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs, src/Ryujinx.Ui.Common/App/ApplicationData.cs, src/Ryujinx.Ui.Common/App/ApplicationLibrary.cs, src/Ryujinx.Ui.Common/App/ApplicationMetadata.cs, src/Ryujinx/Ui/MainWindow.cs
This should fix #2660 and make #2661 obsolete by changing the type of `ApplicationData`/`ApplicationMetadata`'s `LastPlayed` fields from string to nullable DateTime.
I fixed most the problems that cropped up after the change and added a value converter for Avalonia as well as a new readonly property `ApplicationData.LastPlayedString` for the GTK UI.
The one big problem that remains is that after the change, Ryujinx will consider old metadata.json files invalid and reset everything but the title back to default. I'm working on a solution that allows for a graceful migration but I wanted to submit the PR now to get feedback regarding the rest.
=> Changed LastPlayed field from string to nullable DateTime

src/Ryujinx.Ava/Modules/Updater/Updater.cs, src/Ryujinx/Modules/Updater/UpdateDialog.cs
After running the updater for Ryujinx and clicking Yes to restart, I am greeted with an error message:
> The application was unable to start correctly (0xc0000142).
> Click OK to close the application.
I then have to manually start Ryujinx to finish the update.  This PR changes the way that Ryujinx is launched after an update to fix this error.
=> Fix the restart after an update.

src/Ryujinx.Graphics.Gpu/GpuContext.cs, src/Ryujinx.Graphics.Gpu/Image/Texture.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCache.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, src/Ryujinx.Graphics.Gpu/Image/TextureInfo.cs, src/Ryujinx.Graphics.Gpu/Image/TextureViewCompatibility.cs
@gdkchan pointed out that UI textures in TOTK seemed to be setting their texture swizzle incorrectly (texture was RGB but was sampling A, swizzle for A was wrong), so I determined that SwizzleComponentMatches was the problem and set on eliminating it. This PR combines existing work to select the most recently modified texture (now used when selecting which aliased texture to use) with some additional changes to remove the swizzle check and support aliased view creation.
The original observation (#1538) was that we wanted to match depth textures for the purposes of aliasing with color textures, but they often had different swizzle from what was sampled (as it's generally the identity swizzle once rendered). At the time, I decided to allow swizzles to match if only the defined components …
=> GPU: Remove swizzle undefined matching and rework depth aliasing

src/Ryujinx.Graphics.Vulkan/PipelineLayoutFactory.cs
There's a bug with MoltenVK where binding a storage buffer more than once with different stage flags causes resource usage to register incorrectly, which causes the command buffer to fail. There's more information here: https://github.com/KhronosGroup/MoltenVK/issues/1870
This PR partially works around this issue by setting the storage buffer usage flags to all active stages when running under MVK. This means that it will always register the buffer with all possible stages it can be used on.
This can still break if there are non-rasterizing draws, which generally happens with TFB games. Working around that is a lot more involved, and it's probably not worth it when we don't have TFB emulation anyways.
This should be removed when the issue is fixed in MoltenVK.
=> Vulkan: Partially workaround MoltenVK InvalidResource error

src/Ryujinx.Ava/Input/AvaloniaMouseDriver.cs
https://github.com/Ryujinx/Ryujinx/issues/3662#issuecomment-1544744756 report an issue when you goes fullscreen, it's because we remap mouse button to a Ryujinx enum, but we used `-1` on the passed arg for a strange reason. I've removed it and added an extra check in case `MouseButton.None` is used to fix it.
=> Ava: Fix wrong MouseButton

.github/workflows/build.yml, distribution/macos/create_macos_build.sh
- macOS builds were not being named correctly; as a result, the updater couldn't find them. This PR brings them in line with the convention for Ava builds.
- Removes publishing for x86 Mac builds on PR runner.
- Adjust capitalisation `MacOS` -> `macOS`, `universal` -> `Universal`
=> macOS CI Adjustments

src/Ryujinx.Graphics.OpenGL/Image/TextureView.cs, src/Ryujinx.Graphics.OpenGL/Window.cs
This fixes what appears to be a regression from #4711. It binds a buffer to `PixelPackBuffer` to perform a texture to buffer copy, but it never "clears" it back to 0, which means the buffer will remain bound there. When taking a screenshot on the emulator, `glReadPixels` would try to copy the data into that buffer since it's still bound and fail. That caused screenshots to be completely black on games where this texture flush is triggered.
Fixes #4918.
May fix #4919 but that also mentions a camera issue that I did not check.
=> Set OpenGL PixelPackBuffer to 0 when done

.github/workflows/build.yml, .github/workflows/flatpak.yml, .github/workflows/nightly_pr_comment.yml, .github/workflows/release.yml
Currently more workflows than usual run for an extremely long amount of time without actually doing anything.
This PR will cause these workflows to be cancelled a lot earlier by setting a timeout of 35 minutes per job.
We still need to restart them after that, but at least they won't run for 24 hours or until anyone notices it.
=> Add timeout of 35 minutes to workflow jobs

src/Ryujinx.Graphics.Vulkan/BufferHolder.cs
This PR retunes the buffer migration system to map buffers that are written significantly more than they are read back on device, rather than on host.
NVIDIA GPUs seem to have a lot of trouble mapping a storage buffer for write in a ton of places throughout a frame, probably because it has to ensure coherency every time. Unfortunately we can't seem to disable that, so using host buffers always has a large hidden cost when using a storage buffer in a lot of places. TOTK does a lot of storage writes from _fragment_ of all things, in many different places.
This causes a small performance regression in BOTW, but a big performance boost in TOTK. This is due to reading from device memory being uncached. There may be a better solution to this problem.
=> Vulkan: Device map buffers written more than flushed

src/Ryujinx.Ava/AppHost.cs, src/Ryujinx/Ui/RendererWidgetBase.cs
This PR fixes a bug where the hide cursor mode wasn't applied correctly if the cursor wasn't moved.
The bug only affected Avalonia, but I found a few other small issues within Gtk that were addressed as well.
Thank you to @jojodunet for notifying me about this issue!
=> [GUI] Fix always hide cursor mode not hiding the cursor until it was moved

distribution/macos/updater.sh
The updater still seems to be erroring when replacing installed folder under normal operations.
Will attempt to address that separately as it's not easy to debug locally.
=> macos: Fix relaunch with updater when no arguments were provided to the emulator

src/Ryujinx.Ava/Common/ApplicationHelper.cs
Tested against Omega Strickers.
=> ava: Fix crash when extracting sections from NCA with no data section

src/Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, src/Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs
In the depths area, Tears of the Kingdom uses a global memory access with address on constant buffer slot 6. This isn't standard and thus doesn't actually have a size 8 bytes after it, so we were reading back a garbage size that ended up very large (at least in version 1.1.0), and would synchronize a lot of data per frame.
This PR makes storage buffers created from addresses outside constant buffer slot 0 get their size as the number of bytes remaining in the GPU mapping starting at the given virtual address. This should bound the buffer to a reasonable size, and ideally stop it crossing into other memory.
=> GPU: Avoid using garbage size for non-cb0 storage buffers

src/Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, src/Ryujinx.Graphics.Vulkan/HelperShader.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs
On Vulkan, there are a few cases where blit operations are "emulated" using regular draws. Those cases would take the texture component swizzle into account, which is incorrect as swizzle does not affect blits or rendering, they are only supposed to affect regular texture sampling from shaders. This fixes the issue by adding a new `SetTextureAndSamplerIdentitySwizzle` that is now used to bind a `ImageView` with identity (RGBA) swizzle.
Fixes colors flashing on Omega Strikers.
Before:
https://github.com/Ryujinx/Ryujinx/assets/5624669/5acd0beb-2288-4c61-a3d0-e593b63821a2
After:
https://github.com/Ryujinx/Ryujinx/assets/5624669/d10613e3-96b4-413b-89b1-d9d0d5cf54ac
=> Fix Vulkan blit-like operations swizzle

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/Optimizer.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/Utils.cs
This change removes a somewhat redundant pattern on the shader, cause by some code produced by the compiler for perspective correction on fragment shaders. Basically the compiler uses the "Multiply" mode on the IPA instruction for those inputs. The multiplier is `1.0 / gl_FragCoord.w`. To counter-act this, the emulator insert a multiplication by `gl_FragCoord.w` for perspective inputs, and the end result is a `(x * gl_FragCoord.w) * (1.0 / gl_FragCoord.w)`. This is adding an additional step that can recognize an eliminate this pattern.
Sample diff:
Before:
```glsl
// 0x000010: 0xE003FF87CFF7FF09 Ipa
// 0x000018: 0x508000000047090D Mufu
temp_0 = 1.0 / gl_FragCoord.w;
// 0x000028: 0xE043FF8A00D7FF04 Ipa
temp_1 = in_attr2.x * gl_FragCoord.w;
temp_2 = temp_1 * temp_0;
```
After:
```glsl
// …
```
=> Eliminate redundant multiplications by gl_FragCoord.w on the shader

distribution/macos/updater.sh
`lsof` will return a non-zero exit code if the process with the given PID does not exist (i.e., already closed), causing the script to fail. We should wait till we're moving stuff around to do error checking.
=> Fix macOS Update Script

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/Instructions.cs
Sometimes games were emitting implicit LOD texture sampling instructions, which are invalid on anything except fragment, as only fragment can calculate implicit derivatives. Compute does have an implicit derivatives mode with an NV extension, though I think more would need to be done if the switch does actually support this, as it needs to select the mode used for that (linear/quads).
On AMD windows, this caused texture sampling from compute to fail. This caused gloom to malfunction in TOTK. Other drivers likely ignored the "implicit" part and just sampled LOD 0.
Testing is welcome to make sure nothing broke, and that it works on all AMD gpus.
=> SPIR-V: Only allow implicit LOD sampling on fragment

src/Ryujinx.Graphics.Gpu/Constants.cs, src/Ryujinx.Graphics.Gpu/Engine/Compute/ComputeClass.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, src/Ryujinx.Graphics.Vulkan/BufferManager.cs
#4999 limits the size of storage buffers used on graphics shaders, when the base address is not sourced from constant buffer 0, since in those cases the size of the buffer is usually not supplied, it's just a raw pointer. This PR is extending that change to compute shaders.
This fixes a regression on DOOM Eternal where the game would crash because it was trying to create very large buffers. The game is still not playable however due to the other existing issues.
I also added a log on Vulkan for when buffer creation fails, since it was failing silently and causing pretty confusing exceptions later on.
=> Limit compute storage buffer size

src/Ryujinx.HLE/HOS/Services/ServerBase.cs
@lostromb [commented](https://github.com/Ryujinx/Ryujinx/pull/4537#issuecomment-1477130450) on closed PR #4537 about an intermittent exception when stopping emulation. This PR fixes some issues I found while investigating, and though I was unable to reproduce @lostromb's reported exception, I believe this will fix it.
- ServerBase.Dispose() could be (and often was) called multiple times.
- ServerBase.Dispose() had no checks to ensure the ServerLoop() had stopped first.
- Reworked the port and session storage to use a Dictionary only, instead of a Dictionary and List
- Reworked the locking to use a ReaderWriterLockSlim, and made every access of the port and session stores thread-safe.
=> ServerBase thread safety

src/Ryujinx.HLE/HOS/ModLoader.cs
Very small PR to fix the names of mods in log files.
This should allow Ryuko to list mod names correctly again.
=> Fix mod names

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Translation/Rewriter.cs
Fixes a regression from #4714 that caused image operations to not have their coordinates scaled on the shader.
It was causing block flickering on Xenoblade Chronicles 3 title screen when using scale, and probably affected other games too.
=> Fix resolution scaling of image operation coordinates

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/Instructions.cs, src/Ryujinx.Graphics.Shader/IntermediateRepresentation/Operation.cs, src/Ryujinx.Graphics.Shader/StructuredIr/AstOperation.cs, src/Ryujinx.Graphics.Shader/StructuredIr/AstTextureOperation.cs, src/Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, src/Ryujinx.Graphics.Shader/StructuredIr/StructuredProgramContext.cs, src/Ryujinx.Graphics.Shader/Translation/Rewriter.cs
There are a few cases where shaders add a small constant value before doing a reciprocal (`1.0 / x`) operation, to avoid a division by zero. When generating instructions without the "precise" qualifier on SPIR-V, such operations would be allowed to undergo optimizations that may reduce its precision, and if the bias constant value is low enough (near zero), it might get rounded down to zero and become useless. In this scenario, a division by zero would occur and generate invalid values.
To prevent that scenario, this change forces the add operation on the pattern of `1.0 / (x + CONSTANT_BIAS)` to be precise, preventing the value from ever being 0 assuming `x` is not negative.
This fixes the The Legend of Zelda: Tears of the Kingdom having super bright characters on macOS in some cases. …
=> Force reciprocal operation with value biased by constant to be precise on macOS

src/Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs, src/Ryujinx.Ava/UI/Helpers/NotificationHelper.cs, src/Ryujinx.Common/AsyncWorkQueue.cs
I've experienced a lot of instances recently where Ryujinx.Ava would hang on exit, sometimes for so long that I'd open up Task Manager and kill it. It was always with Release builds and attaching the debugger didn't show much. It happened so often, I didn't imagine I should have tried harder because today, try as I might, I've had a real hard time getting it to happen so that I could investigate.
**Hang #1**
I finally got it to happen though, and with a Debug build too. I found one thread stuck waiting, started by `NotificationHelper.SetNotificationManager()` with `Task.Run()`. The thread itself does a simple foreach over a `BlockingCollection<Notification>` but it doesn't have an exit condition. This PR adds one via a `CancellationTokenSource`.
This uses the …
=> Ryujinx.Ava: fixes for random hangs on exit

.github/workflows/build.yml, .github/workflows/flatpak.yml, .github/workflows/nightly_pr_comment.yml, .github/workflows/release.yml
Since the workflows are currently timing out too early, we need to adjust the timeouts again.
But to make this easier to change in the future we will be using a config variable that can be set for the repo or for the whole org.
Before this PR gets merged we need to [create a variable](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository) `JOB_TIMEOUT` for this repo. I think a good start for the value would be `45` minutes.
=> Use variables to configure job timeouts

src/Ryujinx.Ava/AppHost.cs, src/Ryujinx/Ui/RendererWidgetBase.cs
The switch statement was not checking when the data folder was set to a custom path, but only when launch mode was portable.
---
Closes #5085
=> Added Custom Path case when saving screenshots

distribution/macos/updater.sh
In the current version of the `updater.sh` I had an issue, where the update was downloaded, but the Ryujinx.app never got replaced at first try.
I had a look at the script and found the following issue:
Because `set -e` is defined, every command with an exit status other than 0 will cause the script to stop.
In my case, the `lsof`command exited with a status > 0, because there seemed to be still fds open.
The `sleep 1` after that had no effect, because the script exited already.
My approach is to check if the PID still exists in the process table additionally to check for open fds.
If the process is closed correctly and has no open fds, the script continues like it has before.
There will be a 1 second delay until there is a new try (up to 5 times).
If it fails, the script will exit with …
=> Improve macOS updater

src/Ryujinx.Ava/Assets/Locales/en_US.json, src/Ryujinx.Ava/UI/Windows/AboutWindow.axaml, src/Ryujinx/Ui/Windows/AboutWindow.Designer.cs, src/Ryujinx/Ui/Windows/AboutWindow.cs
Add a really simple changelog link under the version number in the About dialog.
While waiting for the actual solution to show the changelog directly in the app (https://github.com/Ryujinx/Ryujinx/issues/3262), adding a link to open in the browser is the convenient way to check the changelog as of now.
=> About window: Add changelog link under ver. number

src/Ryujinx.Graphics.Vulkan/FormatCapabilities.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/PipelineState.cs
This fixes an oversight from #5094. The `Binding` value on the vertex attribute struct is not an index into the vertex descriptors array, it must match the actual vertex buffer `Binding` value. So I have changed the code and added a function to look for the binding return the correct vertex buffer index.
This fixes a regression on macOS where a few games would not render correctly due to it changing the format of some attributes to the wrong format. It only affect games that have gaps on the vertex buffer bindings, which is something uncommon. So far the only game I tested that was affected is Gun Gun Pixies.
=> Fix incorrect vertex attribute format change

src/Ryujinx.Graphics.Vulkan/PipelineBase.cs
On MoltenVK issuing a barrier in the middle of a render pass has no effect. So this ends the render pass as a work around. This fixes vertex explosions on Xenoblade on macOS (has to be tested with #5080 since the game uses transform feedback). This needs to be tested to ensure it does not regress performance on other games since render pass splits is every mobile GPU kryptonite.
Contributes to #4062.
=> Workaround for MoltenVK barrier issues

src/Ryujinx.Graphics.Vulkan/FramebufferParams.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/PipelineConverter.cs, src/Ryujinx.Graphics.Vulkan/PipelineState.cs, src/Ryujinx.Graphics.Vulkan/PipelineUid.cs
Having blend enabled for integer formats is invalid. The most common case where this happens is when logic operations are enabled, and in this case the blend is ignored. Since Metal/MoltenVK does not support logical operations, it is never enabled there, and having blend enabled in this case causes a Metal assert and crash. To avoid this, this change forces blend to be disabled if the respective framebuffer attachment is using a integer format.
This should be safe to enable for all vendors, but here I'm enabling it only on MoltenVK just to be on the safe side. But I can enable it for all vendors too.
Fixes crashes on Xenoblade games, and should fix also fix some crashes on Luigi's Mansion 3 (on macOS). The Luigi's Mansion 3 crash would usually happen when entering the bathroom on Luigi's …
=> Make sure blend is disabled if render target has integer format

src/Ryujinx.Headless.SDL2/Options.cs, src/Ryujinx.Headless.SDL2/Program.cs, src/Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj
- Make `use-hypervisor` nullable
- There is a long-standing bug in CommandLineParser that makes it impossible to disable a bool argument if it is set to true by default and is not nullable
- Properly sign headless builds so they can use Hypervisor
- Bundle MoltenVK in headless builds when building for macOS
- Force Vulkan on macOS
Other Potential Fixes:
- CommandLineParser can't seem to read macOS path strings with escaped spaces in them correctly
=> macOS Headless Fixes

src/Ryujinx.Graphics.Gpu/Shader/GpuAccessorBase.cs, src/Ryujinx.Graphics.Shader/Translation/ResourceManager.cs, src/Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, src/Ryujinx.Graphics.Shader/Translation/TranslatorContext.cs
This fixes a regression from #4646 that caused Borderlands 2 to crash before the title screen while generating a shader. It had an issue while trying to reconcile the bindings between the vertex A and B stages when they are combined. It would have missing bindings which would cause crashes later on as it would not be able to find the constant buffer from the binding when generating the SPIR-V or GLSL code. This change fixes the issue by using the same `ResourceManager` instance for both stages. This should be fine since they share the same constant buffers (and as consequence, also shares the same storage buffer and textures/images, since the base address for the storage buffer and handles for the textures also comes from constant buffers).
=> Share ResourceManager between vertex A and B shaders

src/Ryujinx.Ava/AppHost.cs, src/Ryujinx.Graphics.GAL/IRenderer.cs, src/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs, src/Ryujinx.Graphics.Gpu/GpuContext.cs, src/Ryujinx.Headless.SDL2/WindowBase.cs, src/Ryujinx/Ui/RendererWidgetBase.cs
Deferred actions from disposing physical memory instances always dispose the resources in their caches. The renderer can't be disposed before these resources get disposed, otherwise the dispose actions will not actually run (leaking memory), and the ThreadedRenderer may get stuck trying to enqueue too many commands when there is nothing consuming them (user must close console manually).
This should fix most instances of the emulator freezing on close.
Should fix #2863, should obsolete #5121. Needs a bunch of testing obviously.
=> GPU: Dispose Renderer after running deferred actions

src/Ryujinx.Graphics.GAL/ProgramPipelineState.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, src/Ryujinx.Graphics.Gpu/Shader/ShaderSpecializationState.cs, src/Ryujinx.Graphics.Vulkan/PipelineConverter.cs
Depth mode has been added to the pipeline state by #5027, but was not properly recorded for background compilation or shader caching, which would result in the pipeline compiled to mismatch on first draw, and have to compile another. This could cause additional stuttering.
This PR adds depth mode to the pipeline state and handles it in the converter. Since this already exists in the specialization state, it is always sourced from there when not available (but really, just always). In future it might be worth passing the read size of the struct to the method to decide to overwrite values based on that, for example if this state were to somehow become optional.
=> Vulkan: Include DepthMode in ProgramPipelineState

.github/workflows/build.yml
Small PR to only run one workflow per PR, since there may have been an [increase of running workflows](https://github.com/Ryujinx/Ryujinx/actions/workflows/build.yml?query=branch%3Ainput-refactor) in the last few minutes.
=> Only run one workflow for a PR at a time

src/Ryujinx.Common/Logging/Formatters/DefaultLogFormatter.cs, src/Ryujinx.Common/Logging/Formatters/DynamicObjectFormatter.cs, src/Ryujinx.Common/Logging/Formatters/ILogFormatter.cs, src/Ryujinx.Common/Logging/LogEventArgsJson.cs, src/Ryujinx.Common/Logging/Logger.cs, src/Ryujinx.Common/Logging/Targets/AsyncLogTargetWrapper.cs, src/Ryujinx.Common/Logging/Targets/ConsoleLogTarget.cs, src/Ryujinx.Common/Logging/Targets/FileLogTarget.cs, src/Ryujinx.Common/Logging/Targets/ILogTarget.cs, src/Ryujinx.Common/Logging/Targets/JsonLogTarget.cs, src/Ryujinx.Headless.SDL2/Program.cs, src/Ryujinx.Ui.Common/Configuration/LoggerModule.cs
This small PR adds a convenience method `PrintStack()` to log the current stacktrace in addition to the regular message.
I used this while I was debugging and think it'd be useful to upstream this as well.
=> [Logger] Add print with stacktrace method

src/Ryujinx.Ava/UI/Views/Main/MainViewControls.axaml
Adds an explicit height to the panel so that it won't grow/shrink when the show names checkbox is added/removed. 
Only tested on Win11 on windowed & full screen modes.
=> Fix Avalonia Library header changes size when switching between List/Grid view

src/Ryujinx.Ava/UI/Helpers/ContentDialogHelper.cs, src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
There is currently an issue while a game runs, the content dialog creation method check if `IsGameRunning` is true to show the popup. But the condition here is wrong (`window` is null) so it throw a NullException silently in `Dispatcher.UIThread`. This is now fixed by using the right casting.
=> ava: Fix exit dialog while guest is running.

src/Ryujinx.Graphics.GAL/Format.cs, src/Ryujinx.Graphics.Vulkan/Effects/FsrScalingFilter.cs, src/Ryujinx.Graphics.Vulkan/Effects/FxaaPostProcessingEffect.cs, src/Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs, src/Ryujinx.Graphics.Vulkan/FormatTable.cs
There's a bug on the FXAA and SMAA filters, where if the presentation texture has a BGRA format, it will create a intermediary BGRA texture, but bind it as a RGBA format. This causes the R and B components to be inverted once the filter is applied. It seems there was an attempt to correct that by inverting the R and B components on the swizzle, but that does nothing on *storage image operations*, at least on Vulkan.
This change fixes the issue by simply allowing the BGRA format to be bound directly as a storage image. Most vendors supports this. It also makes the code simpler and more efficient as we don't need to create a new view with different format.
Fixes the issue on Persona 4 Golden and any other game presenting BGRA textures, with FXAA and SMAA filters.
Before:
After:
Fixes #5193.
=> Allow BGRA storage images on Vulkan

src/ARMeilleure/Translation/Cache/JitCache.cs, src/ARMeilleure/Translation/Cache/JitCacheInvalidation.cs
Tested on Windows DevKit 2023 with #5184.
=> Armeilleure: Fix support for Windows on ARM64

src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
Currently, the `Open Applet` menu is still enabled when a guest is running, which is wrong. This is now fixed by refreshing the property binding on `IsEnabled`.
=> ava: Fix Open Applet menu enabled

src/Ryujinx.Ava/Input/AvaloniaMouseDriver.cs
There is currently a regression caused by #4900 where the wrong input touch is released. Since `Avalonia.Input.MouseButton` first entry is `None` and the `Avalonia.Input.PointerUpdateKind` first entry is `Left` we have to change the index of `MouseButton` in the released event handler. This is now fixed.
=> ava: Fix Input Touch

src/Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, src/Ryujinx.Graphics.Gpu/Image/TexturePool.cs, src/Ryujinx.Graphics.Texture/LayoutConverter.cs, src/Ryujinx.Graphics.Texture/SizeCalculator.cs
The size calculator methods deliberately reduce the gob size of textures if they are deemed too small for it. This is required to get correct sizes when iterating mip levels of a texture.
Rendering to a slice of a 3D texture can produce a 3D texture with depth 1, but a gob size matching a much larger texture. We _can't_ "correct" this gob size, as it is intended as a slice of a larger 3D texture. Ignoring it causes layout conversion to break on read and flush.
This caused an issue in Tears of the Kingdom where the compressed 3D texture used for the gloom would always break on OpenGL, and seemingly randomly break on Vulkan. In the first case, the data is forcibly flushed to decompress the BC4 texture on the CPU to upload it as 3D, which was broken due to the incorrect layout. In the …
=> Texture: Fix layout conversion when gobs in z is used with depth = 1

src/Ryujinx.Common/Utilities/TypedStringEnumConverter.cs
Stops Ryujinx from throwing out the whole config file if one enum has an invalid value (very annoying if you're working on a PR to add a new backend lol)
=> Dont Error on Invalid Enum Values

src/Ryujinx.Ava/UI/Controls/ApplicationGridView.axaml
Personally I found the center alignment for rows that are not full to look off. I updated the flexbox constraints so empty rows would left-align and the items would always line up with the rows above. 
**This is a subjective change, so I'm happy to make it an option in the settings somewhere if people would prefer.** 
Some examples of the difference: 
| Before                                                                                           | After                                                                                            |
|--------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------|
| …
=> Avalonia: Adjust Grid Library alignment

src/Ryujinx.Graphics.Texture/SizeCalculator.cs
When there is a remainder when dividing depth by gobs in z, it is used to remove the unused part of the 3D texture's size. This was done to calculate correct sizes for single slice views of 3D textures.
However, this case can also apply to 3D textures with many slices, and more than one total block of gobs in z. In this case it's meant to trim off the end of the level size. Most textures won't encounter this as their size will be aligned, but UE4 games tend to use 3D textures with funny unaligned sizes.
The size offset should have been applied to the level size instead of the slice size, and it should only affect the slice size if it ends up larger.
Hopefully should fix issues with UE4 games without breaking other stuff, I don't have much time to test.
=> Texture: Fix 3D texture size when totalBlocksOfGobsInZ > 1

src/Ryujinx.Graphics.Gpu/Engine/Compute/ComputeClass.cs
This fixes a "regression" caused by #4993 that introduced glitches on some games on Intel GPUs. Because we only know if there's a storage buffer with unaligned offset *after* we have the shader (since knowing which storage buffers are even used in the first places requires having the shader already translated), we need to re-fetch the shader once we know if any storage buffer is unaligned. While the existing code would correctly re-fetch the shader if the unaligned state changed, it would do so still using the old state, so it would return the same (incorrect) shader. This fixes the issue by updating `GpuChannelComputeState` with the new state.
This is a regression because the linked PR enables the optimization where we remove CB0 access to also work when host storage buffer offset …
=> Fix wrong unaligned SB state when fetching compute shaders

src/Ryujinx.HLE/FileSystem/ContentManager.cs, src/Ryujinx.Input/Motion/CemuHook/Client.cs
Benchmark:
```cs
[SimpleJob]
[MemoryDiagnoser]
[Orderer(SummaryOrderPolicy.FastestToSlowest)]
[RankColumn]
public class Test
{
private Dictionary<int, string> dict = new Dictionary<int, string>();
private int size = 1000;
private int keyToFind = 999;
[GlobalSetup]
public void Setup()
{
for (int i = 0; i < size; i++)
{
dict.Add(i, "aaa");
}
}
[Benchmark]
public void ContainsKeyPlusArrayLookup()
{
if (dict.ContainsKey(keyToFind))
{
var response = dict[keyToFind];
}
}
[Benchmark]
public void TryGetValue()
{
dict.TryGetValue(keyToFind, out var response);
}
}
```
Results:
```sh
|                     Method |      Mean |     Error |    StdDev |    Median | Rank | Allocated |
|--------------------------- |----------:|----------:|----------:|----------:|-----:|----------:|
| …
```
=> Prefer a 'TryGetValue' call over a Dictionary indexer access guarded by a 'ContainsKey'

src/Ryujinx.Ava/Modules/Updater/Updater.cs
This should fix a regression introduced by 1.1.869 where the macOS updater won't work anymore.
Because we use a `*.app` package, it isn't necessary to check if the user changed any files in this directory.
The updater for macos is designed, that it always replaces the whole package.
=> Fix regression in macOS updater

src/ARMeilleure/IntermediateRepresentation/Intrinsic.cs, src/Ryujinx.Graphics.Shader/Decoders/InstDecoders.cs, src/Ryujinx.Graphics.Shader/Decoders/InstProps.cs, src/Ryujinx.Graphics.Shader/Translation/AggregateType.cs, src/Ryujinx.HLE/HOS/Kernel/Threading/ThreadSchedState.cs
The `Flags` attribute in C# is used to indicate that an `enum` type is to be treated as a bit field; that is, a set of (binary) flags.
Without the `Flags` attribute, an `enum` is usually treated as a distinct set of values. For instance, you might define an `enum` to represent the days of the week, and each value in the `enum` (Sunday, Monday, etc.) is a distinct day.
However, in some cases, you want an `enum` where each value represents a different binary flag that can be combined with others. This is where the `Flags` attribute comes in.
For instance, consider an `enum` that represents a set of file permissions:
```cs
[Flags]
public enum FilePermissions
{
None = 0,
Read = 1 << 0, // Equivalent to 1
Write = 1 << 1, // Equivalent to 2
Execute = 1 << 2 // Equivalent to 4
}
```
The `Flags` …
=> Non-flags enums should not be used in bitwise operations

src/Ryujinx.Graphics.GAL/Capabilities.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, src/Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheGpuAccessor.cs, src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Gpu/Shader/DiskCache/ParallelDiskCacheLoader.cs, src/Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, src/Ryujinx.Graphics.Gpu/Shader/GpuAccessorBase.cs, src/Ryujinx.Graphics.Gpu/Shader/ResourceCounts.cs, src/Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, src/Ryujinx.Graphics.Gpu/Shader/ShaderInfoBuilder.cs, src/Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs, src/Ryujinx.Graphics.Shader/Constants.cs, src/Ryujinx.Graphics.Shader/IGpuAccessor.cs, src/Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, src/Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetCollection.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, src/Ryujinx.Graphics.Vulkan/ShaderCollection.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
This implements partial support for transform feedback emulation, for platforms that do not have native support for this feature (like macOS).
Test results
-
I tested some games that uses transform feedback locally to validate that the implementation is working. Below I show the results and also some observations regarding issues that I found.
**Pokémon Scarlet/Violet:**
This test was done with buffer mirrors (#4899). ~~Without it, the performance is abysmal and for some reason, some objects are flickering (maybe related to the low performance)~~ (The performance issue was fixed on 5447548610a45c5305cc5affcc07aadbbaec5862). No `InvalidResource` error with and without mirrors.
**Pokémon Legends Arceus:**
~~This was tested without buffer mirrors.~~ (Can also reach 30 fps without mirrors …
=> Implement transform feedback emulation for hardware without native support

src/ARMeilleure/CodeGen/Arm64/CodeGenerator.cs, src/ARMeilleure/CodeGen/Arm64/CodeGeneratorIntrinsic.cs, src/ARMeilleure/CodeGen/Arm64/IntrinsicTable.cs, src/ARMeilleure/CodeGen/Arm64/IntrinsicType.cs, src/ARMeilleure/CodeGen/Arm64/PreAllocator.cs, src/ARMeilleure/Instructions/InstEmitSimdCrypto.cs, src/ARMeilleure/Instructions/InstEmitSimdCrypto32.cs, src/ARMeilleure/Optimizations.cs, src/ARMeilleure/Translation/PTC/Ptc.cs
As the title says. This greatly improves the performance of AES operations when using JIT on Arm64 platforms. It is most notable on Animal Crossing when the game is saving, since it apparently encrypts the save data, and before this change that would cause noticeable stutters.
Closes #5263.
=> Implement fast path for AES crypto instructions on Arm64

src/Ryujinx.Ava/AppHost.cs, src/Ryujinx.Ava/UI/Renderer/EmbeddedWindow.cs, src/Ryujinx.Ava/UI/Renderer/EmbeddedWindowOpenGL.cs, src/Ryujinx/Ui/GLRenderer.cs
I have absolutely no clue why this works.
The error produced by X11 looks like that: `XError: X_Error result is BadMatch (invalid parameter attributes) (code: 8)`
(You can get the error by applying https://github.com/marysaka/SPB/pull/4 to SPB.)
As far as I understood, the issue was related to one of the `FramebufferFormat` parameters being incorrect.
I was about to test different values for `depthBits` (as this [answer](https://stackoverflow.com/a/17127200) suggested), but tried the empty constructor once just to see what would happen. To my surprise it just started to work, so here we are.
---
Fixes #4600
=> Ava: Fix OpenGL on Linux again

.github/assign/audio.yml, .github/assign/cpu.yml, .github/assign/global.yml, .github/assign/gpu.yml, .github/assign/gui.yml, .github/assign/horizon.yml, .github/assign/infra.yml, .github/labeler.yml, .github/workflows/pr_triage.yml
This is a bare minimal triage action that handle big categories.
Allow a big time save (aka less triage of PRs) to be more efficient.
Because kentaro-m/auto-assign-action doesn't allow to filter per label per team, I had to duplicate call of the action.
In the future we could also label all services correctly but I didn't felt this was required for a first iteration.
=> infra: Add PR triage action

src/Ryujinx.Common/Memory/SpanReader.cs, src/Ryujinx.Horizon/LogManager/Ipc/LmLogger.cs
On #4701, I fixed some `IndexOutOfRangeException` crashes on LM service caused by invalid sizes that would make it try to read more data than what is in the message buffer, but it would only apply to cases where it reads a string with variable length. This extends it to all reads. A new `TryRead` method was added to `SpanReader` that will return false if the value can't be read due to it not fitting in the span. In the cases where `TryRead` returns false, it returns immediately and prints whatever we have.
Fixes a crash that I found while trying to start a new match on Mortal Kombat 11 (base version).
=> Make LM skip instead of crashing for invalid messages

src/Ryujinx.Ui.Common/Helper/FileAssociationHelper.cs
Fixes #5243 by correctly setting the registry key for the open command.  
Also wraps IDisposable resources in `using` blocks.
=> UI: Correctly set 'shell/open/command; registry key for file associations

src/Ryujinx.HLE/HOS/ModLoader.cs
This addresses issue #5273.
Not quite sure if there was any reasoning behind the wildcard, I looked in the file but I couldn't see anything that would explicitly need it.
=> Mod Loader: Stop loading mods from folders that don't exactly match titleId

src/ARMeilleure/Instructions/InstEmitSimdCvt32.cs, src/ARMeilleure/Instructions/InstEmitSimdHelper32Arm64.cs, src/ARMeilleure/Translation/PTC/Ptc.cs
This fixes the implementation of the VCVT Arm32 instruction, when doing conversion from double to int or uint (32-bit) on Arm64. The problem is that it was using the Arm64 scalar conversion instructions, but Arm64 only does double to long/ulong or float to int/uint conversion. Meanwhile, Arm32 does double to int/uint and float to int/uint. To fix the issue, this uses the instruction that puts the value on a GPR instead of SIMD register, since those instructions does allow to specify the destination type as well. A similar thing was already being done for the conversion instruction that rounds towards zero.
This fixes bad audio on Prinny Presents NIS Classics Volume 3: La Pucelle: Ragnarok / Rhapsody: A Musical Adventure on Arm64 platforms.
=> Fix Arm32 double to int/uint conversion on Arm64

src/ARMeilleure/Translation/Cache/JitCache.cs, src/Ryujinx.Tests.Memory/Tests.cs, src/Ryujinx.Tests/Cpu/CpuTest.cs, src/Ryujinx.Tests/Cpu/CpuTest32.cs, src/Ryujinx.Tests/Cpu/CpuTestSimdMemory32.cs, src/Ryujinx.Tests/Cpu/CpuTestSimdReg32.cs, src/Ryujinx.Tests/Cpu/CpuTestT32Flow.cs, src/Ryujinx.Tests/Cpu/CpuTestThumb.cs
This fixes running tests on Asahi Linux that uses 16KiB pages.
I disabled `CpuTestThumb::TestRandomTestCases` on system without 4KiB pages for now as it needs to be rewritten.
Also disable `Vshl` test on ARM64 as unicorn crash when trying to run it.
=> test: Make tests runnable on system without 4KiB page size

src/ARMeilleure/Decoders/OpCode32SimdSel.cs, src/ARMeilleure/State/ExecutionMode.cs, src/Ryujinx.Audio.Backends.SoundIo/Native/SoundIoBackend.cs, src/Ryujinx.Common/Configuration/Hid/ControllerType.cs, src/Ryujinx.Common/Configuration/Hid/PlayerIndex.cs, src/Ryujinx.Graphics.Vulkan/MoltenVK/MVKConfiguration.cs, src/Ryujinx.HLE/HOS/Services/Hid/Types/Npad/ControllerType.cs, src/Ryujinx.HLE/HOS/Services/Hid/Types/Npad/NpadIdType.cs, src/Ryujinx.HLE/HOS/Services/Hid/Types/Npad/PlayerIndex.cs, src/Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Npad/DeviceType.cs, src/Ryujinx.HLE/HOS/Services/Hid/Types/SharedMemory/Npad/NpadBatteryLevel.cs, src/Ryujinx.HLE/HOS/Services/Mii/Types/CoreData.cs, src/Ryujinx.HLE/HOS/Services/Mii/Types/RandomMiiConstants.cs, src/Ryujinx.HLE/HOS/Services/Mii/Types/Source.cs, src/Ryujinx.HLE/HOS/Services/Mii/Types/SourceFlag.cs, src/Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvInternalResult.cs, src/Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvMap/Types/NvMapHandleParam.cs, src/Ryujinx.HLE/HOS/Services/Sockets/Bsd/ISocket.cs, src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/NativeWindowApi.cs, src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/Status.cs
An inheritance list entry is redundant if:
- It is `Object` - all classes extend `Object` implicitly.
- It is `int` for an `enum`
- It is a base class of another listed inheritance.
Such redundant declarations should be removed because they needlessly clutter the code and can be confusing.
=> Inheritance should not be redundant

src/Ryujinx.Graphics.Shader/Decoders/Decoder.cs, src/Ryujinx.Graphics.Shader/Instructions/InstEmitMemory.cs, src/Ryujinx.Graphics.Shader/Translation/FeatureFlags.cs, src/Ryujinx.Graphics.Shader/Translation/ResourceManager.cs, src/Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs, src/Ryujinx.Graphics.Shader/Translation/TranslatorContext.cs
Currently, if the local or shared memory sizes are 0, they are not declared at all, since declaring an array of size 0 is invalid (and it would not make sense to use it if the size is 0). For shaders where local memory is used but for some reason the size is 0, this will currently throw an exception and it will try to get the `MemoryDefinition` on the dictionary for memory that doesn't actually exist. To prevent those crashes, this change ensures that we will always declare local and shared memory if they are used. In the cases where it is used and size is 0, it uses a default size instead, just to ensure it is not 0.
This change also warns an early exists if an attempt is made to use shared memory instruction in anything other than a compute shader, as this memory type is only valid on …
=> Ensure shader local and shared memory sizes are not zero

src/Ryujinx.Cpu/AddressSpace.cs, src/Ryujinx.Cpu/Jit/MemoryManagerHostMapped.cs, src/Ryujinx.HLE/HOS/ArmProcessContext.cs, src/Ryujinx.HLE/HOS/ArmProcessContextFactory.cs, src/Ryujinx.HLE/HOS/Kernel/Memory/KPageTable.cs, src/Ryujinx.HLE/HOS/Kernel/Memory/KPageTableBase.cs, src/Ryujinx.HLE/HOS/Kernel/Process/IProcessContext.cs, src/Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs, src/Ryujinx.HLE/HOS/Kernel/Process/ProcessContext.cs, src/Ryujinx.HLE/HOS/Kernel/Process/ProcessContextFactory.cs
This adds code to support userland with less than 39 bits of address space available by testing reserving multiple sizes and reducing guess address space when needed.
This is required for ARM64 support when the kernel is configured to use 63..39 bits for kernel space. (meaning only 39 bits is available to userland)
=> misc: Implement address space size workarounds

src/ARMeilleure/State/V128.cs, src/Ryujinx.HLE/HOS/Services/Mii/Types/CreateId.cs, src/Ryujinx.Tests.Unicorn/SimdValue.cs, src/Spv.Generator/ConstantKey.cs, src/Spv.Generator/DeterministicStringKey.cs, src/Spv.Generator/LiteralString.cs, src/Spv.Generator/TypeDeclarationKey.cs
`GetHashCode` is used to file an object in a `Dictionary` or `Hashtable`. If `GetHashCode` uses non-`readonly` fields and those fields change after the object is stored, the object immediately becomes mis-filed in the `Hashtable`. Any subsequent test to see if the object is in the `Hashtable` will return a false negative.
=> GetHashCode should not reference mutable fields

src/Ryujinx.Graphics.Gpu/Image/TextureGroupHandle.cs, src/Ryujinx.Graphics.Vulkan/ShaderCollection.cs, src/Ryujinx.HLE/HOS/Kernel/Threading/KAddressArbiter.cs, src/Ryujinx.HLE/HOS/Services/Nfc/Nfp/VirtualAmiibo.cs
Both the `List.Exists` method and `IEnumerable.Any` method can be used to find the first element that satisfies a predicate in a collection. However, `List.Exists` can be faster than `IEnumerable.Any` for `List` objects, as well as requires significantly less memory. For small collections, the performance difference may be negligible, but for large collections, it can be noticeable. The same applies to `ImmutableList` and arrays too.
Benchmark:
```cs
private List<int> data;
private readonly Random random = new Random();
[Params(1_000)]
public int N { get; set; }
[GlobalSetup]
public void Setup() =>
data = Enumerable.Range(0, N).Select(x => 43).ToList();
[Benchmark(Baseline = true)]
public void Any()
{
for (var i = 0; i < N; i++)
{
_ = data.Any(x => x % 2 == 0);          // Enumerable.Any …
```
=> "Exists" method should be used instead of the "Any" extension

src/Ryujinx.Ava/UI/ViewModels/AmiiboWindowViewModel.cs, src/Ryujinx.HLE/Loaders/Processes/Extensions/FileSystemExtensions.cs, src/Ryujinx.HLE/Loaders/Processes/ProcessLoader.cs, src/Ryujinx.HLE/Loaders/Processes/ProcessResult.cs, src/Ryujinx/Ui/Windows/AmiiboWindow.cs
Both the `List.Find` method and `IEnumerable.FirstOrDefault` method can be used to find the first element that satisfies a given condition in a collection. However, `List.Find` can be faster than `IEnumerable.FirstOrDefault` for `List` objects. For small collections, the performance difference may be minor, but for large collections, it can make a noticeable difference. The same applies for `ImmutableList` and arrays too.
Benchmark:
```cs
private List<string> data;
private Random random = new Random();
[Params(1_000)]
public int N { get; set; }
[GlobalSetup]
public void Setup() =>
data = Enumerable.Range(0, N).Select(x => Guid.NewGuid().ToString()).ToList();
[Benchmark(Baseline = true)]
public void FirstOrDefault()
{
for (var i = 0; i < N; i++)
{
var value = data[random.Next(N - 1)];
_ = …
```
=> "Find" method should be used instead of the "FirstOrDefault" extension

src/Ryujinx.HLE/HOS/Diagnostics/Demangler/Ast/TemplateArguments.cs, src/Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Proxy/DnsMitmResolver.cs
Benchmark:
```cs
private List<string> data;
[Params(1_000_000)]
public int N { get; set; }
[GlobalSetup]
public void Setup() =>
data = Enumerable.Range(0, N).Select(_ => Guid.NewGuid().ToString()).ToList();
[Benchmark]
public void StartsWith_String()
{
_ = data.Where(guid => guid.StartsWith("d")).ToList();
}
[Benchmark]
public void StartsWith_Char()
{
_ = data.Where(guid => guid.StartsWith('d')).ToList();
}
[Benchmark]
public void EndsWith_String()
{
_ = data.Where(guid => guid.EndsWith("d")).ToList();
}
[Benchmark]
public void EndsWith_Char()
{
_ = data.Where(guid => guid.EndsWith('d')).ToList();
}
```
Results:
<html>
<body>
Method | Mean | StdDev | Median
-- | -- | -- | --
StartsWith_String | 30.965 ms | 3.2732 ms | 29.932 ms
StartsWith_Char | 7.568 ms | 0.3235 ms | 7.534 ms …
=> "StartsWith" and "EndsWith" overloads that take a "char" should be used instead of the ones that take a "string"

src/Ryujinx.Graphics.Shader/Translation/Translator.cs
Benchmark:
```cs
private IList<int> data;
private static readonly Random Random = new Random();
[Params(1_000_000)]
public int NumberOfEntries;
[GlobalSetup]
public void Setup() =>
data = Enumerable.Range(0, NumberOfEntries).Select(x => Random.Next(0, NumberOfEntries)).ToList();
[Benchmark(Baseline = true)]
public void OrderByThenWhere() =>
_ = data.OrderBy(x => x).Where(x => x % 2 == 0 ).ToList();  // OrderBy followed by Where
[Benchmark]
public void WhereThenOrderBy() =>
_ = data.Where(x => x % 2 == 0 ).OrderBy(x => x).ToList();  // Where followed by OrderBy
```
Results:
<html>
<body>
Method | Runtime | Mean | StdDev | Ratio
-- | -- | -- | -- | --
OrderByThenWhere | .NET 7.0 | 175.36 ms | 5.101 ms | 1.00
WhereThenOrderBy | .NET 7.0 | 85.58 ms | 1.697 ms | 0.48
</body>
</html>
=> "Where" should be used before "OrderBy"

src/ARMeilleure/Memory/IJitMemoryBlock.cs, src/Ryujinx.Cpu/Jit/JitMemoryBlock.cs, src/Ryujinx.Memory/MemoryBlock.cs, src/Ryujinx.Memory/MemoryManagement.cs, src/Ryujinx.Memory/MemoryManagementUnix.cs, src/Ryujinx.Memory/MemoryManagementWindows.cs
This PR makes the memory mangement behavior for `Commit()` and `Decommit()` between Unix and Windows consistent again.
This behavior has been inconsistent since I added `SystemException`s  should these methods fail to Unix only.
See: #4702
Now both implementations throw `SystemException`s and the return types were changed to `void` since we always return `true` if they don't fail.
=> MemoryManagement: Change return types for Commit/Decommit to void

src/Ryujinx.Audio/Constants.cs
`public static` mutable fields of classes which are accessed directly should be protected to the degree possible. This can be done by reducing the accessibility of the field or by changing the return type to an immutable type.
=> Mutable fields should not be "public static"

src/ARMeilleure/Instructions/SoftFloat.cs
Empty `case` clauses that fall through to the default are useless. Whether or not such a `case` is present, the `default` clause will be invoked. Such `case`s simply clutter the code, and should be removed.
=> Empty "case" clauses that fall through to the "default" should be omitted

distribution/macos/Info.plist, src/Ryujinx.Ava/AppHost.cs
Echo #5291, we can directly increase the stack size by setting the environment variable in `Ryujinx.app/Contents/Info.plist`.
Using this method, Mortal Kombat 11 still needs stack size of at least 2MB to run properly. Splatoon 3 doesn't need that much, but it's dominated by higher demand.
Update the copyright date by the way.
My environment:
OS: macOS 12.5.1
CPU: Apple M2
RAM: 24G
Some screenshop:
=> Set COMPlus_DefaultStackSize to 2M in macOS

src/Ryujinx.Cpu/AddressSpace.cs, src/Ryujinx.Memory/MemoryBlock.cs, src/Ryujinx.Memory/MemoryManagementUnix.cs, src/Ryujinx.Memory/MemoryManagementWindows.cs
Fix a regression with address space allocation while providing more information about the context of the exception.
=> misc: memory: Migrate from OutOfMemoryException to SystemException entirely

src/Ryujinx.Ui.LocaleGenerator/LocaleGenerator.cs
Benchmark:
```cs
private List<byte> data;
private Random random;
[Params(1_000_000)]
public int SampleSize;
[Params(1_000)]
public int LoopSize;
[GlobalSetup]
public void Setup()
{
random = new Random(42);
var bytes = new byte[SampleSize];
random.NextBytes(bytes);
data = bytes.ToList();
}
[Benchmark]
public void First()
{
for (int i = 0; i < LoopSize; i++)
{
_ = data.First();
}
}
[Benchmark]
public void First_Index()
{
for (int i = 0; i < LoopSize; i++)
{
_ = data[0];
}
}
```
Results:
<html>
<body>
Method | Runtime | Mean | StdDev
-- | -- | -- | --
First | .NET 7.0 | 7,790.2 ns | 165.70 ns
First_Index | .NET 7.0 | 398.5 ns | 5.36 ns
</body>
</html>
=> Prefer indexing instead of "Enumerable" methods on types implementing "IList"

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/BufferDescriptor.cs, src/Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, src/Ryujinx.Graphics.Shader/CodeGen/Glsl/DefaultNames.cs, src/Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, src/Ryujinx.Graphics.Shader/CodeGen/Glsl/OperandManager.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/CodeGenContext.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/Declarations.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/Instructions.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/TextureMeta.cs, src/Ryujinx.Graphics.Shader/Instructions/InstEmitSurface.cs, src/Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs, src/Ryujinx.Graphics.Shader/IntermediateRepresentation/TextureOperation.cs, src/Ryujinx.Graphics.Shader/StructuredIr/AstTextureOperation.cs, src/Ryujinx.Graphics.Shader/StructuredIr/ShaderProperties.cs, src/Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, src/Ryujinx.Graphics.Shader/StructuredIr/TextureDefinition.cs, src/Ryujinx.Graphics.Shader/TextureDescriptor.cs, src/Ryujinx.Graphics.Shader/Translation/EmitterContext.cs, src/Ryujinx.Graphics.Shader/Translation/EmitterContextInsts.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessToIndexed.cs, src/Ryujinx.Graphics.Shader/Translation/ResourceManager.cs, src/Ryujinx.Graphics.Shader/Translation/Rewriter.cs, src/Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
This does a change similar to what I did to buffers, but with textures and images instead. Previously each `TextureOperation` had a constant buffer slot number, and word offset where the handle is stored in that comes (sometimes erroneously called just `Handle` or `HandleIndex`). This change instead uses the host binding number as a way to identify those textures in the IR. Like the buffer changes, the main advantage here is that this allow us to combine shader stages, and also allows us to reserve and use textures for emulation purposes, without messing with the bindings of the game textures.
=> Stop identifying shader textures with handle and cbuf, use binding instead

src/Ryujinx.Ava/UI/ViewModels/ControllerInputViewModel.cs, src/Ryujinx.Headless.SDL2/Program.cs, src/Ryujinx.SDL2.Common/SDL2Driver.cs, src/Ryujinx/Ui/Windows/ControllerWindow.cs
Reverts Ryujinx/Ryujinx#5433
`SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS` seems to not have any effects on the official HID driver.
=> Revert "sdl: set `SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS` to 0"

src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
Barriers inside a render pass should only be disabled for Apple GPUs (which don't support them). [MoltenVK itself ](https://github.com/KhronosGroup/MoltenVK/pull/1540)supports them for other GPUs.
Also changed `isTBDR` to be by vendor rather than setting all GPUs using MoltenVK to `true`.
=> MacOS: Allow barriers inside a render pass for non-Apple GPUs and don't treat as TBDR

src/ARMeilleure/Instructions/SoftFloat.cs
This PR fixes a regression from #5357 which led to some failing tests.
=> [CPU] Hotfix missing ToNearest rounding mode cases

src/Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
This PR fixes a regression from #5380 which was found by @demize.
`GetAddrInfoRequest()` can be called with an empty `service` parameter, which means that the requester doesn't care about the port. The logic introduced by #5380 didn't handle this case properly and would instead return `GaiError.Service`.
The fix here is to add another condition to the if-statement so empty strings aren't causing errors, because we still want to handle those properly.
=> [Hotfix] sockets: Resolve empty port requests to 0 again

src/Ryujinx.Ava/UI/Applet/AvaHostUiHandler.cs, src/Ryujinx.Ava/UI/Helpers/ContentDialogHelper.cs
There is no guarantee that the main window, or any window for that matter will be focused and this should not impact the ability to spawn content dialogs. Should resolve people getting "softlocked" on macOS and Linux when the window is not active and a software keyboard is triggered.
Fixes #5186
=> Ava UI: Remove `IsActive` checks from dialog methods

src/Ryujinx.Graphics.Gpu/Engine/Threed/SpecializationStateUpdater.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, src/Ryujinx.Graphics.Gpu/Memory/SupportBufferUpdater.cs, src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheGpuAccessor.cs, src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Gpu/Shader/GpuAccessor.cs, src/Ryujinx.Graphics.Gpu/Shader/GpuChannelGraphicsState.cs, src/Ryujinx.Graphics.Gpu/Shader/ShaderSpecializationState.cs, src/Ryujinx.Graphics.Shader/CodeGen/Glsl/Declarations.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/SpirvGenerator.cs, src/Ryujinx.Graphics.Shader/IGpuAccessor.cs, src/Ryujinx.Graphics.Shader/Instructions/InstEmitAttribute.cs, src/Ryujinx.Graphics.Shader/ShaderProgramInfo.cs, src/Ryujinx.Graphics.Shader/StructuredIr/ShaderProperties.cs, src/Ryujinx.Graphics.Shader/SupportBuffer.cs, src/Ryujinx.Graphics.Shader/Translation/EmitterContextInsts.cs, src/Ryujinx.Graphics.Shader/Translation/ShaderConfig.cs
The `YNegate` register value seems to affect the origin of `gl_FragCoord` on shaders. Since it did not take this into account, games that had `YNegate` enabled and that used `gl_FragCoord` on the fragment shader to calculate coords to sample a framebuffer texture for example, would be upside down.
This uses different approaches per renderer to flip `gl_FragCoord.y`. On OpenGL it just adds `layout (origin_upper_left) in vec4 gl_FragCoord;` on the fragment shader which changes the origin for those coords. Vulkan, however, does not support this (it only supports a upper left origin), so for Vulkan I added a new viewport size field on the support buffer, where the viewport width and height is written when `YNegate` is enabled. The shader then does `viewportSize.y - gl_FragCoord.y` for every …
=> Fix incorrect fragment origin when YNegate is enabled

src/Ryujinx.Graphics.Shader/Instructions/InstEmitSurface.cs
Contributes to https://github.com/Ryujinx/Ryujinx-Games-List/issues/2828.
Now the game goes ingame:
https://github.com/Ryujinx/Ryujinx/assets/35856442/5bb2c6ff-62a5-4e4f-a73a-45d24bbcd6b6
Reference: https://github.com/Ryujinx/Ryujinx/pull/5502#issuecomment-1657210852
=> (Graphics.Shader): Handle EmitSuatom constant dests and EmitSuld zero dest reg.

.github/workflows/build.yml, .github/workflows/checks.yml
This PR attempts to improve our current workflow issues by adding a slightly better workaround using my [unstable-commands](https://github.com/marketplace/actions/unstable-commands) action which I published yesterday.
I made this action primarily because we keep having issues with workflows that are either timing out or crashing for unknown reasons. Since we have trouble even replicating these issues on our own runners or local machines, the best thing we can do right now is to improve how we deal with them inside the workflows.
My action will retry the specified command if it runs into the timeout or one of the specified retry-codes was encountered. By default this action will only retry the command(s) up to 3 times before it gives up, we can of course adjust that if we think that could …
=> Add slightly better workaround for current workflow issues

src/Ryujinx.Graphics.Vulkan/VulkanInitialization.cs
Enables VK_EXT_4444_formats if GPU supports them resolves a validation error
`GUI.RenderLoop Gpu UserCallback: Validation Error: [ VUID-vkGetPhysicalDeviceFormatProperties-format-parameter ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x4addcb92 | vkGetPhysicalDeviceFormatProperties: value of format (1000340001) does not fall within the begin..end range of the core VkFormat enumeration tokens and is not an extension added token. The Vulkan spec states: format must be a valid VkFormat value (https://vulkan.lunarg.com/doc/view/1.3.250.1/windows/1.3-extensions/vkspec.html#VUID-vkGetPhysicalDeviceFormatProperties-format-parameter)`
=> GPU: Enable VK_EXT_4444_formats

src/Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, src/Ryujinx.Graphics.Gpu/Memory/BufferManager.cs
Sometimes draws don't use an index buffer. It's not necessary to check or upload data for the current index buffer binding as it won't be used.
This fixes Pokemon: Legends Arceus updating a stale index buffer for every draw during its TFB pass, which was all non-indexed draws. Not sure if Scarlet/Violet also does this.
This probably didn't cost much on normal PCs, but it had a large impact on MacOS, which the macos1 release build avoided by mirroring index buffers (the PR currently does not). Needs buffer mirrors still for the rest of the performance.
There are additional cases where index buffers are bound or checked with non-indexed draws on the backend, but this one was straightforward to fix and has the largest impact. Testing is welcome to ensure nothing weird broke.
=> GPU: Don't sync/bind index buffer when it's not in use

.github/workflows/build.yml, .github/workflows/pr_triage.yml
@IsaacMarovitz noticed that some jobs for his PRs were cancelled even though he didn't push new commits.
This PR fixes this by removing the concurrency properties from the build workflow, since we only need them in the checks workflow anyway.
As far as I understood the [docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview) about reusing workflows, I was sure the `github` context would be passed to the called workflow as well. Sadly this doesn't seem to be the case, which means instead of playing it safe (like I thought I did) I essentially only allowed one PR at a time to run the build workflow.
Aside from that I quickly added a condition to the pr_triage workflow, so it doesn't assign reviewers to PRs that are marked as draft anymore.
=> Fix PR build concurrency and stop auto assigning reviewers for draft PRs

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Instructions/InstEmitFlowControl.cs, src/Ryujinx.Graphics.Shader/Translation/EmitterContext.cs
Adding code after a terminal instruction on a basic block is invalid on SPIR-V. `OpKill` (`discard` in GLSL) is considered a terminal instruction. There was one case where we could generate more code after that: Alpha test with the condition set to "never", which would always discard the fragment.
This change fixes the issue by making sure we don't generate any code after a 'discard' when alpha test is set to "Never".
Should fix #4965.
Thanks for @jcm93 for looking into this issue and providing a save.
=> Do not add more code after alpha test discard on fragment shader

.editorconfig, src/Ryujinx.Ava/AppHost.cs, src/Ryujinx.Ava/Assets/Locales/en_US.json, src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs, src/Ryujinx.Ava/UI/Views/Settings/SettingsGraphicsView.axaml, src/Ryujinx.Graphics.GAL/IWindow.cs, src/Ryujinx.Graphics.GAL/Multithreading/ThreadedWindow.cs, src/Ryujinx.Graphics.Gpu/GraphicsConfig.cs, src/Ryujinx.Graphics.OpenGL/Window.cs, src/Ryujinx.Graphics.Vulkan/Window.cs, src/Ryujinx.Graphics.Vulkan/WindowBase.cs, src/Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs, src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
Ryujinx outputs sRGB in conformance with the Switch hardware. This makes sense and is correct behavior, but people on wide gamut displays might want Ryujinx to be able to output wide gamut colors, in order to take advantage of their display's capabilities.
This PR implements the option for Ryujinx's Vulkan backend to attempt to not explicitly select a color space during output, and instead pass the color information through Vulkan to the rest of the display engine. This should result in Ryujinx displaying with RGB values stretched to the color space that the operating system and display are currently using.
Adds a "Enable Color Space Passthrough" checkbox option under the Graphics settings tab in Avalonia. In Vulkan's ``Window.cs``, inside the ``ChooseSwapSurfaceFormat`` function, a check …
=> [Vulkan / Avalonia] Implement Color Space Passthrough option

src/ARMeilleure/Translation/PTC/Ptc.cs, src/ARMeilleure/Translation/PTC/PtcFormatter.cs, src/ARMeilleure/Translation/PTC/PtcProfiler.cs, src/Ryujinx.HLE/Loaders/Processes/Extensions/FileSystemExtensions.cs, src/Ryujinx.HLE/Loaders/Processes/ProcessLoaderHelper.cs
This PR fixes an issue where games would crash if mods utilizing JIT (most notably [exlaunch](https://github.com/shadowninja108/exlaunch)) were used.
More context can be found at the linked issue.
---
Fixes #5466
=> Allow access to code memory for exefs mods

src/Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs, src/Ryujinx.Tests/Cpu/EnvironmentTests.cs
After #5518 was merged, people reported a lot of crashes indicating an out of bounds access within hid.
This PR fixes this issue by returning from `SetSupportedPlayer()` before the array gets accessed should the index be too large.
With this change ARCropolis works properly again.
---
It seems none of my PRs can be merged without requiring a hotfix shortly after that. :upside_down_face:
=> [Hotfix] hid: Prevent out of bounds array access

src/Ryujinx.Ava/Program.cs
ForceDpiAware.Windows has a side effect of forcing the application DPI to be the same as the primary monitor. This isn't good if you have multiple monitors with different DPI.
On Avalonia, I don't think there are any downsides to disabling this. When it's disabled, `ForceDpiAware.GetWindowScaleFactor` always returns 1.
=> Ava UI: Allow DPI switching on Windows

src/Ryujinx.Ava/Assets/Styles/Styles.xaml
Inconsistent usage around the UI and all uses of listbox look a little odd with an animation. 
Most windows themselves have some form of pop-up animation, the content itself does not need one too.
Would like thoughts on full removal vs making a selector for _just_ the game list load. Personally I don't have a huge list and prefer no animation, but the game list is maybe the one listbox it is designed for.
Before:
https://github.com/Ryujinx/Ryujinx/assets/44103205/5ca4048b-f7b6-42b5-a50f-9e32a6ec1a27
After:
https://github.com/Ryujinx/Ryujinx/assets/44103205/927ecd8c-8823-4d81-ab70-46c25b262438
=> Ava UI: Remove animations on listbox items.

src/ARMeilleure/Instructions/InstEmitSimdHelper.cs, src/Ryujinx.Ava/Modules/Updater/Updater.cs, src/Ryujinx.Common/SystemInterop/ForceDpiAware.cs, src/Ryujinx.Graphics.Vulkan/MultiFenceHolder.cs, src/Ryujinx.HLE/HOS/Diagnostics/Demangler/Demangler.cs, src/Ryujinx.HLE/Loaders/Processes/ProcessConst.cs
The value of a `static readonly` field is computed at runtime while the value of a `const` field is calculated at compile time, which improves performance.
=> "static readonly" constants should be "const" instead

src/Ryujinx.Graphics.Gpu/Memory/BufferCache.cs, src/Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs
This branch changes the buffer copy fast path to notify memory tracking for all resources that aren't buffers. This fixes cases where games would copy buffer data directly into texture memory, which before would only work if the texture did not already exist. I imagine this happens when the guest driver is moving data between allocations or uploading it.
Since this only affects the fast path, cases where the source data has been modified from GPU (fast path copy destination doesn't count) will still fail to notify the texture, though I don't imagine games will do this. This should be resolved in future.
This fixes some texture issues with guest OpenGL games on switch, such as Dragon Quest Builders.
This may also be useful in future for games that move shader data around memory, if we end …
=> GPU: Track basic buffer copies that modify texture memory

src/Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, src/Ryujinx.Graphics.Gpu/Image/TextureManager.cs, src/Ryujinx.Graphics.Gpu/Memory/SupportBufferUpdater.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs
Now that the support buffer update is not done on the backend anymore, we can update the support buffer array directly, instead of having the intermediary array for the scales that is set to the support buffer later. This makes the code a little bit simpler.
Testing is welcome, needs to be tested with resolution scaling of course.
=> Simplify resolution scale updates

.github/reviewers.yml, .github/update_reviewers.py, .github/workflows/pr_triage.yml
This PR fixes a regression from #5519 where I broke the pr_triage workflow for non draft PRs.
In addition to that this PR also introduces Mako, a GitHub App for Ryujinx, which for now will only be used to assign reviewers to non-draft PRs.
In the future Mako might get a few more tasks to make project management (and maybe moderation) a little bit easier.
=> Introduce Mako to fix pr_triage workflow

src/Ryujinx.Graphics.Vulkan/StagingBuffer.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
There was an edge case where a game could submit tens of thousands of small copies over the course of over half a minute to unique fences. This could result in a large stutter when the staging buffer became full and it tried to check and free thousands of completed fences.
This became visible with some games and mirrors on Windows, as they don't submit any buffer data via the staging buffer, but may submit copies of the support buffer.
This change makes the Vulkan backend check for staging buffer completion on each command buffer submit, so it can't get backed up with 1000s of copies to check.
=> Vulkan: Periodically free regions of the staging buffer

.editorconfig, src/Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs
In a [multidimensional array](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/multidimensional-arrays), each element in each dimension has the same, fixed size as the other elements in that dimension. In a [jagged array](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/jagged-arrays), which is an array of arrays, each inner array can be of a different size. By only using the space that's needed for a given array, no space is wasted. This rule, CA1814, recommends switching to a jagged array to conserve memory.
Benchmark:
```cs
[SimpleJob]
[MemoryDiagnoser]
[Orderer(SummaryOrderPolicy.FastestToSlowest)]
[RankColumn]
public class Test
{
private static readonly int[,] multiDimensionalArray = new int[,]
{
{ 0b0001, 0b0010, 0b0100, 0b1000, …
```
=> Prefer jagged arrays over multidimensional

.github/update_reviewers.py
I have no idea why the type for app_id and installation_id really needs to be int, but if the package wants that then integers it is.
=> Fix AssertionError in update_reviewers.py

src/Ryujinx.Horizon/Sdk/Sf/Hipc/ServerManager.cs
Fixes an assert that started happening after #5580. This service does not have pointer buffer, but it was still trying to allocate a pointer buffer with size 0, which caused the assert.
This assert only happens in debug builds, so it should have no user visible effect.
=> Fix debug assert on services without pointer buffer

src/Ryujinx.Audio/Renderer/Dsp/PcmHelper.cs, src/Ryujinx.Audio/Renderer/Parameter/VoiceInParameter.cs
This prevents audren from trying to get an span with an invalid length, due to the buffer size being negative. This is caused by the end offset being less than the start offset of the data, so when calculating the size, the result is negative.
There was already a check on `PcmHelper.Decode` and friends to protect against that:
```cs
if (input.IsEmpty || endSampleOffset < startSampleOffset)
{
return 0;
}
```
But it becomes useless if we don't also ensure we are not going to get a span with invalid length which would throw exceptions.
This behaviour matches what the Switch DSP code does. It exits without decoding anything when end offset < start offset.
Fixes
> the cutscene at the end of the mission "Dreaming Mushroom" in Episode 4 is unskippable and crashes, making it impossible to …
=> Fix invalid audio renderer buffer size when end offset < start offset

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/Declarations.cs
#5576 changed where the position was declared, but forgot to add the Invariant declaration to position when the ReducedPrecision flag was enabled. This was causing weird graphical bugs in a bunch of games, mostly to do with mismatching depth between multiple draws of the same geometry.
Maybe the attempt to add it to Position in DeclareInputOrOutput can be removed now, assuming that path is never used.
=> Vulkan: Fix MoltenVK flickering

src/Ryujinx.Ava/UI/Views/Input/ControllerInputView.axaml, src/Ryujinx.Ava/UI/Views/Input/MotionInputView.axaml, src/Ryujinx.Ava/UI/Views/Input/RumbleInputView.axaml, src/Ryujinx.Ava/UI/Views/Main/MainViewControls.axaml
Avalonia will use the `SmallChange` property by default when using a keyboard input. If this isn't present it will simply snap to the `Minimum` and `Maximum` values.
=> Add SmallChange properties to all sliders.

src/Ryujinx.HLE/HOS/Services/Audio/IHardwareOpusDecoderManager.cs
This implement `GetWorkBufferSizeExEx` and `GetWorkBufferSizeForMultiStreamExEx` for `IHardwareOpusDecoderManager`.
A proper fix would be to reimplement the whole service based on the RE, but it should be fine as-is.
Everything is checked by RE.
Fixes Sea of Stars which is playable now:
=> opus: Implement GetWorkBufferSizeExEx and GetWorkBufferSizeForMultiStreamExEx

src/Ryujinx.Ava/Assets/Locales/en_US.json, src/Ryujinx.Ava/UI/Applet/SwkbdAppletDialog.axaml.cs, src/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/KeyboardMode.cs, src/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/NumericCharacterValidation.cs, src/Ryujinx/Ui/Applet/SwkbdAppletDialog.cs
Pip pointed out that this was too restrictive. Numeric is used for situations like manual IP address and DNS setting, in which case numbers `0-9` AND `.` must be valid characters.
- Fixes SMOO IP address selection
=> Fix numeric SWKB validation

src/Ryujinx.Graphics.Shader/IGpuAccessor.cs
Fixes a regression from #5509 that caused ShaderTools to assert in debug mode and produce "incorrect" code on release due to the default graphics state being invalid. No user visible effect, only affect ShaderTools not the emulator itself.
Closes #5644.
=> Fix ShaderTools GpuAcessor default values

src/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRendererBase.cs, src/Ryujinx.HLE/HOS/Services/IpcService.cs, src/Ryujinx.HLE/HOS/Services/Sm/IUserInterface.cs, src/Ryujinx.Headless.SDL2/WindowBase.cs
Using `Type.Assembly` to get the current assembly is nearly free in terms of performance; it’s a simple property access. On the other hand, `Assembly.GetExecutingAssembly()  can take up to 30 times as long because it walks up the call stack to find the assembly.
Note that `Assembly.GetExecutingAssembly()` is different than `Type.Assembly` because it dynamically returns the assembly that contains the startup object of the currently executed application. For example, if executed from an application it will return the application assembly, but if executed from a unit test project it could return the unit test assembly. `Type.Assembly` always returns the assembly that contains the specified type.
Benchmark:
```cs
[SimpleJob]
[MemoryDiagnoser]
[Orderer(SummaryOrderPolicy.FastestToSlowest)] …
```
=> Replacing 'Assembly.GetExecutingAssembly()' with 'Type.Assembly'

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/GlobalToStorage.cs
This fixes a regression introduced on #5241 where the shader translator would fail to find the base address for global memory operations if it comes from a local or shared memory. The issue is that I updated the IR to place a "ID" value to identify the memory being accessed, but by doing that I moved the offset value to the operand at index 1, but did not update `GlobalToStorage` code to account for that change.
This fixes a few failures to find storage buffers on Splatoon 3 and probably other games, though I'm not sure which visible effects that may have (I didn't notice anything visibly broken on master at a first glance).
=> Fix shader GlobalToStorage pass when base address comes from local or shared memory

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Translation/TranslatorContext.cs
This fixes a regression ~~from #5551~~ (actually I think the regression happened before that change, probably on the one that refactors `TranslatorContext`?) that caused the generated geometry shader used to assign `gl_Layer` on older GPUs to not actually assign it, which caused Pokémon Scarlet/Violet to render mostly black.
Only affects old GPUs that do not support `gl_Layer` on vertex shaders.
=> Fix gl_Layer to geometry shader change not writing gl_Layer

src/Ryujinx.Graphics.Vulkan/FramebufferParams.cs, src/Ryujinx.Graphics.Vulkan/HardwareCapabilities.cs, src/Ryujinx.Graphics.Vulkan/HelperShader.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/PipelineConverter.cs, src/Ryujinx.Graphics.Vulkan/PipelineDynamicState.cs, src/Ryujinx.Graphics.Vulkan/TextureStorage.cs, src/Ryujinx.Graphics.Vulkan/TextureView.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs, src/Ryujinx.Graphics.Vulkan/Window.cs
Overview
---
This change aims to reduce the validation error spam that happens when using the Vulkan backend with validation and error logging enabled right now, to make debugging easier, and potentially fix issues on some platforms.
Each commit fixes a different error, so I will explain what each of them fixes individually, in commit order:
- 1st change fixes the following barrier error:
> vkCmdPipelineBarrier(): pImageMemoryBarriers[0].image Barrier for VkImage 0xee74570000000a8a[] does not match an image from the current VkFramebuffer 0x7803750000000ae7[]. The Vulkan spec states: If fname:vkCmdPipelineBarrier is called within a render pass instance using a VkRenderPass object, the image member of any image memory barrier included in this command must be an attachment used in the …
=> Fix some Vulkan validation errors (mostly related to barriers)

src/Ryujinx.Graphics.Shader/CodeGen/Spirv/SpirvGenerator.cs
This replaces the use of the `ShaderOutputLayer` SPIR-V capability with the `ShaderViewportIndexLayerEXT` capability from the `SPV_EXT_shader_viewport_index_layer` extension. `ShaderOutputLayer` requires SPIR-V 1.5 which older drivers might not support, while the extension is much older and has a higher chance of being supported. `ShaderViewportIndexLayerEXT` as the name implies allow the usage of both `Layer` and `ViewportIndex`, while SPIR-V 1.5 added separate capabilities for them.
Fixes #5662.
=> Replace ShaderOutputLayer with equivalent ShaderViewportIndexLayerEXT capability

src/Ryujinx.Ava/Common/Locale/LocaleExtension.cs
This removes one of the few places reflections is used in the Avalonia ui project.
=> Use compiled binding for localizations

src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml.cs
Compiled bindings can only access public members with getters.
=> Fixes compiled bindings in cheat window

src/Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/ManagedSocket.cs, src/Ryujinx.HLE/HOS/Services/Sockets/Bsd/Impl/WinSockHelper.cs
The Switch uses the FreeBSD sockets implementation, while the emulator uses .NET sockets abstraction, which is basically a wrapper around WinSock (later adapted to work on Linux/MacOS). Right now we pretend that any socket option that .NET sockets don't support are not supported at all, and return an error to the game. This is of course not correct and can cause problems since the game does not expect those operations to fail (since they are supported on the Switch).
This change improves the handling of unsupported socket options a little bit by not returning an error if the socket option is valid for FreeBSD, but not supported on .NET sockets.  It doesn't provide an actual implementation for them though, so if the application actually depends on the socket option being set to function, …
=> Stub unsupported BSD socket options

src/Ryujinx.HLE/HOS/Services/Wlan/IInfraManager.cs, src/Ryujinx.HLE/HOS/Services/Wlan/ILocalGetActionFrame.cs, src/Ryujinx.HLE/HOS/Services/Wlan/ILocalGetFrame.cs, src/Ryujinx.HLE/HOS/Services/Wlan/ILocalManager.cs, src/Ryujinx.HLE/HOS/Services/Wlan/ISocketGetFrame.cs, src/Ryujinx.HLE/HOS/Services/Wlan/ISocketManager.cs, src/Ryujinx.HLE/HOS/Services/Wlan/IUnknown1.cs, src/Ryujinx.Horizon/Sdk/Wlan/IDetectManager.cs, src/Ryujinx.Horizon/Sdk/Wlan/IGeneralServiceCreator.cs, src/Ryujinx.Horizon/Sdk/Wlan/IInfraManager.cs, src/Ryujinx.Horizon/Sdk/Wlan/ILocalGetActionFrame.cs, src/Ryujinx.Horizon/Sdk/Wlan/ILocalGetFrame.cs, src/Ryujinx.Horizon/Sdk/Wlan/ILocalManager.cs, src/Ryujinx.Horizon/Sdk/Wlan/IPrivateServiceCreator.cs, src/Ryujinx.Horizon/Sdk/Wlan/ISfDriverServiceCreator.cs, src/Ryujinx.Horizon/Sdk/Wlan/ISocketGetFrame.cs, src/Ryujinx.Horizon/Sdk/Wlan/ISocketManager.cs, src/Ryujinx.Horizon/ServiceTable.cs, src/Ryujinx.Horizon/Wlan/Ipc/DetectManager.cs, src/Ryujinx.Horizon/Wlan/Ipc/GeneralServiceCreator.cs, src/Ryujinx.Horizon/Wlan/Ipc/InfraManager.cs, src/Ryujinx.Horizon/Wlan/Ipc/LocalGetActionFrame.cs, src/Ryujinx.Horizon/Wlan/Ipc/LocalGetFrame.cs, src/Ryujinx.Horizon/Wlan/Ipc/LocalManager.cs, src/Ryujinx.Horizon/Wlan/Ipc/PrivateServiceCreator.cs, src/Ryujinx.Horizon/Wlan/Ipc/SfDriverServiceCreator.cs, src/Ryujinx.Horizon/Wlan/Ipc/SocketGetFrame.cs, src/Ryujinx.Horizon/Wlan/Ipc/SocketManager.cs, src/Ryujinx.Horizon/Wlan/WlanIpcServer.cs, src/Ryujinx.Horizon/Wlan/WlanMain.cs
This PR migrate empty wlan services from HLE project to Horizon project, values are found by RE.
Latest firmwares added some other services which are now stubbed and up-to-date.
=> Horizon: Migrate wlan and stubs latest services

CONTRIBUTING.md, docs/README.md, docs/coding-guidelines/coding-style.md, docs/workflow/pr-guide.md
All files and structure heavily inspired by the dotnet/runtime docs: https://github.com/dotnet/runtime/tree/main/docs
- Main contributor guide landing page.
- C# codestyle doc.
- Pull request guide doc.
Let me know if any references to the `dotnet/runtime` project remain in the files as these were used as a template due to their excellent quality. Draft for now to open a discussion.
=> [INFRA] Addition of basic contributor guides and docs framework.

src/Ryujinx.Graphics.Vulkan/TextureStorage.cs
On macOS, using the generic MemoryBarrier in `InsertWriteToReadBarrier` causes flickering in some scenarios. This patches that by using the old ImageBarrier path on macOS. At the request of gdk I have added this workaround for both `InsertWriteToReadBarrier` and `InsertReadToWriteBarrier` even though it should only be necessary for `InsertWriteToReadBarrier`. As described in #5603, this is technically invalid in Vulkan and would result in a validation error.
Fixes #5685, #5694
=> Vulkan: Fix barriers on macOS

src/Ryujinx.Graphics.GAL/Format.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/RenderTargetUpdateFlags.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, src/Ryujinx.Graphics.Gpu/Image/Texture.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCache.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroupHandle.cs, src/Ryujinx.Graphics.Gpu/Image/TextureSearchFlags.cs, src/Ryujinx.Graphics.Gpu/Window.cs
When binding a render target, we ask the texture cache for the texture, which synchronizes the data both from guest memory, and performs any deferred copies from other textures with a copy dependency. When clearing a texture, this same path is taken, but it's possible that none of that data that was synchronized or copied would ever be used, meaning it just wasted time.
For us to say we can fully ignore the existing data when clearing a texture, the following conditions need to be met:
- All aspects of the texture must be cleared. For color textures, that's a component mask of 15 (RGBA), and for depth textures, that's depth and stencil clears (including stencil mask) when the texture has depth or stencil aspects.
- Viewport scissor must be disabled or larger than the screen scissor state. …
=> GPU: Discard data when getting texture before full clear

src/Ryujinx.Cpu/AppleHv/HvAddressSpace.cs, src/Ryujinx.Cpu/AppleHv/HvAddressSpaceRange.cs, src/Ryujinx.Cpu/AppleHv/HvApi.cs, src/Ryujinx.Cpu/AppleHv/HvCpuContext.cs, src/Ryujinx.Cpu/AppleHv/HvEngine.cs, src/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs, src/Ryujinx.Cpu/AppleHv/HvExecutionContextShadow.cs, src/Ryujinx.Cpu/AppleHv/HvExecutionContextVcpu.cs, src/Ryujinx.Cpu/AppleHv/HvMemoryBlockAllocation.cs, src/Ryujinx.Cpu/AppleHv/HvMemoryBlockAllocator.cs, src/Ryujinx.Cpu/AppleHv/HvMemoryManager.cs, src/Ryujinx.Cpu/AppleHv/HvVcpu.cs, src/Ryujinx.Cpu/AppleHv/HvVcpuPool.cs, src/Ryujinx.Cpu/AppleHv/HvVm.cs, src/Ryujinx.Cpu/AppleHv/IHvExecutionContext.cs, src/Ryujinx.Cpu/AppleHv/TimeApi.cs
There are two ways (that I'm aware of, at least) to interrupt a VCPU on Apple Hypervisor. The most obvious one is the one that the emulator currently uses, calling `hv_vcpus_exit`. The second and slightly less efficient one is setting up a timer to interrupt the VCPU periodically.
The method that the emulator currently uses can miss interrupts in some cases. The most obvious case is when the thread is interrupted before it starts executing guest code again. Because it uses a VCPU pool, and it returns the VCPU to the pool when hadling guest interrupts (calling HLE kernel), there is no way to interrupt a VCPU at that time, so it just ignores the interrupt request. On top of that, I'm not sure how `hv_vcpus_exit` behaves if you call it before the guest code is running. For the emulator, it …
=> Add VTimer as alternative interrupt method on Apple Hypervisor

src/Ryujinx.Graphics.Vulkan/MemoryAllocator.cs, src/Ryujinx.Graphics.Vulkan/MemoryAllocatorBlockList.cs
It seems there was some attempt to make `MemoryAllocator.Allocate` method thread safe, by locking the `MemoryAllocatorBlockList` object when it already exists, however this is not really enough to make it thread safe for several reasons:
- No suck locks exists when a new `MemoryAllocatorBlockList`. It is possible that another thread will access it right after it is added to the list, and then we have 2 threads calling the `Allocate` method which is what the first lock is supposed to prevent.
- Adding the new `MemoryAllocatorBlockList` to the `_blockLists` is also not thread safe.
- Block freeing is not thread safe, although I don't think this ever happens outside of the render thread, but even if it doesn't it will touch the internal `_blocks` list that can be accessed from other threads. …
=> Make Vulkan memory allocator actually thread safe

src/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetManager.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, src/Ryujinx.Graphics.Vulkan/PipelineLayoutCacheEntry.cs, src/Ryujinx.Graphics.Vulkan/ShaderCollection.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
This was started by extracting some changes from #3001: I changed the descriptor pool creation there to use lower pool sizes. Before the change, it would create a pool with sizes for all used descriptor types (uniform/storage buffer, combined image sampler, storage buffers, uniform texel buffers and storage texel buffers). Since it creates a descriptor pool per set, and each set can only use some of those types, this change the descriptor pool to only have pool sizes for the descriptor types that the set uses.
The other change is a bug fix. `PipelineLayoutCacheEntry.GetNewDescriptorSetCollection` knows that the command buffer changed by checking `_dsLastCbIndex != commandBufferIndex`. When the command buffer changes, it sets the current cache entry index to 0, which allows it to re-use …
=> Reduce the amount of descriptor pool allocations on Vulkan

src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
This fix a regression caused by #5516 when CheckLaunchState is assumed to be executed async.
Since the UI isn't created when launch state are check, the vmcount popup, the missing keys popup or the fullscreen game loading on startup just make the UI hang.
if we revert the async changes to use the dispatcher and rewrite the method, it works as expected.
=> Ava: Fix regressions by rewriting CheckLaunchState

src/ARMeilleure/Translation/IntervalTree.cs, src/Ryujinx.Common/Collections/IntervalTree.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCache.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs
Buffer texture memory is handled by the buffer cache - the texture shouldn't create any tracking handles as they aren't used. This change simply makes them create and iterate 0 tracking handles, while keeping the rest of the texture group around.
This prevents a possible issue where many buffer textures are created as views of overlapping buffer ranges, and virtual regions have many dependant textures that don't actually contribute anything to handle state.
Also included:
- Fix a longstanding issue where every texture returned from the interval tree lookup would resize the lookup array. (yes, every)
- Buffer textures now skip checking view compatibility with any other textures, since they are never compatible and don't remove each other due to overlap.
- In MK1, more than 100 buffer …
=> GPU: Don't create tracking handles for buffer textures

src/Ryujinx.Audio/Renderer/Dsp/Command/AuxiliaryBufferCommand.cs, src/Ryujinx.Audio/Renderer/Dsp/Command/BiquadFilterCommand.cs, src/Ryujinx.Audio/Renderer/Dsp/Command/CommandList.cs, src/Ryujinx.Audio/Renderer/Dsp/Command/CompressorCommand.cs, src/Ryujinx.Audio/Renderer/Dsp/Command/DelayCommand.cs, src/Ryujinx.Audio/Renderer/Dsp/Command/LimiterCommandVersion2.cs, src/Ryujinx.Audio/Renderer/Dsp/Command/ReverbCommand.cs, src/Ryujinx.Audio/Renderer/Dsp/FloatingPointHelper.cs, src/Ryujinx.Audio/Renderer/Dsp/State/CompressorState.cs, src/Ryujinx.Audio/Renderer/Dsp/State/DelayState.cs, src/Ryujinx.Audio/Renderer/Dsp/State/LimiterState.cs, src/Ryujinx.Audio/Renderer/Dsp/State/Reverb3dState.cs, src/Ryujinx.Audio/Renderer/Dsp/State/ReverbState.cs
This fixes a few audio renderer issues (mostly related to the compressor effect):
- The `DecibelToLinearExtended` function doesn't exist, it is supposed to be the same as `DecibelToLinear`.
- `FloatingPointHelper.Log10` was wrong, it was doing `pow(10, x)` rather than `log(x, 10)`.
- `FloatingPointHelper.MeanSquare` was not normalizing the input values, causing the result to be too high.
- Incorrect control flow on `ProcessCompressor`, `z` was being intialized to the wrong value in one case (0.0 instead of 1.0).
- `CommandList.ClearBuffer` and `CommandList.CopyBuffer` had wrong lengths, it was using the raw sample count as length, instead of multiplying it by sample size, so it was not actually clearing/copying everything.
- A few of the effect state were classes rather than struct. I …
=> Fix audio renderer compressor effect

src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/BufferQueueProducer.cs
The game Sifu was calling `SetPreallocatedBuffer` and replacing buffers that have been queued. Because it is replaced before consumption, the nvmap reference count is never decremented, and this later causes the nvmap `Free` call to set the `NotYetFreed` flag. This prevents the memory attributes from being restored from `Uncached` to `None`, which in turn causes the `UnmapPhysicalMemory` to return an error, and ultimately the game crashes with `GuestProgramBrokeExecution`. This is fixed here by making sure the problematic case also decrements the reference count. The crash was somewhat random though.
=> Decrement nvmap reference count on surface flinger prealloc

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs, src/Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenHelper.cs, src/Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/Instructions.cs, src/Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs, src/Ryujinx.Graphics.Shader/IntermediateRepresentation/Instruction.cs, src/Ryujinx.Graphics.Shader/StructuredIr/InstructionInfo.cs, src/Ryujinx.Graphics.Shader/Translation/EmitterContextInsts.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs, src/Ryujinx.Graphics.Shader/Translation/ResourceManager.cs, src/Ryujinx.Graphics.Shader/Translation/Transforms/TexturePass.cs
This implements support for querying the amount of samples that a multisample texture has on the shader. This was not supported before, and it would actually generate invalid code for that case. The handlng of the `TXQ` shader instruction was improved a bit to log unsupported query types (instead of assuming that everything is a dimension query as it did before).
I found this while testing the game Cocoon. Unfortunately the game still crashes while compiling shaders on AMD, so I couldn't get very far, and I don't know which effects this change may have on the game...
=> Implement textureSamples texture query shader instruction

src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs, src/Ryujinx.Ava/UI/Views/Settings/SettingsGraphicsView.axaml
Gates the new color space passthrough option behind a check for whether the user is on macOS.
Users have reported being confused about what this option does and/or why it doesn't work. When the option was added, it was unclear whether other operating systems and Vulkan drivers might support the passthrough color space. It seems clear since that macOS and MoltenVK are the only combination for which passthrough is currently supported, implemented and exposed.
Initially, I explored a check for whether the passthrough color space is actually supported. However, this would involve a significant amount of added plumbing, since Ryujinx normally does not check for available color spaces until after a `VulkanRenderer` has already been initialized with a window, surface, and swapchain. For now, it …
=> Avalonia: Add macOS check for Color Space Passthrough

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/CodeGenContext.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/Declarations.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/Instructions.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/SpirvGenerator.cs, src/Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs, src/Ryujinx.Graphics.Shader/Translation/TranslatorContext.cs
Currently the SPIR-V backend will copy each function call parameter to a temporary variable. Right now, it reserves one set of variables per function (one for each input parameter), and reuses them across calls to the same function. For some reason, this now confuses the AMD compiler on their latest drivers, with causes rendering issues that didn't exist before.
This PR changes how it works, now all function calls gets their own unique set of temporary variables without any reuse, which seems to fix the issue.
Example on Pokémon Scarlet.
Before:
After:
=> Use unique temporary variables for function call parameters on SPIR-V

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/Instructions.cs
Fixes an oversight from #5757, on SPIR-V function calls are supposed to pass the pointer to the local variable, not the value itself.
This was causing the NVIDIA compiler to crash compiling shaders with function calls, but apparently was fine on AMD (which is why I didn't notice it was wrong).
=> Fix SPIR-V function calls

src/ARMeilleure/Diagnostics/Symbols.cs, src/Ryujinx.Ava/UI/ViewModels/AmiiboWindowViewModel.cs, src/Ryujinx.Graphics.Shader/CodeGen/Glsl/CodeGenContext.cs, src/Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGen.cs, src/Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/GlobalToStorage.cs, src/Ryujinx.HLE/FileSystem/ContentManager.cs, src/Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs, src/Ryujinx.HLE/HOS/Services/Sm/IUserInterface.cs, src/Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs, src/Ryujinx.Horizon/Sdk/Sm/ServiceName.cs, src/Ryujinx.Ui.LocaleGenerator/LocaleGenerator.cs
`StringBuilder` is more efficient than string concatenation, especially when the operator is repeated over and over as in loops.
In languages where strings are immutable, like Java and C#, each time you concatenate strings using the + operator, a new string object is created in memory to hold the result. This can lead to a significant overhead, both in terms of memory and processing time, especially when you're dealing with large strings or performing the operation multiple times. 
On the other hand, `StringBuilder` is designed to be mutable, meaning it can be modified after its creation without generating a new object in memory. When you append or insert a string to a `StringBuilder` object, it modifies the existing character array in memory, avoiding the need to create a new string …
=> Strings should not be concatenated using '+' in a loop

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/StructuredIr/StructuredProgram.cs
Fixes yet another regression from #5757. On the shader IR, out arguments are usually first added as destination operand, and then later it is moved to one of the source operands of the call (this is required since generally source operands are considered uses, and destination operands are considered assignments). The exception for that rule is some helper functions that the emulator generates, those adds the out argument as a source operand directly. While this was fine before, I did not account for that on #5757, which meant it will copy the out value into a temp (before the call), and the call would modify the temp value, while the actual out value would remain uninitialized.
This mainly affect games using shuffle instructions which does have one out parameter, so mostly UE4 games, but …
=> Fix SPIR-V call out arguments regression

src/Ryujinx.Common/Memory/StructArrayHelpers.cs, src/Ryujinx.HLE/HOS/Services/Mii/DatabaseImpl.cs, src/Ryujinx.HLE/HOS/Services/Mii/Types/CoreData.cs, src/Ryujinx.HLE/HOS/Services/Mii/Types/Nickname.cs, src/Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs, src/Ryujinx.HLE/HOS/Services/Mii/Types/Ver3StoreData.cs
Validating CRCs for data and device involves calculating the crc of all data including the crc being checked, which should then be 0.
The crc should be _generated_ on all data _before_ the crc in the struct. It shouldn't include the crcs themselves.
This fixes all generated miis (eg. default) having invalid crcs. This does not affect mii maker normally, as that generates its own StoreData crcs.
Also includes some miscellaneous fixes:
- Use Array<> instead of a byte storage field for CoreData, Nickname and Ver3StoreData
- This was observed causing core data to become all 0s, and nickname to only display the first character in debug mode. This probably depends on if the struct is copied, I imagine it doesn't think the undefined space in the struct holds any data.
- Ver3StoreData was not …
=> HLE: Fix Mii crc generation and minor issues

src/Ryujinx.Graphics.Gpu/Engine/DeviceStateWithShadow.cs, src/Ryujinx.Graphics.Gpu/Engine/MME/MacroHLE.cs, src/Ryujinx.Graphics.Gpu/Engine/MME/MacroHLEFunctionName.cs, src/Ryujinx.Graphics.Gpu/Engine/MME/MacroHLETable.cs, src/Ryujinx.Graphics.Gpu/Engine/SetMmeShadowRamControlMode.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClass.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClassState.cs, src/Ryujinx.Graphics.Gpu/Engine/Types/Boolean32.cs
We have a Macro JIT that emits CIL that the .NET runtime can convert directly into a method, which allows these methods to perform much faster than the interpreter. However, NativeAOT is not able to use Reflection.Emit, so the current Macro JIT does not work with it. NativeAOT has faster boot and load times, and is required for certain platforms. Also, it might be generally beneficial to make popular macros faster anyways, which it did end up being.
Initially, I tried to make a faster interpreter for macros by abusing C# generics to generate slim methods for instructions that only do what they need, but the cost of an interface method call for each instruction proved to be comparable to just doing everything via a ton of switch statements. I instead used this as a base for something that …
=> GPU: Add HLE macros for popular NVN macros

src/ARMeilleure/Diagnostics/Symbols.cs
Fixes a regression from #5664 that causes the wrong value to be returned in the Get function for Symbols.cs when a result does not currently exist for an address.
=> Symbols.cs Get function return value fix

src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
This PR fixes an odd issue where games would suddenly freeze after LDN was initialized 1021 times (or after spending about 20 minutes playing Pokémon Sword/Shield).
Since the `stateChangeEvent` handles were never closed before, the handle table was eventually running out of space which resulted in the game freezing for some reason. I was sure this issue would manifest as a crash, since at least in LDN we handle that case like that, but it seems in other places we might not be doing that or there is something else going on that I don't really understand yet. 
---
Fixes #5778
=> Fix games freezing after initializing LDN 1021 times

src/ARMeilleure/Translation/TranslatorCache.cs, src/Ryujinx.Common/ReactiveObject.cs, src/Ryujinx.Graphics.Vulkan/BufferHolder.cs
Replaces Use of ReaderWriterLock with ReaderWriterLockSlim, ReaderWriterLock is now deprecated in favor of ReaderWriterLockSlim. In cases of many readers and few writer it is preferred and in other cases a simple lock should be used. UpgradeableReadLock also is a thread blocking state so was replaced with simple switching between reading and writing. 
Supersedes #5493
=> Replace ReaderWriterLock with ReaderWriterLockSlim

src/Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs
This change allows Perky Little Things to render again. The game uses 8x multisampling on a 1920x1088 texture (really 1920x1080), later it tries to sample it as a 7680x2160 texture. While sampling multisampled textures as non-multisampled is already supported, this case was not working because the height doesn't match (1088 * 2 = 2076). This change enables copy compatibility for this specific case (as long the *aligned* height matches, at least).
According to Muffin it's a regression from #4662, but I'm not sure how that is possible.
=> Enable copy between MS and non-MS textures with different height

src/Ryujinx.Graphics.GAL/Capabilities.cs, src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Gpu/Shader/GpuAccessorBase.cs, src/Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs, src/Ryujinx.Graphics.Shader/IGpuAccessor.cs, src/Ryujinx.Graphics.Shader/Translation/Transforms/TexturePass.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
This PR adds a fallback for GPUs or APIs that don't support an equivalent to the method `textureGatherOffsets`, where each of the 4 gathered texels has an individual offset. This is done by reusing the existing code to handle non-const offsets for texture instructions, though it has also been corrected as there were a few implementation issues.
MoltenVK reports support for this capability, and it didn't error when we initially released the MacOS build, but that has since changed. MVK still reports support, but spirv-cross has been fixed in a way that it _attempts_ to use this capability, and the metal compiler errors since it doesn't exist.
Some other fixes:
- textureGatherOffsets emulation has been changed significantly. It now uses 4 texture sample instructions (not gather), calculates …
=> GPU: Add fallback when textureGatherOffsets is not supported

src/Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs
I believe this is a regression from #5792 (though the issue technically already existed before that, but I think we did not hit it because there was no need to "rewrite" any gather with depth compare before). The problem is that emit stage always adds the gather component to the operands, however gathers with depth compare don't have a "component" since it is supposed to be used with a depth texture. This causes the source array size to be too large and the last operand is null, causing NRE later on. Fixed by not adding the component operand when not needed. Maybe it is a good idea to resize the sources array if it's too large to avoid potential issues of this nature in the future.
Should fix this crash on macOS (Luigi's Mansion 3): …
=> Fix NRE on shader gather operations with depth compare on macOS

Directory.Packages.props, src/Ryujinx.Ava/Common/ApplicationHelper.cs, src/Ryujinx.Ava/UI/ViewModels/DownloadableContentManagerViewModel.cs, src/Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs, src/Ryujinx.HLE/FileSystem/ContentManager.cs, src/Ryujinx.HLE/FileSystem/VirtualFileSystem.cs, src/Ryujinx.HLE/HOS/ModLoader.cs, src/Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/FileSystemProxyHelper.cs, src/Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IFileSystem.cs, src/Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs, src/Ryujinx.HLE/Loaders/Processes/Extensions/PartitionFileSystemExtensions.cs, src/Ryujinx.HLE/Loaders/Processes/ProcessLoader.cs, src/Ryujinx.HLE/Loaders/Processes/ProcessLoaderHelper.cs, src/Ryujinx.Ui.Common/App/ApplicationData.cs, src/Ryujinx.Ui.Common/App/ApplicationLibrary.cs, src/Ryujinx/Ui/Widgets/GameTableContextMenu.cs, src/Ryujinx/Ui/Windows/DlcWindow.cs, src/Ryujinx/Ui/Windows/TitleUpdateWindow.cs
Main features:
- Adds `IFileSystem.GetFileSystemAttribute`. Fixes #5665
- General system stability improvements to enhance the user's experience
Non-functional updates made due to LibHac breaking changes:
- `PartitionFileSystem` classes now fully match Nintendo's implementation. Current code creating a `PartitionFileSystem` was updated to use the Initialize method.
- Implementing nn::gcsrv and nn::sdmmcsrv now means the FS server now uses that abstraction instead of the old one where we passed in an IDeviceOperator.
=> Update to LibHac 0.19.0

src/Ryujinx.Common/SystemInfo/MacOSSystemInfo.cs
Logs currently output the Darwin kernel version string. While correct, this is a version string that is never exposed to the user. It would be more useful to output the user-facing macOS version string (i.e. macOS 14.0 for Sonoma, versus Darwin 23.0). This will make debugging at a glance much easier, as most Mac developers do not hold the kernel versioning system in their heads simultaneously with macOS release versions.
It is fairly remote that the much more verbose version string will contain pertinent information that the common version string does not.
Before: <img width="1048" alt="Screenshot 2023-10-22 at 4 54 40 PM" src="https://github.com/Ryujinx/Ryujinx/assets/6864788/c3c62db0-c5c3-4104-8ab4-43b3a92a75ca">
After: 
(screenshot reflects changes from …
=> macOS: Use user-friendly macOS version string

src/Ryujinx.Graphics.Gpu/Image/Texture.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCache.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs
Flushing texture data after the texture has been unmapped from GPU memory is generally considered invalid/dangerous. That is because at this point, the GPU no longer owns it, and the CPU might be using the memory for something else, which means that flushing the texture may cause data corruption.
We already have something in place to prevent flushing after unmap, but it doesn't work for render targets, since after the render target is swapped out, it sets the modified flag again. This PR adds an additional flag to skip flush if the texture has been unmapped, and not bound/modified after the unmap.
This fixes memory corruption on Neptunia GameMaker R:Evolution (#5546), which now goes ingame (it was crashing before showing anything before):
Testing is welcome to ensure nothing broke, …
=> Skip some invalid texture flushes

src/Ryujinx.HLE/HOS/Services/ServerBase.cs
Added a KEvent for each ServerBase which signals whenever a session is added to the _sessions list, which allows it to rerun the ReplyAndReceive with the new session handle.
This greatly reduces the presence of ServerBase on CPU profiles, especially of games that aren't particularly busy. It should also increase responsiveness when adding session objects, as it doesn't take at most 1ms for them to start working.
It also reduces the load on KTimeManager, which could allow it to spin less often. I have noticed that a bunch of games still do 1ms waits (they actually request a bit less than 1ms), so they still end up spinning to the next millisecond. Maybe for waits like this, it could attempt to nudge the timepoints to snap to each other when they're close enough, and also snap to whole …
=> [HLE] Remove ServerBase 1ms polling

src/Ryujinx.Graphics.Gpu/Image/TextureCache.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, src/Ryujinx.Graphics.OpenGL/Image/TextureCopy.cs, src/Ryujinx.Graphics.OpenGL/Image/TextureView.cs, src/Ryujinx.Graphics.Vulkan/TextureView.cs
Luigi's Mansion 3 renders a texture using the R16Unorm format, and samples it using the D16Unorm format. We did not support that case before since those formats are not view compatible. This change adds support for this case using copies (copy dependency).
Fixes shadow issues on Luigi's Mansion 3.
Before:
https://user-images.githubusercontent.com/5624669/216788492-7c69012d-6641-467a-8c17-cb321faf0d2b.mp4
After:
https://user-images.githubusercontent.com/5624669/216788486-e85b3e8a-43e4-4713-ae9b-7205bd4dc92d.mp4
Thanks to @riperiperi for finding the issue.
Fixes #2791.
=> Implement copy dependency for depth and color textures

src/Ryujinx.HLE/HOS/Services/ServerBase.cs
Fixes a regression caused by #5855. It is possible that `AddSessionObj` is called from another thread before the service thread had a chance to create the `_wakeEvent` object, in which case it would throw a `NullReferenceException`. This fixes de issue by moving the event creation before `InitDone.Set();`. Since `AddSessionObj` waits for the `InitDone` event, it won't try to access it before it has been created.
Fixes #5874.
=> Fix AddSessionObj NRE regression

src/ARMeilleure/Decoders/Decoder.cs
At the advice of @gdkchan, adjusted ARMeilleure to better handle unmapped memory. It now actually performs a read when beginning decoding code. This will trip the invalid access handler when execution jumps directly into unmapped memory. This allows for a proper stack trace and register dump, instead of just an exception being thrown.
=> Better handle instruction aborts when hitting unmapped memory

src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
Changes the default hide cursor mode to hide on idle instead of never.
It seems like having the cursor hide on idle is generally a more sensible default than never hiding the cursor, given that the on idle hide does not take effect if you are not both in-game *and* the cursor is over the game window. If both these conditions are true, it seems like most people would want the cursor to disappear, at least by default.
This is the behavior at least on macOS and Avalonia. I have not tested the behavior of this setting extensively on GTK or on other platforms, and if the behavior differs significantly that could possibly be an issue.
=> UI: Change default hide cursor mode to OnIdle

src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml, src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs, src/Ryujinx/Ui/Widgets/GameTableContextMenu.Designer.cs
This pull request aims to fix current issues with the Create Shortcut functionality, specifically this will close #5839 #5827.
This will also add the `--fullscreen` arg to the shortcuts so by default launching games with shortcuts automatically open Ryujinx in fullscreen mode.
I will need some testing with the MacOS issue (#5827), as I do not currently have a Mac to test with myself. Perhaps @nickoanastassiu could help with this?
=> Create Desktop Shortcut fixes

src/Ryujinx.Graphics.Gpu/Image/Texture.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, src/Ryujinx.Graphics.Gpu/Image/TextureManager.cs
Basically aims to fix the same problem as #5755, but implemented using a different approach. Instead of skipping the flush, this avoids setting the modified flag if the texture has not been modified since the last time it was set. This fixes regressions caused by #5755 in some OpenGL games.
Fixes #5908.
=> Do not set modified flag again if texture was not modified

distribution/macos/Info.plist
This should prevent the app from opening on macOS 11 and lower, informing the user that their OS is unsupported.
This should prevent (at least some) people from filing bug reports for unsupported OS versions. 
Important: I don't know for certain if macOS 12 is actually technically the lowest supported version. I have just seen it mentioned [here](https://github.com/Ryujinx/Ryujinx/issues/5918#issuecomment-1809349501) and in several other posts on Discord. This should be confirmed before the PR is merged. 
Testing: 
Try to open the app on macOS 11 or lower and confirm that the "Unable to open" dialog appears.
=> Change minimum OS to macOS 12 in Info.plist

src/Ryujinx.Graphics.Gpu/Image/Texture.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroupHandle.cs
Fixes a regression from #5909 that broke texture on some games.
There is some internal logic there that should run when the texture is unbound, even if we don't set the modified flag.
=> Fix TextureGroup.SignalModifying not being called

src/Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs
We have a fast path where we can avoid some layout conversion operations by setting texture data directly to the destination texture on DMA copy. However, this can also trigger for block linear to linear textures. Typically, block linear to linear copies are used when the target texture will be read from CPU, and in those cases setting the data on the target texture is not worth it (since it will need to be flushed again later). This change disables the GPU path for this case, doing the copy on CPU instead.
Also has the advantage of avoiding flush related bugs, it seems to fix #5889 (this game triggers this case frequently).
Also includes #5926 since it affects that game too.
=> Disable DMA GPU copy for block linear to linear copies

src/Ryujinx.Common/Configuration/AppDataManager.cs
Post .NET 8 has changed `SpecialFolder.Personal` to point to `~/Documents` which resulted in Ryujinx creating/looking for its folder in a user's document directory, rather than actually in Application Support.
Fixes #5940
=> Fix macOS Path on .NET 8

src/ARMeilleure/Translation/Cache/JitCache.cs, src/ARMeilleure/Translation/Cache/JitUnwindWindows.cs
`JitCache.Unmap` was not able to handle multiple unmaps of the same address properly. `TryFind` will return the nearest entry in the cache if it can't find one with the exact address that should be freed. This means that if `Unmap` is called more than once with the same function address, it will free the wrong region the second time. This could cause it to free code still in use which would crash the emulator.
This was causing crashes on games that uses the JIT service. One example is Super Mario 3D All-Stars. To reproduce, launch Super Mario 64 there, then stop emulation and try to launch another game. It will crash quickly. In debug mode, an assert would fire when trying to stop emulation.
This change makes the `Unmap` function more robust, now it checks if the entry offset matches the …
=> Fix JitCache.Unmap called with the same address freeing memory in use

src/Ryujinx.Ui.Common/Configuration/ConfigurationLoadResult.cs, src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs, src/Ryujinx.Ui.Common/Ryujinx.Ui.Common.csproj, src/Ryujinx/Program.cs
MessageBox asking users to choose on fresh installation has been removed in favour of Vulkan if any of two conditions are met:
- The `VulkanRenderer.GetPhysicalDevices()` method returns any valid devices. There are already checks within said method for version and featureset.
- The system is running macOS, where Vulkan was already the only target.
Due to the maturity of the Vulkan backend I think this is a better default experience than the current wall of text popup for new users.
=> misc: Default to Vulkan if available or running on macOS

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs
This extends bindless elimination to also work on cases where the handle is "materialized" on multiple places in the code. It was not able to reason about that before because a Phi was on the way, so it was not able to find the handle comining operation.
Basically, this code:
```glsl
handle = fp_c2.data[24].z | fp_c2.data[88].x;
if (someCond) {
handle = fp_c2.data[24].z | fp_c2.data[88].x;
}
texture(handle, vec2(x, y));
```
Because `handle` has two assignment, and may have different values depending on the path it takes, it was not able to find the handle value. But the value is actually the same regardless of the path it takes, since constant buffers can't be modified inside the shader, and they both access the same values from the constant buffer, and perform the same operation.
To fix …
=> Extend bindless elimination to see through Phis with the same results

src/Ryujinx.Graphics.Gpu/Image/FormatTable.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, src/Ryujinx.Graphics.Gpu/Image/TexturePool.cs
A few OpenGL games do a image store using a texture that has 1/4 of the width and 4x the amount of bytes per pixel (effectively storing 4 pixels in one invocation). Then later, the texture is accessed using the "true" format. This does not work right now because the formats are incompatible, one texture uses a RGBA32 format, and the other RGBA8. A while ago, I enabled copy between incompatible formats since the game Mario + Rabbids Sparks of Hope does something similar (but the formats are R8 and RGBA8 instead). This change enables copy dependency between RGBA32 and RGBA8 formats.
Fixing this reveals another bug, which is why I did not include this fix on the Mario + Rabbids targeted change back then. The format of the input texture that the shader samples for the image store was also …
=> Enable copy dependency between RGBA8 and RGBA32 formats

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs
This shows up in some compiler generated patterns in the code, which I believe are used for some sort of `textureGrad` implementation.  The shuffle shouldn't really make a difference if all invocations access the handle from the same place (like from a constant buffer, without indexing). This change allows bindless elimination to "see through" the shuffle operation.
This pattern generally shows up on games using `SAM` and `RAM` shader instructions (which are currently printed on the log as not implemented).
Fixes missing cubemap reflections on Detective Pikachu.
Before:
After:
Fixes #5901.
=> Extend bindless elimination to see through shuffle

src/Ryujinx.Ui.Common/App/ApplicationLibrary.cs
Just encountered this thanks to my broken keyboard pasting the target for my symlink twice.
---
Fixes #5341
=> ApplicationLibrary: Skip invalid symlinks

src/Ryujinx.Ava/AppHost.cs, src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs, src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
Fixes #5745 
Both the mute button and the mute keybind (F2) now respect the temporary value set via the in-bar flyout slider after unmuting.
cc: @MutantAura
=> Ava UI: Fix temporary volume not being set after unmute

src/Ryujinx.HLE/HOS/Kernel/Memory/KPageTableBase.cs, src/Ryujinx.HLE/HOS/Kernel/Memory/MemoryAttribute.cs, src/Ryujinx.HLE/HOS/Kernel/Memory/MemoryState.cs, src/Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
This was added on firmware version 17.0.0 to support `relro`.
Allows NSO Nintendo 64 to work with firmware version 17.0.0 (the JIT service requires it on this firmware):
Fixes #5993.
Testing welcome.
=> Add support for PermissionLocked attribute added on firmware 17.0.0

src/Ryujinx.HLE/Loaders/Processes/ProcessLoaderHelper.cs
We can't get the version string from the nacp for firmware titles (it is empty), instead use the firmware version. This fixes an issue where changing firmware version would cause games using the JIT service to crash, because it would load the PPTC cache from the previous firmware version, which is not compatible with the new firmware binary.
This is likely a regression caused by the refactoring around that code some time ago.
Fixes #6021.
=> Fix PPTC version string for firmware titles

Directory.Packages.props, src/Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/ManagerServer.cs, src/Ryujinx.HLE/Ryujinx.HLE.csproj
Replaces deprecated and vulnerable `System.IdentityModel.Tokens.Jwt` 7.0.3 with `Microsoft.IdentityModel.JsonWebTokens` 7.2.0.
---
- Fixes GHSA-59j7-ghrg-fj52
- Fixes GHSA-8g9c-28fc-mcx2
=> Switch to `Microsoft.IdentityModel.JsonWebTokens`

src/Ryujinx.Ava/UI/ViewModels/AmiiboWindowViewModel.cs, src/Ryujinx/Ui/Windows/AmiiboWindow.cs
This PR fixes a regression from 1.1.1102 (#3681) by making sure `Amiibo.json` exists before we try to read it.
This PR also addresses a few other issues in the Amiibo loading code:
- We now actually log the exceptions, so it's easier to help with or debug issues.
- Instead of closing the dialog when aren't able to download Amiibo data, we now show the successfully parsed local `Amiibo.json` data to the user.
- A few more try/catch statements have been added, so we still parse the local `Amiibo.json` in case one of the HTTP requests threw an exception before.
---
Fixes #6094
=> Fix Amiibo regression and some minor code improvements

src/Ryujinx.Graphics.Gpu/Engine/Threed/DrawManager.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/DrawState.cs, src/Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs
Some draw commands have passes the parameters (such as vertex count as first vertex) "inline", and does not modify 3D engine state. This currently causes a problem, where the vertex buffer sizes are calculated using the new inline vertex count, but when a draw using 3D engine state happens, it does not detect the count as being modified (since the inline draw did not modify it), and keeps using the previous vertex buffer size.
This PR fixes the issue by forcing a vertex buffer update when switching between inline and state parameter draws.
Fixes rendering on Citizens of Space (it was using the wrong vertex buffer size for a specific draw, and last vertex was 0 as a result).
Before:
After:
Fixes #5974.
=> Fix vertex buffer size when switching between inline and state draw parameters

src/Ryujinx.Graphics.Vulkan/BufferHolder.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
This prevents a small allocation each time this method is called. This is a top 3 SOH allocation during gameplay in most games, and eliminating it is pretty free.
Not much change expected. Biggest offender for SOH allocations is actually scheduler.
=> Vulkan: Cache delegate for EndRenderPass

src/ARMeilleure/Translation/Translator.cs, src/Ryujinx.Ava/AppHost.cs, src/Ryujinx.Graphics.Gpu/GpuContext.cs, src/Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs, src/Ryujinx.HLE/HOS/ArmProcessContext.cs, src/Ryujinx.Headless.SDL2/Program.cs, src/Ryujinx.Headless.SDL2/WindowBase.cs, src/Ryujinx.Tests/Cpu/CpuTest.cs, src/Ryujinx.Tests/Cpu/CpuTest32.cs, src/Ryujinx/Ui/MainWindow.cs, src/Ryujinx/Ui/RendererWidgetBase.cs
We current have a static field event on `ARMeilleure.Translator`, which is initially unsignaled, and we signal it once shader cache load is finished. This prevents the game from running before the shader cache has been loaded, but there are many problems with it:
- It is not reset consistently across UI, only GTK seems to reset it, which means that Avalonia probably doesn't wait for shader cache load on the 2nd launch onwards.
- Does not play nicely with multiple execution engines (as it only exists on ARMeilleure). For example, I think it currently does not wait for shader cache load when using hypervisor on macOS (but it would be hard to notice since GPU does not process commands until shader cache is loaded, so most games would get stuck until it is loaded anyway).
- It is bad design …
=> Change shader cache init wait method

src/Ryujinx.Common/Configuration/AppDataManager.cs
Adds support for using a portable directory placed next to the macOS app bundle. Currently the logic just checks if a portable directory is next to the actual executable, which only works as intended when running Ryujinx as a standalone executable.
I wasn't able to find any proper API for getting the bundle directory in .NET, so I used a similar method to what the updater does to find the bundle path.
Tested this on my Mac to verify it works as intended.
=> Support portable mode using the macOS app bundle.

src/Ryujinx.Graphics.Vulkan/DescriptorSetTemplate.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetTemplateUpdater.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/ShaderCollection.cs, src/Ryujinx.Graphics.Vulkan/VulkanConfiguration.cs
This PR changes the descriptor updater to use descriptor update templates unique to each program. A descriptor update template describes all of the descriptor fields that will be updated at the same time, and how their values will be laid out in memory. Each template defines one subset of descriptors that will be updated, you can't omit or add any without creating another template. This makes sense for us, since we always update all descriptors that are used for a program when updating a descriptor set (as we don't keep track of its existing state).
The descriptors are assumed to update in segment order, and be back to back in memory. There's a simple class for pushing data into a native array that can then be submitted as part of a descriptor update.
The old code for non-templated …
=> Vulkan: Use templates for descriptor updates

src/Ryujinx.Audio/Backends/CompatLayer/Downmixing.cs
This fixes two related on the surround to stereo downsampling code:
- While the result of a multiplication between 2 16-bit values will always fit on a 32-bit integer, adding 4 of such values can overflow. To fix that, I have changed the type of the coefficients from int to long, which will not overflow.
- Even if we fix the overflow above, for PCM16 output we still need a 16-bit value, and the previous code was truncating the value. This was fixed by clamping the value.
Fixes #5275.
=> Fix integer overflow on downsample surround to stereo

src/Ryujinx.Input.SDL2/SDL2GamepadDriver.cs, src/Ryujinx.Input/HLE/NpadManager.cs
Controllers were identified before by a combination of their _global_ index in the list of controllers and their GUID. The problem is, disconnecting and reconnecting a controller can change its global index; the controller can appear at the end when it was originally at the start. This would give it another ID, and the controller would need to be reconfigured.
This happened to me a lot with a switch pro controller and a USB game controller, it was essentially random which appeared first, and sometimes I had to pull cables or reconfigure the controllers. Now, it consistently detects them.
This PR changes the controller identification to be a combination of an index of controllers with the same GUID (generally 0), and its GUID. It also reworks managing the list of controllers to properly …
=> Input: Improve controller identification

src/Ryujinx.Graphics.Gpu/Image/TextureCache.cs
If two textures with different size overlap in memory, a copy dependency is created to ensure modifications to one textures flows into the other as needed. When the copy dependency is created, the assumption is that the existing texture has the latest data, so its data is copied to the new texture. This is a problem when the new texture is larger than the existing one, because the remaining width/height of the new texture will remain untiliased. To fix that, this PR forces the new texture to load its data from CPU if the width or height is greater than that of the existing texture.
Fixes text rendering on Shantae and the Pirate's Curse (regression caused by #4364).
Before:
After:
Testing is welcome, texture cache related changes are prone to exploding.
=> Fix missing data for new copy dependency textures with mismatching size

src/Ryujinx.HLE/FileSystem/VirtualFileSystem.cs
LibHac supports returning the timestamps in Windows File Time or Unix timestamps. AFAIK Horizon only ever returns Unix timestamps. This PR changes the code to use a `LocalFileSystem` overload that allows Unix timestamps to be enabled. All the other overloads default to true, except the one that we use...
Fixes #6151.
Example:
Before:
After:
=> Use unix timestamps on GetFileTimeStampRaw

src/Ryujinx.Graphics.Vulkan/Queries/CounterQueue.cs
Turns out that `ElementAt<T>` for `Queue<T>` runs the default implementation as it doesn't implement `IList<T>`, which enumerates elements of the queue up to the given index. This code was creating `count` enumerators and iterating way more queue items than it needed to at higher counts. The solution is just to use one enumerator and break out of the loop when we get the count that we need.
3.5% of backend time was being spent _just_ enumerating at the usual spot in SMO. Only affects games using occlusion queries.
=> Vulkan: Enumerate Query Pool properly

src/Ryujinx.Graphics.Vulkan/BufferHolder.cs, src/Ryujinx.Graphics.Vulkan/BufferManager.cs, src/Ryujinx.Graphics.Vulkan/Effects/FsrScalingFilter.cs, src/Ryujinx.Graphics.Vulkan/Effects/FxaaPostProcessingEffect.cs, src/Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs, src/Ryujinx.Graphics.Vulkan/HelperShader.cs, src/Ryujinx.Graphics.Vulkan/StagingBuffer.cs
Helper shaders and post processing effects typically need some parameters to tell them what to do, which we pass via constant buffers that are created and destroyed each time.
This can vary in cost between different Vulkan drivers. It shows up on profiles on mesa and MoltenVK, so it's worth avoiding. Some games only do it once (BlitColor for present), others multiple times. It's also done for post processing filters and FSR upscaling, which creates two buffers.
For mirrors, I added the ability to reserve a range on the staging buffer for use as any type of binding. This PR allows these constant buffers to instead be temporarily reserved on the staging buffer similar to mirrors, skipping allocation and buffer management costs entirely. If there isn't enough space for the reservation, it …
=> Vulkan: Use staging buffer for temporary constants

src/Ryujinx.HLE/HOS/Services/Ssl/SslService/SslManagedSocketConnection.cs
This PR implements a workaround for an issue mentioned in #5579 where the switch was able to interact with the GitHub API while Ryujinx crashed with an `AuthenticationException`.
Although this does fix the issue, it doesn't reflect the behavior of the switch. I originally wanted to fix this issue properly and reverse ssl far enough to figure this part out, but unfortunately I didn't get far enough and don't have the time currently to dive deeper into this.
=> ssl: Work around missing remote hostname for authentication

src/Ryujinx.Ava/AppHost.cs, src/Ryujinx.Graphics.GAL/HardwareInfo.cs, src/Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs, src/Ryujinx.Graphics.Vulkan/VulkanPhysicalDevice.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs, src/Ryujinx.Headless.SDL2/WindowBase.cs, src/Ryujinx/Ui/RendererWidgetBase.cs
This PR handles #3682 by displaying the more specific driver name in the status bar rather than only the device vendor. OpenGL has no such API, so there we just continue to display the vendor name.
In many cases such as Windows/NV the name displayed for the vendor and the driver are the same. Seeking testers on Linux to confirm.
=> Use driver name instead of vendor name in the status bar for Vulkan.

src/Ryujinx.Ava/Assets/Locales/en_US.json, src/Ryujinx.Ava/UI/ViewModels/ModManagerViewModel.cs, src/Ryujinx.HLE/HOS/ModLoader.cs
Changes:
- Fixes a crash when selecting an invalid mod directory
- Fixes a crash when trying to enumerate through a directory that Ryujinx doesn't have permissions to access
- Fixes deleting a mod not deleting at the parent directory, leaving invisible orphan files that would prevent re-importing of the same mod
- Better logging and user feedback
TODO: More robust testing of folders to see if they contain valid mods before copying them to the mod directory. This will still copy invalid folders to the mod directory if they have subdirectories, where they won't appear in the list.
Since copying is recursive, this is especially important. Selecting a top-level folder by accident could be very expensive.
=> Ava UI: Mod Manager Fixes

src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/PipelineFull.cs, src/Ryujinx.Graphics.Vulkan/PipelineState.cs, src/Ryujinx.Graphics.Vulkan/ShaderCollection.cs, src/Ryujinx.Graphics.Vulkan/VulkanException.cs
Currently we skip draws when the background compilation of the shaders on Vulkan failed. This is detected with the result code from the pipeline creation call. If an is error returned, we assume that the host failed to compile the shader that the emulator gave. While this generally works, there is an odd situation on macOS with MoltenVK where *some* pipeline variants may compile successfully, and others may fail. This means that the emulator can still crash in some cases due to shader compilation failures.
This PR allows draws to be skipped when *any* pipeline variant creation fails, not just the background one. This is only done for graphics shaders since compute generally doesn't have pipeline variants (since the only pipeline state on compute is the shader itself). This also includes …
=> Allow skipping draws with broken pipeline variants on Vulkan

.editorconfig, .github/workflows/checks.yml, .github/workflows/mako.yml, .github/workflows/pr_triage.yml, .github/workflows/release.yml, README.md
This PR includes a bunch of smaller changes and adds the new Mako workflow as previously announced in Ryujinx/Ryujinx-Mako#3.
The new Mako workflow:
- This workflow replaces the previous Ryujinx-Mako steps and should allow us to change Mako's behavior without changing any files here.
- It receives all the necessary information from the event that triggered the workflow, so we can execute the appropriate tasks for them. All of this is handled by the `exec-ryujinx-tasks` command.
Currently only the `update-reviewers` task will be executed, since I want to make sure everything works before adding more stuff on top of it.
- Although there are a lot of events that trigger this workflow, most runs shouldn't take longer than ~30 seconds, so hopefully we don't run into any issues because of that. …
=> infra: Reformat README.md & add new generic Mako workflow

src/Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
If `LocalEndPoint` is accessed before `Bind` is called on the socket, it will be null. This currently throws a `NullReferenceException`. On WinSocks, this would return an error, and on FreeBSD it would return a zero socket address, since it has not been set yet. It has been changed to write a zero socket address to match FreeBSD behaviour (the Switch uses FreeBSD code for the sockets implementation).
Fixes #6203.
=> Fix NRE when calling GetSockName before Bind

src/Ryujinx.Ava/UI/Helpers/ContentDialogHelper.cs, src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
This PR updates `CheckLaunchState()` to  be async, since we don't want to open multiple dialogs at the same time.
This allows people opening Ryujinx for the first time to actually interact with the window again.
Note: The mod manager is currently prone to the same issue due to the usage of `Dispatcher.UIThread.Post()` with an async lambda.
=> Avalonia: Fix dialog issues caused by 1.1.1105

src/Ryujinx.Ava/UI/Models/ModModel.cs, src/Ryujinx.Ava/UI/ViewModels/ModManagerViewModel.cs
- Fixed a typo in the error message when the mod fails to delete
- Fixed deleting mods from non-Atmosphere directory
- Fixed deleting non-subdirectory mods
- Fixed excessive looping if parent directory is found
=> Ava UI: Mod Manager Fixes (Again)

src/Ryujinx.Horizon/Sdk/Sf/Hipc/HipcMessage.cs, src/Ryujinx.Horizon/Sdk/Sf/Hipc/HipcMessageData.cs, src/Ryujinx.Horizon/Sdk/Sf/HipcCommandProcessor.cs
Fixes a regression from #6174 that was causing Animal Crossing to crash on load.
The offset for the pointer buffer sizes was calculated as if the data array still had the padding on, but the actual array it accessed had the padding removed, which causes a `IndexOutOfRangeException`.
=> Fix exception when trying to read output pointer buffer size

src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs, src/Ryujinx.Common/Logging/Targets/FileLogTarget.cs, src/Ryujinx.Headless.SDL2/Program.cs, src/Ryujinx.Ui.Common/Configuration/LoggerModule.cs, src/Ryujinx/Ui/MainWindow.cs
This small PR fixes an issue caused by #4707 where the menu item to open the log directory opens the wrong one.
=> GUI: Fix opening the wrong log directory

src/Ryujinx.HLE/HOS/Services/ServerBase.cs
If a port was closed, we should stop listening to it, otherwise kernel will return the `PortRemoteClosed` error non-stop and we won't be signalled when other services try to connect to SM. This is a bug that was happening if anything else tried to connect to SM after a process has exited, it started happening after #5802 because it uses SM to connect to HLE services from other HLE services. It caused everything that uses the JIT service (NSO Nintendo 64, etc) to lock up upon trying to load said service.
This should also fix the "loading an applet from another applet" scenario from locking up, for the people that was messing with that.
=> Ensure SM service won't listen to closed sessions

src/Ryujinx.HLE/HOS/Services/ServerBase.cs
#6246 caused a regression on "multi-program" games (those that have multiple program NCAs inside and needs relaunch). This is working around the issue by only enabling the new behaviour for SM, while keeping what we did before the linked change for other services. This still works for games using the JIT service while not regressing multiple program applications.
Ultimately this code should be deleted and fully replaced by new IPC code, so I think this solution is good enough for now.
=> Limit remote closed session removal to SM service

src/Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs
Yet another case of redundant operands being added to the list, and it causing problems later on. Texture gather with depth compare does not need a RGBA component being specified, because what is being sampled is a depth texture, so there is only the depth to select.
This fixes a crash translating shaders on the game Hotshot Racing on Vulkan.
=> Remove component operand for texture gather with depth compare

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Instructions/InstEmitTexture.cs
In register order, the depth compare value comes after the offset, but IR operands (and GLSL function signature/SPIR-V) expect the depth compare value to be before the offset. Fix it by inverting their order.
Fixes shadows in Hotshot Racing.
Before:
After:
=> Fix depth compare value for TLD4S shader instruction with offset

src/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs
Reverts change introduced on #5755. I incorrectly assumed there is no need to flush a texture if the overlap size is 0, but that is not the case since the `RegionHandle` will remove the flush action for the entire page at least, so it could cause flush for some textures to be lost. The fact that the size can be 0 (or potentially "negative") is in itself an issue, but I don't think it will cause problems right now.
Fixes #6244.
=> Revert change to skip flush when range size is 0

src/Ryujinx.Ava/UI/Helpers/ContentDialogHelper.cs
Fixes #6222 
Resolve an issue where changes to the main window's positioning could cause the application to crash if a modal was dismissed beforehand.
To be honest, we probably should be unbinding the OverlayOnPositionChanged event before the window closes for memory reasons. But I'll let the reviewers dictate if thats a priority.
=> [UI] Fix Crash when Windows is moved after a modal is dismissed

src/Ryujinx.HLE/HOS/Services/Account/Acc/AccountService/ManagerServer.cs
This method appears to indicate that the token returned should be cached. I've made it so that it generates a token that lasts until its expiration time, and reuses it on subsequent calls. I'm not sure why this was so slow before.
This should fix an issue where Monopoly for Nintendo Switch tanks its framerate by asking for a token very frequently.
=> AccountService: Cache token data

src/Ryujinx.Common/Logging/Logger.cs
These changes cover all logging methods except for `PrintRawMsg` since that doesn't use `FormatMessage`, where the actual redaction happens. I don't *think* user directory paths ever pass through `PrintRawMsg` so this should be fine.
In my testing, this properly replaced the substring `C:\Users\myusernamehere\` with `C:\Users\[redacted]\`.
I couldn't test this on macOS or Linux, but the special folder tables for those systems I found online suggest that it would Just Work(tm):
* for macOS: https://johnkoerner.com/csharp/special-folder-values-on-windows-versus-mac/
* for Linux (Red Hat specifically, but it should be the same elsewhere): https://developers.redhat.com/blog/2018/11/07/dotnet-special-folder-api-linux#environment_getfolderpath
I chose to replace whole path segments instead of …
=> Redact usernames from logs

Directory.Packages.props
This updates to SDL2 2.30.0 release commit.
This package also now comes with a linux-arm64 build.
=> chore: Update Ryujinx.SDL2-CS to 2.30.0

src/Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs
Setting a vertex buffer size that is too high is fairly inconsequential on the Switch, as it is only used for bounds checking. However on emulator it is problematic since we use those sizes as the actual vertex buffer size. Some games set very high sizes, for this reason we have a few tricks in places to try reducing the size. This PR adds another way to reduce the size. If the size is higher than a given threshold (currently 256 MB), it will set the size to the amount of memory that is actually mapped instead. This does not work well with sparse buffers, but we currently don't support sparse vertex buffers anyway (it assumes that the vertex buffer is a single contiguous range).
Fixes Infinite Tanks World War 2 (still does not render correctly due to an unsupported render target format): …
=> Clamp vertex buffer size to mapped size if too high

Directory.Packages.props, src/Ryujinx.Ava/Ryujinx.Ava.csproj, src/Ryujinx.Ava/UI/Controls/ApplicationGridView.axaml, src/Ryujinx.Ava/UI/Views/User/UserSelectorView.axaml, src/Ryujinx.Ava/UI/Windows/AboutWindow.axaml
This PR changes Grid View, User Profile Selector and About window to use a Wrap Panel instead of a Flex Panel. Closes Feature Request #5055. Allows consistency between List view and Grid view and removes dependency. Changing size and showing names works as usual. Below are comparisons vs Master.
-------------------------------------------------------------------------------------------------
Master Grid View:
PR Grid View:
-------------------------------------------------------------------------------------------------
Master About Window:
PR About Window:
-------------------------------------------------------------------------------------------------
Testing:
People with many games and profiles should test this to compare to behavior in master and please report here.
=> Replace Flex Panels in favor of Wrap Panels for Avalonia

Directory.Packages.props, src/Ryujinx.Ava/Ryujinx.Ava.csproj
This bumps Avalonia to 11.0.8, including the fix for Steam Deck window.
With this version, Ava is getting closer to become the default on all platforms.
This update also removes a dependency on SDC, which means we can remove it from the Ava project, ~~but it persists in UI.Common for now.~~ Removed from UI.Common in #6275
=> Ava UI: Bump Version

src/Ryujinx.Graphics.Vic/Ryujinx.Graphics.Vic.csproj
`Ryujinx.Graphics.Vic` has an unnecessary/unused reference to `Ryujinx.Graphics.Host1x`, this removes that reference.
=> Infra: Remove Vic Reference to Host1x

src/Ryujinx.Cpu/LightningJit/Arm32/Block.cs, src/Ryujinx.Cpu/LightningJit/Arm32/Decoder.cs, src/Ryujinx.Cpu/LightningJit/Arm32/MultiBlock.cs, src/Ryujinx.Cpu/LightningJit/Arm32/RegisterAllocator.cs, src/Ryujinx.Cpu/LightningJit/Arm32/Target/Arm64/Compiler.cs, src/Ryujinx.Cpu/LightningJit/Arm32/Target/Arm64/InstEmitFlow.cs, src/Ryujinx.Cpu/LightningJit/Arm32/Target/Arm64/InstEmitSystem.cs
When we do a managed call on JIT generated code, we need to place all caller saved registers somewhere, since the managed function might overwrite their values. Normally we store them on the stack, however for guest state, we can store them in the context struct, and avoid using the stack this way. This PR changes the "sync point"/interrupt check to use the guest context to store the guest register values, instead of the stack. Then, it changes the stack reservation size calculation to account for the cases where we store the guest states to context, in those cases we only need to reserve 16 bytes as we will only store 2 pointers, the context pointer and the guest address space base pointer.
This reduces the stack usage by a lot in some cases, and notably fixes #6236 which is caused by a …
=> LightningJit: Reduce stack usage for Arm32 code

Directory.Packages.props, src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs, src/Ryujinx.Ui.Common/Ryujinx.Ui.Common.csproj
Replaces our one remaining use of SDC with ImageSharp. Alongside #6271, this removes SDC entirely from Ryujinx.
=> Infra: Remove SDC

Directory.Packages.props
I forgot to update it for a while, so for now let's bump to the latest version of the 5.0.x channel.
This also add linux-arm64 natives.
=> misc: Update to Ryujinx.Graphics.Nvdec.Dependencies 5.0.3-build14

src/Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs
We can't use the direct texture upload optimisation if component remapping is enabled, and not identity (RGBA -> RGBA), because texture upload alone can't change the component order of the texture. To fix this, disable direct texture upload in this case, and do a software CPU side copy, which can perform the remapping.
Should fix some bugs with inverted RGBA components on the game 30XX (tested by Muffin, I don't have this game).
=> Force CPU copy for non-identity DMA remap

src/Ryujinx.SDL2.Common/SDL2Driver.cs
The SDL driver was loading custom mappings from the directory alongside the application binary. This was improper and would lead to code signature issues on macOS and other possible issues for other platforms. Not to mention being wiped along with every Ryujinx update.
This PR changes the driver to look inside `AppDataManager`'s `BaseDirPath` instead, which is already initialized to point toward the correct configuration directory for the instance of Ryujinx being run.
Address some comments on https://github.com/Ryujinx/Ryujinx/issues/4053 and possibly others.
=> Load custom SDL mappings from application data folder

src/Ryujinx.Ava/UI/Renderer/SPBOpenGLContext.cs, src/Ryujinx.Graphics.OpenGL/BackgroundContextWorker.cs, src/Ryujinx.Graphics.OpenGL/IOpenGLContext.cs, src/Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs, src/Ryujinx.Headless.SDL2/OpenGL/OpenGLWindow.cs, src/Ryujinx/Ui/SPBOpenGLContext.cs
This makes IOpenGLContext.HasContext not static and be implementable.
By doing this, we can support more than WGL and WGL.
This also allows the SDL2 headless version to run under Wayland.
=> Make IOpenGLContext.HasContext context dependent

src/Ryujinx.Graphics.Shader/Translation/EmitterContext.cs
Previously we were only doing it for Vulkan, but it turns out that not setting it when PROGRAM_POINT_SIZE is set is considered UB on OpenGL Core.
=> Set PointSize in shader on OpenGL

.github/workflows/build.yml, .github/workflows/release.yml, src/Ryujinx.Ava/Ryujinx.Ava.csproj, src/Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj, src/Ryujinx/Ryujinx.csproj
This enable building and releases for Linux ARM64 as the core native dependencies are now built for it.
=> ci: Enable Linux ARM64 on build and release

src/Ryujinx.Audio.Backends.SoundIo/Ryujinx.Audio.Backends.SoundIo.csproj, src/Ryujinx.Ava/Ryujinx.Ava.csproj, src/Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj, src/Ryujinx.Ui.Common/Ryujinx.Ui.Common.csproj, src/Ryujinx/Ryujinx.csproj
The first release package for linux-arm64 contains unneeded libraries, this should fix it.
=> Add missing RID exclusions for linux-arm64

src/Ryujinx.Graphics.Vulkan/TextureView.cs
Currently we only support setting/getting a single slice of a 3D texture, or the whole texture (controlled by the `singleSlice` parameter). Since #4401, this was no longer taken into account, and it would effectively calculate the mip size as if the texture only had one slice (because `dstLayers` will be always 1 for 3D textures). This causes problem for full texture uploads if the 3D texture depth is > 1, it will calculate the wrong size which causes all mip levels other than the base level to be copied from the wrong input offset.
This change fixes the issue by using the full texture size is we are doing a 3D copy and `singleSlice` is false, rather than the size of a single slice. Similar logic is already used to calculate texture depth:
```cs
int depth = is3D && !singleSlice ? …
```
=> Fix mip offset/size for full 3D texture upload on Vulkan

src/Ryujinx.Ava/UI/Windows/AboutWindow.axaml
Update about window to have Logo and "Ryujinx" in center and adjacent as requested in PR #6267.
---
Before:
After:
=> Update Avalonia About Window like requested in PR #6267

src/Ryujinx.Ava/UI/Windows/ModManagerWindow.axaml
These snuck in at some point; they are unnecessary.
=> Ava UI: Remove ReflectionBinding in Mod Manager

distribution/linux/Ryujinx.sh
Hi, I want to contribute. Also, see https://github.com/NixOS/nixpkgs/pull/278605.
* Avoid Ryujinx.Headless.SDL2 as a last resort in Ryujinx.desktop if you have all three executables installed.
=> Linux: Reorder available executables in Ryujinx.sh

src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs, src/Ryujinx.Common/Configuration/AppDataManager.cs, src/Ryujinx.Common/Logging/Targets/FileLogTarget.cs, src/Ryujinx.Headless.SDL2/Program.cs, src/Ryujinx.Ui.Common/Configuration/LoggerModule.cs, src/Ryujinx.Ui.Common/Helper/OpenHelper.cs, src/Ryujinx/Ui/MainWindow.cs
Unifies log directory finding and creation in `AppDataManager`, and ensures logs are created in the intended, correct places on each platform.
The preferred directory hierarchy is the following.
Windows: Prefer a 'Logs' folder in whatever directory Ryujinx was launched from; fall back to `%APPDATA%\Ryujinx\Logs`.
Mac: Prefer `~/Library/Logs/Ryujinx`. Fall back to `~/Library/Application Support/Ryujinx/Logs`.
Linux: Use `~/.config/Ryujinx/Logs`.
https://github.com/Ryujinx/Ryujinx/commit/70fcba39de34fc211d09da12783898161724b0dc had an unfortunate quality escape where logs on macOS were being written to the executable directory, which is within the .app bundle. This was invalidating the code signature of the app bundle, which can lead to various unintended side effects. This PR addresses …
=> Standardize logging locations across desktop platforms

.github/workflows/flatpak.yml
Required when building on the arm64 runner.
=> infra: Force add linux-x64 apphost in flathub nuget source

src/Ryujinx.Common/Configuration/AppDataManager.cs, src/Ryujinx.UI.Common/Configuration/ConfigurationFileFormat.cs, src/Ryujinx.UI.Common/Configuration/ConfigurationState.cs
When .NET 8 was merged, there were some breaking changes to `Environment.SpecialFolder` values on macOS. One was immediately noticed, the change of `SpecialFolder.Personal` from `~/` to `~/Documents/`. This was addressed by https://github.com/Ryujinx/Ryujinx/pull/5941. Another important change was that of `SpecialFolder.ApplicationData` from `~/.config/` to `~/Library/Application Support`, correcting a longstanding discrepancy between macOS and Linux.
Now let's briefly go back in time to a commit dating from 2020 in `AppDataManager`, which got ahead of .NET, moving Mac configuration files from `~/.config/Ryujinx/` to `~/Library/Application Support/Ryujinx` to fix this discrepancy. The code block that does this is partially excerpted below:
```c#
if (OperatingSystem.IsMacOS() && Mode == …
```
=> macOS: Stop storing user data in Documents for some users; fix symlinks

src/Ryujinx.Common/Configuration/AppDataManager.cs
Version 1191 (#6241) began checking if the users data directory is a symlink on all operating systems, which resulted in an uncaught exception if the user data directory did not exist. This PR surrounds the symlink checking function in a try catch.
Resolves #6303.
=> Handle exceptions when checking user data directory for symlink

src/Ryujinx.Ava/Assets/Locales/en_US.json, src/Ryujinx.Ava/Modules/Updater/Updater.cs, src/Ryujinx/Modules/Updater/Updater.cs
Removes x86 Architecture checks from Ava and GTK updaters. Since the release on Linux ARM builds, this check is now causing problems.
Also adds a check to select the correct archive depending on architecture.
=> Updaters: Fix ARM Linux Updater

src/Ryujinx.Graphics.Vulkan/VulkanInitialization.cs
There's no point in enabling that as we don't use the subgroup size extension anymore, so this is just a leftover.
This actually causes problem for Dozen since it apparently does expose the extension, but does not actually support it, so it would  fail to create the device if we enable it. Thanks to @jduncanator for finding the issue.
=> Remove Vulkan SubgroupSizeControl enablement code

src/Ryujinx.HLE/HOS/Kernel/Memory/KPageTableBase.cs
The check was wrong before, which caused `UnloadRo` on the RO service to return an error, since unmapping the memory would fail, which in turn causes the games using this service and targeting firmware 17.0.0 or newer to crash.
Allows the other games to work on Tomb Raider I-III Remastered Starring Lara Croft (still requires ignore missing service).
Depends on #6313 (just for testing purposes).
=> Fix PermissionLocked check on UnmapProcessCodeMemory

src/Ryujinx.Graphics.GAL/Format.cs, src/Ryujinx.Graphics.Gpu/Engine/Types/ZetaFormat.cs, src/Ryujinx.Graphics.Gpu/Image/FormatTable.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs, src/Ryujinx.Graphics.OpenGL/FormatTable.cs, src/Ryujinx.Graphics.OpenGL/Framebuffer.cs, src/Ryujinx.Graphics.OpenGL/Image/TextureCopy.cs, src/Ryujinx.Graphics.Vulkan/EnumConversion.cs, src/Ryujinx.Graphics.Vulkan/FormatCapabilities.cs, src/Ryujinx.Graphics.Vulkan/FormatTable.cs, src/Ryujinx.Graphics.Vulkan/TextureStorage.cs
- Implemented X8Z24 sampled image format, along with corresponding backend format.
- Rename ZETA formats to match official names.
- Fix X8Z24 render target format, that was using D24S8 backend format. It was changed to use the new X8Z24 format.
- Minor refactoring on OpenGL to reduce code duplication for some depth-stencil format related helper functions.
Fixes some lighting issues on Tomb Raider I-III Remastered Starring Lara Croft.
Before:
After:
=> Implement X8Z24 texture format

src/Ryujinx.Graphics.Vulkan/Constants.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetTemplate.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetTemplateUpdater.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, src/Ryujinx.Graphics.Vulkan/HardwareCapabilities.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/PipelineLayoutCacheEntry.cs, src/Ryujinx.Graphics.Vulkan/ShaderCollection.cs, src/Ryujinx.Graphics.Vulkan/Vendor.cs, src/Ryujinx.Graphics.Vulkan/VulkanConfiguration.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
Followup to https://github.com/Ryujinx/Ryujinx/pull/6014. Uses push descriptors for uniform buffers when possible - when it's not possible it just falls back to the regular descriptor set with templated updates.
Push descriptors are also using templated updates, since it allows us to submit multiple bindings in one call. This is useful when all the bindings change, or we have to resubmit the bindings due to a pipeline layout change. There's a dictionary lookup for the template within the pipeline layout, but there's a fast path if it's the same updated bindings as last time.
There can only be 32 push descriptors, but we tend to have 37 uniform buffer bindings when fragment and vertex are both using uniforms. The chosen solution to this problem is to select a subset of uniforms that are …
=> Vulkan: Use push descriptors for uniform bindings when possible

src/Ryujinx.Graphics.GAL/IPipeline.cs, src/Ryujinx.Graphics.GAL/Multithreading/Commands/SetImageCommand.cs, src/Ryujinx.Graphics.GAL/Multithreading/ThreadedPipeline.cs, src/Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, src/Ryujinx.Graphics.Gpu/Memory/BufferManager.cs, src/Ryujinx.Graphics.OpenGL/Pipeline.cs, src/Ryujinx.Graphics.Vulkan/BarrierBatch.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, src/Ryujinx.Graphics.Vulkan/Effects/FsrScalingFilter.cs, src/Ryujinx.Graphics.Vulkan/Effects/FxaaPostProcessingEffect.cs, src/Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs, src/Ryujinx.Graphics.Vulkan/FramebufferParams.cs, src/Ryujinx.Graphics.Vulkan/HelperShader.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/PipelineFull.cs, src/Ryujinx.Graphics.Vulkan/TextureStorage.cs, src/Ryujinx.Graphics.Vulkan/TextureView.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
This PR aims to fix a few issues caused by barriers being in the wrong place, and generally being missing for render pass load and store ops. The main goal here is to fix rendering on Adreno GPUs using the turnip Mesa driver on linux.
It's possible that every bound texture in a draw was previously drawn, that every framebuffer load was previously stored, so it makes sense that the barriers for them should be batched into less calls for more resources. The batching works by queuing the requested barrier with pipeline stage flags. The queued barriers are flushed when a command buffer ends, before a render pass begins, before a draw or before a compute dispatch. Flushing the `BarrierBatch` groups barriers by pipeline stage flags and submits all of them in batches with a maximum of 16 of each …
=> Vulkan: Improve texture barrier usage, timing and batching

src/Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
Should fix Tomb Raider I-III Remastered and other games that call this service from crashing without enabling Ignore Missing Services. 
Please review this carefully to ensure that this doesn't cause any other unrelated issue or if anything is missing from this PR.
Resolves #6321
=> hid: Stub SetTouchScreenResolution

src/Ryujinx.Ava/Program.cs
Enable input focus proxy, makes WM_TAKE_FOCUS capability to be exposed.
This fix menu on gamescope, for real this time....
=> Avalonia: Fix gamescope once and for all

src/Ryujinx.Graphics.Vulkan/BarrierBatch.cs
If more than 16 barriers were queued at one time, the _queuedBarrierCount would no longer match the number of remaining barriers, because when breaking out of the loop consuming them it deleted all queued barriers, not just the 16 that were consumed.
Should fix freezes that started occurring with #6240. Fixes issue #6338.
=> Vulkan: Fix barrier batching past limit

src/Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, src/Ryujinx.Graphics.Vulkan/ShaderCollection.cs
Disables push descriptors on older NVIDIA GPUs (10xx and below), since it is clearly broken beyond comprehension. The existing workaround wasn't good enough and a more thorough one will probably cost more performance than the feature gains. The workaround has been removed.
Fixes #6331.
=> Vulkan: Disable push descriptors on older NVIDIA GPUs

src/Ryujinx.Graphics.Vulkan/BarrierBatch.cs
Forgot to set the end variable here. Should stop it from crashing when this path is taken.
=> Vulkan: Properly reset barrier batch when splitting due to mismatching flags

src/Ryujinx.Graphics.Gpu/Memory/Buffer.cs, src/Ryujinx.Graphics.Gpu/Memory/BufferCache.cs, src/Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs, src/Ryujinx.Graphics.Gpu/Memory/MultiRangeBuffer.cs, src/Ryujinx.Graphics.Gpu/Memory/VirtualBufferCache.cs, src/Ryujinx.Graphics.Gpu/Memory/VirtualRangeCache.cs
This is similar to #5427, but while the linked change required the host to support sparse buffer mapping on Vulkan, this one does not require anything special. If the host does support sparse mapping, nothing should change, it will continue using it. But if the feature is not supported, this change improves the implementation by creating "virtual" buffers, that are also backed by "physical" buffers, but instead of doing actual memory aliasing on the GPU, it creates copy dependencies. Every time a physical buffer is updated, the data is also copied to the virtual buffer. The virtual buffer keeps track of GPU modifications, and copies it back on use (`SynchronizeMemory` call).
This should benefit platforms where sparse buffer mapping is not supported on Vulkan (macOS), and OpenGL.
Fixes …
=> Implement virtual buffer dependencies

src/Ryujinx.HLE/HOS/Horizon.cs, src/Ryujinx.HLE/Switch.cs
SM `RegisterService` method accesses the `System` instance on `context.Device.System.KernelContext`. However, because services are initialized from the `Horizon` constructor, it is possible that the `System` field has no been assigned yet because the constructor has not finished running. In those cases, if a service tries to register itself before the constructor finishes running, it would cause a NRE. This change fixes the issue by only initializing services after `Horizon` constructor is done as `System` has been assigned.
This issue was manifesting itself as a rare crash when launching games, usually for he 2nd time or later.
=> Ensure service init runs after Horizon constructor

src/Ryujinx.Graphics.OpenGL/Pipeline.cs, src/Ryujinx.Graphics.OpenGL/Program.cs
This appears to match Vulkan's behaviour, which is needed for stencil shadows in Penny's Big Breakaway. It's far from the only issue, you can try the Full Bindless PR if you want to see it in a more intact state.
It's possible there's more to this, there's a constant color rendering register which could enable the color output without a fragment shader, but I don't think it will be used for anything nowadays, and it doesn't seem to support different values for different attachments. All the cases I've seen just want depth only draws, anyways.
https://github.com/NVIDIA/open-gpu-doc/blob/master/classes/3d/clb197.h#L1230
=> OpenGL: Mask out all color outputs with no fragment shader

src/Ryujinx.Horizon.Generators/Hipc/HipcGenerator.cs, src/Ryujinx.Horizon/Sdk/Sf/HipcCommandProcessor.cs
Changes to the `HipcGenerator` source generator that improve the generated code.
Changes to generated code:
- avoid making do-nothing calls to `MemoryMarshal.Cast<byte, byte>()`
- generated methods with a `bool[] isBufferMapAlias` now create it as a `Span<byte>` via `stackalloc` instead of as  heap array.
- `IReadOnlyDictionary<int, CommandHandler> GetCommandHandlers()` no longer returns a `Dictionary`, instead it returns a `FrozenDictionary` which is optimized for lookup performance (and is actually read-only).
Changes to the generator:
- fix a couple private method name typos
=> IPC code gen improvements

src/Ryujinx.Graphics.Gpu/Image/FormatTable.cs
There is some precision error on AMD when using float formats for this, which causes images to be glitched when they are accessed on the shader. Using UInt formats fixes the issue. Other vendors don't seem to have a issue with either float or UInt formats.
Fixes a few OpenGL games that depend on different size aliasing, such as Wet Steps, CEIBA and Yokai Watch 1.
Before:
After:
=> Change packed aliasing formats to UInt

Directory.Packages.props, src/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRendererBase.cs, src/Ryujinx/UI/Windows/IconColorPicker.cs
This PR updates `SixLabors.ImageSharp` and `SixLabors.ImageSharp.Drawing` to the latest available versions before the license change.
> [!Caution]
> The license change for `SixLabors.ImageSharp` was introduced with `v3.0.0` and was added to `SixLabors.ImageSharp.Drawing` with `v2.0.0`.
---
Fixes GHSA-65x7-c272-7g7r
=> Update dependencies from SixLabors to the latest version before the license change 

src/Ryujinx.Cpu/AppleHv/HvMemoryManager.cs, src/Ryujinx.Cpu/Jit/MemoryManager.cs, src/Ryujinx.Cpu/Jit/MemoryManagerHostMapped.cs, src/Ryujinx.Cpu/VirtualMemoryManagerRefCountedBase.cs, src/Ryujinx.Memory/AddressSpaceManager.cs, src/Ryujinx.Memory/VirtualMemoryManagerBase.cs
This PR refactors the various memory managers to share a common abstract base class for the purpose of improving code reuse and consolidating similar implementations of algorithms like virtual-to-physical memory mapping.
In particular it consolidates the `void Read(ulong va, Span<byte> data)` implementations. There is much more that could be done, but I didn't want to do all that without gauging interest first.
This approach is an alternative to the `PagedMemoryRangeEnumerator` in pending PR #6251, which was added after @gdkchan mentioned it'd be desirable to consolidate the many implementations of that page mapping logic.  @riperiperi  raised performance concerns with the enumerator so I began exploring this common base class approach. I haven't benchmarked it but I expect this to …
=> Refactor memory managers to a common base class, consolidate Read() method logic

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/StructuredIr/PhiFunctions.cs
This fixes one problem that is usually called "swap problem" in the literature for Phi elimination. It is possible for some phi sources to also be the destination of another phi node in the same block. In this case, if the copies are done in the wrong order, the variable will have the wrong value (for example, it can do the copy after tha variable has already been overwritten with a newer value).
It also fixes the lost copy problem, which happens when we have a critical edge with a distinct version of a variable. We can't simply insert a single copy at the predecessor block in this case, as it might copy the wrong version of the variable if other copies have already been inserted there.
This is the most simple fix of the problem, it inserts a temporary variable, does a copy to the temp in …
=> Fix lost copy and swap problem on shader SSA deconstruction

src/Ryujinx/UI/Helpers/Win32NativeInterop.cs, src/Ryujinx/UI/Renderer/EmbeddedWindow.cs
Passthough mouse input for win32 embedded windows. Removes the need for rerouting native pointer events as avalonia pointer events.
=> Passthrough mouse for win32

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/CodeGen/Spirv/Declarations.cs
Adds the `PassthroughNV` decorator to geometry shader vertex struct types when GpPassthrough is enabled.
Reported by kakasita on discord, introduced by https://github.com/Ryujinx/Ryujinx/pull/5576 
Before:
After:
=> Fix geometry shader passthrough issue

src/Ryujinx.Graphics.Gpu/Image/AutoDeleteCache.cs
The current texture cache total size limit is 512 MB as established by #4350. This change increases that limit to  1024 MB. As a result, games that previously worked before #4350 was merged are playable again. The River City Girls Zero menu still renders correctly after this change.
Affects **resolution mods** for many titles that target higher resolutions than 1080p (more often 4K mods).
Tested and fixed games include but are not limited to:
Baten Kaitos I & II HD Remaster (fixes performance)
Demon Slayer: Kimetsu no Yaiba (fixes performance)
Prince of Persia: The Lost Crown (fixes crash on the map)
Princess Peach: Showtime Demo (fixes performance)
Star Ocean The Second Story R (fixes crash)
The Legend of Zelda: Tears of the Kingdom (fixes performance)
Thanks to @GamerzHell9137 and …
=> Increase texture cache total size limit to 1024 MB (1 GB)

.github/workflows/release.yml, src/Ryujinx/Modules/Updater/Updater.cs
This PR fixes an issue where old "test" Avalonia users were stuck on 1.1.1217 even after successfully applying the new update.
We now provide both "Ryujinx" and "Ryujinx.Ava" binaries for the old test release and make sure we migrate to the new release binary.
In a few weeks we should be able to remove the migration code and the old test-ava release again.
=> infra: Fix updater for old Ava users

src/ARMeilleure/Instructions/NativeInterface.cs, src/ARMeilleure/Memory/IMemoryManager.cs, src/Ryujinx.Cpu/AppleHv/HvMemoryManager.cs, src/Ryujinx.Cpu/IVirtualMemoryManagerTracked.cs, src/Ryujinx.Cpu/Jit/MemoryManager.cs, src/Ryujinx.Cpu/Jit/MemoryManagerHostMapped.cs, src/Ryujinx.Cpu/ManagedPageFlags.cs, src/Ryujinx.Graphics.Gpu/Image/Pool.cs, src/Ryujinx.Graphics.Gpu/Memory/Buffer.cs, src/Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs, src/Ryujinx.Memory/AddressSpaceManager.cs, src/Ryujinx.Memory/IVirtualMemoryManager.cs, src/Ryujinx.Memory/Tracking/MemoryTracking.cs, src/Ryujinx.Memory/Tracking/MultiRegionHandle.cs, src/Ryujinx.Memory/Tracking/RegionFlags.cs, src/Ryujinx.Memory/Tracking/RegionHandle.cs, src/Ryujinx.Memory/Tracking/VirtualRegion.cs, src/Ryujinx.Tests.Memory/MockVirtualMemoryManager.cs
This PR allows guest memory access and managed memory access (typically from the GPU processing thread) to have different memory tracking handles and protections. 
- Protection regions can be different for guest access. This is useful for the new host tracked memory manager in 16k page mode, as memory protection there only counts the first byte of the access. This causes issues when accesses are unaligned and cross over a page boundary, as it's possible to write data from the previous page without triggering pending actions or signalling the write flag. The solution here is to extend page protections to the previous page, but only for resources that require it, and only for guest accesses.
- This PR also adds the code that enables this; you can specify that a memory has "single byte guest …
=> Separate guest/host tracking + unaligned protection

src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
On Vulkan (and OpenGL) backends, the Polygon primitve topology is implemented with trinagle fans. Since macOS does not support triangle fans, we need to do the same conversion that we would do for triangle fans if the Polygon topology is used. This change updates `TopologyUnsupported` to consider the `Polygon` topology as unsupported too, and updates `TopologyRemap` to "remap" it.
This fixes an error I noticed while testing Penny's Big Breakaway on macOS (game is still not playable without other changes), Should also fix the same things fixed by #3932 on macOS in theory.
=> Consider Polygon as unsupported if triangle fans are unsupported on Vulkan

src/Ryujinx.UI.Common/DiscordIntegrationModule.cs
Since we have a developer team for Discord, we created a new application for Ryujinx, since we don't actually have access to the current one anymore.
This PR simply updates the application id that's used for Discord Rich Presence.
---
Closes #6457 
Partially solves #4916
=> Update ApplicationID for Discord Rich Presence

src/Ryujinx/UI/Windows/ContentDialogOverlayWindow.axaml.cs, src/Ryujinx/UI/Windows/DownloadableContentManagerWindow.axaml.cs, src/Ryujinx/UI/Windows/TitleUpdateWindow.axaml.cs
`ContentDialogHelper` is used when a dialogue needs to be displayed as an external window. This is necessary when it should be shown over the embedded window, like the quit dialogue or the about window.
This PR removes `ContentDialogHelper` uses in the DLC manager and title update manager, as both cannot be opened while the game is open, so there is no risk of a soft lock.
This PR also removes `ExtendClientAreaToDecorationsHint` in `ContentDialogOverlayWindow`, which was responsible for this annoying error on macOS:
`ERROR: Can't have a toolbar in a window with <NSNextStepFrame: 0x4835f5670> as its borderView`
=> Ava UI: Content Dialog Fixes

src/Ryujinx/Common/Locale/LocaleManager.cs
Fixes a crash on Ava when an invalid locale value is taken from system, or present in config.
Fixes #6382.
=> Ava UI: Fix locale crash

src/Ryujinx.Graphics.Vulkan/Queries/BufferedQuery.cs
AMD GPUs (possibly just RDNA 3) could hang with the previous value until the MaxQueryRetries was hit.
Fix #6056
=> Updates the default value for BufferedQuery

src/Ryujinx/Assets/Locales/en_US.json, src/Ryujinx/UI/ViewModels/SettingsViewModel.cs, src/Ryujinx/UI/Views/Settings/SettingsGraphicsView.axaml, src/Ryujinx/UI/Views/Settings/SettingsNetworkView.axaml
Adds two groups of missing strings on the english locale file:
- Graphics scaling filter options (Bilinear, Nearest, FSR).
- Multiplayer network modes (Disabled, LdnMitm).
For the network modes, they were sourced directly from the enum before. To allow them to be translated, I changed the combo box to have its own items that can be translated. I also changed "LdnMitm" to "LDN MitM". Might be worth testing that it is still working properly.
=> Add a few missing locale strings on Avalonia

src/Ryujinx.Graphics.Vulkan/ShaderCollection.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
Apparently it is not working on those GPUs.
Additionally moves vendor information init logic out of the `PrintGpuInformation` method, since it does not make sense for that to be there, and it is actually a source of bugs (for example, `LoadFeatures` checks that `features2.Features.MultiViewport && !(IsMoltenVk && Vendor == Vendor.Amd)`, but `Vendor` has not been set at this point before this change, which means this condition will always be true, since Amd happens to have value 0 in the enum).
Fixes #6512.
=> Disable push descriptors for Intel ARC GPUs on Windows

src/Ryujinx/AppHost.cs, src/Ryujinx/UI/Views/Main/MainStatusBarView.axaml.cs
VSync toggling via hotkeys or the status bar has not been wired up to invalidate the swapchain in the Vulkan renderer window. This meant that, if the game was started with VSync on, and the player then toggled VSync off, the present mode would not be set to immediate, and FPS would (typically) be capped at host display refresh rate. Conversely if the game was started with VSync off, the present mode would be set to immediate, but could never be toggled to mailbox.
This PR creates a method in `AppHost.cs` that sets device VSync as well as calling the previously uncalled Vulkan Window `ChangeVSyncMode` toggle. Further, the hotkey toggle and the status bar toggle now call this new method instead of only directly changing the device VSync.
=> Vulkan: Recreate swapchain correctly when toggling VSync

src/Ryujinx.Graphics.Gpu/Image/Texture.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroupHandle.cs
`DiscardData` is called for textures that are cleared. Since the entire texture data will be overwritten on the GPU side, there is no need to load any CPU side data. However, `DiscardData` also clear the `Modified` flag which as far as I can tell is not correct, since the fact that the GPU will overwrite all texture data implies that is is being modified, so the `Modified` flag should remain set. Clearing it may be problematic since for render target, it is only set on first use, then when the render target is replaced with another. So a clear for a render target that is already bound could cause the flag to be lost.
Fixes #6587 (regression caused by #5719).
Before:
After:
=> Stop clearing Modified flag on DiscardData

src/Ryujinx/UI/ViewModels/MainWindowViewModel.cs
Allows "pokemon" to match "Pokémon" for example.
Someone requested this.
=> Ignore diacritics on game search

src/Ryujinx.HLE/HOS/ModLoader.cs
As annoyed by not knowing the status of mod if it is enabled when investigating the log, I have decided to just add small update in the log message so that we all can see the status from the log itself.
That means it is also required to update the log parser. (https://github.com/Ryujinx/ryuko-ng/pull/93)
**! Merge the log parser first before this PR !**
=> Add mod enablement status in the log message

src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/PipelineState.cs, src/Ryujinx.Graphics.Vulkan/ShaderCollection.cs
Drawing using patches topology without a tessellation shader is invalid according to the Vulkan spec. It crashes on AMD, I'm not sure what the behaviour is on NVIDIA, but it does not crash.
This change skips draws if topology is patches and there's no tessellation control shader.
It fixes a crash on Luigi's Mansion 3 on the floor with sand.
Before:
https://github.com/Ryujinx/Ryujinx/assets/5624669/db9cc165-5a34-42b8-a29b-a66a8b52a633
After:
https://github.com/Ryujinx/Ryujinx/assets/5624669/398e5298-5a63-4b29-9b29-cf41c6fdfb3d
The black triangle flickering seems to be caused by the fact that it only writes `gl_TessOuterLevel` when `gl_InvocationID` is 0 (instead of doing so for all of them). It seems a bit more complicated to fix.
=> Vulkan: Skip draws for patches topology without a tessellation shader

src/Ryujinx.Graphics.Vulkan/RenderPassHolder.cs, src/Ryujinx.Graphics.Vulkan/TextureView.cs
Fixes two regressions from #6182.
- Render passes were never being disposed, causing a render pass leak.
- Swapchain image views were not disposed due to the `_gd.Textures.Remove(this)` check. Those textures are never added to the textures set, so that would be always false preventing them from being disposed.
Might be worth some testing since the fact that the render pass was not disposed before could be hiding some bugs.
=> Vulkan: Fix swapchain image view leak

src/Ryujinx.Cpu/AddressSpace.cs, src/Ryujinx.Cpu/AppleHv/HvMemoryManager.cs, src/Ryujinx.Cpu/Jit/MemoryManager.cs, src/Ryujinx.Cpu/Jit/MemoryManagerHostMapped.cs, src/Ryujinx.Cpu/Jit/MemoryManagerHostTracked.cs, src/Ryujinx.HLE/HOS/ArmProcessContextFactory.cs, src/Ryujinx.HLE/HOS/Kernel/Memory/KPageTable.cs, src/Ryujinx.HLE/HOS/Kernel/Memory/KPageTableBase.cs, src/Ryujinx.HLE/HOS/Kernel/Memory/KSharedMemory.cs, src/Ryujinx.Memory/AddressSpaceManager.cs, src/Ryujinx.Memory/IVirtualMemoryManager.cs, src/Ryujinx.Tests.Memory/MockVirtualMemoryManager.cs
Since #6356, it is no longer used. While I do think it would be useful in some cases to keep it (mainly for testing purposes), I would rather remove it since it is not working correctly in some cases (for example, with Zelda Tears of the Kingdom), I'm not a fan of keeping unused and semi-working code.
Also renamed `Supports4KBPage` to `UsesPrivateAllocations` to better reflect what it actually means now. The condition is also now inverted due to the new name (supporting 4KB pages implies that private allocations are not used).
Should not have any user impact since the code being removed here is unused.
=> Delete old 16KB page workarounds

src/Ryujinx.UI.Common/Configuration/ConfigurationFileFormat.cs, src/Ryujinx.UI.Common/Configuration/ConfigurationState.cs, src/Ryujinx.UI.Common/Helper/CommandLineState.cs, src/Ryujinx/Program.cs
Adds a configuration option to disable hardware-accelerated rendering for Avalonia which can also be triggered via the CLI.
`--software-gui` = Avalonia will use software rendering.
`--hardware-gui` = Avalonia will use ANGLE/GLX rendering.
Not intended to be a user facing change (hence no GUI toggle), but should make it easier to access for those that need it and CLI arguments in renderdoc etc.
Will obviously break stuff like transparency and performance **will** be reduced with large window sizes.
=> misc: Add ANGLE configuration option to JSON and CLI

src/Ryujinx.HLE/HOS/ModLoader.cs
The reason for this is that, when `modData` is null, then a `NullReferenceException` would be thrown if we attempt to access its properties directly. So, this code effectively prevents such exceptions by using the null-conditional operator (`?.`) to safely access `Enabled` only when `modData` is not null. If `modData` is indeed null, the null-coalescing operator (`??`) ensures that `enabled` is set to `true`, maintaining the functionality of enabling new mods by default without the overhead of exception handling.
=> Replacing the try-catch block with null-conditional and null-coalescing operators

src/ARMeilleure/Instructions/InstEmitAlu32.cs, src/ARMeilleure/Translation/PTC/Ptc.cs
For ADR instructions, PC must be 4 bytes aligned, even in thumb mode where the instruction size might be 2 bytes.
Fixes black screen on Ni no Kuni when using the 1.0.2 update (and maybe 1.0.1 too).
Before:
After:
The issue generally only affects x86 CPUs since the new Arm JIT does not have this issue.
As a reminder, the game still needs a save to get past the EULA loop.
=> CPU: Fix PC alignment for ADR thumb instruction

src/Ryujinx.UI.Common/Helper/CommandLineState.cs, src/Ryujinx/Program.cs
CLI argument to enable software rendering no longer persists in config state.
Oversight from initial PR.
Still present in configuration state if needed.
=> gui: Disable CLI setting persistence for HW-accelerated GUI.

src/Ryujinx.Horizon/Sdk/Audio/Detail/AudioRenderer.cs
`SpanMemoryManager` on `Ryujinx.Audio.Renderer.Utils` takes the pointer of a span and stores it on a field, for this reason, the audio output `Memory` needs to be pinned, otherwise GC might move it if its a managed array, which would cause the pointer to be invalid.
It is probably a good idea to change this code to not depend on memory being pinned in the future, but for now I'm pinning it again to fix the regression.
Fixes a regression caused by #6604.
Fixes #6628.
=> Pin audio renderer update output buffers

src/Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs
We allow color formats to match depth formats for the purpose of texture lookup for 2D copy, since 2D engine does not really have any depth formats as APIs alias depth formats as color formats for copy. However we currently don't support such matches for the D32S8 depth format, which forces it to flush the source texture and do the copy on CPU which is very slow.
This PR enables D32S8 textures to be copied on GPU, which greatly improves Penny's Big Breakaway performance, showing up to ~1500% (16x) improvement on my machine.
Before:
After:
=> Fast D32S8 2D depth texture copy

src/ARMeilleure/Instructions/InstEmitSimdArithmetic.cs, src/ARMeilleure/Translation/PTC/Ptc.cs
This PR addresses a difference between x86 and Arm for the recriprocal square root estimate instruction. x86 handles subnormal values the same way as zero, which means that any subnormal value will have a infinity result, while Arm does produce what one would expect (an approximation of the result).
To account for this difference, this PR stops using the RSQRTPS/RSQRTSS instructions on x86, and instead uses the regular square root instruction followed by RCPPS/RCPSS.
This seems to fix the terrain randomly disappearing on Penny's Big Breakaway.
Before:
https://github.com/Ryujinx/Ryujinx/assets/5624669/5f34f366-eb41-4c8f-8315-b60e6c853504
After:
https://github.com/Ryujinx/Ryujinx/assets/5624669/393eb07b-3aed-4a8a-b8da-c11e05da42e8
This is the only place where I was able to reproduce the …
=> CPU: Produce non-inf results for RSQRTE instruction with subnormal inputs

src/Ryujinx.Audio/Renderer/Server/Splitter/SplitterState.cs
Fixes a regression caused by #6604. `SplitterState.Update` should advance the input by `parameter.DestinationCount` elements, even if it actually consumes less than that. This should match the behaviour before the change.
Fixes #6639.
=> Fix input consumed by audio renderer SplitterState.Update

src/Ryujinx/AppHost.cs, src/Ryujinx/UI/Models/StatusInitEventArgs.cs, src/Ryujinx/UI/Models/StatusUpdatedEventArgs.cs, src/Ryujinx/UI/ViewModels/MainWindowViewModel.cs
This prevents the status bar from changing the displayed backend and GPU while a game has already started.
=> Ava UI: Prevent Status Bar Backend Update

src/Ryujinx.HLE/HOS/Tamper/CodeEmitters/StoreConstantToMemory.cs
As it turns out the reading of cheat instruction starting with 6XXXXXXX (`StoreConstantToMemory`) was wrong, so by collective mind of the dev team, the simple fix is to just follow what `StoreConstantToAddress` has done to read the value.
This was part of investigating the issue https://github.com/Ryujinx/ryuko-ng/issues/89
=> Update StoreConstantToMemory to match StoreConstantToAddress on value read

src/Ryujinx.HLE/HOS/Tamper/CodeEmitters/StoreConstantToMemory.cs
Reverts Ryujinx/Ryujinx#6642
The previous code was correct, `StoreStaticToAddress` always accesses a 64-bit value for some reason, unlike the others.
Fixes #6648.
=> Revert "Update StoreConstantToMemory to match StoreConstantToAddress on value read"

src/Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
They would not exit before until the timeout expires (which might be infinite, in which case it might get stuck forever).
This fixes a freeze when trying to stop emulation and/or close the emulator on Penny's Big Breakaway and maybe other games that uses sockets with Poll.
---
Fixes #6355
=> Allow BSD sockets Poll to exit when emulation ends

src/Ryujinx.Graphics.Vulkan/Window.cs
We need to update the semaphore index in case the amount of swapchain images change.
This is an attemp to fix a crash when VSync is toggled on some drivers.
=> Account for swapchain image count change after re-creation

src/Ryujinx.Input/HLE/NpadController.cs
fixes the crash when changing from a keyboard to a controller with motion support while a game is running (https://github.com/Ryujinx/Ryujinx/issues/6647). 
The root cause of this crash is ```needsMotionInputUpdate``` is not calculated correctly when switching from a keyboard to a controller. specifically if _config is the type ```StandardKeyboardInputConfig``` and the new config is ```StandardControllerInputConfig```, then the old code always evaluated ```needsMotionInputUpdate``` to false.
when the motion input is not correctly updated, ```_leftMotionInput``` is left as null when it shouldn't be and causes a null reference exception.
=> Fix crash when changing controller config

src/Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs
On #3706, I added a check to prevent the emulator from trying to read texture handles from unbound constant buffer that would cause crashes. This was done by checking if the address is 0 which would be the case for unbound constant buffers. However, #5427 generally changed how unbound resources are handled, and instead of checking for an address of 0, it checks for the special "unmapped" value that the memory manager returns. But I forgot to update the texture handle read code to account for that.
This fixes a regression that was causing Sniper Elite 3 to crash again at launch, it was likely caused by #5427 but I did not test the version prior to this change to confirm.
=> Fix unmapped address check when reading texture handles

src/Ryujinx.HLE/HOS/TamperMachine.cs, src/Ryujinx.Tests/Memory/PartialUnmaps.cs
https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.volatileread
https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.volatilewrite
> [Thread.VolatileRead](https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.volatileread?view=net-8.0) and [Thread.VolatileWrite](https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.volatilewrite?view=net-8.0) are legacy APIs and have been replaced by [Volatile.Read](https://learn.microsoft.com/en-us/dotnet/api/system.threading.volatile.read?view=net-8.0) and [Volatile.Write](https://learn.microsoft.com/en-us/dotnet/api/system.threading.volatile.write?view=net-8.0).
=> Update to new standard for volatility operations

src/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs, src/Ryujinx.HLE/HOS/Services/Fatal/IService.cs
https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md#ca2265-do-not-compare-spant-to-null-or-default
> Comparing a span to 'null' or 'default' might not do what you intended. 'default' and the 'null' literal are implicitly converted to 'Span\<T>.Empty'. Remove the redundant comparison or make the code more explicit by using 'IsEmpty'.
=> Do not compare Span<T> to 'null' or 'default'

src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoClass.cs, src/Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs
On #5933 I added a way to end the lifetime of render targets with a new `RefreshModifiedTextures` method, when this method is called, it will set the `Modified` flag if needed, and then if any flush happens after that, the `Modified` flag will be cleared and will remain that way unless the render target is actually used again.
However, the linked PR currently only makes use of that in the DMA copy method. This solve some cases of the texture being flushed without being actually modified (due to `Modified` flag being resurected on unbind), but not all of them. This PR aims to fix the remaining cases by calling the method during syncpoint increment as well. Since a syncpoint increment usually means that GPU resources will be accessed from CPU, I think it makes sense to do it there.
This …
=> End render target lifetime on syncpoint increment

src/Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceSession.cs, src/Ryujinx.Audio.Backends.SoundIo/SoundIoHardwareDeviceSession.cs, src/Ryujinx.HLE/HOS/Kernel/Ipc/KServerSession.cs, src/Ryujinx.HLE/HOS/Kernel/Memory/KPageTable.cs, src/Ryujinx.HLE/HOS/Kernel/Memory/KPageTableBase.cs, src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/IBinder.cs, src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/Parcel.cs, src/Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs, src/Ryujinx.Memory/IWritableBlock.cs
I am reworking PR #4777 into 4 new PRs. This PR is # 4 of 4 and it changes a few miscellaneous areas that stood out in a memory profiler. Generally, it:
- changes some `new byte[]` allocations to use pooled memory instead.
- changes some HLE kernel-level methods that were copying data via a temporary copy buffer, to instead copy directly from source to destination via `GetReadOnlySequence()` and `Write(ReadOnlySequence<byte>)`
These are relatively minor, but are the last of the improvements originally proposed by PR #4777.
=> Use pooled memory and avoid memory copies

src/Ryujinx.Cpu/Jit/MemoryManagerHostTracked.cs, src/Ryujinx.Memory/NativeMemoryManager.cs
implement `MemoryManagerHostTracked.GetReadOnlySequence()`, fixes crashes on game starts on MacOS
---
Fixes  #6696
=> implement `MemoryManagerHostTracked.GetReadOnlySequence()`

.github/workflows/build.yml
Due to a change to the GitHub runner labels a few days ago (see: actions/runner#3256) our build workflows for macOS x64 didn't work anymore. According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories the macos-13 label is not using arm64 yet.
Until a better solution is offered in the linked issue above, we'll keep using the macos-13 label which hopefully doesn't switch to arm64 soon.
=> ci: Replace macos-latest label with macos-13

src/Ryujinx.HLE/HOS/Services/Hid/HidDevices/MouseDevice.cs
The delta position of the mouse should be the difference between the current and last position. Subtracting the last deltas doesn't really make sense.
Won't implement pointer lock for first person games, but might stop some super weird behaviour with the mouse values appearing totally random.
=> HID: Correct direct mouse deltas

src/Ryujinx.Input/HLE/NpadController.cs, src/Ryujinx.Input/HLE/NpadManager.cs
- Pass KeyboardDriver to NpadController.GetHLEKeyboardInput().
- Always fetch a Keyboard with KeyboardDriver.GetGamepad("0") if Direct Keyboard is on.
- Remove unnecessary return null.
=> Fix direct keyboard not working when using a Controller.

src/Ryujinx/AppHost.cs, src/Ryujinx/Input/AvaloniaMouse.cs, src/Ryujinx/UI/Helpers/Win32NativeInterop.cs, src/Ryujinx/UI/Renderer/EmbeddedWindow.cs, src/Ryujinx/UI/ViewModels/MainWindowViewModel.cs, src/Ryujinx/UI/Views/Main/MainMenuBarView.axaml, src/Ryujinx/UI/Windows/MainWindow.axaml.cs
It's been sometime since the last PR #5415 was made and last time i was waiting for Ava 11 to be merged before re-writing the code and along the way forgot about the PR.
Anyway this PR supersedes both #5288 and #5415, and fixes issue: #5136
* Now, the bounds for which the cursor should be detected in renderer should be accurate to any scaling / resolution, taking into account the status and the menu bar. ( This issue was partially resolved by #6450 )
* Reduced the number of times the cursor updates from per frame update to updating only when the cursor state needs to be changed.
* Fixed the issue wherein you weren't able to resize the window, because of the cursor passthrough which caused the cursor to reset from the reset icon or flicker.
* Fixed the issue caused by #6450 which caused …
=> Fix Cursor States On Windows

src/ARMeilleure/Translation/PTC/Ptc.cs, src/Ryujinx.Graphics.Gpu/GpuContext.cs
Benchmark:
```cs
[SimpleJob(RuntimeMoniker.Net80)]
[SimpleJob(RuntimeMoniker.Net90)]
[MemoryDiagnoser]
[RankColumn]
public class MyBenchmark
{
private readonly List<string> _list = [];
private readonly int _size = 100000;
[GlobalSetup]
public void Setup()
{
var random = new Random(420);
for (var i = 0; i < _size; i++)
{
_list.Add(random.Next().ToString());
}
}
[Benchmark]
public string Foreach()
{
var result = string.Empty;
foreach (var item in _list)
{
result = item;
}
return result;
}
[Benchmark]
public string ListForeach()
{
var result = string.Empty;
_list.ForEach(item => result = item);
return result;
}
}
```
Results:
```sh
| Method      | Job      | Runtime  | Mean      | Error    | StdDev   | Median    | Rank | Allocated |
|------------ |--------- |--------- …
```
=> Replace "List.ForEach" for "foreach"

src/Ryujinx.Gtk3/Ryujinx.Gtk3.csproj, src/Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj, src/Ryujinx/Ryujinx.csproj
Tiny PR to make sure Linux specific files are copied to the output directory when building locally.
This is useful when testing shortcuts for example.
=> Add linux specific files to local builds

src/Ryujinx.Gtk3/Program.cs, src/Ryujinx/Program.cs
When running on an outdated version of Windows, Ryujinx will give the message: "You are running an outdated version of Windows. Starting on June 1st 2022, Ryujinx will only support Windows 10 1803 and newer."
Due to it being long after 2022, I have changed the text to: "You are running an outdated version of Windows. Ryujinx supports Windows 10 version 1803 and newer."
=> Update outdated Windows version warning

src/Ryujinx.UI.Common/DiscordIntegrationModule.cs
Fixes https://github.com/Ryujinx/Ryujinx/issues/6576
Also hit in the wild with:
`INAZUMA ELEVEN: Victory Road Versione di prova per beta testing per tutto il mondo Incidi i cieli con il fulmine Inazuma!`
Unsure if it would be desirable to truncate a further 3 characters and add a `...`? 
Thoughts appreciated.
=> discordRPC: Truncate game title and details if they exceed discord byte limit.

src/Ryujinx.Graphics.Gpu/Image/Texture.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroupHandle.cs
The list of views from the texture is passed directly on `TextureGroup.UpdateViews`. That list is accessed on the `ClearModified` method. However the `ClearModified` method can be called from other threads (due to the `MemoryUnmappedHandler`). For the most part, this method seems already thread safe, except for the views list that can be modified from other threads and cause crashes. To fix this, I changed the code to store an array copy of the list, instead of a reference to the list itself.
One such crashes was reported on https://github.com/Ryujinx/Ryujinx-Games-List/issues/4935
=> Make TextureGroup.ClearModified thread safe

src/Ryujinx.Gtk3/Input/GTK3/GTK3KeyboardDriver.cs, src/Ryujinx.Gtk3/UI/Applet/GtkHostUIHandler.cs, src/Ryujinx.Input/HLE/NpadManager.cs, src/Ryujinx.Input/IGamepadDriver.cs, src/Ryujinx/Input/AvaloniaKeyboard.cs, src/Ryujinx/Input/AvaloniaKeyboardDriver.cs, src/Ryujinx/UI/Applet/AvaHostUIHandler.cs
This PR fixes #5625 by disabling the keyboard controller input while the swkbd applet is open.
> [!WARNING]
> This does not prevent keyboard controller inputs while the inline keyboard is active.
---
Thank you @music-discussion for figuring out the bug and describing it in the [comments](https://github.com/Ryujinx/Ryujinx/issues/5625#issuecomment-1736538968)! It saved me quite some time and allowed me to create this PR quickly.
=> Disable keyboard controller input while swkbd is open (foreground)

src/Ryujinx.Graphics.Gpu/Image/TextureCache.cs
The `UpdateMapping` method removes and adds a new texture, so it must take a look for the textures tree, since it might be accessed by another thread (for example, on `MemoryUnmappedHandler` method).
This additionally refactors the lock usage to instead use a `ReaderWriterLockSlim`, which allows concurrent access to the tree and should be more efficient than the regular lock (which would block on concurrent access).
This fixes a crash on the game Harmony: The Fall of Reverie. Other games might be affected as well.
The crash happens upon entering this place called "the Naiads".
=> Add missing lock on texture cache UpdateMapping method

src/Ryujinx.Gtk3/Input/GTK3/GTK3KeyboardDriver.cs, src/Ryujinx.Gtk3/UI/Applet/GtkHostUIHandler.cs, src/Ryujinx.Input/HLE/NpadManager.cs, src/Ryujinx.Input/IGamepadDriver.cs, src/Ryujinx/Input/AvaloniaKeyboard.cs, src/Ryujinx/Input/AvaloniaKeyboardDriver.cs, src/Ryujinx/UI/Applet/AvaHostUIHandler.cs
Reverts Ryujinx/Ryujinx#6646
Reverting because "it causes pokemon to crash upon starting a new save and naming the char".
=> Revert "Disable keyboard controller input while swkbd is open (foreground)"

src/Ryujinx.Gtk3/Program.cs, src/Ryujinx.UI.Common/App/ApplicationData.cs, src/Ryujinx.UI.Common/App/ApplicationLibrary.cs, src/Ryujinx.UI.Common/Configuration/ConfigurationState.cs, src/Ryujinx/Program.cs
The main goal of this commit is to improve the somewhat cryptic wording of the log message that shows up when previously specified game directories no longer exist. I removed the config file's name from the message since the **vast** majority of users do not and should never interact with that file directly.
As for the change in `ConfigurationState.cs`: I noticed floats (like the one for `AudioVolume`) got formatted with the local culture for some reason, so I made it use the invariant culture.
=> Improves some log messages and fixes a typo

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/BinarySerializer.cs
From my own empirical testing, `SmallestSize` is, naturally the slowest algorithm:
It also has seemingly no benefit over faster algorithms for the current disk cache data structure:
Based on these results the changes here simply update the compression level to `Fastest`. There was a near 14x speedup in the "packaging" stage of rebuild with a minimal 7% increase in disk usage.
Testing would be appreciated with some other games.
=> misc: Change Deflate compression level to `Fastest`

src/Ryujinx.Gtk3/Input/GTK3/GTK3KeyboardDriver.cs, src/Ryujinx.Gtk3/UI/Applet/GtkHostUIHandler.cs, src/Ryujinx.Input/HLE/NpadManager.cs, src/Ryujinx.Input/IGamepadDriver.cs, src/Ryujinx/Input/AvaloniaKeyboard.cs, src/Ryujinx/Input/AvaloniaKeyboardDriver.cs, src/Ryujinx/UI/Applet/AvaHostUIHandler.cs
Pretty much the same as #6646. This PR just includes a new commit which only clears the driver state if the driver isn't null.
<details>
<summary>Original PR description</summary>
This PR fixes #5625 by disabling the keyboard controller input while the swkbd applet is open.
> [!WARNING]
> This does not prevent keyboard controller inputs while the inline keyboard is active.
---
Thank you @music-discussion for figuring out the bug and describing it in the [comments](https://github.com/Ryujinx/Ryujinx/issues/5625#issuecomment-1736538968)! It saved me quite some time and allowed me to create this PR quickly.
</details>
=> Disable keyboard controller input while swkbd is open (foreground) (second attempt)

src/Ryujinx.Input/HLE/NpadManager.cs
I can't reproduce this locally, but the person crashing on discord reported that it worked fine with this fix.
Feels really bad to have a 2nd PR to address the same issue, but I guess it can't be helped.
I'll try to look into creating more/better unit tests when LDN upstreaming is done.
=> HID: Fix another NullReferenceException when unblocking input updates

src/Ryujinx.HLE/HOS/Kernel/Threading/KScheduler.cs, src/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs, src/Ryujinx.HLE/HOS/Kernel/Threading/ThreadType.cs, src/Ryujinx.HLE/HOS/Services/ServerBase.cs
Right now when a core enters an idle state, leaving that idle state requires us to first signal the core's idle thread, which then signals the correct thread that we want to run on the core. This means that in a lot of cases, we're paying double for a thread to be awoken from an idle state.
This PR moves this process to happen on the thread that is waking others out of idle, instead of an idle thread that needs to be awoken first.
For compatibility the process has been kept as similar as possible - the process for IdleThreadLoop has been migrated to TryLeaveIdle, and is gated by a condition variable that lets it run only once at a time for each core. A core is only considered for wake from idle if idle is both active and has been signalled - the signal is consumed and the active state is …
=> Kernel: Wake cores from idle directly rather than through a host thread

src/Ryujinx.Graphics.GAL/Format.cs, src/Ryujinx.Graphics.Vulkan/FramebufferParams.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/PipelineConverter.cs, src/Ryujinx.Graphics.Vulkan/PipelineState.cs, src/Ryujinx.Graphics.Vulkan/PipelineUid.cs
According to the Vulkan spec:
> The application can enable a logical operation between the fragment’s color values and the existing value in the framebuffer attachment. This logical operation is applied prior to updating the framebuffer attachment. Logical operations are applied only for signed and unsigned integer and normalized integer framebuffers. Logical operations are not applied to floating-point or sRGB format color attachments.
But AMD does not seems to follow that, and if logical operations are enabled, it will be applied even for attachment with float formats (at least for R11G11B10_FLOAT format). To work around this issue, this change forces logic ops to be disabled if all attachment formats are float or sRGB formats (following what the spec says), but only on AMD.
This fixes …
=> Workaround AMD bug on logic op with float framebuffer

src/Ryujinx.Graphics.Vulkan/PipelineState.cs
built on top of #6852 to add support for intel gpu's
NOTE: this won't fix the crashing on windows
fixes #6859
before:
after:
=> Workaround bug on logic op with float framebuffer

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/BinarySerializer.cs, src/Ryujinx.Graphics.Gpu/Shader/DiskCache/CompressionAlgorithm.cs, src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheCommon.cs
.NET offers a number of compression algorithms built into `System.IO.Compression`.
- Deflate (current default)
- Brotli
- GZip
- Zlib
While initially I simply updated the shader cache logic to use the fastest version of `Deflate`, `Brotli` is actually 40% faster under equal load and matches the compression ratio at each level.
Testing would be nice to make sure this doesn't change disproportionately on lower end systems or something.
=> misc: Change disk shader cache compression algorithm to `Brotli` (RFC 7932)

src/ARMeilleure/CodeGen/Arm64/CodeGenContext.cs, src/ARMeilleure/CodeGen/X86/Assembler.cs, src/Ryujinx.Graphics.Gpu/Shader/DiskCache/BinarySerializer.cs, src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheGuestStorage.cs, src/Ryujinx.Gtk3/UI/Windows/AvatarWindow.cs, src/Ryujinx.UI.Common/App/ApplicationLibrary.cs, src/Ryujinx/UI/ViewModels/UserFirmwareAvatarSelectorViewModel.cs
https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md#ca2022-avoid-inexact-read-with-streamread
> A call to 'Stream.Read' may return fewer bytes than requested, resulting in unreliable code if the return value is not checked.
=> Avoid inexact read with 'Stream.Read'

src/Ryujinx.Common/Memory/MemoryOwner.cs, src/Ryujinx.Common/Memory/SpanOwner.cs, src/Ryujinx.Graphics.Vulkan/MultiFenceHolder.cs
This PR adds 2 new types for using pooled memory:
- `MemoryOwner<T>` is a generic class for easy access to pooled memory.
- `SpanOwner<T>` is generic value type (`readonly ref struct`) that serves the same purpose in more constrained scopes, without requiring an additional allocation to manage it.
Both are intended for future optimization and to eventually replace the existing `ByteMemoryPool` and `ByteMemoryPool.ByteMemoryPoolBuffer` types in `Ryujinx.Common.Memory`, which have the following limitations:
- They only support `byte` buffers
- The `IMemoryOwner<byte>` implementation (the nested `ByteMemoryPoolBuffer` class) is private and returned as the interface. Usage as the concrete type would be faster.
- They don't have a value-type version, meaning their use requires allocating a …
=> New pooled memory types

src/Ryujinx.Graphics.Vulkan/PipelineConverter.cs, src/Ryujinx.Graphics.Vulkan/PipelineState.cs, src/Ryujinx.Graphics.Vulkan/PipelineUid.cs
- Removed dynamic state setting for Depth Bounds from PipelineDynamicStateCreateInfo as the command to set them is never used. At best this means no change. At worst this may have caused some validation errors?  
- Avoid passing pointers for viewport and scissor since these dynamic states are supported across devices that support Vulkan. 
- Removed references to unused DepthBias values and StencilOpState for both Front and Back.
This change likely has no user facing changes, but just need to check if there is anything broken. Just clean-up for future changes.
=> GPU: Remove unused dynamic state and pipeline settings

src/Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceSession.cs, src/Ryujinx.Audio.Backends.SoundIo/SoundIoHardwareDeviceSession.cs, src/Ryujinx.Audio/Backends/Common/DynamicRingBuffer.cs
Replaces use of ByteMemoryPool with the new `MemoryOwner` and `SpanOwner` types in the following projects:
- Ryujinx.Audio
- Ryujinx.Audio.Backends.SDL2
- Ryujinx.Audio.Backends.SoundIo
=> replace ByteMemoryPool in Audio projects

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Instructions/InstEmitPredicate.cs, src/Ryujinx.Graphics.Shader/IntermediateRepresentation/Instruction.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessToArray.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/Optimizer.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/Simplification.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/Utils.cs
This is yet another PR to extend bindless elimination even further. It catches some cases that I found on some games (mainly UE4 games).
I will try to explain each case with the disassembly of the relevant code.
**Negated and non-negated predicate.**
```
@!P0 MOV R2, c[0x2][0x168] ;
@P0 MOV R2, RZ ;
@!P0 LOP.OR R14, R2, c[0x2][0x568] ;
@!P0 TEX.B.NODEP.P R0, R8, R14, 0x0, 2D, 0xf ;
```
Here there are two values assigned to `R2`, but there is only one that can actually reach the texture use. It is not easy to detect this in the code due to the use of predicates.  We already have code find the value from the source that has the same condition as the current block. So I just extended it to go a bit further. If the source is a phi node, it now tries to check the next sources as well. I do …
=> Extend bindless elimination to catch a few more specific cases

src/Ryujinx.Common/Memory/MemoryOwner.cs, src/Ryujinx.Common/Memory/SpanOwner.cs, src/Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs, src/Ryujinx.HLE/HOS/Kernel/Threading/KSynchronization.cs
This PR adjusts calls to `ArrayPool<T>.Shared.Return(T[])` so that the memory is cleared when `T` is a reference type. This is important to prevent pooled memory from keeping alive object instances that would otherwise be collected by the GC.
I intend to profile this change eventually, but I didn't want that to delay submission of this (IMO important) fix to pooled memory usage.
=> clear pooled memory on return when used to hold object references

src/ARMeilleure/Translation/ControlFlowGraph.cs, src/ARMeilleure/Translation/RegisterUsage.cs
Currently `RegisterUsage` pass assumes that the entry block has 0 predecessors. This is always the case right now, but only because the interrupt check code is always inserted at the start of every function. This change updates the `RegisterUsage` pass to insert a new entry block if needed, for cases where the code jumps to the start of the function. Now if the `EmitSynchronization` call inside the `Translator.Translate` function is removed, the JIT no longer crashes.
Does not really change anything right now, but will be required if we decide to use signal based thread suspension in the future.
=> JIT: Ensure entry block has no predecessors on RegisterUsage pass

src/ARMeilleure/CodeGen/RegisterAllocators/LinearScanAllocator.cs, src/ARMeilleure/CodeGen/RegisterAllocators/LiveInterval.cs, src/ARMeilleure/Translation/PTC/Ptc.cs
This effectively allows some copies to be coalesced on the JIT, when the `HighCq` mode is used.  It does not actually coalesce them, but rather, the register allocator tries to select the same register as the copy source for the destination. When both source and destination uses the same register, the backend will just skip the instruction since it basically does nothing.
This allows the elimination of some copies, such as those generated after Phi removal, or the ones inserted for instructions where the destination and first operand must use the same register on x86.
Examples (from Shantae and the Pirate's Curse `main`):
Before:
```nasm
mov r13, qword ptr [rbx + 0xf8]
mov eax, dword ptr [rbx + 0x410]
test eax, eax
je 0x169c
sub eax, 1
mov dword ptr [rbx + 0x410], eax
mov rax, r13
sub …
```
=> JIT: Coalesce copies on LSRA with simple register preferencing

src/Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
There was wrong handling of the syscall, as it can be checked in https://switchbrew.org/wiki/SVC.
Without my patch, the arguments end up reversed, resulting in a 0xD401 (InvalidMemState) error.
My patch makes calls to this SVC work flawlessly under Aarch32 processes.
=> SetProcessMemoryPermission address and size are always 64-bit

src/Ryujinx.UI.Common/DiscordIntegrationModule.cs
This tiny PR adds a check to make sure the string we are trimming is long enough for the basic trim.
The bytes of the string can exceed the limit, while actual length of the string can still be a lot lower than that.
As a test I used a string of length 50, which could be represented as a byte array with 130 elements.
---
Fixes #6981
=> discord: Fix TruncateToByteLength() not taking the string length into account before trimming

src/Ryujinx.Graphics.Vulkan/BufferManager.cs, src/Ryujinx.Graphics.Vulkan/TextureStorage.cs, src/Ryujinx.Graphics.Vulkan/TextureView.cs, src/Ryujinx.Graphics.Vulkan/VulkanInitialization.cs
- Pass ExternalMemoryBufferCreateInfo to BufferCreateInfo with HandleType (based on import) 
resolves: 
```
VUID-vkBindBufferMemory-memory-02985(ERROR / SPEC): msgNum: -1873212623 - Validation Error: [ VUID-vkBindBufferMemory-memory-02985 ] Object 0: handle = 0x19ea8aa6b68, type = VK_OBJECT_TYPE_BUFFER; Object 1: handle = 0x19ea8acc288, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x90590b31 | vkBindBufferMemory(): memory (VkDeviceMemory 0x19ea8acc288[]) was created with an import operation with handleType of VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT which is not set in the VkBuffer (VkBuffer 0x19ea8aa6b68[]) VkExternalMemoryBufferCreateInfo::handleType (VkExternalMemoryHandleTypeFlags(0)). The Vulkan spec states: If memory was allocated by a memory import operation, …
```
=> Resolve some Vulkan validation errors

src/Ryujinx.Graphics.Vulkan/Window.cs
Most drivers returns an `ErrorOutOfDateKhr` or `SuboptimalKhr` error when the swapchain is used after the window is resized, but apparently not Adreno driver.
This forces a swapchain re-creation when the window size size changes.
Fixes incorrect render size after window resize on Adreno GPUs on Windows.
Before:
https://github.com/Ryujinx/Ryujinx/assets/5624669/8d4205b5-fbcd-45c9-88a1-f054ff1bb4ac
After:
https://github.com/Ryujinx/Ryujinx/assets/5624669/7a995cd3-d98c-41ba-8613-5e72cdb68500
=> Force Vulkan swapchain re-creation when window size changes

src/Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/ShaderCollection.cs
Buffer texture updates are currently causing the Adreno driver to crash on Windows. To work around the issue, this change disables template updates for buffer textures on Adreno.
Allows UE4 games and a few others (like Mario + Rabbids) to run.
Note that this was tested with #7001, otherwise it crashes pretty quickly when waiting for fences.
=> Disable descriptor set template updates for buffer textures on Adreno

src/Ryujinx.Graphics.Vulkan/PipelineBase.cs
There is a bug on Adreno drivers where the viewport state becomes corrupted after enabling rasterizer discard.
This change works around the issue by making dynamic state dirty after rasterizer discard is disabled. This will force the viewport and other dynamic state to be updated again on the next draw.
Improves rendering on Xenoblade Chronicles 2. It is not easy to see the difference right now due to all the barrier issues, but it causes some objects to disappear or move around. The screenshots below catches the "bad state" to make the difference more evident.
Before:
After:
=> Force dynamic state update after rasterizer discard disable on Adreno

src/Ryujinx.Graphics.Vulkan/BackgroundResources.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/PipelineFull.cs, src/Ryujinx.Graphics.Vulkan/ShaderCollection.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
`vkCmdClearAttachments` does not work properly on the proprietary Adreno driver, and appears to race with subsequent draw commands, which causes the texture to be cleared too late and effectively clears what is supposed to be rendered. As a workaround, this change will now use clears with draw, which is normally used on scenarios not supported by `vkCmdClearAttachments`, but for Adreno it will be used for all clears (at least until we use render pass clears).
This additionally adds a new `IsQualcommProprietary ` and makes use of it in all places where we previously checked if the vendor is Qualcomm. This avoids triggering those workarounds on the Turnip driver, which does not suffer from those issues and should not be penalized for the proprietary driver bugs.
Also fixes a bug on GTX …
=> Use draw clear on Adreno, instead of vkCmdClearAttachments

src/Ryujinx.HLE/HOS/Services/ServerBase.cs, src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/IHOSBinderDriver.cs, src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/Parcel.cs
Replaces use of `ByteMemoryPool` with the new `MemoryOwner` and `SpanOwner` types in the Ryujinx.HLE project. 
It does use `SpanOwner` in 2 places to make those fully allocation-less, but otherwise these are all just different ways of using `System.Buffers.ArrayPool` and the before/after should be functionally identical.
=> replace ByteMemoryPool usage in Ryujinx.HLE

src/Ryujinx.Graphics.GAL/ResourceLayout.cs, src/Ryujinx.Graphics.Gpu/Shader/ShaderInfoBuilder.cs, src/Ryujinx.Graphics.Vulkan/BarrierBatch.cs, src/Ryujinx.Graphics.Vulkan/Effects/FsrScalingFilter.cs, src/Ryujinx.Graphics.Vulkan/Effects/FxaaPostProcessingEffect.cs, src/Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs, src/Ryujinx.Graphics.Vulkan/FramebufferParams.cs, src/Ryujinx.Graphics.Vulkan/HelperShader.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/PipelineConverter.cs, src/Ryujinx.Graphics.Vulkan/PipelineFull.cs, src/Ryujinx.Graphics.Vulkan/RenderPassHolder.cs, src/Ryujinx.Graphics.Vulkan/ResourceLayoutBuilder.cs, src/Ryujinx.Graphics.Vulkan/ShaderCollection.cs, src/Ryujinx.Graphics.Vulkan/TextureCopy.cs, src/Ryujinx.Graphics.Vulkan/TextureStorage.cs, src/Ryujinx.Graphics.Vulkan/TextureView.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
This PR mostly aims to avoid visual bugs that can occur on platforms more susceptible to barrier issues, such as Adreno, but it will also eliminate unnecessary barriers that are already covered by our resource usage tracking.
The main observation is that there are two types of graphics barriers that we need to handle, and that they should be handled separately:
- The guest handles these by writing the `TextureBarrier`/`TextureBarrierTiled` register in 3d class state. We discovered over time that these aren't reliable enough to make sure attachments are fully written before they are sampled or written again on basically any GPU past NVIDIA's pascal architecture, or from other vendors.
- This type of access is **coherent**. When a game accesses a texture after it's sampled, there is _no …
=> Vulkan: Defer guest barriers, and improve image barrier timings

src/Ryujinx.Horizon/Ngc/Ipc/Service.cs
Somehow I forgot to add the buffer attribute on the text span for this method. This PR adds the missing attribute.
Fixes a crash on Teenage Mutant Ninja Turtles: Splintered Fate and other games that does profanity filter checks and targets firmware 16.0.0+.
=> Add missing Buffer attribute on NGC Check method

src/Ryujinx.Horizon/Sdk/OsTypes/Impl/MultiWaitImpl.cs, src/Ryujinx.Horizon/Sdk/OsTypes/MultiWait.cs, src/Ryujinx.Horizon/Sdk/Sf/Hipc/ServerManagerBase.cs
Some code paths do not unlink the server session object from the multi-wait list (such as the one that catches a `ThreadTerminatedException`). This ensures they are unlinked before the dispose method for the `ServerManager` is called, since dispose expects them to be unlinked.
This fixes an assert that may happen when emulation is stopped, but that only affects debug builds, release builds do not have this issue and thus should not be affected.
=> Unlink server sessions from multi-wait when service stops processing requests

src/Ryujinx/AppHost.cs
Fixes two regressions from #6269.
The first is that it "clearing" the destination bitmap with a transparent background. This is undesirable since the image being saved might also have transparency, but we don't want to save a screenshot with a transparent background, it should be black.
The second is that it was drawing the bitmap at a negative position:
```cs
canvas.DrawBitmap(bitmap, new SKPoint(e.FlipX ? -bitmap.Width : 0, e.FlipY ? -bitmap.Height : 0));
```
I have no idea why that was done, but it was causing the bitmap to not be drawn at all, so I set it to zero always.
I tested on a few games, and the saved images are now correct.
Fixes #7068.
=> Fix Skia saving screenshot with transparent background and incorrect origin

src/Ryujinx.HLE/Loaders/Npdm/ACI0.cs, src/Ryujinx.HLE/Loaders/Npdm/ACID.cs, src/Ryujinx.HLE/Loaders/Npdm/FsAccessControl.cs, src/Ryujinx.HLE/Loaders/Npdm/FsAccessHeader.cs, src/Ryujinx.HLE/Loaders/Npdm/KernelAccessControl.cs, src/Ryujinx.HLE/Loaders/Npdm/Npdm.cs, src/Ryujinx.HLE/Loaders/Npdm/ServiceAccessControl.cs, src/Ryujinx.UI.Common/App/ApplicationLibrary.cs
Since I failed to fully fix the issue where Ryujinx crashes on startup when it finds invalid files in my previous PR (#7036), I spent some time to figure out which exceptions can be thrown by the methods we are using there and documented them.
This PR should fix all other crashes on startup that people have been reporting since #6515 was merged.
I also found that I forgot to use the `filePath` parameter in `GetApplicationFromExeFs()` previously and addressed that here as well.
---
Fixes #7061
=> Make sure TryGetApplicationsFromFile() doesn't throw exceptions anymore

src/Ryujinx.Gtk3/UI/Widgets/GameTableContextMenu.cs, src/Ryujinx.Gtk3/UI/Windows/DlcWindow.cs, src/Ryujinx.Gtk3/UI/Windows/TitleUpdateWindow.cs, src/Ryujinx.HLE/Loaders/Processes/Extensions/NcaExtensions.cs, src/Ryujinx.HLE/Loaders/Processes/Extensions/PartitionFileSystemExtensions.cs, src/Ryujinx.UI.Common/App/ApplicationData.cs, src/Ryujinx/UI/ViewModels/DownloadableContentManagerViewModel.cs, src/Ryujinx/UI/ViewModels/TitleUpdateViewModel.cs, src/Ryujinx/UI/Windows/DownloadableContentManagerWindow.axaml.cs, src/Ryujinx/UI/Windows/TitleUpdateWindow.axaml.cs
Thanks to @Littl3Guy for finding this issue and @piplup55 for testing this with me!
This PR fixes another regression from #6515 that caused Ryujinx to not apply updates for games that get launched with different program indices (like the games in Super Mario 3D All-Stars).
(Ryujinx also wasn't applying DLCs for these games, but that wasn't caused by #6515.)
The issue here was that we were looking for the `updates.json` (and `dlc.json`) in a directory with the exact same application id (which also contains the program index) as the name, which doesn't exist. Updates (and DLCs) are only managed for the base game, but still apply to the different program indices, so we need to remove the index from the application id before we check for `updates.json` (or `dlc.json`).
---
Fixes #7044
=> Fix checking for the wrong metadata files for applications launched with a different program index

src/Ryujinx.Graphics.Vulkan/PipelineState.cs
Vulkan spec states that input topology should always be PatchList when a tessellation stage is present. The AMD GPU driver on windows crashes so hard it BSODs the machine if this isn't the case, so it's forced here just in case.
Fixes a crash on Floor 15 of Luigi's Mansion 3.
I'm not sure what providing a different topology here would even do, as you'd think it would always be a patch list input.
=> Vulkan: Force topology to PatchList for Tessellation

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Translation/RegisterUsage.cs
The `RegisterUsage` pass, which computes all registers consumed (inputs) and modified (outputs) by a shader function, was not accounting for the fact that some operations can produce multiple results. One example of such operations is any texture operation, which can read up to 4 colour component values (RGBA). Because it was only accounting for the first one, only R (red) would be actually considered modified by the function.
Fixes red tint on "THE NEW DENPA MEN" (still needs ignore missing services).
Before:
After:
Fixes #7126.
=> Fix shader RegisterUsage pass only taking first operation dest into account

src/Ryujinx.UI.Common/App/ApplicationLibrary.cs
There is actually one person that managed to crash in `TryGetApplicationsFromFile()` even after the latest fix, so I guess we didn't actually catch every exception yet (https://github.com/Ryujinx/Ryujinx/pull/7046#issuecomment-2237597083).
This PR fixes the `FileNotFoundException` that occurs if we try to get the length of a directory or a non-existent file.
Additionally the log with that crash also showed that Ryujinx was trying to load games in a `.git` subdirectory, which is not ideal.
This was also addressed here, by using `EnumerationOptions` instead of `SearchOptions` for `Directory.EnumerateFiles()`.
The default options already exclude hidden and system files/dirs, so I only needed to adjust the remaining properties with the values from the old `SearchOptions`.
---
Log from the …
=> Fix FileNotFoundException in TryGetApplicationsFromFile() and improve loading applications

src/Ryujinx.Graphics.Device/DeviceMemoryManager.cs, src/Ryujinx.Graphics.Gpu/Engine/InlineToMemory/InlineToMemoryClass.cs, src/Ryujinx.Graphics.Gpu/Image/Texture.cs, src/Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs, src/Ryujinx.Graphics.Gpu/Memory/PhysicalMemory.cs, src/Ryujinx.Graphics.OpenGL/Image/FormatConverter.cs, src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs, src/Ryujinx.Graphics.Texture/BCnDecoder.cs, src/Ryujinx.Graphics.Texture/BCnEncoder.cs, src/Ryujinx.Graphics.Texture/ETC2Decoder.cs, src/Ryujinx.Graphics.Texture/LayoutConverter.cs, src/Ryujinx.Graphics.Texture/PixelConverter.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs
Replaces use of `ByteMemoryPool` with `MemoryOwner<byte>`. These are both wrappers to the standard `ArrayPool` so there should be no functional changes.  Also replaces some uses of `IMemoryOwner<byte>` with `MemoryOwner<byte>` directly, with more of this planned after `ByteMemoryPool` is replaced/removed completely.
=> replace ByteMemoryPool usage in Ryujinx.Graphics

src/Ryujinx.Gtk3/Program.cs, src/Ryujinx.Gtk3/UI/MainWindow.cs, src/Ryujinx.UI.Common/App/ApplicationLibrary.cs, src/Ryujinx/UI/Windows/MainWindow.axaml.cs
Thanks to @Tartifless and @frafes for discussing the issue and providing information in #7077! Due to these comments I got an idea what the issue could be about.
Although I wasn't able to reproduce this issue myself, I'm pretty sure I figured out what's causing it.
While launching Ryujinx the game directories will be scanned for applications regardless whether an application gets launched directly from the command line.
This happens in a separate thread and will be started just before we check if an application was launched from the command line.
When an application gets launched we update the `LastPlayed` field in `metadata.json` to the current time.
And while we load applications we perform migration tasks and update the `Title` field in `metadata.json`.
So my theory is that …
=> Avoid race conditions while launching games directly from the command line

Directory.Packages.props, src/Ryujinx/UI/ViewModels/UserProfileViewModel.cs
Supersedes #7034.
Ava had a weird dependency on a random static helper method from an implicitly installed package from `Microsoft.IdentityModel.JsonWebTokens` which was removed in 8.0.0, causing the dependabot PR to fail.
=> Infra: Update Microsoft.IdentityModel.JsonWebTokens

src/Ryujinx/Common/Locale/LocaleExtension.cs, src/Ryujinx/Common/Locale/LocaleManager.cs
`LocaleExtension` currently uses `CompiledBindingPathBuilder.SetRawSource()`, which while public wasn't really meant to be used, and isn't even generated at all by the Avalonia XAML compiler.
In Avalonia 11.1, `SetRawSource()` won't do anything - see https://github.com/AvaloniaUI/Avalonia/issues/16430#issuecomment-2254462844 
This PR replaces it with `Binding.Source`, which is the supported way and works in all versions.
Additionally, I noticed that changing the language was abnormally slow (there's a noticeable UI freeze).
`OnPropertyChanged("Item")` is triggered for every item set in `LocaleManager.LoadLanguage()`, which forces all localization bindings in the application to refresh every time. Said another way, the operation is currently O(N²). This PR now raises `PropertyChanged` only …
=> Fix LocaleExtension SetRawSource usages + language perf improvement

src/Ryujinx.Memory/Range/IMultiRangeItem.cs, src/Ryujinx.Memory/Range/MemoryRange.cs, src/Ryujinx.Memory/Range/MultiRangeList.cs
When we get the address to find overlaps for a texture with unmapped start, we use the address of the first region that is mapped. This is done because otherwise, *all* textures with unmapped start would be considered a same address overlap (which is bad for performance if the game has a lot of them). The problem is that `IMultiRangeItem.BaseAddress` was not doing the same, so it would return the special all bits one value that is used for unmapped regions, and the `MultiRangeList<T>.FindOverlaps` check `if (output[i].BaseAddress == baseAddress)` would consider them different. The end result is that every time it tries to find a texture with unmapped start, it would not be able to find an exact match and would create a new view.
A side effect of the problem above is that an exception …
=> Fix same textures with unmapped start being considered different

src/Ryujinx.Graphics.GAL/TextureCreateInfo.cs, src/Ryujinx.Graphics.Gpu/Image/TexturePool.cs, src/Ryujinx.Graphics.OpenGL/Image/TextureStorage.cs, src/Ryujinx.Graphics.OpenGL/Image/TextureView.cs
This is basically the same as #2808, but now applies to all backends instead of just OpenGL.
I found that the AMD driver crashes when the mipmap levels is invalid on Vulkan (at least on Windows with the proprietary driver), so this change fixes the crashes when using  those mods.
Since we'd need to do the clamping logic on all backends, I just moved it to the GPU project instead (it also does not make sense to load/decode/send data for the additional levels that are not going to be used).
=> Clamp amount of mipmap levels to max allowed for all backends

src/Ryujinx.Graphics.Gpu/Image/TextureBindingsArrayCache.cs, src/Ryujinx.Graphics.Vulkan/ImageArray.cs, src/Ryujinx.Graphics.Vulkan/ResourceArray.cs, src/Ryujinx.Graphics.Vulkan/TextureArray.cs
Storage images does not use a sampler, so we pass a null sampler pool for those. However, some functions did not expect to receive a null sampler pool. This changes updates those functions to work with null sampler pool. This also fixes an issue on the Vulkan backend where image arrays bindings would not be dirtied if one of the image array textures change.
This fixes a crash on World of Goo 2, but the game still does not work due to a corrupt compute shader.
=> Fix NRE when using image array from constant buffer

src/ARMeilleure/Translation/TranslatorQueue.cs
TryDequeue checks for _disposed before taking the lock.  If another thread calls Dispose before it takes the lock, it won't get woken up by the PulseAll call, and will deadlock in Monitor.Wait.
Double-checking _disposed with the lock taken should avoid this.
Various users have been reporting deadlocks in testing when building from nix: https://github.com/NixOS/nixpkgs/issues/325857
This seems to happen more when the system is under load.  I was able to reproduce it by calling `dotnet test` in a loop while running artificial load.
When it deadlocks, the relevant thread stacks are:
```
~~~~ 2c67f2
1 System.Threading.Thread.Join()
1 ARMeilleure.Translation.Translator.Execute(ExecutionContext, UInt64)
1 Ryujinx.Tests.Cpu.CpuTest.ExecuteOpcodes(Boolean)
1 …
```
=> Fix deadlock in background translation thread shutdown

Directory.Packages.props, src/Ryujinx.Gtk3/Program.cs, src/Ryujinx.Gtk3/Ryujinx.Gtk3.csproj, src/Ryujinx.Gtk3/UI/RendererWidgetBase.cs, src/Ryujinx.Gtk3/UI/Windows/AvatarWindow.cs, src/Ryujinx.Gtk3/UI/Windows/UserProfilesManagerWindow.cs, src/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRenderer.cs, src/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRendererBase.cs, src/Ryujinx.HLE/HOS/Services/Caps/CaptureManager.cs, src/Ryujinx.HLE/Ryujinx.HLE.csproj, src/Ryujinx.UI.Common/Helper/ShortcutHelper.cs, src/Ryujinx/UI/Applet/AvaloniaDynamicTextInputHandler.cs, src/Ryujinx/UI/Helpers/OffscreenTextBox.cs, src/Ryujinx/UI/Windows/MainWindow.axaml
Use Skiasharp for image processing. ImageSharp is replaced because;
1. Their tendencies to change license on a whim
2. ImageSharp isn't fully AOT compatible
3. Why have 2 image processing libraries when 1 is enough.
There isn't any real performance gain of using Skiasharp. This is mainly to add Native AOT support to the Avalonia UI project.
Also fixed text input bugs in the avalonia ui handler for inline keyboard applet. Recent changes in avalonia requires textboxes to be rendered at least once before they handle key events. Previously, BackSpace, Delete and the direction weren't working on the avalonia side due to this.
=> Replace ImageSharp with SkiaSharp everywhere

Directory.Packages.props, src/Ryujinx.Graphics.Vulkan/BufferHolder.cs, src/Ryujinx.Graphics.Vulkan/BufferManager.cs, src/Ryujinx.Graphics.Vulkan/BufferState.cs, src/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetCollection.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetManager.cs, src/Ryujinx.Graphics.Vulkan/FramebufferParams.cs, src/Ryujinx.Graphics.Vulkan/HostMemoryAllocator.cs, src/Ryujinx.Graphics.Vulkan/MemoryAllocatorBlockList.cs, src/Ryujinx.Graphics.Vulkan/MoltenVK/MVKInitialization.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/PipelineConverter.cs, src/Ryujinx.Graphics.Vulkan/PipelineLayoutFactory.cs, src/Ryujinx.Graphics.Vulkan/Queries/BufferedQuery.cs, src/Ryujinx.Graphics.Vulkan/RenderPassHolder.cs, src/Ryujinx.Graphics.Vulkan/SamplerHolder.cs, src/Ryujinx.Graphics.Vulkan/Shader.cs, src/Ryujinx.Graphics.Vulkan/TextureCopy.cs, src/Ryujinx.Graphics.Vulkan/TextureStorage.cs, src/Ryujinx.Graphics.Vulkan/TextureView.cs, src/Ryujinx.Graphics.Vulkan/Vendor.cs, src/Ryujinx.Graphics.Vulkan/Window.cs, src/Ryujinx.Gtk3/Program.cs, src/Ryujinx.Headless.SDL2/Program.cs, src/Ryujinx/Program.cs
Allows use of newer extensions and Vulkan features. We avoided upgrading due to some incompatibilities with how we bundled MoltenVK with the emulator, but I've found a way to work around it for now. We should figure out a way to use the Vulkan loader if we update MVK (needs bounds checks for atomic image storage, and spec compliant occlusion queries).
- Adds MVK linking workaround.
- Resolves warnings caused by a lot of fields changing from `in` to `readonly ref`.
=> Vulkan: Update Silk.NET to 2.21

src/Ryujinx.Graphics.Gpu/Engine/Threed/ThreedClassState.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCache.cs
The official documentation indicates that there is no 3D bit for depth texture. Before, it was ignoring one bit located next to the depth value (which was causing the texture to have an incorrect size) and using an inexistent bit as the bit that indicates the texture is 3D.
Fixes a crash in Neverwinter Nights: Enhanced Edition.
Lighting is broken, seems to be the same problem as a few other OpenGL games where the depth attachment is never cleared.
=> Fix incorrect depth texture 3D flag

src/Ryujinx.Common/GraphicsDriver/DriverUtilities.cs, src/Ryujinx.Common/Utilities/OsUtils.cs, src/Ryujinx.Graphics.Vulkan/BarrierBatch.cs, src/Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs, src/Ryujinx.Graphics.Vulkan/FeedbackLoopAspects.cs, src/Ryujinx.Graphics.Vulkan/FramebufferParams.cs, src/Ryujinx.Graphics.Vulkan/HardwareCapabilities.cs, src/Ryujinx.Graphics.Vulkan/PipelineBase.cs, src/Ryujinx.Graphics.Vulkan/PipelineDynamicState.cs, src/Ryujinx.Graphics.Vulkan/PipelineFull.cs, src/Ryujinx.Graphics.Vulkan/PipelineState.cs, src/Ryujinx.Graphics.Vulkan/TextureStorage.cs, src/Ryujinx.Graphics.Vulkan/TextureView.cs, src/Ryujinx.Graphics.Vulkan/VulkanInitialization.cs, src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs, src/Ryujinx.Gtk3/Program.cs, src/Ryujinx.Headless.SDL2/Program.cs, src/Ryujinx/Program.cs
This PR allows the Vulkan backend to detect attachment feedback loops. These are currently used in the following ways:
- Partial use of VK_EXT_attachment_feedback_loop_layout
- All renderable textures have AttachmentFeedbackLoopBitExt
- Compile pipelines with Color/DepthStencil feedback loop flags when present
- Support using FragmentBarrier for feedback loops (fixes regressions from https://github.com/Ryujinx/Ryujinx/pull/7012 )
Generally trying to fix issues with RDNA3 GPUs, but I don't have one so it's more of a wild guess.
Feedback loops are very poorly considered by Vulkan and its validation layers, and the addition of the `VK_EXT_attachment_feedback_loop_layout` extension hasn't really helped much. Original specification for Vulkan prohibited attachment feedback loops entirely, …
=> Vulkan: Feedback loop detection and barriers

src/ARMeilleure/Decoders/OpCodeTable.cs, src/ARMeilleure/Instructions/InstEmitAlu32.cs, src/ARMeilleure/Instructions/InstEmitSimdShift32.cs, src/ARMeilleure/Instructions/InstName.cs, src/Ryujinx.Tests/Cpu/CpuTestAlu32.cs, src/Ryujinx.Tests/Cpu/CpuTestSimd32.cs
Implements the VSHLL (A2 encoding, A1 was already implemented) and QADD16 32-bit Arm instructions.
This is required by "The Legend of Sword and Fairy".
Fixes #7295.
=> Implement Arm32 VSHLL and QADD16 instructions

src/ARMeilleure/Translation/DelegateInfo.cs, src/ARMeilleure/Translation/Delegates.cs
Little change to make ARMeilleure AOT safe. Using `Delegate` as return type for `GetFunctionPointerForDelegate` is not supported in AOT mode, as the compiler can't tell what type the actual delegate is. So we instead use the real type and save the function pointer.
=> Make GetFunctionPointerForDelegate as explicit as possible

src/Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs, src/Ryujinx.Graphics.Gpu/Image/TextureCache.cs
This change allows DMA copies between two textures to happen in the GPU in some cases.
This generally has a performance advantage, even if the destination data will be accessed in the CPU In the future, first because we don't need to block GPU processing and wait until the flush is complete, and second because we don't need to pay the cost of linear to block linear followed by block linear to linear conversion (which would also happen on CPU).
This gives a massive performance improvement on Castlevania Dominus Collection (more than 2x faster on my machine).
Before:
https://github.com/user-attachments/assets/2fac1261-64e5-4e19-89eb-664cd5057d1c
After:
https://github.com/user-attachments/assets/6333daa4-670f-4769-a931-8c7ba00184e0
This will need to be tested extensively to ensure there are …
=> Implement fast DMA texture to texture copy

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Instructions/InstEmitMemory.cs
This implements the `atomicExchange` shader operation, which was missing for some reason. The other operations were re-ordered to follow the enum order. Also added a log message to warn when a operation is invalid/unsupported. The only operations missing now are increment, decrement and "safe add".
Fixes missing reflections on Lollipop Chainsaw RePOP.
Before:
After:
=> Implement support for shader ATOM.EXCH instruction

src/Ryujinx.Graphics.GAL/ITexture.cs, src/Ryujinx.Graphics.GAL/Multithreading/Commands/Texture/TextureSetDataCommand.cs, src/Ryujinx.Graphics.GAL/Multithreading/Commands/Texture/TextureSetDataSliceCommand.cs, src/Ryujinx.Graphics.GAL/Multithreading/Commands/Texture/TextureSetDataSliceRegionCommand.cs, src/Ryujinx.Graphics.GAL/Multithreading/Resources/ThreadedTexture.cs, src/Ryujinx.Graphics.Gpu/Engine/Dma/DmaClass.cs, src/Ryujinx.Graphics.Gpu/Image/Texture.cs, src/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs, src/Ryujinx.Graphics.OpenGL/Image/TextureBuffer.cs, src/Ryujinx.Graphics.OpenGL/Image/TextureView.cs, src/Ryujinx.Graphics.Vulkan/TextureBuffer.cs, src/Ryujinx.Graphics.Vulkan/TextureView.cs, src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/Parcel.cs, src/Ryujinx.Memory/WritableRegion.cs
Replaces cases where `MemoryOwner<byte>` is passed/returned as `IMemoryOwner<byte>`.
Also, changes locations that were getting a `Span<byte>` to the memory via `MemoryOwner<byte>.Memory.Span` to use `MemoryOwner<byte>.Span` directly, which is cleaner and more efficient.
=> Replace passing by IMemoryOwner<byte> with passing by concrete MemoryOwner<byte>

src/Ryujinx.Graphics.Gpu/Image/Sampler.cs, src/Ryujinx.Graphics.Gpu/Image/SamplerDescriptor.cs, src/Ryujinx.Graphics.Gpu/Image/TextureBindingsManager.cs, src/Ryujinx.Graphics.Gpu/Image/TexturePool.cs
This builds on the support added on #7311 for creating views aliases of a texture pool entry to implement the sRGB bit on samplers. When this bit is set to zero, the texture format is not sRGB. In other words, for a texture to be sRGB, both t he sampler and the texture must have their respective sRGB bits set to 1.
This fixes the image being too dark on Sphin and the Cursed Mummy and Charge Kid.
Before:
After:
Other OpenGL games might be affected (not Tomb Raider, I already tested). NVN games should not be affected since they always set the sRGB bit to 1 in the sampler.
=> Add support for sampler sRGB disable

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Translation/Optimizations/Utils.cs
When all sources but one of a phi operation are undefined, we can assume that the one that is not undefined is the right one, when looking for handles or global memory addresses. This assumption is valid as long the shader is not accessing uninitialized registers, but if it does I beleive the behaviour would be unpredictable anyway.
This fixes some bindless elimination failures in Romancing Saga 2 demo.
Before:
After:
=> Shader: Assume the only remaining source is the right one when all others are undefined

src/Ryujinx.Graphics.Vulkan/PipelineBase.cs
This fixes a bug where topology conversion would not be done for unsupported topologies after a `DrawTexture` operation, until `SetPrimitiveType` is called again. This happens because the internal `_topology` field is not restored, so the draw function does now know that the topology is unsupported anymore.
Fixes rendering on FUZE4 when using Vulkan.
Before:
After:
Might fix similar issues in other games, but this is a rare combination.
=> Fix quads draws after DrawTexture on Vulkan

src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs, src/Ryujinx.Graphics.Shader/Translation/Translator.cs
Fixes an issue with some AMD GPUs and drivers where uninitialized clip distance seemingly contained random values instead of 0, either resulting in geometry not drawing at all or seemingly clipping against nothing.
In future, we could limit the size of the clip distances array to the highest index of clip distance that is used, and only have to initialize up to that. For now, this works.
=> GPU: Ensure all clip distances are initialized when used

src/Ryujinx.SDL2.Common/SDL2Driver.cs
Ryujinx was not hinting application name, so on some platforms (e.g. Linux) volume control shows Ryujinx as 'SDL Application'. This can cause confusion.
This commit fixes name in volume control applets on some platforms.
see: https://wiki.libsdl.org/SDL2/SDL_HINT_APP_NAME
```diff
$ wpctl status > /tmp/before.txt
$ # After this patch
$ wpctl status > /tmp/after.txt
$ diff -u /tmp/before.txt /tmp/after.txt
-        83. SDL Application                                            
-             86. output_FR       > Generic Analog:playback_FR	[active]
-             87. output_FL       > Generic Analog:playback_FL	[active]
+        83. Ryujinx                                                    
+             86. output_FR       > Generic Analog:playback_FR	[active]
+             87. output_FL …
```
=> sdl: set app name

src/Ryujinx.Graphics.Gpu/Shader/ShaderSpecializationState.cs
If the shader does not use textures, we don't need to try creating a texture pool when checking if a shader in the cache matches. This was causing a crash on some games when they were loaded with a shader cache because the texture pool might not exist yet.
Fixes #7192.
Fixes #7378.
=> Do not try to create a texture pool if shader does not use textures

src/Ryujinx.Audio/Renderer/Dsp/Command/CompressorCommand.cs, src/Ryujinx.Audio/Renderer/Dsp/Command/LimiterCommandVersion1.cs, src/Ryujinx.Audio/Renderer/Dsp/Command/LimiterCommandVersion2.cs, src/Ryujinx.Audio/Renderer/Parameter/Effect/CompressorParameter.cs, src/Ryujinx.Audio/Renderer/Parameter/Effect/CompressorStatistics.cs, src/Ryujinx.Audio/Renderer/Parameter/ISplitterDestinationInParameter.cs, src/Ryujinx.Audio/Renderer/Parameter/SplitterDestinationInParameterVersion1.cs, src/Ryujinx.Audio/Renderer/Parameter/SplitterDestinationInParameterVersion2.cs, src/Ryujinx.Audio/Renderer/Server/BehaviourContext.cs, src/Ryujinx.Audio/Renderer/Server/CommandBuffer.cs, src/Ryujinx.Audio/Renderer/Server/CommandGenerator.cs, src/Ryujinx.Audio/Renderer/Server/CommandProcessingTimeEstimatorVersion5.cs, src/Ryujinx.Audio/Renderer/Server/Effect/CompressorEffect.cs, src/Ryujinx.Audio/Renderer/Server/Splitter/SplitterContext.cs, src/Ryujinx.Audio/Renderer/Server/Splitter/SplitterDestination.cs, src/Ryujinx.Audio/Renderer/Server/Splitter/SplitterDestinationVersion1.cs, src/Ryujinx.Audio/Renderer/Server/Splitter/SplitterDestinationVersion2.cs, src/Ryujinx.Horizon/Sdk/Audio/AudioResult.cs, src/Ryujinx.Horizon/Sdk/Audio/Detail/AudioDevice.cs, src/Ryujinx.Tests/Audio/Renderer/Server/BehaviourContextTests.cs
This updates the audio renderer to revision 13, which was added with firmware 18.0.0.
- The compressor effect can now optionally produce "compressor statistics" with some data from the compressor processing.
- The previous mix volumes for splitters now needs to be manually reset by setting a bool to `true` in the parameter, instead of that being done on first use. REV12 and older still keeps the previous behaviour where it resets on first use.
- Two new audio device IPC commands have been added. They just always result the "not implemented" error. I implemented those and the new IPC commands from 17.0.0, which also just returns "not implemented" on the actual firmware.
Allows Trouble Magia to go in-game.
Fixes #7140.
=> Update audio renderer to REV13: Add support for compressor statistics and volume reset
